array(
  array(
    'nid' => '5321',
    'type' => 'fmag_video',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1446724800',
    'changed' => 1457634906,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5321',
    'revision_uid' => '0',
    'title' => 'Video Video - Portrait of Roma Acorn',
    'body' => '<p>VIDEO VIDEO - Portrait of Roma Acorn <br />
	 Exclusive video by Jake Singer. </p>
',
    'teaser' => '<p>VIDEO VIDEO - Portrait of Roma Acorn <br />
	 Exclusive video by Jake Singer. </p>
',
    'revision_timestamp' => '1446724815',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	DIRECTOR<br />
	JAKE SINGER</p>
<p>
	PERFORMER<br />
	ROMA ACORN</p>
<p>
	PHOTOGRAPHER<br />
	LOUIS BOTHA</p>
',
      ),
    ),
    'field_videoembed' => array(
      '0' => array(
        'value' => '<!-- here is the documentation you will need for adding videos --><!--first, you have the embed tag: -->
<p>
	<iframe allowfullscreen="" frameborder="0&amp;" height=" 550" src="http://www.youtube.com/embed/Vomjk-FkRiw?&amp;autoplay=1&amp;amp;rel=0&amp;showinfo=0&amp;modestbranding=1&amp;hd=1&amp;autohide=1&amp;color=white&amp;vq=hd720" width="1000"></iframe><!-- 

--></p>
',
      ),
    ),
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'path' => 'videos/video-video-portrait-roma-acorn',
    'tags' => array(
      '5' => array(
        '3338' => array(
          'tid' => '3338',
          'vid' => '5',
          'name' => 'Louis Botha',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Louis Botha',
      ),
    ),
    'files' => array(
      '40561' => array(
        'fid' => '40561',
        'uid' => '1',
        'filename' => 'Screen Shot 2015-11-04 at 6.51.31 PM.png',
        'filepath' => 'files/Screen Shot 2015-11-04 at 6.51.31 PM_0.png',
        'filemime' => 'image/png',
        'filesize' => '930963',
        'status' => '1',
        'timestamp' => '1446686562',
        'origname' => '',
        'vid' => '5321',
        'description' => 'Screen Shot 2015-11-04 at 6.51.31 PM.png',
        'list' => '1',
        'nid' => '5321',
        'weight' => '0',
      ),
    ),
    'page_title' => '',
    'uuid' => 'cfaa055a-e6ee-11e5-b369-cf2e79d5c249',
    'is_new' => FALSE,
    'timestamp' => 1457634906,
    'xmlsitemap' => array(
      'id' => '5321',
      'type' => 'node',
      'subtype' => 'fmag_video',
      'loc' => 'node/5321',
      'language' => '',
      'access' => TRUE,
      'status' => '0',
      'status_override' => '0',
      'lastmod' => '1457634906',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '0',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5321',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
