array(
  array(
    'nid' => '3471',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1325263468',
    'changed' => '1403838948',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3471',
    'revision_uid' => '1',
    'title' => 'Oo La La',
    'body' => '<p>
	Designer Steven OO knits up a storm.</p>
<p>
	Interview by Heather MacDonald.</p>
<p>
	Exclusive photography by Anna Cone &amp; Christopher Nelson.</p>
<p>
	&nbsp;</p>
',
    'teaser' => '<p>
	Designer Steven OO knits up a storm.</p>
<p>
	Interview by Heather MacDonald.</p>
<p>
	Exclusive photography by Anna Cone &amp; Christopher Nelson.</p>
<p>
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1403838948',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://stevenoo.viewbook.com/" target="_blank">STEVEN OO</a></p>
<p>
	&nbsp;</p>
<p>
	INTERVIEW<br />
	HEATHER MACDONALD</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.annaconephotography.com/" target="_blank">ANNA CONE</a><br />
	&amp; <a href="http://www.christophernelson.net/" target="_blank">CHRISTOPHER NELSON</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	CAROLA REMAR<br />
	@ PHOTGENICS</p>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10559',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-2_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80092',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '10560',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-3_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85397',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '10565',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'oo5_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/oo5_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '62876',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'oo5_SEPT10.jpg',
      ),
      '3' => array(
        'fid' => '10566',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'oo6_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/oo6_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '163688',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'oo6_SEPT10.jpg',
      ),
      '4' => array(
        'fid' => '10660',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'oo7_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/oo7_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '373130',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'oo7_SEPT10.jpg',
      ),
      '5' => array(
        'fid' => '10568',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'oo8_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/oo8_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67646',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'oo8_SEPT10.jpg',
      ),
      '6' => array(
        'fid' => '10569',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'oo9_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/oo9_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78110',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'oo9_SEPT10.jpg',
      ),
      '7' => array(
        'fid' => '10570',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'oo10_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/oo10_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '176198',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'oo10_SEPT10.jpg',
      ),
      '8' => array(
        'fid' => '10571',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'oo11_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/oo11_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '52314',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'oo11_SEPT10.jpg',
      ),
      '9' => array(
        'fid' => '10572',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'oo12_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/oo12_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132828',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'oo12_SEPT10.jpg',
      ),
    ),
    'path' => 'stories/oo-la-la',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2467' => array(
          'tid' => '2467',
          'vid' => '5',
          'name' => 'VIKRAM PATHAK',
          'description' => 'http://www.vikrampathak.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '4' => 'men, women',
        '5' => 'VIKRAM PATHAK',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
