array(
  array(
    'nid' => '3531',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1322329797',
    'changed' => '1337807508',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3531',
    'revision_uid' => '1',
    'title' => 'Troy Smith',
    'body' => '<p>
	Urban Outfitters&#39; D Collection designer Troy Smith.</p>
<p>
	Interview by Heather MacDonald.</p>
<p>
	&nbsp;</p>
',
    'teaser' => '<p>
	Urban Outfitters&#39; D Collection designer Troy Smith.</p>
<p>
	Interview by Heather MacDonald.</p>
<p>
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1337807508',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.troysmithfor-d.com/" target="_blank">TROY SMITH</a></p>
<p>
	&nbsp;</p>
<p>
	INTERVIEW<br />
	HEATHER MACDONALD</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	&amp; ILLUSTRATION<br />
	TROY SMITH</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<a href="http://www.urbanoutfitters.com/urban/catalog/category.jsp?id=M_APP_BRANDS_DCOLLECTION&amp;navAction=jump&amp;navCount=48&amp;popId=&amp;pushId=BRANDS&amp;isSortBy=true" target="_blank">D COLLECTION<br />
	@ URBAN OUTFITTERS</a></p>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11231',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DCONSTRUCTED_2.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/DCONSTRUCTED_2_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102630',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DCONSTRUCTED_2.jpg',
      ),
      '1' => array(
        'fid' => '11232',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DCONSTRUCTED_3.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/DCONSTRUCTED_3_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '35976',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DCONSTRUCTED_3.jpg',
      ),
      '2' => array(
        'fid' => '11233',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DCONSTRUCTED_4.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/DCONSTRUCTED_4_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '164319',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DCONSTRUCTED_4.jpg',
      ),
      '3' => array(
        'fid' => '11234',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DCONSTRUCTED_5.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/DCONSTRUCTED_5_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '142492',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DCONSTRUCTED_5.jpg',
      ),
      '4' => array(
        'fid' => '11235',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DCONSTRUCTED_6.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/DCONSTRUCTED_6_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '168941',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DCONSTRUCTED_6.jpg',
      ),
      '5' => array(
        'fid' => '11236',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DCONSTRUCTED_7.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/DCONSTRUCTED_7_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '191508',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DCONSTRUCTED_7.jpg',
      ),
      '6' => array(
        'fid' => '11237',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DCONSTRUCTED_8.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/DCONSTRUCTED_8_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93498',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DCONSTRUCTED_8.jpg',
      ),
      '7' => array(
        'fid' => '11238',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DCONSTRUCTED_9.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/DCONSTRUCTED_9_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '166931',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DCONSTRUCTED_9.jpg',
      ),
      '8' => array(
        'fid' => '11239',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DCONSTRUCTED_10.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/DCONSTRUCTED_10_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '110999',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DCONSTRUCTED_10.jpg',
      ),
      '9' => array(
        'fid' => '11240',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DCONSTRUCTED_11.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/DCONSTRUCTED_11_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '157330',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DCONSTRUCTED_11.jpg',
      ),
    ),
    'path' => 'stories/troy-smith',
    'tags' => array(
      '5' => array(
        '2416' => array(
          'tid' => '2416',
          'vid' => '5',
          'name' => 'Sean Watters',
          'description' => 'http://www.seanpwatters.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '167' => array(
          'tid' => '167',
          'vid' => '1',
          'name' => 'Urban Outfitters',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'Sean Watters',
        '1' => 'Urban Outfitters',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
