array(
  array(
    'nid' => '3562',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1293908384',
    'changed' => '1403919362',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3562',
    'revision_uid' => '1',
    'title' => 'Vivid',
    'body' => '<p>
	Brighten up.</p>
<p>
	Exclusive photography by <a href="http://www.wendyhopephotography.com/" target="_blank">WENDY HOPE</a>.</p>
<p>
	Models ~&nbsp; Celia Becker @ Muse &amp; Victoria Brito @ Major.</p>
',
    'teaser' => '<p>
	Brighten up.</p>
<p>
	Exclusive photography by <a href="http://www.wendyhopephotography.com/" target="_blank">WENDY HOPE</a>.</p>
<p>
	Models ~&nbsp; Celia Becker @ Muse &amp; Victoria Brito @ Major.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919362',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.wendyhopephotography.com/" target="_blank">WENDY HOPE</a></p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	MENGLY H</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODELS<br />
	CELIA BECKER<br />
	@MUSE<br />
	VICTORIA BRITO<br />
	@ MAJOR</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		BETSEY JOHNSON</li>
	<li>
		Z SPOKE BY ZAC POSEN</li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11596',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-2_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72937',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '11579',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-5_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141339',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '2' => array(
        'fid' => '11580',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-6_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61342',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '3' => array(
        'fid' => '11581',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-7_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '23085',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '4' => array(
        'fid' => '11582',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-8_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86187',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '5' => array(
        'fid' => '11583',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-9_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '6' => array(
        'fid' => '11584',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-10_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '7' => array(
        'fid' => '11585',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-11_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102816',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '8' => array(
        'fid' => '11586',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-12_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18043',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '9' => array(
        'fid' => '11587',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-13_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63548',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '10' => array(
        'fid' => '11588',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-14_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116723',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '11' => array(
        'fid' => '11589',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-15_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20524',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '12' => array(
        'fid' => '11590',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-16_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '13' => array(
        'fid' => '11591',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-17_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '171222',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
    ),
    'path' => 'stories/vivid',
    'tags' => array(
      '1' => array(
        '135' => array(
          'tid' => '135',
          'vid' => '1',
          'name' => 'BETSEY JOHNSON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '136' => array(
          'tid' => '136',
          'vid' => '1',
          'name' => 'ZAC POSEN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2605' => array(
          'tid' => '2605',
          'vid' => '5',
          'name' => 'WENDY HOPE',
          'description' => 'http://www.wendyhopephotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'BETSEY JOHNSON, ZAC POSEN',
        '5' => 'WENDY HOPE',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
