array(
  array(
    'nid' => '3566',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1294274244',
    'changed' => '1403919164',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3566',
    'revision_uid' => '1',
    'title' => 'Hair Cut',
    'body' => '<p>
	Are you getting snippy?</p>
<p>
	Exclusive photography by&nbsp;<a href="http://www.zenaidakwong.com/" target="_blank">ZENAIDA KWONG</a>.</p>
<p>
	Model ~&nbsp; Kaz P @ Nobasura.</p>
',
    'teaser' => '<p>
	Are you getting snippy?</p>
<p>
	Exclusive photography by&nbsp;<a href="http://www.zenaidakwong.com/" target="_blank">ZENAIDA KWONG</a>.</p>
<p>
	Model ~&nbsp; Kaz P @ Nobasura.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919164',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.zenaidakwong.com/" target="_blank">ZENAIDA KWONG</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	STYLING<br />
	<a href="http://www.lizbellagency.com/artists/908.htm" target="_blank">DEANNA PALKOWSKI</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	KAZ @ NOBASURA</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		A LIFE</li>
	<li>
		HOLT RENFREW</li>
	<li>
		NOUVELLE NOUVELLE</li>
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11619',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90243',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '11634',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-3_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86190',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '11802',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-4_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29047',
        'status' => '1',
        'timestamp' => '1295044323',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '11622',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123373',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '11623',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101818',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '11803',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '25283',
        'status' => '1',
        'timestamp' => '1295044342',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '11808',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1295044958',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '11626',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74503',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '11627',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86955',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '11809',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-11_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22448',
        'status' => '1',
        'timestamp' => '1295045042',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '11810',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19314',
        'status' => '1',
        'timestamp' => '1295045158',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '11630',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80679',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '11807',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-14_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88463',
        'status' => '1',
        'timestamp' => '1295044385',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '11632',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13416',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
    ),
    'path' => 'stories/hair-cut',
    'tags' => array(
      '1' => array(
        '122' => array(
          'tid' => '122',
          'vid' => '1',
          'name' => 'A LIFE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '123' => array(
          'tid' => '123',
          'vid' => '1',
          'name' => 'HOLT RENFREW',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '124' => array(
          'tid' => '124',
          'vid' => '1',
          'name' => 'NOUVELLE NOUVELLE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2571' => array(
          'tid' => '2571',
          'vid' => '5',
          'name' => 'ZENAIDA KWONG',
          'description' => 'http://www.zenaidakwong.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'A LIFE, HOLT RENFREW, NOUVELLE NOUVELLE',
        '4' => 'men',
        '5' => 'ZENAIDA KWONG',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
