array(
  array(
    'nid' => '3570',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1294673573',
    'changed' => '1403918098',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3570',
    'revision_uid' => '1',
    'title' => 'Split Decision',
    'body' => '<p>
	One extreme to the other.</p>
<p>
	Exclusive photography by <a href="http://www.lindsayadlerphotography.com/" target="_blank">LINDSAY ADLER</a>.</p>
<p>
	Model ~ Agata @ Q.</p>
',
    'teaser' => '<p>
	One extreme to the other.</p>
<p>
	Exclusive photography by <a href="http://www.lindsayadlerphotography.com/" target="_blank">LINDSAY ADLER</a>.</p>
<p>
	Model ~ Agata @ Q.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918098',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.lindsayadlerphotography.com/" target="_blank">LINDSAY ADLER</a></p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	LSC</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	AGATA @ Q</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		CHARLES HENRY</li>
	<li>
		MAYA LUZ</li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11696',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138696',
        'status' => '1',
        'timestamp' => '1294241390',
        'origname' => 'split_JAN2011.jpg',
      ),
      '1' => array(
        'fid' => '11698',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split2_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split2_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88525',
        'status' => '1',
        'timestamp' => '1294241405',
        'origname' => 'split2_JAN2011.jpg',
      ),
      '2' => array(
        'fid' => '11700',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split3_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split3_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82125',
        'status' => '1',
        'timestamp' => '1294241413',
        'origname' => 'split3_JAN2011.jpg',
      ),
      '3' => array(
        'fid' => '11702',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split4_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split4_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '27201',
        'status' => '1',
        'timestamp' => '1294241423',
        'origname' => 'split4_JAN2011.jpg',
      ),
      '4' => array(
        'fid' => '11703',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split5_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split5_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '26674',
        'status' => '1',
        'timestamp' => '1294241431',
        'origname' => 'split5_JAN2011.jpg',
      ),
      '5' => array(
        'fid' => '11704',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split6_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split6_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '64677',
        'status' => '1',
        'timestamp' => '1294241441',
        'origname' => 'split6_JAN2011.jpg',
      ),
      '6' => array(
        'fid' => '11705',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split7_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split7_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '56298',
        'status' => '1',
        'timestamp' => '1294241455',
        'origname' => 'split7_JAN2011.jpg',
      ),
      '7' => array(
        'fid' => '11706',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split8_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split8_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22262',
        'status' => '1',
        'timestamp' => '1294241470',
        'origname' => 'split8_JAN2011.jpg',
      ),
      '8' => array(
        'fid' => '11707',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split9_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split9_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '1294241485',
        'origname' => 'split9_JAN2011.jpg',
      ),
      '9' => array(
        'fid' => '11708',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split10_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split10_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96462',
        'status' => '1',
        'timestamp' => '1294241503',
        'origname' => 'split10_JAN2011.jpg',
      ),
      '10' => array(
        'fid' => '11709',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split11_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split11_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84056',
        'status' => '1',
        'timestamp' => '1294241515',
        'origname' => 'split11_JAN2011.jpg',
      ),
      '11' => array(
        'fid' => '11711',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split12_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split12_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '151975',
        'status' => '1',
        'timestamp' => '1294241527',
        'origname' => 'split12_JAN2011.jpg',
      ),
      '12' => array(
        'fid' => '11713',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split13_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split13_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19558',
        'status' => '1',
        'timestamp' => '1294241536',
        'origname' => 'split13_JAN2011.jpg',
      ),
      '13' => array(
        'fid' => '11715',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split14_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split14_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113998',
        'status' => '1',
        'timestamp' => '1294241546',
        'origname' => 'split14_JAN2011.jpg',
      ),
      '14' => array(
        'fid' => '11717',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split15_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split15_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72064',
        'status' => '1',
        'timestamp' => '1294241553',
        'origname' => 'split15_JAN2011.jpg',
      ),
      '15' => array(
        'fid' => '11718',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'split16_JAN2011.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/split16_JAN2011.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '115819',
        'status' => '1',
        'timestamp' => '1294241561',
        'origname' => 'split16_JAN2011.jpg',
      ),
    ),
    'path' => 'stories/split-decision',
    'tags' => array(
      '1' => array(
        '133' => array(
          'tid' => '133',
          'vid' => '1',
          'name' => 'CHARLES HENRY',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '134' => array(
          'tid' => '134',
          'vid' => '1',
          'name' => 'MAYA LUZ',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2606' => array(
          'tid' => '2606',
          'vid' => '5',
          'name' => 'LINDSAY ADLER',
          'description' => 'http://www.lindsayadlerphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'CHARLES HENRY, MAYA LUZ',
        '5' => 'LINDSAY ADLER',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
