array(
  array(
    'nid' => '3571',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1294407380',
    'changed' => '1403917834',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3571',
    'revision_uid' => '1',
    'title' => 'Fuse',
    'body' => '<p>
	Formal more... or... less.</p>
<p>
	Exclusive photography by <a href="http://www.skphotography.ca/" target="_blank">SOPHIE KINACHTCHOUK</a>.</p>
<p>
	Model ~ Jesse Carter @ Adam.</p>
',
    'teaser' => '<p>
	Formal more... or... less.</p>
<p>
	Exclusive photography by <a href="http://www.skphotography.ca/" target="_blank">SOPHIE KINACHTCHOUK</a>.</p>
<p>
	Model ~ Jesse Carter @ Adam.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917834',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.skphotography.ca/" target="_blank">SOPHIE KINACHTCHOUK</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	FASHION EDITOR<br />
	JAMES N</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	JESSE CARTER<br />
	@ ADAM</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		RELIGION</li>
	<li>
		SUIT</li>
	<li>
		ELEVEN PARIS</li>
	<li>
		ELVIS JESUS</li>
	<li>
		BLUE BLOOD</li>
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11720',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73654',
        'status' => '1',
        'timestamp' => '1294407171',
        'origname' => 'fuse_JAN11.jpg',
      ),
      '1' => array(
        'fid' => '11748',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82553',
        'status' => '1',
        'timestamp' => '1294408401',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '11724',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse3_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse3_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17661',
        'status' => '1',
        'timestamp' => '1294407190',
        'origname' => 'fuse3_JAN11.jpg',
      ),
      '3' => array(
        'fid' => '11726',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse4_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse4_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75573',
        'status' => '1',
        'timestamp' => '1294407212',
        'origname' => 'fuse4_JAN11.jpg',
      ),
      '4' => array(
        'fid' => '11728',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse5_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse5_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1294407228',
        'origname' => 'fuse5_JAN11.jpg',
      ),
      '5' => array(
        'fid' => '11730',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse6_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse6_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '147913',
        'status' => '1',
        'timestamp' => '1294407240',
        'origname' => 'fuse6_JAN11.jpg',
      ),
      '6' => array(
        'fid' => '11732',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse7_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse7_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '232187',
        'status' => '1',
        'timestamp' => '1294407254',
        'origname' => 'fuse7_JAN11.jpg',
      ),
      '7' => array(
        'fid' => '11734',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse8_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse8_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15568',
        'status' => '1',
        'timestamp' => '1294407264',
        'origname' => 'fuse8_JAN11.jpg',
      ),
      '8' => array(
        'fid' => '11736',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse9_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse9_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65590',
        'status' => '1',
        'timestamp' => '1294407274',
        'origname' => 'fuse9_JAN11.jpg',
      ),
      '9' => array(
        'fid' => '11738',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse10_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse10_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84406',
        'status' => '1',
        'timestamp' => '1294407286',
        'origname' => 'fuse10_JAN11.jpg',
      ),
      '10' => array(
        'fid' => '11740',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse11_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse11_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '105472',
        'status' => '1',
        'timestamp' => '1294407297',
        'origname' => 'fuse11_JAN11.jpg',
      ),
      '11' => array(
        'fid' => '11741',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse12_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse12_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1294407307',
        'origname' => 'fuse12_JAN11.jpg',
      ),
      '12' => array(
        'fid' => '11743',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse13_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse13_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17402',
        'status' => '1',
        'timestamp' => '1294407317',
        'origname' => 'fuse13_JAN11.jpg',
      ),
      '13' => array(
        'fid' => '11745',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse14_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse14_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94024',
        'status' => '1',
        'timestamp' => '1294407334',
        'origname' => 'fuse14_JAN11.jpg',
      ),
      '14' => array(
        'fid' => '11746',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse15_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse15_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82534',
        'status' => '1',
        'timestamp' => '1294407344',
        'origname' => 'fuse15_JAN11.jpg',
      ),
      '15' => array(
        'fid' => '11747',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fuse16_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/fuse16_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97260',
        'status' => '1',
        'timestamp' => '1294407361',
        'origname' => 'fuse16_JAN11.jpg',
      ),
    ),
    'path' => 'stories/fuse',
    'tags' => array(
      '1' => array(
        '125' => array(
          'tid' => '125',
          'vid' => '1',
          'name' => 'Blue Blood',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '128' => array(
          'tid' => '128',
          'vid' => '1',
          'name' => 'Eleven Paris',
          'description' => 'elevenparis.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '131' => array(
          'tid' => '131',
          'vid' => '1',
          'name' => 'ELVIS JESUS',
          'description' => 'elvisjesus.co.uk',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '130' => array(
          'tid' => '130',
          'vid' => '1',
          'name' => 'RELIGION',
          'description' => 'religionclothing.co.uk',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '127' => array(
          'tid' => '127',
          'vid' => '1',
          'name' => 'Suit',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2429' => array(
          'tid' => '2429',
          'vid' => '5',
          'name' => 'Sophie Kinachtchouk',
          'description' => 'http://www.skphotography.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Blue Blood, Eleven Paris, ELVIS JESUS, RELIGION, Suit',
        '4' => 'men',
        '5' => 'Sophie Kinachtchouk',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
