array(
  array(
    'nid' => '3574',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1294777124',
    'changed' => '1403917834',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3574',
    'revision_uid' => '1',
    'title' => 'Private Eye',
    'body' => '<p>
	A noir state of mind.<br />
	Exclusive photography by <a href="http://www.forteandzachary.com/" target="_blank">FORTE+ZACHARY</a>.<br />
	Models ~ Crosby Tailor&nbsp; @ Nous &amp; Martin Rogal @ Red.</p>
',
    'teaser' => '<p>
	A noir state of mind.<br />
	Exclusive photography by <a href="http://www.forteandzachary.com/" target="_blank">FORTE+ZACHARY</a>.<br />
	Models ~ Crosby Tailor&nbsp; @ Nous &amp; Martin Rogal @ Red.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917834',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.forteandzachary.com/" target="_blank">FORTE+ZACHARY</a></p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	CLAUDIA PAOLINELLI</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODELS<br />
	CROSBY TAILOR&nbsp;<br />
	@ NOUS<br />
	MARTIN ROGAL<br />
	@ RED</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		ALFANI</li>
	<li>
		BILLY REID</li>
	<li>
		MICHAEL KORS</li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11752',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '145272',
        'status' => '1',
        'timestamp' => '1294776864',
        'origname' => 'private_JAN11.jpg',
      ),
      '1' => array(
        'fid' => '11753',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private2_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private2_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '69662',
        'status' => '1',
        'timestamp' => '1294776875',
        'origname' => 'private2_JAN11.jpg',
      ),
      '2' => array(
        'fid' => '11755',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private3_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private3_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '181477',
        'status' => '1',
        'timestamp' => '1294776889',
        'origname' => 'private3_JAN11.jpg',
      ),
      '3' => array(
        'fid' => '11756',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private4_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private4_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16748',
        'status' => '1',
        'timestamp' => '1294776897',
        'origname' => 'private4_JAN11.jpg',
      ),
      '4' => array(
        'fid' => '11758',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private5_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private5_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '146114',
        'status' => '1',
        'timestamp' => '1294776913',
        'origname' => 'private5_JAN11.jpg',
      ),
      '5' => array(
        'fid' => '11759',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private6_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private6_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '133188',
        'status' => '1',
        'timestamp' => '1294776925',
        'origname' => 'private6_JAN11.jpg',
      ),
      '6' => array(
        'fid' => '11760',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private7_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private7_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140109',
        'status' => '1',
        'timestamp' => '1294776938',
        'origname' => 'private7_JAN11.jpg',
      ),
      '7' => array(
        'fid' => '11761',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private8_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private8_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '159948',
        'status' => '1',
        'timestamp' => '1294776953',
        'origname' => 'private8_JAN11.jpg',
      ),
      '8' => array(
        'fid' => '11762',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private9_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private9_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91750',
        'status' => '1',
        'timestamp' => '1294776965',
        'origname' => 'private9_JAN11.jpg',
      ),
      '9' => array(
        'fid' => '11763',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private10_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private10_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82741',
        'status' => '1',
        'timestamp' => '1294776981',
        'origname' => 'private10_JAN11.jpg',
      ),
      '10' => array(
        'fid' => '11764',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private11_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private11_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '195013',
        'status' => '1',
        'timestamp' => '1294776993',
        'origname' => 'private11_JAN11.jpg',
      ),
      '11' => array(
        'fid' => '11765',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private12_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private12_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16374',
        'status' => '1',
        'timestamp' => '1294777010',
        'origname' => 'private12_JAN11.jpg',
      ),
      '12' => array(
        'fid' => '11766',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private13_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private13_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '183079',
        'status' => '1',
        'timestamp' => '1294777025',
        'origname' => 'private13_JAN11.jpg',
      ),
      '13' => array(
        'fid' => '11767',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private14_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private14_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '206328',
        'status' => '1',
        'timestamp' => '1294777044',
        'origname' => 'private14_JAN11.jpg',
      ),
      '14' => array(
        'fid' => '11768',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private15_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private15_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16398',
        'status' => '1',
        'timestamp' => '1294777061',
        'origname' => 'private15_JAN11.jpg',
      ),
      '15' => array(
        'fid' => '11770',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private16_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private16_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '143471',
        'status' => '1',
        'timestamp' => '1294777077',
        'origname' => 'private16_JAN11.jpg',
      ),
      '16' => array(
        'fid' => '11771',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private17_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private17_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '231565',
        'status' => '1',
        'timestamp' => '1294777089',
        'origname' => 'private17_JAN11.jpg',
      ),
      '17' => array(
        'fid' => '11772',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'private18_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/private18_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '217840',
        'status' => '1',
        'timestamp' => '1294777109',
        'origname' => 'private18_JAN11.jpg',
      ),
    ),
    'path' => 'stories/private-eye',
    'tags' => array(
      '1' => array(
        '109' => array(
          'tid' => '109',
          'vid' => '1',
          'name' => 'ALFANI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '110' => array(
          'tid' => '110',
          'vid' => '1',
          'name' => 'BILLY REID',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '111' => array(
          'tid' => '111',
          'vid' => '1',
          'name' => 'MICHAEL KORS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2607' => array(
          'tid' => '2607',
          'vid' => '5',
          'name' => 'FORTE+ZACHARY',
          'description' => 'http://www.forteandzachary.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'ALFANI, BILLY REID, MICHAEL KORS',
        '5' => 'FORTE+ZACHARY',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
