array(
  array(
    'nid' => '3576',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1295038338',
    'changed' => '1403918098',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3576',
    'revision_uid' => '1',
    'title' => 'Dress Code',
    'body' => '<p>
	Dress up time.<br />
	Exclusive photography by <a href="http://www.dripbook.com/edwardstgeorge/splash" target="_blank">EDWARD S+GEORGE-ADAMS</a>.<br />
	Model ~ Joslyn Fink @ No Ties.</p>
',
    'teaser' => '<p>
	Dress up time.<br />
	Exclusive photography by <a href="http://www.dripbook.com/edwardstgeorge/splash" target="_blank">EDWARD S+GEORGE-ADAMS</a>.<br />
	Model ~ Joslyn Fink @ No Ties.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918098',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.dripbook.com/edwardstgeorge/splash" target="_blank">EDWARD S+GEORGE-ADAMS</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	JOSLYN FINK<br />
	@ NO TIES<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.espacofashion.6d.com.br/" target="_blank">ESPACO</a></li>
	<li>
		<a href="http://www.loriblu.com/" target="_blank">LORIBLU</a></li>
	<li>
		<a href="http://www.shoppetrozillia.com/" target="_blank">PETRO ZILLIA</a></li>
	<li>
		<a href="http://www.felja.com/" target="_blank">FELJA</a></li>
	<li>
		<a href="http://www.jonano.com/" target="_blank">jonano</a></li>
	<li>
		<a href="http://www.michellemonroestudios.com" target="_blank">Michelle monroe</a></li>
	<li>
		<a href="http://www.milesmcneel.com" target="_blank">miles mcneel</a></li>
	<li>
		<a href="http://www.gypsyglobalchic.com" target="_blank">gypsy</a></li>
</ul>
<p>
	<br />
	&nbsp;</p>
<ul>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11776',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95148',
        'status' => '1',
        'timestamp' => '1295038098',
        'origname' => 'dress_JAN11.jpg',
      ),
      '1' => array(
        'fid' => '11777',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress2_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress2_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102856',
        'status' => '1',
        'timestamp' => '1295038107',
        'origname' => 'dress2_JAN11.jpg',
      ),
      '2' => array(
        'fid' => '11778',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress3_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress3_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '151208',
        'status' => '1',
        'timestamp' => '1295038116',
        'origname' => 'dress3_JAN11.jpg',
      ),
      '3' => array(
        'fid' => '11779',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress4_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress4_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1295038126',
        'origname' => 'dress4_JAN11.jpg',
      ),
      '4' => array(
        'fid' => '11780',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress5_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress5_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15381',
        'status' => '1',
        'timestamp' => '1295038137',
        'origname' => 'dress5_JAN11.jpg',
      ),
      '5' => array(
        'fid' => '11781',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress6_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress6_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107817',
        'status' => '1',
        'timestamp' => '1295038149',
        'origname' => 'dress6_JAN11.jpg',
      ),
      '6' => array(
        'fid' => '11782',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress7_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress7_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96384',
        'status' => '1',
        'timestamp' => '1295038165',
        'origname' => 'dress7_JAN11.jpg',
      ),
      '7' => array(
        'fid' => '11784',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress8_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress8_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16776',
        'status' => '1',
        'timestamp' => '1295038189',
        'origname' => 'dress8_JAN11.jpg',
      ),
      '8' => array(
        'fid' => '11786',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress9_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress9_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11379',
        'status' => '1',
        'timestamp' => '1295038197',
        'origname' => 'dress9_JAN11.jpg',
      ),
      '9' => array(
        'fid' => '11787',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress10_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress10_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '150453',
        'status' => '1',
        'timestamp' => '1295038205',
        'origname' => 'dress10_JAN11.jpg',
      ),
      '10' => array(
        'fid' => '11789',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress11_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress11_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160049',
        'status' => '1',
        'timestamp' => '1295038223',
        'origname' => 'dress11_JAN11.jpg',
      ),
      '11' => array(
        'fid' => '11790',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress12_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress12_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14364',
        'status' => '1',
        'timestamp' => '1295038228',
        'origname' => 'dress12_JAN11.jpg',
      ),
      '12' => array(
        'fid' => '11791',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress13_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress13_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13100',
        'status' => '1',
        'timestamp' => '1295038241',
        'origname' => 'dress13_JAN11.jpg',
      ),
      '13' => array(
        'fid' => '11793',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress14_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress14_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '149003',
        'status' => '1',
        'timestamp' => '1295038257',
        'origname' => 'dress14_JAN11.jpg',
      ),
      '14' => array(
        'fid' => '11794',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress15_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress15_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66885',
        'status' => '1',
        'timestamp' => '1295038265',
        'origname' => 'dress15_JAN11.jpg',
      ),
      '15' => array(
        'fid' => '11795',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress16_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress16_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92653',
        'status' => '1',
        'timestamp' => '1295038275',
        'origname' => 'dress16_JAN11.jpg',
      ),
      '16' => array(
        'fid' => '11796',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress17_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress17_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76048',
        'status' => '1',
        'timestamp' => '1295038284',
        'origname' => 'dress17_JAN11.jpg',
      ),
      '17' => array(
        'fid' => '11797',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress18_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress18_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138939',
        'status' => '1',
        'timestamp' => '1295038297',
        'origname' => 'dress18_JAN11.jpg',
      ),
      '18' => array(
        'fid' => '11798',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress19_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress19_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12901',
        'status' => '1',
        'timestamp' => '1295038307',
        'origname' => 'dress19_JAN11.jpg',
      ),
      '19' => array(
        'fid' => '11799',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dress20_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dress20_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95911',
        'status' => '1',
        'timestamp' => '1295038325',
        'origname' => 'dress20_JAN11.jpg',
      ),
    ),
    'path' => 'stories/dress-code',
    'tags' => array(
      '5' => array(
        '2463' => array(
          'tid' => '2463',
          'vid' => '5',
          'name' => 'EDWARD S+GEORGE-ADAMS',
          'description' => 'http://www.dripbook.com/edwardstgeorge/splash',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '114' => array(
          'tid' => '114',
          'vid' => '1',
          'name' => 'ESPACO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '117' => array(
          'tid' => '117',
          'vid' => '1',
          'name' => 'FELJA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '121' => array(
          'tid' => '121',
          'vid' => '1',
          'name' => 'gypsy',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '118' => array(
          'tid' => '118',
          'vid' => '1',
          'name' => 'jonano',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '115' => array(
          'tid' => '115',
          'vid' => '1',
          'name' => 'LORIBLU',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '119' => array(
          'tid' => '119',
          'vid' => '1',
          'name' => 'Michelle monroe',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '120' => array(
          'tid' => '120',
          'vid' => '1',
          'name' => 'miles mcneel',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '116' => array(
          'tid' => '116',
          'vid' => '1',
          'name' => 'PETRO ZILLIA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'EDWARD S+GEORGE-ADAMS',
        '1' => 'ESPACO, FELJA, gypsy, jonano, LORIBLU, Michelle monroe, miles mcneel, PETRO ZILLIA',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
