array(
  array(
    'nid' => '3581',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1295462553',
    'changed' => '1403918098',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3581',
    'revision_uid' => '1',
    'title' => 'Dragon Dance',
    'body' => '<p>
	Happy Chinese New Year.<br />
	Exclusive photography by <a href="http://www.toddanthonytyler.com/">TODD ANTHONY TYLER</a>.<br />
	Model ~ Raquel.</p>
',
    'teaser' => '<p>
	Happy Chinese New Year.<br />
	Exclusive photography by <a href="http://www.toddanthonytyler.com/">TODD ANTHONY TYLER</a>.<br />
	Model ~ Raquel.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918098',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.toddanthonytyler.com/" target="_blank">TODD ANTHONY TYLER</a></p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	MIA</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	RAQUEL<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		HERVE LEGER</li>
	<li>
		SPORTMAX</li>
	<li>
		JEAN PAUL GAULTIER</li>
	<li>
		PRADA</li>
	<li>
		BADGLEY MISCHKA</li>
</ul>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11884',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2_0.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-2_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '393009',
        'status' => '1',
        'timestamp' => '1295471238',
        'origname' => 'Layout-1_Page-2_0.jpg',
      ),
      '1' => array(
        'fid' => '11882',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-3_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '204016',
        'status' => '1',
        'timestamp' => '1295463811',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '11863',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon3_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon3_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167543',
        'status' => '1',
        'timestamp' => '1295462473',
        'origname' => 'dragon3_JAN11.jpg',
      ),
      '3' => array(
        'fid' => '11864',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon4_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon4_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16748',
        'status' => '1',
        'timestamp' => '1295462482',
        'origname' => 'dragon4_JAN11.jpg',
      ),
      '4' => array(
        'fid' => '11865',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon5_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon5_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11378',
        'status' => '1',
        'timestamp' => '1295462493',
        'origname' => 'dragon5_JAN11.jpg',
      ),
      '5' => array(
        'fid' => '11866',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon6_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon6_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90175',
        'status' => '1',
        'timestamp' => '1295462504',
        'origname' => 'dragon6_JAN11.jpg',
      ),
      '6' => array(
        'fid' => '11867',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon7_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon7_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '270390',
        'status' => '1',
        'timestamp' => '1295462538',
        'origname' => 'dragon7_JAN11.jpg',
      ),
      '7' => array(
        'fid' => '11868',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon8_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon8_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13021',
        'status' => '1',
        'timestamp' => '1295462581',
        'origname' => 'dragon8_JAN11.jpg',
      ),
      '8' => array(
        'fid' => '11869',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon9_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon9_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14763',
        'status' => '1',
        'timestamp' => '1295462593',
        'origname' => 'dragon9_JAN11.jpg',
      ),
      '9' => array(
        'fid' => '11870',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon10_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon10_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '150241',
        'status' => '1',
        'timestamp' => '1295462612',
        'origname' => 'dragon10_JAN11.jpg',
      ),
      '10' => array(
        'fid' => '11871',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon11_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon11_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87126',
        'status' => '1',
        'timestamp' => '1295462629',
        'origname' => 'dragon11_JAN11.jpg',
      ),
      '11' => array(
        'fid' => '11872',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon12_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon12_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108037',
        'status' => '1',
        'timestamp' => '1295462643',
        'origname' => 'dragon12_JAN11.jpg',
      ),
      '12' => array(
        'fid' => '11873',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon13_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon13_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87336',
        'status' => '1',
        'timestamp' => '1295462668',
        'origname' => 'dragon13_JAN11.jpg',
      ),
      '13' => array(
        'fid' => '11874',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon14_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon14_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11378',
        'status' => '1',
        'timestamp' => '1295462681',
        'origname' => 'dragon14_JAN11.jpg',
      ),
      '14' => array(
        'fid' => '11875',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon15_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon15_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12878',
        'status' => '1',
        'timestamp' => '1295462697',
        'origname' => 'dragon15_JAN11.jpg',
      ),
      '15' => array(
        'fid' => '11876',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dragon16_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/dragon16_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '231385',
        'status' => '1',
        'timestamp' => '1295462710',
        'origname' => 'dragon16_JAN11.jpg',
      ),
    ),
    'path' => 'stories/dragon-dance',
    'tags' => array(
      '1' => array(
        '108' => array(
          'tid' => '108',
          'vid' => '1',
          'name' => 'BADGLEY MISCHKA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '104' => array(
          'tid' => '104',
          'vid' => '1',
          'name' => 'HERVE LEGER',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '106' => array(
          'tid' => '106',
          'vid' => '1',
          'name' => 'JEAN PAUL GAULTIER',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '107' => array(
          'tid' => '107',
          'vid' => '1',
          'name' => 'PRADA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '105' => array(
          'tid' => '105',
          'vid' => '1',
          'name' => 'SPORTMAX',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2493' => array(
          'tid' => '2493',
          'vid' => '5',
          'name' => 'Todd ANTHONY TYLER',
          'description' => 'http://www.toddanthonytyler.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'BADGLEY MISCHKA, HERVE LEGER, JEAN PAUL GAULTIER, PRADA, SPORTMAX',
        '5' => 'Todd ANTHONY TYLER',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
