array(
  array(
    'nid' => '3585',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1295976762',
    'changed' => '1337803417',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3585',
    'revision_uid' => '1',
    'title' => 'Casey Skinner',
    'body' => '<p>
	Case study.<br />
	Exclusive photography by Max-Arthur Mantle.</p>
',
    'teaser' => '<p>
	Case study.<br />
	Exclusive photography by Max-Arthur Mantle.</p>
',
    'log' => '',
    'revision_timestamp' => '1337803417',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	CASEY SKINNER</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.blurb.com/user/Maxarthurman#store-price"> MAX-ARTHUR MANTLE</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<a href="http://www.blurb.com/user/Maxarthurman#store-price">THE BOYS &amp; THE BEACH</a></p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11936',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-2_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139161',
        'status' => '1',
        'timestamp' => '1295977301',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '11937',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-3_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141602',
        'status' => '1',
        'timestamp' => '1295977301',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '11949',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-8_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '1295977586',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '3' => array(
        'fid' => '11950',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-9_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107388',
        'status' => '1',
        'timestamp' => '1295977599',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '4' => array(
        'fid' => '11938',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-4_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '164789',
        'status' => '1',
        'timestamp' => '1295977325',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '5' => array(
        'fid' => '11940',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-5_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154763',
        'status' => '1',
        'timestamp' => '1295977351',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '6' => array(
        'fid' => '11941',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-6_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126116',
        'status' => '1',
        'timestamp' => '1295977362',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '7' => array(
        'fid' => '11943',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-7_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154389',
        'status' => '1',
        'timestamp' => '1295977388',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '8' => array(
        'fid' => '11944',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-10_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '233937',
        'status' => '1',
        'timestamp' => '1295977400',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '11945',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-11_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '237144',
        'status' => '1',
        'timestamp' => '1295977419',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '11951',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-12_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '262995',
        'status' => '1',
        'timestamp' => '1295977866',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '11948',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-13_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101722',
        'status' => '1',
        'timestamp' => '1295977448',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/casey-skinner',
    'tags' => array(
      '5' => array(
        '2608' => array(
          'tid' => '2608',
          'vid' => '5',
          'name' => ' SOPHIE KINACHTCHOUK',
          'description' => 'http://www.skphotography.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => ' SOPHIE KINACHTCHOUK',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
