array(
  array(
    'nid' => '3587',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1296069940',
    'changed' => '1403918098',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3587',
    'revision_uid' => '1',
    'title' => 'Kristy',
    'body' => '<p>
	Special K.<br />
	Exclusive photography by Joel Esposito.</p>
',
    'teaser' => '<p>
	Special K.<br />
	Exclusive photography by Joel Esposito.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918098',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	KRISTY<br />
	@ ELMER OLSEN</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.joelesposito.com/">JOEL ESPOSITO</a></p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11967',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-2_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134805',
        'status' => '1',
        'timestamp' => '1296086418',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '11954',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kristy2_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/kristy2_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89900',
        'status' => '1',
        'timestamp' => '1296070152',
        'origname' => 'kristy2_JAN11.jpg',
      ),
      '2' => array(
        'fid' => '11955',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kristy3_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/kristy3_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71958',
        'status' => '1',
        'timestamp' => '1296070163',
        'origname' => 'kristy3_JAN11.jpg',
      ),
      '3' => array(
        'fid' => '11956',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kristy4_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/kristy4_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '51533',
        'status' => '1',
        'timestamp' => '1296070173',
        'origname' => 'kristy4_JAN11.jpg',
      ),
      '4' => array(
        'fid' => '11957',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kristy5_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/kristy5_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101514',
        'status' => '1',
        'timestamp' => '1296071482',
        'origname' => 'kristy5_JAN11.jpg',
      ),
      '5' => array(
        'fid' => '11958',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kristy6_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/kristy6_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71958',
        'status' => '1',
        'timestamp' => '1296071522',
        'origname' => 'kristy6_JAN11.jpg',
      ),
      '6' => array(
        'fid' => '11959',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kristy7_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/kristy7_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65483',
        'status' => '1',
        'timestamp' => '1296071537',
        'origname' => 'kristy7_JAN11.jpg',
      ),
      '7' => array(
        'fid' => '11961',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kristy8_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/kristy8_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71918',
        'status' => '1',
        'timestamp' => '1296071550',
        'origname' => 'kristy8_JAN11.jpg',
      ),
      '8' => array(
        'fid' => '11962',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kristy9_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/kristy9_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91060',
        'status' => '1',
        'timestamp' => '1296071558',
        'origname' => 'kristy9_JAN11.jpg',
      ),
      '9' => array(
        'fid' => '11964',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kristy10_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/kristy10_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141035',
        'status' => '1',
        'timestamp' => '1296071676',
        'origname' => 'kristy10_JAN11.jpg',
      ),
    ),
    'path' => 'stories/kristy',
    'tags' => array(
      '5' => array(
        '2608' => array(
          'tid' => '2608',
          'vid' => '5',
          'name' => ' SOPHIE KINACHTCHOUK',
          'description' => 'http://www.skphotography.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => ' SOPHIE KINACHTCHOUK',
        '4' => 'women',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
