array(
  array(
    'nid' => '3589',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1296146191',
    'changed' => '1337804839',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3589',
    'revision_uid' => '1',
    'title' => 'Espionage',
    'body' => '<p>
	I spy.<br />
	Exclusive photography by <a href="http://www.jacksonzhao.com/">Jackson Zhao</a>.<br />
	Model ~ Dana Drori @ Trump.</p>
',
    'teaser' => '<p>
	I spy.<br />
	Exclusive photography by <a href="http://www.jacksonzhao.com/">Jackson Zhao</a>.<br />
	Model ~ Dana Drori @ Trump.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804839',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.jacksonzhao.com/"> JACKSON ZHAO</a></p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	MICHAEL TUCKER</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	DANA DRORI<br />
	@ TRUMP<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		HELMUT LANG</li>
	<li>
		DONNA KARAN</li>
</ul>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11968',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136290',
        'status' => '1',
        'timestamp' => '1296146070',
        'origname' => 'espionage_JAN11.jpg',
      ),
      '1' => array(
        'fid' => '11969',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage2_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage2_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '148864',
        'status' => '1',
        'timestamp' => '1296146081',
        'origname' => 'espionage2_JAN11.jpg',
      ),
      '2' => array(
        'fid' => '11970',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage3_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage3_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '201249',
        'status' => '1',
        'timestamp' => '1296146090',
        'origname' => 'espionage3_JAN11.jpg',
      ),
      '3' => array(
        'fid' => '11982',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage4_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage4_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '223614',
        'status' => '1',
        'timestamp' => '1296146230',
        'origname' => 'espionage4_JAN11.jpg',
      ),
      '4' => array(
        'fid' => '11972',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage5_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage5_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154488',
        'status' => '1',
        'timestamp' => '1296146111',
        'origname' => 'espionage5_JAN11.jpg',
      ),
      '5' => array(
        'fid' => '11973',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage6_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage6_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '169600',
        'status' => '1',
        'timestamp' => '1296146122',
        'origname' => 'espionage6_JAN11.jpg',
      ),
      '6' => array(
        'fid' => '11974',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage7_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage7_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '197458',
        'status' => '1',
        'timestamp' => '1296146132',
        'origname' => 'espionage7_JAN11.jpg',
      ),
      '7' => array(
        'fid' => '11976',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage8_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage8_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '184465',
        'status' => '1',
        'timestamp' => '1296146144',
        'origname' => 'espionage8_JAN11.jpg',
      ),
      '8' => array(
        'fid' => '11977',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage9_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage9_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103707',
        'status' => '1',
        'timestamp' => '1296146151',
        'origname' => 'espionage9_JAN11.jpg',
      ),
      '9' => array(
        'fid' => '11979',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage10_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage10_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85389',
        'status' => '1',
        'timestamp' => '1296146162',
        'origname' => 'espionage10_JAN11.jpg',
      ),
      '10' => array(
        'fid' => '11980',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage11_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage11_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '162035',
        'status' => '1',
        'timestamp' => '1296146171',
        'origname' => 'espionage11_JAN11.jpg',
      ),
      '11' => array(
        'fid' => '11981',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'espionage12_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/espionage12_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123505',
        'status' => '1',
        'timestamp' => '1296146183',
        'origname' => 'espionage12_JAN11.jpg',
      ),
    ),
    'path' => 'stories/espionage',
    'tags' => array(
      '5' => array(
        '2609' => array(
          'tid' => '2609',
          'vid' => '5',
          'name' => ' JACKSON ZHAO',
          'description' => 'http://www.jacksonzhao.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '103' => array(
          'tid' => '103',
          'vid' => '1',
          'name' => 'DONNA KARAN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '102' => array(
          'tid' => '102',
          'vid' => '1',
          'name' => 'HELMUT LANG',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => ' JACKSON ZHAO',
        '1' => 'DONNA KARAN, HELMUT LANG',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
