array(
  array(
    'nid' => '3592',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1296230323',
    'changed' => '1403918098',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3592',
    'revision_uid' => '1',
    'title' => 'Into The Outback',
    'body' => '<p>
	Animal prints everywhere.<br />
	Exclusive photography by <a href="http://www.wendyhopephotography.com/" target="_blank">WENDY HOPE</a>.<br />
	Model ~&nbsp; Sosheeba @ Muse.</p>
',
    'teaser' => '<p>
	Animal prints everywhere.<br />
	Exclusive photography by <a href="http://www.wendyhopephotography.com/" target="_blank">WENDY HOPE</a>.<br />
	Model ~&nbsp; Sosheeba @ Muse.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918098',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.wendyhopephotography.com/" target="_blank">WENDY HOPE</a></p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	JANELLE NICOLE</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	SOSHEEBA<br />
	@ MUSE<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		SHAKUHACHI</li>
	<li>
		CARIN WEBSTER</li>
	<li>
		PINS AND NEEDLES</li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12026',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2A.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-2A.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '401402',
        'status' => '1',
        'timestamp' => '1296231079',
        'origname' => 'Layout-1_Page-2A.jpg',
      ),
      '1' => array(
        'fid' => '12010',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback2_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback2_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75085',
        'status' => '1',
        'timestamp' => '1296230181',
        'origname' => 'outback2_JAN11.jpg',
      ),
      '2' => array(
        'fid' => '12011',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback3_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback3_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '99226',
        'status' => '1',
        'timestamp' => '1296230194',
        'origname' => 'outback3_JAN11.jpg',
      ),
      '3' => array(
        'fid' => '12012',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback4_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback4_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '26412',
        'status' => '1',
        'timestamp' => '1296230204',
        'origname' => 'outback4_JAN11.jpg',
      ),
      '4' => array(
        'fid' => '12014',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback5_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback5_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20680',
        'status' => '1',
        'timestamp' => '1296230217',
        'origname' => 'outback5_JAN11.jpg',
      ),
      '5' => array(
        'fid' => '12015',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback6_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback6_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131412',
        'status' => '1',
        'timestamp' => '1296230227',
        'origname' => 'outback6_JAN11.jpg',
      ),
      '6' => array(
        'fid' => '12016',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback7_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback7_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104926',
        'status' => '1',
        'timestamp' => '1296230237',
        'origname' => 'outback7_JAN11.jpg',
      ),
      '7' => array(
        'fid' => '12017',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback8_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback8_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19736',
        'status' => '1',
        'timestamp' => '1296230247',
        'origname' => 'outback8_JAN11.jpg',
      ),
      '8' => array(
        'fid' => '12018',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback9_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback9_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19379',
        'status' => '1',
        'timestamp' => '1296230261',
        'origname' => 'outback9_JAN11.jpg',
      ),
      '9' => array(
        'fid' => '12020',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback10_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback10_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101232',
        'status' => '1',
        'timestamp' => '1296230271',
        'origname' => 'outback10_JAN11.jpg',
      ),
      '10' => array(
        'fid' => '12021',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback11_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback11_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '50219',
        'status' => '1',
        'timestamp' => '1296230279',
        'origname' => 'outback11_JAN11.jpg',
      ),
      '11' => array(
        'fid' => '12023',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback12_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback12_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '150010',
        'status' => '1',
        'timestamp' => '1296230290',
        'origname' => 'outback12_JAN11.jpg',
      ),
      '12' => array(
        'fid' => '12024',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback13_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback13_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '1296230300',
        'origname' => 'outback13_JAN11.jpg',
      ),
      '13' => array(
        'fid' => '12025',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'outback14_JAN11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/outback14_JAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '166611',
        'status' => '1',
        'timestamp' => '1296230311',
        'origname' => 'outback14_JAN11.jpg',
      ),
    ),
    'path' => 'stories/outback',
    'tags' => array(
      '1' => array(
        '100' => array(
          'tid' => '100',
          'vid' => '1',
          'name' => 'CARIN WEBSTER',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '101' => array(
          'tid' => '101',
          'vid' => '1',
          'name' => 'PINS AND NEEDLES',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '99' => array(
          'tid' => '99',
          'vid' => '1',
          'name' => 'SHAKUHACHI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2605' => array(
          'tid' => '2605',
          'vid' => '5',
          'name' => 'WENDY HOPE',
          'description' => 'http://www.wendyhopephotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'CARIN WEBSTER, PINS AND NEEDLES, SHAKUHACHI',
        '5' => 'WENDY HOPE',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
