array(
  array(
    'nid' => '3594',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1296493602',
    'changed' => '1403917833',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3594',
    'revision_uid' => '1',
    'title' => 'Aesthetes and Decadents',
    'body' => '<p>
	Aesthete chic.<br />
	Exclusive photography by <a href="http://www.christophersims.com/" target="_blank">Christopher Sims</a>.<br />
	Models ~&nbsp; Florian @ M+P &amp; Igor @ Premier.</p>
',
    'teaser' => '<p>
	Aesthete chic.<br />
	Exclusive photography by <a href="http://www.christophersims.com/" target="_blank">Christopher Sims</a>.<br />
	Models ~&nbsp; Florian @ M+P &amp; Igor @ Premier.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917833',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.christophersims.com/" target="_blank">Christopher Sims</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	STYLING<br />
	SARA DARLING</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODELS<br />
	FLORIAN @ M+P<br />
	IGOR @ PREMIER<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.orschel-read.com/" target="_blank">ORSCHEL READ</a></li>
	<li>
		<a href="http://www.asos.com/default.aspx?r=2" target="_blank">CAROLYN MASSEY</a></li>
	<li>
		<a href="http://www.selfridges.com/">WOOYOUNGMI @ SELFRIDGES</a></li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12028',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-2_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134443',
        'status' => '1',
        'timestamp' => '1296493356',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12060',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-3_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89100',
        'status' => '1',
        'timestamp' => '1296494420',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12031',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-4_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128132',
        'status' => '1',
        'timestamp' => '1296493373',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12032',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '39468',
        'status' => '1',
        'timestamp' => '1296493378',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12034',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-6_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '21717',
        'status' => '1',
        'timestamp' => '1296493390',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12035',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-7_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80949',
        'status' => '1',
        'timestamp' => '1296493396',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12038',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-8_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154699',
        'status' => '1',
        'timestamp' => '1296493403',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12039',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-9_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13985',
        'status' => '1',
        'timestamp' => '1296493414',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12040',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-10_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '143905',
        'status' => '1',
        'timestamp' => '1296493426',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12041',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-11_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116920',
        'status' => '1',
        'timestamp' => '1296493438',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12042',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-12_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17892',
        'status' => '1',
        'timestamp' => '1296493449',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12043',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-13_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112103',
        'status' => '1',
        'timestamp' => '1296493460',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '12045',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-14_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17920',
        'status' => '1',
        'timestamp' => '1296493477',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '12047',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-15_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '151863',
        'status' => '1',
        'timestamp' => '1296493485',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '12048',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-16_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129297',
        'status' => '1',
        'timestamp' => '1296493493',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '12050',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-17_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17993',
        'status' => '1',
        'timestamp' => '1296493508',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '16' => array(
        'fid' => '12051',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-18_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17238',
        'status' => '1',
        'timestamp' => '1296493522',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
      '17' => array(
        'fid' => '12053',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-19.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-19_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95762',
        'status' => '1',
        'timestamp' => '1296493536',
        'origname' => 'Layout-1_Page-19.jpg',
      ),
      '18' => array(
        'fid' => '12054',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-20.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-20_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '210140',
        'status' => '1',
        'timestamp' => '1296493544',
        'origname' => 'Layout-1_Page-20.jpg',
      ),
      '19' => array(
        'fid' => '12057',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-21.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-21_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '27442',
        'status' => '1',
        'timestamp' => '1296493572',
        'origname' => 'Layout-1_Page-21.jpg',
      ),
      '20' => array(
        'fid' => '12058',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-22.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-22.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16038',
        'status' => '1',
        'timestamp' => '1296493582',
        'origname' => 'Layout-1_Page-22.jpg',
      ),
      '21' => array(
        'fid' => '12059',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-23.jpg',
        'filepath' => 'files/fmag_story/2011/Jan/Layout-1_Page-23_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158011',
        'status' => '1',
        'timestamp' => '1296493592',
        'origname' => 'Layout-1_Page-23.jpg',
      ),
    ),
    'path' => 'stories/aesthetes-and-decadents',
    'tags' => array(
      '1' => array(
        '97' => array(
          'tid' => '97',
          'vid' => '1',
          'name' => 'CAROLYN MASSEY',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '96' => array(
          'tid' => '96',
          'vid' => '1',
          'name' => 'ORSCHEL READ',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '98' => array(
          'tid' => '98',
          'vid' => '1',
          'name' => 'WOOYOUNGMI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2523' => array(
          'tid' => '2523',
          'vid' => '5',
          'name' => 'Christopher Sims',
          'description' => 'http://christophersims.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'CAROLYN MASSEY, ORSCHEL READ, WOOYOUNGMI',
        '5' => 'Christopher Sims',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
