array(
  array(
    'nid' => '3598',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1296755361',
    'changed' => '1337804798',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3598',
    'revision_uid' => '1',
    'title' => 'Stormy Weather',
    'body' => '<p>
	Take cover.<br />
	Exclusive photography by <a href="http://www.regenandhisphotography.com">Regen Chen</a>.<br />
	Model ~&nbsp; Dami @ I Models.</p>
',
    'teaser' => '<p>
	Take cover.<br />
	Exclusive photography by <a href="http://www.regenandhisphotography.com">Regen Chen</a>.<br />
	Model ~&nbsp; Dami @ I Models.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804798',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.regenandhisphotography.com"> REGEN CHEN</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	STYLING<br />
	TIFFANY BRISENO-FERA</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	DAMI @ I MODELS<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		DIESEL</li>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12112',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-2_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '252516',
        'status' => '1',
        'timestamp' => '1296755145',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12115',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-3_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80459',
        'status' => '1',
        'timestamp' => '1296755164',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12117',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-4_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '263930',
        'status' => '1',
        'timestamp' => '1296755177',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12119',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-5_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '53719',
        'status' => '1',
        'timestamp' => '1296755186',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12120',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-6_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '207738',
        'status' => '1',
        'timestamp' => '1296755192',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12121',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-7_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '278578',
        'status' => '1',
        'timestamp' => '1296755202',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12123',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-8_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114692',
        'status' => '1',
        'timestamp' => '1296755248',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12125',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-9_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '135791',
        'status' => '1',
        'timestamp' => '1296755255',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12127',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-10_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131026',
        'status' => '1',
        'timestamp' => '1296755263',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12144',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-11_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '39480',
        'status' => '1',
        'timestamp' => '1296755541',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12128',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-12_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14665',
        'status' => '1',
        'timestamp' => '1296755268',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12130',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-13_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '191478',
        'status' => '1',
        'timestamp' => '1296755278',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '12131',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-14_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11378',
        'status' => '1',
        'timestamp' => '1296755284',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '12133',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-15_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '99193',
        'status' => '1',
        'timestamp' => '1296755295',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '12135',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-16_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14729',
        'status' => '1',
        'timestamp' => '1296755302',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '12138',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-17_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '194074',
        'status' => '1',
        'timestamp' => '1296755315',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '16' => array(
        'fid' => '12139',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-18_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13695',
        'status' => '1',
        'timestamp' => '1296755325',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
      '17' => array(
        'fid' => '12140',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-19.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-19_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '203075',
        'status' => '1',
        'timestamp' => '1296755337',
        'origname' => 'Layout-1_Page-19.jpg',
      ),
      '18' => array(
        'fid' => '12142',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-20.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-20_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '185520',
        'status' => '1',
        'timestamp' => '1296755347',
        'origname' => 'Layout-1_Page-20.jpg',
      ),
      '19' => array(
        'fid' => '12143',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-21.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-21_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13326',
        'status' => '1',
        'timestamp' => '1296755352',
        'origname' => 'Layout-1_Page-21.jpg',
      ),
    ),
    'path' => 'stories/stormy-weather',
    'tags' => array(
      '5' => array(
        '2612' => array(
          'tid' => '2612',
          'vid' => '5',
          'name' => ' REGEN CHEN',
          'description' => 'http://www.regenandhisphotography.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '89' => array(
          'tid' => '89',
          'vid' => '1',
          'name' => 'DIESEL',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => ' REGEN CHEN',
        '1' => 'DIESEL',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
