array(
  array(
    'nid' => '3600',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1297369312',
    'changed' => '1403918097',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3600',
    'revision_uid' => '1',
    'title' => 'Let Me Think About It',
    'body' => '<p>
	Baby think about it.<br />
	Exclusive photography by <a href="http://www.anjelicam.com/">Anjelica Martinez</a>.<br />
	Model ~&nbsp; Johanna @ Wilhelmina.</p>
',
    'teaser' => '<p>
	Baby think about it.<br />
	Exclusive photography by <a href="http://www.anjelicam.com/">Anjelica Martinez</a>.<br />
	Model ~&nbsp; Johanna @ Wilhelmina.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918097',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.anjelicam.com/"> ANjelica Martinez</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	STYLING<br />
	WAINA CHANCY<br />
	&amp; OBE SANTOS</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	JOHANNA<br />
	@ WILHELMINA<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.redcarter.com/">RED CARTER</a></li>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12146',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-2_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '170496',
        'status' => '1',
        'timestamp' => '1297369151',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12147',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-3_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139201',
        'status' => '1',
        'timestamp' => '1297369163',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12148',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-4_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '57136',
        'status' => '1',
        'timestamp' => '1297369174',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12149',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-5_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '23281',
        'status' => '1',
        'timestamp' => '1297369185',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12150',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-6_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68940',
        'status' => '1',
        'timestamp' => '1297369197',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12151',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-7_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60120',
        'status' => '1',
        'timestamp' => '1297369207',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12152',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-8_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60753',
        'status' => '1',
        'timestamp' => '1297369219',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12153',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-9_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22872',
        'status' => '1',
        'timestamp' => '1297369231',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12154',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-10_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18540',
        'status' => '1',
        'timestamp' => '1297369243',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12155',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-11_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63893',
        'status' => '1',
        'timestamp' => '1297369255',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12156',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-12_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94389',
        'status' => '1',
        'timestamp' => '1297369267',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12157',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-13_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17452',
        'status' => '1',
        'timestamp' => '1297369280',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '12158',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-14_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17740',
        'status' => '1',
        'timestamp' => '1297369290',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '12159',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-15_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '62060',
        'status' => '1',
        'timestamp' => '1297369300',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
    ),
    'path' => 'stories/let-me-think-about-it',
    'tags' => array(
      '5' => array(
        '2613' => array(
          'tid' => '2613',
          'vid' => '5',
          'name' => ' ANjelica Martinez',
          'description' => 'http://www.anjelicam.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '88' => array(
          'tid' => '88',
          'vid' => '1',
          'name' => 'Red Carter',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => ' ANjelica Martinez',
        '1' => 'Red Carter',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
