array(
  array(
    'nid' => '3604',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1297625626',
    'changed' => '1337804773',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3604',
    'revision_uid' => '1',
    'title' => 'Game of Assembly',
    'body' => '<p>
	Putting it all together.<br />
	Exclusive photography by <a href="http://www.cecilieharris.co.uk/"><span>Cecilie Harris</span></a>.<br />
	Model ~&nbsp; Joe @ D1 &amp; Tom @ M&amp;P.</p>
',
    'teaser' => '<p>
	Putting it all together.<br />
	Exclusive photography by <a href="http://www.cecilieharris.co.uk/"><span>Cecilie Harris</span></a>.<br />
	Model ~&nbsp; Joe @ D1 &amp; Tom @ M&amp;P.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804773',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.cecilieharris.co.uk/"><span>Cecilie Harris</span></a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING BY<br />
	CRAIG DAVID HILLS</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODELS<br />
	JOE @ D1<br />
	&amp; TOM<br />
	@ M&amp;P</p>
<p>
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		ORSCHEL-READ</li>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12194',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '168731',
        'status' => '1',
        'timestamp' => '1297625401',
        'origname' => 'assembly_feb11.jpg',
      ),
      '1' => array(
        'fid' => '12209',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-3_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '48427',
        'status' => '1',
        'timestamp' => '1297705163',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12196',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly3_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly3_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '219456',
        'status' => '1',
        'timestamp' => '1297625429',
        'origname' => 'assembly3_feb11.jpg',
      ),
      '3' => array(
        'fid' => '12197',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly4_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly4_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '179192',
        'status' => '1',
        'timestamp' => '1297625441',
        'origname' => 'assembly4_feb11.jpg',
      ),
      '4' => array(
        'fid' => '12198',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly5_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly5_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '234480',
        'status' => '1',
        'timestamp' => '1297625459',
        'origname' => 'assembly5_feb11.jpg',
      ),
      '5' => array(
        'fid' => '12199',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly6_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly6_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '199695',
        'status' => '1',
        'timestamp' => '1297625478',
        'origname' => 'assembly6_feb11.jpg',
      ),
      '6' => array(
        'fid' => '12200',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly7_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly7_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '203176',
        'status' => '1',
        'timestamp' => '1297625498',
        'origname' => 'assembly7_feb11.jpg',
      ),
      '7' => array(
        'fid' => '12201',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly8_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly8_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173181',
        'status' => '1',
        'timestamp' => '1297625514',
        'origname' => 'assembly8_feb11.jpg',
      ),
      '8' => array(
        'fid' => '12202',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly9_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly9_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '199128',
        'status' => '1',
        'timestamp' => '1297625531',
        'origname' => 'assembly9_feb11.jpg',
      ),
      '9' => array(
        'fid' => '12203',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly10_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly10_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15053',
        'status' => '1',
        'timestamp' => '1297625546',
        'origname' => 'assembly10_feb11.jpg',
      ),
      '10' => array(
        'fid' => '12204',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly11_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly11_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '233825',
        'status' => '1',
        'timestamp' => '1297625564',
        'origname' => 'assembly11_feb11.jpg',
      ),
      '11' => array(
        'fid' => '12205',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly12_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly12_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '162786',
        'status' => '1',
        'timestamp' => '1297625580',
        'origname' => 'assembly12_feb11.jpg',
      ),
      '12' => array(
        'fid' => '12206',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly13_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly13_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '212699',
        'status' => '1',
        'timestamp' => '1297625599',
        'origname' => 'assembly13_feb11.jpg',
      ),
      '13' => array(
        'fid' => '12207',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'assembly14_feb11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/assembly14_feb11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '229397',
        'status' => '1',
        'timestamp' => '1297625614',
        'origname' => 'assembly14_feb11.jpg',
      ),
    ),
    'path' => 'stories/game-assembly',
    'tags' => array(
      '5' => array(
        '2615' => array(
          'tid' => '2615',
          'vid' => '5',
          'name' => 'Cecilie Harris',
          'description' => 'http://www.cecilieharris.co.uk/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '87' => array(
          'tid' => '87',
          'vid' => '1',
          'name' => 'ORSCHEL-READ',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Cecilie Harris',
        '1' => 'ORSCHEL-READ',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
