array(
  array(
    'nid' => '3606',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1297723699',
    'changed' => '1403918097',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3606',
    'revision_uid' => '1',
    'title' => 'I Want To Be Perfect',
    'body' => '<p>
	Birds of a feather.<br />
	Exclusive photography by <a href="http://www.jasonobrotka.com/">JASON OBROTKA</a>.<br />
	Model ~&nbsp; Anna Z @ MC2.</p>
',
    'teaser' => '<p>
	Birds of a feather.<br />
	Exclusive photography by <a href="http://www.jasonobrotka.com/">JASON OBROTKA</a>.<br />
	Model ~&nbsp; Anna Z @ MC2.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918097',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.jasonobrotka.com/">JASON OBROTKA</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING BY<br />
	KAREN PEREZ</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	ANNA Z<br />
	@ MC2</p>
<p>
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<p>
	<br />
	&nbsp;</p>
<ul>
	<li>
		<a href="http://www.liesangbong.com/gb/index.php">LIE SANG BONG</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12210',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'I-just-want-to-be-perfect_2.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/I-just-want-to-be-perfect_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78638',
        'status' => '1',
        'timestamp' => '1297723465',
        'origname' => 'I-just-want-to-be-perfect_2.jpg',
      ),
      '1' => array(
        'fid' => '12327',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'I-just-want-to-be-perfect_3.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/I-just-want-to-be-perfect_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87497',
        'status' => '1',
        'timestamp' => '1297976564',
        'origname' => 'I-just-want-to-be-perfect_3.jpg',
      ),
      '2' => array(
        'fid' => '12212',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'I-just-want-to-be-perfect_4.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/I-just-want-to-be-perfect_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17252',
        'status' => '1',
        'timestamp' => '1297723511',
        'origname' => 'I-just-want-to-be-perfect_4.jpg',
      ),
      '3' => array(
        'fid' => '12213',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'I-just-want-to-be-perfect_5.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/I-just-want-to-be-perfect_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66911',
        'status' => '1',
        'timestamp' => '1297723571',
        'origname' => 'I-just-want-to-be-perfect_5.jpg',
      ),
      '4' => array(
        'fid' => '12216',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'I-just-want-to-be-perfect_8.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/I-just-want-to-be-perfect_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92837',
        'status' => '1',
        'timestamp' => '1297723606',
        'origname' => 'I-just-want-to-be-perfect_8.jpg',
      ),
      '5' => array(
        'fid' => '12217',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'I-just-want-to-be-perfect_9.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/I-just-want-to-be-perfect_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17415',
        'status' => '1',
        'timestamp' => '1297723626',
        'origname' => 'I-just-want-to-be-perfect_9.jpg',
      ),
      '6' => array(
        'fid' => '12218',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'I-just-want-to-be-perfct_10.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/I-just-want-to-be-perfct_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17225',
        'status' => '1',
        'timestamp' => '1297723651',
        'origname' => 'I-just-want-to-be-perfct_10.jpg',
      ),
      '7' => array(
        'fid' => '12219',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'I-just-want-to-be-perfct_11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/I-just-want-to-be-perfct_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61498',
        'status' => '1',
        'timestamp' => '1297723687',
        'origname' => 'I-just-want-to-be-perfct_11.jpg',
      ),
    ),
    'path' => 'stories/i-want-be-perfect',
    'tags' => array(
      '5' => array(
        '2492' => array(
          'tid' => '2492',
          'vid' => '5',
          'name' => 'JASON OBROTKA',
          'description' => 'http://www.jasonobrotka.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '79' => array(
          'tid' => '79',
          'vid' => '1',
          'name' => 'Lie Sang Bong',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JASON OBROTKA',
        '1' => 'Lie Sang Bong',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
