array(
  array(
    'nid' => '3612',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1298318373',
    'changed' => '1403918097',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3612',
    'revision_uid' => '1',
    'title' => 'Down The Garden Path',
    'body' => '<p>
	Floral it up.<br />
	Exclusive photography by <a href="http://www.samanthawolov.com/" target="_blank"><span>Samantha Wolov</span></a>.<br />
	Model ~&nbsp; Nikki @ City.</p>
',
    'teaser' => '<p>
	Floral it up.<br />
	Exclusive photography by <a href="http://www.samanthawolov.com/" target="_blank"><span>Samantha Wolov</span></a>.<br />
	Model ~&nbsp; Nikki @ City.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918097',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.samanthawolov.com/" target="_blank">SAMANTHA WOLOV</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	ALANNA ANDERSON</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	NIKKI @ CITY</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		CAROLINA HERERRA</li>
	<li>
		ROBERTO CAVALLI</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12294',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '238874',
        'status' => '1',
        'timestamp' => '1297972599',
        'origname' => 'garden_FEB11.jpg',
      ),
      '1' => array(
        'fid' => '12295',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden2_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden2_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '41165',
        'status' => '1',
        'timestamp' => '1297972615',
        'origname' => 'garden2_FEB11.jpg',
      ),
      '2' => array(
        'fid' => '12296',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden3_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden3_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18744',
        'status' => '1',
        'timestamp' => '1297972627',
        'origname' => 'garden3_FEB11.jpg',
      ),
      '3' => array(
        'fid' => '12297',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden4_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden4_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '199214',
        'status' => '1',
        'timestamp' => '1297972639',
        'origname' => 'garden4_FEB11.jpg',
      ),
      '4' => array(
        'fid' => '12298',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden5_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden5_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '367705',
        'status' => '1',
        'timestamp' => '1297972652',
        'origname' => 'garden5_FEB11.jpg',
      ),
      '5' => array(
        'fid' => '12299',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden6_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden6_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '25551',
        'status' => '1',
        'timestamp' => '1297972663',
        'origname' => 'garden6_FEB11.jpg',
      ),
      '6' => array(
        'fid' => '12300',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden7_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden7_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '258136',
        'status' => '1',
        'timestamp' => '1297972675',
        'origname' => 'garden7_FEB11.jpg',
      ),
      '7' => array(
        'fid' => '12301',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden8_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden8_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15484',
        'status' => '1',
        'timestamp' => '1297972690',
        'origname' => 'garden8_FEB11.jpg',
      ),
      '8' => array(
        'fid' => '12302',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden9_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden9_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17613',
        'status' => '1',
        'timestamp' => '1297972701',
        'origname' => 'garden9_FEB11.jpg',
      ),
      '9' => array(
        'fid' => '12303',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden10_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden10_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '434812',
        'status' => '1',
        'timestamp' => '1297972715',
        'origname' => 'garden10_FEB11.jpg',
      ),
      '10' => array(
        'fid' => '12304',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden11_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden11_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '217073',
        'status' => '1',
        'timestamp' => '1297972727',
        'origname' => 'garden11_FEB11.jpg',
      ),
      '11' => array(
        'fid' => '12305',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden12_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden12_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20148',
        'status' => '1',
        'timestamp' => '1297972742',
        'origname' => 'garden12_FEB11.jpg',
      ),
      '12' => array(
        'fid' => '12306',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden13_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden13_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18416',
        'status' => '1',
        'timestamp' => '1297972754',
        'origname' => 'garden13_FEB11.jpg',
      ),
      '13' => array(
        'fid' => '12307',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'garden14_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/garden14_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '305203',
        'status' => '1',
        'timestamp' => '1297972765',
        'origname' => 'garden14_FEB11.jpg',
      ),
    ),
    'path' => 'stories/down-garden-path',
    'tags' => array(
      '1' => array(
        '173' => array(
          'tid' => '173',
          'vid' => '1',
          'name' => 'CAROLINA HERERRA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '174' => array(
          'tid' => '174',
          'vid' => '1',
          'name' => 'ROBERTO CAVALLI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2598' => array(
          'tid' => '2598',
          'vid' => '5',
          'name' => 'Samantha wolov',
          'description' => 'http://www.samanthawolov.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'CAROLINA HERERRA, ROBERTO CAVALLI',
        '5' => 'Samantha wolov',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
