array(
  array(
    'nid' => '3616',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1298661115',
    'changed' => '1403918097',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3616',
    'revision_uid' => '1',
    'title' => 'Metal Heart',
    'body' => '<p>
	Steely love.<br />
	Exclusive photography by <a href="http://loravertue.com/" target="_blank">LORA VERTUE</a>.<br />
	Model ~&nbsp; Jessica Lewis @ Elmer Olsen.</p>
',
    'teaser' => '<p>
	Steely love.<br />
	Exclusive photography by <a href="http://loravertue.com/" target="_blank">LORA VERTUE</a>.<br />
	Model ~&nbsp; Jessica Lewis @ Elmer Olsen.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918097',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://loravertue.com/" target="_blank">LORA VERTUE</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING BY<br />
	NELLYA TSYRLIN</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	JESSICA LEWIS<br />
	@ ELMER OLSEN</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		ALEXANDER WANG</li>
	<li>
		ELIZA KOZURNO</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12329',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119663',
        'status' => '1',
        'timestamp' => '1298056430',
        'origname' => 'metal_FEB11.jpg',
      ),
      '1' => array(
        'fid' => '12330',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal2_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal2_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '190488',
        'status' => '1',
        'timestamp' => '1298056437',
        'origname' => 'metal2_FEB11.jpg',
      ),
      '2' => array(
        'fid' => '12331',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal3_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal3_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132263',
        'status' => '1',
        'timestamp' => '1298056455',
        'origname' => 'metal3_FEB11.jpg',
      ),
      '3' => array(
        'fid' => '12332',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal4_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal4_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20393',
        'status' => '1',
        'timestamp' => '1298056466',
        'origname' => 'metal4_FEB11.jpg',
      ),
      '4' => array(
        'fid' => '12333',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal5_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal5_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100604',
        'status' => '1',
        'timestamp' => '1298056477',
        'origname' => 'metal5_FEB11.jpg',
      ),
      '5' => array(
        'fid' => '12334',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal6_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal6_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83209',
        'status' => '1',
        'timestamp' => '1298056488',
        'origname' => 'metal6_FEB11.jpg',
      ),
      '6' => array(
        'fid' => '12335',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal7_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal7_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14278',
        'status' => '1',
        'timestamp' => '1298056499',
        'origname' => 'metal7_FEB11.jpg',
      ),
      '7' => array(
        'fid' => '12336',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal8_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal8_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '159451',
        'status' => '1',
        'timestamp' => '1298056511',
        'origname' => 'metal8_FEB11.jpg',
      ),
      '8' => array(
        'fid' => '12337',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal9_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal9_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16458',
        'status' => '1',
        'timestamp' => '1298056524',
        'origname' => 'metal9_FEB11.jpg',
      ),
      '9' => array(
        'fid' => '12338',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal10_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal10_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89674',
        'status' => '1',
        'timestamp' => '1298056540',
        'origname' => 'metal10_FEB11.jpg',
      ),
      '10' => array(
        'fid' => '12339',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal11_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal11_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97513',
        'status' => '1',
        'timestamp' => '1298056550',
        'origname' => 'metal11_FEB11.jpg',
      ),
      '11' => array(
        'fid' => '12340',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'metal12_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/metal12_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15560',
        'status' => '1',
        'timestamp' => '1298056561',
        'origname' => 'metal12_FEB11.jpg',
      ),
    ),
    'path' => 'stories/metal-heart',
    'tags' => array(
      '5' => array(
        '2616' => array(
          'tid' => '2616',
          'vid' => '5',
          'name' => 'LORA VERTUE',
          'description' => 'http://loravertue.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'LORA VERTUE',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
