array(
  array(
    'nid' => '3619',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1299009573',
    'changed' => '1403918097',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3619',
    'revision_uid' => '1',
    'title' => 'The Naked and the Dressed',
    'body' => '<p>
	It&#39;s all about nude.<br />
	Exclusive photography by <a href="http://www.michaelfranco.net/" target="_blank">Michael Franco</a>.<br />
	Model ~&nbsp; Amanda Kepner @ Ford/RBA.</p>
',
    'teaser' => '<p>
	It&#39;s all about nude.<br />
	Exclusive photography by <a href="http://www.michaelfranco.net/" target="_blank">Michael Franco</a>.<br />
	Model ~&nbsp; Amanda Kepner @ Ford/RBA.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918097',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.michaelfranco.net/" target="_blank">MICHAEL FRANCO</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	AMANDA KEPNER @ FORD/RBA</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		JATIN VARMA</li>
	<li>
		IRINA SHABAYEVA</li>
	<li>
		DONNA MIZANI</li>
	<li>
		AURELIO COSTARELLA</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12360',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90385',
        'status' => '1',
        'timestamp' => '1298327256',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12361',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '219161',
        'status' => '1',
        'timestamp' => '1298327274',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12345',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118336',
        'status' => '1',
        'timestamp' => '1298325945',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12346',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17425',
        'status' => '1',
        'timestamp' => '1298325959',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12347',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98963',
        'status' => '1',
        'timestamp' => '1298325973',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12348',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96877',
        'status' => '1',
        'timestamp' => '1298325986',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12349',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94268',
        'status' => '1',
        'timestamp' => '1298326003',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12350',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '32469',
        'status' => '1',
        'timestamp' => '1298326016',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12620',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-6_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '1300223100',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '9' => array(
        'fid' => '12621',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-7_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132493',
        'status' => '1',
        'timestamp' => '1300223112',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '10' => array(
        'fid' => '12351',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124290',
        'status' => '1',
        'timestamp' => '1298326057',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '11' => array(
        'fid' => '12353',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114833',
        'status' => '1',
        'timestamp' => '1298326095',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '12' => array(
        'fid' => '12354',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13430',
        'status' => '1',
        'timestamp' => '1298326109',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '13' => array(
        'fid' => '12355',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118499',
        'status' => '1',
        'timestamp' => '1298326126',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '14' => array(
        'fid' => '12356',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128828',
        'status' => '1',
        'timestamp' => '1298326140',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '15' => array(
        'fid' => '12357',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123426',
        'status' => '1',
        'timestamp' => '1298326158',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '16' => array(
        'fid' => '12358',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84796',
        'status' => '1',
        'timestamp' => '1298326172',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '17' => array(
        'fid' => '12359',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '44930',
        'status' => '1',
        'timestamp' => '1298326185',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
    ),
    'path' => 'stories/naked-and-dressed',
    'tags' => array(
      '1' => array(
        '179' => array(
          'tid' => '179',
          'vid' => '1',
          'name' => 'derric lowe',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '176' => array(
          'tid' => '176',
          'vid' => '1',
          'name' => 'FORD',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '180' => array(
          'tid' => '180',
          'vid' => '1',
          'name' => 'ford/rba',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2465' => array(
          'tid' => '2465',
          'vid' => '5',
          'name' => 'MICHAEL FRANCO',
          'description' => 'http://www.michaelfranco.net/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'derric lowe, FORD, ford/rba',
        '5' => 'MICHAEL FRANCO',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
