array(
  array(
    'nid' => '3621',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1299173271',
    'changed' => '1403917832',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3621',
    'revision_uid' => '1',
    'title' => 'Lush Life',
    'body' => '<p>
	Stephano Diaz and Troy Mattison Hicks on Necklush.<br />
	Interview by Heather MacDonald.</p>
',
    'teaser' => '<p>
	Stephano Diaz and Troy Mattison Hicks on Necklush.<br />
	Interview by Heather MacDonald.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917832',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://shop.necklush.com/" target="_blank">NECKLUSH</a></p>
<p>
	&nbsp;</p>
<p>
	INTERVIEW<br />
	HEATHER MACDONALD</p>
<p>
	&nbsp;</p>
<p>
	<a href="http://thisartisyours.com/" target="_blank">THIS ART IS YOURS</a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://zeliumquang.bandcamp.com/" target="_blank">ZELIUM QUANG</a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://paano.bandcamp.com/" target="_blank">PAANO</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12368',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'lush_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/lush_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '120227',
        'status' => '1',
        'timestamp' => '1298568363',
        'origname' => 'lush_FEB11.jpg',
      ),
      '1' => array(
        'fid' => '12369',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'lush2_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/lush2_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '178273',
        'status' => '1',
        'timestamp' => '1298568378',
        'origname' => 'lush2_FEB11.jpg',
      ),
      '2' => array(
        'fid' => '12370',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'lush3_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/lush3_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89443',
        'status' => '1',
        'timestamp' => '1298568390',
        'origname' => 'lush3_FEB11.jpg',
      ),
      '3' => array(
        'fid' => '12371',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'lush4_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/lush4_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173372',
        'status' => '1',
        'timestamp' => '1298568399',
        'origname' => 'lush4_FEB11.jpg',
      ),
      '4' => array(
        'fid' => '12372',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'lush5_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/lush5_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91079',
        'status' => '1',
        'timestamp' => '1298568411',
        'origname' => 'lush5_FEB11.jpg',
      ),
      '5' => array(
        'fid' => '12373',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'lush6_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/lush6_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73242',
        'status' => '1',
        'timestamp' => '1298568420',
        'origname' => 'lush6_FEB11.jpg',
      ),
      '6' => array(
        'fid' => '12374',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'lush7_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/lush7_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '166258',
        'status' => '1',
        'timestamp' => '1298568431',
        'origname' => 'lush7_FEB11.jpg',
      ),
      '7' => array(
        'fid' => '12375',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'lush8_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/lush8_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '145585',
        'status' => '1',
        'timestamp' => '1298568440',
        'origname' => 'lush8_FEB11.jpg',
      ),
      '8' => array(
        'fid' => '12376',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'lush9_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/lush9_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102204',
        'status' => '1',
        'timestamp' => '1298568449',
        'origname' => 'lush9_FEB11.jpg',
      ),
      '9' => array(
        'fid' => '12377',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'lush10_FEB11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/lush10_FEB11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153104',
        'status' => '1',
        'timestamp' => '1298568461',
        'origname' => 'lush10_FEB11.jpg',
      ),
    ),
    'path' => 'stories/lush-life',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2465' => array(
          'tid' => '2465',
          'vid' => '5',
          'name' => 'MICHAEL FRANCO',
          'description' => 'http://www.michaelfranco.net/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '181' => array(
          'tid' => '181',
          'vid' => '1',
          'name' => 'necklush',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'men',
        '5' => 'MICHAEL FRANCO',
        '1' => 'necklush',
      ),
      '2' => array(
        '2' => '2',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
