array(
  array(
    'nid' => '3623',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1299524593',
    'changed' => '1299669355',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3623',
    'revision_uid' => '1',
    'title' => 'Twin Set',
    'body' => '<p>
	Siblings but no rivalry.<br />
	Exclusive photography by<a href="http://www.tiffanymay.ca/" target="_blank"><span> Tiffany May</span></a>.<br />
	Models ~&nbsp; Christine Popovich &amp; Mark V @ Richards.</p>
',
    'teaser' => '<p>
	Siblings but no rivalry.<br />
	Exclusive photography by<a href="http://www.tiffanymay.ca/" target="_blank"><span> Tiffany May</span></a>.<br />
	Models ~&nbsp; Christine Popovich &amp; Mark V @ Richards.</p>
',
    'log' => '',
    'revision_timestamp' => '1299669355',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.tiffanymay.ca/" target="_blank">TIFFANY MAY</a></p>
<p>
	<br />
	&nbsp;</p>
<p>
	STYLIST<br />
	PATRICIA LAGMAY<br />
	@THEY REP</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODELS<br />
	CHRISTINE POPOVICH<br />
	&amp; MARK V<br />
	@ RICHARDS</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		H&amp;M</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12379',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '176914',
        'status' => '1',
        'timestamp' => '1298573843',
        'origname' => 'twinset_MAR11.jpg',
      ),
      '1' => array(
        'fid' => '12401',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/Layout-1_Page-3_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106607',
        'status' => '1',
        'timestamp' => '1298574458',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12381',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset3_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset3_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '168719',
        'status' => '1',
        'timestamp' => '1298573860',
        'origname' => 'twinset3_MAR11.jpg',
      ),
      '3' => array(
        'fid' => '12382',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset4_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset4_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13421',
        'status' => '1',
        'timestamp' => '1298573870',
        'origname' => 'twinset4_MAR11.jpg',
      ),
      '4' => array(
        'fid' => '12383',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset5_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset5_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '169966',
        'status' => '1',
        'timestamp' => '1298573879',
        'origname' => 'twinset5_MAR11.jpg',
      ),
      '5' => array(
        'fid' => '12384',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset6_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset6_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '144880',
        'status' => '1',
        'timestamp' => '1298573889',
        'origname' => 'twinset6_MAR11.jpg',
      ),
      '6' => array(
        'fid' => '12385',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset7_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset7_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '1298573901',
        'origname' => 'twinset7_MAR11.jpg',
      ),
      '7' => array(
        'fid' => '12386',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset8_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset8_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106222',
        'status' => '1',
        'timestamp' => '1298573914',
        'origname' => 'twinset8_MAR11.jpg',
      ),
      '8' => array(
        'fid' => '12387',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset9_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset9_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67364',
        'status' => '1',
        'timestamp' => '1298573929',
        'origname' => 'twinset9_MAR11.jpg',
      ),
      '9' => array(
        'fid' => '12388',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset10_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset10_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101767',
        'status' => '1',
        'timestamp' => '1298573969',
        'origname' => 'twinset10_MAR11.jpg',
      ),
      '10' => array(
        'fid' => '12389',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset11_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset11_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81124',
        'status' => '1',
        'timestamp' => '1298573982',
        'origname' => 'twinset11_MAR11.jpg',
      ),
      '11' => array(
        'fid' => '12390',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset12_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset12_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73819',
        'status' => '1',
        'timestamp' => '1298573992',
        'origname' => 'twinset12_MAR11.jpg',
      ),
      '12' => array(
        'fid' => '12391',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset13_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset13_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '1298574006',
        'origname' => 'twinset13_MAR11.jpg',
      ),
      '13' => array(
        'fid' => '12392',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset14_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset14_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131369',
        'status' => '1',
        'timestamp' => '1298574017',
        'origname' => 'twinset14_MAR11.jpg',
      ),
      '14' => array(
        'fid' => '12393',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset15_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset15_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137307',
        'status' => '1',
        'timestamp' => '1298574029',
        'origname' => 'twinset15_MAR11.jpg',
      ),
      '15' => array(
        'fid' => '12394',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset16_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset16_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '196521',
        'status' => '1',
        'timestamp' => '1298574041',
        'origname' => 'twinset16_MAR11.jpg',
      ),
      '16' => array(
        'fid' => '12395',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset17_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset17_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87722',
        'status' => '1',
        'timestamp' => '1298574072',
        'origname' => 'twinset17_MAR11.jpg',
      ),
      '17' => array(
        'fid' => '12396',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset18_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset18_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '115347',
        'status' => '1',
        'timestamp' => '1298574106',
        'origname' => 'twinset18_MAR11.jpg',
      ),
      '18' => array(
        'fid' => '12397',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset19_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset19_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '145460',
        'status' => '1',
        'timestamp' => '1298574137',
        'origname' => 'twinset19_MAR11.jpg',
      ),
      '19' => array(
        'fid' => '12398',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset20_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset20_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '170018',
        'status' => '1',
        'timestamp' => '1298574157',
        'origname' => 'twinset20_MAR11.jpg',
      ),
      '20' => array(
        'fid' => '12399',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset21_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset21_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104079',
        'status' => '1',
        'timestamp' => '1298574169',
        'origname' => 'twinset21_MAR11.jpg',
      ),
      '21' => array(
        'fid' => '12400',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'twinset22_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/twinset22_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139201',
        'status' => '1',
        'timestamp' => '1298574182',
        'origname' => 'twinset22_MAR11.jpg',
      ),
    ),
    'path' => 'stories/twin-set',
    'tags' => array(
      '1' => array(
        '182' => array(
          'tid' => '182',
          'vid' => '1',
          'name' => 'Tiffany May',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2617' => array(
          'tid' => '2617',
          'vid' => '5',
          'name' => 'TIFFANY MAY',
          'description' => 'http://www.tiffanymay.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '1' => '1',
      ),
      'tags' => array(
        '1' => 'Tiffany May',
        '5' => 'TIFFANY MAY',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
