array(
  array(
    'nid' => '3625',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1299704367',
    'changed' => '1337804742',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3625',
    'revision_uid' => '1',
    'title' => 'Top It Up',
    'body' => '<p>
	Topsy turvy.<br />
	Exclusive photography by <a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a>.<br />
	Models ~&nbsp; Adam Jones @ Major.</p>
',
    'teaser' => '<p>
	Topsy turvy.<br />
	Exclusive photography by <a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a>.<br />
	Models ~&nbsp; Adam Jones @ Major.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804742',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	ADAM JONES<br />
	@ MAJOR<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		ANN DEMEULEMEESTER</li>
	<li>
		RICK OWENS</li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12403',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'top_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/top_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '70835',
        'status' => '1',
        'timestamp' => '1298581083',
        'origname' => 'top_MAR11.jpg',
      ),
      '1' => array(
        'fid' => '12404',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'top3_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/top3_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97367',
        'status' => '1',
        'timestamp' => '1298581096',
        'origname' => 'top3_MAR11.jpg',
      ),
      '2' => array(
        'fid' => '12405',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'top4_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/top4_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101936',
        'status' => '1',
        'timestamp' => '1298581110',
        'origname' => 'top4_MAR11.jpg',
      ),
      '3' => array(
        'fid' => '12406',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'top5_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/top5_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '125038',
        'status' => '1',
        'timestamp' => '1298581123',
        'origname' => 'top5_MAR11.jpg',
      ),
      '4' => array(
        'fid' => '12407',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'top6_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/top6_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85392',
        'status' => '1',
        'timestamp' => '1298581134',
        'origname' => 'top6_MAR11.jpg',
      ),
      '5' => array(
        'fid' => '12408',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'top7_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/top7_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77326',
        'status' => '1',
        'timestamp' => '1298581144',
        'origname' => 'top7_MAR11.jpg',
      ),
      '6' => array(
        'fid' => '12409',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'top8_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/top8_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84756',
        'status' => '1',
        'timestamp' => '1298581157',
        'origname' => 'top8_MAR11.jpg',
      ),
      '7' => array(
        'fid' => '12410',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'top9_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/top9_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94793',
        'status' => '1',
        'timestamp' => '1298581255',
        'origname' => 'top9_MAR11.jpg',
      ),
    ),
    'path' => 'stories/top-it',
    'tags' => array(
      '5' => array(
        '2519' => array(
          'tid' => '2519',
          'vid' => '5',
          'name' => 'BILLY WINTERS',
          'description' => 'http://www.billywinters.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'BILLY WINTERS',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
