array(
  array(
    'nid' => '3627',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1301004114',
    'changed' => '1403918096',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3627',
    'revision_uid' => '1',
    'title' => 'Night Time',
    'body' => '<p>
	Into the night.<br />
	Exclusive photography by Joel Esposito<br />
	Model ~&nbsp; Jessa @ Sutherland.</p>
',
    'teaser' => '<p>
	Into the night.<br />
	Exclusive photography by Joel Esposito<br />
	Model ~&nbsp; Jessa @ Sutherland.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918096',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	JOEL ESPOSITO</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	STEPHANIE MARK<br />
	@ PLUTINO</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	JESSA @ SUTHERLAND</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		TOPSHOP</li>
	<li>
		JONATHAN + OLIVIA</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12413',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nightime_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/nightime_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65538',
        'status' => '1',
        'timestamp' => '1298584755',
        'origname' => 'nightime_MAR11.jpg',
      ),
      '1' => array(
        'fid' => '12414',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nightime2_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/nightime2_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126187',
        'status' => '1',
        'timestamp' => '1298584791',
        'origname' => 'nightime2_MAR11.jpg',
      ),
      '2' => array(
        'fid' => '12649',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nightime3_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/nightime3_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103757',
        'status' => '1',
        'timestamp' => '1301183146',
        'origname' => 'nightime3_MAR11.jpg',
      ),
      '3' => array(
        'fid' => '12639',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-5_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '57877',
        'status' => '1',
        'timestamp' => '1300833905',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12640',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-6_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75131',
        'status' => '1',
        'timestamp' => '1300833916',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12418',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nightime6_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/nightime6_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18428',
        'status' => '1',
        'timestamp' => '1298584833',
        'origname' => 'nightime6_MAR11.jpg',
      ),
      '6' => array(
        'fid' => '12641',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-8_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '69078',
        'status' => '1',
        'timestamp' => '1300833937',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12650',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9_4.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-9_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '192572',
        'status' => '1',
        'timestamp' => '1301184244',
        'origname' => 'Layout-1_Page-9_4.jpg',
      ),
      '8' => array(
        'fid' => '12644',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nightime9_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/nightime9_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82507',
        'status' => '1',
        'timestamp' => '1301063205',
        'origname' => 'nightime9_MAR11.jpg',
      ),
      '9' => array(
        'fid' => '12645',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nightime10_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/nightime10_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13657',
        'status' => '1',
        'timestamp' => '1301063233',
        'origname' => 'nightime10_MAR11.jpg',
      ),
      '10' => array(
        'fid' => '12423',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nightime11_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/nightime11_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15679',
        'status' => '1',
        'timestamp' => '1298584895',
        'origname' => 'nightime11_MAR11.jpg',
      ),
      '11' => array(
        'fid' => '12643',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-13_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95614',
        'status' => '1',
        'timestamp' => '1300834012',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/night-time-0',
    'tags' => array(
      '5' => array(
        '2618' => array(
          'tid' => '2618',
          'vid' => '5',
          'name' => 'JOEL ESPOSITO',
          'description' => 'http://www.joelesposito.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '201' => array(
          'tid' => '201',
          'vid' => '1',
          'name' => 'JONATHAN + OLIVIA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '200' => array(
          'tid' => '200',
          'vid' => '1',
          'name' => 'TOPSHOP',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JOEL ESPOSITO',
        '1' => 'JONATHAN + OLIVIA, TOPSHOP',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
