array(
  array(
    'nid' => '3629',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1300404290',
    'changed' => '1403918096',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3629',
    'revision_uid' => '1',
    'title' => 'My Little Pony',
    'body' => '<p>
	Ride &#39;em cowgirl.<br />
	Exclusive photography by <a href="http://scottzane.com/">Scott Zane</a> .<br />
	Model ~&nbsp; Elena K @ Front.</p>
',
    'teaser' => '<p>
	Ride &#39;em cowgirl.<br />
	Exclusive photography by <a href="http://scottzane.com/">Scott Zane</a> .<br />
	Model ~&nbsp; Elena K @ Front.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918096',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://scottzane.com/" target="_blank"><span>Scott Zane</span></a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	<a href="http://melaniewhittle.com/index2.php#/home/">MELANIE WHITTLE</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	ELENA K @ FRONT</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		JIL SANDER</li>
	<li>
		LUCCHESE</li>
	<li>
		ALLSAINTS</li>
	<li>
		ANTHROPOLOGIE</li>
	<li>
		RALPH LAUREN</li>
	<li>
		ALICE AND OLIVIA</li>
	<li>
		AMERICAN APPAREL</li>
	<li>
		LA PERLA</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12426',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '37823',
        'status' => '1',
        'timestamp' => '1298589747',
        'origname' => 'mylittle_MAR11.jpg',
      ),
      '1' => array(
        'fid' => '12427',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle2_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle2_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '150338',
        'status' => '1',
        'timestamp' => '1298589758',
        'origname' => 'mylittle2_MAR11.jpg',
      ),
      '2' => array(
        'fid' => '12428',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle3_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle3_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '166926',
        'status' => '1',
        'timestamp' => '1298589770',
        'origname' => 'mylittle3_MAR11.jpg',
      ),
      '3' => array(
        'fid' => '12429',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle4_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle4_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '23551',
        'status' => '1',
        'timestamp' => '1298589780',
        'origname' => 'mylittle4_MAR11.jpg',
      ),
      '4' => array(
        'fid' => '12430',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle5_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle5_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '1298589790',
        'origname' => 'mylittle5_MAR11.jpg',
      ),
      '5' => array(
        'fid' => '12431',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle6_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle6_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126353',
        'status' => '1',
        'timestamp' => '1298589802',
        'origname' => 'mylittle6_MAR11.jpg',
      ),
      '6' => array(
        'fid' => '12432',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle7_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle7_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '238087',
        'status' => '1',
        'timestamp' => '1298589814',
        'origname' => 'mylittle7_MAR11.jpg',
      ),
      '7' => array(
        'fid' => '12433',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle8_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle8_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '201599',
        'status' => '1',
        'timestamp' => '1298589827',
        'origname' => 'mylittle8_MAR11.jpg',
      ),
      '8' => array(
        'fid' => '12434',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle9_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle9_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18623',
        'status' => '1',
        'timestamp' => '1298589841',
        'origname' => 'mylittle9_MAR11.jpg',
      ),
      '9' => array(
        'fid' => '12435',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle10_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle10_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '200997',
        'status' => '1',
        'timestamp' => '1298589854',
        'origname' => 'mylittle10_MAR11.jpg',
      ),
      '10' => array(
        'fid' => '12436',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle11_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle11_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '159091',
        'status' => '1',
        'timestamp' => '1298589869',
        'origname' => 'mylittle11_MAR11.jpg',
      ),
      '11' => array(
        'fid' => '12437',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mylittle12_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/mylittle12_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '185118',
        'status' => '1',
        'timestamp' => '1298589881',
        'origname' => 'mylittle12_MAR11.jpg',
      ),
    ),
    'path' => 'stories/my-little-pony',
    'tags' => array(
      '1' => array(
        '190' => array(
          'tid' => '190',
          'vid' => '1',
          'name' => 'ALICE AND OLIVIA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '187' => array(
          'tid' => '187',
          'vid' => '1',
          'name' => 'ALLSAINTS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '129' => array(
          'tid' => '129',
          'vid' => '1',
          'name' => 'American Apparel',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '188' => array(
          'tid' => '188',
          'vid' => '1',
          'name' => 'ANTHROPOLOGIE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '185' => array(
          'tid' => '185',
          'vid' => '1',
          'name' => 'JIL SANDER',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '191' => array(
          'tid' => '191',
          'vid' => '1',
          'name' => 'LA PERLA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '186' => array(
          'tid' => '186',
          'vid' => '1',
          'name' => 'LUCCHESE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '189' => array(
          'tid' => '189',
          'vid' => '1',
          'name' => 'RALPH LAUREN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2619' => array(
          'tid' => '2619',
          'vid' => '5',
          'name' => 'Scott Zane',
          'description' => 'http://scottzane.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'ALICE AND OLIVIA, ALLSAINTS, American Apparel, ANTHROPOLOGIE, JIL SANDER, LA PERLA, LUCCHESE, RALPH LAUREN',
        '5' => 'Scott Zane',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
