array(
  array(
    'nid' => '3631',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1300540115',
    'changed' => '1403917832',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3631',
    'revision_uid' => '1',
    'title' => 'Brisk',
    'body' => '<p>
	Grab a jacket; it&#39;s brisk baby.<br />
	Exclusive photography by <a href="http://www.skphotography.ca/">Sophie Kinachtchouk</a>.<br />
	Model ~&nbsp; Mike Di Carlo @ Ford.</p>
',
    'teaser' => '<p>
	Grab a jacket; it&#39;s brisk baby.<br />
	Exclusive photography by <a href="http://www.skphotography.ca/">Sophie Kinachtchouk</a>.<br />
	Model ~&nbsp; Mike Di Carlo @ Ford.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917832',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.skphotography.ca/">SOPHIE KINACHTCHOUK</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	JAMES N</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	MIKE DI CARLO @ FORD</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		ELEVEN PARIS</li>
	<li>
		ELVIS JESUS</li>
	<li>
		BLUE BLOOD</li>
	<li>
		SUIT</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12439',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132870',
        'status' => '1',
        'timestamp' => '1298639153',
        'origname' => 'brisk_MAR11.jpg',
      ),
      '1' => array(
        'fid' => '12440',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk2_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk2_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101102',
        'status' => '1',
        'timestamp' => '1298639163',
        'origname' => 'brisk2_MAR11.jpg',
      ),
      '2' => array(
        'fid' => '12442',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk3_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk3_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114633',
        'status' => '1',
        'timestamp' => '1298639172',
        'origname' => 'brisk3_MAR11.jpg',
      ),
      '3' => array(
        'fid' => '12443',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk4_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk4_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113382',
        'status' => '1',
        'timestamp' => '1298639178',
        'origname' => 'brisk4_MAR11.jpg',
      ),
      '4' => array(
        'fid' => '12444',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk5_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk5_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '189044',
        'status' => '1',
        'timestamp' => '1298639188',
        'origname' => 'brisk5_MAR11.jpg',
      ),
      '5' => array(
        'fid' => '12445',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk6_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk6_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '188355',
        'status' => '1',
        'timestamp' => '1298639198',
        'origname' => 'brisk6_MAR11.jpg',
      ),
      '6' => array(
        'fid' => '12446',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk7_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk7_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15154',
        'status' => '1',
        'timestamp' => '1298639206',
        'origname' => 'brisk7_MAR11.jpg',
      ),
      '7' => array(
        'fid' => '12447',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk8_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk8_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '217429',
        'status' => '1',
        'timestamp' => '1298639217',
        'origname' => 'brisk8_MAR11.jpg',
      ),
      '8' => array(
        'fid' => '12448',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk9_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk9_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '183561',
        'status' => '1',
        'timestamp' => '1298639228',
        'origname' => 'brisk9_MAR11.jpg',
      ),
      '9' => array(
        'fid' => '12449',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk10_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk10_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '210536',
        'status' => '1',
        'timestamp' => '1298639241',
        'origname' => 'brisk10_MAR11.jpg',
      ),
      '10' => array(
        'fid' => '12450',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk11_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk11_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137648',
        'status' => '1',
        'timestamp' => '1298639251',
        'origname' => 'brisk11_MAR11.jpg',
      ),
      '11' => array(
        'fid' => '12451',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk12_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk12_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108247',
        'status' => '1',
        'timestamp' => '1298639260',
        'origname' => 'brisk12_MAR11.jpg',
      ),
      '12' => array(
        'fid' => '12452',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk13_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk13_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95521',
        'status' => '1',
        'timestamp' => '1298639270',
        'origname' => 'brisk13_MAR11.jpg',
      ),
      '13' => array(
        'fid' => '12453',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk14_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk14_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '142590',
        'status' => '1',
        'timestamp' => '1298639279',
        'origname' => 'brisk14_MAR11.jpg',
      ),
      '14' => array(
        'fid' => '12454',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk15_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk15_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167598',
        'status' => '1',
        'timestamp' => '1298639290',
        'origname' => 'brisk15_MAR11.jpg',
      ),
      '15' => array(
        'fid' => '12455',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'brisk16_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/brisk16_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '171379',
        'status' => '1',
        'timestamp' => '1298639302',
        'origname' => 'brisk16_MAR11.jpg',
      ),
    ),
    'path' => 'stories/brisk',
    'tags' => array(
      '1' => array(
        '125' => array(
          'tid' => '125',
          'vid' => '1',
          'name' => 'Blue Blood',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '128' => array(
          'tid' => '128',
          'vid' => '1',
          'name' => 'Eleven Paris',
          'description' => 'elevenparis.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '131' => array(
          'tid' => '131',
          'vid' => '1',
          'name' => 'ELVIS JESUS',
          'description' => 'elvisjesus.co.uk',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '127' => array(
          'tid' => '127',
          'vid' => '1',
          'name' => 'Suit',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2429' => array(
          'tid' => '2429',
          'vid' => '5',
          'name' => 'Sophie Kinachtchouk',
          'description' => 'http://www.skphotography.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Blue Blood, Eleven Paris, ELVIS JESUS, Suit',
        '4' => 'men',
        '5' => 'Sophie Kinachtchouk',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
