array(
  array(
    'nid' => '3633',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1299850847',
    'changed' => '1403918097',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3633',
    'revision_uid' => '1',
    'title' => 'Moody',
    'body' => '<p>
	In the mood?<br />
	Exclusive photography by <a href="http://www.alanchanstudio.com/" target="_blank"><span>Alan Chan</span></a>.<br />
	Model ~&nbsp; Laura K @ Next.</p>
',
    'teaser' => '<p>
	In the mood?<br />
	Exclusive photography by <a href="http://www.alanchanstudio.com/" target="_blank"><span>Alan Chan</span></a>.<br />
	Model ~&nbsp; Laura K @ Next.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918097',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.alanchanstudio.com/" target="_blank">ALAN CHAN</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	<a href="http://janetlistyling.carbonmade.com/" target="_blank">JANET LI</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	LAURA K @ NEXT</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		ALEXANDER WANG</li>
	<li>
		OBAKKI</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12473',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '43714',
        'status' => '1',
        'timestamp' => '1298641666',
        'origname' => 'moody_MAR11.jpg',
      ),
      '1' => array(
        'fid' => '12474',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody2_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody2_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '194616',
        'status' => '1',
        'timestamp' => '1298641676',
        'origname' => 'moody2_MAR11.jpg',
      ),
      '2' => array(
        'fid' => '12460',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody3_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody3_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19393',
        'status' => '1',
        'timestamp' => '1298641144',
        'origname' => 'moody3_MAR11.jpg',
      ),
      '3' => array(
        'fid' => '12471',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody4_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody4_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96826',
        'status' => '1',
        'timestamp' => '1298641335',
        'origname' => 'moody4_MAR11.jpg',
      ),
      '4' => array(
        'fid' => '12461',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody5_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody5_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '176899',
        'status' => '1',
        'timestamp' => '1298641150',
        'origname' => 'moody5_MAR11.jpg',
      ),
      '5' => array(
        'fid' => '12462',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody6_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody6_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '152453',
        'status' => '1',
        'timestamp' => '1298641160',
        'origname' => 'moody6_MAR11.jpg',
      ),
      '6' => array(
        'fid' => '12463',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody7_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody7_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161697',
        'status' => '1',
        'timestamp' => '1298641169',
        'origname' => 'moody7_MAR11.jpg',
      ),
      '7' => array(
        'fid' => '12464',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody8_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody8_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '144239',
        'status' => '1',
        'timestamp' => '1298641176',
        'origname' => 'moody8_MAR11.jpg',
      ),
      '8' => array(
        'fid' => '12465',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody9_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody9_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '268891',
        'status' => '1',
        'timestamp' => '1298641184',
        'origname' => 'moody9_MAR11.jpg',
      ),
      '9' => array(
        'fid' => '12466',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody10_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody10_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '225468',
        'status' => '1',
        'timestamp' => '1298641194',
        'origname' => 'moody10_MAR11.jpg',
      ),
      '10' => array(
        'fid' => '12467',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody11_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody11_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93389',
        'status' => '1',
        'timestamp' => '1298641203',
        'origname' => 'moody11_MAR11.jpg',
      ),
      '11' => array(
        'fid' => '12468',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody12_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody12_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '266404',
        'status' => '1',
        'timestamp' => '1298641218',
        'origname' => 'moody12_MAR11.jpg',
      ),
      '12' => array(
        'fid' => '12469',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody13_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody13_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153038',
        'status' => '1',
        'timestamp' => '1298641226',
        'origname' => 'moody13_MAR11.jpg',
      ),
      '13' => array(
        'fid' => '12470',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'moody14_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/moody14_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90665',
        'status' => '1',
        'timestamp' => '1298641235',
        'origname' => 'moody14_MAR11.jpg',
      ),
    ),
    'path' => 'stories/moody',
    'tags' => array(
      '5' => array(
        '2620' => array(
          'tid' => '2620',
          'vid' => '5',
          'name' => 'ALAN CHAN',
          'description' => 'http://www.alanchanstudio.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ALAN CHAN',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
