array(
  array(
    'nid' => '3637',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1301094726',
    'changed' => '1337804604',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3637',
    'revision_uid' => '1',
    'title' => 'Esprit De Corps',
    'body' => '<p>
	Atten-hut.<br />
	Exclusive photography by <a href="http://www.annathiessen.com/">Anna Thiessen</a>.<br />
	Model ~&nbsp; Kayte @ Muse.</p>
',
    'teaser' => '<p>
	Atten-hut.<br />
	Exclusive photography by <a href="http://www.annathiessen.com/">Anna Thiessen</a>.<br />
	Model ~&nbsp; Kayte @ Muse.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804604',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.annathiessen.com/">ANNA THIESSEN</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	RENESSTA OLDS</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	KAYTE @ MUSE</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		TRINA TURK</li>
	<li>
		ZADIG &amp; VOLTAIRE</li>
	<li>
		SUNGHEE BANG</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12498',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154413',
        'status' => '1',
        'timestamp' => '1298675379',
        'origname' => 'esprit_MAR11.jpg',
      ),
      '1' => array(
        'fid' => '12499',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit2_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit2_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130708',
        'status' => '1',
        'timestamp' => '1298675389',
        'origname' => 'esprit2_MAR11.jpg',
      ),
      '2' => array(
        'fid' => '12500',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit3_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit3_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '23432',
        'status' => '1',
        'timestamp' => '1298675400',
        'origname' => 'esprit3_MAR11.jpg',
      ),
      '3' => array(
        'fid' => '12501',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit4_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit4_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '99300',
        'status' => '1',
        'timestamp' => '1298675412',
        'origname' => 'esprit4_MAR11.jpg',
      ),
      '4' => array(
        'fid' => '12502',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit5_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit5_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78086',
        'status' => '1',
        'timestamp' => '1298675425',
        'origname' => 'esprit5_MAR11.jpg',
      ),
      '5' => array(
        'fid' => '12503',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit6_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit6_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '23649',
        'status' => '1',
        'timestamp' => '1298675434',
        'origname' => 'esprit6_MAR11.jpg',
      ),
      '6' => array(
        'fid' => '12504',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit7_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit7_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18391',
        'status' => '1',
        'timestamp' => '1298675445',
        'origname' => 'esprit7_MAR11.jpg',
      ),
      '7' => array(
        'fid' => '12505',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit8_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit8_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73196',
        'status' => '1',
        'timestamp' => '1298675457',
        'origname' => 'esprit8_MAR11.jpg',
      ),
      '8' => array(
        'fid' => '12506',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit9_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit9_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77628',
        'status' => '1',
        'timestamp' => '1298675474',
        'origname' => 'esprit9_MAR11.jpg',
      ),
      '9' => array(
        'fid' => '12507',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit10_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit10_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20345',
        'status' => '1',
        'timestamp' => '1298675486',
        'origname' => 'esprit10_MAR11.jpg',
      ),
      '10' => array(
        'fid' => '12508',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit11_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit11_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18530',
        'status' => '1',
        'timestamp' => '1298675500',
        'origname' => 'esprit11_MAR11.jpg',
      ),
      '11' => array(
        'fid' => '12509',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'esprit12_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/esprit12_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84083',
        'status' => '1',
        'timestamp' => '1298675515',
        'origname' => 'esprit12_MAR11.jpg',
      ),
    ),
    'path' => 'stories/esprit-de-corps',
    'tags' => array(
      '5' => array(
        '2621' => array(
          'tid' => '2621',
          'vid' => '5',
          'name' => 'ANNA THIESSEN',
          'description' => 'http://www.annathiessen.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '199' => array(
          'tid' => '199',
          'vid' => '1',
          'name' => 'SUNGHEE BANG',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '91' => array(
          'tid' => '91',
          'vid' => '1',
          'name' => 'TRINA TURK',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '198' => array(
          'tid' => '198',
          'vid' => '1',
          'name' => 'ZADIG & VOLTAIRE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ANNA THIESSEN',
        '1' => 'SUNGHEE BANG, TRINA TURK, ZADIG & VOLTAIRE',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
