array(
  array(
    'nid' => '3641',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1301494335',
    'changed' => '1403918096',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3641',
    'revision_uid' => '1',
    'title' => 'Color Coded',
    'body' => '<p>
	Brighten up.<br />
	Exclusive photography by <a href="http://www.frankrubio.net/"><span style="text-decoration: underline;">Frank Rubio</span></a>.<br />
	Model ~&nbsp; Lauren Lewis @ Next.</p>
',
    'teaser' => '<p>
	Brighten up.<br />
	Exclusive photography by <a href="http://www.frankrubio.net/"><span style="text-decoration: underline;">Frank Rubio</span></a>.<br />
	Model ~&nbsp; Lauren Lewis @ Next.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918096',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.frankrubio.net/">Frank Rubio</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	CARLOS DAVIS @ MC2</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	LAUREN LEWIS @ NEXT</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		JELLYFISH</li>
	<li>
		KRELWEAR</li>
	<li>
		LUPE POSSE</li>
	<li>
		NATASHA MORGAN</li>
	<li>
		PAMELA MARCUZZI</li>
	<li>
		MARIA CAMILA MESA</li>
	<li>
		NIKKI POULOS</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12526',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112908',
        'status' => '1',
        'timestamp' => '1298902045',
        'origname' => 'color_MAR11.jpg',
      ),
      '1' => array(
        'fid' => '12527',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color2_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color2_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '214276',
        'status' => '1',
        'timestamp' => '1298902059',
        'origname' => 'color2_MAR11.jpg',
      ),
      '2' => array(
        'fid' => '12528',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color3_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color3_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82111',
        'status' => '1',
        'timestamp' => '1298902068',
        'origname' => 'color3_MAR11.jpg',
      ),
      '3' => array(
        'fid' => '12529',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color4_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color4_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '49654',
        'status' => '1',
        'timestamp' => '1298902082',
        'origname' => 'color4_MAR11.jpg',
      ),
      '4' => array(
        'fid' => '12530',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color5_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color5_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '37550',
        'status' => '1',
        'timestamp' => '1298902101',
        'origname' => 'color5_MAR11.jpg',
      ),
      '5' => array(
        'fid' => '12531',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color6_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color6_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93054',
        'status' => '1',
        'timestamp' => '1298902113',
        'origname' => 'color6_MAR11.jpg',
      ),
      '6' => array(
        'fid' => '12532',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color7_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color7_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85004',
        'status' => '1',
        'timestamp' => '1298902187',
        'origname' => 'color7_MAR11.jpg',
      ),
      '7' => array(
        'fid' => '12533',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color8_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color8_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '47463',
        'status' => '1',
        'timestamp' => '1298902200',
        'origname' => 'color8_MAR11.jpg',
      ),
      '8' => array(
        'fid' => '12534',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color9_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color9_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134772',
        'status' => '1',
        'timestamp' => '1298902216',
        'origname' => 'color9_MAR11.jpg',
      ),
      '9' => array(
        'fid' => '12535',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color10_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color10_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96435',
        'status' => '1',
        'timestamp' => '1298902239',
        'origname' => 'color10_MAR11.jpg',
      ),
      '10' => array(
        'fid' => '12536',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color11_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color11_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '47003',
        'status' => '1',
        'timestamp' => '1298902257',
        'origname' => 'color11_MAR11.jpg',
      ),
      '11' => array(
        'fid' => '12537',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color12_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color12_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61721',
        'status' => '1',
        'timestamp' => '1298902277',
        'origname' => 'color12_MAR11.jpg',
      ),
      '12' => array(
        'fid' => '12538',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color13_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color13_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98186',
        'status' => '1',
        'timestamp' => '1298902290',
        'origname' => 'color13_MAR11.jpg',
      ),
      '13' => array(
        'fid' => '12539',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color14_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color14_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '43128',
        'status' => '1',
        'timestamp' => '1298902301',
        'origname' => 'color14_MAR11.jpg',
      ),
      '14' => array(
        'fid' => '12540',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color15_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color15_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '37194',
        'status' => '1',
        'timestamp' => '1298902311',
        'origname' => 'color15_MAR11.jpg',
      ),
      '15' => array(
        'fid' => '12541',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'color16_MAR11.jpg',
        'filepath' => 'files/fmag_story/2011/Feb/color16_MAR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114272',
        'status' => '1',
        'timestamp' => '1298902324',
        'origname' => 'color16_MAR11.jpg',
      ),
    ),
    'path' => 'stories/color-coded',
    'tags' => array(
      '5' => array(
        '2622' => array(
          'tid' => '2622',
          'vid' => '5',
          'name' => 'Frank Rubio',
          'description' => 'http://www.frankrubio.net/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '205' => array(
          'tid' => '205',
          'vid' => '1',
          'name' => 'JELLYFISH',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '206' => array(
          'tid' => '206',
          'vid' => '1',
          'name' => 'KRELWEAR',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '207' => array(
          'tid' => '207',
          'vid' => '1',
          'name' => 'LUPE POSSE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '210' => array(
          'tid' => '210',
          'vid' => '1',
          'name' => 'MARIA CAMILA MESA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '208' => array(
          'tid' => '208',
          'vid' => '1',
          'name' => 'NATASHA MORGAN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '211' => array(
          'tid' => '211',
          'vid' => '1',
          'name' => 'NIKKI POULOS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '209' => array(
          'tid' => '209',
          'vid' => '1',
          'name' => 'PAMELA MARCUZZI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Frank Rubio',
        '1' => 'JELLYFISH, KRELWEAR, LUPE POSSE, MARIA CAMILA MESA, NATASHA MORGAN, NIKKI POULOS, PAMELA MARCUZZI',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
