array(
  array(
    'nid' => '3647',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1300822611',
    'changed' => '1403917832',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3647',
    'revision_uid' => '1',
    'title' => 'Day Tripper',
    'body' => '<p>
	Trippy.<br />
	Exclusive photography by <a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a>.<br />
	Models ~&nbsp; Lauren, Adam Alex &amp; Brett @ Exalt. Kelsey &amp; Troy @ Stars. Landry @ City.</p>
',
    'teaser' => '<p>
	Trippy.<br />
	Exclusive photography by <a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a>.<br />
	Models ~&nbsp; Lauren, Adam Alex &amp; Brett @ Exalt. Kelsey &amp; Troy @ Stars. Landry @ City.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917832',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a></p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	LAUREN<br />
	ADAM<br />
	ALEX<br />
	BRETT @ EXALT<br />
	KELSEY<br />
	TROY @ STARS<br />
	LANDRY @ CITY<br />
	&nbsp;</p>
<p>
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		TRACY DENHAM</li>
	<li>
		MARC JACOBS</li>
	<li>
		THEORY</li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12622',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-2_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '168312',
        'status' => '1',
        'timestamp' => '1300822596',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12623',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-3_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '272718',
        'status' => '1',
        'timestamp' => '1300822723',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12624',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-4_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '190754',
        'status' => '1',
        'timestamp' => '1300822966',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12625',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '186919',
        'status' => '1',
        'timestamp' => '1300823006',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12626',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-6_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11378',
        'status' => '1',
        'timestamp' => '1300823017',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12627',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-7_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '150729',
        'status' => '1',
        'timestamp' => '1300823040',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12628',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-8_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '165066',
        'status' => '1',
        'timestamp' => '1300823091',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12629',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-9_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '150023',
        'status' => '1',
        'timestamp' => '1300823104',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12630',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-10_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '200082',
        'status' => '1',
        'timestamp' => '1300823113',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12631',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-11_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17265',
        'status' => '1',
        'timestamp' => '1300823131',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12632',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-12_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '182566',
        'status' => '1',
        'timestamp' => '1300823144',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12633',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-13_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20895',
        'status' => '1',
        'timestamp' => '1300823153',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '12634',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-14_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '177895',
        'status' => '1',
        'timestamp' => '1300823192',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '12635',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-15_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137861',
        'status' => '1',
        'timestamp' => '1300823209',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '12636',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-16_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '235696',
        'status' => '1',
        'timestamp' => '1300823221',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '12637',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-17_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '225708',
        'status' => '1',
        'timestamp' => '1300823348',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
    ),
    'path' => 'stories/day-tripper',
    'tags' => array(
      '5' => array(
        '2519' => array(
          'tid' => '2519',
          'vid' => '5',
          'name' => 'BILLY WINTERS',
          'description' => 'http://www.billywinters.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '203' => array(
          'tid' => '203',
          'vid' => '1',
          'name' => 'MARC JACOBS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '204' => array(
          'tid' => '204',
          'vid' => '1',
          'name' => 'THEORY',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => array(
            'ext_url' => '',
          ),
          '#_export_node_encode_object' => '1',
        ),
        '202' => array(
          'tid' => '202',
          'vid' => '1',
          'name' => 'TRACY DENHAM',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'BILLY WINTERS',
        '1' => 'MARC JACOBS, THEORY, TRACY DENHAM',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
