array(
  array(
    'nid' => '3649',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1301331253',
    'changed' => '1403917831',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3649',
    'revision_uid' => '1',
    'title' => 'Blue Wave',
    'body' => '<p>
	He&#39;s feeling blue but in a good way.<br />
	Exclusive photography by <a href="http://www.skphotography.ca/">Sophie Kinachtchouk</a>.<br />
	Model ~&nbsp; Thomson @ Elmer Olsen.</p>
',
    'teaser' => '<p>
	He&#39;s feeling blue but in a good way.<br />
	Exclusive photography by <a href="http://www.skphotography.ca/">Sophie Kinachtchouk</a>.<br />
	Model ~&nbsp; Thomson @ Elmer Olsen.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917831',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.skphotography.ca/">SOPHIE KINACHTCHOUK</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	JAMES NIXON</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	THOMSON @ ELMER OLSEN</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		CHEAP MONDAY</li>
	<li>
		VANISHING ELEPHANT</li>
	<li>
		LIFE/AFTER/DENIM</li>
	<li>
		LEVIS</li>
	<li>
		H&amp;M</li>
	<li>
		ROGUE&#39;S GALLERY</li>
	<li>
		ELVIS JESUS</li>
	<li>
		HUDSON&#39;S BAY COMPANY</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12684',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-2_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '356470',
        'status' => '1',
        'timestamp' => '1301333048',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12652',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-3_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '45480',
        'status' => '1',
        'timestamp' => '1301331197',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12654',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-4_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95725',
        'status' => '1',
        'timestamp' => '1301331210',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12656',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-5_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131939',
        'status' => '1',
        'timestamp' => '1301331218',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12658',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-6_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161843',
        'status' => '1',
        'timestamp' => '1301331229',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12659',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-7_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109518',
        'status' => '1',
        'timestamp' => '1301331236',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12661',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-8_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13252',
        'status' => '1',
        'timestamp' => '1301331291',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12662',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-9_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91100',
        'status' => '1',
        'timestamp' => '1301331299',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12681',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-10_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '262035',
        'status' => '1',
        'timestamp' => '1301332580',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12665',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-11_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141406',
        'status' => '1',
        'timestamp' => '1301331323',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12666',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-12_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14982',
        'status' => '1',
        'timestamp' => '1301331331',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12667',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-13_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86067',
        'status' => '1',
        'timestamp' => '1301331342',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '12668',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-14_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67777',
        'status' => '1',
        'timestamp' => '1301332196',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '12669',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-15_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '198904',
        'status' => '1',
        'timestamp' => '1301332208',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '12671',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-16_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1301332220',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '12672',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-17_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73049',
        'status' => '1',
        'timestamp' => '1301332229',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '16' => array(
        'fid' => '12673',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-18_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1301332242',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
      '17' => array(
        'fid' => '12674',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-19.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-19_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88753',
        'status' => '1',
        'timestamp' => '1301332253',
        'origname' => 'Layout-1_Page-19.jpg',
      ),
      '18' => array(
        'fid' => '12682',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-20.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-20_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '287965',
        'status' => '1',
        'timestamp' => '1301332603',
        'origname' => 'Layout-1_Page-20.jpg',
      ),
      '19' => array(
        'fid' => '12683',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-21.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-21_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '261566',
        'status' => '1',
        'timestamp' => '1301332619',
        'origname' => 'Layout-1_Page-21.jpg',
      ),
      '20' => array(
        'fid' => '12677',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-22.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-22_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101710',
        'status' => '1',
        'timestamp' => '1301332385',
        'origname' => 'Layout-1_Page-22.jpg',
      ),
      '21' => array(
        'fid' => '12678',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-23.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-23_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104399',
        'status' => '1',
        'timestamp' => '1301332396',
        'origname' => 'Layout-1_Page-23.jpg',
      ),
      '22' => array(
        'fid' => '12679',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-24.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-24_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122937',
        'status' => '1',
        'timestamp' => '1301332409',
        'origname' => 'Layout-1_Page-24.jpg',
      ),
      '23' => array(
        'fid' => '12680',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-25.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/Layout-1_Page-25_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106447',
        'status' => '1',
        'timestamp' => '1301332423',
        'origname' => 'Layout-1_Page-25.jpg',
      ),
    ),
    'path' => 'stories/blue-wave',
    'tags' => array(
      '1' => array(
        '192' => array(
          'tid' => '192',
          'vid' => '1',
          'name' => 'CHEAP MONDAY',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '131' => array(
          'tid' => '131',
          'vid' => '1',
          'name' => 'ELVIS JESUS',
          'description' => 'elvisjesus.co.uk',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '31' => array(
          'tid' => '31',
          'vid' => '1',
          'name' => 'H&M',
          'description' => 'www.hm.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '308' => array(
          'tid' => '308',
          'vid' => '1',
          'name' => 'HUDSON\'S BAY COMPANY',
          'description' => 'www.thebay.com/eng/men-thebay',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '195' => array(
          'tid' => '195',
          'vid' => '1',
          'name' => 'LEVIS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '194' => array(
          'tid' => '194',
          'vid' => '1',
          'name' => 'LIFE/AFTER/DENIM',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '197' => array(
          'tid' => '197',
          'vid' => '1',
          'name' => 'ROGUE\'S GALLERY',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '193' => array(
          'tid' => '193',
          'vid' => '1',
          'name' => 'VANISHING ELEPHANT',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2429' => array(
          'tid' => '2429',
          'vid' => '5',
          'name' => 'Sophie Kinachtchouk',
          'description' => 'http://www.skphotography.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'CHEAP MONDAY, ELVIS JESUS, H&M, HUDSON\'S BAY COMPANY, LEVIS, LIFE/AFTER/DENIM, ROGUE\'S GALLERY, VANISHING ELEPHANT',
        '4' => 'men',
        '5' => 'Sophie Kinachtchouk',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
