array(
  array(
    'nid' => '3651',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1301673035',
    'changed' => '1337804545',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3651',
    'revision_uid' => '1',
    'title' => 'Feet First',
    'body' => '<p>
	If the shoe fits...<br />
	Exclusive photography by <a href="http://www.michaelfranco.net/">Michael Franco</a>.<br />
	Models ~&nbsp; Eric Eisele &amp; Ryan Belton.</p>
',
    'teaser' => '<p>
	If the shoe fits...<br />
	Exclusive photography by <a href="http://www.michaelfranco.net/">Michael Franco</a>.<br />
	Models ~&nbsp; Eric Eisele &amp; Ryan Belton.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804545',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.michaelfranco.net/">MICHAEL FRANCO</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODELS<br />
	ERIC EISELE<br />
	&amp; RYAN BELTON</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		TEVA</li>
	<li>
		TSUBO</li>
	<li>
		HEYDAY</li>
	<li>
		LOUIS VUITTON</li>
	<li>
		GUCCI</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12686',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '151132',
        'status' => '1',
        'timestamp' => '1301499870',
        'origname' => 'feet_mar11.jpg',
      ),
      '1' => array(
        'fid' => '12687',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet2_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet2_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104362',
        'status' => '1',
        'timestamp' => '1301499885',
        'origname' => 'feet2_mar11.jpg',
      ),
      '2' => array(
        'fid' => '12688',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet3_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet3_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75809',
        'status' => '1',
        'timestamp' => '1301499901',
        'origname' => 'feet3_mar11.jpg',
      ),
      '3' => array(
        'fid' => '12689',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet4_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet4_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61171',
        'status' => '1',
        'timestamp' => '1301499916',
        'origname' => 'feet4_mar11.jpg',
      ),
      '4' => array(
        'fid' => '12690',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet5_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet5_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58762',
        'status' => '1',
        'timestamp' => '1301499930',
        'origname' => 'feet5_mar11.jpg',
      ),
      '5' => array(
        'fid' => '12691',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet6_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet6_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '48452',
        'status' => '1',
        'timestamp' => '1301499966',
        'origname' => 'feet6_mar11.jpg',
      ),
      '6' => array(
        'fid' => '12692',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet7_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet7_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '50758',
        'status' => '1',
        'timestamp' => '1301499984',
        'origname' => 'feet7_mar11.jpg',
      ),
      '7' => array(
        'fid' => '12693',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet8_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet8_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13464',
        'status' => '1',
        'timestamp' => '1301499999',
        'origname' => 'feet8_mar11.jpg',
      ),
      '8' => array(
        'fid' => '12694',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet9_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet9_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14693',
        'status' => '1',
        'timestamp' => '1301500016',
        'origname' => 'feet9_mar11.jpg',
      ),
      '9' => array(
        'fid' => '12695',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet10_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet10_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '56654',
        'status' => '1',
        'timestamp' => '1301500032',
        'origname' => 'feet10_mar11.jpg',
      ),
      '10' => array(
        'fid' => '12696',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet11_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet11_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66270',
        'status' => '1',
        'timestamp' => '1301500047',
        'origname' => 'feet11_mar11.jpg',
      ),
      '11' => array(
        'fid' => '12709',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '59354',
        'status' => '1',
        'timestamp' => '1301669841',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '12698',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet13_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet13_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63081',
        'status' => '1',
        'timestamp' => '1301500081',
        'origname' => 'feet13_mar11.jpg',
      ),
      '13' => array(
        'fid' => '12699',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet14_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet14_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72237',
        'status' => '1',
        'timestamp' => '1301500099',
        'origname' => 'feet14_mar11.jpg',
      ),
      '14' => array(
        'fid' => '12700',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet15_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet15_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13485',
        'status' => '1',
        'timestamp' => '1301500114',
        'origname' => 'feet15_mar11.jpg',
      ),
      '15' => array(
        'fid' => '12701',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet16_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet16_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82787',
        'status' => '1',
        'timestamp' => '1301500130',
        'origname' => 'feet16_mar11.jpg',
      ),
      '16' => array(
        'fid' => '12702',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet17_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet17_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95078',
        'status' => '1',
        'timestamp' => '1301500146',
        'origname' => 'feet17_mar11.jpg',
      ),
      '17' => array(
        'fid' => '12703',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet18_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet18_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94188',
        'status' => '1',
        'timestamp' => '1301500162',
        'origname' => 'feet18_mar11.jpg',
      ),
      '18' => array(
        'fid' => '12704',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet19_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet19_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '45701',
        'status' => '1',
        'timestamp' => '1301500178',
        'origname' => 'feet19_mar11.jpg',
      ),
      '19' => array(
        'fid' => '12705',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet20_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet20_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92927',
        'status' => '1',
        'timestamp' => '1301500194',
        'origname' => 'feet20_mar11.jpg',
      ),
      '20' => array(
        'fid' => '12706',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet21_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet21_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '1301500208',
        'origname' => 'feet21_mar11.jpg',
      ),
      '21' => array(
        'fid' => '12707',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'feet22_mar11.jpg',
        'filepath' => 'files/fmag_story/2011/Mar/feet22_mar11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72371',
        'status' => '1',
        'timestamp' => '1301500225',
        'origname' => 'feet22_mar11.jpg',
      ),
    ),
    'path' => 'stories/feet-first',
    'tags' => array(
      '1' => array(
        '215' => array(
          'tid' => '215',
          'vid' => '1',
          'name' => 'GUCCI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '214' => array(
          'tid' => '214',
          'vid' => '1',
          'name' => 'HEYDAY',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '158' => array(
          'tid' => '158',
          'vid' => '1',
          'name' => 'LOUIS VUITTON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '212' => array(
          'tid' => '212',
          'vid' => '1',
          'name' => 'TEVA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '216' => array(
          'tid' => '216',
          'vid' => '1',
          'name' => 'TSUBO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2465' => array(
          'tid' => '2465',
          'vid' => '5',
          'name' => 'MICHAEL FRANCO',
          'description' => 'http://www.michaelfranco.net/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'GUCCI, HEYDAY, LOUIS VUITTON, TEVA, TSUBO',
        '5' => 'MICHAEL FRANCO',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
