array(
  array(
    'nid' => '3653',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1301685673',
    'changed' => '1337804562',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3653',
    'revision_uid' => '1',
    'title' => 'Rain',
    'body' => '<p>
	Look to the sky.<br />
	Exclusive photography by <a href="http://www.susannekindt.com/">SUSANNE KINDT</a>.<br />
	Model ~&nbsp; Amanda S @ Photogenics.</p>
',
    'teaser' => '<p>
	Look to the sky.<br />
	Exclusive photography by <a href="http://www.susannekindt.com/">SUSANNE KINDT</a>.<br />
	Model ~&nbsp; Amanda S @ Photogenics.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804562',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.susannekindt.com/">SUSANNE KINDT</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	KRISSIE TORGERSON</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	AMANDA S</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		MARIA FRANCESCA PEPE</li>
	<li>
		ODILON</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12710',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '55659',
        'status' => '1',
        'timestamp' => '1301685511',
        'origname' => 'rain_apr11.jpg',
      ),
      '1' => array(
        'fid' => '12711',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain2_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain2_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72722',
        'status' => '1',
        'timestamp' => '1301685528',
        'origname' => 'rain2_apr11.jpg',
      ),
      '2' => array(
        'fid' => '12712',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain3_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain3_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97410',
        'status' => '1',
        'timestamp' => '1301685541',
        'origname' => 'rain3_apr11.jpg',
      ),
      '3' => array(
        'fid' => '12713',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain4_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain4_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16335',
        'status' => '1',
        'timestamp' => '1301685551',
        'origname' => 'rain4_apr11.jpg',
      ),
      '4' => array(
        'fid' => '12714',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain5_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain5_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '115538',
        'status' => '1',
        'timestamp' => '1301685563',
        'origname' => 'rain5_apr11.jpg',
      ),
      '5' => array(
        'fid' => '12715',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain6_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain6_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16038',
        'status' => '1',
        'timestamp' => '1301685577',
        'origname' => 'rain6_apr11.jpg',
      ),
      '6' => array(
        'fid' => '12716',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain7_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain7_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '233048',
        'status' => '1',
        'timestamp' => '1301685591',
        'origname' => 'rain7_apr11.jpg',
      ),
      '7' => array(
        'fid' => '12717',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain8_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain8_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '184324',
        'status' => '1',
        'timestamp' => '1301685604',
        'origname' => 'rain8_apr11.jpg',
      ),
      '8' => array(
        'fid' => '12718',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain9_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain9_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '110364',
        'status' => '1',
        'timestamp' => '1301685621',
        'origname' => 'rain9_apr11.jpg',
      ),
      '9' => array(
        'fid' => '12719',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain10_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain10_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16621',
        'status' => '1',
        'timestamp' => '1301685632',
        'origname' => 'rain10_apr11.jpg',
      ),
      '10' => array(
        'fid' => '12720',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain11_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain11_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104305',
        'status' => '1',
        'timestamp' => '1301685646',
        'origname' => 'rain11_apr11.jpg',
      ),
      '11' => array(
        'fid' => '12721',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'rain12_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/rain12_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '62114',
        'status' => '1',
        'timestamp' => '1301685658',
        'origname' => 'rain12_apr11.jpg',
      ),
    ),
    'path' => 'stories/rain',
    'tags' => array(
      '1' => array(
        '217' => array(
          'tid' => '217',
          'vid' => '1',
          'name' => 'MARIA FRANCESCA PEPE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '218' => array(
          'tid' => '218',
          'vid' => '1',
          'name' => 'ODILON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2623' => array(
          'tid' => '2623',
          'vid' => '5',
          'name' => 'SUSANNE KINDT',
          'description' => 'http://www.susannekindt.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'MARIA FRANCESCA PEPE, ODILON',
        '5' => 'SUSANNE KINDT',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
