array(
  array(
    'nid' => '3654',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1301950463',
    'changed' => '1403918096',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3654',
    'revision_uid' => '1',
    'title' => 'Boy Meets Girl',
    'body' => '<p>
	The ole story... boy meets girl... boy steals her look.<br />
	Exclusive photography by <a href="http://www.katandduck.com/">Kat + DUCK</a>.<br />
	Models ~&nbsp; Marie Moreau &amp; Max Schneider @ Major.</p>
',
    'teaser' => '<p>
	The ole story... boy meets girl... boy steals her look.<br />
	Exclusive photography by <a href="http://www.katandduck.com/">Kat + DUCK</a>.<br />
	Models ~&nbsp; Marie Moreau &amp; Max Schneider @ Major.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918096',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.katandduck.com/">KAT + DUCK</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	ANGELINA VIVACE</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODELS<br />
	MARIE MOREAU<br />
	&amp; MAX SCHNEIDER<br />
	@ MAJOR</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		JUMA</li>
	<li>
		WICCE</li>
	<li>
		TRIBAL COUTURE</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12770',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156856',
        'status' => '1',
        'timestamp' => '1302109277',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12723',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87112',
        'status' => '1',
        'timestamp' => '1301691210',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12724',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78731',
        'status' => '1',
        'timestamp' => '1301691223',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12725',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '64249',
        'status' => '1',
        'timestamp' => '1301691236',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12726',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65570',
        'status' => '1',
        'timestamp' => '1301691491',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12727',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '43504',
        'status' => '1',
        'timestamp' => '1301691505',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12728',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '59520',
        'status' => '1',
        'timestamp' => '1301691521',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12729',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '49182',
        'status' => '1',
        'timestamp' => '1301691536',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12730',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78602',
        'status' => '1',
        'timestamp' => '1301691549',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12731',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '21825',
        'status' => '1',
        'timestamp' => '1301691563',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12732',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '51841',
        'status' => '1',
        'timestamp' => '1301691575',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12733',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-13_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83024',
        'status' => '1',
        'timestamp' => '1301691589',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '12734',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '28702',
        'status' => '1',
        'timestamp' => '1301691601',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '12735',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122541',
        'status' => '1',
        'timestamp' => '1301691615',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
    ),
    'path' => 'stories/boy-meets-girl',
    'tags' => array(
      '1' => array(
        '219' => array(
          'tid' => '219',
          'vid' => '1',
          'name' => 'JUMA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '221' => array(
          'tid' => '221',
          'vid' => '1',
          'name' => 'TRIBAL COUTURE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '220' => array(
          'tid' => '220',
          'vid' => '1',
          'name' => 'WICCE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2624' => array(
          'tid' => '2624',
          'vid' => '5',
          'name' => 'KAT + DUCK',
          'description' => 'http://www.katandduck.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'JUMA, TRIBAL COUTURE, WICCE',
        '5' => 'KAT + DUCK',
        '4' => 'men, women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
