array(
  array(
    'nid' => '3659',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1302195388',
    'changed' => '1337804510',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3659',
    'revision_uid' => '1',
    'title' => 'Holiday Inn',
    'body' => '<p>
	She&#39;s a-trip.<br />
	Exclusive photography by <a href="http://www.pierospoggi.com/">PIERO SPOGGI</a>.&nbsp;<br />
	Model ~&nbsp; Carolina Ballesteros @ Uno BCN.</p>
',
    'teaser' => '<p>
	She&#39;s a-trip.<br />
	Exclusive photography by <a href="http://www.pierospoggi.com/">PIERO SPOGGI</a>.&nbsp;<br />
	Model ~&nbsp; Carolina Ballesteros @ Uno BCN.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804510',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.pierospoggi.com/">PIERO SPOGGI</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	PATTY CEREIJO</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	CAROLINA BALLESTEROS<br />
	@ UNO BCN</p>
<p>
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		ARMAND BASI</li>
	<li>
		COS</li>
	<li>
		TONY FRANCESC</li>
	<li>
		PRADA</li>
	<li>
		ZARA</li>
	<li>
		MIRIAM OCARIZ</li>
	<li>
		STUART WEISZMAN</li>
	<li>
		RELIGION</li>
	<li>
		SONIA RYKIEL<br />
		&nbsp;</li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12760',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'holiday_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/holiday_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '206082',
        'status' => '1',
        'timestamp' => '1302108870',
        'origname' => 'holiday_apr11.jpg',
      ),
      '1' => array(
        'fid' => '12761',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'holiday2_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/holiday2_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '198308',
        'status' => '1',
        'timestamp' => '1302108881',
        'origname' => 'holiday2_apr11.jpg',
      ),
      '2' => array(
        'fid' => '12762',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'holiday3_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/holiday3_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154565',
        'status' => '1',
        'timestamp' => '1302108893',
        'origname' => 'holiday3_apr11.jpg',
      ),
      '3' => array(
        'fid' => '12763',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'holiday4_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/holiday4_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '142627',
        'status' => '1',
        'timestamp' => '1302108903',
        'origname' => 'holiday4_apr11.jpg',
      ),
      '4' => array(
        'fid' => '12764',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'holiday5_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/holiday5_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113364',
        'status' => '1',
        'timestamp' => '1302108915',
        'origname' => 'holiday5_apr11.jpg',
      ),
      '5' => array(
        'fid' => '12765',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'holiday6_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/holiday6_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119164',
        'status' => '1',
        'timestamp' => '1302108929',
        'origname' => 'holiday6_apr11.jpg',
      ),
      '6' => array(
        'fid' => '12766',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'holiday7_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/holiday7_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130009',
        'status' => '1',
        'timestamp' => '1302108941',
        'origname' => 'holiday7_apr11.jpg',
      ),
      '7' => array(
        'fid' => '12767',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'holiday8_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/holiday8_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81251',
        'status' => '1',
        'timestamp' => '1302108951',
        'origname' => 'holiday8_apr11.jpg',
      ),
      '8' => array(
        'fid' => '12768',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'holiday9_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/holiday9_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129216',
        'status' => '1',
        'timestamp' => '1302108964',
        'origname' => 'holiday9_apr11.jpg',
      ),
      '9' => array(
        'fid' => '12769',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'holiday10_apr11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/holiday10_apr11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81825',
        'status' => '1',
        'timestamp' => '1302108975',
        'origname' => 'holiday10_apr11.jpg',
      ),
    ),
    'path' => 'stories/holiday-inn',
    'tags' => array(
      '1' => array(
        '222' => array(
          'tid' => '222',
          'vid' => '1',
          'name' => 'ARMAND BASI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '223' => array(
          'tid' => '223',
          'vid' => '1',
          'name' => 'COS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '225' => array(
          'tid' => '225',
          'vid' => '1',
          'name' => 'MIRIAM OCARIZ',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '107' => array(
          'tid' => '107',
          'vid' => '1',
          'name' => 'PRADA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '130' => array(
          'tid' => '130',
          'vid' => '1',
          'name' => 'RELIGION',
          'description' => 'religionclothing.co.uk',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '227' => array(
          'tid' => '227',
          'vid' => '1',
          'name' => 'SONIA RYKIEL',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '226' => array(
          'tid' => '226',
          'vid' => '1',
          'name' => 'STUART WEISZMAN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '224' => array(
          'tid' => '224',
          'vid' => '1',
          'name' => 'TONY FRANCESC',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '155' => array(
          'tid' => '155',
          'vid' => '1',
          'name' => 'ZARA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2625' => array(
          'tid' => '2625',
          'vid' => '5',
          'name' => 'PIERO SPOGGI',
          'description' => 'http://www.pierospoggi.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'ARMAND BASI, COS, MIRIAM OCARIZ, PRADA, RELIGION, SONIA RYKIEL, STUART WEISZMAN, TONY FRANCESC, ZARA',
        '5' => 'PIERO SPOGGI',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
