array(
  array(
    'nid' => '3661',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1302383078',
    'changed' => '1337804498',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3661',
    'revision_uid' => '1',
    'title' => 'Lady In Red',
    'body' => '<p>
	He&#39;s an animal and she&#39;s a basket case.<br />
	Exclusive photography by <a href="http://www.juntanphoto.com/">Jun Tan</a>.<br />
	Models ~&nbsp; Joanna R @ Standalone &amp; Leo @ First.</p>
',
    'teaser' => '<p>
	He&#39;s an animal and she&#39;s a basket case.<br />
	Exclusive photography by <a href="http://www.juntanphoto.com/">Jun Tan</a>.<br />
	Models ~&nbsp; Joanna R @ Standalone &amp; Leo @ First.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804498',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.juntanphoto.com/">JUN TAN</a><br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	SIMONE SYLVESTER</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODELS<br />
	JOANNA R<br />
	@ STANDALONE<br />
	LEO @ FIRST</p>
<p>
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		PIERRE GARROUDI</li>
	<li>
		AMERICAN APPAREL<br />
		&nbsp;</li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12773',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-2_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114098',
        'status' => '1',
        'timestamp' => '1302296543',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12775',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-3_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128920',
        'status' => '1',
        'timestamp' => '1302296548',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12776',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-4_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '187760',
        'status' => '1',
        'timestamp' => '1302296554',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12777',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '183303',
        'status' => '1',
        'timestamp' => '1302296580',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12778',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-6_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140369',
        'status' => '1',
        'timestamp' => '1302296592',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12779',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-7_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126942',
        'status' => '1',
        'timestamp' => '1302296604',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12786',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-8_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '162977',
        'status' => '1',
        'timestamp' => '1302297163',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12781',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-9_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173878',
        'status' => '1',
        'timestamp' => '1302296625',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12782',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-10_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101246',
        'status' => '1',
        'timestamp' => '1302296634',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12783',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-11_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104498',
        'status' => '1',
        'timestamp' => '1302296646',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12784',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-12_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '147664',
        'status' => '1',
        'timestamp' => '1302296656',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12785',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-13_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '182506',
        'status' => '1',
        'timestamp' => '1302296667',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/lady-red',
    'tags' => array(
      '5' => array(
        '2626' => array(
          'tid' => '2626',
          'vid' => '5',
          'name' => 'JUN TAN',
          'description' => 'http://www.juntanphoto.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JUN TAN',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
