array(
  array(
    'nid' => '3663',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1302550236',
    'changed' => '1403917831',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3663',
    'revision_uid' => '1',
    'title' => 'Prepitary Academy',
    'body' => '<p>
	Tenhut prepster.</p>
<p>
	Exclusive photography by <a href="http://www.mikelewis.ca/" target="_blank">MIKE LEWIS</a>.</p>
<p>
	Model ~&nbsp; Gavin Dunne @ Elmer Olsen.</p>
',
    'teaser' => '<p>
	Tenhut prepster.</p>
<p>
	Exclusive photography by <a href="http://www.mikelewis.ca/" target="_blank">MIKE LEWIS</a>.</p>
<p>
	Model ~&nbsp; Gavin Dunne @ Elmer Olsen.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917831',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.mikelewis.ca/" target="_blank">MIKE LEWIS</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	FASHION EDITOR<br />
	JAMES N</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	GAVIN DUNNE<br />
	@ ELMER OLSEN<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		RELIGION</li>
	<li>
		LACOSTE</li>
	<li>
		LIFE/AFTER/DENIM</li>
	<li>
		H&amp;M</li>
	<li>
		ELVIS JESUS</li>
	<li>
		ELEVIN PARIS</li>
	<li>
		SUIT</li>
	<li>
		TOPMAN<br />
		&nbsp;</li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12831',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-2_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '240584',
        'status' => '1',
        'timestamp' => '1302553423',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12789',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-3_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '144449',
        'status' => '1',
        'timestamp' => '1302550141',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12790',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-4_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161942',
        'status' => '1',
        'timestamp' => '1302550150',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12791',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-5_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67199',
        'status' => '1',
        'timestamp' => '1302550163',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12815',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-6_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100078',
        'status' => '1',
        'timestamp' => '1302551783',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12793',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-7_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1302550183',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12816',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-8_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15839',
        'status' => '1',
        'timestamp' => '1302551796',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12817',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-9_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84316',
        'status' => '1',
        'timestamp' => '1302551863',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12818',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-10_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94078',
        'status' => '1',
        'timestamp' => '1302551877',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12813',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-11_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1302550715',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12819',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-12_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86999',
        'status' => '1',
        'timestamp' => '1302551902',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12799',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-13_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65678',
        'status' => '1',
        'timestamp' => '1302550318',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '12800',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-14_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66106',
        'status' => '1',
        'timestamp' => '1302550335',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '12801',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-15_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60819',
        'status' => '1',
        'timestamp' => '1302550346',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '12820',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-16_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90000',
        'status' => '1',
        'timestamp' => '1302551932',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '12821',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-17_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1302551960',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '16' => array(
        'fid' => '12822',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15563',
        'status' => '1',
        'timestamp' => '1302551975',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
      '17' => array(
        'fid' => '12823',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-19.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-19.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96266',
        'status' => '1',
        'timestamp' => '1302551989',
        'origname' => 'Layout-1_Page-19.jpg',
      ),
      '18' => array(
        'fid' => '12806',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-20.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-20.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65941',
        'status' => '1',
        'timestamp' => '1302550412',
        'origname' => 'Layout-1_Page-20.jpg',
      ),
      '19' => array(
        'fid' => '12828',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-21.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-21.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72626',
        'status' => '1',
        'timestamp' => '1302552259',
        'origname' => 'Layout-1_Page-21.jpg',
      ),
      '20' => array(
        'fid' => '12829',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-22.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-22.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85630',
        'status' => '1',
        'timestamp' => '1302552273',
        'origname' => 'Layout-1_Page-22.jpg',
      ),
      '21' => array(
        'fid' => '12814',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-23.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-23.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74349',
        'status' => '1',
        'timestamp' => '1302550744',
        'origname' => 'Layout-1_Page-23.jpg',
      ),
      '22' => array(
        'fid' => '12824',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-24.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-24.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127503',
        'status' => '1',
        'timestamp' => '1302552034',
        'origname' => 'Layout-1_Page-24.jpg',
      ),
      '23' => array(
        'fid' => '12825',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-25.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-25.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13352',
        'status' => '1',
        'timestamp' => '1302552048',
        'origname' => 'Layout-1_Page-25.jpg',
      ),
      '24' => array(
        'fid' => '12826',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-26.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-26.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14920',
        'status' => '1',
        'timestamp' => '1302552061',
        'origname' => 'Layout-1_Page-26.jpg',
      ),
      '25' => array(
        'fid' => '12827',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-27.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-27.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96544',
        'status' => '1',
        'timestamp' => '1302552073',
        'origname' => 'Layout-1_Page-27.jpg',
      ),
    ),
    'path' => 'stories/prepitary-academy',
    'tags' => array(
      '1' => array(
        '128' => array(
          'tid' => '128',
          'vid' => '1',
          'name' => 'Eleven Paris',
          'description' => 'elevenparis.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '131' => array(
          'tid' => '131',
          'vid' => '1',
          'name' => 'ELVIS JESUS',
          'description' => 'elvisjesus.co.uk',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '31' => array(
          'tid' => '31',
          'vid' => '1',
          'name' => 'H&M',
          'description' => 'www.hm.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '43' => array(
          'tid' => '43',
          'vid' => '1',
          'name' => 'Lacoste',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '194' => array(
          'tid' => '194',
          'vid' => '1',
          'name' => 'LIFE/AFTER/DENIM',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '130' => array(
          'tid' => '130',
          'vid' => '1',
          'name' => 'RELIGION',
          'description' => 'religionclothing.co.uk',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '127' => array(
          'tid' => '127',
          'vid' => '1',
          'name' => 'Suit',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '229' => array(
          'tid' => '229',
          'vid' => '1',
          'name' => 'TOPMAN',
          'description' => 'www.topman.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2550' => array(
          'tid' => '2550',
          'vid' => '5',
          'name' => 'Mike Lewis',
          'description' => 'http://www.mikelewis.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Eleven Paris, ELVIS JESUS, H&M, Lacoste, LIFE/AFTER/DENIM, RELIGION, Suit, TOPMAN',
        '4' => 'men',
        '5' => 'Mike Lewis',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
