array(
  array(
    'nid' => '3665',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1302702910',
    'changed' => '1403918095',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3665',
    'revision_uid' => '1',
    'title' => 'Cosmo Girl',
    'body' => '<p>
	Cosmo-politan.<br />
	Exclusive photography by&nbsp;<a href="http://www.duboisphotography.com/" target="_blank">RICHARD DUBOIS</a>.<br />
	Model ~&nbsp; Sarah Barnes @ Elmer Olsen.</p>
',
    'teaser' => '<p>
	Cosmo-politan.<br />
	Exclusive photography by&nbsp;<a href="http://www.duboisphotography.com/" target="_blank">RICHARD DUBOIS</a>.<br />
	Model ~&nbsp; Sarah Barnes @ Elmer Olsen.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918095',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.duboisphotography.com/" target="_blank">RICHARD DUBOIS</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	STYLING<br />
	JO-ANNA DAVIDSON</p>
<p>
	<br />
	MODEL<br />
	SARAH BARNES<br />
	@ ELMER OLSEN</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		ALEXANDER MCQUEEN</li>
	<li>
		ESCADA</li>
	<li>
		KARA ROSS</li>
	<li>
		MARIOLA</li>
	<li>
		GIUSEPPE ZANOTTI</li>
	<li>
		HALSTON</li>
	<li>
		HENRI BENDEL</li>
	<li>
		FREDERICK PRINCE</li>
	<li>
		SAM EDELMAN</li>
	<li>
		TORY BURCH&nbsp;</li>
	<li>
		PIERRE HARDY</li>
</ul>
<p>
	&nbsp;</p>
<ul>
	<br />
	<br />
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12832',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-2_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103532',
        'status' => '1',
        'timestamp' => '1302616140',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12833',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-3_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127894',
        'status' => '1',
        'timestamp' => '1302616187',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12834',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-4_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136757',
        'status' => '1',
        'timestamp' => '1302616224',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12835',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-5_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '52922',
        'status' => '1',
        'timestamp' => '1302616241',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12836',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-6_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95996',
        'status' => '1',
        'timestamp' => '1302616421',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12837',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-7_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '178668',
        'status' => '1',
        'timestamp' => '1302616437',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12838',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-8_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77337',
        'status' => '1',
        'timestamp' => '1302616447',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12839',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-9_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '125344',
        'status' => '1',
        'timestamp' => '1302616460',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12840',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-10_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107054',
        'status' => '1',
        'timestamp' => '1302616470',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12841',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-11_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73098',
        'status' => '1',
        'timestamp' => '1302616482',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12842',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-12_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108245',
        'status' => '1',
        'timestamp' => '1302616490',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12843',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-13_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132792',
        'status' => '1',
        'timestamp' => '1302616500',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/cosmo-girl',
    'tags' => array(
      '1' => array(
        '230' => array(
          'tid' => '230',
          'vid' => '1',
          'name' => 'ALEXANDER MCQUEEN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '231' => array(
          'tid' => '231',
          'vid' => '1',
          'name' => 'ESCADA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '237' => array(
          'tid' => '237',
          'vid' => '1',
          'name' => 'FREDERICK PRINCE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '234' => array(
          'tid' => '234',
          'vid' => '1',
          'name' => 'GIUSEPPE ZANOTTI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '235' => array(
          'tid' => '235',
          'vid' => '1',
          'name' => 'HALSTON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '236' => array(
          'tid' => '236',
          'vid' => '1',
          'name' => 'HENRI BENDEL',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '232' => array(
          'tid' => '232',
          'vid' => '1',
          'name' => 'KARA ROSS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '233' => array(
          'tid' => '233',
          'vid' => '1',
          'name' => 'MARIOLA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '240' => array(
          'tid' => '240',
          'vid' => '1',
          'name' => 'PIERRE HARDY',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '238' => array(
          'tid' => '238',
          'vid' => '1',
          'name' => 'SAM EDELMAN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '239' => array(
          'tid' => '239',
          'vid' => '1',
          'name' => 'TORY BURCH',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2550' => array(
          'tid' => '2550',
          'vid' => '5',
          'name' => 'Mike Lewis',
          'description' => 'http://www.mikelewis.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'ALEXANDER MCQUEEN, ESCADA, FREDERICK PRINCE, GIUSEPPE ZANOTTI, HALSTON, HENRI BENDEL, KARA ROSS, MARIOLA, PIERRE HARDY, SAM EDELMAN, TORY BURCH',
        '5' => 'Mike Lewis',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
