array(
  array(
    'nid' => '3667',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1302902338',
    'changed' => '1337804634',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3667',
    'revision_uid' => '1',
    'title' => 'Bright Idea',
    'body' => '<p>
	Color commentary.<br />
	Exclusive photography by <a href="http://curtisbenjamin.com/">Curtis Benjamin</a>.<br />
	Models ~&nbsp; Josh Parkinson @ Select &amp; Eric Monjoin @ Nevs.</p>
',
    'teaser' => '<p>
	Color commentary.<br />
	Exclusive photography by <a href="http://curtisbenjamin.com/">Curtis Benjamin</a>.<br />
	Models ~&nbsp; Josh Parkinson @ Select &amp; Eric Monjoin @ Nevs.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804634',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://curtisbenjamin.com/">CURTIS BENJAMIN</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	STYLING<br />
	<a href="http://www.soboyesoong.com/">SAMSON SOBOYE</a></p>
<p>
	<br />
	MODELS<br />
	JOSH PARKINSON<br />
	@ SELECT<br />
	ERIC MONJOIN<br />
	@ NEVS</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		UNIQLO</li>
	<li>
		CHRISTOPHER SHANNON</li>
	<li>
		CALVIN KLEIN</li>
	<li>
		TIMBERLAND</li>
	<li>
		DARK ROOM</li>
	<li>
		EDE &amp; RAVENSCROFT</li>
	<li>
		HENRI LLOYD</li>
	<li>
		SAMSON SABOYE</li>
	<li>
		FIRETRAP</li>
	<li>
		MARTIN BAL</li>
	<li>
		CANALI</li>
	<li>
		ENERGIE</li>
	<li>
		FOGOTTEN FUTURE</li>
	<li>
		MATTHEW WILLIAMSON</li>
	<li>
		ETRO</li>
	<li>
		LES HOMMES</li>
</ul>
<p>
	&nbsp;</p>
<p>
	<br />
	<br />
	&nbsp;</p>
<ul>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12846',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-2_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107253',
        'status' => '1',
        'timestamp' => '1302902233',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12862',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-3_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112774',
        'status' => '1',
        'timestamp' => '1302903220',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12848',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-4_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '27739',
        'status' => '1',
        'timestamp' => '1302902267',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12849',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-5_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88408',
        'status' => '1',
        'timestamp' => '1302902279',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12850',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-6_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90947',
        'status' => '1',
        'timestamp' => '1302902289',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12851',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-7_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112714',
        'status' => '1',
        'timestamp' => '1302902304',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12852',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-8_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16853',
        'status' => '1',
        'timestamp' => '1302902316',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12853',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-9_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136701',
        'status' => '1',
        'timestamp' => '1302902327',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12854',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-10_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89630',
        'status' => '1',
        'timestamp' => '1302902417',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12855',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-11_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17401',
        'status' => '1',
        'timestamp' => '1302902427',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12856',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-12_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101361',
        'status' => '1',
        'timestamp' => '1302902437',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12857',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-13_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103196',
        'status' => '1',
        'timestamp' => '1302902447',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '12858',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-14_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72339',
        'status' => '1',
        'timestamp' => '1302902456',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '12859',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-15_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19486',
        'status' => '1',
        'timestamp' => '1302902464',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '12860',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-16_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22373',
        'status' => '1',
        'timestamp' => '1302902473',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '12861',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-17_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160708',
        'status' => '1',
        'timestamp' => '1302902487',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
    ),
    'path' => 'stories/bright-idea',
    'tags' => array(
      '1' => array(
        '52' => array(
          'tid' => '52',
          'vid' => '1',
          'name' => 'calvin Klein',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '245' => array(
          'tid' => '245',
          'vid' => '1',
          'name' => 'CANAL',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '252' => array(
          'tid' => '252',
          'vid' => '1',
          'name' => 'CHRISTOPHER SHANNON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '254' => array(
          'tid' => '254',
          'vid' => '1',
          'name' => 'DARK ROOM',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '255' => array(
          'tid' => '255',
          'vid' => '1',
          'name' => 'EDE & RAVENSCROFT',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '246' => array(
          'tid' => '246',
          'vid' => '1',
          'name' => 'ENERGIE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '249' => array(
          'tid' => '249',
          'vid' => '1',
          'name' => 'ETRO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '243' => array(
          'tid' => '243',
          'vid' => '1',
          'name' => 'FIRETRAP',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '251' => array(
          'tid' => '251',
          'vid' => '1',
          'name' => 'FOGOTTEN FUTURE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '256' => array(
          'tid' => '256',
          'vid' => '1',
          'name' => 'HENRI LLOYD',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '250' => array(
          'tid' => '250',
          'vid' => '1',
          'name' => 'LES HOMMES',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '244' => array(
          'tid' => '244',
          'vid' => '1',
          'name' => 'MARTIN BAL',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '248' => array(
          'tid' => '248',
          'vid' => '1',
          'name' => 'MATTHEW WILLIAMSON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '242' => array(
          'tid' => '242',
          'vid' => '1',
          'name' => 'SAMSON SABOY',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '253' => array(
          'tid' => '253',
          'vid' => '1',
          'name' => 'TIMBERLAND',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '156' => array(
          'tid' => '156',
          'vid' => '1',
          'name' => 'UNIQLO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2627' => array(
          'tid' => '2627',
          'vid' => '5',
          'name' => 'CURTIS BENJAMIN',
          'description' => 'http://curtisbenjamin.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'calvin Klein, CANAL, CHRISTOPHER SHANNON, DARK ROOM, EDE & RAVENSCROFT, ENERGIE, ETRO, FIRETRAP, FOGOTTEN FUTURE, HENRI LLOYD, LES HOMMES, MARTIN BAL, MATTHEW WILLIAMSON, SAMSON SABOY, TIMBERLAND, UNIQLO',
        '5' => 'CURTIS BENJAMIN',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
