array(
  array(
    'nid' => '3669',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1303156552',
    'changed' => '1337804475',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3669',
    'revision_uid' => '1',
    'title' => 'Doll In A House',
    'body' => '<p>
	Because life is just theater.<br />
	Exclusive photography by <a href="http://ericgranwehr.viewbook.com/">Eric Granwehr</a>.<br />
	Model ~&nbsp; Emma Beam @ Major.</p>
',
    'teaser' => '<p>
	Because life is just theater.<br />
	Exclusive photography by <a href="http://ericgranwehr.viewbook.com/">Eric Granwehr</a>.<br />
	Model ~&nbsp; Emma Beam @ Major.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804475',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://ericgranwehr.viewbook.com/">ERIC GRANWEHR</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	EMMA BEAM<br />
	@ MAJOR</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		KIMBERLY TAYLOR<br />
		&nbsp;</li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12864',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-2_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '30465',
        'status' => '1',
        'timestamp' => '1303156425',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12865',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-3_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100241',
        'status' => '1',
        'timestamp' => '1303156445',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12866',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-4_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68368',
        'status' => '1',
        'timestamp' => '1303156457',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12867',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-5_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61296',
        'status' => '1',
        'timestamp' => '1303156467',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12868',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-6_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '37386',
        'status' => '1',
        'timestamp' => '1303156477',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12869',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-7_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '70539',
        'status' => '1',
        'timestamp' => '1303156488',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12870',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-8_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '49362',
        'status' => '1',
        'timestamp' => '1303156498',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12871',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-9_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60387',
        'status' => '1',
        'timestamp' => '1303156508',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12875',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-10_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '70938',
        'status' => '1',
        'timestamp' => '1303156627',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12872',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-11_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93593',
        'status' => '1',
        'timestamp' => '1303156520',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12873',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-12_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '47520',
        'status' => '1',
        'timestamp' => '1303156531',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12874',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-13_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '46226',
        'status' => '1',
        'timestamp' => '1303156541',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/doll-house',
    'tags' => array(
      '5' => array(
        '2628' => array(
          'tid' => '2628',
          'vid' => '5',
          'name' => 'ERIC GRANWEHR',
          'description' => 'http://ericgranwehr.viewbook.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ERIC GRANWEHR',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
