array(
  array(
    'nid' => '3673',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1303487680',
    'changed' => '1403918095',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3673',
    'revision_uid' => '1',
    'title' => 'Concrete',
    'body' => '<p>
	Blossom in a cement garden.<br />
	Exclusive photography by <a href="http://www.paulfarnham.com/">PAUL FARNHAM</a>.<br />
	Model ~&nbsp; Leona @ Next.</p>
',
    'teaser' => '<p>
	Blossom in a cement garden.<br />
	Exclusive photography by <a href="http://www.paulfarnham.com/">PAUL FARNHAM</a>.<br />
	Model ~&nbsp; Leona @ Next.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918095',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.paulfarnham.com/">PAUL FARNHAM</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	SARA DARLING</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	LEONA @ NEXT</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		RACHEL FRIERE</li>
	<li>
		PPQ</li>
	<li>
		PAM HOGG</li>
	<li>
		KIRSTY DOYLE</li>
	<li>
		HARRIET&#39;S MUSE</li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12907',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-2_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154731',
        'status' => '1',
        'timestamp' => '1303412909',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12908',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-3_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94004',
        'status' => '1',
        'timestamp' => '1303412916',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12909',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-4_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16809',
        'status' => '1',
        'timestamp' => '1303412923',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12910',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-5_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127918',
        'status' => '1',
        'timestamp' => '1303412936',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12911',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-6_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134807',
        'status' => '1',
        'timestamp' => '1303412969',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12912',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-7_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13084',
        'status' => '1',
        'timestamp' => '1303412979',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12913',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-8_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '195676',
        'status' => '1',
        'timestamp' => '1303412990',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12914',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-9_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68049',
        'status' => '1',
        'timestamp' => '1303414953',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12915',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-10_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81161',
        'status' => '1',
        'timestamp' => '1303414964',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12916',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-11_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13426',
        'status' => '1',
        'timestamp' => '1303414979',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12917',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-12_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1303414989',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12918',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-13_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '217425',
        'status' => '1',
        'timestamp' => '1303415037',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '12919',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-14_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '56049',
        'status' => '1',
        'timestamp' => '1303415052',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '12920',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-15_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123342',
        'status' => '1',
        'timestamp' => '1303415067',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '12921',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-16_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1303415079',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '12922',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-17_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60508',
        'status' => '1',
        'timestamp' => '1303415093',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '16' => array(
        'fid' => '12923',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-18_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '149310',
        'status' => '1',
        'timestamp' => '1303415107',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
      '17' => array(
        'fid' => '12924',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-19.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-19_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60366',
        'status' => '1',
        'timestamp' => '1303415119',
        'origname' => 'Layout-1_Page-19.jpg',
      ),
      '18' => array(
        'fid' => '12925',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-20.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-20_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78824',
        'status' => '1',
        'timestamp' => '1303415132',
        'origname' => 'Layout-1_Page-20.jpg',
      ),
      '19' => array(
        'fid' => '12926',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-21.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-21_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22531',
        'status' => '1',
        'timestamp' => '1303415143',
        'origname' => 'Layout-1_Page-21.jpg',
      ),
    ),
    'path' => 'stories/concrete',
    'tags' => array(
      '5' => array(
        '2629' => array(
          'tid' => '2629',
          'vid' => '5',
          'name' => 'PAUL FARNHAM',
          'description' => 'http://www.paulfarnham.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'PAUL FARNHAM',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
