array(
  array(
    'nid' => '3675',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1303752654',
    'changed' => '1403917831',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3675',
    'revision_uid' => '1',
    'title' => 'Gym Class',
    'body' => '<p>
	Class up your sweats.<br />
	Exclusive photography by Joel Esposito.<br />
	Models ~&nbsp; Daniel, Duncan, Justin, Michael &amp; Mike K @ Elmer Olsen.</p>
',
    'teaser' => '<p>
	Class up your sweats.<br />
	Exclusive photography by Joel Esposito.<br />
	Models ~&nbsp; Daniel, Duncan, Justin, Michael &amp; Mike K @ Elmer Olsen.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917831',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	JOEL ESPOSITO</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	JAMES NIXON</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODELS<br />
	DANIEL, DUNCAN, JUSTIN, MICHAEL, &amp; MIKE K @ ELMER OLSEN.</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		ELVIS JESUS</li>
	<li>
		RELIGION</li>
	<li>
		ELEVEN PARIS</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12929',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-2_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '70599',
        'status' => '1',
        'timestamp' => '1303752497',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12930',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-3_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66133',
        'status' => '1',
        'timestamp' => '1303752509',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12931',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-4_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67358',
        'status' => '1',
        'timestamp' => '1303752521',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12932',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-5_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16752',
        'status' => '1',
        'timestamp' => '1303752530',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12933',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-6_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71013',
        'status' => '1',
        'timestamp' => '1303752541',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12934',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-7_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '57678',
        'status' => '1',
        'timestamp' => '1303752551',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12935',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-8_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65516',
        'status' => '1',
        'timestamp' => '1303752561',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12936',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-9_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '51797',
        'status' => '1',
        'timestamp' => '1303752574',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12937',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-10_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66916',
        'status' => '1',
        'timestamp' => '1303752586',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12938',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-11_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104437',
        'status' => '1',
        'timestamp' => '1303752597',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12939',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-12_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83993',
        'status' => '1',
        'timestamp' => '1303752626',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12940',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-13_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67021',
        'status' => '1',
        'timestamp' => '1303752635',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/gym-class',
    'tags' => array(
      '1' => array(
        '128' => array(
          'tid' => '128',
          'vid' => '1',
          'name' => 'Eleven Paris',
          'description' => 'elevenparis.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '131' => array(
          'tid' => '131',
          'vid' => '1',
          'name' => 'ELVIS JESUS',
          'description' => 'elvisjesus.co.uk',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '130' => array(
          'tid' => '130',
          'vid' => '1',
          'name' => 'RELIGION',
          'description' => 'religionclothing.co.uk',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2618' => array(
          'tid' => '2618',
          'vid' => '5',
          'name' => 'JOEL ESPOSITO',
          'description' => 'http://www.joelesposito.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Eleven Paris, ELVIS JESUS, RELIGION',
        '5' => 'JOEL ESPOSITO',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
