array(
  array(
    'nid' => '3677',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1303942146',
    'changed' => '1403918095',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3677',
    'revision_uid' => '1',
    'title' => 'Block Party',
    'body' => '<p>
	Blocking blast.<br />
	Exclusive photography by <a href="http://www.claudiagoetzelmann.com/">Claudia Goetzelmann</a>.<br />
	Model ~&nbsp; Debra @ Look.</p>
',
    'teaser' => '<p>
	Blocking blast.<br />
	Exclusive photography by <a href="http://www.claudiagoetzelmann.com/">Claudia Goetzelmann</a>.<br />
	Model ~&nbsp; Debra @ Look.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918095',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.claudiagoetzelmann.com/">CLAUDIA GOETZELMANN</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	PAULINE MONTUPET</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	DEBRA @ LOOK</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		MAISON MARTIN MARGIELA</li>
	<li>
		DOLCE VITA</li>
	<li>
		KATE SPADE</li>
	<li>
		VICTOR &amp; ROLF</li>
	<li>
		EQUIPMENT</li>
	<li>
		FOREVER</li>
	<li>
		MANU</li>
	<li>
		YVES SAINT LAURENT</li>
	<li>
		BARNEYS NEW YORK</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12942',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-2_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '165276',
        'status' => '1',
        'timestamp' => '1303941957',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '12957',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-3_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78623',
        'status' => '1',
        'timestamp' => '1303998969',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12944',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-4_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '207781',
        'status' => '1',
        'timestamp' => '1303941979',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12945',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-5_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '188384',
        'status' => '1',
        'timestamp' => '1303941991',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12946',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-6_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '168405',
        'status' => '1',
        'timestamp' => '1303942006',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12947',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-7_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '121136',
        'status' => '1',
        'timestamp' => '1303942018',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12948',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-8_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103236',
        'status' => '1',
        'timestamp' => '1303942033',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12949',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-9_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '159486',
        'status' => '1',
        'timestamp' => '1303942043',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '12950',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-10_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129452',
        'status' => '1',
        'timestamp' => '1303942058',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '12951',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-11_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117074',
        'status' => '1',
        'timestamp' => '1303942069',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '12952',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-12_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '224352',
        'status' => '1',
        'timestamp' => '1303942086',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '12953',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-13_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '239520',
        'status' => '1',
        'timestamp' => '1303942100',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '12954',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-14_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131283',
        'status' => '1',
        'timestamp' => '1303942117',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '12955',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/Layout-1_Page-15_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '172904',
        'status' => '1',
        'timestamp' => '1303942136',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
    ),
    'path' => 'stories/block-party',
    'tags' => array(
      '1' => array(
        '284' => array(
          'tid' => '284',
          'vid' => '1',
          'name' => 'BARNEYS NEW YORK',
          'description' => '<a href="http://rstyle.me/ad/gj9i2pukw">barneys.com</a><div class="gallery-adbanner"><a href="http://rstyle.me/ad/gj9i2pukw" target="_blank"><img src="http://ad.linksynergy.com/fs-bin/show?id=QFGLnEolOWg&bids=306112.349&type=4" /></a></div>',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '277' => array(
          'tid' => '277',
          'vid' => '1',
          'name' => 'DOLCE VITA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '280' => array(
          'tid' => '280',
          'vid' => '1',
          'name' => 'EQUIPMENT',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '281' => array(
          'tid' => '281',
          'vid' => '1',
          'name' => 'FOREVER',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '278' => array(
          'tid' => '278',
          'vid' => '1',
          'name' => 'KATE SPADE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '276' => array(
          'tid' => '276',
          'vid' => '1',
          'name' => 'MAISON MARTIN MARGIELA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '282' => array(
          'tid' => '282',
          'vid' => '1',
          'name' => 'MANU',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '279' => array(
          'tid' => '279',
          'vid' => '1',
          'name' => 'VICTOR & ROLF',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '283' => array(
          'tid' => '283',
          'vid' => '1',
          'name' => 'YVES SAINT LAURENT',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2530' => array(
          'tid' => '2530',
          'vid' => '5',
          'name' => 'Claudia Goetzelmann',
          'description' => 'http://www.claudiagoetzelmann.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'BARNEYS NEW YORK, DOLCE VITA, EQUIPMENT, FOREVER, KATE SPADE, MAISON MARTIN MARGIELA, MANU, VICTOR & ROLF, YVES SAINT LAURENT',
        '5' => 'Claudia Goetzelmann',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
