array(
  array(
    'nid' => '3679',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1304100303',
    'changed' => '1337804436',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3679',
    'revision_uid' => '1',
    'title' => 'Strike It Up',
    'body' => '<p>
	Striking.<br />
	Exclusive photography by <a href="http://www.thomasknights.co.uk/">Thomas Knights</a>.<br />
	Model ~&nbsp; Alex Prinz @ D1.</p>
',
    'teaser' => '<p>
	Striking.<br />
	Exclusive photography by <a href="http://www.thomasknights.co.uk/">Thomas Knights</a>.<br />
	Model ~&nbsp; Alex Prinz @ D1.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804436',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.thomasknights.co.uk/">THOMAS KNIGHTS</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	CALLUM VINCENT</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	ALEX PRINZ @ D1</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		JEREMY SCOTT</li>
	<li>
		UNCONDITIONAL</li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12959',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '377737',
        'status' => '1',
        'timestamp' => '1304014021',
        'origname' => 'strike_APR11.jpg',
      ),
      '1' => array(
        'fid' => '12981',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike2_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike2_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '328121',
        'status' => '1',
        'timestamp' => '1304119727',
        'origname' => 'strike2_APR11.jpg',
      ),
      '2' => array(
        'fid' => '12961',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike3_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike3_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132039',
        'status' => '1',
        'timestamp' => '1304014068',
        'origname' => 'strike3_APR11.jpg',
      ),
      '3' => array(
        'fid' => '12962',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike4_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike4_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '178268',
        'status' => '1',
        'timestamp' => '1304014080',
        'origname' => 'strike4_APR11.jpg',
      ),
      '4' => array(
        'fid' => '12963',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike5_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike5_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84140',
        'status' => '1',
        'timestamp' => '1304014092',
        'origname' => 'strike5_APR11.jpg',
      ),
      '5' => array(
        'fid' => '12964',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike6_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike6_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95517',
        'status' => '1',
        'timestamp' => '1304014103',
        'origname' => 'strike6_APR11.jpg',
      ),
      '6' => array(
        'fid' => '12965',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike7_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike7_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '178352',
        'status' => '1',
        'timestamp' => '1304014114',
        'origname' => 'strike7_APR11.jpg',
      ),
      '7' => array(
        'fid' => '12966',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike8_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike8_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '227185',
        'status' => '1',
        'timestamp' => '1304014124',
        'origname' => 'strike8_APR11.jpg',
      ),
      '8' => array(
        'fid' => '12967',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike9_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike9_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124238',
        'status' => '1',
        'timestamp' => '1304014137',
        'origname' => 'strike9_APR11.jpg',
      ),
      '9' => array(
        'fid' => '12968',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike10_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike10_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '253554',
        'status' => '1',
        'timestamp' => '1304014155',
        'origname' => 'strike10_APR11.jpg',
      ),
      '10' => array(
        'fid' => '12969',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike11_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike11_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118386',
        'status' => '1',
        'timestamp' => '1304014167',
        'origname' => 'strike11_APR11.jpg',
      ),
      '11' => array(
        'fid' => '12970',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike12_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike12_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114759',
        'status' => '1',
        'timestamp' => '1304014217',
        'origname' => 'strike12_APR11.jpg',
      ),
      '12' => array(
        'fid' => '12971',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike13_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike13_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155512',
        'status' => '1',
        'timestamp' => '1304014227',
        'origname' => 'strike13_APR11.jpg',
      ),
      '13' => array(
        'fid' => '12973',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike14_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike14_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141834',
        'status' => '1',
        'timestamp' => '1304014261',
        'origname' => 'strike14_APR11.jpg',
      ),
      '14' => array(
        'fid' => '12974',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike15_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike15_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137855',
        'status' => '1',
        'timestamp' => '1304014274',
        'origname' => 'strike15_APR11.jpg',
      ),
      '15' => array(
        'fid' => '12975',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike16_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike16_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '149344',
        'status' => '1',
        'timestamp' => '1304014286',
        'origname' => 'strike16_APR11.jpg',
      ),
      '16' => array(
        'fid' => '12976',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike17_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike17_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132072',
        'status' => '1',
        'timestamp' => '1304014299',
        'origname' => 'strike17_APR11.jpg',
      ),
      '17' => array(
        'fid' => '12977',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike18_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike18_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129340',
        'status' => '1',
        'timestamp' => '1304014311',
        'origname' => 'strike18_APR11.jpg',
      ),
      '18' => array(
        'fid' => '12978',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike19_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike19_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91535',
        'status' => '1',
        'timestamp' => '1304014324',
        'origname' => 'strike19_APR11.jpg',
      ),
      '19' => array(
        'fid' => '12979',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'strike20_APR11.jpg',
        'filepath' => 'files/fmag_story/2011/Apr/strike20_APR11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77728',
        'status' => '1',
        'timestamp' => '1304014334',
        'origname' => 'strike20_APR11.jpg',
      ),
    ),
    'path' => 'stories/strike-it',
    'tags' => array(
      '1' => array(
        '285' => array(
          'tid' => '285',
          'vid' => '1',
          'name' => 'JEREMY SCOTT',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '150' => array(
          'tid' => '150',
          'vid' => '1',
          'name' => 'UNCONDITIONAL',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2630' => array(
          'tid' => '2630',
          'vid' => '5',
          'name' => 'THOMAS KNIGHTS',
          'description' => 'http://www.thomasknights.co.uk/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'JEREMY SCOTT, UNCONDITIONAL',
        '5' => 'THOMAS KNIGHTS',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
