array(
  array(
    'nid' => '3681',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1304354632',
    'changed' => '1403917831',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3681',
    'revision_uid' => '1',
    'title' => 'Colin Egglesfield',
    'body' => '<p>
	Egglesfield of dreams.<br />
	Exclusive photography by Scott Teitler.</p>
',
    'teaser' => '<p>
	Egglesfield of dreams.<br />
	Exclusive photography by Scott Teitler.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917831',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.colinegglesfield.com/">COLIN EGGLESFIELD</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.scottteitler.com/"> SCOTT TEITLER</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<a href="http://shoutoutclothing.com/main.html">SHOUT OUT CLOTHING<br />
	</a><a href="http://www.alocanastudio.com/"><br />
	</a></p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12982',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout 1_Page 2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '311847',
        'status' => '1',
        'timestamp' => '1304354838',
        'origname' => 'Layout 1_Page 2.jpg',
      ),
      '1' => array(
        'fid' => '12983',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '99217',
        'status' => '1',
        'timestamp' => '1304354920',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12985',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106610',
        'status' => '1',
        'timestamp' => '1304355036',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12986',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80052',
        'status' => '1',
        'timestamp' => '1304355042',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '12988',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76504',
        'status' => '1',
        'timestamp' => '1304355052',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '12989',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65411',
        'status' => '1',
        'timestamp' => '1304355059',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '12991',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76061',
        'status' => '1',
        'timestamp' => '1304355070',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '12993',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77130',
        'status' => '1',
        'timestamp' => '1304355442',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
    ),
    'path' => 'stories/colin-egglesfield',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2630' => array(
          'tid' => '2630',
          'vid' => '5',
          'name' => 'THOMAS KNIGHTS',
          'description' => 'http://www.thomasknights.co.uk/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '4' => 'men',
        '5' => 'THOMAS KNIGHTS',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
