array(
  array(
    'nid' => '3683',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1304631447',
    'changed' => '1406008586',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3683',
    'revision_uid' => '1',
    'title' => 'Water Babies',
    'body' => '<p>
	The best of the latest swimwear.<br />
	Exclusive photography by <a href="http://www.michaelfranco.net/">Michael Franco</a>.<br />
	Model ~&nbsp; Mykie Oyler @ Ford/RBA.</p>
',
    'teaser' => '<p>
	The best of the latest swimwear.<br />
	Exclusive photography by <a href="http://www.michaelfranco.net/">Michael Franco</a>.<br />
	Model ~&nbsp; Mykie Oyler @ Ford/RBA.</p>
',
    'log' => '',
    'revision_timestamp' => '1406008586',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.michaelfranco.net/">MICHAEL FRANCO</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	MYKIE OYLER<br />
	@ FORD/RBA</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		CHARLIE BY MATTHEW ZINK</li>
	<li>
		WE ARE HANDSOME</li>
	<li>
		WHITE SANDS AUSTRALIA</li>
	<li>
		JUNGLE GURL</li>
	<li>
		NECKLUSH</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '12996',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '148025',
        'status' => '1',
        'timestamp' => '1304631745',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13021',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-3_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '148134',
        'status' => '1',
        'timestamp' => '1304632814',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '12998',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-4_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '148919',
        'status' => '1',
        'timestamp' => '1304631760',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '12999',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-5_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '151018',
        'status' => '1',
        'timestamp' => '1304631768',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13000',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-6_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '143272',
        'status' => '1',
        'timestamp' => '1304631778',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13001',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-7_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167917',
        'status' => '1',
        'timestamp' => '1304631787',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13002',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-8_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86166',
        'status' => '1',
        'timestamp' => '1304631861',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13004',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-9_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13727',
        'status' => '1',
        'timestamp' => '1304631875',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '13005',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '40355',
        'status' => '1',
        'timestamp' => '1304631882',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '13006',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '228675',
        'status' => '1',
        'timestamp' => '1304631890',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '13007',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '147794',
        'status' => '1',
        'timestamp' => '1304631899',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '13008',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '163520',
        'status' => '1',
        'timestamp' => '1304631909',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '13009',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '99426',
        'status' => '1',
        'timestamp' => '1304631919',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '13010',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13421',
        'status' => '1',
        'timestamp' => '1304631927',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '13013',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129428',
        'status' => '1',
        'timestamp' => '1304631965',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
      '15' => array(
        'fid' => '13014',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-19.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-19.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '223496',
        'status' => '1',
        'timestamp' => '1304631979',
        'origname' => 'Layout-1_Page-19.jpg',
      ),
      '16' => array(
        'fid' => '13015',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-16_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '1304631990',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '17' => array(
        'fid' => '13016',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-17_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106718',
        'status' => '1',
        'timestamp' => '1304631999',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '18' => array(
        'fid' => '13017',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-20.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-20.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '192734',
        'status' => '1',
        'timestamp' => '1304632015',
        'origname' => 'Layout-1_Page-20.jpg',
      ),
      '19' => array(
        'fid' => '13018',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-21.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-21.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '228657',
        'status' => '1',
        'timestamp' => '1304632024',
        'origname' => 'Layout-1_Page-21.jpg',
      ),
      '20' => array(
        'fid' => '13019',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-22.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-22.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15553',
        'status' => '1',
        'timestamp' => '1304632035',
        'origname' => 'Layout-1_Page-22.jpg',
      ),
      '21' => array(
        'fid' => '13020',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-23.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-23.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161822',
        'status' => '1',
        'timestamp' => '1304632045',
        'origname' => 'Layout-1_Page-23.jpg',
      ),
    ),
    'path' => 'stories/water-babies',
    'tags' => array(
      '4' => array(
        '2134' => array(
          'tid' => '2134',
          'vid' => '4',
          'name' => 'bikini',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2129' => array(
          'tid' => '2129',
          'vid' => '4',
          'name' => 'swimwear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '286' => array(
          'tid' => '286',
          'vid' => '1',
          'name' => 'CHARLIE BY MATTHEW ZINK',
          'description' => 'www.charliebymz.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '289' => array(
          'tid' => '289',
          'vid' => '1',
          'name' => 'JUNGLE GURL',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '181' => array(
          'tid' => '181',
          'vid' => '1',
          'name' => 'necklush',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '287' => array(
          'tid' => '287',
          'vid' => '1',
          'name' => 'WE ARE HANDSOME',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '288' => array(
          'tid' => '288',
          'vid' => '1',
          'name' => 'WHITE SANDS AUSTRALIA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2465' => array(
          'tid' => '2465',
          'vid' => '5',
          'name' => 'MICHAEL FRANCO',
          'description' => 'http://www.michaelfranco.net/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'bikini, swimwear, women',
        '1' => 'CHARLIE BY MATTHEW ZINK, JUNGLE GURL, necklush, WE ARE HANDSOME, WHITE SANDS AUSTRALIA',
        '5' => 'MICHAEL FRANCO',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
