array(
  array(
    'nid' => '3685',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1304812869',
    'changed' => '1403917830',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3685',
    'revision_uid' => '1',
    'title' => 'Cold Steel',
    'body' => '<p>
	Violently fashionable.<br />
	Exclusive photography by <a href="http://www.alexanderhankoff.com/">ALEXANDER HANKOFF</a>.<br />
	Models ~ Jake Brodsky, Alec Foster, Jakob Graff, Glen Herder, Arthur Keller,<br />
	Monty Mariano, Devon Pittman, Martin Rogal @ Red.</p>
<p>
	<br />
	&nbsp;</p>
',
    'teaser' => '<p>
	Violently fashionable.<br />
	Exclusive photography by <a href="http://www.alexanderhankoff.com/">ALEXANDER HANKOFF</a>.<br />
	Models ~ Jake Brodsky, Alec Foster, Jakob Graff, Glen Herder, Arthur Keller,<br />
	Monty Mariano, Devon Pittman, Martin Rogal @ Red.</p>
<p>
	<br />
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1403917830',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.alexanderhankoff.com/">ALEXANDER HANKOFF</a></p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	OLIVIA DeAMBROGIO</p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	JAKE BRODSKY<br />
	ALEC FOSTER<br />
	JAKOB GRAFF<br />
	GLEN HERDER<br />
	ARTHUR KELLER<br />
	MONTY MARIANO<br />
	DEVON PITTMAN<br />
	MARTIN ROGAL<br />
	@ RED</p>
<p>
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		RAG AND BONE</li>
	<li>
		BOTTEGA VENETA</li>
	<li>
		VERSACE</li>
	<li>
		ETRO</li>
	<li>
		LOUIS VUITTON</li>
	<li>
		PERRY GARGANO</li>
	<li>
		VIKTOR &amp; ROLF</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13039',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-2_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87313',
        'status' => '1',
        'timestamp' => '1304707635',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13024',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-3_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '99564',
        'status' => '1',
        'timestamp' => '1304640045',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13025',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-4_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112620',
        'status' => '1',
        'timestamp' => '1304640393',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13027',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-5_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60575',
        'status' => '1',
        'timestamp' => '1304640403',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13028',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-6_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86609',
        'status' => '1',
        'timestamp' => '1304640410',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13029',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-7_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63658',
        'status' => '1',
        'timestamp' => '1304640419',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13030',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-8_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78523',
        'status' => '1',
        'timestamp' => '1304640430',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13031',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-9_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81354',
        'status' => '1',
        'timestamp' => '1304640442',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '13032',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-10_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60739',
        'status' => '1',
        'timestamp' => '1304640452',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '13033',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-11_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74746',
        'status' => '1',
        'timestamp' => '1304640473',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '13034',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-12_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '45367',
        'status' => '1',
        'timestamp' => '1304640482',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '13035',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-13_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85343',
        'status' => '1',
        'timestamp' => '1304640494',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '13036',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-14_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73436',
        'status' => '1',
        'timestamp' => '1304640506',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '13037',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-15_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88018',
        'status' => '1',
        'timestamp' => '1304640517',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
    ),
    'path' => 'stories/cold-steel',
    'tags' => array(
      '5' => array(
        '2557' => array(
          'tid' => '2557',
          'vid' => '5',
          'name' => 'Alexander Hankoff',
          'description' => 'http://%20www.alexanderhankoff.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '291' => array(
          'tid' => '291',
          'vid' => '1',
          'name' => 'BOTTEGA VENETA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '249' => array(
          'tid' => '249',
          'vid' => '1',
          'name' => 'ETRO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '158' => array(
          'tid' => '158',
          'vid' => '1',
          'name' => 'LOUIS VUITTON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '293' => array(
          'tid' => '293',
          'vid' => '1',
          'name' => 'PERRY GARGANO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '290' => array(
          'tid' => '290',
          'vid' => '1',
          'name' => 'RAG AND BONE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '292' => array(
          'tid' => '292',
          'vid' => '1',
          'name' => 'VERSACE',
          'description' => 'shop.versace.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '294' => array(
          'tid' => '294',
          'vid' => '1',
          'name' => 'VIKTOR & ROLF',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Alexander Hankoff',
        '1' => 'BOTTEGA VENETA, ETRO, LOUIS VUITTON, PERRY GARGANO, RAG AND BONE, VERSACE, VIKTOR & ROLF',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
