array(
  array(
    'nid' => '3688',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1304968556',
    'changed' => '1403918095',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3688',
    'revision_uid' => '1',
    'title' => 'Seamstress',
    'body' => '<p>
	She&#39;s got prints sewn up.<br />
	Exclusive photography by <a href="http://www.toddanthonytyler.com/">TODD ANTHONY TYLER</a>.<br />
	Model ~ Alina.</p>
',
    'teaser' => '<p>
	She&#39;s got prints sewn up.<br />
	Exclusive photography by <a href="http://www.toddanthonytyler.com/">TODD ANTHONY TYLER</a>.<br />
	Model ~ Alina.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918095',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.toddanthonytyler.com/" target="_blank">TODD ANTHONY TYLER</a></p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	KARINA SMITH</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	ALINA<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		PUCCI</li>
	<li>
		SERGIO ROSSI</li>
	<li>
		CALVIN KLEIN</li>
	<li>
		LOEWE</li>
	<li>
		SPORTMAX</li>
	<li>
		ESCADA</li>
	<li>
		SWAROVSKI</li>
	<li>
		CHRISTIAN DIOR</li>
</ul>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13048',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-2_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '125674',
        'status' => '1',
        'timestamp' => '1304968537',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13049',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-3_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74319',
        'status' => '1',
        'timestamp' => '1304968549',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13078',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-4_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127823',
        'status' => '1',
        'timestamp' => '1305202193',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13051',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '175566',
        'status' => '1',
        'timestamp' => '1304968592',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13052',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-6_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14683',
        'status' => '1',
        'timestamp' => '1304968603',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13053',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-7_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113008',
        'status' => '1',
        'timestamp' => '1304968618',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13054',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-8_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '121774',
        'status' => '1',
        'timestamp' => '1304968643',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13055',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-9_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14672',
        'status' => '1',
        'timestamp' => '1304968653',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '13056',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-10_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '111939',
        'status' => '1',
        'timestamp' => '1304968674',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '13057',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-11_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114680',
        'status' => '1',
        'timestamp' => '1304968726',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '13058',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-12_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16100',
        'status' => '1',
        'timestamp' => '1304968736',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '13059',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-13_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93893',
        'status' => '1',
        'timestamp' => '1304968748',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '13060',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-14_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106516',
        'status' => '1',
        'timestamp' => '1304968758',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '13061',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-15_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15338',
        'status' => '1',
        'timestamp' => '1304968767',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
    ),
    'path' => 'stories/seamstress',
    'tags' => array(
      '1' => array(
        '52' => array(
          'tid' => '52',
          'vid' => '1',
          'name' => 'calvin Klein',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '299' => array(
          'tid' => '299',
          'vid' => '1',
          'name' => 'christian dior',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '231' => array(
          'tid' => '231',
          'vid' => '1',
          'name' => 'ESCADA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '297' => array(
          'tid' => '297',
          'vid' => '1',
          'name' => 'loewe',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '295' => array(
          'tid' => '295',
          'vid' => '1',
          'name' => 'pucci',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '296' => array(
          'tid' => '296',
          'vid' => '1',
          'name' => 'sergio rossi',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '105' => array(
          'tid' => '105',
          'vid' => '1',
          'name' => 'SPORTMAX',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '298' => array(
          'tid' => '298',
          'vid' => '1',
          'name' => 'swarovski',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2493' => array(
          'tid' => '2493',
          'vid' => '5',
          'name' => 'Todd ANTHONY TYLER',
          'description' => 'http://www.toddanthonytyler.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'calvin Klein, christian dior, ESCADA, loewe, pucci, sergio rossi, SPORTMAX, swarovski',
        '5' => 'Todd ANTHONY TYLER',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
