array(
  array(
    'nid' => '3690',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1305152670',
    'changed' => '1337804398',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3690',
    'revision_uid' => '1',
    'title' => 'At Home Day',
    'body' => '<p>
	Lounge around.<br />
	Exclusive photography by <a href="http://www.icheric.com/">CHERIC KWONG</a>.<br />
	Model ~ Alexis.</p>
',
    'teaser' => '<p>
	Lounge around.<br />
	Exclusive photography by <a href="http://www.icheric.com/">CHERIC KWONG</a>.<br />
	Model ~ Alexis.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804398',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.icheric.com/">CHERIC KWONG</a></p>
<p>
	&nbsp;</p>
<p>
	CONCEPT<br />
	<a href="http://ramarights.blogspot.com/">RAMA</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	ALEXIS<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		CALVIN KLEIN</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13063',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-2_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '142486',
        'status' => '1',
        'timestamp' => '1304979696',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13064',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-3_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85263',
        'status' => '1',
        'timestamp' => '1304979706',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13065',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-4_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116278',
        'status' => '1',
        'timestamp' => '1304979716',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13066',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-5_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93908',
        'status' => '1',
        'timestamp' => '1304979728',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13067',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-6_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131127',
        'status' => '1',
        'timestamp' => '1304979742',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13068',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-7_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14703',
        'status' => '1',
        'timestamp' => '1304979752',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13069',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-8_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78008',
        'status' => '1',
        'timestamp' => '1304979765',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13070',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-9_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87824',
        'status' => '1',
        'timestamp' => '1304979775',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '13071',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-10_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89321',
        'status' => '1',
        'timestamp' => '1304979788',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '13072',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-11_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '55650',
        'status' => '1',
        'timestamp' => '1304979799',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '13073',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-12_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107356',
        'status' => '1',
        'timestamp' => '1304979812',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '13074',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-13_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95912',
        'status' => '1',
        'timestamp' => '1304979822',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '13075',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-14_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117033',
        'status' => '1',
        'timestamp' => '1304979835',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '13076',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-15_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98115',
        'status' => '1',
        'timestamp' => '1304979846',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
    ),
    'path' => 'stories/home-day',
    'tags' => array(
      '1' => array(
        '52' => array(
          'tid' => '52',
          'vid' => '1',
          'name' => 'calvin Klein',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2631' => array(
          'tid' => '2631',
          'vid' => '5',
          'name' => 'CHERIC KWONG',
          'description' => 'http://www.icheric.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'calvin Klein',
        '5' => 'CHERIC KWONG',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
