array(
  array(
    'nid' => '3693',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1321203988',
    'changed' => '1406008355',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3693',
    'revision_uid' => '1',
    'title' => 'And The Call it Charlie',
    'body' => '<p>
	<a href="http://www.charliebymz.com">Charlie</a> swimwear designer Matthew Zink.<br />
	Interview by Heather MacDonald.<br />
	Photography by <a href="http://www.kevinmcdermott.com/">Kevin McDermott</a></p>
',
    'teaser' => '<p>
	<a href="http://www.charliebymz.com">Charlie</a> swimwear designer Matthew Zink.<br />
	Interview by Heather MacDonald.<br />
	Photography by <a href="http://www.kevinmcdermott.com/">Kevin McDermott</a></p>
',
    'log' => '',
    'revision_timestamp' => '1406008355',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.charliebymz.com">CHARLIE BY MATTHEW ZINK</a></p>
<p>
	&nbsp;</p>
<p>
	INTERVIEW<br />
	HEATHER MACDONALD</p>
<p>
	&nbsp;</p>
<p>
	ZINK PORTRAITS<br />
	BY <a href="http://www.kevinmcdermott.com/">KEVIN MCDERMOTT</a></p>
<p>
	&nbsp;</p>
<p>
	SWIMWEAR PHOTOGRAPHY BY SETH HUTCHINSON</p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	ADRIANA CERNANOVA<br />
	@ FORD<br />
	ALEX GEERMAN<br />
	@ MAJOR</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13103',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-2_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '246746',
        'status' => '1',
        'timestamp' => '1305307689',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13104',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-3_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '453790',
        'status' => '1',
        'timestamp' => '1305307696',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13083',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-4_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60191',
        'status' => '1',
        'timestamp' => '1305306265',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13105',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-5_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109436',
        'status' => '1',
        'timestamp' => '1305307705',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13086',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-6_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '70600',
        'status' => '1',
        'timestamp' => '1305306279',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13106',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-7_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '120140',
        'status' => '1',
        'timestamp' => '1305307716',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13089',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-8_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84441',
        'status' => '1',
        'timestamp' => '1305306298',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13107',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-9_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97519',
        'status' => '1',
        'timestamp' => '1305307728',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '13108',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-10_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '226305',
        'status' => '1',
        'timestamp' => '1305307739',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '13093',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-11_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '57790',
        'status' => '1',
        'timestamp' => '1305306324',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '13095',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-12_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102076',
        'status' => '1',
        'timestamp' => '1305306335',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '13109',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-13_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '251007',
        'status' => '1',
        'timestamp' => '1305307751',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '13110',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-14_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108958',
        'status' => '1',
        'timestamp' => '1305307765',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '13099',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-15_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76800',
        'status' => '1',
        'timestamp' => '1305306365',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '13101',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '54997',
        'status' => '1',
        'timestamp' => '1305306374',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '13111',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108208',
        'status' => '1',
        'timestamp' => '1305307772',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
    ),
    'path' => 'stories/and-call-it-charlie',
    'tags' => array(
      '4' => array(
        '2138' => array(
          'tid' => '2138',
          'vid' => '4',
          'name' => 'interview',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2129' => array(
          'tid' => '2129',
          'vid' => '4',
          'name' => 'swimwear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2493' => array(
          'tid' => '2493',
          'vid' => '5',
          'name' => 'Todd ANTHONY TYLER',
          'description' => 'http://www.toddanthonytyler.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '4' => 'interview, men, swimwear, women',
        '5' => 'Todd ANTHONY TYLER',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
