array(
  array(
    'nid' => '3697',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1305584107',
    'changed' => '1403918095',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3697',
    'revision_uid' => '1',
    'title' => 'Wood Work',
    'body' => '<p>
	Wood-sy details.<br />
	Exclusive photography by <a href="http://www.michaelfranco.net/">Michael Franco</a>.<br />
	Model ~&nbsp; Jenny Watwood @ Ford/RBA.</p>
',
    'teaser' => '<p>
	Wood-sy details.<br />
	Exclusive photography by <a href="http://www.michaelfranco.net/">Michael Franco</a>.<br />
	Model ~&nbsp; Jenny Watwood @ Ford/RBA.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918095',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.michaelfranco.net/">MICHAEL FRANCO</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	JENNY WATWOOD<br />
	@ FORD/RBA</p>
<p>
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.thrivela.com/">THRIVE</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13144',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-2_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123880',
        'status' => '1',
        'timestamp' => '1305760621',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13130',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-3_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98066',
        'status' => '1',
        'timestamp' => '1305583986',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13131',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-4_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104695',
        'status' => '1',
        'timestamp' => '1305583992',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13133',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-5_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127884',
        'status' => '1',
        'timestamp' => '1305584016',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13134',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-6_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14913',
        'status' => '1',
        'timestamp' => '1305584025',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13135',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-7_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132219',
        'status' => '1',
        'timestamp' => '1305584036',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13136',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-8_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73990',
        'status' => '1',
        'timestamp' => '1305584045',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13137',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-9_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91057',
        'status' => '1',
        'timestamp' => '1305584055',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '13138',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-10_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '135942',
        'status' => '1',
        'timestamp' => '1305584067',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '13139',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-11_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '51361',
        'status' => '1',
        'timestamp' => '1305584080',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '13140',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-12_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134064',
        'status' => '1',
        'timestamp' => '1305584090',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '13141',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-13_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141555',
        'status' => '1',
        'timestamp' => '1305584100',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/wood-work',
    'tags' => array(
      '5' => array(
        '2465' => array(
          'tid' => '2465',
          'vid' => '5',
          'name' => 'MICHAEL FRANCO',
          'description' => 'http://www.michaelfranco.net/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '301' => array(
          'tid' => '301',
          'vid' => '1',
          'name' => 'thrive',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'MICHAEL FRANCO',
        '1' => 'thrive',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
