array(
  array(
    'nid' => '3701',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1306172254',
    'changed' => '1406008547',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3701',
    'revision_uid' => '1',
    'title' => 'Renata',
    'body' => '<p>
	We love Renata; you gotta.<br />
	Exclusive photography by Joel Esposito.</p>
',
    'teaser' => '<p>
	We love Renata; you gotta.<br />
	Exclusive photography by Joel Esposito.</p>
',
    'log' => '',
    'revision_timestamp' => '1406008547',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	RENATA<br />
	@ ELITE</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.joelesposito.com/">JOEL ESPOSITO</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING BY<br />
	<a href="http://www.judyinc.com/michellepaiano/bio.html"> MICHELE PAIANO</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13173',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-2_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '34179',
        'status' => '1',
        'timestamp' => '1306172469',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13174',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-3_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83569',
        'status' => '1',
        'timestamp' => '1306172478',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13175',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-4_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114562',
        'status' => '1',
        'timestamp' => '1306172492',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13176',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-5_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78586',
        'status' => '1',
        'timestamp' => '1306172504',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13177',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-6_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73322',
        'status' => '1',
        'timestamp' => '1306172515',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13178',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-7_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '62367',
        'status' => '1',
        'timestamp' => '1306172529',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
    ),
    'path' => 'stories/renata',
    'tags' => array(
      '5' => array(
        '2620' => array(
          'tid' => '2620',
          'vid' => '5',
          'name' => 'ALAN CHAN',
          'description' => 'http://www.alanchanstudio.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2137' => array(
          'tid' => '2137',
          'vid' => '4',
          'name' => 'lingerie',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2139' => array(
          'tid' => '2139',
          'vid' => '4',
          'name' => 'profile',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ALAN CHAN',
        '4' => 'lingerie, profile, women',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
