array(
  array(
    'nid' => '3703',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1306341029',
    'changed' => '1403918095',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3703',
    'revision_uid' => '1',
    'title' => 'The Escapist',
    'body' => '<p>
	Unlock some style.<br />
	Exclusive photography by <a href="http://www.alexanderhankoff.com/">ALEXANDER HANKOFF</a>.<br />
	Model ~ Shaun Haugh @ Red.</p>
',
    'teaser' => '<p>
	Unlock some style.<br />
	Exclusive photography by <a href="http://www.alexanderhankoff.com/">ALEXANDER HANKOFF</a>.<br />
	Model ~ Shaun Haugh @ Red.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918095',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.alexanderhankoff.com/">ALEXANDER HANKOFF</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	OLIVIA DeAMBROGIO</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	SHAUN HAUGH<br />
	@ RED</p>
<p>
	&nbsp;</p>
<p>
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		RAG AND BONE</li>
	<li>
		BOTTEGA VENETA</li>
	<li>
		VERSACE</li>
	<li>
		ETRO</li>
	<li>
		LOUIS VUITTON</li>
	<li>
		PERRY GARGANO</li>
	<li>
		OAK</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13192',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-2_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123407',
        'status' => '1',
        'timestamp' => '1306347442',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13190',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-2_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '163567',
        'status' => '1',
        'timestamp' => '1306346615',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '2' => array(
        'fid' => '13183',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-4_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18841',
        'status' => '1',
        'timestamp' => '1306340971',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13184',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-5_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127144',
        'status' => '1',
        'timestamp' => '1306340982',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13185',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-6_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77052',
        'status' => '1',
        'timestamp' => '1306340992',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13187',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-7_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14392',
        'status' => '1',
        'timestamp' => '1306341005',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13188',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-8_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109569',
        'status' => '1',
        'timestamp' => '1306341014',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13189',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-9_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101864',
        'status' => '1',
        'timestamp' => '1306341024',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
    ),
    'path' => 'stories/escapist',
    'tags' => array(
      '5' => array(
        '2557' => array(
          'tid' => '2557',
          'vid' => '5',
          'name' => 'Alexander Hankoff',
          'description' => 'http://%20www.alexanderhankoff.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '291' => array(
          'tid' => '291',
          'vid' => '1',
          'name' => 'BOTTEGA VENETA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '249' => array(
          'tid' => '249',
          'vid' => '1',
          'name' => 'ETRO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '158' => array(
          'tid' => '158',
          'vid' => '1',
          'name' => 'LOUIS VUITTON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '309' => array(
          'tid' => '309',
          'vid' => '1',
          'name' => 'oak',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '293' => array(
          'tid' => '293',
          'vid' => '1',
          'name' => 'PERRY GARGANO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '290' => array(
          'tid' => '290',
          'vid' => '1',
          'name' => 'RAG AND BONE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '292' => array(
          'tid' => '292',
          'vid' => '1',
          'name' => 'VERSACE',
          'description' => 'shop.versace.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Alexander Hankoff',
        '1' => 'BOTTEGA VENETA, ETRO, LOUIS VUITTON, oak, PERRY GARGANO, RAG AND BONE, VERSACE',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
