array(
  array(
    'nid' => '3705',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1306706171',
    'changed' => '1403918095',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3705',
    'revision_uid' => '1',
    'title' => 'Dynamo',
    'body' => '<p>
	You&#39;re dynamic.<br />
	Exclusive photography by <a href="http://weeseing.com/">WEE SEING NG</a>.<br />
	Model ~ Amanda @ Factor Women.</p>
',
    'teaser' => '<p>
	You&#39;re dynamic.<br />
	Exclusive photography by <a href="http://weeseing.com/">WEE SEING NG</a>.<br />
	Model ~ Amanda @ Factor Women.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918095',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://weeseing.com">WEE SEING NG</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	REBEKAH KAPLAN</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	HAIR &amp; MAKE UP<br />
	SYLVIA FOX</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	AMANDA<br />
	@ FACTOR WOMEN</p>
<p>
	&nbsp;</p>
<p>
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		URBAN OUTFITTERS</li>
	<li>
		LAROK</li>
	<li>
		ANTHROPOLOGIE</li>
	<li>
		NARCISO RODRIGUEZ</li>
	<li>
		JAY GODFREY</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13222',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-2_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155087',
        'status' => '1',
        'timestamp' => '1307016278',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13195',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-3_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '105864',
        'status' => '1',
        'timestamp' => '1306360774',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13196',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-4_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19794',
        'status' => '1',
        'timestamp' => '1306360784',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13198',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-5_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '55565',
        'status' => '1',
        'timestamp' => '1306360792',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13200',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-6_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109391',
        'status' => '1',
        'timestamp' => '1306360801',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13201',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-7_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132128',
        'status' => '1',
        'timestamp' => '1306360809',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13202',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-8_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58475',
        'status' => '1',
        'timestamp' => '1306360819',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13203',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/May/Layout-1_Page-9_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89747',
        'status' => '1',
        'timestamp' => '1306360827',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
    ),
    'path' => 'stories/dynamo',
    'tags' => array(
      '1' => array(
        '188' => array(
          'tid' => '188',
          'vid' => '1',
          'name' => 'ANTHROPOLOGIE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '312' => array(
          'tid' => '312',
          'vid' => '1',
          'name' => 'JAY GODFREY',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '310' => array(
          'tid' => '310',
          'vid' => '1',
          'name' => 'LAROK',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '311' => array(
          'tid' => '311',
          'vid' => '1',
          'name' => 'NARCISO RODRIGUEZ',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '167' => array(
          'tid' => '167',
          'vid' => '1',
          'name' => 'Urban Outfitters',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2632' => array(
          'tid' => '2632',
          'vid' => '5',
          'name' => 'WEE SEING NG',
          'description' => 'http://weeseing.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'ANTHROPOLOGIE, JAY GODFREY, LAROK, NARCISO RODRIGUEZ, Urban Outfitters',
        '5' => 'WEE SEING NG',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
