array(
  array(
    'nid' => '3707',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1306962541',
    'changed' => '1403917830',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3707',
    'revision_uid' => '1',
    'title' => 'Corey Alfaro',
    'body' => '<p>
	Corey is the story.<br />
	Exclusive photography by Michael Franco.</p>
',
    'teaser' => '<p>
	Corey is the story.<br />
	Exclusive photography by Michael Franco.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917830',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	MICHAEL FRANCO</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		VIZEAU</li>
	<li>
		TED BAKER</li>
	<li>
		ROBERT WAYNE</li>
	<li>
		TIFFANY &amp; CO</li>
	<li>
		THRIVE</li>
	<li>
		WE ARE HANDSOME</li>
	<li>
		THRIVE</li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13205',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '59966',
        'status' => '1',
        'timestamp' => '1306962416',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13207',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '133773',
        'status' => '1',
        'timestamp' => '1306962426',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13209',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102467',
        'status' => '1',
        'timestamp' => '1306962434',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13211',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98575',
        'status' => '1',
        'timestamp' => '1306962444',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13212',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138420',
        'status' => '1',
        'timestamp' => '1306962451',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13214',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155024',
        'status' => '1',
        'timestamp' => '1306962468',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13220',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '207808',
        'status' => '1',
        'timestamp' => '1306962593',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13215',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119326',
        'status' => '1',
        'timestamp' => '1306962477',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '13216',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114728',
        'status' => '1',
        'timestamp' => '1306962488',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '13217',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '150685',
        'status' => '1',
        'timestamp' => '1306962500',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '13218',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137536',
        'status' => '1',
        'timestamp' => '1306962513',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '13219',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79541',
        'status' => '1',
        'timestamp' => '1306962523',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/corey-alfaro',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2465' => array(
          'tid' => '2465',
          'vid' => '5',
          'name' => 'MICHAEL FRANCO',
          'description' => 'http://www.michaelfranco.net/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '4' => 'men',
        '5' => 'MICHAEL FRANCO',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
