array(
  array(
    'nid' => '3711',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1307281955',
    'changed' => '1403917829',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3711',
    'revision_uid' => '1',
    'title' => 'Telmuun',
    'body' => '<p>
	Talking bout Telmuun.<br />
	Exclusive photography by Joel Esposito.</p>
',
    'teaser' => '<p>
	Talking bout Telmuun.<br />
	Exclusive photography by Joel Esposito.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917829',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	&nbsp;</p>
<p>
	TELMUUN<br />
	@ FORD</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.joelesposito.com/">JOEL ESPOSITO</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING BY<br />
	RYAN CATNEY<br />
	@ JUDY INC</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13240',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-2_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '35272',
        'status' => '1',
        'timestamp' => '1307285818',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13241',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-3_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140266',
        'status' => '1',
        'timestamp' => '1307285830',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13242',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-4_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '144134',
        'status' => '1',
        'timestamp' => '1307285842',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13243',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-5_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106292',
        'status' => '1',
        'timestamp' => '1307285854',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13244',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-6_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17513',
        'status' => '1',
        'timestamp' => '1307285867',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13245',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-7_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '151810',
        'status' => '1',
        'timestamp' => '1307285880',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13246',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-8_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92524',
        'status' => '1',
        'timestamp' => '1307285895',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13247',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-9_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94504',
        'status' => '1',
        'timestamp' => '1307285909',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '13248',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-10_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129100',
        'status' => '1',
        'timestamp' => '1307285921',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '13249',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-11_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58969',
        'status' => '1',
        'timestamp' => '1307285939',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
    ),
    'path' => 'stories/telmuun',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2550' => array(
          'tid' => '2550',
          'vid' => '5',
          'name' => 'Mike Lewis',
          'description' => 'http://www.mikelewis.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '4' => 'men',
        '5' => 'Mike Lewis',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
