array(
  array(
    'nid' => '3713',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1307384198',
    'changed' => '1403917829',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3713',
    'revision_uid' => '1',
    'title' => 'It\'s A Guy Thing',
    'body' => '<p>
	Cecilie Harris and India Hobson on <a href="http://www.boysbygirls.co.uk/">Boys By Girls</a>.<br />
	Interview by James N.</p>
',
    'teaser' => '<p>
	Cecilie Harris and India Hobson on <a href="http://www.boysbygirls.co.uk/">Boys By Girls</a>.<br />
	Interview by James N.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917829',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.boysbygirls.co.uk/">BOYS BY GIRLS </a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://www.cecilieharris.co.uk/">CECILIE HARRIS</a></p>
<p>
	<br />
	<br />
	<a href="http://www.indiahobsonphotography.co.uk/">INDIA HOBSON</a></p>
<p>
	&nbsp;</p>
<p>
	INTERVIEW<br />
	JAMES N</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13251',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-2_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '186985',
        'status' => '1',
        'timestamp' => '1307384248',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13253',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-3_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '56211',
        'status' => '1',
        'timestamp' => '1307384258',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13254',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-4_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77801',
        'status' => '1',
        'timestamp' => '1307384266',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13255',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161026',
        'status' => '1',
        'timestamp' => '1307384277',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13257',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-6_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118167',
        'status' => '1',
        'timestamp' => '1307384291',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13258',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-7_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '236234',
        'status' => '1',
        'timestamp' => '1307384298',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13259',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-8_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '233136',
        'status' => '1',
        'timestamp' => '1307384313',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13264',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-9_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132944',
        'status' => '1',
        'timestamp' => '1307385214',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '13261',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-10_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104856',
        'status' => '1',
        'timestamp' => '1307384334',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '13263',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-11_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136382',
        'status' => '1',
        'timestamp' => '1307385138',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
    ),
    'path' => 'stories/its-guy-thing',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2550' => array(
          'tid' => '2550',
          'vid' => '5',
          'name' => 'Mike Lewis',
          'description' => 'http://www.mikelewis.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'men',
        '5' => 'Mike Lewis',
      ),
      '2' => array(
        '2' => '2',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
