array(
  array(
    'nid' => '3715',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1307481292',
    'changed' => '1406007736',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3715',
    'revision_uid' => '1',
    'title' => 'Sunshine Lolita',
    'body' => '<p>
	Ahhhh the girls of summer.<br />
	Exclusive photography by <a href="http://www.mikelewis.ca/" target="_blank">MIKE LEWIS</a>.<br />
	Model ~&nbsp; Dana @ Spot 6.</p>
',
    'teaser' => '<p>
	Ahhhh the girls of summer.<br />
	Exclusive photography by <a href="http://www.mikelewis.ca/" target="_blank">MIKE LEWIS</a>.<br />
	Model ~&nbsp; Dana @ Spot 6.</p>
',
    'log' => '',
    'revision_timestamp' => '1406007736',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.mikelewis.ca/" target="_blank">MIKE LEWIS</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	STYLIST<br />
	SHELLYZA JETHA</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	DANA<br />
	@ SPOT 6<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		KATHERINE DEMARCHELIER</li>
	<li>
		H&amp;M</li>
	<li>
		PSALM 91:1</li>
	<li>
		JEWELRY BY KAREN<br />
		&nbsp;</li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13267',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-2_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67740',
        'status' => '1',
        'timestamp' => '1307481123',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13268',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-3_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '110532',
        'status' => '1',
        'timestamp' => '1307481132',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13271',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-6_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93533',
        'status' => '1',
        'timestamp' => '1307481169',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '3' => array(
        'fid' => '13280',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-7_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '25400',
        'status' => '1',
        'timestamp' => '1307481358',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '4' => array(
        'fid' => '13269',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-4_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123507',
        'status' => '1',
        'timestamp' => '1307481146',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '5' => array(
        'fid' => '13270',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-5_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100553',
        'status' => '1',
        'timestamp' => '1307481156',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '6' => array(
        'fid' => '13281',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-8_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '21969',
        'status' => '1',
        'timestamp' => '1307481431',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13272',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-9_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66903',
        'status' => '1',
        'timestamp' => '1307481186',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '13283',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-10_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '21970',
        'status' => '1',
        'timestamp' => '1307481571',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '13284',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-11_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '48055',
        'status' => '1',
        'timestamp' => '1307481591',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '13285',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-12_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17973',
        'status' => '1',
        'timestamp' => '1307481604',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '13286',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-13_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '180345',
        'status' => '1',
        'timestamp' => '1307481619',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '13276',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60228',
        'status' => '1',
        'timestamp' => '1307481238',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '13277',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19884',
        'status' => '1',
        'timestamp' => '1307481252',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '13278',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76523',
        'status' => '1',
        'timestamp' => '1307481270',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '13279',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13464',
        'status' => '1',
        'timestamp' => '1307481283',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
    ),
    'path' => 'stories/sunshine-lolita',
    'tags' => array(
      '1' => array(
        '31' => array(
          'tid' => '31',
          'vid' => '1',
          'name' => 'H&M',
          'description' => 'www.hm.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '315' => array(
          'tid' => '315',
          'vid' => '1',
          'name' => 'JEWELRY BY KAREN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '313' => array(
          'tid' => '313',
          'vid' => '1',
          'name' => 'KATHERINE DEMARCHELIER',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '314' => array(
          'tid' => '314',
          'vid' => '1',
          'name' => 'PSALM 91:1',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2550' => array(
          'tid' => '2550',
          'vid' => '5',
          'name' => 'Mike Lewis',
          'description' => 'http://www.mikelewis.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2129' => array(
          'tid' => '2129',
          'vid' => '4',
          'name' => 'swimwear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'H&M, JEWELRY BY KAREN, KATHERINE DEMARCHELIER, PSALM 91:1',
        '5' => 'Mike Lewis',
        '4' => 'swimwear, women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
