array(
  array(
    'nid' => '3717',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1307552568',
    'changed' => '1403917829',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3717',
    'revision_uid' => '1',
    'title' => 'Short Story',
    'body' => '<p>
	Show some leg.<br />
	Exclusive photography by <a href="http://www.tracyrasinski.com/">TRACY RASINSKI</a>.<br />
	Models ~ Jesse &amp; Tobias @ Elmer Olsen.</p>
',
    'teaser' => '<p>
	Show some leg.<br />
	Exclusive photography by <a href="http://www.tracyrasinski.com/">TRACY RASINSKI</a>.<br />
	Models ~ Jesse &amp; Tobias @ Elmer Olsen.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917829',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.tracyrasinski.com/">TRACY RASINSKI</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	JAMES N</p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	JESSE &amp; TOBIAS<br />
	@ ELMER OLSEN</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		ELVIS JESUS</li>
	<li>
		SUIT</li>
	<li>
		ELEVEN PARIS</li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13288',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-3_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '145821',
        'status' => '1',
        'timestamp' => '1307552386',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '1' => array(
        'fid' => '13289',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-4_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126247',
        'status' => '1',
        'timestamp' => '1307552398',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '2' => array(
        'fid' => '13290',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-5_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '196234',
        'status' => '1',
        'timestamp' => '1307552410',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '3' => array(
        'fid' => '13291',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-6_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114223',
        'status' => '1',
        'timestamp' => '1307552422',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '4' => array(
        'fid' => '13292',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-7_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '1307552433',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '5' => array(
        'fid' => '13293',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-8_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '187275',
        'status' => '1',
        'timestamp' => '1307552443',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '6' => array(
        'fid' => '13294',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-9_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20592',
        'status' => '1',
        'timestamp' => '1307552454',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '7' => array(
        'fid' => '13295',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-10_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130974',
        'status' => '1',
        'timestamp' => '1307552467',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '8' => array(
        'fid' => '13296',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-11_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93162',
        'status' => '1',
        'timestamp' => '1307552477',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '9' => array(
        'fid' => '13297',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-12_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88417',
        'status' => '1',
        'timestamp' => '1307552489',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '10' => array(
        'fid' => '13299',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-13_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106437',
        'status' => '1',
        'timestamp' => '1307552504',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '11' => array(
        'fid' => '13300',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-14_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17992',
        'status' => '1',
        'timestamp' => '1307552513',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '12' => array(
        'fid' => '13301',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-15_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79476',
        'status' => '1',
        'timestamp' => '1307552527',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '13' => array(
        'fid' => '13302',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-16_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95502',
        'status' => '1',
        'timestamp' => '1307552537',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '14' => array(
        'fid' => '13304',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-17_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94011',
        'status' => '1',
        'timestamp' => '1307552548',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '15' => array(
        'fid' => '13305',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81993',
        'status' => '1',
        'timestamp' => '1307552558',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
    ),
    'path' => 'stories/short-story',
    'tags' => array(
      '1' => array(
        '128' => array(
          'tid' => '128',
          'vid' => '1',
          'name' => 'Eleven Paris',
          'description' => 'elevenparis.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '131' => array(
          'tid' => '131',
          'vid' => '1',
          'name' => 'ELVIS JESUS',
          'description' => 'elvisjesus.co.uk',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '127' => array(
          'tid' => '127',
          'vid' => '1',
          'name' => 'Suit',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2554' => array(
          'tid' => '2554',
          'vid' => '5',
          'name' => 'Tracy Rasinski',
          'description' => 'http://www.tracyrasinski.com/#splashpage-f4cd0',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Eleven Paris, ELVIS JESUS, Suit',
        '4' => 'men',
        '5' => 'Tracy Rasinski',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
