array(
  array(
    'nid' => '3746',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1309869876',
    'changed' => '1403918094',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3746',
    'revision_uid' => '1',
    'title' => 'Linette Mikel',
    'body' => '<p>
	Linette&#39;s a sure bet.<br />
	Exclusive photography by Tracy Rasinski.</p>
',
    'teaser' => '<p>
	Linette&#39;s a sure bet.<br />
	Exclusive photography by Tracy Rasinski.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918094',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	LINETTE MIKEL</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	TRACY RASINSKI</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13598',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-2_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '40841',
        'status' => '1',
        'timestamp' => '1309351408',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13599',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-3_15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107955',
        'status' => '1',
        'timestamp' => '1309351417',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13600',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-4_16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '111973',
        'status' => '1',
        'timestamp' => '1309351424',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13601',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-5_15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131759',
        'status' => '1',
        'timestamp' => '1309351434',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13602',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-6_14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122945',
        'status' => '1',
        'timestamp' => '1309351444',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13603',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-7_16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126440',
        'status' => '1',
        'timestamp' => '1309351455',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13604',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-8_16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158304',
        'status' => '1',
        'timestamp' => '1309351464',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13605',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Jun/Layout-1_Page-9_15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58091',
        'status' => '1',
        'timestamp' => '1309351472',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
    ),
    'path' => 'stories/linette-mikel',
    'tags' => array(
      '5' => array(
        '2636' => array(
          'tid' => '2636',
          'vid' => '5',
          'name' => 'CHRISTIAN ALEXANDER',
          'description' => 'http://www.frontmanagement.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'CHRISTIAN ALEXANDER',
        '4' => 'women',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
