array(
  array(
    'nid' => '3752',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1310332287',
    'changed' => '1314975932',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3752',
    'revision_uid' => '1',
    'title' => 'Accent on Edge',
    'body' => '<p>
	Edge in your accessories.<br />
	Exclusive photography by <a href="http://www.boandbro.com/home/">Bo Zhang</a><br />
	Model ~ Eyen Chrom @ Muse.</p>
',
    'teaser' => '<p>
	Edge in your accessories.<br />
	Exclusive photography by <a href="http://www.boandbro.com/home/">Bo Zhang</a><br />
	Model ~ Eyen Chrom @ Muse.</p>
',
    'log' => '',
    'revision_timestamp' => '1314975932',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.boandbro.com/home/">BO ZHANG</a><br />
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	<a href="http://www.colintmcdonald.com/">COLIN T MCDONALD</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MAKE UP<br />
	<a href="http://www.rachelnicksmakeup.com/">RACHEL NGAI</a><br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	<a href="http://www.mauriciohair.com/">MAURICIO CIFUENTES</a><br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	EYEN CHROM<br />
	@ MUSE</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13686',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-2_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '47622',
        'status' => '1',
        'timestamp' => '1310332162',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '13687',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-3_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128876',
        'status' => '1',
        'timestamp' => '1310332169',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '13688',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-4_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18384',
        'status' => '1',
        'timestamp' => '1310332177',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '13689',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-5_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129467',
        'status' => '1',
        'timestamp' => '1310332186',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '13690',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-6_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15954',
        'status' => '1',
        'timestamp' => '1310332194',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '13691',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-7_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '142354',
        'status' => '1',
        'timestamp' => '1310332205',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '13693',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-8_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '147359',
        'status' => '1',
        'timestamp' => '1310332219',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '13695',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-9_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16010',
        'status' => '1',
        'timestamp' => '1310332227',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '13697',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-10_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130794',
        'status' => '1',
        'timestamp' => '1310332241',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '13699',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-11_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156792',
        'status' => '1',
        'timestamp' => '1310332251',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '13700',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-12_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16637',
        'status' => '1',
        'timestamp' => '1310332258',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '13702',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Jul/Layout-1_Page-13_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '115164',
        'status' => '1',
        'timestamp' => '1310332279',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/accent-edge',
    'tags' => array(
      '5' => array(
        '2611' => array(
          'tid' => '2611',
          'vid' => '5',
          'name' => 'BO ZHANG',
          'description' => 'http://www.boandbro.com/home/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'BO ZHANG',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
