array(
  array(
    'nid' => '3776',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1313415831',
    'changed' => '1403917827',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3776',
    'revision_uid' => '1',
    'title' => 'Jaunty Chapeau',
    'body' => '<p>
	Hats are hot.<br />
	Exclusive photography by <a href="http://www.troymattisonhicks.com/">Troy Mattison Hicks</a>.<br />
	Model ~ Daniel Finlan at Q.</p>
',
    'teaser' => '<p>
	Hats are hot.<br />
	Exclusive photography by <a href="http://www.troymattisonhicks.com/">Troy Mattison Hicks</a>.<br />
	Model ~ Daniel Finlan at Q.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917827',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.troymattisonhicks.com/">TROY MATTISON HICKS</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	JAMES N</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	STEPHANO DIAZ</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	DANIEL FINLAN<br />
	AT Q</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '13963',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 4 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '685434',
        'status' => '1',
        'timestamp' => '1312551651',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '1' => array(
        'fid' => '14063',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 5 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '271380',
        'status' => '1',
        'timestamp' => '1312913406',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '2' => array(
        'fid' => '13965',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 6 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '425247',
        'status' => '1',
        'timestamp' => '1312551677',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '3' => array(
        'fid' => '13966',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 7 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '658562',
        'status' => '1',
        'timestamp' => '1312551689',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '4' => array(
        'fid' => '13967',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 8 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '746277',
        'status' => '1',
        'timestamp' => '1312551703',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '5' => array(
        'fid' => '13968',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 9 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '512096',
        'status' => '1',
        'timestamp' => '1312551721',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '6' => array(
        'fid' => '13969',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 10 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '598039',
        'status' => '1',
        'timestamp' => '1312551730',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '7' => array(
        'fid' => '13970',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 11 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '703244',
        'status' => '1',
        'timestamp' => '1312551741',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '8' => array(
        'fid' => '13971',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 12 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '428148',
        'status' => '1',
        'timestamp' => '1312551750',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '9' => array(
        'fid' => '13972',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 13 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '660538',
        'status' => '1',
        'timestamp' => '1312551761',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
      '10' => array(
        'fid' => '13973',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 14 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 14 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '564309',
        'status' => '1',
        'timestamp' => '1312551777',
        'origname' => 'Layout 1_Page 14 copy.jpg',
      ),
      '11' => array(
        'fid' => '13974',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 15 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 15 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '856315',
        'status' => '1',
        'timestamp' => '1312551788',
        'origname' => 'Layout 1_Page 15 copy.jpg',
      ),
      '12' => array(
        'fid' => '13975',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 16 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 16 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88165',
        'status' => '1',
        'timestamp' => '1312551800',
        'origname' => 'Layout 1_Page 16 copy.jpg',
      ),
      '13' => array(
        'fid' => '13976',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 17 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 17 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '776365',
        'status' => '1',
        'timestamp' => '1312551816',
        'origname' => 'Layout 1_Page 17 copy.jpg',
      ),
    ),
    'path' => 'stories/jaunty-chapeau',
    'tags' => array(
      '1' => array(
        '318' => array(
          'tid' => '318',
          'vid' => '1',
          'name' => 'General Idea',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '393' => array(
          'tid' => '393',
          'vid' => '1',
          'name' => 'Kangol',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '320' => array(
          'tid' => '320',
          'vid' => '1',
          'name' => 'Plain Jane Homme',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '317' => array(
          'tid' => '317',
          'vid' => '1',
          'name' => 'Trovata',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2638' => array(
          'tid' => '2638',
          'vid' => '5',
          'name' => 'TROY MATTISON HICKS',
          'description' => 'http://www.troymattisonhicks.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'General Idea, Kangol, Plain Jane Homme, Trovata',
        '4' => 'men',
        '5' => 'TROY MATTISON HICKS',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
