array(
  array(
    'nid' => '3783',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1312844302',
    'changed' => '1337804200',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3783',
    'revision_uid' => '1',
    'title' => 'Shady',
    'body' => '<p>
	Shady character.<br />
	Exclusive photography by <a href="http://www.troymattisonhicks.com/">Troy Mattison Hicks</a>.<br />
	Model ~ Billy Morgan at Ford.</p>
',
    'teaser' => '<p>
	Shady character.<br />
	Exclusive photography by <a href="http://www.troymattisonhicks.com/">Troy Mattison Hicks</a>.<br />
	Model ~ Billy Morgan at Ford.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804200',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.troymattisonhicks.com/"> TROY MATTISON HICKS</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	JAMES N</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	SETPHANO DIAZ</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	BILLY MORGAN<br />
	AT FORD</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14021',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-2_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100699',
        'status' => '1',
        'timestamp' => '1312757556',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '14022',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-3_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156369',
        'status' => '1',
        'timestamp' => '1312757567',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '14023',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-4_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '110312',
        'status' => '1',
        'timestamp' => '1312757577',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '14024',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-5_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107088',
        'status' => '1',
        'timestamp' => '1312757588',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '14027',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-6_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '56721',
        'status' => '1',
        'timestamp' => '1312757773',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '14028',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-7_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139023',
        'status' => '1',
        'timestamp' => '1312757783',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '14029',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-8_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158062',
        'status' => '1',
        'timestamp' => '1312757792',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '14030',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-9_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71415',
        'status' => '1',
        'timestamp' => '1312757800',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '14031',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-10_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16316',
        'status' => '1',
        'timestamp' => '1312757808',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '14032',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-11_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77471',
        'status' => '1',
        'timestamp' => '1312757817',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '14033',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-13_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84056',
        'status' => '1',
        'timestamp' => '1312757839',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '11' => array(
        'fid' => '14037',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-12_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87000',
        'status' => '1',
        'timestamp' => '1312757892',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '12' => array(
        'fid' => '14035',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-14_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1312757866',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '14036',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-15_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83021',
        'status' => '1',
        'timestamp' => '1312757875',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '14038',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-16_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88742',
        'status' => '1',
        'timestamp' => '1312757976',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '14039',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-17_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117674',
        'status' => '1',
        'timestamp' => '1312757989',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '16' => array(
        'fid' => '14040',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-18_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78891',
        'status' => '1',
        'timestamp' => '1312758003',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
      '17' => array(
        'fid' => '14041',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-19.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-19_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90472',
        'status' => '1',
        'timestamp' => '1312758016',
        'origname' => 'Layout-1_Page-19.jpg',
      ),
      '18' => array(
        'fid' => '14042',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-20.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-20_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '24707',
        'status' => '1',
        'timestamp' => '1312758025',
        'origname' => 'Layout-1_Page-20.jpg',
      ),
      '19' => array(
        'fid' => '14043',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-21.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-21_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117121',
        'status' => '1',
        'timestamp' => '1312758038',
        'origname' => 'Layout-1_Page-21.jpg',
      ),
    ),
    'path' => 'stories/shady',
    'tags' => array(
      '5' => array(
        '2634' => array(
          'tid' => '2634',
          'vid' => '5',
          'name' => ' TROY MATTISON HICKS',
          'description' => 'http://www.troymattisonhicks.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '318' => array(
          'tid' => '318',
          'vid' => '1',
          'name' => 'General Idea',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '402' => array(
          'tid' => '402',
          'vid' => '1',
          'name' => 'Mykita',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '316' => array(
          'tid' => '316',
          'vid' => '1',
          'name' => 'Riviera Club',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => ' TROY MATTISON HICKS',
        '1' => 'General Idea, Mykita, Riviera Club',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
