array(
  array(
    'nid' => '3785',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1313672134',
    'changed' => '1403918094',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3785',
    'revision_uid' => '1',
    'title' => 'Sharp',
    'body' => '<p>
	Sharp dressed girls.<br />
	Exclusive photography by Marie-Michele Hayeur.<br />
	Models ~Viktoriya &amp; Trudy at Folio.</p>
',
    'teaser' => '<p>
	Sharp dressed girls.<br />
	Exclusive photography by Marie-Michele Hayeur.<br />
	Models ~Viktoriya &amp; Trudy at Folio.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918094',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	MARIE-MICHELE HAYEUR</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	CHANELLE RIOPELLE</p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	VIKTORIYA<br />
	&amp; TRUDY<br />
	AT FOLIO</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14064',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-2_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155749',
        'status' => '1',
        'timestamp' => '1312927964',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '14065',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout-1_Page-3_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '145215',
        'status' => '1',
        'timestamp' => '1312927978',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '14048',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 4 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '536848',
        'status' => '1',
        'timestamp' => '1312807978',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '14062',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 5 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106033',
        'status' => '1',
        'timestamp' => '1312808383',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '14052',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 8 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '455146',
        'status' => '1',
        'timestamp' => '1312808016',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '5' => array(
        'fid' => '14053',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 9 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '585487',
        'status' => '1',
        'timestamp' => '1312808026',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '6' => array(
        'fid' => '14054',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 10 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '565035',
        'status' => '1',
        'timestamp' => '1312808037',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '7' => array(
        'fid' => '14055',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 11 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91017',
        'status' => '1',
        'timestamp' => '1312808048',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '8' => array(
        'fid' => '14056',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 12 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82057',
        'status' => '1',
        'timestamp' => '1312808058',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '9' => array(
        'fid' => '14057',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 13 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '605240',
        'status' => '1',
        'timestamp' => '1312808068',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
      '10' => array(
        'fid' => '14058',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 14 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 14 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '742096',
        'status' => '1',
        'timestamp' => '1312808078',
        'origname' => 'Layout 1_Page 14 copy.jpg',
      ),
      '11' => array(
        'fid' => '14059',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 15 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 15 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89426',
        'status' => '1',
        'timestamp' => '1312808087',
        'origname' => 'Layout 1_Page 15 copy.jpg',
      ),
      '12' => array(
        'fid' => '14060',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 16 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 16 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109549',
        'status' => '1',
        'timestamp' => '1312808097',
        'origname' => 'Layout 1_Page 16 copy.jpg',
      ),
      '13' => array(
        'fid' => '14061',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 17 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Aug/Layout 1_Page 17 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '509124',
        'status' => '1',
        'timestamp' => '1312808115',
        'origname' => 'Layout 1_Page 17 copy.jpg',
      ),
    ),
    'path' => 'stories/sharp',
    'tags' => array(
      '5' => array(
        '2641' => array(
          'tid' => '2641',
          'vid' => '5',
          'name' => 'MARIE-MICHELE HAYEUR',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'MARIE-MICHELE HAYEUR',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
