array(
  array(
    'nid' => '3818',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1316352820',
    'changed' => '1403918093',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3818',
    'revision_uid' => '1',
    'title' => 'Outsiders',
    'body' => '<p>
	Take it outside.<br />
	Exclusive photography by <a href="http://www.frontmanagement.com/">Christian Alexander</a>.<br />
	Models ~ Omahira Mota, Colin Lee, Bobby Llewelyn, and Frederick Valentin.</p>
',
    'teaser' => '<p>
	Take it outside.<br />
	Exclusive photography by <a href="http://www.frontmanagement.com/">Christian Alexander</a>.<br />
	Models ~ Omahira Mota, Colin Lee, Bobby Llewelyn, and Frederick Valentin.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918093',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.frontmanagement.com/">CHRISTIAN ALEXANDER</a><br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	RAQUEL AT ORTIZ/KELI</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	OMAHIRA MOTA,<br />
	COLIN LEE,<br />
	BOBBY LLEWELYN,<br />
	FREDERICK VALENTIN</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14466',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 2 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '976248',
        'status' => '1',
        'timestamp' => '1316093549',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '14485',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 3 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '172252',
        'status' => '1',
        'timestamp' => '1316093875',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '14469',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 4 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '475198',
        'status' => '1',
        'timestamp' => '1316093589',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '14470',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 5 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '511154',
        'status' => '1',
        'timestamp' => '1316093599',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '14471',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 6 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '719203',
        'status' => '1',
        'timestamp' => '1316093613',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '14473',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 7 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91876',
        'status' => '1',
        'timestamp' => '1316093658',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '14475',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 8 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '692474',
        'status' => '1',
        'timestamp' => '1316093668',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '14476',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 9 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '620648',
        'status' => '1',
        'timestamp' => '1316093679',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '14478',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 10 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '922488',
        'status' => '1',
        'timestamp' => '1316093699',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '14479',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 11 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '533973',
        'status' => '1',
        'timestamp' => '1316093711',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '14481',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 12 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '723132',
        'status' => '1',
        'timestamp' => '1316093733',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '14482',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 13 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '453281',
        'status' => '1',
        'timestamp' => '1316093744',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
      '12' => array(
        'fid' => '14483',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 14 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 14 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '817607',
        'status' => '1',
        'timestamp' => '1316093759',
        'origname' => 'Layout 1_Page 14 copy.jpg',
      ),
      '13' => array(
        'fid' => '14484',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 15 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 15 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '809256',
        'status' => '1',
        'timestamp' => '1316093774',
        'origname' => 'Layout 1_Page 15 copy.jpg',
      ),
    ),
    'path' => 'stories/outsiders',
    'tags' => array(
      '5' => array(
        '2636' => array(
          'tid' => '2636',
          'vid' => '5',
          'name' => 'CHRISTIAN ALEXANDER',
          'description' => 'http://www.frontmanagement.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '276' => array(
          'tid' => '276',
          'vid' => '1',
          'name' => 'MAISON MARTIN MARGIELA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '203' => array(
          'tid' => '203',
          'vid' => '1',
          'name' => 'MARC JACOBS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '469' => array(
          'tid' => '469',
          'vid' => '1',
          'name' => 'medussas',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '468' => array(
          'tid' => '468',
          'vid' => '1',
          'name' => 'met',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'CHRISTIAN ALEXANDER',
        '1' => 'MAISON MARTIN MARGIELA, MARC JACOBS, medussas, met',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
