array(
  array(
    'nid' => '3821',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1316524429',
    'changed' => '1316526120',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3821',
    'revision_uid' => '1',
    'title' => 'Hi Panda',
    'body' => '<p>
	Shanghai artist Jiji&#39;s <a href="http://www.hi-panda.com/us/">Hi Panda</a> collection is a bear essential.<br />
	&nbsp;</p>
',
    'teaser' => '<p>
	Shanghai artist Jiji&#39;s <a href="http://www.hi-panda.com/us/">Hi Panda</a> collection is a bear essential.<br />
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1316526120',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.hi-panda.com/us/">HI PANDA PARIS<br />
	</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14522',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 2 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '389544',
        'status' => '1',
        'timestamp' => '1316524357',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '14523',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 3 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '312742',
        'status' => '1',
        'timestamp' => '1316524373',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '14528',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 4 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '465017',
        'status' => '1',
        'timestamp' => '1316526086',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '14527',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5b copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 5b copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '290260',
        'status' => '1',
        'timestamp' => '1316525735',
        'origname' => 'Layout 1_Page 5b copy.jpg',
      ),
    ),
    'path' => 'stories/hi-panda-0',
    'tags' => array(
      '5' => array(
        '2636' => array(
          'tid' => '2636',
          'vid' => '5',
          'name' => 'CHRISTIAN ALEXANDER',
          'description' => 'http://www.frontmanagement.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '417' => array(
          'tid' => '417',
          'vid' => '1',
          'name' => 'Harvey Nichols',
          'description' => 'www.harveynichols.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '470' => array(
          'tid' => '470',
          'vid' => '1',
          'name' => 'Hi Panda',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '471' => array(
          'tid' => '471',
          'vid' => '1',
          'name' => 'Le Bon Marché',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'CHRISTIAN ALEXANDER',
        '1' => 'Harvey Nichols, Hi Panda, Le Bon Marché',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
