array(
  array(
    'nid' => '3830',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1316455343',
    'changed' => '1403918093',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3830',
    'revision_uid' => '1',
    'title' => 'Roman Fisher',
    'body' => '<p>
	Roman rocks.<br />
	Exclusive photography by <a href="http://www.tysonvick.com/">Tyson Vick</a>.</p>
',
    'teaser' => '<p>
	Roman rocks.<br />
	Exclusive photography by <a href="http://www.tysonvick.com/">Tyson Vick</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918093',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.reverbnation.com/clarkcandles" target="_blank">CLARK AND CANDLES</a></p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.tysonvick.com/">TYSON VICK</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14603',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 2 copy_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '537936',
        'status' => '1',
        'timestamp' => '1317319278',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '14604',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 3 copy_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '504660',
        'status' => '1',
        'timestamp' => '1317319292',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '14605',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 4 copy_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '876986',
        'status' => '1',
        'timestamp' => '1317319303',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '14606',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 5 copy_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '774474',
        'status' => '1',
        'timestamp' => '1317319314',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '14607',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 6 copy_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '759461',
        'status' => '1',
        'timestamp' => '1317319325',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '14609',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 7 copy_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '326357',
        'status' => '1',
        'timestamp' => '1317319901',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
    ),
    'path' => 'stories/roman-fisher',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2647' => array(
          'tid' => '2647',
          'vid' => '5',
          'name' => 'SARA FORREST',
          'description' => 'http://www.saraforrestphoto.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '4' => 'men, women',
        '5' => 'SARA FORREST',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
