array(
  array(
    'nid' => '3832',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1316370855',
    'changed' => '1337803111',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3832',
    'revision_uid' => '1',
    'title' => 'Malek',
    'body' => '<p>
	Marvelous Malek.<br />
	Exclusive photography by <a href="http://www.davidvance.com/">David Vance</a>.</p>
',
    'teaser' => '<p>
	Marvelous Malek.<br />
	Exclusive photography by <a href="http://www.davidvance.com/">David Vance</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1337803111',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.iammalek.com/">MALEK </a></p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.davidvance.com/"> DAVID VANCE</a><br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14611',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 2 copy_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '384845',
        'status' => '1',
        'timestamp' => '1317406470',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '14612',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 3 copy_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '547457',
        'status' => '1',
        'timestamp' => '1317406482',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '14614',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 4 copy_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '516152',
        'status' => '1',
        'timestamp' => '1317406497',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '14615',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 5 copy_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '528222',
        'status' => '1',
        'timestamp' => '1317406504',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '14617',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 6 copy_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '492173',
        'status' => '1',
        'timestamp' => '1317406520',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '14618',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 7 copy_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '712229',
        'status' => '1',
        'timestamp' => '1317406532',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '14619',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 8 copy_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '570385',
        'status' => '1',
        'timestamp' => '1317407629',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '14622',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy_9.jpg',
        'filepath' => 'files/fmag_story/2011/Sep/Layout 1_Page 9 copy_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173311',
        'status' => '1',
        'timestamp' => '1317420981',
        'origname' => 'Layout 1_Page 9 copy_9.jpg',
      ),
    ),
    'path' => 'stories/malek',
    'tags' => array(
      '5' => array(
        '2647' => array(
          'tid' => '2647',
          'vid' => '5',
          'name' => 'SARA FORREST',
          'description' => 'http://www.saraforrestphoto.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'SARA FORREST',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
