array(
  array(
    'nid' => '3834',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1317492330',
    'changed' => '1403918093',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3834',
    'revision_uid' => '1',
    'title' => 'No Time For Playtime',
    'body' => '<p>
	New wavey play.<br />
	Exclusive photography by <a href="http://www.maxkopanygin.com/">Max Kopanygin</a>.<br />
	Model ~ Dervla at Annabelle Cho.</p>
',
    'teaser' => '<p>
	New wavey play.<br />
	Exclusive photography by <a href="http://www.maxkopanygin.com/">Max Kopanygin</a>.<br />
	Model ~ Dervla at Annabelle Cho.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918093',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.maxkopanygin.com/"> MAX KOPANYGIN</a><br />
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	VALERIYA VALD</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	DERVLA AT<br />
	ANNABELLE CHO</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14623',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '42607',
        'status' => '1',
        'timestamp' => '1317492172',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '14640',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123723',
        'status' => '1',
        'timestamp' => '1317601666',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '14626',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '43635',
        'status' => '1',
        'timestamp' => '1317492197',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '14628',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130909',
        'status' => '1',
        'timestamp' => '1317492212',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '14629',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '48760',
        'status' => '1',
        'timestamp' => '1317492224',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '14630',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1317492238',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '14631',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98527',
        'status' => '1',
        'timestamp' => '1317492252',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '14632',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134856',
        'status' => '1',
        'timestamp' => '1317492267',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '14634',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68506',
        'status' => '1',
        'timestamp' => '1317492281',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '14635',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15879',
        'status' => '1',
        'timestamp' => '1317492290',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '14636',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94708',
        'status' => '1',
        'timestamp' => '1317492305',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '14637',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58859',
        'status' => '1',
        'timestamp' => '1317492317',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/no-time-playtime',
    'tags' => array(
      '5' => array(
        '2648' => array(
          'tid' => '2648',
          'vid' => '5',
          'name' => ' MAX KOPANYGIN',
          'description' => 'http://www.maxkopanygin.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => ' MAX KOPANYGIN',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
