array(
  array(
    'nid' => '3836',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1317816490',
    'changed' => '1403917825',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3836',
    'revision_uid' => '1',
    'title' => 'Michael Wilcox',
    'body' => '<p>
	Wonderful Wilcox.<br />
	Exclusive photography by Joel Esposito.</p>
',
    'teaser' => '<p>
	Wonderful Wilcox.<br />
	Exclusive photography by Joel Esposito.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917825',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	MICHAEL WILCOX<br />
	@ ELMER OLSEN</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.joelesposito.com/">JOEL ESPOSITO</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14641',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-2_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167276',
        'status' => '1',
        'timestamp' => '1317816394',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '14642',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-3_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100662',
        'status' => '1',
        'timestamp' => '1317816406',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '14644',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-4_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158968',
        'status' => '1',
        'timestamp' => '1317816422',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '14645',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-5_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11378',
        'status' => '1',
        'timestamp' => '1317816429',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '14646',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-6_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '151376',
        'status' => '1',
        'timestamp' => '1317816442',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '14647',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-7_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78506',
        'status' => '1',
        'timestamp' => '1317816455',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '14648',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-8_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97182',
        'status' => '1',
        'timestamp' => '1317816470',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '14650',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout-1_Page-9_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113588',
        'status' => '1',
        'timestamp' => '1317816698',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
    ),
    'path' => 'stories/michael-wilcox',
    'tags' => array(
      '5' => array(
        '2648' => array(
          'tid' => '2648',
          'vid' => '5',
          'name' => ' MAX KOPANYGIN',
          'description' => 'http://www.maxkopanygin.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => ' MAX KOPANYGIN',
        '4' => 'men',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
