array(
  array(
    'nid' => '3840',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1318011879',
    'changed' => '1318011879',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3840',
    'revision_uid' => '1',
    'title' => 'Test post',
    'body' => '<p>
	testing 1234</p>
',
    'teaser' => '<p>
	testing 1234</p>
',
    'log' => '',
    'revision_timestamp' => '1318011879',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14668',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'facesBanner.png',
        'filepath' => 'files/fmag_story/2011/Oct/facesBanner.png',
        'filemime' => 'image/png',
        'filesize' => '1136',
        'status' => '1',
        'timestamp' => '1318011849',
        'origname' => 'facesBanner.png',
      ),
      '1' => array(
        'fid' => '14670',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'v_2.png',
        'filepath' => 'files/fmag_story/2011/Oct/v_2.png',
        'filemime' => 'image/png',
        'filesize' => '266284',
        'status' => '1',
        'timestamp' => '1318011867',
        'origname' => 'v_2.png',
      ),
    ),
    'path' => 'stories/test-post',
    'tags' => array(),
    'taxonomy' => array(
      '2' => array(
        '2' => '2',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
