array(
  array(
    'nid' => '3843',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1318350074',
    'changed' => '1337802995',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3843',
    'revision_uid' => '1',
    'title' => 'Plum',
    'body' => '<p>
	Plum crazy.<br />
	Exclusive photography by <a href="http://www.davidvance.com/">David Vance</a>.</p>
',
    'teaser' => '<p>
	Plum crazy.<br />
	Exclusive photography by <a href="http://www.davidvance.com/">David Vance</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1337802995',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	MODEL<br />
	ERIC MICHAEL</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.davidvance.com/"> DAVID VANCE</a><br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14726',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 2 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '608776',
        'status' => '1',
        'timestamp' => '1318609273',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '14727',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 3 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '525663',
        'status' => '1',
        'timestamp' => '1318609312',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '14729',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 4 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '523175',
        'status' => '1',
        'timestamp' => '1318609327',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '14730',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 5 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '611027',
        'status' => '1',
        'timestamp' => '1318609336',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '14732',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 6 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '458770',
        'status' => '1',
        'timestamp' => '1318609352',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '14733',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 7 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '333635',
        'status' => '1',
        'timestamp' => '1318609361',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '14734',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 8 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '766385',
        'status' => '1',
        'timestamp' => '1318609376',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '14735',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 9 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '467982',
        'status' => '1',
        'timestamp' => '1318609388',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
    ),
    'path' => 'stories/plum',
    'tags' => array(
      '5' => array(
        '2649' => array(
          'tid' => '2649',
          'vid' => '5',
          'name' => ' SAMANTHA JARRETT',
          'description' => 'http://samanthajarrett.co.uk',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => ' SAMANTHA JARRETT',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
