array(
  array(
    'nid' => '3845',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1319050223',
    'changed' => '1403917824',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3845',
    'revision_uid' => '1',
    'title' => 'Suit You Self',
    'body' => '<p>
	Dress it up a tad.<br />
	Exclusive photography by <a href="http://www.curtisbenjamin.com/">Curtis Benjamin</a>.<br />
	Model ~ Thomas Ivasaki at M&amp;P.</p>
',
    'teaser' => '<p>
	Dress it up a tad.<br />
	Exclusive photography by <a href="http://www.curtisbenjamin.com/">Curtis Benjamin</a>.<br />
	Model ~ Thomas Ivasaki at M&amp;P.</p>
',
    'log' => '',
    'revision_timestamp' => '1403917824',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.curtisbenjamin.com/">CURTIS BENJAMIN</a><br />
	<a href="http://samanthajarrett.co.uk/"> </a><br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	DENISE BROWN</p>
<p>
	<br />
	<a href="http://biancachristoff.com/"> </a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	THOMAS IVASAKI<br />
	AT M&amp;P</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14737',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 2 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '162061',
        'status' => '1',
        'timestamp' => '1319050144',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '14738',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 3 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '472047',
        'status' => '1',
        'timestamp' => '1319050161',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '14739',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 4 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '850062',
        'status' => '1',
        'timestamp' => '1319050198',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '14740',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 5 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84896',
        'status' => '1',
        'timestamp' => '1319050214',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '14741',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 6 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75238',
        'status' => '1',
        'timestamp' => '1319050256',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '14743',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 7 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '696984',
        'status' => '1',
        'timestamp' => '1319050292',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '14744',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 8 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '804320',
        'status' => '1',
        'timestamp' => '1319050316',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '14745',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 9 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '628021',
        'status' => '1',
        'timestamp' => '1319050341',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '14746',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 10 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '609935',
        'status' => '1',
        'timestamp' => '1319050400',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '14747',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 11 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81072',
        'status' => '1',
        'timestamp' => '1319050426',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '14748',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 12 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '747344',
        'status' => '1',
        'timestamp' => '1319050498',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '14749',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 13 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87802',
        'status' => '1',
        'timestamp' => '1319050516',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
      '12' => array(
        'fid' => '14750',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 14 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 14 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '714961',
        'status' => '1',
        'timestamp' => '1319050548',
        'origname' => 'Layout 1_Page 14 copy.jpg',
      ),
      '13' => array(
        'fid' => '14751',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 15 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 15 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83633',
        'status' => '1',
        'timestamp' => '1319050566',
        'origname' => 'Layout 1_Page 15 copy.jpg',
      ),
      '14' => array(
        'fid' => '14752',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 16 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 16 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '755323',
        'status' => '1',
        'timestamp' => '1319050590',
        'origname' => 'Layout 1_Page 16 copy.jpg',
      ),
      '15' => array(
        'fid' => '14753',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 17 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 17 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '583787',
        'status' => '1',
        'timestamp' => '1319050613',
        'origname' => 'Layout 1_Page 17 copy.jpg',
      ),
    ),
    'path' => 'stories/suit-you-self',
    'tags' => array(
      '5' => array(
        '2627' => array(
          'tid' => '2627',
          'vid' => '5',
          'name' => 'CURTIS BENJAMIN',
          'description' => 'http://curtisbenjamin.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'CURTIS BENJAMIN',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
