array(
  array(
    'nid' => '3850',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1319475699',
    'changed' => '1403918092',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3850',
    'revision_uid' => '1',
    'title' => 'Stain',
    'body' => '<p>
	Evening dress.<br />
	Exclusive photography by <a href="http://www.rackydiack.com/">Racky Diack</a>.<br />
	Models ~ Rachel &amp; Tianna at Next.</p>
',
    'teaser' => '<p>
	Evening dress.<br />
	Exclusive photography by <a href="http://www.rackydiack.com/">Racky Diack</a>.<br />
	Models ~ Rachel &amp; Tianna at Next.</p>
',
    'log' => '',
    'revision_timestamp' => '1403918092',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.rackydiack.com/">RACKY DIACK</a><br />
	<br />
	<a href="http://samanthajarrett.co.uk/"> </a><br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	FAUSTINE IGNEGONGBA</p>
<p>
	<br />
	<a href="http://biancachristoff.com/"> </a></p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	RACHEL &amp; TIANNA<br />
	AT NEXT</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '14801',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 2 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130953',
        'status' => '1',
        'timestamp' => '1319459047',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '14802',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 3 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '375596',
        'status' => '1',
        'timestamp' => '1319459054',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '14804',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 4 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '310050',
        'status' => '1',
        'timestamp' => '1319459067',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '14819',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 5 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80366',
        'status' => '1',
        'timestamp' => '1319459486',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '14820',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 6 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76929',
        'status' => '1',
        'timestamp' => '1319459498',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '14821',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 7 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '272714',
        'status' => '1',
        'timestamp' => '1319459553',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '14822',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 8 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '663847',
        'status' => '1',
        'timestamp' => '1319459567',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '14823',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 9 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75238',
        'status' => '1',
        'timestamp' => '1319459579',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '14832',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 10 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82098',
        'status' => '1',
        'timestamp' => '1319460490',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '14825',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 11 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '288873',
        'status' => '1',
        'timestamp' => '1319459617',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '14826',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 12 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75210',
        'status' => '1',
        'timestamp' => '1319459626',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '14827',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 13 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '417399',
        'status' => '1',
        'timestamp' => '1319459637',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
      '12' => array(
        'fid' => '14828',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 14 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 14 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '531966',
        'status' => '1',
        'timestamp' => '1319459651',
        'origname' => 'Layout 1_Page 14 copy.jpg',
      ),
      '13' => array(
        'fid' => '14829',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 15 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 15 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75240',
        'status' => '1',
        'timestamp' => '1319459664',
        'origname' => 'Layout 1_Page 15 copy.jpg',
      ),
      '14' => array(
        'fid' => '14830',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 16 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 16 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '361712',
        'status' => '1',
        'timestamp' => '1319459676',
        'origname' => 'Layout 1_Page 16 copy.jpg',
      ),
      '15' => array(
        'fid' => '14831',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 17 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Oct/Layout 1_Page 17 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '505725',
        'status' => '1',
        'timestamp' => '1319459687',
        'origname' => 'Layout 1_Page 17 copy.jpg',
      ),
    ),
    'path' => 'stories/stain',
    'tags' => array(
      '1' => array(
        '129' => array(
          'tid' => '129',
          'vid' => '1',
          'name' => 'American Apparel',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '508' => array(
          'tid' => '508',
          'vid' => '1',
          'name' => 'duy',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '155' => array(
          'tid' => '155',
          'vid' => '1',
          'name' => 'ZARA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2651' => array(
          'tid' => '2651',
          'vid' => '5',
          'name' => 'RACKY DIACK',
          'description' => 'http://www.rackydiack.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'American Apparel, duy, ZARA',
        '5' => 'RACKY DIACK',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
