array(
  array(
    'nid' => '3866',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1320445602',
    'changed' => '1403838741',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3866',
    'revision_uid' => '1',
    'title' => 'Travis Van Winkle',
    'body' => '<p>
	Actor Travis Van Winkle.<br />
	Exclusive photography by <a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">Aldo Rossi</a>.<br />
	Interview by James Nixon.<br />
	&nbsp;</p>
',
    'teaser' => '<p>
	Actor Travis Van Winkle.<br />
	Exclusive photography by <a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">Aldo Rossi</a>.<br />
	Interview by James Nixon.<br />
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1403838741',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">ALDO ROSSI</a></p>
<p>
	&nbsp;</p>
<p>
	INTERVIEW BY<br />
	JAMES NIXON</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	ANGELA AARON<br />
	AT REX ARTISTS</p>
<p>
	&nbsp;</p>
<p>
	REPRESENTATION<br />
	L.A. MODELS</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15047',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2A.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout-1_Page-2A.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '48667',
        'status' => '1',
        'timestamp' => '1320272791',
        'origname' => 'Layout-1_Page-2A.jpg',
      ),
      '1' => array(
        'fid' => '15050',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '464150',
        'status' => '1',
        'timestamp' => '1320344391',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '15051',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '547168',
        'status' => '1',
        'timestamp' => '1320344404',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '15078',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '321441',
        'status' => '1',
        'timestamp' => '1320410343',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '15081',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '415964',
        'status' => '1',
        'timestamp' => '1320412093',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '15053',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '438017',
        'status' => '1',
        'timestamp' => '1320344437',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '15079',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '442372',
        'status' => '1',
        'timestamp' => '1320410362',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '15080',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '509795',
        'status' => '1',
        'timestamp' => '1320410379',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '15058',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '558613',
        'status' => '1',
        'timestamp' => '1320344735',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '15059',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '640090',
        'status' => '1',
        'timestamp' => '1320344751',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '15060',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '680976',
        'status' => '1',
        'timestamp' => '1320344769',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '15061',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '654489',
        'status' => '1',
        'timestamp' => '1320344784',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
      '12' => array(
        'fid' => '15253',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 14 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '575187',
        'status' => '1',
        'timestamp' => '1321292751',
        'origname' => 'Layout 1_Page 14 copy.jpg',
      ),
      '13' => array(
        'fid' => '15075',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 15 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '421283',
        'status' => '1',
        'timestamp' => '1320410241',
        'origname' => 'Layout 1_Page 15 copy.jpg',
      ),
      '14' => array(
        'fid' => '15076',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 16 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 16 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '555759',
        'status' => '1',
        'timestamp' => '1320410262',
        'origname' => 'Layout 1_Page 16 copy.jpg',
      ),
      '15' => array(
        'fid' => '15077',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 17 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 17 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '775595',
        'status' => '1',
        'timestamp' => '1320410283',
        'origname' => 'Layout 1_Page 17 copy.jpg',
      ),
    ),
    'path' => 'stories/travis-van-winkle',
    'tags' => array(
      '5' => array(
        '2633' => array(
          'tid' => '2633',
          'vid' => '5',
          'name' => 'ALDO ROSSI',
          'description' => 'http://www.studioaldorossi.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ALDO ROSSI',
        '4' => 'men',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
