array(
  array(
    'nid' => '3871',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1321277898',
    'changed' => '1403838740',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3871',
    'revision_uid' => '1',
    'title' => 'Rodrigo Otazu',
    'body' => '<p>
	Jewelry designer <a href="http://www.rodrigootazu.com/">Rodrigo Otazu</a>.<br />
	Interview by Heather MacDonald.</p>
',
    'teaser' => '<p>
	Jewelry designer <a href="http://www.rodrigootazu.com/">Rodrigo Otazu</a>.<br />
	Interview by Heather MacDonald.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838740',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.rodrigootazu.com/"><span>RODRIGO OTAZU</span></a></p>
<p>
	&nbsp;</p>
<p>
	INTERVIEW BY<br />
	HEATHER MACDONALD</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15161',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158052',
        'status' => '1',
        'timestamp' => '1320677061',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '15152',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 3 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '516449',
        'status' => '1',
        'timestamp' => '1320676600',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '15162',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 4 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '245192',
        'status' => '1',
        'timestamp' => '1320677334',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '15155',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 5 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '383237',
        'status' => '1',
        'timestamp' => '1320676624',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '15157',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 6 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '610899',
        'status' => '1',
        'timestamp' => '1320676644',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '15158',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 7 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '518885',
        'status' => '1',
        'timestamp' => '1320676656',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '15159',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 8 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '323785',
        'status' => '1',
        'timestamp' => '1320676671',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '15160',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 9 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '400205',
        'status' => '1',
        'timestamp' => '1320676686',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
    ),
    'path' => 'stories/rodrigo-otazu',
    'tags' => array(
      '5' => array(
        '2633' => array(
          'tid' => '2633',
          'vid' => '5',
          'name' => 'ALDO ROSSI',
          'description' => 'http://www.studioaldorossi.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ALDO ROSSI',
        '4' => 'men',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
