array(
  array(
    'nid' => '3876',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1321068131',
    'changed' => '1403838741',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3876',
    'revision_uid' => '1',
    'title' => 'Grunge Effect',
    'body' => '<p>
	Grunge takes a modern slant.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.<br />
	Model ~ Frankie Wade @ Select.</p>
',
    'teaser' => '<p>
	Grunge takes a modern slant.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.<br />
	Model ~ Frankie Wade @ Select.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838741',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://darrenblackphotography.com/">DARREN BLACK</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	OLIVER VAUGHN</p>
<p>
	&nbsp;</p>
<p>
	GROOMING<br />
	<a href="http://www.josieheightontowers.co.uk/">JOSIE HEIGHTON-TOWERS</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	FRANKIE WADE<br />
	AT SELECT</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15208',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_2.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_2_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114637',
        'status' => '1',
        'timestamp' => '1320808964',
        'origname' => 'Grunge-Effect_2.jpg',
      ),
      '1' => array(
        'fid' => '15209',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_3.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_3_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '43174',
        'status' => '1',
        'timestamp' => '1320808972',
        'origname' => 'Grunge-Effect_3.jpg',
      ),
      '2' => array(
        'fid' => '15221',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_4.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_4_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19460',
        'status' => '1',
        'timestamp' => '1320809531',
        'origname' => 'Grunge-Effect_4.jpg',
      ),
      '3' => array(
        'fid' => '15211',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_5.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_5_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71444',
        'status' => '1',
        'timestamp' => '1320809004',
        'origname' => 'Grunge-Effect_5.jpg',
      ),
      '4' => array(
        'fid' => '15212',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_6.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_6_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94156',
        'status' => '1',
        'timestamp' => '1320809026',
        'origname' => 'Grunge-Effect_6.jpg',
      ),
      '5' => array(
        'fid' => '15213',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_7.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_7_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '54687',
        'status' => '1',
        'timestamp' => '1320809046',
        'origname' => 'Grunge-Effect_7.jpg',
      ),
      '6' => array(
        'fid' => '15214',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_8.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_8_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63577',
        'status' => '1',
        'timestamp' => '1320809066',
        'origname' => 'Grunge-Effect_8.jpg',
      ),
      '7' => array(
        'fid' => '15222',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_9.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_9_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13309',
        'status' => '1',
        'timestamp' => '1320809544',
        'origname' => 'Grunge-Effect_9.jpg',
      ),
      '8' => array(
        'fid' => '15223',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_10.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_10_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17776',
        'status' => '1',
        'timestamp' => '1320809564',
        'origname' => 'Grunge-Effect_10.jpg',
      ),
      '9' => array(
        'fid' => '15217',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_11.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_11_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98492',
        'status' => '1',
        'timestamp' => '1320809154',
        'origname' => 'Grunge-Effect_11.jpg',
      ),
      '10' => array(
        'fid' => '15218',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_12.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_12_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97021',
        'status' => '1',
        'timestamp' => '1320809170',
        'origname' => 'Grunge-Effect_12.jpg',
      ),
      '11' => array(
        'fid' => '15219',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Grunge-Effect_13.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Grunge-Effect_13_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '52769',
        'status' => '1',
        'timestamp' => '1320809190',
        'origname' => 'Grunge-Effect_13.jpg',
      ),
    ),
    'path' => 'stories/grunge-effect-0',
    'tags' => array(
      '1' => array(
        '454' => array(
          'tid' => '454',
          'vid' => '1',
          'name' => 'beyond retro',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '554' => array(
          'tid' => '554',
          'vid' => '1',
          'name' => 'ems',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '553' => array(
          'tid' => '553',
          'vid' => '1',
          'name' => 'katie eary',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '195' => array(
          'tid' => '195',
          'vid' => '1',
          'name' => 'LEVIS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '552' => array(
          'tid' => '552',
          'vid' => '1',
          'name' => 'rokit',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '229' => array(
          'tid' => '229',
          'vid' => '1',
          'name' => 'TOPMAN',
          'description' => 'www.topman.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '555' => array(
          'tid' => '555',
          'vid' => '1',
          'name' => 'year 0 London',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'beyond retro, ems, katie eary, LEVIS, rokit, TOPMAN, year 0 London',
        '5' => 'Darren Black',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
