array(
  array(
    'nid' => '3879',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1321196962',
    'changed' => '1403838951',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3879',
    'revision_uid' => '1',
    'title' => 'Alanna',
    'body' => '<p>
	Alluring Alanna.<br />
	Exclusive photography by <a href="http://www.joelesposito.com/">Joel Esposito</a>.</p>
',
    'teaser' => '<p>
	Alluring Alanna.<br />
	Exclusive photography by <a href="http://www.joelesposito.com/">Joel Esposito</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838951',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.joelesposito.com/">JOEL ESPOSITO</a></p>
<p>
	<br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15231',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 2 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '356427',
        'status' => '1',
        'timestamp' => '1320937605',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '15232',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 3 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '540417',
        'status' => '1',
        'timestamp' => '1320937632',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '15233',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 4 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '360871',
        'status' => '1',
        'timestamp' => '1320937648',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '15234',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 5 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '541613',
        'status' => '1',
        'timestamp' => '1320937661',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '15235',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 6 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75376',
        'status' => '1',
        'timestamp' => '1320937675',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '15236',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 7 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '313417',
        'status' => '1',
        'timestamp' => '1320937696',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '15237',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 8 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '383993',
        'status' => '1',
        'timestamp' => '1320937718',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '15238',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 9 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '259725',
        'status' => '1',
        'timestamp' => '1320937741',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
    ),
    'path' => 'stories/alanna',
    'tags' => array(
      '5' => array(
        '2618' => array(
          'tid' => '2618',
          'vid' => '5',
          'name' => 'JOEL ESPOSITO',
          'description' => 'http://www.joelesposito.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'JOEL ESPOSITO',
        '4' => 'women',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
