array(
  array(
    'nid' => '3881',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1321385859',
    'changed' => '1405544108',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3881',
    'revision_uid' => '1',
    'title' => 'Lucas Kerr',
    'body' => '<p>
	Actor Lucas Kerr.<br />
	Exclusive photography by <a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">Aldo Rossi</a>.<br />
	Interview by James Nixon.</p>
',
    'teaser' => '<p>
	Actor Lucas Kerr.<br />
	Exclusive photography by <a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">Aldo Rossi</a>.<br />
	Interview by James Nixon.</p>
',
    'log' => '',
    'revision_timestamp' => '1405544108',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">ALDO ROSSI</a></p>
<p>
	&nbsp;</p>
<p>
	INTERVIEW BY<br />
	JAMES NIXON</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	ANGELA AARON<br />
	AT REX ARTISTS</p>
<p>
	&nbsp;</p>
<p>
	REPRESENTATION<br />
	L.A. MODELS</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15240',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 2 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '395553',
        'status' => '1',
        'timestamp' => '1320953685',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '15241',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 3 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '368689',
        'status' => '1',
        'timestamp' => '1320953699',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '15242',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 4 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '362984',
        'status' => '1',
        'timestamp' => '1320953712',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '15243',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 5 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '460478',
        'status' => '1',
        'timestamp' => '1320953727',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '15244',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 6 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '313144',
        'status' => '1',
        'timestamp' => '1320953741',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '15245',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 7 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '340099',
        'status' => '1',
        'timestamp' => '1320953754',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '15246',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 8 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '453024',
        'status' => '1',
        'timestamp' => '1320953769',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '15247',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 9 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '269114',
        'status' => '1',
        'timestamp' => '1320953784',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '15248',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 10 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '547223',
        'status' => '1',
        'timestamp' => '1320953802',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '15249',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 11 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '554898',
        'status' => '1',
        'timestamp' => '1320953819',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '15250',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 12 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '457056',
        'status' => '1',
        'timestamp' => '1320953833',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '15254',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Nov/Layout 1_Page 13 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '376657',
        'status' => '1',
        'timestamp' => '1321379952',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
    ),
    'path' => 'stories/lucas-kerr',
    'tags' => array(
      '5' => array(
        '2633' => array(
          'tid' => '2633',
          'vid' => '5',
          'name' => 'ALDO ROSSI',
          'description' => 'http://www.studioaldorossi.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2114' => array(
          'tid' => '2114',
          'vid' => '4',
          'name' => 'beards',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ALDO ROSSI',
        '4' => 'beards, men',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
