array(
  array(
    'nid' => '3899',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1323299119',
    'changed' => '1323299488',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3899',
    'revision_uid' => '1',
    'title' => 'Twist',
    'body' => '<p>
	Expect the unexpected.<br />
	Exclusive photography by <a href="http://www.nikolaidevera.com/">Nikolai de vera</a>.<br />
	Model ~ Sunghee at Wilhelmina.</p>
',
    'teaser' => '<p>
	Expect the unexpected.<br />
	Exclusive photography by <a href="http://www.nikolaidevera.com/">Nikolai de vera</a>.<br />
	Model ~ Sunghee at Wilhelmina.</p>
',
    'log' => '',
    'revision_timestamp' => '1323299488',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.nikolaidevera.com/">NIKOLAI DE VERA</a><br />
	<a href="http://www.troymattisonhicks.com/"> </a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	DONALD HICKS</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	SUNGHEE<br />
	AT WILHELMINA</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15548',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '47802',
        'status' => '1',
        'timestamp' => '1323298996',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '15549',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93620',
        'status' => '1',
        'timestamp' => '1323299006',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '15550',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16249',
        'status' => '1',
        'timestamp' => '1323299016',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '15551',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92979',
        'status' => '1',
        'timestamp' => '1323299031',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '15553',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68067',
        'status' => '1',
        'timestamp' => '1323299044',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '15555',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17100',
        'status' => '1',
        'timestamp' => '1323299053',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '15557',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '31767',
        'status' => '1',
        'timestamp' => '1323299063',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '15559',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63804',
        'status' => '1',
        'timestamp' => '1323299074',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '15561',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22308',
        'status' => '1',
        'timestamp' => '1323299082',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '15563',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85321',
        'status' => '1',
        'timestamp' => '1323299092',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '15564',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80016',
        'status' => '1',
        'timestamp' => '1323299099',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '15565',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '70243',
        'status' => '1',
        'timestamp' => '1323299109',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/twist',
    'tags' => array(
      '1' => array(
        '574' => array(
          'tid' => '574',
          'vid' => '1',
          'name' => 'Alexis Bittar',
          'description' => 'www.alexisbittar.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '573' => array(
          'tid' => '573',
          'vid' => '1',
          'name' => 'Balenciaga',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '571' => array(
          'tid' => '571',
          'vid' => '1',
          'name' => 'Ben Amun',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '423' => array(
          'tid' => '423',
          'vid' => '1',
          'name' => 'kenneth jay lane',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '572' => array(
          'tid' => '572',
          'vid' => '1',
          'name' => 'Lulu Frost',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '570' => array(
          'tid' => '570',
          'vid' => '1',
          'name' => 'Nathan Jenden',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '575' => array(
          'tid' => '575',
          'vid' => '1',
          'name' => 'Nicole Millar',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2547' => array(
          'tid' => '2547',
          'vid' => '5',
          'name' => 'Nikolai de Vera',
          'description' => 'http://www.nikolaidevera.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Alexis Bittar, Balenciaga, Ben Amun, kenneth jay lane, Lulu Frost, Nathan Jenden, Nicole Millar',
        '5' => 'Nikolai de Vera',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
