array(
  array(
    'nid' => '3903',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1323804245',
    'changed' => '1403838950',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3903',
    'revision_uid' => '1',
    'title' => 'Supermodel Icons',
    'body' => '<p>
	The best models of all time at <a href="http://supermodelicons.com/">Supermodel icons</a>.</p>
',
    'teaser' => '<p>
	The best models of all time at <a href="http://supermodelicons.com/">Supermodel icons</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838950',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://supermodelicons.com/">SUPERMODEL<br />
	ICONS</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15637',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 2 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '950943',
        'status' => '1',
        'timestamp' => '1323374008',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '15638',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 3 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '935206',
        'status' => '1',
        'timestamp' => '1323374020',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '15639',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 4 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1023878',
        'status' => '1',
        'timestamp' => '1323374039',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '15640',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 5 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '414570',
        'status' => '1',
        'timestamp' => '1323374053',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
    ),
    'path' => 'stories/supermodel-icons',
    'tags' => array(
      '5' => array(
        '2660' => array(
          'tid' => '2660',
          'vid' => '5',
          'name' => 'RICK DAY',
          'description' => 'http://rickdaynyc.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'RICK DAY',
        '4' => 'women',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
