array(
  array(
    'nid' => '3906',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1323885781',
    'changed' => '1403838950',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3906',
    'revision_uid' => '1',
    'title' => 'Marina Zappia',
    'body' => '<p>
	Marvelous Marina.<br />
	Exclusive photography by <a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">Aldo Rossi</a>.<br />
	&nbsp;</p>
',
    'teaser' => '<p>
	Marvelous Marina.<br />
	Exclusive photography by <a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">Aldo Rossi</a>.<br />
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1403838950',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">ALDO ROSSI</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	ERIC BERG<br />
	AT REX ARTISTS</p>
<p>
	&nbsp;</p>
<p>
	REPRESENTATION<br />
	ELITE</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15705',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 2 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '475574',
        'status' => '1',
        'timestamp' => '1323885545',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '15720',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 3 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '530989',
        'status' => '1',
        'timestamp' => '1323886835',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '15707',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 4 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '582662',
        'status' => '1',
        'timestamp' => '1323885574',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '15708',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 5 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '659355',
        'status' => '1',
        'timestamp' => '1323885592',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '15709',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 6 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '775493',
        'status' => '1',
        'timestamp' => '1323885613',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '15713',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 7 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '783981',
        'status' => '1',
        'timestamp' => '1323885676',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '15714',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 8 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '406793',
        'status' => '1',
        'timestamp' => '1323885691',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '15715',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 9 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '556425',
        'status' => '1',
        'timestamp' => '1323885710',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '15716',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 10 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '433337',
        'status' => '1',
        'timestamp' => '1323885732',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '15717',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 11 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '424656',
        'status' => '1',
        'timestamp' => '1323885753',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '15718',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 12 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '697674',
        'status' => '1',
        'timestamp' => '1323885770',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '15719',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 13 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '691742',
        'status' => '1',
        'timestamp' => '1323886180',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
    ),
    'path' => 'stories/marina-zappia',
    'tags' => array(
      '5' => array(
        '2633' => array(
          'tid' => '2633',
          'vid' => '5',
          'name' => 'ALDO ROSSI',
          'description' => 'http://www.studioaldorossi.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ALDO ROSSI',
        '4' => 'women',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
