array(
  array(
    'nid' => '3914',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1324413711',
    'changed' => '1337803035',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3914',
    'revision_uid' => '1',
    'title' => 'CLOSER',
    'body' => '<p>
	Photographers Cecilie Harris and India Hobson get <a href="http://www.blurb.com/bookstore/detail/2774360">CLOSER</a>.</p>
',
    'teaser' => '<p>
	Photographers Cecilie Harris and India Hobson get <a href="http://www.blurb.com/bookstore/detail/2774360">CLOSER</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1337803035',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.blurb.com/bookstore/detail/2774360">CLOSER</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15828',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 2 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '618018',
        'status' => '1',
        'timestamp' => '1324327267',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '15829',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 3 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '314752',
        'status' => '1',
        'timestamp' => '1324327275',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '15831',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 4 copy_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '441289',
        'status' => '1',
        'timestamp' => '1324327290',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '15832',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout 1_Page 5 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '375981',
        'status' => '1',
        'timestamp' => '1324327300',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
    ),
    'path' => 'stories/closer',
    'tags' => array(
      '5' => array(
        '2662' => array(
          'tid' => '2662',
          'vid' => '5',
          'name' => 'SERGEI YAHCHYBEKOV',
          'description' => 'http://serhio.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'SERGEI YAHCHYBEKOV',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
