array(
  array(
    'nid' => '3917',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1324924478',
    'changed' => '1403838735',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3917',
    'revision_uid' => '1',
    'title' => 'Choice ',
    'body' => '<p>
	Some of our choicest cuts from 2011. The year in review part one.</p>
',
    'teaser' => '<p>
	Some of our choicest cuts from 2011. The year in review part one.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838735',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	THE YEAR<br />
	IN REVIEW<br />
	PART ONE</p>
<p>
	COVER STORY<br />
	<a href="http://www.fantasticsmag.com/stories/vest">IN VEST</a><br />
	<br />
	<a href="http://www.fantasticsmag.com/stories/dream-runs-ahead">DREAM RUNS AHEAD</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/vivid">VIVID</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/escapist">THE ESCAPIST</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/water-babies">WATER BABIES</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/trafalgar">TRAFALGAR</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/wild-side-0">WILD SIDE</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/absolute-jeanius">ABSOLUTE JEANIUS</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/modern-world">THIS MODERN WORLD</a><br />
	<br />
	<a href="http://www.fantasticsmag.com/stories/red-new-black">RED IS THE NEW BLACK</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/wood-work">WOOD WORK</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/transitions">TRANSITIONS</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/aura">AURA</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/block-party">BLOCK PARTY</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/diego-barberi">DIEGO BARBERI</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15894',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-4_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '240062',
        'status' => '1',
        'timestamp' => '1324664945',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '1' => array(
        'fid' => '15895',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-5_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '217276',
        'status' => '1',
        'timestamp' => '1324664962',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '2' => array(
        'fid' => '15898',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-16_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '64742',
        'status' => '1',
        'timestamp' => '1324664994',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '3' => array(
        'fid' => '15900',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-17_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128425',
        'status' => '1',
        'timestamp' => '1324665008',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '4' => array(
        'fid' => '15902',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-18_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '53659',
        'status' => '1',
        'timestamp' => '1324665019',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
      '5' => array(
        'fid' => '15904',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-19.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-19_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '243540',
        'status' => '1',
        'timestamp' => '1324665035',
        'origname' => 'Layout-1_Page-19.jpg',
      ),
      '6' => array(
        'fid' => '15906',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-20.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-20_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '120684',
        'status' => '1',
        'timestamp' => '1324665050',
        'origname' => 'Layout-1_Page-20.jpg',
      ),
      '7' => array(
        'fid' => '15908',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-21.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-21_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80302',
        'status' => '1',
        'timestamp' => '1324665061',
        'origname' => 'Layout-1_Page-21.jpg',
      ),
      '8' => array(
        'fid' => '15910',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-22.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-22_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '157022',
        'status' => '1',
        'timestamp' => '1324665075',
        'origname' => 'Layout-1_Page-22.jpg',
      ),
      '9' => array(
        'fid' => '15912',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-23.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-23_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '143605',
        'status' => '1',
        'timestamp' => '1324665089',
        'origname' => 'Layout-1_Page-23.jpg',
      ),
      '10' => array(
        'fid' => '15914',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-24.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-24_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95825',
        'status' => '1',
        'timestamp' => '1324665104',
        'origname' => 'Layout-1_Page-24.jpg',
      ),
      '11' => array(
        'fid' => '15916',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-25.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-25_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158548',
        'status' => '1',
        'timestamp' => '1324665117',
        'origname' => 'Layout-1_Page-25.jpg',
      ),
      '12' => array(
        'fid' => '15918',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-26.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-26_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '198765',
        'status' => '1',
        'timestamp' => '1324665134',
        'origname' => 'Layout-1_Page-26.jpg',
      ),
      '13' => array(
        'fid' => '15920',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-27.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-27_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129480',
        'status' => '1',
        'timestamp' => '1324665149',
        'origname' => 'Layout-1_Page-27.jpg',
      ),
      '14' => array(
        'fid' => '15922',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-28.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-28_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '239456',
        'status' => '1',
        'timestamp' => '1324665167',
        'origname' => 'Layout-1_Page-28.jpg',
      ),
      '15' => array(
        'fid' => '15896',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-15_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116168',
        'status' => '1',
        'timestamp' => '1324664976',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '16' => array(
        'fid' => '15923',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-30.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-30_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156053',
        'status' => '1',
        'timestamp' => '1324665181',
        'origname' => 'Layout-1_Page-30.jpg',
      ),
      '17' => array(
        'fid' => '15925',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-31.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-31_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '146902',
        'status' => '1',
        'timestamp' => '1324665217',
        'origname' => 'Layout-1_Page-31.jpg',
      ),
      '18' => array(
        'fid' => '15927',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-32.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-32_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117728',
        'status' => '1',
        'timestamp' => '1324665230',
        'origname' => 'Layout-1_Page-32.jpg',
      ),
      '19' => array(
        'fid' => '15929',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-33.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-33_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '147226',
        'status' => '1',
        'timestamp' => '1324665245',
        'origname' => 'Layout-1_Page-33.jpg',
      ),
      '20' => array(
        'fid' => '15931',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-34.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-34_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '121496',
        'status' => '1',
        'timestamp' => '1324665257',
        'origname' => 'Layout-1_Page-34.jpg',
      ),
      '21' => array(
        'fid' => '15932',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-35.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-35_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94443',
        'status' => '1',
        'timestamp' => '1324665267',
        'origname' => 'Layout-1_Page-35.jpg',
      ),
    ),
    'path' => 'stories/choice',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
