array(
  array(
    'nid' => '3919',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1325019629',
    'changed' => '1331215198',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3919',
    'revision_uid' => '1',
    'title' => 'Choice 2',
    'body' => '<p>
	Some of our choicest cuts from 2011. The year in review part two.</p>
',
    'teaser' => '<p>
	Some of our choicest cuts from 2011. The year in review part two.</p>
',
    'log' => '',
    'revision_timestamp' => '1331215198',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	THE YEAR<br />
	IN REVIEW<br />
	PART TWO</p>
<p>
	COVER STORY<br />
	<a href="http://www.fantasticsmag.com/stories/just-girl">JUST A GIRL</a></p>
<p>
	<a href="http://fantasticsmag.com/stories/niki">NIKI TAYLOR</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/pow">POW</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/seamstress">SEAMSTRESS</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/smash-hits">SMASH HITS</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/cosmo-girl">COSMO GIRL</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/cold-steel">COLD STEEL</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/fall">FALL IN</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/boy-meets-girl">BOY MEETS GIRL</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/billy-kiraly">BILLY KIRALY</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/below-ground">BELOW GROUND</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/holiday-inn">HOLIDAY INN</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/satisfaction">SATISFACTION</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/eclipse">ECLIPSE</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/esprit-de-corps">ESPIRIT DE CORPS</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/concrete">CONCRETE</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15935',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-134.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-134.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96321',
        'status' => '1',
        'timestamp' => '1325019349',
        'origname' => 'Layout-1_Page-134.jpg',
      ),
      '1' => array(
        'fid' => '15937',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-135.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-135.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76791',
        'status' => '1',
        'timestamp' => '1325019358',
        'origname' => 'Layout-1_Page-135.jpg',
      ),
      '2' => array(
        'fid' => '15939',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-22.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-22_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141249',
        'status' => '1',
        'timestamp' => '1325019368',
        'origname' => 'Layout-1_Page-22.jpg',
      ),
      '3' => array(
        'fid' => '15941',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-23.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-23_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160114',
        'status' => '1',
        'timestamp' => '1325019379',
        'origname' => 'Layout-1_Page-23.jpg',
      ),
      '4' => array(
        'fid' => '15943',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-24.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-24_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129120',
        'status' => '1',
        'timestamp' => '1325019389',
        'origname' => 'Layout-1_Page-24.jpg',
      ),
      '5' => array(
        'fid' => '15945',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-25.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-25_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167508',
        'status' => '1',
        'timestamp' => '1325019402',
        'origname' => 'Layout-1_Page-25.jpg',
      ),
      '6' => array(
        'fid' => '15947',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-26.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-26_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84427',
        'status' => '1',
        'timestamp' => '1325019423',
        'origname' => 'Layout-1_Page-26.jpg',
      ),
      '7' => array(
        'fid' => '15949',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-27.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-27_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '202020',
        'status' => '1',
        'timestamp' => '1325019437',
        'origname' => 'Layout-1_Page-27.jpg',
      ),
      '8' => array(
        'fid' => '15951',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-28.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-28_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104010',
        'status' => '1',
        'timestamp' => '1325019448',
        'origname' => 'Layout-1_Page-28.jpg',
      ),
      '9' => array(
        'fid' => '15953',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-29.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-29_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132790',
        'status' => '1',
        'timestamp' => '1325019460',
        'origname' => 'Layout-1_Page-29.jpg',
      ),
      '10' => array(
        'fid' => '15955',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-30.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-30_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78520',
        'status' => '1',
        'timestamp' => '1325019470',
        'origname' => 'Layout-1_Page-30.jpg',
      ),
      '11' => array(
        'fid' => '15957',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-31.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-31_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76504',
        'status' => '1',
        'timestamp' => '1325019482',
        'origname' => 'Layout-1_Page-31.jpg',
      ),
      '12' => array(
        'fid' => '15958',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-32.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-32_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '105698',
        'status' => '1',
        'timestamp' => '1325019491',
        'origname' => 'Layout-1_Page-32.jpg',
      ),
      '13' => array(
        'fid' => '15959',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-33.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-33_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80753',
        'status' => '1',
        'timestamp' => '1325019507',
        'origname' => 'Layout-1_Page-33.jpg',
      ),
      '14' => array(
        'fid' => '15961',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-34.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-34_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132580',
        'status' => '1',
        'timestamp' => '1325019523',
        'origname' => 'Layout-1_Page-34.jpg',
      ),
      '15' => array(
        'fid' => '15963',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-35.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-35_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161929',
        'status' => '1',
        'timestamp' => '1325019535',
        'origname' => 'Layout-1_Page-35.jpg',
      ),
      '16' => array(
        'fid' => '15965',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-36.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-36_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130561',
        'status' => '1',
        'timestamp' => '1325019545',
        'origname' => 'Layout-1_Page-36.jpg',
      ),
      '17' => array(
        'fid' => '15967',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-37.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-37_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75685',
        'status' => '1',
        'timestamp' => '1325019555',
        'origname' => 'Layout-1_Page-37.jpg',
      ),
      '18' => array(
        'fid' => '15969',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-38.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-38_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '165634',
        'status' => '1',
        'timestamp' => '1325019567',
        'origname' => 'Layout-1_Page-38.jpg',
      ),
      '19' => array(
        'fid' => '15971',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-39.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-39_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161742',
        'status' => '1',
        'timestamp' => '1325019580',
        'origname' => 'Layout-1_Page-39.jpg',
      ),
      '20' => array(
        'fid' => '15973',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-40.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-40_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '51739',
        'status' => '1',
        'timestamp' => '1325019589',
        'origname' => 'Layout-1_Page-40.jpg',
      ),
      '21' => array(
        'fid' => '15974',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-41.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-41_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128846',
        'status' => '1',
        'timestamp' => '1325019598',
        'origname' => 'Layout-1_Page-41.jpg',
      ),
      '22' => array(
        'fid' => '15975',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-42.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-42_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129723',
        'status' => '1',
        'timestamp' => '1325019612',
        'origname' => 'Layout-1_Page-42.jpg',
      ),
      '23' => array(
        'fid' => '15976',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-43.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-43_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '48297',
        'status' => '1',
        'timestamp' => '1325019622',
        'origname' => 'Layout-1_Page-43.jpg',
      ),
    ),
    'path' => 'stories/choice-2',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
