array(
  array(
    'nid' => '3921',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1325102648',
    'changed' => '1403838735',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3921',
    'revision_uid' => '1',
    'title' => 'Choice 3',
    'body' => '<p>
	Some of our choicest cuts from 2011. The year in review part three.</p>
',
    'teaser' => '<p>
	Some of our choicest cuts from 2011. The year in review part three.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838735',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	THE YEAR<br />
	IN REVIEW<br />
	PART THREE</p>
<p>
	COVER STORY<br />
	<a href="http://www.fantasticsmag.com/stories/gym-class">GYM CLASS</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/prince-and-show-pony">THE PRINCE AND THE SHOW PONY</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/roman-fisher">ROMAN FISHER</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/dance-stranger">DANCE WITH A STRANGER</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/down-garden-path">DOWN THE GARDEN PATH</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/c-te-dazur-65">COTE D&#39;AZUR 65</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/lucas-kerr">LUCAS KERR</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/stain">STAIN</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/vest">IN VEST</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/fall-wrap">FALL WRAP UP</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/fuse">FUSE</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/alanna">ALANNA</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/dress-code-0">DRESS CODE</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/fall">FALL IN</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/broski">BROSKI</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/sunshine-lolita">SUNSHINE LOLITA</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/girl-about-town">GIRL ABOUT TOWN</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/forward">FORWARD</a></p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15981',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-136.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-136.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '191696',
        'status' => '1',
        'timestamp' => '1325103149',
        'origname' => 'Layout-1_Page-136.jpg',
      ),
      '1' => array(
        'fid' => '15982',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-137.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-137.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '229305',
        'status' => '1',
        'timestamp' => '1325103157',
        'origname' => 'Layout-1_Page-137.jpg',
      ),
      '2' => array(
        'fid' => '15984',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-44.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-44.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '278489',
        'status' => '1',
        'timestamp' => '1325103314',
        'origname' => 'Layout-1_Page-44.jpg',
      ),
      '3' => array(
        'fid' => '15986',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-45.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-45.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '226642',
        'status' => '1',
        'timestamp' => '1325103327',
        'origname' => 'Layout-1_Page-45.jpg',
      ),
      '4' => array(
        'fid' => '15988',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-46.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-46.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '144450',
        'status' => '1',
        'timestamp' => '1325103336',
        'origname' => 'Layout-1_Page-46.jpg',
      ),
      '5' => array(
        'fid' => '15990',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-47.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-47.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '199357',
        'status' => '1',
        'timestamp' => '1325103347',
        'origname' => 'Layout-1_Page-47.jpg',
      ),
      '6' => array(
        'fid' => '15992',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-48.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-48.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118405',
        'status' => '1',
        'timestamp' => '1325103356',
        'origname' => 'Layout-1_Page-48.jpg',
      ),
      '7' => array(
        'fid' => '15994',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-49.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-49.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123835',
        'status' => '1',
        'timestamp' => '1325103365',
        'origname' => 'Layout-1_Page-49.jpg',
      ),
      '8' => array(
        'fid' => '15996',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-50.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-50.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74948',
        'status' => '1',
        'timestamp' => '1325103372',
        'origname' => 'Layout-1_Page-50.jpg',
      ),
      '9' => array(
        'fid' => '15998',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-51.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-51.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87079',
        'status' => '1',
        'timestamp' => '1325103380',
        'origname' => 'Layout-1_Page-51.jpg',
      ),
      '10' => array(
        'fid' => '16000',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-52.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-52.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83788',
        'status' => '1',
        'timestamp' => '1325103391',
        'origname' => 'Layout-1_Page-52.jpg',
      ),
      '11' => array(
        'fid' => '16002',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-53.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-53.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68099',
        'status' => '1',
        'timestamp' => '1325103399',
        'origname' => 'Layout-1_Page-53.jpg',
      ),
      '12' => array(
        'fid' => '16004',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-54.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-54.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109265',
        'status' => '1',
        'timestamp' => '1325103407',
        'origname' => 'Layout-1_Page-54.jpg',
      ),
      '13' => array(
        'fid' => '16006',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-55.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-55.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84330',
        'status' => '1',
        'timestamp' => '1325103416',
        'origname' => 'Layout-1_Page-55.jpg',
      ),
      '14' => array(
        'fid' => '16008',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-56.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-56.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68482',
        'status' => '1',
        'timestamp' => '1325103426',
        'origname' => 'Layout-1_Page-56.jpg',
      ),
      '15' => array(
        'fid' => '16010',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-57.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-57.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140751',
        'status' => '1',
        'timestamp' => '1325103435',
        'origname' => 'Layout-1_Page-57.jpg',
      ),
      '16' => array(
        'fid' => '16012',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-58.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-58.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '181555',
        'status' => '1',
        'timestamp' => '1325103448',
        'origname' => 'Layout-1_Page-58.jpg',
      ),
      '17' => array(
        'fid' => '16014',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-59.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-59.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160269',
        'status' => '1',
        'timestamp' => '1325103460',
        'origname' => 'Layout-1_Page-59.jpg',
      ),
      '18' => array(
        'fid' => '16016',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-60.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-60.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161993',
        'status' => '1',
        'timestamp' => '1325103470',
        'origname' => 'Layout-1_Page-60.jpg',
      ),
      '19' => array(
        'fid' => '16018',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-61.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-61.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98522',
        'status' => '1',
        'timestamp' => '1325103478',
        'origname' => 'Layout-1_Page-61.jpg',
      ),
      '20' => array(
        'fid' => '16020',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-62.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-62.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140537',
        'status' => '1',
        'timestamp' => '1325103488',
        'origname' => 'Layout-1_Page-62.jpg',
      ),
      '21' => array(
        'fid' => '16021',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-63.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-63.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '184099',
        'status' => '1',
        'timestamp' => '1325103497',
        'origname' => 'Layout-1_Page-63.jpg',
      ),
    ),
    'path' => 'stories/choice-3',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
        '4' => 'men',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
