array(
  array(
    'nid' => '3922',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1325189117',
    'changed' => '1331215092',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3922',
    'revision_uid' => '1',
    'title' => 'Choice 4',
    'body' => '<p>
	Some of our choicest cuts from 2011. The year in review part four.</p>
',
    'teaser' => '<p>
	Some of our choicest cuts from 2011. The year in review part four.</p>
',
    'log' => '',
    'revision_timestamp' => '1331215092',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	THE YEAR<br />
	IN REVIEW<br />
	PART FOUR</p>
<p>
	COVER STORY<br />
	<a href="http://www.fantasticsmag.com/stories/dance-stranger">DANCE WITH A STRANGER</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/coat-check">COAT CHECK</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/forward">FORWARD</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/beautiful-spirit">BEAUTIFUL SPIRIT</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/feet-first">FEET FIRST</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/flotsam-and-jetsam">FLOTSAM AND JETSAM</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/extravaganza">EXTRAVAGANZA</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/french-quarter-ts">FRENCH QUARTER Ts</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/get-wet">GET WET</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/hard-times">HARD TIMES</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/miss-60s">MISS 60s</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/slick-rick">SLICK RICK</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/jaunty-chapeau">JAUNTY CHAPEAU</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/corey-alfaro">COREY ALFARO</a></p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16022',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-138.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-138.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66057',
        'status' => '1',
        'timestamp' => '1325103553',
        'origname' => 'Layout-1_Page-138.jpg',
      ),
      '1' => array(
        'fid' => '16024',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-139.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-139.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94302',
        'status' => '1',
        'timestamp' => '1325103563',
        'origname' => 'Layout-1_Page-139.jpg',
      ),
      '2' => array(
        'fid' => '16025',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-64.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-64.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81536',
        'status' => '1',
        'timestamp' => '1325103573',
        'origname' => 'Layout-1_Page-64.jpg',
      ),
      '3' => array(
        'fid' => '16027',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-65.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-65.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '257864',
        'status' => '1',
        'timestamp' => '1325103588',
        'origname' => 'Layout-1_Page-65.jpg',
      ),
      '4' => array(
        'fid' => '16029',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-66.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-66.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68194',
        'status' => '1',
        'timestamp' => '1325103596',
        'origname' => 'Layout-1_Page-66.jpg',
      ),
      '5' => array(
        'fid' => '16031',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-67.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-67.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '57272',
        'status' => '1',
        'timestamp' => '1325103605',
        'origname' => 'Layout-1_Page-67.jpg',
      ),
      '6' => array(
        'fid' => '16033',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-68.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-68.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '191752',
        'status' => '1',
        'timestamp' => '1325103617',
        'origname' => 'Layout-1_Page-68.jpg',
      ),
      '7' => array(
        'fid' => '16035',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-69.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-69.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58926',
        'status' => '1',
        'timestamp' => '1325103624',
        'origname' => 'Layout-1_Page-69.jpg',
      ),
      '8' => array(
        'fid' => '16037',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-70.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-70.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '248654',
        'status' => '1',
        'timestamp' => '1325103639',
        'origname' => 'Layout-1_Page-70.jpg',
      ),
      '9' => array(
        'fid' => '16039',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-71.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-71.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '268641',
        'status' => '1',
        'timestamp' => '1325103654',
        'origname' => 'Layout-1_Page-71.jpg',
      ),
      '10' => array(
        'fid' => '16041',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-72.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-72.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '185596',
        'status' => '1',
        'timestamp' => '1325103666',
        'origname' => 'Layout-1_Page-72.jpg',
      ),
      '11' => array(
        'fid' => '16043',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-73.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-73.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108232',
        'status' => '1',
        'timestamp' => '1325103677',
        'origname' => 'Layout-1_Page-73.jpg',
      ),
      '12' => array(
        'fid' => '16045',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-74.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-74.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74906',
        'status' => '1',
        'timestamp' => '1325103687',
        'origname' => 'Layout-1_Page-74.jpg',
      ),
      '13' => array(
        'fid' => '16047',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-75.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-75.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '135655',
        'status' => '1',
        'timestamp' => '1325103697',
        'origname' => 'Layout-1_Page-75.jpg',
      ),
      '14' => array(
        'fid' => '16049',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-76.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-76.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '40473',
        'status' => '1',
        'timestamp' => '1325103705',
        'origname' => 'Layout-1_Page-76.jpg',
      ),
      '15' => array(
        'fid' => '16051',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-77.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-77.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113797',
        'status' => '1',
        'timestamp' => '1325103717',
        'origname' => 'Layout-1_Page-77.jpg',
      ),
      '16' => array(
        'fid' => '16053',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-78.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-78.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91069',
        'status' => '1',
        'timestamp' => '1325103728',
        'origname' => 'Layout-1_Page-78.jpg',
      ),
      '17' => array(
        'fid' => '16055',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-79.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-79.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '33855',
        'status' => '1',
        'timestamp' => '1325103737',
        'origname' => 'Layout-1_Page-79.jpg',
      ),
      '18' => array(
        'fid' => '16057',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-80.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-80.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156298',
        'status' => '1',
        'timestamp' => '1325103750',
        'origname' => 'Layout-1_Page-80.jpg',
      ),
      '19' => array(
        'fid' => '16058',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-81.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-81.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112468',
        'status' => '1',
        'timestamp' => '1325103759',
        'origname' => 'Layout-1_Page-81.jpg',
      ),
    ),
    'path' => 'stories/choice-4',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
