array(
  array(
    'nid' => '3923',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1325275596',
    'changed' => '1331214884',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3923',
    'revision_uid' => '1',
    'title' => 'Choice 5',
    'body' => '<p>
	Some of our choicest cuts from 2011. The year in review part five.</p>
',
    'teaser' => '<p>
	Some of our choicest cuts from 2011. The year in review part five.</p>
',
    'log' => '',
    'revision_timestamp' => '1331214884',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	THE YEAR<br />
	IN REVIEW<br />
	PART FIVE</p>
<p>
	COVER STORY<a href="http://www.fantasticsmag.com/stories/aesthetes-and-decadents"><br />
	AESTHETES<br />
	&amp; DECADENTS</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/ten-raw">TEN RAW</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/broski">BROSKI</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/over-dreaming">OVER DREAMING</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/sharp">SHARP</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/bad">BAD</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/nocturne">NOCTURNE</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/chill-factor">CHILL FACTOR</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/i-want-be-your-dog">I WANT TO BE YOUR DOG</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/just-girl">JUST A GIRL</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/james-elliott">JAMES ELLIOT</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/kris-kranz">KRIS KRANZ</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/rib-hillis">RIB HILLIS</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/moody">MOODY</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/madison-leyes">MADISON LEYES</a></p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16059',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-140.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-140.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '48292',
        'status' => '1',
        'timestamp' => '1325103843',
        'origname' => 'Layout-1_Page-140.jpg',
      ),
      '1' => array(
        'fid' => '16061',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-141.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-141.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83028',
        'status' => '1',
        'timestamp' => '1325103850',
        'origname' => 'Layout-1_Page-141.jpg',
      ),
      '2' => array(
        'fid' => '16063',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-82.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-82.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127641',
        'status' => '1',
        'timestamp' => '1325103861',
        'origname' => 'Layout-1_Page-82.jpg',
      ),
      '3' => array(
        'fid' => '16065',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-83.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-83.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118413',
        'status' => '1',
        'timestamp' => '1325103869',
        'origname' => 'Layout-1_Page-83.jpg',
      ),
      '4' => array(
        'fid' => '16067',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-84.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-84.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66240',
        'status' => '1',
        'timestamp' => '1325103876',
        'origname' => 'Layout-1_Page-84.jpg',
      ),
      '5' => array(
        'fid' => '16069',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-85.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-85.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79342',
        'status' => '1',
        'timestamp' => '1325103882',
        'origname' => 'Layout-1_Page-85.jpg',
      ),
      '6' => array(
        'fid' => '16071',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-86.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-86.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63189',
        'status' => '1',
        'timestamp' => '1325103890',
        'origname' => 'Layout-1_Page-86.jpg',
      ),
      '7' => array(
        'fid' => '16073',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-87.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-87.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140738',
        'status' => '1',
        'timestamp' => '1325103900',
        'origname' => 'Layout-1_Page-87.jpg',
      ),
      '8' => array(
        'fid' => '16075',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-88.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-88.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85217',
        'status' => '1',
        'timestamp' => '1325103908',
        'origname' => 'Layout-1_Page-88.jpg',
      ),
      '9' => array(
        'fid' => '16077',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-89.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-89.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124894',
        'status' => '1',
        'timestamp' => '1325103917',
        'origname' => 'Layout-1_Page-89.jpg',
      ),
      '10' => array(
        'fid' => '16079',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-90.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-90.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138659',
        'status' => '1',
        'timestamp' => '1325103926',
        'origname' => 'Layout-1_Page-90.jpg',
      ),
      '11' => array(
        'fid' => '16081',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-91.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-91.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '135005',
        'status' => '1',
        'timestamp' => '1325103937',
        'origname' => 'Layout-1_Page-91.jpg',
      ),
      '12' => array(
        'fid' => '16083',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-92.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-92.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29657',
        'status' => '1',
        'timestamp' => '1325103943',
        'origname' => 'Layout-1_Page-92.jpg',
      ),
      '13' => array(
        'fid' => '16085',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-93.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-93.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '115163',
        'status' => '1',
        'timestamp' => '1325103953',
        'origname' => 'Layout-1_Page-93.jpg',
      ),
      '14' => array(
        'fid' => '16087',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-94.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-94.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155376',
        'status' => '1',
        'timestamp' => '1325103972',
        'origname' => 'Layout-1_Page-94.jpg',
      ),
      '15' => array(
        'fid' => '16089',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-95.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-95.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '125597',
        'status' => '1',
        'timestamp' => '1325103983',
        'origname' => 'Layout-1_Page-95.jpg',
      ),
      '16' => array(
        'fid' => '16091',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-96.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-96.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94337',
        'status' => '1',
        'timestamp' => '1325103993',
        'origname' => 'Layout-1_Page-96.jpg',
      ),
      '17' => array(
        'fid' => '16093',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-97.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-97.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91761',
        'status' => '1',
        'timestamp' => '1325104003',
        'origname' => 'Layout-1_Page-97.jpg',
      ),
      '18' => array(
        'fid' => '16095',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-98.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-98.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79928',
        'status' => '1',
        'timestamp' => '1325104012',
        'origname' => 'Layout-1_Page-98.jpg',
      ),
      '19' => array(
        'fid' => '16097',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-99.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-99.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90018',
        'status' => '1',
        'timestamp' => '1325104024',
        'origname' => 'Layout-1_Page-99.jpg',
      ),
      '20' => array(
        'fid' => '16099',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-100.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-100.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '121647',
        'status' => '1',
        'timestamp' => '1325104038',
        'origname' => 'Layout-1_Page-100.jpg',
      ),
      '21' => array(
        'fid' => '16101',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-101.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-101.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '265726',
        'status' => '1',
        'timestamp' => '1325104053',
        'origname' => 'Layout-1_Page-101.jpg',
      ),
      '22' => array(
        'fid' => '16103',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-102.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-102.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84992',
        'status' => '1',
        'timestamp' => '1325104064',
        'origname' => 'Layout-1_Page-102.jpg',
      ),
      '23' => array(
        'fid' => '16105',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-103.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-103.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94762',
        'status' => '1',
        'timestamp' => '1325104075',
        'origname' => 'Layout-1_Page-103.jpg',
      ),
    ),
    'path' => 'stories/choice-5',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
