array(
  array(
    'nid' => '3136',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1262444641',
    'changed' => '1403919753',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3136',
    'revision_uid' => '1',
    'title' => 'The Bride Wore Black and...',
    'body' => '<p>Never a bridesmaid always a bride.</p>
<p>Exclusive photography by <a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a>.</p>
<p>Model ~ Marjorie @ <a href="http://www.lookmodelagency.com/" target="_blank">LOOK</a>, Niya &amp; Svetlana @ <a href="http://www.citymodel.com/" target="_blank">CITY SF</a>.</p>
<p><a href="http://www.lookmodelagency.com/" target="_blank"><br /></a><a href="http://www.citymodel.com/" target="_blank"></a></p>',
    'teaser' => '<p>Never a bridesmaid always a bride.</p>
<p>Exclusive photography by <a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a>.</p>
<p>Model ~ Marjorie @ <a href="http://www.lookmodelagency.com/" target="_blank">LOOK</a>, Niya &amp; Svetlana @ <a href="http://www.citymodel.com/" target="_blank">CITY SF</a>.</p>
<p><a href="http://www.lookmodelagency.com/" target="_blank"><br /></a><a href="http://www.citymodel.com/" target="_blank"></a></p>',
    'log' => '',
    'revision_timestamp' => '1403919753',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>PHOTOGRAPHY<br /><a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a></p>
<p>MODELS<br />MARJORIE @ <a href="http://www.lookmodelagency.com/" target="_blank">LOOK</a><br />NIYA &amp; SVETLANA @ <a href="http://www.citymodel.com/" target="_blank">CITY</a></p>
<p>FEATURED FASHION</p>
<ul>
<li><a href="http://www.elle-meme.com/" target="_blank">elle-meme</a></li>
</ul>
<ul>
<li><a href="http://www.atelierdesmodistes.com/" target="_blank">ateliers des modistes</a></li>
</ul>
<ul>
<li><a href="http://www.amykuschel.com/" target="_blank">amy kuschel</a></li>
</ul>
<ul>
<br /><br /> 
</ul>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '7147',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bride_JAN10.jpg',
        'filepath' => 'files/bride_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '150001',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bride_JAN10.jpg',
      ),
      '1' => array(
        'fid' => '7287',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/Layout-1_Page-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '182184',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '7149',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bride3_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/bride3_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '331272',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bride3_JAN10.jpg',
      ),
      '3' => array(
        'fid' => '7150',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bride4_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/bride4_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '21663',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bride4_JAN10.jpg',
      ),
      '4' => array(
        'fid' => '7151',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bride5_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/bride5_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17387',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bride5_JAN10.jpg',
      ),
      '5' => array(
        'fid' => '7152',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bride6_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/bride6_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '249577',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bride6_JAN10.jpg',
      ),
      '6' => array(
        'fid' => '7342',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '174596',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '7154',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bride8_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/bride8_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14818',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bride8_JAN10.jpg',
      ),
      '8' => array(
        'fid' => '7288',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/Layout-1_Page-10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18775',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '7156',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bride10_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/bride10_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '310262',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bride10_JAN10.jpg',
      ),
    ),
    'path' => 'stories/bride-wore-black-and',
    'tags' => array(
      '5' => array(
        '2519' => array(
          'tid' => '2519',
          'vid' => '5',
          'name' => 'BILLY WINTERS',
          'description' => 'http://www.billywinters.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'BILLY WINTERS',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
