array(
  array(
    'nid' => '3156',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1263590125',
    'changed' => '1337805472',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3156',
    'revision_uid' => '1',
    'title' => 'A Sense of Ennui',
    'body' => '<p>
	Feeling lazy.</p>
<p>
	Exclusive photography by <a href="http://samuelzakuto.blogspot.com/" target="_blank">Samuel Zakuto</a>.</p>
<p>
	Models ~ Ryan Bertroche &amp; Ram Boneh @ REQUEST</p>
<p>
	and Nick Riback @ MAJOR.</p>
<p>
	&nbsp;</p>
',
    'teaser' => '<p>
	Feeling lazy.</p>
<p>
	Exclusive photography by <a href="http://samuelzakuto.blogspot.com/" target="_blank">Samuel Zakuto</a>.</p>
<p>
	Models ~ Ryan Bertroche &amp; Ram Boneh @ REQUEST</p>
<p>
	and Nick Riback @ MAJOR.</p>
<p>
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1337805472',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://samuelzakuto.blogspot.com/" target="_blank">Samuel Zakuto</a>.<br />
	<br />
	MODELS<br />
	RYAN BERTROUCHE<br />
	&amp; RAM BONEH<br />
	@ REQUEST<br />
	NICK RIBACK<br />
	@ MAJOR<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="/us.levi.com" target="_blank">LEVIS</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '7362',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '42561',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui_JAN10.jpg',
      ),
      '1' => array(
        'fid' => '7363',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui2_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui2_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113923',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui2_JAN10.jpg',
      ),
      '2' => array(
        'fid' => '7364',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui3_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui3_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124374',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui3_JAN10.jpg',
      ),
      '3' => array(
        'fid' => '7365',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui4_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui4_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102916',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui4_JAN10.jpg',
      ),
      '4' => array(
        'fid' => '7366',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui5_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui5_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117416',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui5_JAN10.jpg',
      ),
      '5' => array(
        'fid' => '7367',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui6_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui6_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127283',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui6_JAN10.jpg',
      ),
      '6' => array(
        'fid' => '7368',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui7_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui7_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112749',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui7_JAN10.jpg',
      ),
      '7' => array(
        'fid' => '7369',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui8_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui8_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102512',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui8_JAN10.jpg',
      ),
      '8' => array(
        'fid' => '7370',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui9_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui9_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106220',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui9_JAN10.jpg',
      ),
      '9' => array(
        'fid' => '7371',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui10_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui10_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88568',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui10_JAN10.jpg',
      ),
      '10' => array(
        'fid' => '7372',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui11_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui11_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '148011',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui11_JAN10.jpg',
      ),
      '11' => array(
        'fid' => '7373',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui12_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui12_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12692',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui12_JAN10.jpg',
      ),
      '12' => array(
        'fid' => '7374',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui13_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui13_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72936',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui13_JAN10.jpg',
      ),
      '13' => array(
        'fid' => '7375',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ennui14_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ennui14_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100437',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ennui14_JAN10.jpg',
      ),
    ),
    'path' => 'stories/sense-ennui',
    'tags' => array(
      '5' => array(
        '2544' => array(
          'tid' => '2544',
          'vid' => '5',
          'name' => 'Samuel Zakuto.',
          'description' => 'http://samuelzakuto.blogspot.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Samuel Zakuto.',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
