array(
  array(
    'nid' => '3165',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1264623707',
    'changed' => '1309800413',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3165',
    'revision_uid' => '1',
    'title' => 'Ximena Valero',
    'body' => '<p>
	<a href="http://www.ximenavalero.com/" target="_blank">Ximena Valero&#39;s</a> OMG dress is more than meets the eye.</p>
<p>
	Exclusive photography by <a href="http://www.RodneyRayPhotography.com" target="_blank">Rodney Ray</a>.</p>
<p>
	&nbsp;</p>
',
    'teaser' => '<p>
	<a href="http://www.ximenavalero.com/" target="_blank">Ximena Valero&#39;s</a> OMG dress is more than meets the eye.</p>
<p>
	Exclusive photography by <a href="http://www.RodneyRayPhotography.com" target="_blank">Rodney Ray</a>.</p>
<p>
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1309800413',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.ximenavalero.com/" target="_blank">Ximena Valero</a></p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.RodneyRayPhotography.com" target="_blank">Rodney Ray</a></p>
<p>
	PROFILE<br />
	HEATHER MACDONALD</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10846',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96394',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '10847',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/Layout-1_Page-3_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81351',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '7454',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ximena3_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ximena3_JAN10_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136710',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ximena3_JAN10.jpg',
      ),
      '3' => array(
        'fid' => '7455',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ximena4_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/ximena4_JAN10_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '115170',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'ximena4_JAN10.jpg',
      ),
    ),
    'path' => 'stories/ximena-valero-0',
    'tags' => array(
      '5' => array(
        '2415' => array(
          'tid' => '2415',
          'vid' => '5',
          'name' => 'McKenzie James',
          'description' => 'http://www.modelmayhem.com/29023',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'McKenzie James',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
