array(
  array(
    'nid' => '3166',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1264818967',
    'changed' => '1309800413',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3166',
    'revision_uid' => '1',
    'title' => 'Death Valley Superstar',
    'body' => '<p>
	In DEATH VALLEY SUPERSTAR director <a href="http://www.imdb.com/name/nm0003095/" target="_blank">MICHAEL YAROSHEVSKY</a> examines the strange life of actor Mark Frechette.</p>
<p>
	Interview by James Nixon.</p>
<p>
	&nbsp;</p>
',
    'teaser' => '<p>
	In DEATH VALLEY SUPERSTAR director <a href="http://www.imdb.com/name/nm0003095/" target="_blank">MICHAEL YAROSHEVSKY</a> examines the strange life of actor Mark Frechette.</p>
<p>
	Interview by James Nixon.</p>
<p>
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1309800413',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.imdb.com/name/nm0003095/" target="_blank">MICHAEL YAROSHEVSKY</a></p>
<p>
	INTERVIEW BY<br />
	JAMES NIXON</p>
<p>
	<a href="http://www.amazon.com/Zabriskie-Point-Mark-Frechette/dp/B001TK80CA" target="_blank">ZABRISKIE POINT<br />
	@ AMAZON</a></p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10850',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/Layout-1_Page-2_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137928',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '7457',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS2_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS2_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '276312',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS2_JAN10.jpg',
      ),
      '2' => array(
        'fid' => '7458',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS3_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS3_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138008',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS3_JAN10.jpg',
      ),
      '3' => array(
        'fid' => '7459',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS4_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS4_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128914',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS4_JAN10.jpg',
      ),
      '4' => array(
        'fid' => '7471',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS5_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS5_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '263661',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS5_JAN10.jpg',
      ),
      '5' => array(
        'fid' => '7461',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS6_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS6_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '70919',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS6_JAN10.jpg',
      ),
      '6' => array(
        'fid' => '7462',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS7_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS7_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '159915',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS7_JAN10.jpg',
      ),
      '7' => array(
        'fid' => '7463',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS8_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS8_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89382',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS8_JAN10.jpg',
      ),
      '8' => array(
        'fid' => '7464',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS9_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS9_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '146037',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS9_JAN10.jpg',
      ),
      '9' => array(
        'fid' => '7465',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS10_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS10_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '169576',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS10_JAN10.jpg',
      ),
      '10' => array(
        'fid' => '7466',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS11_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS11_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104597',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS11_JAN10.jpg',
      ),
      '11' => array(
        'fid' => '7472',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS12_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS12_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '142325',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS12_JAN10.jpg',
      ),
      '12' => array(
        'fid' => '7468',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS13_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS13_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113218',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS13_JAN10.jpg',
      ),
      '13' => array(
        'fid' => '7469',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DVS14_JAN10.jpg',
        'filepath' => 'files/fmag_story/2010/Jan/DVS14_JAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108082',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'DVS14_JAN10.jpg',
      ),
    ),
    'path' => 'stories/death-valley-superstar',
    'tags' => array(
      '5' => array(
        '2415' => array(
          'tid' => '2415',
          'vid' => '5',
          'name' => 'McKenzie James',
          'description' => 'http://www.modelmayhem.com/29023',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'McKenzie James',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
