array(
  array(
    'nid' => '3168',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1264708832',
    'changed' => '1403919572',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3168',
    'revision_uid' => '1',
    'title' => 'Basic Instinct',
    'body' => '<p>
	It&#39;s a bad economy so keep it real.</p>
<p>
	Exclusive photography by James N.</p>
<p>
	Model ~ Jordan K.</p>
',
    'teaser' => '<p>
	It&#39;s a bad economy so keep it real.</p>
<p>
	Exclusive photography by James N.</p>
<p>
	Model ~ Jordan K.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919572',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	JAMES N</p>
<p>
	&nbsp;</p>
<p>
	<a href="http://www.myspace.com/theloommusic" target="_blank">THE LOOM</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	JORDAN K<br />
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.hm.com" target="_blank">H&amp;M</a></li>
	<li>
		<a href="http://www.uniqlo.com/us/" target="_blank">UNIQLO</a></li>
	<li>
		&nbsp;</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '7473',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141437',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic_FEB10.jpg',
      ),
      '1' => array(
        'fid' => '7474',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic2_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic2_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94006',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic2_FEB10.jpg',
      ),
      '2' => array(
        'fid' => '7475',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic3_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic3_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '111886',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic3_FEB10.jpg',
      ),
      '3' => array(
        'fid' => '7476',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic4_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic4_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126475',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic4_FEB10.jpg',
      ),
      '4' => array(
        'fid' => '7477',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic5_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic5_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic5_FEB10.jpg',
      ),
      '5' => array(
        'fid' => '7478',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic6_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic6_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107923',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic6_FEB10.jpg',
      ),
      '6' => array(
        'fid' => '7479',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic7_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic7_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13433',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic7_FEB10.jpg',
      ),
      '7' => array(
        'fid' => '7480',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic8_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic8_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '267311',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic8_FEB10.jpg',
      ),
      '8' => array(
        'fid' => '7481',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic9_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic9_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic9_FEB10.jpg',
      ),
      '9' => array(
        'fid' => '7482',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic10_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic10_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '200757',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic10_FEB10.jpg',
      ),
      '10' => array(
        'fid' => '7483',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic11_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic11_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122451',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic11_FEB10.jpg',
      ),
      '11' => array(
        'fid' => '7484',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic12_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic12_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '55644',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic12_FEB10.jpg',
      ),
      '12' => array(
        'fid' => '7485',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic13_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic13_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '40875',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic13_FEB10.jpg',
      ),
      '13' => array(
        'fid' => '7486',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic14_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic14_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '212927',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic14_FEB10.jpg',
      ),
      '14' => array(
        'fid' => '7487',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic15_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic15_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119000',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic15_FEB10.jpg',
      ),
      '15' => array(
        'fid' => '7488',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic16_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic16_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138797',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic16_FEB10.jpg',
      ),
      '16' => array(
        'fid' => '7489',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic17_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic17_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '35774',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic17_FEB10.jpg',
      ),
      '17' => array(
        'fid' => '7490',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic18_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic18_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '157931',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic18_FEB10.jpg',
      ),
      '18' => array(
        'fid' => '7491',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic19_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic19_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153979',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic19_FEB10.jpg',
      ),
      '19' => array(
        'fid' => '7492',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'basic20_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/basic20_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13421',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'basic20_FEB10.jpg',
      ),
    ),
    'path' => 'stories/basic-instinct',
    'tags' => array(
      '5' => array(
        '2412' => array(
          'tid' => '2412',
          'vid' => '5',
          'name' => 'JAMES N',
          'description' => 'jimmynixon.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JAMES N',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
