array(
  array(
    'nid' => '3209',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1267211447',
    'changed' => '1267212849',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3209',
    'revision_uid' => '1',
    'title' => 'Just What I Do',
    'body' => '<p>Sass Jordan does it her way.</p>
<p>Interview by Heather MacDonald.</p>
<p>Photography by Derek Sharp.</p>',
    'teaser' => '<p>Sass Jordan does it her way.</p>
<p>Interview by Heather MacDonald.</p>
<p>Photography by Derek Sharp.</p>',
    'log' => '',
    'revision_timestamp' => '1267212849',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p><a target="_blank" href="http://www.sassjordan.com/">SASS JORDAN</a></p>
<p> </p>
<p><a target="_blank" href="http://www.amazon.com/Dusk-Til-Dawn-Sass-Jordan/dp/B002LS5ZQS">FROM DUSK TIL DAWN</a></p>
<p> </p>
<p>INTERVIEW BY<br />HEATHER MACDONALD</p>
<p> </p>
<p>PHOTOGRAPHY<br />DEREK SHARP</p>
<p> </p>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '7908',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sass_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/sass_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '192142',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sass_FEB10.jpg',
      ),
      '1' => array(
        'fid' => '7909',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sass2_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/sass2_FEB10_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '45060',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sass2_FEB10.jpg',
      ),
      '2' => array(
        'fid' => '7910',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sass3_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/sass3_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '194211',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sass3_FEB10.jpg',
      ),
      '3' => array(
        'fid' => '7903',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sass4_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/sass4_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156328',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sass4_FEB10.jpg',
      ),
      '4' => array(
        'fid' => '7904',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sass5_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/sass5_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132038',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sass5_FEB10.jpg',
      ),
      '5' => array(
        'fid' => '7905',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sass6_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/sass6_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '183947',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sass6_FEB10.jpg',
      ),
      '6' => array(
        'fid' => '7906',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sass7_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/sass7_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '240948',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sass7_FEB10.jpg',
      ),
      '7' => array(
        'fid' => '7911',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sass8_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/sass8_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '190394',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sass8_FEB10.jpg',
      ),
    ),
    'path' => 'stories/just-what-i-do',
    'tags' => array(
      '5' => array(
        '2551' => array(
          'tid' => '2551',
          'vid' => '5',
          'name' => 'Fabrice Lachant',
          'description' => 'http://www.photobyfabrice.com/intro',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Fabrice Lachant',
      ),
      '2' => array(
        '2' => '2',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
