array(
  array(
    'nid' => '3211',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1267305063',
    'changed' => '1403919752',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3211',
    'revision_uid' => '1',
    'title' => 'Fever',
    'body' => '<p>I\'m feeling flushed.</p>
<p><br />Exclusive photography by Chantal Gallant.<a href="http://www.duboisphotography.com/" target="_blank"><br /></a></p>
<p><br />Model ~ Sarah Jordan @ Specs.</p>',
    'teaser' => '<p>I\'m feeling flushed.</p>
<p><br />Exclusive photography by Chantal Gallant.<a href="http://www.duboisphotography.com/" target="_blank"><br /></a></p>
<p><br />Model ~ Sarah Jordan @ Specs.</p>',
    'log' => '',
    'revision_timestamp' => '1403919752',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>PHOTOGRAPHY<br />CHANTAL GALLANT</p>
<p> </p>
<p>MODEL<br />SARAH JORDAN<br />@ SPECS</p>
<p> </p>
<p>FEATURED FASHION</p>
<ul>
<li>LA SENZA</li>
<li>ELLE MACPHERSON</li>
</ul>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '7913',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fever_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/fever_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139055',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fever_FEB10.jpg',
      ),
      '1' => array(
        'fid' => '7923',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fever2_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/fever2_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137951',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fever2_FEB10.jpg',
      ),
      '2' => array(
        'fid' => '8354',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/Layout-1_Page-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123580',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '7916',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fever4_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/fever4_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '26691',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fever4_FEB10.jpg',
      ),
      '4' => array(
        'fid' => '7917',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fever5_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/fever5_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '21595',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fever5_FEB10.jpg',
      ),
      '5' => array(
        'fid' => '7918',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fever6_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/fever6_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '148578',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fever6_FEB10.jpg',
      ),
      '6' => array(
        'fid' => '7921',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fever7_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/fever7_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136572',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fever7_FEB10.jpg',
      ),
      '7' => array(
        'fid' => '7920',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fever8_FEB10.jpg',
        'filepath' => 'files/fmag_story/2010/Feb/fever8_FEB10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19890',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fever8_FEB10.jpg',
      ),
    ),
    'path' => 'stories/fever',
    'tags' => array(
      '5' => array(
        '2552' => array(
          'tid' => '2552',
          'vid' => '5',
          'name' => 'CHANTAL GALLANT',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'CHANTAL GALLANT',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
