array(
  array(
    'nid' => '3220',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1268407329',
    'changed' => '1337805342',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3220',
    'revision_uid' => '1',
    'title' => 'Shirt Story',
    'body' => '<p>
	Reaasess your button-down world mister.</p>
<p>
	Exclusive photography by <a href="http://www.christophersims.com/" target="_blank">Christopher Sims</a>.</p>
<p>
	Models ~&nbsp; Alex @ Premier &amp; Rob @ M&amp;P London.</p>
',
    'teaser' => '<p>
	Reaasess your button-down world mister.</p>
<p>
	Exclusive photography by <a href="http://www.christophersims.com/" target="_blank">Christopher Sims</a>.</p>
<p>
	Models ~&nbsp; Alex @ Premier &amp; Rob @ M&amp;P London.</p>
',
    'log' => '',
    'revision_timestamp' => '1337805342',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.christophersims.com/" target="_blank">Christopher Sims</a></p>
<p>
	<br />
	FASHION EDITOR<br />
	SARA DARLING</p>
<p>
	<br />
	MODEL<br />
	ALEX @ PREMIER<br />
	ROB @ M&amp;P LONDON<br />
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.emmawillis.com/" target="_blank">Emma Willis</a></li>
	<li>
		<a href="http://denisonboston.com/" target="_blank">Deniston Boston</a></li>
	<li>
		<a href="http://www.rokit.co.uk/" target="_blank">Rokit</a></li>
	<li>
		<a href="http://www.henrilloyd.com/" target="_blank">Henri LLoyd</a></li>
	<li>
		<a href="http://www.omarkashoura.com/" target="_blank"><span>Omar Kashoura</span></a></li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '8059',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92974',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '8060',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/Layout-1_Page-3_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94385',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '8011',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt3_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt3_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100635',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt3_MAR10.jpg',
      ),
      '3' => array(
        'fid' => '8012',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt4_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt4_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98307',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt4_MAR10.jpg',
      ),
      '4' => array(
        'fid' => '8013',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt5_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt5_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '62649',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt5_MAR10.jpg',
      ),
      '5' => array(
        'fid' => '8014',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt6_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt6_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '69039',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt6_MAR10.jpg',
      ),
      '6' => array(
        'fid' => '8015',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt7_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt7_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22415',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt7_MAR10.jpg',
      ),
      '7' => array(
        'fid' => '8016',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt8_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt8_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123620',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt8_MAR10.jpg',
      ),
      '8' => array(
        'fid' => '8017',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt9_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt9_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '133511',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt9_MAR10.jpg',
      ),
      '9' => array(
        'fid' => '8018',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt10_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt10_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16930',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt10_MAR10.jpg',
      ),
      '10' => array(
        'fid' => '8019',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt11_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt11_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20990',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt11_MAR10.jpg',
      ),
      '11' => array(
        'fid' => '8020',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt12_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt12_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88173',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt12_MAR10.jpg',
      ),
      '12' => array(
        'fid' => '8021',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt13_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt13_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '115468',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt13_MAR10.jpg',
      ),
      '13' => array(
        'fid' => '8022',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shirt14_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/shirt14_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114086',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shirt14_MAR10.jpg',
      ),
    ),
    'path' => 'stories/shirt-story',
    'tags' => array(
      '5' => array(
        '2523' => array(
          'tid' => '2523',
          'vid' => '5',
          'name' => 'Christopher Sims',
          'description' => 'http://christophersims.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Christopher Sims',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
