array(
  array(
    'nid' => '3229',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1268674892',
    'changed' => '1403919751',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3229',
    'revision_uid' => '1',
    'title' => 'House Beautiful',
    'body' => '<p>Wear pretty things and sit on them too.</p>
<p>Exclusive photography by <a target="_blank" href="http://josephsaraceno.com/">JOSEPH SARACENO</a>.</p>
<p>Models ~  Frances @ Elite.</p>',
    'teaser' => '<p>Wear pretty things and sit on them too.</p>
<p>Exclusive photography by <a target="_blank" href="http://josephsaraceno.com/">JOSEPH SARACENO</a>.</p>
<p>Models ~  Frances @ Elite.</p>',
    'log' => '',
    'revision_timestamp' => '1403919751',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>PHOTOGRAPHY<br /><a target="_blank" href="http://josephsaraceno.com/">JOSEPH SARACENO</a></p>
<p><br /><br />MODEL<br />FRANCES @ ELITE<br /><br /><br /><br />FEATURED FASHION</p>
<ul>
<li> <a target="_blank" href="http://evanbiddell.ca/">EVAN BIDDELL</a></li>
<li><a target="_blank" href="http://www.trafficpeople.net/">Traffic People</a></li>
</ul>
<p> </p>
<p>FEATURED FURNISHINGS</p>
<ul>
<li><a target="_blank" href="http://www.roche-bobois.com/">Roche bobois</a></li>
</ul>
<ul>
<br /><br /> 
</ul>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '8182',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house_MAR10_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '907718',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house_MAR10.jpg',
      ),
      '1' => array(
        'fid' => '8117',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house2_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house2_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '430834',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house2_MAR10.jpg',
      ),
      '2' => array(
        'fid' => '8118',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house3_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house3_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127460',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house3_MAR10.jpg',
      ),
      '3' => array(
        'fid' => '8119',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house4_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house4_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29184',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house4_MAR10.jpg',
      ),
      '4' => array(
        'fid' => '8120',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house5_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house5_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '195097',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house5_MAR10.jpg',
      ),
      '5' => array(
        'fid' => '8121',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house6_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house6_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60651',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house6_MAR10.jpg',
      ),
      '6' => array(
        'fid' => '8183',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house7_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house7_MAR10_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104424',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house7_MAR10.jpg',
      ),
      '7' => array(
        'fid' => '8123',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house8_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house8_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160666',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house8_MAR10.jpg',
      ),
      '8' => array(
        'fid' => '8128',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house9_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house9_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106497',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house9_MAR10.jpg',
      ),
      '9' => array(
        'fid' => '8125',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house10_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house10_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123675',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house10_MAR10.jpg',
      ),
      '10' => array(
        'fid' => '8126',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house11_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house11_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '143905',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house11_MAR10.jpg',
      ),
      '11' => array(
        'fid' => '8127',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'house12_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/house12_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18189',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'house12_MAR10.jpg',
      ),
    ),
    'path' => 'stories/house-beautiful',
    'tags' => array(
      '5' => array(
        '2468' => array(
          'tid' => '2468',
          'vid' => '5',
          'name' => 'joseph saraceno',
          'description' => 'http://josephsaraceno.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'joseph saraceno',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
