array(
  array(
    'nid' => '3235',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1268344805',
    'changed' => '1403919571',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3235',
    'revision_uid' => '1',
    'title' => 'Sam Grundy',
    'body' => '<p>Sam he is.</p>
<p>Exclusive photography by Joel Esposito.</p>',
    'teaser' => '<p>Sam he is.</p>
<p>Exclusive photography by Joel Esposito.</p>',
    'log' => '',
    'revision_timestamp' => '1403919571',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>SAM GRUNDY</p>
<p><br />@ <a href="http://www.elmerolsenmodels.com/">ELMER OLSEN</a></p>
<p> </p>
<p><a target="_blank" href="http://www.myspace.com/yourgreeneggsandsam">GREEN EGGS AND SAM</a></p>
<p> </p>
<p>PHOTOGRAPHY<br />JOEL ESPOSITO</p>
<p> </p>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10842',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/Layout-1_Page-2_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77570',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '10843',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/Layout-1_Page-3_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75418',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '8164',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sam3_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/sam3_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63319',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sam3_MAR10.jpg',
      ),
      '3' => array(
        'fid' => '8165',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sam4_MAR10.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/sam4_MAR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84093',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sam4_MAR10.jpg',
      ),
    ),
    'path' => 'stories/sam-grundy',
    'tags' => array(
      '5' => array(
        '2492' => array(
          'tid' => '2492',
          'vid' => '5',
          'name' => 'JASON OBROTKA',
          'description' => 'http://www.jasonobrotka.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'JASON OBROTKA',
        '4' => 'men',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
