array(
  array(
    'nid' => '3242',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1269980730',
    'changed' => '1403919751',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3242',
    'revision_uid' => '1',
    'title' => 'Sarah Barnes',
    'body' => '<p>Barnes storm.</p>
<p>Exclusive photography by Joel Esposito.</p>',
    'teaser' => '<p>Barnes storm.</p>
<p>Exclusive photography by Joel Esposito.</p>',
    'log' => '',
    'revision_timestamp' => '1403919751',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>SARAH BARNES</p>
<p><br />@ <a href="http://www.elmerolsenmodels.com/">ELMER OLSEN</a></p>
<p> </p>
<p>PHOTOGRAPHY<br />JOEL ESPOSITO</p>
<p> </p>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10844',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/Layout-1_Page-2_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79101',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '10845',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/Layout-1_Page-3_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88158',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '8246',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/Layout-1_Page-4_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137137',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '8247',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2010/Mar/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '120363',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
    ),
    'path' => 'stories/sarah-barnes',
    'tags' => array(
      '5' => array(
        '2556' => array(
          'tid' => '2556',
          'vid' => '5',
          'name' => 'Richard  Dubois',
          'description' => 'http://www.duboisphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'Richard  Dubois',
        '4' => 'women',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
