array(
  array(
    'nid' => '3262',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1271800338',
    'changed' => '1403919169',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3262',
    'revision_uid' => '1',
    'title' => 'Justin Pinos',
    'body' => '<p>Justin time.</p>
<p>Exclusive photography by Joel Esposito.</p>',
    'teaser' => '<p>Justin time.</p>
<p>Exclusive photography by Joel Esposito.</p>',
    'log' => '',
    'revision_timestamp' => '1403919169',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>JUSTIN PINOS</p>
<p><br />@ <a href="http://www.elmerolsenmodels.com/">ELMER OLSEN</a></p>
<p> </p>
<p>PHOTOGRAPHY<br />JOEL ESPOSITO</p>
<p> </p>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10840',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/Layout-1_Page-2_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77442',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '10841',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/Layout-1_Page-3_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108110',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '8404',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'EnthusJUSTIN3_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/EnthusJUSTIN3_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96429',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'EnthusJUSTIN3_APR10.jpg',
      ),
      '3' => array(
        'fid' => '8405',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'EnthusJUSTIN4_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/EnthusJUSTIN4_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92983',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'EnthusJUSTIN4_APR10.jpg',
      ),
    ),
    'path' => 'stories/justin-pinos',
    'tags' => array(
      '5' => array(
        '2519' => array(
          'tid' => '2519',
          'vid' => '5',
          'name' => 'BILLY WINTERS',
          'description' => 'http://www.billywinters.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'BILLY WINTERS',
        '4' => 'men',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
