array(
  array(
    'nid' => '3274',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1272468825',
    'changed' => '1404919873',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3274',
    'revision_uid' => '1',
    'title' => 'The Bearable Lightness of Being',
    'body' => '<p>
	Beautiful bearing.</p>
<p>
	Exclusive photography by <a href="http://www.enrique-vega.net/" target="_blank">Enrique Vega</a>.</p>
<p>
	Model ~&nbsp; Ediely @ Muse.</p>
',
    'teaser' => '<p>
	Beautiful bearing.</p>
<p>
	Exclusive photography by <a href="http://www.enrique-vega.net/" target="_blank">Enrique Vega</a>.</p>
<p>
	Model ~&nbsp; Ediely @ Muse.</p>
',
    'log' => '',
    'revision_timestamp' => '1404919873',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.enrique-vega.net/" target="_blank">Enrique Vega</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	<a href="http://www.1fashionproductions.com/" target="_blank">DAVIS CARRASQUILLO</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	EDIELY SPAPINELLO<br />
	@ MUSE<br />
	<br />
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.jenkao.com/" target="_blank">JEN KAO</a></li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '8496',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84199',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable_APR10.jpg',
      ),
      '1' => array(
        'fid' => '8568',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/Layout-1_Page-3_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '534116',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '8498',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable3_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable3_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14796',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable3_APR10.jpg',
      ),
      '3' => array(
        'fid' => '8499',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable4_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable4_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '400171',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable4_APR10.jpg',
      ),
      '4' => array(
        'fid' => '8500',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable5_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable5_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '277923',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable5_APR10.jpg',
      ),
      '5' => array(
        'fid' => '8501',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable6_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable6_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '190372',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable6_APR10.jpg',
      ),
      '6' => array(
        'fid' => '8502',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable7_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable7_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116998',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable7_APR10.jpg',
      ),
      '7' => array(
        'fid' => '8503',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable8_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable8_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160735',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable8_APR10.jpg',
      ),
      '8' => array(
        'fid' => '8504',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable9_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable9_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167249',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable9_APR10.jpg',
      ),
      '9' => array(
        'fid' => '8505',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable10_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable10_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '233858',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable10_APR10.jpg',
      ),
      '10' => array(
        'fid' => '8506',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable11_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable11_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '231820',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable11_APR10.jpg',
      ),
      '11' => array(
        'fid' => '8507',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable12_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable12_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '328247',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable12_APR10.jpg',
      ),
      '12' => array(
        'fid' => '8508',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable13_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable13_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '392242',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable13_APR10.jpg',
      ),
      '13' => array(
        'fid' => '8509',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bearable14_APR10.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/bearable14_APR10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '550642',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bearable14_APR10.jpg',
      ),
      '14' => array(
        'fid' => '8512',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/Layout-1_Page-16_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '362284',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '8513',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2010/Apr/Layout-1_Page-17_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '349222',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
    ),
    'path' => 'stories/bearable-lightness-being',
    'tags' => array(
      '4' => array(
        '2098' => array(
          'tid' => '2098',
          'vid' => '4',
          'name' => 'davis carrasquillo',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2563' => array(
          'tid' => '2563',
          'vid' => '5',
          'name' => 'Enrique Vega',
          'description' => 'http://www.enrique-vega.net/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'davis carrasquillo, women',
        '5' => 'Enrique Vega',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
