array(
  array(
    'nid' => '3283',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1273258208',
    'changed' => '1404920556',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3283',
    'revision_uid' => '1',
    'title' => 'A Single Man',
    'body' => '<p>
	Singular guy.</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.seanpwatters.com/" target="_blank">Sean Watters</a>.</p>
<p>
	<br />
	Model ~ Magnus @ Heartbreak.</p>
',
    'teaser' => '<p>
	Singular guy.</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.seanpwatters.com/" target="_blank">Sean Watters</a>.</p>
<p>
	<br />
	Model ~ Magnus @ Heartbreak.</p>
',
    'log' => '',
    'revision_timestamp' => '1404920556',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.seanpwatters.com/" target="_blank">Sean Watters</a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://seanpwatters.wordpress.com/" target="_blank">WATTERS WITH TWO T&#39;s</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	MAGNUS<br />
	@ HEARTBREAK</p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://manuel-delacruz.com/" target="_blank">MANUEL DE LA CRUZ</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '8588',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '208876',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single_MAY10.jpg',
      ),
      '1' => array(
        'fid' => '8606',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/May/Layout-1_Page-3_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '224114',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '8590',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single3_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single3_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158113',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single3_MAY10.jpg',
      ),
      '3' => array(
        'fid' => '8591',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single4_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single4_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '222113',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single4_MAY10.jpg',
      ),
      '4' => array(
        'fid' => '8592',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single5_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single5_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '304541',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single5_MAY10.jpg',
      ),
      '5' => array(
        'fid' => '8593',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single6_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single6_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '300971',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single6_MAY10.jpg',
      ),
      '6' => array(
        'fid' => '8594',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single7_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single7_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '144823',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single7_MAY10.jpg',
      ),
      '7' => array(
        'fid' => '8595',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single8_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single8_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15523',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single8_MAY10.jpg',
      ),
      '8' => array(
        'fid' => '8596',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single9_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single9_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117980',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single9_MAY10.jpg',
      ),
      '9' => array(
        'fid' => '8597',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single10_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single10_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127942',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single10_MAY10.jpg',
      ),
      '10' => array(
        'fid' => '8598',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single11_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single11_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '185434',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single11_MAY10.jpg',
      ),
      '11' => array(
        'fid' => '8599',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single12_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single12_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160548',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single12_MAY10.jpg',
      ),
      '12' => array(
        'fid' => '8600',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single13_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single13_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130183',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single13_MAY10.jpg',
      ),
      '13' => array(
        'fid' => '8601',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single14_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single14_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13729',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single14_MAY10.jpg',
      ),
      '14' => array(
        'fid' => '8602',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single15_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single15_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13497',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single15_MAY10.jpg',
      ),
      '15' => array(
        'fid' => '8603',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single16_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single16_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '125965',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single16_MAY10.jpg',
      ),
      '16' => array(
        'fid' => '8604',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single17_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single17_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158298',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single17_MAY10.jpg',
      ),
      '17' => array(
        'fid' => '8605',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'single18_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/single18_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '70962',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'single18_MAY10.jpg',
      ),
    ),
    'path' => 'stories/single-man',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2079' => array(
          'tid' => '2079',
          'vid' => '4',
          'name' => 'sean patrick watters',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2416' => array(
          'tid' => '2416',
          'vid' => '5',
          'name' => 'Sean Watters',
          'description' => 'http://www.seanpwatters.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'men, sean patrick watters',
        '5' => 'Sean Watters',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
