array(
  array(
    'nid' => '3291',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1273688606',
    'changed' => '1403919369',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3291',
    'revision_uid' => '1',
    'title' => 'Think Again',
    'body' => '<p>
	Take the vintage advantage.</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.evangunville.com/" target="_blank">EVAN GUNVILLE</a>.</p>
<p>
	<br />
	Model ~ Danielle Tedesco @ Ford/RBA.</p>
',
    'teaser' => '<p>
	Take the vintage advantage.</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.evangunville.com/" target="_blank">EVAN GUNVILLE</a>.</p>
<p>
	<br />
	Model ~ Danielle Tedesco @ Ford/RBA.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919369',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.evangunville.com/" target="_blank">EVAN GUNVILLE</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	DANIELLE TEDESCO<br />
	@ FORD/RBA</p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.fashionbyrobertblack.com/" target="_blank">FASHION BY ROBERT BLACK</a></li>
	<li>
		<a href="http://www.nordstroms.com/" target="_blank">NORDSTROM</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '8688',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/May/Layout-1_Page-2_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161042',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '8689',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/May/Layout-1_Page-3_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161627',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '8674',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think3_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think3_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20952',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think3_MAY10.jpg',
      ),
      '3' => array(
        'fid' => '8675',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think4_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think4_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155182',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think4_MAY10.jpg',
      ),
      '4' => array(
        'fid' => '8676',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think5_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think5_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '254107',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think5_MAY10.jpg',
      ),
      '5' => array(
        'fid' => '8677',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think6_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think6_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '149167',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think6_MAY10.jpg',
      ),
      '6' => array(
        'fid' => '8678',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think7_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think7_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '120598',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think7_MAY10.jpg',
      ),
      '7' => array(
        'fid' => '8679',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think8_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think8_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104898',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think8_MAY10.jpg',
      ),
      '8' => array(
        'fid' => '8680',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think9_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think9_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '21673',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think9_MAY10.jpg',
      ),
      '9' => array(
        'fid' => '8681',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think10_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think10_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '190323',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think10_MAY10.jpg',
      ),
      '10' => array(
        'fid' => '8682',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think11_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think11_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '213432',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think11_MAY10.jpg',
      ),
      '11' => array(
        'fid' => '8683',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think12_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think12_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '143063',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think12_MAY10.jpg',
      ),
      '12' => array(
        'fid' => '8684',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think13_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think13_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '262724',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think13_MAY10.jpg',
      ),
      '13' => array(
        'fid' => '8685',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think14_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think14_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158360',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think14_MAY10.jpg',
      ),
      '14' => array(
        'fid' => '8686',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think15_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think15_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '125405',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think15_MAY10.jpg',
      ),
      '15' => array(
        'fid' => '8687',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'think16_MAY10.jpg',
        'filepath' => 'files/fmag_story/2010/May/think16_MAY10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114950',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'think16_MAY10.jpg',
      ),
    ),
    'path' => 'stories/think-again',
    'tags' => array(
      '5' => array(
        '2567' => array(
          'tid' => '2567',
          'vid' => '5',
          'name' => 'EVAN GUNVILLE',
          'description' => 'http://www.evangunville.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'EVAN GUNVILLE',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
