array(
  array(
    'nid' => '3352',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1277729342',
    'changed' => '1337805231',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3352',
    'revision_uid' => '1',
    'title' => 'Air Conditioned',
    'body' => '<p>
	Crank it.</p>
<p>
	Exclusive photography by <a href="http://www.alkanphotography.com/" target="_blank">Alkan Emin</a>.</p>
<p>
	Model ~&nbsp; Andrew @ <a href="http://www.swishmodelmanagement.com/profile-andrew.html">Swish Models</a></p>
',
    'teaser' => '<p>
	Crank it.</p>
<p>
	Exclusive photography by <a href="http://www.alkanphotography.com/" target="_blank">Alkan Emin</a>.</p>
<p>
	Model ~&nbsp; Andrew @ <a href="http://www.swishmodelmanagement.com/profile-andrew.html">Swish Models</a></p>
',
    'log' => '',
    'revision_timestamp' => '1337805231',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.alkanphotography.com/" target="_blank">Alkan Emin</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	ANDREW<br />
	@ SWISH MODELS</p>
<p>
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.dsquared2.com/" target="_self">DSQUARED</a></li>
	<li>
		<a href="http://www.versace.com/" target="_blank">Versace</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '9352',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan2.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '329247',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan2.jpg',
      ),
      '1' => array(
        'fid' => '9353',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan3.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114427',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan3.jpg',
      ),
      '2' => array(
        'fid' => '9354',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan4.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '213910',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan4.jpg',
      ),
      '3' => array(
        'fid' => '9355',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan5.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '557578',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan5.jpg',
      ),
      '4' => array(
        'fid' => '9356',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan6.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '257737',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan6.jpg',
      ),
      '5' => array(
        'fid' => '9357',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan7.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '352460',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan7.jpg',
      ),
      '6' => array(
        'fid' => '9358',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan8.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '429646',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan8.jpg',
      ),
      '7' => array(
        'fid' => '9359',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan9.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '437399',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan9.jpg',
      ),
      '8' => array(
        'fid' => '9360',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan10.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '396450',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan10.jpg',
      ),
      '9' => array(
        'fid' => '9361',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan11.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '293318',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan11.jpg',
      ),
      '10' => array(
        'fid' => '9362',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan12.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '506121',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan12.jpg',
      ),
      '11' => array(
        'fid' => '9363',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan13.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '340540',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan13.jpg',
      ),
      '12' => array(
        'fid' => '9364',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan14.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87371',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan14.jpg',
      ),
      '13' => array(
        'fid' => '9365',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan15.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '284751',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan15.jpg',
      ),
      '14' => array(
        'fid' => '9366',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan16.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '357792',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan16.jpg',
      ),
      '15' => array(
        'fid' => '9367',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan17.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '442127',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan17.jpg',
      ),
      '16' => array(
        'fid' => '9368',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan18.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89775',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan18.jpg',
      ),
      '17' => array(
        'fid' => '9369',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'alkan19.jpg',
        'filepath' => 'files/fmag_story/2010/Jun/alkan19.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '660969',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'alkan19.jpg',
      ),
    ),
    'path' => 'stories/air-conditioned',
    'tags' => array(
      '5' => array(
        '2559' => array(
          'tid' => '2559',
          'vid' => '5',
          'name' => 'ALKAN EMIN',
          'description' => 'http://www.alkanphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '14' => array(
          'tid' => '14',
          'vid' => '1',
          'name' => 'men\'s',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ALKAN EMIN',
        '1' => 'men\'s',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
