array(
  array(
    'nid' => '3373',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1279652907',
    'changed' => '1303575450',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3373',
    'revision_uid' => '1',
    'title' => 'The Blue and The Grey',
    'body' => '<p>
	Palette cleanser.</p>
<p>
	Exclusive photography by <a href="http://www.mckenziejames.com/" target="_blank">MCKENZIE JAMES</a>.</p>
<p>
	Model ~ Mike @ Ford.</p>
',
    'teaser' => '<p>
	Palette cleanser.</p>
<p>
	Exclusive photography by <a href="http://www.mckenziejames.com/" target="_blank">MCKENZIE JAMES</a>.</p>
<p>
	Model ~ Mike @ Ford.</p>
',
    'log' => '',
    'revision_timestamp' => '1303575450',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.mckenziejames.com/" target="_blank">MCKENZIE JAMES</a></p>
<p>
	<br />
	MODELS<br />
	MIKE @ FORD</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.bluebloodbrand.com/" target="_blank">Blue Blood</a></li>
	<li>
		<a href="http://ringspun.co.uk/" target="_blank">Ringspun</a></li>
	<li>
		<a href="http://www.suit.dk/" target="_blank">Suit</a></li>
	<li>
		<a href="http://www.elevenparis.com/" target="_blank">Eleven Paris</a></li>
	<li>
		<a href="http://americanapparel.net/" target="_blank">American Apparel</a></li>
	<li>
		<a href="http://www.lacoste.com/" target="_blank">Lacoste</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '9554',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79312',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey_JUL10.jpg',
      ),
      '1' => array(
        'fid' => '9555',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey2_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey2_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '62374',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey2_JUL10.jpg',
      ),
      '2' => array(
        'fid' => '9571',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey3_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey3_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19217',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey3_JUL10.jpg',
      ),
      '3' => array(
        'fid' => '9557',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey4_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey4_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96277',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey4_JUL10.jpg',
      ),
      '4' => array(
        'fid' => '9558',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey5_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey5_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132275',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey5_JUL10.jpg',
      ),
      '5' => array(
        'fid' => '9559',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey6_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey6_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '105572',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey6_JUL10.jpg',
      ),
      '6' => array(
        'fid' => '9560',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey7_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey7_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '54625',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey7_JUL10.jpg',
      ),
      '7' => array(
        'fid' => '9561',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey8_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey8_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '120561',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey8_JUL10.jpg',
      ),
      '8' => array(
        'fid' => '9572',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey9_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey9_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17382',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey9_JUL10.jpg',
      ),
      '9' => array(
        'fid' => '9563',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey10_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey10_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94068',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey10_JUL10.jpg',
      ),
      '10' => array(
        'fid' => '9564',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey11_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey11_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '50100',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey11_JUL10.jpg',
      ),
      '11' => array(
        'fid' => '9565',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey12_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey12_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '42668',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey12_JUL10.jpg',
      ),
      '12' => array(
        'fid' => '9573',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey13_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey13_JUL10_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12208',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey13_JUL10.jpg',
      ),
      '13' => array(
        'fid' => '9574',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey14_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey14_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '59168',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey14_JUL10.jpg',
      ),
      '14' => array(
        'fid' => '9575',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey15_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey15_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81695',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey15_JUL10.jpg',
      ),
      '15' => array(
        'fid' => '9569',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blueandgrey16_JUL10.jpg',
        'filepath' => 'files/fmag_story/2010/Jul/blueandgrey16_JUL10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15025',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blueandgrey16_JUL10.jpg',
      ),
    ),
    'path' => 'stories/blue-and-grey',
    'tags' => array(
      '1' => array(
        '129' => array(
          'tid' => '129',
          'vid' => '1',
          'name' => 'American Apparel',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '125' => array(
          'tid' => '125',
          'vid' => '1',
          'name' => 'Blue Blood',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '128' => array(
          'tid' => '128',
          'vid' => '1',
          'name' => 'Eleven Paris',
          'description' => 'elevenparis.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '43' => array(
          'tid' => '43',
          'vid' => '1',
          'name' => 'Lacoste',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '126' => array(
          'tid' => '126',
          'vid' => '1',
          'name' => 'Ringspun',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '127' => array(
          'tid' => '127',
          'vid' => '1',
          'name' => 'Suit',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2415' => array(
          'tid' => '2415',
          'vid' => '5',
          'name' => 'McKenzie James',
          'description' => 'http://www.modelmayhem.com/29023',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'American Apparel, Blue Blood, Eleven Paris, Lacoste, Ringspun, Suit',
        '5' => 'McKenzie James',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
