array(
  array(
    'nid' => '3422',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1283689654',
    'changed' => '1406008963',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3422',
    'revision_uid' => '1',
    'title' => 'Pool Party',
    'body' => '<p>
	Looks good wet or on deck.</p>
<p>
	Exclusive photography by <a href="http://www.alexanderhankoff.com/" target="_blank">ALEXANDER HANKOFF</a>.</p>
<p>
	Model ~ Jessica Roffey @ Muse.</p>
',
    'teaser' => '<p>
	Looks good wet or on deck.</p>
<p>
	Exclusive photography by <a href="http://www.alexanderhankoff.com/" target="_blank">ALEXANDER HANKOFF</a>.</p>
<p>
	Model ~ Jessica Roffey @ Muse.</p>
',
    'log' => '',
    'revision_timestamp' => '1406008963',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.alexanderhankoff.com/" target="_blank">ALEXANDER HANKOFF</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	JESSICA ROFFEY<br />
	@ MUSE</p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.emiliopucci.com/chooseYourCountry.asp" target="_blank">EMILIO PUCCI</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10172',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '36433',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty_AUG10.jpg',
      ),
      '1' => array(
        'fid' => '10173',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty2_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty2_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136777',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty2_AUG10.jpg',
      ),
      '2' => array(
        'fid' => '10174',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty3_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty3_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153045',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty3_AUG10.jpg',
      ),
      '3' => array(
        'fid' => '10175',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty4_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty4_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '30451',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty4_AUG10.jpg',
      ),
      '4' => array(
        'fid' => '10176',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty5_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty5_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '150037',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty5_AUG10.jpg',
      ),
      '5' => array(
        'fid' => '10177',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty6_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty6_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18545',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty6_AUG10.jpg',
      ),
      '6' => array(
        'fid' => '10178',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty7_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty7_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107451',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty7_AUG10.jpg',
      ),
      '7' => array(
        'fid' => '10179',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty8_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty8_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17635',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty8_AUG10.jpg',
      ),
      '8' => array(
        'fid' => '10180',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty9_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty9_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123983',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty9_AUG10.jpg',
      ),
      '9' => array(
        'fid' => '10181',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty10_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty10_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13421',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty10_AUG10.jpg',
      ),
      '10' => array(
        'fid' => '10182',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty11_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty11_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156524',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty11_AUG10.jpg',
      ),
      '11' => array(
        'fid' => '10183',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'poolparty12_AUG10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/poolparty12_AUG10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15484',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'poolparty12_AUG10.jpg',
      ),
    ),
    'path' => 'stories/pool-party',
    'tags' => array(
      '5' => array(
        '2557' => array(
          'tid' => '2557',
          'vid' => '5',
          'name' => 'Alexander Hankoff',
          'description' => 'http://%20www.alexanderhankoff.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2134' => array(
          'tid' => '2134',
          'vid' => '4',
          'name' => 'bikini',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2129' => array(
          'tid' => '2129',
          'vid' => '4',
          'name' => 'swimwear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Alexander Hankoff',
        '4' => 'bikini, swimwear, women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
