array(
  array(
    'nid' => '3426',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1282825851',
    'changed' => '1406006104',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3426',
    'revision_uid' => '1',
    'title' => 'Wake Up To The Sun',
    'body' => '<p>
	<span class="sqq">You&#39;ll want to get an early start.</span></p>
<p>
	Exclusive photography by&nbsp;Don Miller.</p>
<p>
	Model ~ Valeria @ Next.</p>
',
    'teaser' => '<p>
	<span class="sqq">You&#39;ll want to get an early start.</span></p>
<p>
	Exclusive photography by&nbsp;Don Miller.</p>
<p>
	Model ~ Valeria @ Next.</p>
',
    'log' => '',
    'revision_timestamp' => '1406006104',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	DON MILLER</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	VALERIA @ <a href="http://www.nextmodels.com/#/home" target="_blank">NEXT</a></p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.marilynmonroe.co.za" target="_blank">MARILYN MONROE INTIMATES </a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10214',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun2.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '620338',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun2.jpg',
      ),
      '1' => array(
        'fid' => '10215',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun3.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '527156',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun3.jpg',
      ),
      '2' => array(
        'fid' => '10216',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun4.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91268',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun4.jpg',
      ),
      '3' => array(
        'fid' => '10217',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun5.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '334062',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun5.jpg',
      ),
      '4' => array(
        'fid' => '10218',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun6.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '664751',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun6.jpg',
      ),
      '5' => array(
        'fid' => '10219',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun7.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '661294',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun7.jpg',
      ),
      '6' => array(
        'fid' => '10227',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun8.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '429488',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun8.jpg',
      ),
      '7' => array(
        'fid' => '10220',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun9.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82275',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun9.jpg',
      ),
      '8' => array(
        'fid' => '10221',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun10.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '250974',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun10.jpg',
      ),
      '9' => array(
        'fid' => '10222',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun11.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '370070',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun11.jpg',
      ),
      '10' => array(
        'fid' => '10223',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun12.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '475066',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun12.jpg',
      ),
      '11' => array(
        'fid' => '10224',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun13.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81895',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun13.jpg',
      ),
      '12' => array(
        'fid' => '10225',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun14.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167733',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun14.jpg',
      ),
      '13' => array(
        'fid' => '10226',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wakeUpToTheSun15.jpg',
        'filepath' => 'files/fmag_story/2010/Aug/wakeUpToTheSun15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '721098',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wakeUpToTheSun15.jpg',
      ),
    ),
    'path' => 'stories/wake-sun',
    'tags' => array(
      '5' => array(
        '2592' => array(
          'tid' => '2592',
          'vid' => '5',
          'name' => 'DON MILLER',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2137' => array(
          'tid' => '2137',
          'vid' => '4',
          'name' => 'lingerie',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '11' => array(
          'tid' => '11',
          'vid' => '1',
          'name' => 'underwear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '15' => array(
          'tid' => '15',
          'vid' => '1',
          'name' => 'women\'s',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'DON MILLER',
        '4' => 'lingerie, women',
        '1' => 'underwear, women\'s',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
