array(
  array(
    'nid' => '3430',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1284061172',
    'changed' => '1403919365',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3430',
    'revision_uid' => '1',
    'title' => 'Waves of Grace',
    'body' => '<p>Karen Sabag\'s elegant design.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.jasonobrotka.com/">JASON OBROTKA</a>.</p>
<p>Model ~ Jennifer Sodhi.</p>',
    'teaser' => '<p>Karen Sabag\'s elegant design.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.jasonobrotka.com/">JASON OBROTKA</a>.</p>
<p>Model ~ Jennifer Sodhi.</p>',
    'log' => '',
    'revision_timestamp' => '1403919365',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>PHOTOGRAPHY<br /><a target="_blank" href="http://www.jasonobrotka.com/">JASON OBROTKA</a></p>
<p> </p>
<p>MODEL<br />JENNIFER SODHI</p>
<p> </p>
<p>FEATURED FASHION</p>
<ul>
<li><a target="_blank" href="http://www.karensabagcouture.com/">KAREN SABAG</a></li>
</ul>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10258',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'grace_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/grace_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161426',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'grace_SEPT10.jpg',
      ),
      '1' => array(
        'fid' => '10259',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'grace2_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/grace2_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154272',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'grace2_SEPT10.jpg',
      ),
      '2' => array(
        'fid' => '10260',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'grace3_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/grace3_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127957',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'grace3_SEPT10.jpg',
      ),
      '3' => array(
        'fid' => '10261',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'grace4_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/grace4_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '224203',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'grace4_SEPT10.jpg',
      ),
      '4' => array(
        'fid' => '10262',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'grace5_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/grace5_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '283928',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'grace5_SEPT10.jpg',
      ),
      '5' => array(
        'fid' => '10263',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'grace6_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/grace6_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '157556',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'grace6_SEPT10.jpg',
      ),
    ),
    'path' => 'stories/waves-grace',
    'tags' => array(
      '5' => array(
        '2492' => array(
          'tid' => '2492',
          'vid' => '5',
          'name' => 'JASON OBROTKA',
          'description' => 'http://www.jasonobrotka.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JASON OBROTKA',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
