array(
  array(
    'nid' => '3433',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1284405173',
    'changed' => '1406008929',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3433',
    'revision_uid' => '1',
    'title' => 'Elise',
    'body' => '<p>
	Exquisite Elise.</p>
<p>
	Exclusive photography by Joel Esposito.</p>
',
    'teaser' => '<p>
	Exquisite Elise.</p>
<p>
	Exclusive photography by Joel Esposito.</p>
',
    'log' => '',
    'revision_timestamp' => '1406008929',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	ELISE</p>
<p>
	<br />
	@ <a href="http://www.elmerolsenmodels.com/">ELMER OLSEN</a></p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	JOEL ESPOSITO</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10829',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-2_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '64154',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '10830',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-3_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97411',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '10284',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'elise3_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/elise3_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96850',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'elise3_SEPT10.jpg',
      ),
      '3' => array(
        'fid' => '10285',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'elise4_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/elise4_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '28781',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'elise4_SEPT10.jpg',
      ),
      '4' => array(
        'fid' => '10286',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'elise5_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/elise5_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '57276',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'elise5_SEPT10.jpg',
      ),
      '5' => array(
        'fid' => '10287',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'elise6_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/elise6_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18750',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'elise6_SEPT10.jpg',
      ),
      '6' => array(
        'fid' => '10288',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'elise7_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/elise7_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11378',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'elise7_SEPT10.jpg',
      ),
      '7' => array(
        'fid' => '10289',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'elise8_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/elise8_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91832',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'elise8_SEPT10.jpg',
      ),
      '8' => array(
        'fid' => '10290',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'elise9_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/elise9_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '42192',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'elise9_SEPT10.jpg',
      ),
      '9' => array(
        'fid' => '10291',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'elise10_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/elise10_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104820',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'elise10_SEPT10.jpg',
      ),
    ),
    'path' => 'stories/elise',
    'tags' => array(
      '4' => array(
        '2139' => array(
          'tid' => '2139',
          'vid' => '4',
          'name' => 'profile',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2593' => array(
          'tid' => '2593',
          'vid' => '5',
          'name' => 'REGEN CHEN',
          'description' => 'http://www.regenandhisphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '4' => 'profile, women',
        '5' => 'REGEN CHEN',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
