array(
  array(
    'nid' => '3449',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1284484994',
    'changed' => '1403919166',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3449',
    'revision_uid' => '1',
    'title' => 'Preppy Little Sweater',
    'body' => '<p>
	You need a September sweater kid.</p>
<p>
	Exclusive photography by James N.</p>
<p>
	Model ~&nbsp; Mike @ Ford.</p>
',
    'teaser' => '<p>
	You need a September sweater kid.</p>
<p>
	Exclusive photography by James N.</p>
<p>
	Model ~&nbsp; Mike @ Ford.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919166',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	JAMES N</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	MIKE @ FORD<br />
	<br />
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		J CREW</li>
	<li>
		BROOKS BROTHERS</li>
	<li>
		TOMMY HILFIGER</li>
	<li>
		BANANA REPUBLIC</li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10334',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'preppy_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/preppy_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153414',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'preppy_SEPT10.jpg',
      ),
      '1' => array(
        'fid' => '10344',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'preppy2_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/preppy2_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '56310',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'preppy2_SEPT10.jpg',
      ),
      '2' => array(
        'fid' => '10336',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'preppy3_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/preppy3_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17443',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'preppy3_SEPT10.jpg',
      ),
      '3' => array(
        'fid' => '10337',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'preppy4_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/preppy4_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '120637',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'preppy4_SEPT10.jpg',
      ),
      '4' => array(
        'fid' => '10338',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'preppy5_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/preppy5_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '189333',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'preppy5_SEPT10.jpg',
      ),
      '5' => array(
        'fid' => '10339',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'preppy6_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/preppy6_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '171864',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'preppy6_SEPT10.jpg',
      ),
      '6' => array(
        'fid' => '10340',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'preppy7_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/preppy7_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '239167',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'preppy7_SEPT10.jpg',
      ),
      '7' => array(
        'fid' => '10341',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'preppy8_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/preppy8_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '177538',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'preppy8_SEPT10.jpg',
      ),
      '8' => array(
        'fid' => '10342',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'preppy9_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/preppy9_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13466',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'preppy9_SEPT10.jpg',
      ),
      '9' => array(
        'fid' => '10343',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'preppy10_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/preppy10_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130556',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'preppy10_SEPT10.jpg',
      ),
    ),
    'path' => 'stories/preppy-little-sweater',
    'tags' => array(
      '5' => array(
        '2412' => array(
          'tid' => '2412',
          'vid' => '5',
          'name' => 'JAMES N',
          'description' => 'jimmynixon.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JAMES N',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
