array(
  array(
    'nid' => '3458',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1285267756',
    'changed' => '1403919364',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3458',
    'revision_uid' => '1',
    'title' => 'Dualities',
    'body' => '<p>New waves.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.wtphoto.com/">WILL TAYLOR</a>.</p>
<p>Models ~  Dani, Emily &amp; Zinta @ Photogenics.</p>',
    'teaser' => '<p>New waves.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.wtphoto.com/">WILL TAYLOR</a>.</p>
<p>Models ~  Dani, Emily &amp; Zinta @ Photogenics.</p>',
    'log' => '',
    'revision_timestamp' => '1403919364',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>PHOTOGRAPHY<br /><a target="_blank" href="http://www.wtphoto.com/">WILL TAYLOR</a></p>
<p> </p>
<p>MODELS<br />DANI, EMILY<br />&amp; ZINTA<br />@ PHOTOGENICS</p>
<p> </p>
<p><br />FEATURED PRODUCT</p>
<ul>
<li>"R" SESSION NALU WAVER</li>
</ul>
<ul>
<br /><br /> 
</ul>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10561',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-2_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '238377',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '10562',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-3_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '191007',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '10425',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dual3_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/dual3_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '234022',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'dual3_SEPT10.jpg',
      ),
      '3' => array(
        'fid' => '10426',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dual4_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/dual4_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '178518',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'dual4_SEPT10.jpg',
      ),
      '4' => array(
        'fid' => '10427',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dual5_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/dual5_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '202011',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'dual5_SEPT10.jpg',
      ),
      '5' => array(
        'fid' => '10428',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'dual6_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/dual6_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153248',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'dual6_SEPT10.jpg',
      ),
    ),
    'path' => 'stories/dualities',
    'tags' => array(
      '5' => array(
        '2535' => array(
          'tid' => '2535',
          'vid' => '5',
          'name' => 'Will Taylor',
          'description' => 'http://wtphoto.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '1' => '1',
      ),
      'tags' => array(
        '5' => 'Will Taylor',
        '4' => 'women',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
