array(
  array(
    'nid' => '3464',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1285338578',
    'changed' => '1403919166',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3464',
    'revision_uid' => '1',
    'title' => 'Plaid Factor',
    'body' => '<p>
	Mad about plaid.</p>
<p>
	Exclusive photography by <a href="http://www.jasonobrotka.com/" target="_blank">JASON OBROTKA</a>.</p>
<p>
	Model ~ Isaac @ VNY.</p>
',
    'teaser' => '<p>
	Mad about plaid.</p>
<p>
	Exclusive photography by <a href="http://www.jasonobrotka.com/" target="_blank">JASON OBROTKA</a>.</p>
<p>
	Model ~ Isaac @ VNY.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919166',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.jasonobrotka.com/" target="_blank">JASON OBROTKA</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	ISAAC @ VNY</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10550',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-2_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '272566',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '10551',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-3_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108853',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '10539',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-4_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15608',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '10552',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '339266',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '10541',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-6_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67927',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '10542',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-7_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75373',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '10553',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-8_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '200209',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '10554',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-9_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '147668',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '10547',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-10_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '304763',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '10549',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-11_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136087',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
    ),
    'path' => 'stories/plaid-factor',
    'tags' => array(
      '1' => array(
        '318' => array(
          'tid' => '318',
          'vid' => '1',
          'name' => 'General Idea',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '229' => array(
          'tid' => '229',
          'vid' => '1',
          'name' => 'TOPMAN',
          'description' => 'www.topman.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '156' => array(
          'tid' => '156',
          'vid' => '1',
          'name' => 'UNIQLO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2492' => array(
          'tid' => '2492',
          'vid' => '5',
          'name' => 'JASON OBROTKA',
          'description' => 'http://www.jasonobrotka.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'General Idea, TOPMAN, UNIQLO',
        '5' => 'JASON OBROTKA',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
