array(
  array(
    'nid' => '3467',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1285679166',
    'changed' => '1403919166',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3467',
    'revision_uid' => '1',
    'title' => 'Fall Guy',
    'body' => '<p>Autumnal accents.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.vikrampathak.com/">VIKRAM PATHAK</a>.</p>
<p>Model ~  Joshua Brisbane.</p>',
    'teaser' => '<p>Autumnal accents.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.vikrampathak.com/">VIKRAM PATHAK</a>.</p>
<p>Model ~  Joshua Brisbane.</p>',
    'log' => '',
    'revision_timestamp' => '1403919166',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>PHOTOGRAPHY<br /><a target="_blank" href="http://www.vikrampathak.com/">VIKRAM PATHAK</a></p>
<p> </p>
<p>MODEL<br />JOSHUA BRISBANE</p>
<p> </p>
<p>FEATURED PRODUCT</p>
<ul>
<li><a target="_blank" href="http://www.alkemyclothing.com/">Alkemy</a></li>
<li><a target="_blank" href="http://www.marknason.com/">MARK NASON</a></li>
<li><a target="_blank" href="http://www.sosumeclothing.com/">sosume</a></li>
<li><a target="_blank" href="http://www.diesel.com/">diesel</a></li>
</ul>
<ul>
<br /><br /> 
</ul>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10555',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-2_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '189161',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '10556',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/Layout-1_Page-3_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61313',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '10527',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fall3_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/fall3_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '171098',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fall3_SEPT10.jpg',
      ),
      '3' => array(
        'fid' => '10528',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fall4_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/fall4_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '187524',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fall4_SEPT10.jpg',
      ),
      '4' => array(
        'fid' => '10529',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fall5_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/fall5_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fall5_SEPT10.jpg',
      ),
      '5' => array(
        'fid' => '10530',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fall6_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/fall6_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158441',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fall6_SEPT10.jpg',
      ),
      '6' => array(
        'fid' => '10531',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fall7_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/fall7_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '205105',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fall7_SEPT10.jpg',
      ),
      '7' => array(
        'fid' => '10532',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fall8_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/fall8_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '179725',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fall8_SEPT10.jpg',
      ),
      '8' => array(
        'fid' => '10533',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fall9_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/fall9_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '115132',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fall9_SEPT10.jpg',
      ),
      '9' => array(
        'fid' => '10534',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fall10_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/fall10_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104006',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fall10_SEPT10.jpg',
      ),
      '10' => array(
        'fid' => '10535',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fall11_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/fall11_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '159104',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fall11_SEPT10.jpg',
      ),
      '11' => array(
        'fid' => '10536',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'fall12_SEPT10.jpg',
        'filepath' => 'files/fmag_story/2010/Sep/fall12_SEPT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '177668',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'fall12_SEPT10.jpg',
      ),
    ),
    'path' => 'stories/fall-guy',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2467' => array(
          'tid' => '2467',
          'vid' => '5',
          'name' => 'VIKRAM PATHAK',
          'description' => 'http://www.vikrampathak.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'men',
        '5' => 'VIKRAM PATHAK',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
