array(
  array(
    'nid' => '3487',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1287411761',
    'changed' => '1403919165',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3487',
    'revision_uid' => '1',
    'title' => 'The Wares We Like',
    'body' => '<p>
	Note these.</p>
<p>
	Exclusive photography by James N.</p>
<p>
	Model ~ Jesse Carter @ Adam.</p>
',
    'teaser' => '<p>
	Note these.</p>
<p>
	Exclusive photography by James N.</p>
<p>
	Model ~ Jesse Carter @ Adam.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919165',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	MODEL<br />
	JESSE CARTER<br />
	@ ADAM</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	JAMES N</p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		WOOD WOOD</li>
	<li>
		UNIQLO</li>
	<li>
		EMPORIO ARMANI</li>
	<li>
		TOPMAN</li>
	<li>
		HENRIK VIBSKOV</li>
	<li>
		BANANA REPUBLIC</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10862',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-2_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87200',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '10863',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-3_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '210771',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '10807',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '199938',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '10808',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '220994',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '10809',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '135704',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '10810',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119006',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '10811',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173790',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '10812',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-9_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '43136',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '10813',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67041',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '10814',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106459',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '10815',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '204148',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '10816',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72351',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '10817',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '115101',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '10818',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13421',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '10819',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-16_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '265735',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '10820',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '69126',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '16' => array(
        'fid' => '10821',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97325',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
      '17' => array(
        'fid' => '10822',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-19.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-19.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132187',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-19.jpg',
      ),
      '18' => array(
        'fid' => '10823',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-20.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-20.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134852',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-20.jpg',
      ),
      '19' => array(
        'fid' => '10824',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-21.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-21.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130691',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-21.jpg',
      ),
      '20' => array(
        'fid' => '10825',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-22.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-22.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '185359',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-22.jpg',
      ),
      '21' => array(
        'fid' => '10826',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-23.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-23.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '222651',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-23.jpg',
      ),
    ),
    'path' => 'stories/wares-we',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2554' => array(
          'tid' => '2554',
          'vid' => '5',
          'name' => 'Tracy Rasinski',
          'description' => 'http://www.tracyrasinski.com/#splashpage-f4cd0',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '4' => 'men',
        '5' => 'Tracy Rasinski',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
