array(
  array(
    'nid' => '3489',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1287619544',
    'changed' => '1403919364',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3489',
    'revision_uid' => '1',
    'title' => 'It\'s A Man\'s World',
    'body' => '<p>She likes what boys like.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.samanthawolov.com/">Samantha wolov</a>.</p>
<p>Model ~  Anna @ Look.</p>',
    'teaser' => '<p>She likes what boys like.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.samanthawolov.com/">Samantha wolov</a>.</p>
<p>Model ~  Anna @ Look.</p>',
    'log' => '',
    'revision_timestamp' => '1403919364',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>PHOTOGRAPHY<br /><a target="_blank" href="http://www.samanthawolov.com/">Samantha wolov<br /></a></p>
<p><br /><br />MODEL<br />ANNA @ LOOK</p>
<p> </p>
<p>FEATURED FASHION</p>
<ul>
<li> VIONNET</li>
<li>ALEXANDER WANG</li>
<li>MOSCHINO</li>
</ul>
<ul>
<br /><br /> 
</ul>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10853',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mans_OCT10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/mans_OCT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137675',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'mans_OCT10.jpg',
      ),
      '1' => array(
        'fid' => '10854',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mans2_OCT10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/mans2_OCT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '56660',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'mans2_OCT10.jpg',
      ),
      '2' => array(
        'fid' => '10855',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mans3_OCT10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/mans3_OCT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '151411',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'mans3_OCT10.jpg',
      ),
      '3' => array(
        'fid' => '10856',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mans4_OCT10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/mans4_OCT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18515',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'mans4_OCT10.jpg',
      ),
      '4' => array(
        'fid' => '10857',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mans5_OCT10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/mans5_OCT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14217',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'mans5_OCT10.jpg',
      ),
      '5' => array(
        'fid' => '10858',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mans6_OCT10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/mans6_OCT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126717',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'mans6_OCT10.jpg',
      ),
      '6' => array(
        'fid' => '10859',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mans7_OCT10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/mans7_OCT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136055',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'mans7_OCT10.jpg',
      ),
      '7' => array(
        'fid' => '10860',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'mans8_OCT10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/mans8_OCT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14663',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'mans8_OCT10.jpg',
      ),
    ),
    'path' => 'stories/its-mans-world',
    'tags' => array(
      '5' => array(
        '2598' => array(
          'tid' => '2598',
          'vid' => '5',
          'name' => 'Samantha wolov',
          'description' => 'http://www.samanthawolov.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Samantha wolov',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
