array(
  array(
    'nid' => '3498',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1288066675',
    'changed' => '1406008944',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3498',
    'revision_uid' => '1',
    'title' => 'Model T',
    'body' => '<p>
	Running down the line: <a href="http://www.laceeswan.com/">Lacee Swan</a>&#39;s Model Series.</p>
<p>
	Exclusive photography by <a href="http://www.jasonobrotka.com/">Jason Obrotka</a>.</p>
<p>
	Models ~&nbsp; Courtney @ Q, &nbsp;Ekaterina @ MC2.</p>
',
    'teaser' => '<p>
	Running down the line: <a href="http://www.laceeswan.com/">Lacee Swan</a>&#39;s Model Series.</p>
<p>
	Exclusive photography by <a href="http://www.jasonobrotka.com/">Jason Obrotka</a>.</p>
<p>
	Models ~&nbsp; Courtney @ Q, &nbsp;Ekaterina @ MC2.</p>
',
    'log' => '',
    'revision_timestamp' => '1406008944',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY</p>
<meta charset="utf-8" />
<p>
	<a href="http://www.jasonobrotka.com/">JASON OBROTKA</a></p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	COURTNEY @ Q,<br />
	EKATERINA @ MC2.<br />
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.laceeswan.com/">LACEE SWAN</a></li>
	<li>
		<a href="http://www.fancysexyme.com/">FANCYSEXYME</a></li>
	<li>
		<a href="http://www.renerofe.com/">RENE ROFE</a></li>
</ul>
<ul>
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10911',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT2.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77880',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT2.jpg',
      ),
      '1' => array(
        'fid' => '10912',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT3.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127970',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT3.jpg',
      ),
      '2' => array(
        'fid' => '10913',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT4.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137908',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT4.jpg',
      ),
      '3' => array(
        'fid' => '10914',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT5.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108866',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT5.jpg',
      ),
      '4' => array(
        'fid' => '10915',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT6.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85055',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT6.jpg',
      ),
      '5' => array(
        'fid' => '10916',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT7.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94941',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT7.jpg',
      ),
      '6' => array(
        'fid' => '10917',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT8.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138402',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT8.jpg',
      ),
      '7' => array(
        'fid' => '10918',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT9.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '52596',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT9.jpg',
      ),
      '8' => array(
        'fid' => '10919',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '70577',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT10.jpg',
      ),
      '9' => array(
        'fid' => '10920',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT11.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65451',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT11.jpg',
      ),
      '10' => array(
        'fid' => '10921',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT12.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63290',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT12.jpg',
      ),
      '11' => array(
        'fid' => '10922',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT13.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117647',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT13.jpg',
      ),
      '12' => array(
        'fid' => '10923',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT14.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '368106',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT14.jpg',
      ),
      '13' => array(
        'fid' => '10924',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT15.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '399855',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT15.jpg',
      ),
      '14' => array(
        'fid' => '10925',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT16.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131097',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT16.jpg',
      ),
      '15' => array(
        'fid' => '10926',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'modelT17.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/modelT17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141633',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'modelT17.jpg',
      ),
    ),
    'path' => 'stories/model-t',
    'tags' => array(
      '4' => array(
        '2137' => array(
          'tid' => '2137',
          'vid' => '4',
          'name' => 'lingerie',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2439' => array(
          'tid' => '2439',
          'vid' => '5',
          'name' => 'PHOTOGRAPHY',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '78' => array(
          'tid' => '78',
          'vid' => '1',
          'name' => 'tshirts',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '11' => array(
          'tid' => '11',
          'vid' => '1',
          'name' => 'underwear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '15' => array(
          'tid' => '15',
          'vid' => '1',
          'name' => 'women\'s',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'lingerie, women',
        '5' => 'PHOTOGRAPHY',
        '1' => 'tshirts, underwear, women\'s',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
