array(
  array(
    'nid' => '3503',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1288648886',
    'changed' => '1303575697',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3503',
    'revision_uid' => '1',
    'title' => 'Sex Type Thing',
    'body' => '<p>
	The girl can&#39;t help it.</p>
<p>
	Exclusive photography by <a href="http://www.lynxkarma.com/" target="_blank">Kira Bucca</a>.</p>
<p>
	Model ~&nbsp; Alexis Armour @ Sutherland.</p>
',
    'teaser' => '<p>
	The girl can&#39;t help it.</p>
<p>
	Exclusive photography by <a href="http://www.lynxkarma.com/" target="_blank">Kira Bucca</a>.</p>
<p>
	Model ~&nbsp; Alexis Armour @ Sutherland.</p>
',
    'log' => '',
    'revision_timestamp' => '1303575697',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.lynxkarma.com/" target="_blank">Kira Bucca</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	ALEXIS ARMOUR<br />
	@ SUTHERLAND<br />
	<br />
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.pinkcobra.ca/" target="_self">Pink Cobra</a></li>
</ul>
<ul>
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '10977',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '344090',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype_NOV10.jpg',
      ),
      '1' => array(
        'fid' => '10976',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype2_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype2_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1999407',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype2_NOV10.jpg',
      ),
      '2' => array(
        'fid' => '10963',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-4_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '169968',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '10964',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160823',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '10965',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype5_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype5_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114393',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype5_NOV10.jpg',
      ),
      '5' => array(
        'fid' => '10966',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype6_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype6_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71624',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype6_NOV10.jpg',
      ),
      '6' => array(
        'fid' => '10967',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype7_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype7_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119370',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype7_NOV10.jpg',
      ),
      '7' => array(
        'fid' => '10968',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype8_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype8_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114854',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype8_NOV10.jpg',
      ),
      '8' => array(
        'fid' => '10969',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype9_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype9_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104251',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype9_NOV10.jpg',
      ),
      '9' => array(
        'fid' => '10970',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype10_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype10_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117875',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype10_NOV10.jpg',
      ),
      '10' => array(
        'fid' => '10971',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype11_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype11_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '110231',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype11_NOV10.jpg',
      ),
      '11' => array(
        'fid' => '10972',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype12_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype12_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129014',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype12_NOV10.jpg',
      ),
      '12' => array(
        'fid' => '10973',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype13_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype13_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108842',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype13_NOV10.jpg',
      ),
      '13' => array(
        'fid' => '10974',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sextype14_NOV10.jpg',
        'filepath' => 'files/fmag_story/2010/Oct/sextype14_NOV10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132971',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sextype14_NOV10.jpg',
      ),
    ),
    'path' => 'stories/sex-type-thing',
    'tags' => array(
      '5' => array(
        '2586' => array(
          'tid' => '2586',
          'vid' => '5',
          'name' => 'KIRA BUCCA',
          'description' => 'http://www.lynxkarma.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'KIRA BUCCA',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
