array(
  array(
    'nid' => '3518',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1290183541',
    'changed' => '1403919165',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3518',
    'revision_uid' => '1',
    'title' => 'Underpass',
    'body' => '<p>
	Do it in the Road.</p>
<p>
	Exclusive photography by <a href="http://www.alexanderhankoff.com/" target="_blank">Alexander Hankoff</a>.</p>
<p>
	Model ~ Joshua O&#39;Sullivan @ Click.</p>
',
    'teaser' => '<p>
	Do it in the Road.</p>
<p>
	Exclusive photography by <a href="http://www.alexanderhankoff.com/" target="_blank">Alexander Hankoff</a>.</p>
<p>
	Model ~ Joshua O&#39;Sullivan @ Click.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919165',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.alexanderhankoff.com/" target="_blank">Alexander Hankoff</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	OLIVIA DE ABROGIO</p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	JOSHUA O&#39;SULLIVAN<br />
	@ CLICK</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.johngalliano.com/" target="_blank">JOHN GALLIANO</a></li>
	<li>
		<a href="http://www.paulsmith.co.uk" target="_blank">PAUL SMITH</a></li>
	<li>
		<a href="http://www.paulsmith.co.uk" target="_blank">BRUNO CUCINELLI</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11161',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'underpass_2.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/underpass_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '120060',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'underpass_2.jpg',
      ),
      '1' => array(
        'fid' => '11162',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'underpass_3.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/underpass_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140293',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'underpass_3.jpg',
      ),
      '2' => array(
        'fid' => '11117',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hankoffnight_4.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/hankoffnight_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '227849',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hankoffnight_4.jpg',
      ),
      '3' => array(
        'fid' => '11118',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hankoffnight_5.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/hankoffnight_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78421',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hankoffnight_5.jpg',
      ),
      '4' => array(
        'fid' => '11119',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hankoffnight_6.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/hankoffnight_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129795',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hankoffnight_6.jpg',
      ),
      '5' => array(
        'fid' => '11120',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hankoffnight_7.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/hankoffnight_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124237',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hankoffnight_7.jpg',
      ),
      '6' => array(
        'fid' => '11121',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hankoffnight_8.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/hankoffnight_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '185996',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hankoffnight_8.jpg',
      ),
      '7' => array(
        'fid' => '11122',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hankoffnight_9.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/hankoffnight_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '235025',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hankoffnight_9.jpg',
      ),
    ),
    'path' => 'stories/underpass',
    'tags' => array(
      '5' => array(
        '2557' => array(
          'tid' => '2557',
          'vid' => '5',
          'name' => 'Alexander Hankoff',
          'description' => 'http://%20www.alexanderhankoff.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '171' => array(
          'tid' => '171',
          'vid' => '1',
          'name' => 'BRUNO CUCINELLI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '169' => array(
          'tid' => '169',
          'vid' => '1',
          'name' => 'JOHN GALLIANO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '170' => array(
          'tid' => '170',
          'vid' => '1',
          'name' => 'PAUL SMITH',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Alexander Hankoff',
        '1' => 'BRUNO CUCINELLI, JOHN GALLIANO, PAUL SMITH',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
