array(
  array(
    'nid' => '3523',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1290004965',
    'changed' => '1411162130',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3523',
    'revision_uid' => '1',
    'title' => 'Gothic Revival',
    'body' => '<p>
	Gothic but not goth</p>
<p>
	Exclusive photography by <a href="http://www.jasonobrotka.com/" target="_blank">JASON OBROTKA</a>.</p>
<p>
	Model ~ Anna J @ MC2.</p>
',
    'teaser' => '<p>
	Gothic but not goth</p>
<p>
	Exclusive photography by <a href="http://www.jasonobrotka.com/" target="_blank">JASON OBROTKA</a>.</p>
<p>
	Model ~ Anna J @ MC2.</p>
',
    'log' => '',
    'revision_timestamp' => '1411162130',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.jasonobrotka.com/" target="_blank">JASON OBROTKA</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	KAREN PEREZ</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	ANNA J<br />
	@ MC2</p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.liesangbong.com/gb/index.php" target="_blank">LIE SANG BONG</a></li>
	<li>
		<a href="http://www.revivalvintageboutique.com/" target="_blank">REVIVAL</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11148',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_2.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100141',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_2.jpg',
      ),
      '1' => array(
        'fid' => '11149',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_3.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '62857',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_3.jpg',
      ),
      '2' => array(
        'fid' => '11150',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_4.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161775',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_4.jpg',
      ),
      '3' => array(
        'fid' => '11151',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_5.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22562',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_5.jpg',
      ),
      '4' => array(
        'fid' => '11152',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_6.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19935',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_6.jpg',
      ),
      '5' => array(
        'fid' => '11153',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_7.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129455',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_7.jpg',
      ),
      '6' => array(
        'fid' => '11154',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_8.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '191395',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_8.jpg',
      ),
      '7' => array(
        'fid' => '11155',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_9.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '21117',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_9.jpg',
      ),
      '8' => array(
        'fid' => '11156',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_10.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153016',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_10.jpg',
      ),
      '9' => array(
        'fid' => '11157',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_11.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153331',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_11.jpg',
      ),
      '10' => array(
        'fid' => '11158',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_12.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11381',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_12.jpg',
      ),
      '11' => array(
        'fid' => '11159',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Obrotka_13.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Obrotka_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '187196',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Obrotka_13.jpg',
      ),
    ),
    'path' => 'stories/gothic-revival',
    'tags' => array(
      '5' => array(
        '2492' => array(
          'tid' => '2492',
          'vid' => '5',
          'name' => 'JASON OBROTKA',
          'description' => 'http://www.jasonobrotka.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2273' => array(
          'tid' => '2273',
          'vid' => '4',
          'name' => 'kink',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '79' => array(
          'tid' => '79',
          'vid' => '1',
          'name' => 'Lie Sang Bong',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '172' => array(
          'tid' => '172',
          'vid' => '1',
          'name' => 'REVIVAL',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JASON OBROTKA',
        '4' => 'kink, women',
        '1' => 'Lie Sang Bong, REVIVAL',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
