array(
  array(
    'nid' => '3525',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1290465007',
    'changed' => '1337805053',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3525',
    'revision_uid' => '1',
    'title' => 'Here I Am',
    'body' => '<p>
	Evil twins and dualities and such.</p>
<p>
	Exclusive photography by <a href="http://www.journeygong.com/" target="_blank">JOURNEY GONG</a>.</p>
<p>
	Model ~ Thomas Whitfield @ Orb.</p>
',
    'teaser' => '<p>
	Evil twins and dualities and such.</p>
<p>
	Exclusive photography by <a href="http://www.journeygong.com/" target="_blank">JOURNEY GONG</a>.</p>
<p>
	Model ~ Thomas Whitfield @ Orb.</p>
',
    'log' => '',
    'revision_timestamp' => '1337805053',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.journeygong.com/" target="_blank">JOURNEY GONG</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	OSCAR MONTES DE OCA</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	THOMAS WHITFIELD<br />
	@ ORB</p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://longzone.net/" target="_blank">Long Zone</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11164',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_2.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '57770',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_2.jpg',
      ),
      '1' => array(
        'fid' => '11165',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_3.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106820',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_3.jpg',
      ),
      '2' => array(
        'fid' => '11166',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_4.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132893',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_4.jpg',
      ),
      '3' => array(
        'fid' => '11167',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_5.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112429',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_5.jpg',
      ),
      '4' => array(
        'fid' => '11168',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_6.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98014',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_6.jpg',
      ),
      '5' => array(
        'fid' => '11169',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_7.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16682',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_7.jpg',
      ),
      '6' => array(
        'fid' => '11170',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_8.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112999',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_8.jpg',
      ),
      '7' => array(
        'fid' => '11171',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_9.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '50248',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_9.jpg',
      ),
      '8' => array(
        'fid' => '11172',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_10.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19942',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_10.jpg',
      ),
      '9' => array(
        'fid' => '11173',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_11.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94947',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_11.jpg',
      ),
      '10' => array(
        'fid' => '11174',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_12.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108772',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_12.jpg',
      ),
      '11' => array(
        'fid' => '11175',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_13.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '144098',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_13.jpg',
      ),
      '12' => array(
        'fid' => '11176',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_14.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129446',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_14.jpg',
      ),
      '13' => array(
        'fid' => '11177',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_15.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '146341',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_15.jpg',
      ),
      '14' => array(
        'fid' => '11178',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_16.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16365',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_16.jpg',
      ),
      '15' => array(
        'fid' => '11179',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_17.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97462',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_17.jpg',
      ),
      '16' => array(
        'fid' => '11180',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_18.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103172',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_18.jpg',
      ),
      '17' => array(
        'fid' => '11181',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_19.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_19.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112266',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_19.jpg',
      ),
      '18' => array(
        'fid' => '11182',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_20.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_20.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96350',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_20.jpg',
      ),
      '19' => array(
        'fid' => '11183',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'journey_21.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/journey_21.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13510',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'journey_21.jpg',
      ),
    ),
    'path' => 'stories/here-i-am',
    'tags' => array(
      '5' => array(
        '2587' => array(
          'tid' => '2587',
          'vid' => '5',
          'name' => 'Journey Gong',
          'description' => 'http://journeygong.blogspot.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '168' => array(
          'tid' => '168',
          'vid' => '1',
          'name' => 'Long Zone',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Journey Gong',
        '1' => 'Long Zone',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
