array(
  array(
    'nid' => '3536',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1291152725',
    'changed' => '1337805014',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3536',
    'revision_uid' => '1',
    'title' => 'Western Union',
    'body' => '<p>
	West meets wow.</p>
<p>
	Exclusive photography by <a href="http://www.cajiophoto.com/" target="_blank">David Cajio</a>.</p>
<p>
	Models ~&nbsp; Ryan Melissa @ Greer Lange &amp; Britt AW.</p>
',
    'teaser' => '<p>
	West meets wow.</p>
<p>
	Exclusive photography by <a href="http://www.cajiophoto.com/" target="_blank">David Cajio</a>.</p>
<p>
	Models ~&nbsp; Ryan Melissa @ Greer Lange &amp; Britt AW.</p>
',
    'log' => '',
    'revision_timestamp' => '1337805014',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.cajiophoto.com/" target="_blank">David Cajio</a></p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	RYAN MELISSA<br />
	@ GREER LANGE<br />
	&amp; BRITT AW</p>
<p>
	&nbsp;</p>
<p>
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		BELLE MORTE</li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11278',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-2_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '176549',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '11334',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-3_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '184076',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '11280',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-4_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '177739',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '11281',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-5_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '11282',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-6_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117383',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '11283',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-7_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160734',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '11284',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-8_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '292512',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '11285',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-9_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '319314',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '11286',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-10_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '253149',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '11287',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-11_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '274208',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '11288',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-12_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '179097',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '11289',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/Layout-1_Page-13_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119690',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/western-union',
    'tags' => array(
      '1' => array(
        '163' => array(
          'tid' => '163',
          'vid' => '1',
          'name' => 'BELLE MORTE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2602' => array(
          'tid' => '2602',
          'vid' => '5',
          'name' => 'David Cajio',
          'description' => 'http://www.cajiophoto.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'BELLE MORTE',
        '5' => 'David Cajio',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
