array(
  array(
    'nid' => '3540',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1291407012',
    'changed' => '1403919164',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3540',
    'revision_uid' => '1',
    'title' => 'Getting Back To Where I Was',
    'body' => '<p>
	Get Back.</p>
<p>
	Exclusive photography by <a href="http://www.kristiinawilson.com/" target="_blank">KRISTIINA WILSON</a>.</p>
<p>
	Model ~&nbsp; Paul Boche @ Fusion.</p>
',
    'teaser' => '<p>
	Get Back.</p>
<p>
	Exclusive photography by <a href="http://www.kristiinawilson.com/" target="_blank">KRISTIINA WILSON</a>.</p>
<p>
	Model ~&nbsp; Paul Boche @ Fusion.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919164',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.kristiinawilson.com" target="_blank">KRISTIINA WILSON</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	MARTIN WAITT</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	PAUL BOCHE<br />
	@ FUSION</p>
<p>
	&nbsp;</p>
<p>
	<br />
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.louisvuitton.com/" target="_blank">LOUIS VUITTON</a></li>
	<li>
		<a href="http://www.31philliplim.com/" target="_blank">PHILLIP LIM</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11321',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWas_2.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWas_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118075',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWas_2.jpg',
      ),
      '1' => array(
        'fid' => '11333',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWasTITLE.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWasTITLE.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72307',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWasTITLE.jpg',
      ),
      '2' => array(
        'fid' => '11323',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWas_4.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWas_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92455',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWas_4.jpg',
      ),
      '3' => array(
        'fid' => '11324',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWas_5.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWas_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22263',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWas_5.jpg',
      ),
      '4' => array(
        'fid' => '11325',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWas_6.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWas_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17477',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWas_6.jpg',
      ),
      '5' => array(
        'fid' => '11326',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWas_7.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWas_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155439',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWas_7.jpg',
      ),
      '6' => array(
        'fid' => '11327',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWas_8.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWas_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160598',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWas_8.jpg',
      ),
      '7' => array(
        'fid' => '11328',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWas_9.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWas_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17262',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWas_9.jpg',
      ),
      '8' => array(
        'fid' => '11329',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWas_10.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWas_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17385',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWas_10.jpg',
      ),
      '9' => array(
        'fid' => '11330',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWas_11.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWas_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130036',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWas_11.jpg',
      ),
      '10' => array(
        'fid' => '11331',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWas_12.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWas_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '148037',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWas_12.jpg',
      ),
      '11' => array(
        'fid' => '11332',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gettingBackTowhereIWas_13.jpg',
        'filepath' => 'files/fmag_story/2010/Nov/gettingBackTowhereIWas_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17884',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'gettingBackTowhereIWas_13.jpg',
      ),
    ),
    'path' => 'stories/getting-back-where-i-was',
    'tags' => array(
      '5' => array(
        '2461' => array(
          'tid' => '2461',
          'vid' => '5',
          'name' => 'Kristiina Wilson',
          'description' => 'http://www.kristiinawilson.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '158' => array(
          'tid' => '158',
          'vid' => '1',
          'name' => 'LOUIS VUITTON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '159' => array(
          'tid' => '159',
          'vid' => '1',
          'name' => 'PHILLIP LIM',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Kristiina Wilson',
        '1' => 'LOUIS VUITTON, PHILLIP LIM',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
