array(
  array(
    'nid' => '3541',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1291846236',
    'changed' => '1403919164',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3541',
    'revision_uid' => '1',
    'title' => 'Super',
    'body' => '<p>
	Super denim for those made of steel.</p>
<p>
	Exclusive photography by <a href="http://www.michaellohrphotography.com/" target="_blank">MICHAEL LOHR</a>. Video by JASON HART.</p>
<p>
	Model ~ Dustin Duke @ LA Models.</p>
',
    'teaser' => '<p>
	Super denim for those made of steel.</p>
<p>
	Exclusive photography by <a href="http://www.michaellohrphotography.com/" target="_blank">MICHAEL LOHR</a>. Video by JASON HART.</p>
<p>
	Model ~ Dustin Duke @ LA Models.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919164',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.michaellohrphotography.com/" target="_blank">MICHAEL LOHR</a></p>
<p>
	&nbsp;</p>
<p>
	VIDEO<br />
	<a href="http://www.lacasting.com/jasonhart" target="_blank">JASON HART</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	DUSTIN DUKE<br />
	@ LA MODELS</p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.rufskin.com/cart/" target="_blank">RUFSKIN</a></li>
</ul>
<p>
	&nbsp;</p>
<p>
	MUSIC<br />
	VYNAL SYNDICATE<br />
	&amp; APHRODITE</p>
<p>
	&nbsp;</p>
<p>
	LOCATION<br />
	THE HOLLYWOOD LOFT</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11647',
        'list' => '1',
        'data' => array(
          'alt' => '.m4v.m4v.m4v',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super01.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super01_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58822',
        'status' => '1',
        'timestamp' => '1293119784',
        'origname' => 'super01.jpg',
      ),
      '1' => array(
        'fid' => '11648',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super02.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super02.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94764',
        'status' => '1',
        'timestamp' => '1293119819',
        'origname' => 'super02.jpg',
      ),
      '2' => array(
        'fid' => '11649',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super03.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super03.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '147460',
        'status' => '1',
        'timestamp' => '1293119868',
        'origname' => 'super03.jpg',
      ),
      '3' => array(
        'fid' => '11650',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super04.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super04.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92318',
        'status' => '1',
        'timestamp' => '1293119906',
        'origname' => 'super04.jpg',
      ),
      '4' => array(
        'fid' => '11685',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/Layout-1_Page-6_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1293121248',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '11686',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88571',
        'status' => '1',
        'timestamp' => '1293121259',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '11651',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super05.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super05.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1293119998',
        'origname' => 'super05.jpg',
      ),
      '7' => array(
        'fid' => '11652',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super08.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '340600',
        'status' => '1',
        'timestamp' => '1293120017',
        'origname' => 'super08.jpg',
      ),
      '8' => array(
        'fid' => '11653',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super09.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1293120059',
        'origname' => 'super09.jpg',
      ),
      '9' => array(
        'fid' => '11654',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super10.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94207',
        'status' => '1',
        'timestamp' => '1293120068',
        'origname' => 'super10.jpg',
      ),
      '10' => array(
        'fid' => '11655',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super11.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1293120076',
        'origname' => 'super11.jpg',
      ),
      '11' => array(
        'fid' => '11656',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super12.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80395',
        'status' => '1',
        'timestamp' => '1293120087',
        'origname' => 'super12.jpg',
      ),
      '12' => array(
        'fid' => '11657',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super13.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '238904',
        'status' => '1',
        'timestamp' => '1293120128',
        'origname' => 'super13.jpg',
      ),
      '13' => array(
        'fid' => '11658',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super14.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167970',
        'status' => '1',
        'timestamp' => '1293120132',
        'origname' => 'super14.jpg',
      ),
      '14' => array(
        'fid' => '11659',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super15.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20516',
        'status' => '1',
        'timestamp' => '1293120137',
        'origname' => 'super15.jpg',
      ),
      '15' => array(
        'fid' => '11660',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super16.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94021',
        'status' => '1',
        'timestamp' => '1293120145',
        'origname' => 'super16.jpg',
      ),
      '16' => array(
        'fid' => '11661',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super17.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '55439',
        'status' => '1',
        'timestamp' => '1293120153',
        'origname' => 'super17.jpg',
      ),
      '17' => array(
        'fid' => '11662',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super18.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '273480',
        'status' => '1',
        'timestamp' => '1293120163',
        'origname' => 'super18.jpg',
      ),
      '18' => array(
        'fid' => '11678',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-20.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/Layout-1_Page-20.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13432',
        'status' => '1',
        'timestamp' => '1293120882',
        'origname' => 'Layout-1_Page-20.jpg',
      ),
      '19' => array(
        'fid' => '11663',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super20.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super20.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119901',
        'status' => '1',
        'timestamp' => '1293120202',
        'origname' => 'super20.jpg',
      ),
      '20' => array(
        'fid' => '11664',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super21.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super21.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1293120218',
        'origname' => 'super21.jpg',
      ),
      '21' => array(
        'fid' => '11665',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super22.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super22.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129058',
        'status' => '1',
        'timestamp' => '1293120228',
        'origname' => 'super22.jpg',
      ),
      '22' => array(
        'fid' => '11667',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '2010/12/super_hi.m4v mobile:super_lo.m4v',
        ),
        'uid' => '1',
        'filename' => 'super23.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super23_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '345042',
        'status' => '1',
        'timestamp' => '1293120245',
        'origname' => 'super23.jpg',
      ),
      '23' => array(
        'fid' => '11683',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super24.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super24_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '299952',
        'status' => '1',
        'timestamp' => '1293121034',
        'origname' => 'super24.jpg',
      ),
      '24' => array(
        'fid' => '11682',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super23.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super23_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '345042',
        'status' => '1',
        'timestamp' => '1293121009',
        'origname' => 'super23.jpg',
      ),
      '25' => array(
        'fid' => '11669',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super24.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super24_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '299952',
        'status' => '1',
        'timestamp' => '1293120257',
        'origname' => 'super24.jpg',
      ),
      '26' => array(
        'fid' => '11671',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super25.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super25_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1293120266',
        'origname' => 'super25.jpg',
      ),
      '27' => array(
        'fid' => '11672',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super26.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super26.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '205215',
        'status' => '1',
        'timestamp' => '1293120279',
        'origname' => 'super26.jpg',
      ),
      '28' => array(
        'fid' => '11674',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super27.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super27_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '143104',
        'status' => '1',
        'timestamp' => '1293120303',
        'origname' => 'super27.jpg',
      ),
      '29' => array(
        'fid' => '11675',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super28.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super28.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1293120441',
        'origname' => 'super28.jpg',
      ),
      '30' => array(
        'fid' => '11676',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super29.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super29.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1293120468',
        'origname' => 'super29.jpg',
      ),
      '31' => array(
        'fid' => '11677',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'super30.jpg',
        'filepath' => 'files/[type]/[yyyy]/[mon]/super30.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '165957',
        'status' => '1',
        'timestamp' => '1293120483',
        'origname' => 'super30.jpg',
      ),
    ),
    'path' => 'stories/super',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2502' => array(
          'tid' => '2502',
          'vid' => '5',
          'name' => 'Michael Lohr',
          'description' => 'http://www.michaellohrphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '139' => array(
          'tid' => '139',
          'vid' => '1',
          'name' => 'RUFSKIN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '71' => array(
          'tid' => '71',
          'vid' => '1',
          'name' => 'video',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'men',
        '5' => 'Michael Lohr',
        '1' => 'RUFSKIN, video',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
