array(
  array(
    'nid' => '3544',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1292617429',
    'changed' => '1337804929',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3544',
    'revision_uid' => '1',
    'title' => 'Under Current',
    'body' => '<p>
	Under statement.</p>
<p>
	Exclusive photography by <a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a>.</p>
<p>
	Models ~&nbsp; Chris Brew @ Major &amp; Paul Roemer @ City.</p>
',
    'teaser' => '<p>
	Under statement.</p>
<p>
	Exclusive photography by <a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a>.</p>
<p>
	Models ~&nbsp; Chris Brew @ Major &amp; Paul Roemer @ City.</p>
',
    'log' => '',
    'revision_timestamp' => '1337804929',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a></p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	CHRIS BREW<br />
	@ MAJOR<br />
	&amp; PAUL ROEMER<br />
	@ CITY</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		2(x)ist</li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11556',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-2_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140928',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '11635',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-3_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '44233',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '11419',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-4_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '105406',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '11420',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-5_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103577',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '11421',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-6_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '193214',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '11422',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-7_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '49292',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '11423',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-8_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '110895',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '11424',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-9_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132384',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
    ),
    'path' => 'stories/under-current',
    'tags' => array(
      '1' => array(
        '140' => array(
          'tid' => '140',
          'vid' => '1',
          'name' => '2(x)ist',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => array(
            'ext_url' => 'http://www.2xist.com/site/default.asp',
          ),
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2519' => array(
          'tid' => '2519',
          'vid' => '5',
          'name' => 'BILLY WINTERS',
          'description' => 'http://www.billywinters.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => '2(x)ist',
        '5' => 'BILLY WINTERS',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
