array(
  array(
    'nid' => '3547',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1291988316',
    'changed' => '1403919362',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3547',
    'revision_uid' => '1',
    'title' => 'Exotica',
    'body' => '<p>
	Exotique baby.</p>
<p>
	Exclusive photography by <a href="http://www.christophersims.com/" target="_blank">Christopher Sims</a>.</p>
<p>
	Models ~&nbsp; Betty Adewole &amp; Gabriella @ Models1 &amp; Oreintha Russell &amp; Mariam Ogunsanya @ D1.</p>
',
    'teaser' => '<p>
	Exotique baby.</p>
<p>
	Exclusive photography by <a href="http://www.christophersims.com/" target="_blank">Christopher Sims</a>.</p>
<p>
	Models ~&nbsp; Betty Adewole &amp; Gabriella @ Models1 &amp; Oreintha Russell &amp; Mariam Ogunsanya @ D1.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919362',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.christophersims.com/" target="_blank">Christopher Sims</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	STYLING<br />
	SAMSON SOBOYE</p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODELS<br />
	BETTY ADEWOLE<br />
	&amp; GABRIELLA<br />
	@ MODELS1<br />
	OREINTHA RUSSELL<br />
	&amp; MARIAM OGUNSANYA<br />
	@ D1</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.bryce-danice-aime.com/" target="_blank">BRYCE AIME</a></li>
	<li>
		<a href="http://www.littleshilpa.com/" target="_blank">LITTLE SHILPA</a></li>
	<li>
		<a href="http://www.lapetitesalope.com/" target="_blank">LA PETITE S*****</a></li>
	<li>
		<a href="http://www.unconditional.uk.com/" target="_blank">UNCONDITIONAL</a></li>
	<li>
		<a href="http://www.soboyesoong.com/" target="_blank">JLYNCH</a></li>
	<li>
		<a href="http://www.bernardchandran.com/" target="_blank">BERNARD CHANDRAN</a></li>
	<li>
		<a href="http://www.fionapaxton.com/" target="_blank">FIONA PAXTON</a></li>
	<li>
		<a href="http://dereklawlor.com/" target="_blank">DEREK LAWLOR </a></li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11446',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-16_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103949',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '1' => array(
        'fid' => '11447',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-17_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '99321',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '2' => array(
        'fid' => '11434',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-4_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108434',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '11435',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '21180',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '11436',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-6_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18468',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '11437',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-7_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116613',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '11438',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-8_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '47049',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '11439',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-9_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102462',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '11440',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-10_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17677',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '11441',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-11_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102815',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '11442',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-12_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82413',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '11443',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-13_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18634',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '11444',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-14_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '62484',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '11445',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-15_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19477',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
    ),
    'path' => 'stories/exotica-0',
    'tags' => array(
      '1' => array(
        '152' => array(
          'tid' => '152',
          'vid' => '1',
          'name' => 'BERNARD CHANDRAN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '147' => array(
          'tid' => '147',
          'vid' => '1',
          'name' => 'BRYCE AIME',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '154' => array(
          'tid' => '154',
          'vid' => '1',
          'name' => 'DEREK LAWLOR',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '153' => array(
          'tid' => '153',
          'vid' => '1',
          'name' => 'FIONA PAXTON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '151' => array(
          'tid' => '151',
          'vid' => '1',
          'name' => 'JLYNCH',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '149' => array(
          'tid' => '149',
          'vid' => '1',
          'name' => 'LA PETITE S*****',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '148' => array(
          'tid' => '148',
          'vid' => '1',
          'name' => 'LITTLE SHILPA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '150' => array(
          'tid' => '150',
          'vid' => '1',
          'name' => 'UNCONDITIONAL',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2523' => array(
          'tid' => '2523',
          'vid' => '5',
          'name' => 'Christopher Sims',
          'description' => 'http://christophersims.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'BERNARD CHANDRAN, BRYCE AIME, DEREK LAWLOR, FIONA PAXTON, JLYNCH, LA PETITE S*****, LITTLE SHILPA, UNCONDITIONAL',
        '5' => 'Christopher Sims',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
