array(
  array(
    'nid' => '3551',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1292435826',
    'changed' => '1403919362',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3551',
    'revision_uid' => '1',
    'title' => 'Viva Brisvegas',
    'body' => '<p>
	Brisbane? You bet.</p>
<p>
	Exclusive photography by <a href="http://www.thorelias.com/" target="_blank">THOR ELIAS</a>.</p>
<p>
	Model ~&nbsp; Caitlin Lomax @ Scene.</p>
',
    'teaser' => '<p>
	Brisbane? You bet.</p>
<p>
	Exclusive photography by <a href="http://www.thorelias.com/" target="_blank">THOR ELIAS</a>.</p>
<p>
	Model ~&nbsp; Caitlin Lomax @ Scene.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919362',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.thorelias.com/" target="_blank">THOR ELIAS</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	FASHION EDITOR<br />
	<a href="http://www.amberrenae.com/" target="_blank">AMBER RENAE</a></p>
<p>
	&nbsp;</p>
<p>
	<br />
	MODEL<br />
	CAITLIN LOMAX<br />
	@ SCENE</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.talulah.com.au/" target="_blank">Talulah</a></li>
	<li>
		<a href="http://www.ginakim.swappler.com/" target="_blank">Gina Kim</a></li>
	<li>
		<a href="http://www.chelseadeluca.com.au/" target="_blank">Chelsea de luca</a></li>
	<li>
		<a href="http://www.nat-sui.com.au/" target="_blank">Nat-sui</a></li>
	<li>
		<a href="http://www.blancanddelta.com/" target="_blank">blanc and delta</a></li>
	<li>
		<a href="http://www.neonheartache.com.au/" target="_blank">neon heartache</a></li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11477',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-2_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '310209',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '11478',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-3_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98382',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '11479',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-4_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112117',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '11480',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-5_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91524',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '11481',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-6_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94965',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '11482',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-7_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16441',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '11483',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-8_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104838',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '11484',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-9_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96708',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '11485',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-10_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138772',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '11486',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-11_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '224098',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '11487',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-12_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13371',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '11488',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-13_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '192929',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '11489',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-14_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '152125',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '11490',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-15_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98489',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '11491',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-16_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130900',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '11492',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-17_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109325',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '16' => array(
        'fid' => '11493',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-18_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15965',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
      '17' => array(
        'fid' => '11494',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-19.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-19_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '125013',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-19.jpg',
      ),
    ),
    'path' => 'stories/viva-brisvegas',
    'tags' => array(
      '1' => array(
        '145' => array(
          'tid' => '145',
          'vid' => '1',
          'name' => 'blanc and delta',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '143' => array(
          'tid' => '143',
          'vid' => '1',
          'name' => 'Chelsea de luca',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '142' => array(
          'tid' => '142',
          'vid' => '1',
          'name' => 'Gina Kim',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '144' => array(
          'tid' => '144',
          'vid' => '1',
          'name' => 'Nat-sui',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '146' => array(
          'tid' => '146',
          'vid' => '1',
          'name' => 'neon heartache',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '141' => array(
          'tid' => '141',
          'vid' => '1',
          'name' => 'Talulah',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2604' => array(
          'tid' => '2604',
          'vid' => '5',
          'name' => 'THOR ELIAS',
          'description' => 'http://www.thorelias.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'blanc and delta, Chelsea de luca, Gina Kim, Nat-sui, neon heartache, Talulah',
        '5' => 'THOR ELIAS',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
