array(
  array(
    'nid' => '3564',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1293662093',
    'changed' => '1403919164',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3564',
    'revision_uid' => '1',
    'title' => 'Sharpen Up',
    'body' => '<p>
	Sharp dressed men.</p>
<p>
	Exclusive photography by Evan Gunville</p>
<p>
	Models ~&nbsp; Joshua Brisbane @ The Agency</p>
<p>
	&amp; Channce Condit @ Frod/RBA.</p>
',
    'teaser' => '<p>
	Sharp dressed men.</p>
<p>
	Exclusive photography by Evan Gunville</p>
<p>
	Models ~&nbsp; Joshua Brisbane @ The Agency</p>
<p>
	&amp; Channce Condit @ Frod/RBA.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919164',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	EVAN GUNVILLE</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	JOSHUA BRISBANE<br />
	@ THE AGENCY<br />
	CHANNCE CONDIT<br />
	@ FORD/RBA</p>
<p>
	&nbsp;</p>
<p>
	<br />
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.dolcegabbana.com/" target="_blank">DOLCE &amp; GABBANA</a></li>
	<li>
		<a href="http://www.johnvarvatos.com/" target="_blank">JOHN VARVATOS</a></li>
	<li>
		<a href="http://www.hugoboss.com/" target="_blank">HUGO BOSS</a></li>
	<li>
		<a href="http://www.bonachatresale.com/" target="_blank">BON ACHAT</a></li>
	<li>
		<a href="http://shop.nordstrom.com/" target="_blank">NORDSTROM</a></li>
</ul>
<ul>
	<br />
	<br />
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '11694',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2_10.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-2_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '351770',
        'status' => '1',
        'timestamp' => '1293669354',
        'origname' => 'Layout-1_Page-2_10.jpg',
      ),
      '1' => array(
        'fid' => '11695',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3_8.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-3_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '381319',
        'status' => '1',
        'timestamp' => '1293669427',
        'origname' => 'Layout-1_Page-3_8.jpg',
      ),
      '2' => array(
        'fid' => '11600',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-4_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '164943',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '11601',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-5_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14463',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '11602',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-6_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122025',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '11603',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-7_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '170645',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '11604',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-8_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '171096',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '11605',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-9_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130076',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '11606',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-10_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '220230',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '11607',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-11_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '168537',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '11608',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-12_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118842',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '11609',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-13_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '41441',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '11610',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-14_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '175069',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '11611',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-15_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '178816',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
      '14' => array(
        'fid' => '11612',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-16.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-16_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82332',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-16.jpg',
      ),
      '15' => array(
        'fid' => '11613',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-17.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-17_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79444',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-17.jpg',
      ),
      '16' => array(
        'fid' => '11614',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-18.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-18_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '188480',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-18.jpg',
      ),
      '17' => array(
        'fid' => '11615',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-19.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-19_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173602',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-19.jpg',
      ),
      '18' => array(
        'fid' => '11616',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-20.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-20_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14463',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-20.jpg',
      ),
      '19' => array(
        'fid' => '11617',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-21.jpg',
        'filepath' => 'files/fmag_story/2010/Dec/Layout-1_Page-21_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160438',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-21.jpg',
      ),
    ),
    'path' => 'stories/sharpen',
    'tags' => array(
      '1' => array(
        '84' => array(
          'tid' => '84',
          'vid' => '1',
          'name' => 'BON ACHAT',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '81' => array(
          'tid' => '81',
          'vid' => '1',
          'name' => 'DOLCE & GABBANA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '83' => array(
          'tid' => '83',
          'vid' => '1',
          'name' => 'HUGO BOSS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '82' => array(
          'tid' => '82',
          'vid' => '1',
          'name' => 'JOHN VARVATOS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '85' => array(
          'tid' => '85',
          'vid' => '1',
          'name' => 'NORDSTROM',
          'description' => '<a href="http://rstyle.me/n/s82pukw">nordstrom.com</a>',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => array(
            'ext_url' => '',
          ),
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2567' => array(
          'tid' => '2567',
          'vid' => '5',
          'name' => 'EVAN GUNVILLE',
          'description' => 'http://www.evangunville.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'BON ACHAT, DOLCE & GABBANA, HUGO BOSS, JOHN VARVATOS, NORDSTROM',
        '5' => 'EVAN GUNVILLE',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
