array(
  array(
    'nid' => '2774',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1234993461',
    'changed' => '1403919984',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2774',
    'revision_uid' => '1',
    'title' => 'Cool Factor',
    'body' => '<p>
	It&#39;s February dude! Put on a sweater.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.lindsaylozon.com/" target="_blank">Lindsay Lozon.</a></p>
<p>
	<br />
	Models ~ Mitchell Carnie; Taras &amp; Ronnie @&nbsp; <a href="http://www.elmerolsenmodels.com/" target="_blank">ELMER OLSEN.</a></p>
',
    'teaser' => '<p>
	It&#39;s February dude! Put on a sweater.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.lindsaylozon.com/" target="_blank">Lindsay Lozon.</a></p>
<p>
	<br />
	Models ~ Mitchell Carnie; Taras &amp; Ronnie @&nbsp; <a href="http://www.elmerolsenmodels.com/" target="_blank">ELMER OLSEN.</a></p>
',
    'log' => '',
    'revision_timestamp' => '1403919984',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.lindsaylozon.com/" target="_blank">Lindsay Lozon</a></p>
<p>
	MODELS<br />
	MITCHELL<br />
	TARAS &amp; RONNIE @ <a href="http://www.elmerolsenmodels.com/" target="_blank">ELMER OLSEN</a></p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.hm.com" target="_blank">H&amp;M</a></li>
	<li>
		<a href="http://www.uniqlo.com/us/" target="_blank">UNIQLO</a></li>
	<li>
		<a href="http://www.gap.com/" target="_blank">GAP</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '3010',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool_feb09_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '59134',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool_feb09.jpg',
      ),
      '1' => array(
        'fid' => '3011',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool2_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool2_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '169608',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool2_feb09.jpg',
      ),
      '2' => array(
        'fid' => '3013',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool3_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool3_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '175466',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool3_feb09.jpg',
      ),
      '3' => array(
        'fid' => '3014',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool4_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool4_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78278',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool4_feb09.jpg',
      ),
      '4' => array(
        'fid' => '2996',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool5_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool5_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '254963',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool5_feb09.jpg',
      ),
      '5' => array(
        'fid' => '2997',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool6_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool6_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '233809',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool6_feb09.jpg',
      ),
      '6' => array(
        'fid' => '2998',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool7_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool7_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15852',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool7_feb09.jpg',
      ),
      '7' => array(
        'fid' => '2999',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool8_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool8_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '276199',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool8_feb09.jpg',
      ),
      '8' => array(
        'fid' => '3000',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool9_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool9_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102812',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool9_feb09.jpg',
      ),
      '9' => array(
        'fid' => '3001',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool10_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool10_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98969',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool10_feb09.jpg',
      ),
      '10' => array(
        'fid' => '3002',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool11_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool11_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '62970',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool11_feb09.jpg',
      ),
      '11' => array(
        'fid' => '3003',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool12_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool12_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '245200',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool12_feb09.jpg',
      ),
      '12' => array(
        'fid' => '3004',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool13_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool13_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106337',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool13_feb09.jpg',
      ),
      '13' => array(
        'fid' => '3005',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool14_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool14_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '240631',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool14_feb09.jpg',
      ),
      '14' => array(
        'fid' => '3006',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool15_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool15_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '233162',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool15_feb09.jpg',
      ),
      '15' => array(
        'fid' => '3007',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool16_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool16_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '28212',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool16_feb09.jpg',
      ),
      '16' => array(
        'fid' => '3009',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool18_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool18_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '194947',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool18_feb09.jpg',
      ),
      '17' => array(
        'fid' => '3015',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'cool17_feb09.jpg',
        'filepath' => 'files/fmag_story/2009/Feb/cool17_feb09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '182522',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'cool17_feb09.jpg',
      ),
    ),
    'path' => 'stories/cool-factor',
    'tags' => array(
      '5' => array(
        '2417' => array(
          'tid' => '2417',
          'vid' => '5',
          'name' => 'Lindsay Lozon',
          'description' => 'http://www.lindsaylozon.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '62' => array(
          'tid' => '62',
          'vid' => '1',
          'name' => 'lindsay lozon fantasticsmag',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '63' => array(
          'tid' => '63',
          'vid' => '1',
          'name' => 'lindsay lozon sweaters fantasticsmag',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Lindsay Lozon',
        '1' => 'lindsay lozon fantasticsmag, lindsay lozon sweaters fantasticsmag',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
