array(
  array(
    'nid' => '2789',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1236207457',
    'changed' => '1337806336',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2789',
    'revision_uid' => '1',
    'title' => 'Nightclubbing',
    'body' => '<p>
	Hmmm.... what should I wear tonight?</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.laurarosephotography.com/" target="_blank">Laura Rose</a>.</p>
<p>
	<br />
	Model ~ Yulia @ <a href="http://www.marilynagency.com/" target="_blank">MARILYN</a>.</p>
',
    'teaser' => '<p>
	Hmmm.... what should I wear tonight?</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.laurarosephotography.com/" target="_blank">Laura Rose</a>.</p>
<p>
	<br />
	Model ~ Yulia @ <a href="http://www.marilynagency.com/" target="_blank">MARILYN</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1337806336',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.laurarosephotography.com/" target="_blank">Laura Rose</a></p>
<p>
	MODEL<br />
	YULIA @ <a href="http://www.marilynagency.com/" target="_blank">MARILYN</a></p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.normakamalicollection.com/" target="_blank">NORMA KAMALI</a></li>
	<li>
		<a href="http://www.naeemkhan.com/" target="_blank">NAEEM KHAN</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '3169',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97412',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night_mar09.jpg',
      ),
      '1' => array(
        'fid' => '3188',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night2_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night2_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96204',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night2_mar09.jpg',
      ),
      '2' => array(
        'fid' => '3171',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night3_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night3_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95605',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night3_mar09.jpg',
      ),
      '3' => array(
        'fid' => '3172',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night4_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night4_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91340',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night4_mar09.jpg',
      ),
      '4' => array(
        'fid' => '3173',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night5_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night5_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '45986',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night5_mar09.jpg',
      ),
      '5' => array(
        'fid' => '3174',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night6_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night6_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92494',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night6_mar09.jpg',
      ),
      '6' => array(
        'fid' => '3175',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night7_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night7_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18626',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night7_mar09.jpg',
      ),
      '7' => array(
        'fid' => '3176',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night8_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night8_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85864',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night8_mar09.jpg',
      ),
      '8' => array(
        'fid' => '3177',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night9_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night9_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '148131',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night9_mar09.jpg',
      ),
      '9' => array(
        'fid' => '3178',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night10_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night10_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19317',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night10_mar09.jpg',
      ),
      '10' => array(
        'fid' => '3179',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night11_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night11_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '37762',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night11_mar09.jpg',
      ),
      '11' => array(
        'fid' => '3180',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night12_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night12_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '59925',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night12_mar09.jpg',
      ),
      '12' => array(
        'fid' => '3182',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night13_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night13_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154275',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night13_mar09.jpg',
      ),
      '13' => array(
        'fid' => '3181',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night14_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night14_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158324',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night14_mar09.jpg',
      ),
      '14' => array(
        'fid' => '3183',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night15_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night15_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19368',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night15_mar09.jpg',
      ),
      '15' => array(
        'fid' => '3184',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night16_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night16_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66995',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night16_mar09.jpg',
      ),
      '16' => array(
        'fid' => '3185',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night17_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night17_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91243',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night17_mar09.jpg',
      ),
      '17' => array(
        'fid' => '3186',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'night18_mar09.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/night18_mar09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109791',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'night18_mar09.jpg',
      ),
    ),
    'path' => 'stories/nightclubbing',
    'tags' => array(
      '5' => array(
        '2472' => array(
          'tid' => '2472',
          'vid' => '5',
          'name' => 'Laura Rose',
          'description' => 'http://www.laurarosephotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Laura Rose',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
