array(
  array(
    'nid' => '2796',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1236634738',
    'changed' => '1337806285',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2796',
    'revision_uid' => '1',
    'title' => 'A Paralysis of Nostalgia',
    'body' => '<p>
	Memories can&#39;t wait.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.troymoth.com/" target="_blank">Troy moth.</a></p>
<p>
	Model ~Kira @ <a href="http://www.elmerolsenmodels.com/" target="_blank">ELmer olsen</a>.</p>
',
    'teaser' => '<p>
	Memories can&#39;t wait.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.troymoth.com/" target="_blank">Troy moth.</a></p>
<p>
	Model ~Kira @ <a href="http://www.elmerolsenmodels.com/" target="_blank">ELmer olsen</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1337806285',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.troymoth.com/" target="_blank">Troy moth</a></p>
<p>
	MODEL<br />
	KIRA<br />
	@&nbsp;<a href="http://www.elmerolsenmodels.com/" target="_blank">ELmer olsen</a></p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		ANIKA</li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '3248',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '145843',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '3249',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67249',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '3250',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65567',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '3251',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132529',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '3256',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88721',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '5' => array(
        'fid' => '3257',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '64837',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '6' => array(
        'fid' => '3252',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134827',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '7' => array(
        'fid' => '3253',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '148089',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '8' => array(
        'fid' => '3258',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122470',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '3259',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '51971',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '3260',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136254',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '3261',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '186665',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '3255',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '175222',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '3254',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2009/Mar/Layout-1_Page-15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97282',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
    ),
    'path' => 'stories/paralysis-nostalgia',
    'tags' => array(
      '5' => array(
        '2462' => array(
          'tid' => '2462',
          'vid' => '5',
          'name' => 'Troy moth',
          'description' => 'http://www.troymoth.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '1' => '1',
      ),
      'tags' => array(
        '5' => 'Troy moth',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
