array(
  array(
    'nid' => '2814',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1238604373',
    'changed' => '1288899100',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2814',
    'revision_uid' => '1',
    'title' => 'Even Redheads Get the Blues',
    'body' => '<p>Indeed they do.</p>
<p><br />Exclusive photography by <a target="_blank" href="http://www.matthewlyn.com/">MATTHEW LYN.</a></p>
<p><br />Models ~ Holland @ <a target="_blank" href="http://majorwomen.blogspot.com/">MAJOR.</a></p>',
    'teaser' => '<p>Indeed they do.</p>
<p><br />Exclusive photography by <a target="_blank" href="http://www.matthewlyn.com/">MATTHEW LYN.</a></p>
<p><br />Models ~ Holland @ <a target="_blank" href="http://majorwomen.blogspot.com/">MAJOR.</a></p>',
    'log' => '',
    'revision_timestamp' => '1288899100',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p> </p>
<p>PHOTOGRAPHY<br /><a target="_blank" href="http://www.matthewlyn.com/">MATTHEW LYN</a></p>
<p> </p>
<p>MODEL<br />HOLLAND @ <a target="_blank" href="http://majorwomen.blogspot.com/">MAJOR</a></p>
<p> </p>
<p>FEATURED FASHION</p>
<ul>
<li><a target="_blank" href="http://www.bebe.com/">BEBE</a></li>
<li><a target="_self" href="http://www.urbanoutfitters.com">URBAN OUTFITTTERS</a></li>
</ul>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '3459',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'even_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/even_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '228664',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'even_APR09.jpg',
      ),
      '1' => array(
        'fid' => '3460',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'even2_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/even2_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78974',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'even2_APR09.jpg',
      ),
      '2' => array(
        'fid' => '3461',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'even3_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/even3_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17204',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'even3_APR09.jpg',
      ),
      '3' => array(
        'fid' => '3462',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'even4_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/even4_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '204690',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'even4_APR09.jpg',
      ),
      '4' => array(
        'fid' => '3463',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'even5_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/even5_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139944',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'even5_APR09.jpg',
      ),
      '5' => array(
        'fid' => '3464',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'even6_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/even6_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155686',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'even6_APR09.jpg',
      ),
      '6' => array(
        'fid' => '3465',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'even7_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/even7_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '121696',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'even7_APR09.jpg',
      ),
      '7' => array(
        'fid' => '3466',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'even8_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/even8_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118219',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'even8_APR09.jpg',
      ),
    ),
    'path' => 'stories/even-redheads-get-blues',
    'tags' => array(
      '5' => array(
        '2466' => array(
          'tid' => '2466',
          'vid' => '5',
          'name' => 'MAGDALENA M',
          'description' => 'http://www.dripbook.com/MagdalenaM/book/fashion-1/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'MAGDALENA M',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
