array(
  array(
    'nid' => '2818',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1238978407',
    'changed' => '1337806242',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2818',
    'revision_uid' => '1',
    'title' => 'Wonder Where',
    'body' => '<p>
	Wonder where? Wonder wear.</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.luciehugary.com" target="_self">LUCIE HUGARY</a><a href="http://www.matthewlyn.com/" target="_blank">.</a></p>
<p>
	<br />
	Models ~ Robin Linke @ 301 Models.</p>
',
    'teaser' => '<p>
	Wonder where? Wonder wear.</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.luciehugary.com" target="_self">LUCIE HUGARY</a><a href="http://www.matthewlyn.com/" target="_blank">.</a></p>
<p>
	<br />
	Models ~ Robin Linke @ 301 Models.</p>
',
    'log' => '',
    'revision_timestamp' => '1337806242',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.luciehugary.com" target="_self">LUCIE HUGARY</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	ROBIN LINKE<br />
	@ 301 MODELS</p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<div>
	&nbsp;</div>
<ul>
	<li>
		<a href="http://www.zara.com/" target="_self">ZARA</a></li>
	<li>
		<a href="http://www.bebe.com/" target="_self">BEBE</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '3497',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118898',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder_APR09.jpg',
      ),
      '1' => array(
        'fid' => '3498',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder2_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder2_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153469',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder2_APR09.jpg',
      ),
      '2' => array(
        'fid' => '3500',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder3_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder3_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '351437',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder3_APR09.jpg',
      ),
      '3' => array(
        'fid' => '3499',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder4_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder4_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '211524',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder4_APR09.jpg',
      ),
      '4' => array(
        'fid' => '3501',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder5_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder5_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1438041',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder5_APR09.jpg',
      ),
      '5' => array(
        'fid' => '3502',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder6_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder6_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '26736',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder6_APR09.jpg',
      ),
      '6' => array(
        'fid' => '3503',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder7_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder7_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '311756',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder7_APR09.jpg',
      ),
      '7' => array(
        'fid' => '3504',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder8_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder8_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '240256',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder8_APR09.jpg',
      ),
      '8' => array(
        'fid' => '3505',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder9_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder9_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '259240',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder9_APR09.jpg',
      ),
      '9' => array(
        'fid' => '3506',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder10_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder10_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '293750',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder10_APR09.jpg',
      ),
      '10' => array(
        'fid' => '3510',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder11_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder11_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22818',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder11_APR09.jpg',
      ),
      '11' => array(
        'fid' => '3507',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder12_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder12_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '228971',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder12_APR09.jpg',
      ),
      '12' => array(
        'fid' => '3508',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder13_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder13_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '220160',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder13_APR09.jpg',
      ),
      '13' => array(
        'fid' => '3509',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'wonder14_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/wonder14_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '178191',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'wonder14_APR09.jpg',
      ),
    ),
    'path' => 'stories/wonder-where',
    'tags' => array(
      '5' => array(
        '2466' => array(
          'tid' => '2466',
          'vid' => '5',
          'name' => 'MAGDALENA M',
          'description' => 'http://www.dripbook.com/MagdalenaM/book/fashion-1/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'MAGDALENA M',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
