array(
  array(
    'nid' => '2819',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1239229635',
    'changed' => '1337806219',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2819',
    'revision_uid' => '1',
    'title' => 'Bound and Determined',
    'body' => '<p>
	Tied to your looks?</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.kristiinawilson.com/" target="_blank">KRISTIINA WILSON</a>.</p>
<p>
	<br />
	Model ~ Jules @ <a href="http://www.onemanagement.com/" target="_blank">One</a>.</p>
',
    'teaser' => '<p>
	Tied to your looks?</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.kristiinawilson.com/" target="_blank">KRISTIINA WILSON</a>.</p>
<p>
	<br />
	Model ~ Jules @ <a href="http://www.onemanagement.com/" target="_blank">One</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1337806219',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.kristiinawilson.com/" target="_blank">KRISTIINA WILSON</a></p>
<p>
	MODEL</p>
<p>
	JULES<br />
	@ <a href="http://www.onemanagement.com/" target="_blank">One</a></p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://alexisbittar.com/home.php" target="_blank">alexis bittar</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '3511',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bound_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/bound_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73532',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bound_APR09.jpg',
      ),
      '1' => array(
        'fid' => '3512',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bound2_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/bound2_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61724',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bound2_APR09.jpg',
      ),
      '2' => array(
        'fid' => '3513',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bound3_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/bound3_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102200',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bound3_APR09.jpg',
      ),
      '3' => array(
        'fid' => '3514',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bound4_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/bound4_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75708',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bound4_APR09.jpg',
      ),
      '4' => array(
        'fid' => '3515',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bound5_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/bound5_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108505',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bound5_APR09.jpg',
      ),
      '5' => array(
        'fid' => '3516',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bound6_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/bound6_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '145969',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bound6_APR09.jpg',
      ),
    ),
    'path' => 'stories/bound-and-determined',
    'tags' => array(
      '5' => array(
        '2461' => array(
          'tid' => '2461',
          'vid' => '5',
          'name' => 'Kristiina Wilson',
          'description' => 'http://www.kristiinawilson.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Kristiina Wilson',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
