array(
  array(
    'nid' => '2825',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1239885920',
    'changed' => '1337806259',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2825',
    'revision_uid' => '1',
    'title' => 'Guy From Bed Stuy',
    'body' => '<p>
	Just another day in the neighbourhood.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.dmwphoto.com/" target="_blank">DAVID MATTHEW WALTERS.</a><http:> </http:></p>
<p>
	<br />
	Model ~ Artem @ <a href="http://rednyc.com/">RED.</a></p>
',
    'teaser' => '<p>
	Just another day in the neighbourhood.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.dmwphoto.com/" target="_blank">DAVID MATTHEW WALTERS.</a><http:> </http:></p>
<p>
	<br />
	Model ~ Artem @ <a href="http://rednyc.com/">RED.</a></p>
',
    'log' => '',
    'revision_timestamp' => '1337806259',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.dmwphoto.com/" target="_blank">DAVID MATTHEW WALTERS</a></p>
<p>
	MODEL<br />
	ARTEM @ <a href="http://rednyc.com/">RED</a></p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.calvinkleininc.com/" target="_blank">COSA NOSTRA</a></li>
	<li>
		<a href="http://rockandrepublic.com" target="_blank">rock and republic</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '3592',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BEDSTUY_apr09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/BEDSTUY_apr09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '37014',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BEDSTUY_apr09.jpg',
      ),
      '1' => array(
        'fid' => '3593',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BEDSTUY2_apr09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/BEDSTUY2_apr09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '234021',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BEDSTUY2_apr09.jpg',
      ),
      '2' => array(
        'fid' => '3594',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BEDSTUY3_apr09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/BEDSTUY3_apr09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '43849',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BEDSTUY3_apr09.jpg',
      ),
      '3' => array(
        'fid' => '3595',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BEDSTUY4_apr09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/BEDSTUY4_apr09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126256',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BEDSTUY4_apr09.jpg',
      ),
      '4' => array(
        'fid' => '3596',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BEDSTUY5_apr09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/BEDSTUY5_apr09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '203668',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BEDSTUY5_apr09.jpg',
      ),
      '5' => array(
        'fid' => '3597',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BEDSTUY6_apr09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/BEDSTUY6_apr09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '147908',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BEDSTUY6_apr09.jpg',
      ),
      '6' => array(
        'fid' => '3598',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BEDSTUY7_apr09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/BEDSTUY7_apr09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158519',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BEDSTUY7_apr09.jpg',
      ),
      '7' => array(
        'fid' => '3599',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BEDSTUY8_apr09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/BEDSTUY8_apr09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139202',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BEDSTUY8_apr09.jpg',
      ),
      '8' => array(
        'fid' => '3600',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BEDSTUY9_apr09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/BEDSTUY9_apr09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '323141',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BEDSTUY9_apr09.jpg',
      ),
      '9' => array(
        'fid' => '3601',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BEDSTUY10_apr09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/BEDSTUY10_apr09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '152265',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BEDSTUY10_apr09.jpg',
      ),
    ),
    'path' => 'stories/guy-bed-stuy',
    'tags' => array(
      '5' => array(
        '2475' => array(
          'tid' => '2475',
          'vid' => '5',
          'name' => 'DAVID MATTHEW WALTERS',
          'description' => 'http://www.dmwphoto.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'DAVID MATTHEW WALTERS',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
