array(
  array(
    'nid' => '2830',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1241182798',
    'changed' => '1337806141',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2830',
    'revision_uid' => '1',
    'title' => 'When the Blooms of Love Fade',
    'body' => '<p>
	Innocence dies; villian is born.</p>
<p>
	<br />
	Exclusive photography by <a href="http://arkanphoto.com/">Arkan Zaharov</a>.</p>
<p>
	<br />
	Model ~ Michael Wilcox @ <a href="http://www.elmerolsenmodels.com/">ELMER OLSEN</a>.</p>
',
    'teaser' => '<p>
	Innocence dies; villian is born.</p>
<p>
	<br />
	Exclusive photography by <a href="http://arkanphoto.com/">Arkan Zaharov</a>.</p>
<p>
	<br />
	Model ~ Michael Wilcox @ <a href="http://www.elmerolsenmodels.com/">ELMER OLSEN</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1337806141',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://arkanphoto.com/">Arkan Zaharov</a></p>
<p>
	MODEL<br />
	MICHAEL WILCOX<br />
	@ <a href="http://www.elmerolsenmodels.com/">ELMER OLSEN</a>.</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.adidas.com/" target="_blank">ADIDAS</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '3663',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104086',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms_APR09.jpg',
      ),
      '1' => array(
        'fid' => '3664',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms2_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms2_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61615',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms2_APR09.jpg',
      ),
      '2' => array(
        'fid' => '3665',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms3_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms3_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89901',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms3_APR09.jpg',
      ),
      '3' => array(
        'fid' => '3666',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms4_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms4_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17981',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms4_APR09.jpg',
      ),
      '4' => array(
        'fid' => '3667',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms5_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms5_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18406',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms5_APR09.jpg',
      ),
      '5' => array(
        'fid' => '3668',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms6_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms6_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130898',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms6_APR09.jpg',
      ),
      '6' => array(
        'fid' => '3669',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms7_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms7_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87255',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms7_APR09.jpg',
      ),
      '7' => array(
        'fid' => '3670',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms8_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms8_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16486',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms8_APR09.jpg',
      ),
      '8' => array(
        'fid' => '3671',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms9_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms9_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '26072',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms9_APR09.jpg',
      ),
      '9' => array(
        'fid' => '3672',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms10_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms10_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58106',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms10_APR09.jpg',
      ),
      '10' => array(
        'fid' => '3673',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms11_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms11_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '69351',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms11_APR09.jpg',
      ),
      '11' => array(
        'fid' => '3674',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms12_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms12_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16248',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms12_APR09.jpg',
      ),
      '12' => array(
        'fid' => '3675',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms13_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms13_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '30343',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms13_APR09.jpg',
      ),
      '13' => array(
        'fid' => '3676',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms14_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms14_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108397',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms14_APR09.jpg',
      ),
      '14' => array(
        'fid' => '3677',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms15_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms15_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73800',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms15_APR09.jpg',
      ),
      '15' => array(
        'fid' => '3678',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms16_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms16_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16955',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms16_APR09.jpg',
      ),
      '16' => array(
        'fid' => '3679',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms17_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms17_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13414',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms17_APR09.jpg',
      ),
      '17' => array(
        'fid' => '3680',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blooms18_APR09.jpg',
        'filepath' => 'files/fmag_story/2009/Apr/blooms18_APR09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78157',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blooms18_APR09.jpg',
      ),
    ),
    'path' => 'stories/when-blooms-love-fade',
    'tags' => array(
      '5' => array(
        '2425' => array(
          'tid' => '2425',
          'vid' => '5',
          'name' => 'Arkan Zaharov',
          'description' => 'http://arkanphoto.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Arkan Zaharov',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
