array(
  array(
    'nid' => '2857',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1244230406',
    'changed' => '1337805869',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2857',
    'revision_uid' => '1',
    'title' => 'Theres Something in the Air',
    'body' => '<p>
	Air it out.</p>
<p>
	Exclusive photography by&nbsp;<a href="http://www.matthewlyn.com/">MATTHEW LYN.</a></p>
<p>
	Model ~ Darius @&nbsp;<a href="http://www.dnamodels.com/">DNA</a>.</p>
',
    'teaser' => '<p>
	Air it out.</p>
<p>
	Exclusive photography by&nbsp;<a href="http://www.matthewlyn.com/">MATTHEW LYN.</a></p>
<p>
	Model ~ Darius @&nbsp;<a href="http://www.dnamodels.com/">DNA</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1337805869',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.matthewlyn.com/" target="_blank">MATTHEW LYN</a></p>
<p>
	MODEL<br />
	DARIUS<br />
	@&nbsp;<a href="http://www.dnamodels.com/" target="_blank">DNA</a></p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<div>
	&nbsp;</div>
<ul>
	<li>
		<span style="color: #0000ee; text-decoration: underline;"><a href="http://www.cheapmonday.com/" target="_blank">CHEAP MONDAY</a></span></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '3941',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75145',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something_MAY09.jpg',
      ),
      '1' => array(
        'fid' => '3942',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something2_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something2_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '186539',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something2_MAY09.jpg',
      ),
      '2' => array(
        'fid' => '3943',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something3_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something3_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '175593',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something3_MAY09.jpg',
      ),
      '3' => array(
        'fid' => '3944',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something4_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something4_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161363',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something4_MAY09.jpg',
      ),
      '4' => array(
        'fid' => '3945',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something5_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something5_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '194799',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something5_MAY09.jpg',
      ),
      '5' => array(
        'fid' => '3946',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something6_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something6_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '200669',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something6_MAY09.jpg',
      ),
      '6' => array(
        'fid' => '3947',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something7_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something7_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '234367',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something7_MAY09.jpg',
      ),
      '7' => array(
        'fid' => '3948',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something8_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something8_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '40977',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something8_MAY09.jpg',
      ),
      '8' => array(
        'fid' => '3949',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something9_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something9_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22899',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something9_MAY09.jpg',
      ),
      '9' => array(
        'fid' => '3950',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something10_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something10_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '242881',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something10_MAY09.jpg',
      ),
      '10' => array(
        'fid' => '3951',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something11_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something11_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18637',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something11_MAY09.jpg',
      ),
      '11' => array(
        'fid' => '3952',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something12_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something12_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103199',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something12_MAY09.jpg',
      ),
      '12' => array(
        'fid' => '3953',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something13_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something13_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '166049',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something13_MAY09.jpg',
      ),
      '13' => array(
        'fid' => '3954',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something14_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something14_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13401',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something14_MAY09.jpg',
      ),
      '14' => array(
        'fid' => '3955',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something15_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something15_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20590',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something15_MAY09.jpg',
      ),
      '15' => array(
        'fid' => '3956',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'something16_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/something16_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '64279',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'something16_MAY09.jpg',
      ),
    ),
    'path' => 'stories/theres-something-air',
    'tags' => array(
      '5' => array(
        '2413' => array(
          'tid' => '2413',
          'vid' => '5',
          'name' => 'Matthew Lyn',
          'description' => 'http://www.matthewlyn.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Matthew Lyn',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
