array(
  array(
    'nid' => '2861',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1242764800',
    'changed' => '1337806023',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2861',
    'revision_uid' => '1',
    'title' => 'Shoot Some Pool',
    'body' => '<p>
	Dip into something refreshing.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.matthewlyn.com/" target="_blank">MATTHEW LYN.</a></p>
<p>
	<br />
	Model ~ Drew Van Acker @ <a href="http://www.bleumodels.com/" target="_blank">Bleu</a>.</p>
',
    'teaser' => '<p>
	Dip into something refreshing.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.matthewlyn.com/" target="_blank">MATTHEW LYN.</a></p>
<p>
	<br />
	Model ~ Drew Van Acker @ <a href="http://www.bleumodels.com/" target="_blank">Bleu</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1337806023',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.matthewlyn.com/" target="_blank">MATTHEW LYN</a></p>
<p>
	MODEL<br />
	DREW VAN ACKER<br />
	@ <a href="http://www.bleumodels.com/" target="_blank">Bleu</a></p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.vizeau.com">Vizeau</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '3961',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76018',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool_MAY09.jpg',
      ),
      '1' => array(
        'fid' => '3962',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool2_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool2_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '120964',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool2_MAY09.jpg',
      ),
      '2' => array(
        'fid' => '3963',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool3_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool3_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122935',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool3_MAY09.jpg',
      ),
      '3' => array(
        'fid' => '3964',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool4_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool4_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128476',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool4_MAY09.jpg',
      ),
      '4' => array(
        'fid' => '3965',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool5_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool5_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154583',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool5_MAY09.jpg',
      ),
      '5' => array(
        'fid' => '3966',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool6_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool6_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '164389',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool6_MAY09.jpg',
      ),
      '6' => array(
        'fid' => '3967',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool7_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool7_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122727',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool7_MAY09.jpg',
      ),
      '7' => array(
        'fid' => '3968',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool8_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool8_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129904',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool8_MAY09.jpg',
      ),
      '8' => array(
        'fid' => '3969',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool9_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool9_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104696',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool9_MAY09.jpg',
      ),
      '9' => array(
        'fid' => '3970',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool10_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool10_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117360',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool10_MAY09.jpg',
      ),
      '10' => array(
        'fid' => '3971',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool11_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool11_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104061',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool11_MAY09.jpg',
      ),
      '11' => array(
        'fid' => '3972',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool12_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool12_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167599',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool12_MAY09.jpg',
      ),
      '12' => array(
        'fid' => '3973',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool13_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool13_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '185130',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool13_MAY09.jpg',
      ),
      '13' => array(
        'fid' => '3974',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool14_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool14_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83552',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool14_MAY09.jpg',
      ),
      '14' => array(
        'fid' => '3975',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool15_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool15_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '186915',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool15_MAY09.jpg',
      ),
      '15' => array(
        'fid' => '3976',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool16_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool16_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118092',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool16_MAY09.jpg',
      ),
      '16' => array(
        'fid' => '3977',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool17_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool17_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154835',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool17_MAY09.jpg',
      ),
      '17' => array(
        'fid' => '3978',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pool18_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/pool18_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130848',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pool18_MAY09.jpg',
      ),
    ),
    'path' => 'stories/shoot-some-pool',
    'tags' => array(
      '5' => array(
        '2413' => array(
          'tid' => '2413',
          'vid' => '5',
          'name' => 'Matthew Lyn',
          'description' => 'http://www.matthewlyn.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Matthew Lyn',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
