array(
  array(
    'nid' => '2871',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1243630364',
    'changed' => '1337806002',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2871',
    'revision_uid' => '1',
    'title' => 'Punch Drunk Love',
    'body' => '<p>
	Punch up some color.</p>
<p>
	Exclusive photography by&nbsp;<http:><a href="http://www.marcelaphoto.com " target="_blank">MARCELA MORENO</a>.</http:></p>
<p>
	<br />
	Models ~ Iren Mirror, Lina Caforio<br />
	&amp; Kristian Milatinov&nbsp;@&nbsp;<a href="http://www.flemingmodels.com" target="_blank">FLEMING</a></p>
',
    'teaser' => '<p>
	Punch up some color.</p>
<p>
	Exclusive photography by&nbsp;<http:><a href="http://www.marcelaphoto.com " target="_blank">MARCELA MORENO</a>.</http:></p>
<p>
	<br />
	Models ~ Iren Mirror, Lina Caforio<br />
	&amp; Kristian Milatinov&nbsp;@&nbsp;<a href="http://www.flemingmodels.com" target="_blank">FLEMING</a></p>
',
    'log' => '',
    'revision_timestamp' => '1337806002',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.marcelaphoto.com " target="_blank">MARCELA MORENO</a></p>
<p>
	MODELS</p>
<p>
	IREN MIRROR,<br />
	LINA CAFORIO,<br />
	KRISTIAN MILATINOV<br />
	@ <a href="http://www.flemingmodels.com" target="_blank">FLEMING</a></p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://cult.diesel.com/" target="_blank">DIESEL</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '4119',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '169772',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch_MAY09.jpg',
      ),
      '1' => array(
        'fid' => '4120',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch2_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch2_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '188585',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch2_MAY09.jpg',
      ),
      '2' => array(
        'fid' => '4121',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch3_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch3_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '217758',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch3_MAY09.jpg',
      ),
      '3' => array(
        'fid' => '4122',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch4_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch4_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '202342',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch4_MAY09.jpg',
      ),
      '4' => array(
        'fid' => '4123',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch5_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch5_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '188910',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch5_MAY09.jpg',
      ),
      '5' => array(
        'fid' => '4124',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch6_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch6_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '210637',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch6_MAY09.jpg',
      ),
      '6' => array(
        'fid' => '4125',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch7_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch7_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '305034',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch7_MAY09.jpg',
      ),
      '7' => array(
        'fid' => '4126',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch8_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch8_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '329472',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch8_MAY09.jpg',
      ),
      '8' => array(
        'fid' => '4127',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch9_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch9_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '207235',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch9_MAY09.jpg',
      ),
      '9' => array(
        'fid' => '4128',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch10_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch10_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '261856',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch10_MAY09.jpg',
      ),
      '10' => array(
        'fid' => '4129',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch11_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch11_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '266381',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch11_MAY09.jpg',
      ),
      '11' => array(
        'fid' => '4130',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch12_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch12_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '266507',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch12_MAY09.jpg',
      ),
      '12' => array(
        'fid' => '4131',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch13_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch13_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '325817',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch13_MAY09.jpg',
      ),
      '13' => array(
        'fid' => '4132',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch14_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch14_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '337138',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch14_MAY09.jpg',
      ),
      '14' => array(
        'fid' => '4133',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch15_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch15_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '208297',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch15_MAY09.jpg',
      ),
      '15' => array(
        'fid' => '4134',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'punch16_MAY09.jpg',
        'filepath' => 'files/fmag_story/2009/May/punch16_MAY09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '227350',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'punch16_MAY09.jpg',
      ),
    ),
    'path' => 'stories/punch-drunk-love',
    'tags' => array(
      '5' => array(
        '2486' => array(
          'tid' => '2486',
          'vid' => '5',
          'name' => 'MARCELA MORENO',
          'description' => 'http://www.marcelaphoto.com%20',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'MARCELA MORENO',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
