array(
  array(
    'nid' => '2911',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1247853949',
    'changed' => '1303574333',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2911',
    'revision_uid' => '1',
    'title' => 'The Roommate',
    'body' => '<p>
	That chick down the hall.</p>
<p>
	Exclusive photography by&nbsp; <a href="http://www.matthewstylianou.com/" target="_blank">Matthew Stylianou</a>.</p>
<p>
	Model ~ Kyla @ <a href="http://www.elmerolsenmodels.com/">Elmer Olsen.</a></p>
',
    'teaser' => '<p>
	That chick down the hall.</p>
<p>
	Exclusive photography by&nbsp; <a href="http://www.matthewstylianou.com/" target="_blank">Matthew Stylianou</a>.</p>
<p>
	Model ~ Kyla @ <a href="http://www.elmerolsenmodels.com/">Elmer Olsen.</a></p>
',
    'log' => '',
    'revision_timestamp' => '1303574333',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.matthewstylianou.com/" target="_blank"><span>Matthew Stylianou</span></a></p>
<p>
	MODEL<br />
	KYLA @ <a href="http://www.elmerolsenmodels.com/">Elmer Olsen</a></p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.bensherman.com/" target="_blank">Ben Sherman</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '4687',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158853',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room_JUL09.jpg',
      ),
      '1' => array(
        'fid' => '4688',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room2_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room2_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61079',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room2_JUL09.jpg',
      ),
      '2' => array(
        'fid' => '4689',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room3_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room3_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '37351',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room3_JUL09.jpg',
      ),
      '3' => array(
        'fid' => '4690',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room4_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room4_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131508',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room4_JUL09.jpg',
      ),
      '4' => array(
        'fid' => '4691',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room5_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room5_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18909',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room5_JUL09.jpg',
      ),
      '5' => array(
        'fid' => '4692',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room6_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room6_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154720',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room6_JUL09.jpg',
      ),
      '6' => array(
        'fid' => '4693',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room7_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room7_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '125452',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room7_JUL09.jpg',
      ),
      '7' => array(
        'fid' => '4694',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room8_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room8_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20970',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room8_JUL09.jpg',
      ),
      '8' => array(
        'fid' => '4695',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room9_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room9_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124785',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room9_JUL09.jpg',
      ),
      '9' => array(
        'fid' => '4696',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room10_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room10_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '34033',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room10_JUL09.jpg',
      ),
      '10' => array(
        'fid' => '4697',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room11_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room11_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16929',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room11_JUL09.jpg',
      ),
      '11' => array(
        'fid' => '4698',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'room12_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jun/room12_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '187095',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'room12_JUL09.jpg',
      ),
    ),
    'path' => 'stories/roommate',
    'tags' => array(
      '5' => array(
        '2497' => array(
          'tid' => '2497',
          'vid' => '5',
          'name' => 'Matthew Stylianou',
          'description' => 'http://www.matthewstylianou.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Matthew Stylianou',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
