array(
  array(
    'nid' => '2931',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1248377011',
    'changed' => '1403919980',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2931',
    'revision_uid' => '1',
    'title' => 'Chaos Control',
    'body' => '<p>
	Let loose... then get a grip.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.mckenziejames.com/" target="_blank">MCKENZIE JAMES</a><http:>. </http:></p>
<p>
	<br />
	Model ~ Matt Prata @ <a href="http://www.nammodels.com/">NAM</a></p>
',
    'teaser' => '<p>
	Let loose... then get a grip.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.mckenziejames.com/" target="_blank">MCKENZIE JAMES</a><http:>. </http:></p>
<p>
	<br />
	Model ~ Matt Prata @ <a href="http://www.nammodels.com/">NAM</a></p>
',
    'log' => '',
    'revision_timestamp' => '1403919980',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.mckenziejames.com/" target="_blank">MCKENZIE JAMES</a></p>
<p>
	MODEL<br />
	MATT PRATA<br />
	@ <a href="http://www.nammodels.com/">NAM</a></p>
<p>
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.hm.com" target="_blank">H&amp;M</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '4801',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130885',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont_JUL09.jpg',
      ),
      '1' => array(
        'fid' => '4802',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont2_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont2_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109864',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont2_JUL09.jpg',
      ),
      '2' => array(
        'fid' => '4803',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont3_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont3_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17707',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont3_JUL09.jpg',
      ),
      '3' => array(
        'fid' => '4804',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont4_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont4_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108047',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont4_JUL09.jpg',
      ),
      '4' => array(
        'fid' => '4805',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont5_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont5_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '70968',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont5_JUL09.jpg',
      ),
      '5' => array(
        'fid' => '4806',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont6_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont6_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77904',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont6_JUL09.jpg',
      ),
      '6' => array(
        'fid' => '4807',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont7_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont7_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58110',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont7_JUL09.jpg',
      ),
      '7' => array(
        'fid' => '4808',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont8_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont8_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138323',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont8_JUL09.jpg',
      ),
      '8' => array(
        'fid' => '4809',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont9_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont9_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97713',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont9_JUL09.jpg',
      ),
      '9' => array(
        'fid' => '4810',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont10_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont10_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '26169',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont10_JUL09.jpg',
      ),
      '10' => array(
        'fid' => '4811',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont11_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont11_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16398',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont11_JUL09.jpg',
      ),
      '11' => array(
        'fid' => '4812',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont12_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont12_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86267',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont12_JUL09.jpg',
      ),
      '12' => array(
        'fid' => '4813',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont13_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont13_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '39948',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont13_JUL09.jpg',
      ),
      '13' => array(
        'fid' => '4814',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont14_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont14_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71150',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont14_JUL09.jpg',
      ),
      '14' => array(
        'fid' => '4815',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont15_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont15_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66632',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont15_JUL09.jpg',
      ),
      '15' => array(
        'fid' => '4816',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont16_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont16_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85022',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont16_JUL09.jpg',
      ),
      '16' => array(
        'fid' => '4817',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont17_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont17_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71586',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont17_JUL09.jpg',
      ),
      '17' => array(
        'fid' => '4818',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'chaoscont18_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/chaoscont18_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '54136',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'chaoscont18_JUL09.jpg',
      ),
    ),
    'path' => 'stories/chaos-control',
    'tags' => array(
      '5' => array(
        '2415' => array(
          'tid' => '2415',
          'vid' => '5',
          'name' => 'McKenzie James',
          'description' => 'http://www.modelmayhem.com/29023',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'McKenzie James',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
