array(
  array(
    'nid' => '2935',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1248712192',
    'changed' => '1303574215',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2935',
    'revision_uid' => '1',
    'title' => 'Pillow Talk',
    'body' => '<p>
	Lay your head on some <a href="http://www.sarikastyle.com/" target="_blank">SARI KA STYLE</a>.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.mckenziejames.com/" target="_blank">MCKENZIE JAMES</a><http:>. </http:></p>
<p>
	<br />
	Model ~ Paul Voisard @ <a href="http://www.nammodels.com/">NAM</a></p>
',
    'teaser' => '<p>
	Lay your head on some <a href="http://www.sarikastyle.com/" target="_blank">SARI KA STYLE</a>.</p>
<p>
	<br />
	Exclusive photography by&nbsp;<a href="http://www.mckenziejames.com/" target="_blank">MCKENZIE JAMES</a><http:>. </http:></p>
<p>
	<br />
	Model ~ Paul Voisard @ <a href="http://www.nammodels.com/">NAM</a></p>
',
    'log' => '',
    'revision_timestamp' => '1303574215',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.mckenziejames.com/" target="_blank">MCKENZIE JAMES</a></p>
<p>
	MODEL<br />
	PAUL VOISARD<br />
	@ <a href="http://www.nammodels.com/">NAM</a></p>
<p>
	&nbsp;</p>
<p>
	FEATURED</p>
<ul>
	<li>
		<a href="http://www.sarikastyle.com/" target="_blank">SARI KA STYLE</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '4852',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129831',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow_JUL09.jpg',
      ),
      '1' => array(
        'fid' => '4853',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow2_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow2_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139873',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow2_JUL09.jpg',
      ),
      '2' => array(
        'fid' => '4854',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow3_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow3_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83740',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow3_JUL09.jpg',
      ),
      '3' => array(
        'fid' => '4855',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow4_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow4_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88195',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow4_JUL09.jpg',
      ),
      '4' => array(
        'fid' => '4856',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow5_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow5_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '230850',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow5_JUL09.jpg',
      ),
      '5' => array(
        'fid' => '4857',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow6_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow6_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '235532',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow6_JUL09.jpg',
      ),
      '6' => array(
        'fid' => '4858',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow7_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow7_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13516',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow7_JUL09.jpg',
      ),
      '7' => array(
        'fid' => '4859',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow8_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow8_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112319',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow8_JUL09.jpg',
      ),
      '8' => array(
        'fid' => '4860',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow9_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow9_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156927',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow9_JUL09.jpg',
      ),
      '9' => array(
        'fid' => '4861',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow10_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow10_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138588',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow10_JUL09.jpg',
      ),
      '10' => array(
        'fid' => '4862',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow11_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow11_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141245',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow11_JUL09.jpg',
      ),
      '11' => array(
        'fid' => '4863',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow12_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow12_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16921',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow12_JUL09.jpg',
      ),
      '12' => array(
        'fid' => '4864',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow13_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow13_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13191',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow13_JUL09.jpg',
      ),
      '13' => array(
        'fid' => '4865',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow14_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow14_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101725',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow14_JUL09.jpg',
      ),
      '14' => array(
        'fid' => '4866',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow15_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow15_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118383',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow15_JUL09.jpg',
      ),
      '15' => array(
        'fid' => '4867',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow16_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow16_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15902',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow16_JUL09.jpg',
      ),
      '16' => array(
        'fid' => '4868',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow17_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow17_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13452',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow17_JUL09.jpg',
      ),
      '17' => array(
        'fid' => '4869',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow18_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow18_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101435',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow18_JUL09.jpg',
      ),
      '18' => array(
        'fid' => '4870',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow19_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow19_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156772',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow19_JUL09.jpg',
      ),
      '19' => array(
        'fid' => '4871',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow20_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow20_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140214',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow20_JUL09.jpg',
      ),
      '20' => array(
        'fid' => '4872',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow21_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow21_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '114185',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow21_JUL09.jpg',
      ),
      '21' => array(
        'fid' => '4873',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'pillow22_JUL09.jpg',
        'filepath' => 'files/fmag_story/2009/Jul/pillow22_JUL09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '152272',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pillow22_JUL09.jpg',
      ),
    ),
    'path' => 'stories/pillow-talk',
    'tags' => array(
      '5' => array(
        '2415' => array(
          'tid' => '2415',
          'vid' => '5',
          'name' => 'McKenzie James',
          'description' => 'http://www.modelmayhem.com/29023',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'McKenzie James',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
