array(
  array(
    'nid' => '2957',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1250973133',
    'changed' => '1406045032',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2957',
    'revision_uid' => '1',
    'title' => 'Beach Blanket Bombshell',
    'body' => '<p>
	Big bang for the beach.</p>
<p>
	Exclusive photography by <a href="http://www.vikrampathak.com" target="_blank">VIKRAM PATHAK</a>.</p>
<p>
	Models ~&nbsp; Angela @ <a href="http://www.notiesmanagement.com/home.php" target="_blank">NO TIES</a> &amp; Tyler @ LMG</p>
',
    'teaser' => '<p>
	Big bang for the beach.</p>
<p>
	Exclusive photography by <a href="http://www.vikrampathak.com" target="_blank">VIKRAM PATHAK</a>.</p>
<p>
	Models ~&nbsp; Angela @ <a href="http://www.notiesmanagement.com/home.php" target="_blank">NO TIES</a> &amp; Tyler @ LMG</p>
',
    'log' => '',
    'revision_timestamp' => '1406045032',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.vikrampathak.com" target="_blank">VIKRAM PATHAK</a></p>
<p>
	MODELS<br />
	ANGELA MARCELLO<br />
	@ <a href="http://www.notiesmanagement.com/home.php" target="_blank">NO TIES</a><br />
	&amp; TYLER BASHLOR<br />
	@<span><b> LMG</b></span></p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://belinher.web.officelive.com/default.aspx" target="_blank">BEHLINER</a></li>
	<li>
		<a href="http://www.n2nbodywear.com/" target="_blank">N2N</a></li>
	<li>
		<a href="http://www.vizeau.com/" target="_blank">VIZEAU</a></li>
	<li>
		<a href="http://www.samplestudio.com/" target="_blank">SAMPLE NY</a></li>
	<li>
		<a href="http://www.freestyleusa.com/" target="_blank">FREESTYLE</a></li>
	<li>
		<a href="http://www.terraplana.com/dopie" target="_blank">DOPIE</a></li>
	<li>
		<a href="http://www.coveri.com/english/history.html" target="_blank">Enrico coveri</a></li>
	<li>
		<a href="http://it.loriblu.com/is-bin/INTERSHOP.enfinity/WFS/Loriblu-Loriblu-Site/it_IT/-/EUR/ViewLandingPage-Start?FromLandingPage=true" target="_blank">Loriblu</a></li>
</ul>
<ul>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '5126',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112959',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach_AUG09.jpg',
      ),
      '1' => array(
        'fid' => '5107',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach2_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach2_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '183208',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach2_AUG09.jpg',
      ),
      '2' => array(
        'fid' => '5108',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach3_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach3_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109341',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach3_AUG09.jpg',
      ),
      '3' => array(
        'fid' => '5109',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach4_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach4_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14610',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach4_AUG09.jpg',
      ),
      '4' => array(
        'fid' => '5110',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach5_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach5_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130244',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach5_AUG09.jpg',
      ),
      '5' => array(
        'fid' => '5111',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach6_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach6_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131908',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach6_AUG09.jpg',
      ),
      '6' => array(
        'fid' => '5112',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach7_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach7_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103378',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach7_AUG09.jpg',
      ),
      '7' => array(
        'fid' => '5113',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach8_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach8_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131708',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach8_AUG09.jpg',
      ),
      '8' => array(
        'fid' => '5114',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach9_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach9_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '142112',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach9_AUG09.jpg',
      ),
      '9' => array(
        'fid' => '5115',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach10_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach10_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '147914',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach10_AUG09.jpg',
      ),
      '10' => array(
        'fid' => '5116',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach11_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach11_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16272',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach11_AUG09.jpg',
      ),
      '11' => array(
        'fid' => '5117',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach12_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach12_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '151495',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach12_AUG09.jpg',
      ),
      '12' => array(
        'fid' => '5118',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach13_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach13_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138316',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach13_AUG09.jpg',
      ),
      '13' => array(
        'fid' => '5119',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach14_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach14_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141608',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach14_AUG09.jpg',
      ),
      '14' => array(
        'fid' => '5120',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach15_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach15_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14276',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach15_AUG09.jpg',
      ),
      '15' => array(
        'fid' => '5121',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach16_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach16_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173075',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach16_AUG09.jpg',
      ),
      '16' => array(
        'fid' => '5122',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach17_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach17_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119766',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach17_AUG09.jpg',
      ),
      '17' => array(
        'fid' => '5123',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach18_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach18_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16268',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach18_AUG09.jpg',
      ),
      '18' => array(
        'fid' => '5124',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach19_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach19_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '125150',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach19_AUG09.jpg',
      ),
      '19' => array(
        'fid' => '5125',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beach20_AUG09.jpg',
        'filepath' => 'files/fmag_story/2009/Aug/beach20_AUG09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '123938',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'beach20_AUG09.jpg',
      ),
    ),
    'path' => 'stories/beach-blanket-bombshell',
    'tags' => array(
      '4' => array(
        '2134' => array(
          'tid' => '2134',
          'vid' => '4',
          'name' => 'bikini',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2129' => array(
          'tid' => '2129',
          'vid' => '4',
          'name' => 'swimwear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2467' => array(
          'tid' => '2467',
          'vid' => '5',
          'name' => 'VIKRAM PATHAK',
          'description' => 'http://www.vikrampathak.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'bikini, men, swimwear, women',
        '5' => 'VIKRAM PATHAK',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
