array(
  array(
    'nid' => '2995',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1254183011',
    'changed' => '1403919756',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2995',
    'revision_uid' => '1',
    'title' => 'Space Girl',
    'body' => '<p>2009 ~ a style odyssey.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.nickidm.com/">NICK IDM</a>.</p>
<p>Model ~ Asheena @ <a target="_blank" href="http://www.d1models.com/">D1</a>.</p>',
    'teaser' => '<p>2009 ~ a style odyssey.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.nickidm.com/">NICK IDM</a>.</p>
<p>Model ~ Asheena @ <a target="_blank" href="http://www.d1models.com/">D1</a>.</p>',
    'log' => '',
    'revision_timestamp' => '1403919756',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>PHOTOGRAPHY<br /><a target="_blank" href="http://www.nickidm.com/">NICK IDM</a></p>
<p>MODEL<br />ASHEENA @ <a target="_blank" href="http://www.d1models.com/">D1</a></p>
<p>FASHION EDITOR<br /><a target="_blank" href="http://www.grahamcruz.com/">Graham Cruz</a></p>
<p> </p>
<p> </p>
<p>FEATURED FASHION</p>
<ul>
<li><a target="_blank" href="http://www.topshop.com/">Topshop</a></li>
</ul>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '5626',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'space_SEPT09.jpg',
        'filepath' => 'files/fmag_story/2009/Sep/space_SEPT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66412',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'space_SEPT09.jpg',
      ),
      '1' => array(
        'fid' => '5627',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'space2_SEPT09.jpg',
        'filepath' => 'files/fmag_story/2009/Sep/space2_SEPT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85733',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'space2_SEPT09.jpg',
      ),
      '2' => array(
        'fid' => '5628',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'space3_SEPT09.jpg',
        'filepath' => 'files/fmag_story/2009/Sep/space3_SEPT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116690',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'space3_SEPT09.jpg',
      ),
      '3' => array(
        'fid' => '5629',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'space4_SEPT09.jpg',
        'filepath' => 'files/fmag_story/2009/Sep/space4_SEPT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '54686',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'space4_SEPT09.jpg',
      ),
      '4' => array(
        'fid' => '5630',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'space5_SEPT09.jpg',
        'filepath' => 'files/fmag_story/2009/Sep/space5_SEPT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98357',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'space5_SEPT09.jpg',
      ),
      '5' => array(
        'fid' => '5631',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'space6_SEPT09.jpg',
        'filepath' => 'files/fmag_story/2009/Sep/space6_SEPT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71473',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'space6_SEPT09.jpg',
      ),
      '6' => array(
        'fid' => '5632',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'space7_SEPT09.jpg',
        'filepath' => 'files/fmag_story/2009/Sep/space7_SEPT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89286',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'space7_SEPT09.jpg',
      ),
      '7' => array(
        'fid' => '5633',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'space8_SEPT09.jpg',
        'filepath' => 'files/fmag_story/2009/Sep/space8_SEPT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '56267',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'space8_SEPT09.jpg',
      ),
    ),
    'path' => 'stories/space-girl',
    'tags' => array(
      '5' => array(
        '2510' => array(
          'tid' => '2510',
          'vid' => '5',
          'name' => 'NICK IDM',
          'description' => 'http://www.nickidm.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'NICK IDM',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
