array(
  array(
    'nid' => '3013',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1254920799',
    'changed' => '1309800794',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3013',
    'revision_uid' => '1',
    'title' => 'What Women Want',
    'body' => '<p>Fashion designer Ella Zahlan.</p>
<p>By Heather MacDonald.</p>
<p>Exclusive photography by <a href="http://www.nicoleannerobbins.com/" target="_blank">Nicole Anne Robbins</a>.</p>
<p> </p>',
    'teaser' => '<p>Fashion designer Ella Zahlan.</p>
<p>By Heather MacDonald.</p>
<p>Exclusive photography by <a href="http://www.nicoleannerobbins.com/" target="_blank">Nicole Anne Robbins</a>.</p>
<p> </p>',
    'log' => '',
    'revision_timestamp' => '1309800794',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p><a href="http://www.ellazahlan.com/" target="_blank">ELLA ZAHLAN</a></p>
<p>BY HEATHER MACDONALD</p>
<p>PHOTOGRAPHY<br /><a href="http://www.nicoleannerobbins.com/" target="_blank">Nicole Anne Robbins</a></p>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '7786',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/Layout-1_Page-2_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '42700',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '7787',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/Layout-1_Page-3_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131052',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '7788',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/Layout-1_Page-4_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '180039',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '7789',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '189979',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
    ),
    'path' => 'stories/what-women-want',
    'tags' => array(
      '5' => array(
        '2513' => array(
          'tid' => '2513',
          'vid' => '5',
          'name' => 'Nicole Anne Robbins',
          'description' => 'http://www.nicoleannerobbins.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'Nicole Anne Robbins',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
