array(
  array(
    'nid' => '3026',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1255715734',
    'changed' => '1403114143',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3026',
    'revision_uid' => '1',
    'title' => 'Michael Alago: Sound Instincts',
    'body' => '<p>
	A&amp;R man turned photographer Michael Alago.</p>
<p>
	Interview by Heather MacDonald.</p>
<p>
	Photography by Isauro Cairo.</p>
',
    'teaser' => '<p>
	A&amp;R man turned photographer Michael Alago.</p>
<p>
	Interview by Heather MacDonald.</p>
<p>
	Photography by Isauro Cairo.</p>
',
    'log' => '',
    'revision_timestamp' => '1403114143',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Michael Alago&#39;s ears heard the music and his guts told him what to do. Interview by Heather Macdonald. Photography by Isauro Cairo.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	MICHAEL ALAGO&#39;S<br />
	<a href="http://www.roughgods.com/" target="_blank">ROUGH GODS</a></p>
<p>
	&nbsp;</p>
<p>
	INTERVIEW BY<br />
	HEATHER MACDONALD</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	ISAURO CAIRO</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '5964',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82083',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound_OCT09.jpg',
      ),
      '1' => array(
        'fid' => '5965',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound2_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound2_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '36405',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound2_OCT09.jpg',
      ),
      '2' => array(
        'fid' => '5966',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound3_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound3_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124027',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound3_OCT09.jpg',
      ),
      '3' => array(
        'fid' => '5967',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound4_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound4_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '133099',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound4_OCT09.jpg',
      ),
      '4' => array(
        'fid' => '5968',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound5_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound5_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '185751',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound5_OCT09.jpg',
      ),
      '5' => array(
        'fid' => '5969',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound6_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound6_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129292',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound6_OCT09.jpg',
      ),
      '6' => array(
        'fid' => '5970',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound7_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound7_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '183518',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound7_OCT09.jpg',
      ),
      '7' => array(
        'fid' => '5971',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound8_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound8_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '200229',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound8_OCT09.jpg',
      ),
      '8' => array(
        'fid' => '6219',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/Layout-1_Page-10_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128982',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '5973',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound10_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound10_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '142760',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound10_OCT09.jpg',
      ),
      '10' => array(
        'fid' => '5974',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound11_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound11_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '214927',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound11_OCT09.jpg',
      ),
      '11' => array(
        'fid' => '5975',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound12_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound12_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '198314',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound12_OCT09.jpg',
      ),
      '12' => array(
        'fid' => '5976',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound13_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound13_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '196299',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound13_OCT09.jpg',
      ),
      '13' => array(
        'fid' => '5977',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound14_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound14_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '249284',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound14_OCT09.jpg',
      ),
      '14' => array(
        'fid' => '5978',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound15_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound15_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '151335',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound15_OCT09.jpg',
      ),
      '15' => array(
        'fid' => '5979',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound16_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound16_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '149125',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound16_OCT09.jpg',
      ),
      '16' => array(
        'fid' => '5980',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound17_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound17_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '144652',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound17_OCT09.jpg',
      ),
      '17' => array(
        'fid' => '5981',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sound18_OCT09.jpg',
        'filepath' => 'files/fmag_story/2009/Oct/sound18_OCT09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '135651',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sound18_OCT09.jpg',
      ),
    ),
    'path' => 'stories/michael-alago-sound-instincts',
    'tags' => array(
      '5' => array(
        '2415' => array(
          'tid' => '2415',
          'vid' => '5',
          'name' => 'McKenzie James',
          'description' => 'http://www.modelmayhem.com/29023',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'McKenzie James',
      ),
      '2' => array(
        '2' => '2',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
