array(
  array(
    'nid' => '3065',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1258061754',
    'changed' => '1337805632',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3065',
    'revision_uid' => '1',
    'title' => 'Scream',
    'body' => '<p>
	You&#39;re really getting on my nerves.</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.alexanderbeerphotography.com/" target="_blank">Alexander Beer</a>.</p>
<p>
	<br />
	Models ~ Deano&nbsp;Mitchison&nbsp;&amp; Jamie Hanson @ <a href="http://www.bossmodelmanagement.co.uk/" target="_blank">boss</a></p>
',
    'teaser' => '<p>
	You&#39;re really getting on my nerves.</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.alexanderbeerphotography.com/" target="_blank">Alexander Beer</a>.</p>
<p>
	<br />
	Models ~ Deano&nbsp;Mitchison&nbsp;&amp; Jamie Hanson @ <a href="http://www.bossmodelmanagement.co.uk/" target="_blank">boss</a></p>
',
    'log' => '',
    'revision_timestamp' => '1337805632',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.alexanderbeerphotography.com/" target="_blank">Alexander Beer</a></p>
<p>
	MODELS<br />
	DEANO MITCHISON<br />
	&amp; JAMIE HANSON<br />
	@ <a href="http://www.bossmodelmanagement.co.uk/" target="_blank">boss</a></p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.expectations.co.uk/" target="_blank">Expectations</a></li>
	<li>
		<a href="http://www.edeandravenscroft.co.uk/" target="_blank">Ede &amp; Ravenscroft</a></li>
	<li>
		<a href="http://www.roubi.eu/" target="_blank">Roubi L&#39; Roubi </a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '6434',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '32655',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream_NOV09.jpg',
      ),
      '1' => array(
        'fid' => '6435',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream2_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream2_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160003',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream2_NOV09.jpg',
      ),
      '2' => array(
        'fid' => '6436',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream3_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream3_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '179444',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream3_NOV09.jpg',
      ),
      '3' => array(
        'fid' => '6437',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream4_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream4_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134148',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream4_NOV09.jpg',
      ),
      '4' => array(
        'fid' => '6438',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream5_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream5_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63147',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream5_NOV09.jpg',
      ),
      '5' => array(
        'fid' => '6439',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream6_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream6_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '191032',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream6_NOV09.jpg',
      ),
      '6' => array(
        'fid' => '6440',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream7_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream7_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '152058',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream7_NOV09.jpg',
      ),
      '7' => array(
        'fid' => '6441',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream8_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream8_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17773',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream8_NOV09.jpg',
      ),
      '8' => array(
        'fid' => '6442',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream9_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream9_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22942',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream9_NOV09.jpg',
      ),
      '9' => array(
        'fid' => '6443',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream10_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream10_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156035',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream10_NOV09.jpg',
      ),
      '10' => array(
        'fid' => '6444',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream11_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream11_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '242955',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream11_NOV09.jpg',
      ),
      '11' => array(
        'fid' => '6445',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'scream12_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/scream12_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124044',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'scream12_NOV09.jpg',
      ),
    ),
    'path' => 'stories/scream',
    'tags' => array(
      '5' => array(
        '2525' => array(
          'tid' => '2525',
          'vid' => '5',
          'name' => 'Alexander Beer',
          'description' => 'http://www.alexanderbeerphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Alexander Beer',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
