array(
  array(
    'nid' => '3066',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1258149248',
    'changed' => '1403919574',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3066',
    'revision_uid' => '1',
    'title' => 'Bijoux Town',
    'body' => '<p>Bedeck it up.</p>
<p>Exclusive photography by <a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a>.</p>
<p>Models ~ Brandon, Julian, Kevin &amp; Nate @ <a href="http://www.citymodel.com/" target="_blank">CITY SF</a></p>
<p><a href="http://www.citymodel.com/" target="_blank"></a>Andrew &amp; Billy @ <a href="http://www.wilhelmina.com/" target="_blank">WILHELMINA.</a></p>',
    'teaser' => '<p>Bedeck it up.</p>
<p>Exclusive photography by <a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a>.</p>
<p>Models ~ Brandon, Julian, Kevin &amp; Nate @ <a href="http://www.citymodel.com/" target="_blank">CITY SF</a></p>
<p><a href="http://www.citymodel.com/" target="_blank"></a>Andrew &amp; Billy @ <a href="http://www.wilhelmina.com/" target="_blank">WILHELMINA.</a></p>',
    'log' => '',
    'revision_timestamp' => '1403919574',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>PHOTOGRAPHY<br /><a href="http://www.billywinters.com/" target="_blank">BILLY WINTERS</a><br /><br />MODELS<br />BRANDON, JULIAN,<br />KEVIN &amp; NATE <br />@ <a href="http://www.citymodel.com/" target="_blank">CITY SF</a><br />ANDREW &amp; BILLY<br />@ <a href="http://www.wilhelmina.com/" target="_blank">WILHELMINA</a></p>
<p><br /><br /><br />FEATURED FASHION</p>
<p> </p>
<ul>
<li><a href="http://www.badgleymischka.com/" target="_blank">badgley mishka</a></li>
<li><a href="http://www.elle-meme.com/" target="_blank">elle meme</a></li>
</ul>
<ul>
<br /><br /> 
</ul>
<p> </p>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '6446',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bijoux_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/bijoux_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '228027',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bijoux_NOV09.jpg',
      ),
      '1' => array(
        'fid' => '6520',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/Layout-1_Page-3_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86139',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '6448',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bijoux3_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/bijoux3_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119000',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bijoux3_NOV09.jpg',
      ),
      '3' => array(
        'fid' => '6449',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bijoux4_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/bijoux4_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122177',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bijoux4_NOV09.jpg',
      ),
      '4' => array(
        'fid' => '6450',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bijoux5_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/bijoux5_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97284',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bijoux5_NOV09.jpg',
      ),
      '5' => array(
        'fid' => '6451',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bijoux6_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/bijoux6_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129171',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bijoux6_NOV09.jpg',
      ),
      '6' => array(
        'fid' => '6452',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bijoux7_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/bijoux7_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '53431',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bijoux7_NOV09.jpg',
      ),
      '7' => array(
        'fid' => '6453',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bijoux8_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/bijoux8_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109933',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'bijoux8_NOV09.jpg',
      ),
    ),
    'path' => 'stories/bijoux-town',
    'tags' => array(
      '5' => array(
        '2519' => array(
          'tid' => '2519',
          'vid' => '5',
          'name' => 'BILLY WINTERS',
          'description' => 'http://www.billywinters.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'BILLY WINTERS',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
