array(
  array(
    'nid' => '3093',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1259595530',
    'changed' => '1337805589',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3093',
    'revision_uid' => '1',
    'title' => 'Flowerhead',
    'body' => '<p>
	How goes it my tiny blossom?</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.claudiagoetzelmann.com/" target="_blank">Claudia Goetzelmann</a>.</p>
<p>
	Model ~ Vincent B @ <a href="http://www.fordmodels.com/main.cfm" target="_blank">Ford</a>.</p>
',
    'teaser' => '<p>
	How goes it my tiny blossom?</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.claudiagoetzelmann.com/" target="_blank">Claudia Goetzelmann</a>.</p>
<p>
	Model ~ Vincent B @ <a href="http://www.fordmodels.com/main.cfm" target="_blank">Ford</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1337805589',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.claudiagoetzelmann.com/" target="_blank">Claudia Goetzelmann</a><br />
	<br />
</p>
<p>
	MODEL<br />
	VINCENT B<br />
	@ <a href="http://www.fordmodels.com/main.cfm" target="_blank">Ford</a></p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.marcjacobs.com/" target="_blank">Marc Jacobs</a></li>
</ul>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '6834',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '152094',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '6836',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/Layout-1_Page-3_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '177590',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '6752',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'flowerhead3_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/flowerhead3_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68982',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'flowerhead3_NOV09.jpg',
      ),
      '3' => array(
        'fid' => '6753',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'flowerhead4_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/flowerhead4_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74661',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'flowerhead4_NOV09.jpg',
      ),
      '4' => array(
        'fid' => '6754',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'flowerhead5_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/flowerhead5_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104919',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'flowerhead5_NOV09.jpg',
      ),
      '5' => array(
        'fid' => '6755',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'flowerhead6_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/flowerhead6_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '197001',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'flowerhead6_NOV09.jpg',
      ),
      '6' => array(
        'fid' => '6756',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'flowerhead7_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/flowerhead7_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '217262',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'flowerhead7_NOV09.jpg',
      ),
      '7' => array(
        'fid' => '6757',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'flowerhead8_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/flowerhead8_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '238328',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'flowerhead8_NOV09.jpg',
      ),
      '8' => array(
        'fid' => '6758',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'flowerhead9_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/flowerhead9_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107334',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'flowerhead9_NOV09.jpg',
      ),
      '9' => array(
        'fid' => '6759',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'flowerhead10_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/flowerhead10_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91658',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'flowerhead10_NOV09.jpg',
      ),
      '10' => array(
        'fid' => '6760',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'flowerhead11_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/flowerhead11_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '209397',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'flowerhead11_NOV09.jpg',
      ),
      '11' => array(
        'fid' => '6761',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'flowerhead12_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Nov/flowerhead12_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140853',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'flowerhead12_NOV09.jpg',
      ),
    ),
    'path' => 'stories/flowerhead',
    'tags' => array(
      '5' => array(
        '2530' => array(
          'tid' => '2530',
          'vid' => '5',
          'name' => 'Claudia Goetzelmann',
          'description' => 'http://www.claudiagoetzelmann.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Claudia Goetzelmann',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
