array(
  array(
    'nid' => '3097',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1259422613',
    'changed' => '1434715385',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3097',
    'revision_uid' => '1',
    'title' => 'Winter Blush',
    'body' => '<p>
	Put some verve in your snowsuit.</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.enokae.com/" target="_blank">ENOKAE</a>.</p>
<p>
	Model ~ Alex Smith @ Storm.</p>
',
    'teaser' => '<p>
	Put some verve in your snowsuit.</p>
<p>
	<br />
	Exclusive photography by <a href="http://www.enokae.com/" target="_blank">ENOKAE</a>.</p>
<p>
	Model ~ Alex Smith @ Storm.</p>
',
    'log' => '',
    'revision_timestamp' => '1434715385',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.enokae.com/" target="_blank">ENOKAE</a></p>
<p>
	MODEL<br />
	ALEX SMITH<br />
	@ Storm<br />
	&nbsp;</p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.uniqlo.com/us/" target="_blank">Uniqlo</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '6802',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'winter_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/winter_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '105687',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'winter_NOV09.jpg',
      ),
      '1' => array(
        'fid' => '6803',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'winter2_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/winter2_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '34635',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'winter2_NOV09.jpg',
      ),
      '2' => array(
        'fid' => '6804',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'winter3_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/winter3_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158782',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'winter3_NOV09.jpg',
      ),
      '3' => array(
        'fid' => '6805',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'winter4_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/winter4_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100851',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'winter4_NOV09.jpg',
      ),
      '4' => array(
        'fid' => '6806',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'winter5_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/winter5_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153183',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'winter5_NOV09.jpg',
      ),
      '5' => array(
        'fid' => '6807',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'winter6_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/winter6_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '135873',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'winter6_NOV09.jpg',
      ),
      '6' => array(
        'fid' => '6808',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'winter7_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/winter7_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '179250',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'winter7_NOV09.jpg',
      ),
      '7' => array(
        'fid' => '6809',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'winter8_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/winter8_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '105192',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'winter8_NOV09.jpg',
      ),
      '8' => array(
        'fid' => '6810',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'winter9_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/winter9_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127140',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'winter9_NOV09.jpg',
      ),
      '9' => array(
        'fid' => '6811',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'winter10_NOV09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/winter10_NOV09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103185',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'winter10_NOV09.jpg',
      ),
    ),
    'path' => 'stories/winter-blush',
    'tags' => array(
      '5' => array(
        '2526' => array(
          'tid' => '2526',
          'vid' => '5',
          'name' => 'ENOKAE',
          'description' => 'http://www.enokae.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ENOKAE',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
