array(
  array(
    'nid' => '3109',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1260378472',
    'changed' => '1403919753',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3109',
    'revision_uid' => '1',
    'title' => 'Swing Out Sister',
    'body' => '<p>Let loose Dollface.</p>
<p>Exclusive photography by <a href="http://www.dripbook.com/edwardstgeorge/splash/" target="_blank">Edward S+George-Adams</a>.</p>
<p>&gt;Models ~ Ania @ <a target="_blank" href="http://www.photogenicsmedia.com/">photogenics</a>.</p>
<p> </p>',
    'teaser' => '<p>Let loose Dollface.</p>
<p>Exclusive photography by <a href="http://www.dripbook.com/edwardstgeorge/splash/" target="_blank">Edward S+George-Adams</a>.</p>
<p>&gt;Models ~ Ania @ <a target="_blank" href="http://www.photogenicsmedia.com/">photogenics</a>.</p>
<p> </p>',
    'log' => '',
    'revision_timestamp' => '1403919753',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>PHOTOGRAPHY<br /><a target="_blank" href="http://www.dripbook.com/edwardstgeorge/splash/">EDWARD <br />S+GEORGE-ADAMS</a></p>
<p>MODEL<br />ANIA A @  <a target="_blank" href="http://www.photogenicsmedia.com"><br />Photogenics</a></p>
<p>FEATURED FASHION</p>
<ul>
<li><a target="_blank" href="http://www.leeklabin.com/">Lee Klabin</a></li>
<li><a target="_blank" href="http://www.sermonetagloves.com/">Sermoneta Gloves</a></li>
<li><a target="_blank" href="http://michadesign.myshopify.com/">Micha Design</a></li>
<li><a target="_blank" href="http://www.ellazahlan.com/">Ella Zahlan</a></li>
<li><a target="_blank" href="http://www.misis.it/">MISIS</a></li>
<li><a target="_blank" href="http://it.loriblu.com/">loriblu</a></li>
<li><a target="_blank" href="http://www.gasolineglamour.com/">Gasoline Glamour</a></li>
<li><a target="_blank" href="http://www.sheribodell.com/">SHERi BODELL</a></li>
</ul>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '6885',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '154802',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing_DEC09.jpg',
      ),
      '1' => array(
        'fid' => '6886',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing2_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing2_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '170067',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing2_DEC09.jpg',
      ),
      '2' => array(
        'fid' => '6887',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing3_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing3_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126469',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing3_DEC09.jpg',
      ),
      '3' => array(
        'fid' => '6888',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing4_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing4_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173577',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing4_DEC09.jpg',
      ),
      '4' => array(
        'fid' => '6889',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing5_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing5_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160532',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing5_DEC09.jpg',
      ),
      '5' => array(
        'fid' => '6890',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing6_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing6_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '25357',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing6_DEC09.jpg',
      ),
      '6' => array(
        'fid' => '6891',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing7_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing7_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14372',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing7_DEC09.jpg',
      ),
      '7' => array(
        'fid' => '6892',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing8_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing8_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85464',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing8_DEC09.jpg',
      ),
      '8' => array(
        'fid' => '6893',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing9_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing9_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14328',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing9_DEC09.jpg',
      ),
      '9' => array(
        'fid' => '6894',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing10_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing10_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136798',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing10_DEC09.jpg',
      ),
      '10' => array(
        'fid' => '6895',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing11_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing11_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137336',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing11_DEC09.jpg',
      ),
      '11' => array(
        'fid' => '6896',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'swing12_DEC09.jpg',
        'filepath' => 'files/fmag_story/2009/Dec/swing12_DEC09.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '34455',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'swing12_DEC09.jpg',
      ),
    ),
    'path' => 'stories/swing-out-sister',
    'tags' => array(
      '5' => array(
        '2500' => array(
          'tid' => '2500',
          'vid' => '5',
          'name' => 'EDWARD ',
          'description' => 'http://www.dripbook.com/edwardstgeorge/splash/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'EDWARD ',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
