array(
  array(
    'nid' => '5016',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1423069965',
    'changed' => 1442382392,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5016',
    'revision_uid' => '1',
    'title' => 'In Bloom',
    'body' => '<p>
	Spring awakening.<br />
	Exclusive photography by <a href="http://www.peterrosa.com/">Peter Rosa</a> at <a href="http://www.utopianyc.com/">Utopia</a>.<br />
	Model - Paulina Panas at <a href="http://www.wilhelmina.com/">Wilhelmina</a>.</p>
',
    'teaser' => '<p>
	Spring awakening.<br />
	Exclusive photography by <a href="http://www.peterrosa.com/">Peter Rosa</a> at <a href="http://www.utopianyc.com/">Utopia</a>.<br />
	Model - Paulina Panas at <a href="http://www.wilhelmina.com/">Wilhelmina</a>.</p>
',
    'revision_timestamp' => '1423144579',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Maestro <a href="http://www.peterrosa.com/">Peter Rosa</a> shoots a portfolio of fab fresh photos starring <a href="http://www.wilhelmina.com/">Wilhelmina</a>&#39;s magnificent model Paulina Panas. Suberb talents - <a href="http://www.takayoshitsukisawa.com/">Tsuki</a> on hair, <a href="http://www.anneliesetieck.com/">Anneliese Tieck</a> on makeup and <a href="http://www.wilhelmina.com/bio.aspx?c=la&amp;nav=17...">Daria Hardeman</a> on manicure - with stylist <a href="http://brianheiser.com/">Brian Heiser</a>&#39;s gorgeous headpieces round out this pretty tribute to spring&#39;s awakening.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.peterrosa.com/">Peter Rosa</a><br />
	at <a href="http://www.utopianyc.com/">Utopia</a></p>
<p>
	PROP STYLING<br />
	<a href="http://brianheiser.com/"> Brian Heiser</a><br />
	<br />
	HAIR<br />
	<a href="http://www.takayoshitsukisawa.com/">Tsuki</a></p>
<p>
	MAKEUP<br />
	<a href="http://www.anneliesetieck.com/">Anneliese Tieck</a></p>
<p>
	MANICURIST<br />
	<a href="http://www.wilhelmina.com/bio.aspx?c=la&amp;nav=17...">Daria Hardeman</a></p>
<p>
	MODEL<br />
	Paulina Panas<br />
	at <a href="http://www.wilhelmina.com/">Wilhelmina</a><br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '35054',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Peter-Rosa-Paulina-Panas2.jpg',
        'filepath' => 'files/fmag_story/2015/Feb/Peter-Rosa-Paulina-Panas2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '839147',
        'status' => '1',
        'timestamp' => '1423069835',
        'origname' => 'Peter-Rosa-Paulina-Panas2.jpg',
      ),
      '1' => array(
        'fid' => '35056',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Peter-Rosa-Paulina-Panas3.jpg',
        'filepath' => 'files/fmag_story/2015/Feb/Peter-Rosa-Paulina-Panas3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113736',
        'status' => '1',
        'timestamp' => '1423069846',
        'origname' => 'Peter-Rosa-Paulina-Panas3.jpg',
      ),
      '2' => array(
        'fid' => '35058',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Peter-Rosa-Paulina-Panas4.jpg',
        'filepath' => 'files/fmag_story/2015/Feb/Peter-Rosa-Paulina-Panas4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '610065',
        'status' => '1',
        'timestamp' => '1423069857',
        'origname' => 'Peter-Rosa-Paulina-Panas4.jpg',
      ),
      '3' => array(
        'fid' => '35059',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Peter-Rosa-Paulina-Panas5.jpg',
        'filepath' => 'files/fmag_story/2015/Feb/Peter-Rosa-Paulina-Panas5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '810643',
        'status' => '1',
        'timestamp' => '1423069868',
        'origname' => 'Peter-Rosa-Paulina-Panas5.jpg',
      ),
      '4' => array(
        'fid' => '35060',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Peter-Rosa-Paulina-Panas6.jpg',
        'filepath' => 'files/fmag_story/2015/Feb/Peter-Rosa-Paulina-Panas6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '768750',
        'status' => '1',
        'timestamp' => '1423069891',
        'origname' => 'Peter-Rosa-Paulina-Panas6.jpg',
      ),
      '5' => array(
        'fid' => '35062',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Peter-Rosa-Paulina-Panas7.jpg',
        'filepath' => 'files/fmag_story/2015/Feb/Peter-Rosa-Paulina-Panas7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '604936',
        'status' => '1',
        'timestamp' => '1423069903',
        'origname' => 'Peter-Rosa-Paulina-Panas7.jpg',
      ),
      '6' => array(
        'fid' => '35064',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Peter-Rosa-Paulina-Panas8.jpg',
        'filepath' => 'files/fmag_story/2015/Feb/Peter-Rosa-Paulina-Panas8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '733129',
        'status' => '1',
        'timestamp' => '1423069914',
        'origname' => 'Peter-Rosa-Paulina-Panas8.jpg',
      ),
      '7' => array(
        'fid' => '35065',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Peter-Rosa-Paulina-Panas9.jpg',
        'filepath' => 'files/fmag_story/2015/Feb/Peter-Rosa-Paulina-Panas9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '560936',
        'status' => '1',
        'timestamp' => '1423069926',
        'origname' => 'Peter-Rosa-Paulina-Panas9.jpg',
      ),
      '8' => array(
        'fid' => '35067',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Peter-Rosa-Paulina-Panas10.jpg',
        'filepath' => 'files/fmag_story/2015/Feb/Peter-Rosa-Paulina-Panas10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '774571',
        'status' => '1',
        'timestamp' => '1423069944',
        'origname' => 'Peter-Rosa-Paulina-Panas10.jpg',
      ),
      '9' => array(
        'fid' => '35068',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Peter-Rosa-Paulina-Panas11.jpg',
        'filepath' => 'files/fmag_story/2015/Feb/Peter-Rosa-Paulina-Panas11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '778337',
        'status' => '1',
        'timestamp' => '1423069953',
        'origname' => 'Peter-Rosa-Paulina-Panas11.jpg',
      ),
    ),
    'path' => 'stories/bloom',
    'tags' => array(
      '4' => array(
        '2916' => array(
          'tid' => '2916',
          'vid' => '4',
          'name' => 'peter rosa',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2295' => array(
          'tid' => '2295',
          'vid' => '4',
          'name' => 'wilhelmina models',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'peter rosa, wilhelmina models, women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => '48a1f1c8-5c36-11e5-a48a-9c55d738902c',
    'is_new' => FALSE,
    'timestamp' => 1442382392,
    'xmlsitemap' => array(
      'id' => '5016',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5016',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1442382392',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5016',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
