array(
  array(
    'nid' => '5420',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1462209493',
    'changed' => '1462210591',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5420',
    'revision_uid' => '1',
    'title' => 'Focus: Sabine Turner by David Apeji',
    'body' => '<p>
	The focus is model Sabine Turner.<br />
	Exclusive photography by <a href="http://www.livebooks.com/">David Apeji</a>.</p>
',
    'teaser' => '<p>
	The focus is model Sabine Turner.<br />
	Exclusive photography by <a href="http://www.livebooks.com/">David Apeji</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1462210591',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.livebooks.com/">David Apeji</a>&nbsp; photo essays model Sabine Turner.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHER<br />
	<a href="http://www.livebooks.com/">David Apeji</a><br />
	&nbsp;</p>
<p>
	SUBJECT<br />
	Sabine Turner<br />
	at Ford/RBA<br />
	&nbsp;</p>
<p>
	STYLING<br />
	<a href="http://www.shannoncampbellstylist.com/">Shannon Campbell</a><br />
	&nbsp;</p>
<p>
	MAKEUP<br />
	<a href="http://www.3jayproductions.com/">Jalia Pettis</a></p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	Vion Eubanks</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '42509',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'david-apeji-sabine-turner2.jpg',
        'filepath' => 'files/fmag_story/2016/May/david-apeji-sabine-turner2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130127',
        'status' => '1',
        'timestamp' => '1462209393',
        'origname' => 'david-apeji-sabine-turner2.jpg',
      ),
      '1' => array(
        'fid' => '42511',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'david-apeji-sabine-turner3.jpg',
        'filepath' => 'files/fmag_story/2016/May/david-apeji-sabine-turner3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '390641',
        'status' => '1',
        'timestamp' => '1462209402',
        'origname' => 'david-apeji-sabine-turner3.jpg',
      ),
      '2' => array(
        'fid' => '42513',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'david-apeji-sabine-turner4.jpg',
        'filepath' => 'files/fmag_story/2016/May/david-apeji-sabine-turner4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '397042',
        'status' => '1',
        'timestamp' => '1462209413',
        'origname' => 'david-apeji-sabine-turner4.jpg',
      ),
      '3' => array(
        'fid' => '42515',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'david-apeji-sabine-turner5.jpg',
        'filepath' => 'files/fmag_story/2016/May/david-apeji-sabine-turner5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61062',
        'status' => '1',
        'timestamp' => '1462209425',
        'origname' => 'david-apeji-sabine-turner5.jpg',
      ),
      '4' => array(
        'fid' => '42517',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'david-apeji-sabine-turner6.jpg',
        'filepath' => 'files/fmag_story/2016/May/david-apeji-sabine-turner6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '469748',
        'status' => '1',
        'timestamp' => '1462209435',
        'origname' => 'david-apeji-sabine-turner6.jpg',
      ),
      '5' => array(
        'fid' => '42519',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'david-apeji-sabine-turner7.jpg',
        'filepath' => 'files/fmag_story/2016/May/david-apeji-sabine-turner7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '451604',
        'status' => '1',
        'timestamp' => '1462209445',
        'origname' => 'david-apeji-sabine-turner7.jpg',
      ),
      '6' => array(
        'fid' => '42521',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'david-apeji-sabine-turner8.jpg',
        'filepath' => 'files/fmag_story/2016/May/david-apeji-sabine-turner8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '692459',
        'status' => '1',
        'timestamp' => '1462209455',
        'origname' => 'david-apeji-sabine-turner8.jpg',
      ),
      '7' => array(
        'fid' => '42523',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'david-apeji-sabine-turner9.jpg',
        'filepath' => 'files/fmag_story/2016/May/david-apeji-sabine-turner9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '807084',
        'status' => '1',
        'timestamp' => '1462209466',
        'origname' => 'david-apeji-sabine-turner9.jpg',
      ),
      '8' => array(
        'fid' => '42525',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'david-apeji-sabine-turner10.jpg',
        'filepath' => 'files/fmag_story/2016/May/david-apeji-sabine-turner10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67287',
        'status' => '1',
        'timestamp' => '1462209477',
        'origname' => 'david-apeji-sabine-turner10.jpg',
      ),
      '9' => array(
        'fid' => '42526',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'david-apeji-sabine-turner11.jpg',
        'filepath' => 'files/fmag_story/2016/May/david-apeji-sabine-turner11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '425154',
        'status' => '1',
        'timestamp' => '1462209485',
        'origname' => 'david-apeji-sabine-turner11.jpg',
      ),
    ),
    'path' => 'stories/focus-sabine-turner-david-apeji',
    'tags' => array(
      '4' => array(
        '3459' => array(
          'tid' => '3459',
          'vid' => '4',
          'name' => 'david',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2904' => array(
          'tid' => '2904',
          'vid' => '4',
          'name' => 'ford RBA Models',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'david, ford RBA Models, women',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
