array(
  array(
    'nid' => '5430',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1464132245',
    'changed' => '1464132638',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5430',
    'revision_uid' => '1',
    'title' => 'Cool: Veronika Losyuk by Wendy Hope',
    'body' => '<p>
	Veronika is cool.<br />
	Exclusive photography by <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a>.</p>
',
    'teaser' => '<p>
	Veronika is cool.<br />
	Exclusive photography by <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1464132638',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a> essays <a href="http://rednyc.com/">Red</a> model Veronika Losyuk.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHER<br />
	<a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope<br />
	at ABTP</a><br />
	&nbsp;</p>
<p>
	SUBJECT<br />
	Veronika Losyuk</p>
<p>
	HAIR<br />
	<a href="http://abtp.com/Hair/Hair/Bradley-Irion/Biography">Bradley Irion<br />
	at ABTP&nbsp;&nbsp; &nbsp;</a></p>
<p>
	MAKEUP<br />
	Margina Dennis<br />
	at <a href="http://www.stocklandmartel.com/talent/margina-dennis/photography">Stockland Martel</a></p>
<p>
	STYLING<br />
	<a href="http://www.jadechung.co/about/">Jade C. Chung</a></p>
<p>
	<a href="http://rednyc.com/">Red NYC</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '42782',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Veronika-Losyuk-Wendy-Hope2.jpg',
        'filepath' => 'files/fmag_story/2016/May/Veronika-Losyuk-Wendy-Hope2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '393236',
        'status' => '1',
        'timestamp' => '1464132633',
        'origname' => 'Veronika-Losyuk-Wendy-Hope2.jpg',
      ),
      '1' => array(
        'fid' => '42771',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Veronika-Losyuk-Wendy-Hope3.jpg',
        'filepath' => 'files/fmag_story/2016/May/Veronika-Losyuk-Wendy-Hope3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94261',
        'status' => '1',
        'timestamp' => '1464132280',
        'origname' => 'Veronika-Losyuk-Wendy-Hope3.jpg',
      ),
      '2' => array(
        'fid' => '42773',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Veronika-Losyuk-Wendy-Hope4.jpg',
        'filepath' => 'files/fmag_story/2016/May/Veronika-Losyuk-Wendy-Hope4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '335233',
        'status' => '1',
        'timestamp' => '1464132290',
        'origname' => 'Veronika-Losyuk-Wendy-Hope4.jpg',
      ),
      '3' => array(
        'fid' => '42775',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Veronika-Losyuk-Wendy-Hope5.jpg',
        'filepath' => 'files/fmag_story/2016/May/Veronika-Losyuk-Wendy-Hope5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '357998',
        'status' => '1',
        'timestamp' => '1464132298',
        'origname' => 'Veronika-Losyuk-Wendy-Hope5.jpg',
      ),
      '4' => array(
        'fid' => '42776',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Veronika-Losyuk-Wendy-Hope6.jpg',
        'filepath' => 'files/fmag_story/2016/May/Veronika-Losyuk-Wendy-Hope6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '365060',
        'status' => '1',
        'timestamp' => '1464132307',
        'origname' => 'Veronika-Losyuk-Wendy-Hope6.jpg',
      ),
      '5' => array(
        'fid' => '42777',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Veronika-Losyuk-Wendy-Hope7.jpg',
        'filepath' => 'files/fmag_story/2016/May/Veronika-Losyuk-Wendy-Hope7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '343992',
        'status' => '1',
        'timestamp' => '1464132317',
        'origname' => 'Veronika-Losyuk-Wendy-Hope7.jpg',
      ),
      '6' => array(
        'fid' => '42779',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Veronika-Losyuk-Wendy-Hope8.jpg',
        'filepath' => 'files/fmag_story/2016/May/Veronika-Losyuk-Wendy-Hope8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '138702',
        'status' => '1',
        'timestamp' => '1464132329',
        'origname' => 'Veronika-Losyuk-Wendy-Hope8.jpg',
      ),
      '7' => array(
        'fid' => '42780',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Veronika-Losyuk-Wendy-Hope9.jpg',
        'filepath' => 'files/fmag_story/2016/May/Veronika-Losyuk-Wendy-Hope9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '257781',
        'status' => '1',
        'timestamp' => '1464132337',
        'origname' => 'Veronika-Losyuk-Wendy-Hope9.jpg',
      ),
    ),
    'path' => 'stories/cool-veronika-losyuk-wendy-hope',
    'tags' => array(
      '4' => array(
        '3475' => array(
          'tid' => '3475',
          'vid' => '4',
          'name' => 'cool',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '3244' => array(
          'tid' => '3244',
          'vid' => '4',
          'name' => 'red models',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '3476' => array(
          'tid' => '3476',
          'vid' => '4',
          'name' => 'wendy hope',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'cool, red models, wendy hope',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
