array(
  array(
    'nid' => '5437',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1464730987',
    'changed' => 1475181754,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5437',
    'revision_uid' => '1',
    'title' => 'Cool: Jamey Poole by Wendy Hope',
    'body' => '<p>
	James is cool.<br />
	Exclusive photography by <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a>.</p>
',
    'teaser' => '<p>
	James is cool.<br />
	Exclusive photography by <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a>.</p>
',
    'revision_timestamp' => '1464731266',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a> essays <a href="http://rednyc.com/">Red</a> model Jamey Poole.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHER<br />
	<a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope<br />
	at ABTP</a><br />
	&nbsp;</p>
<p>
	SUBJECT<br />
	Jamey Poole</p>
<p>
	HAIR<br />
	<a href="http://abtp.com/Hair/Hair/Bradley-Irion/Biography">Bradley Irion<br />
	at ABTP&nbsp;&nbsp; &nbsp;</a></p>
<p>
	MAKEUP<br />
	Margina Dennis<br />
	at <a href="http://www.stocklandmartel.com/talent/margina-dennis/photography">Stockland Martel</a></p>
<p>
	STYLING<br />
	<a href="http://www.jadechung.co/about/">Jade C. Chung</a></p>
<p>
	<a href="http://rednyc.com/">Red NYC</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '42895',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope2.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '39560',
        'status' => '1',
        'timestamp' => '1464731023',
        'origname' => 'Jamey-Poole-Wendy-hope2.jpg',
      ),
      '1' => array(
        'fid' => '42897',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope3.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81931',
        'status' => '1',
        'timestamp' => '1464731038',
        'origname' => 'Jamey-Poole-Wendy-hope3.jpg',
      ),
      '2' => array(
        'fid' => '42898',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope4.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '53815',
        'status' => '1',
        'timestamp' => '1464731049',
        'origname' => 'Jamey-Poole-Wendy-hope4.jpg',
      ),
      '3' => array(
        'fid' => '42899',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope5.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71153',
        'status' => '1',
        'timestamp' => '1464731075',
        'origname' => 'Jamey-Poole-Wendy-hope5.jpg',
      ),
      '4' => array(
        'fid' => '42901',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope6.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29084',
        'status' => '1',
        'timestamp' => '1464731102',
        'origname' => 'Jamey-Poole-Wendy-hope6.jpg',
      ),
      '5' => array(
        'fid' => '42902',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope7.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '59963',
        'status' => '1',
        'timestamp' => '1464731111',
        'origname' => 'Jamey-Poole-Wendy-hope7.jpg',
      ),
      '6' => array(
        'fid' => '42904',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope8.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88818',
        'status' => '1',
        'timestamp' => '1464731186',
        'origname' => 'Jamey-Poole-Wendy-hope8.jpg',
      ),
      '7' => array(
        'fid' => '42906',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope9.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107353',
        'status' => '1',
        'timestamp' => '1464731199',
        'origname' => 'Jamey-Poole-Wendy-hope9.jpg',
      ),
      '8' => array(
        'fid' => '42908',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope10.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83054',
        'status' => '1',
        'timestamp' => '1464731214',
        'origname' => 'Jamey-Poole-Wendy-hope10.jpg',
      ),
      '9' => array(
        'fid' => '42909',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope11.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29084',
        'status' => '1',
        'timestamp' => '1464731224',
        'origname' => 'Jamey-Poole-Wendy-hope11.jpg',
      ),
      '10' => array(
        'fid' => '42911',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope12.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29084',
        'status' => '1',
        'timestamp' => '1464731236',
        'origname' => 'Jamey-Poole-Wendy-hope12.jpg',
      ),
      '11' => array(
        'fid' => '42912',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope13.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67465',
        'status' => '1',
        'timestamp' => '1464731244',
        'origname' => 'Jamey-Poole-Wendy-hope13.jpg',
      ),
      '12' => array(
        'fid' => '42914',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope14.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66631',
        'status' => '1',
        'timestamp' => '1464731254',
        'origname' => 'Jamey-Poole-Wendy-hope14.jpg',
      ),
      '13' => array(
        'fid' => '42915',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jamey-Poole-Wendy-hope15.jpg',
        'filepath' => 'files/fmag_story/2016/May/Jamey-Poole-Wendy-hope15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85108',
        'status' => '1',
        'timestamp' => '1464731261',
        'origname' => 'Jamey-Poole-Wendy-hope15.jpg',
      ),
    ),
    'path' => 'stories/cool-jamey-poole-wendy-hope',
    'tags' => NULL,
    'taxonomy' => array(),
    'files' => array(),
    'page_title' => '',
    'uuid' => '401c5492-8685-11e6-8e23-251e245d64df',
    'is_new' => FALSE,
    'timestamp' => 1475181754,
    'xmlsitemap' => array(
      'id' => '5437',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5437',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1475181754',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5437',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
