array(
  array(
    'nid' => '5445',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1466118311',
    'changed' => '1466118441',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5445',
    'revision_uid' => '1',
    'title' => 'Cool: Kimberlyn Parris by Wendy Hope',
    'body' => '<p>
	Kimberlyn is cool.<br />
	Exclusive photography by <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a>.</p>
',
    'teaser' => '<p>
	Kimberlyn is cool.<br />
	Exclusive photography by <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1466118441',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a> essays <a href="http://www.onemanagement.com/">One</a>&#39;s model Kimberlyn Parris.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHER<br />
	<a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope<br />
	at ABTP</a><br />
	&nbsp;</p>
<p>
	SUBJECT<br />
	<a href="http://kimberlynparris.com">Kimberlyn Parris</a></p>
<p>
	HAIR<br />
	<a href="http://abtp.com/Hair/Hair/Bradley-Irion/Biography">Bradley Irion<br />
	at ABTP&nbsp;&nbsp; &nbsp;</a></p>
<p>
	MAKEUP<br />
	Margina Dennis<br />
	at <a href="http://www.stocklandmartel.com/talent/margina-dennis/photography">Stockland Martel</a></p>
<p>
	STYLING<br />
	<a href="http://www.jadechung.co/about/">Jade C. Chung</a></p>
<p>
	<a href="http://rednyc.com/">Red NYC</a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://www.onemanagement.com/">One Model Management</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '43092',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kimberlyn-Parris-Wendy-Hope2.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/Kimberlyn-Parris-Wendy-Hope2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '45068',
        'status' => '1',
        'timestamp' => '1466118329',
        'origname' => 'Kimberlyn-Parris-Wendy-Hope2.jpg',
      ),
      '1' => array(
        'fid' => '43094',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kimberlyn-Parris-Wendy-Hope3.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/Kimberlyn-Parris-Wendy-Hope3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '99078',
        'status' => '1',
        'timestamp' => '1466118337',
        'origname' => 'Kimberlyn-Parris-Wendy-Hope3.jpg',
      ),
      '2' => array(
        'fid' => '43096',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kimberlyn-Parris-Wendy-Hope4.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/Kimberlyn-Parris-Wendy-Hope4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29084',
        'status' => '1',
        'timestamp' => '1466118345',
        'origname' => 'Kimberlyn-Parris-Wendy-Hope4.jpg',
      ),
      '3' => array(
        'fid' => '43098',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kimberlyn-Parris-Wendy-Hope5.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/Kimberlyn-Parris-Wendy-Hope5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73429',
        'status' => '1',
        'timestamp' => '1466118352',
        'origname' => 'Kimberlyn-Parris-Wendy-Hope5.jpg',
      ),
      '4' => array(
        'fid' => '43100',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kimberlyn-Parris-Wendy-Hope6.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/Kimberlyn-Parris-Wendy-Hope6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '59823',
        'status' => '1',
        'timestamp' => '1466118363',
        'origname' => 'Kimberlyn-Parris-Wendy-Hope6.jpg',
      ),
      '5' => array(
        'fid' => '43102',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kimberlyn-Parris-Wendy-Hope7.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/Kimberlyn-Parris-Wendy-Hope7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60762',
        'status' => '1',
        'timestamp' => '1466118383',
        'origname' => 'Kimberlyn-Parris-Wendy-Hope7.jpg',
      ),
      '6' => array(
        'fid' => '43104',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kimberlyn-Parris-Wendy-Hope8.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/Kimberlyn-Parris-Wendy-Hope8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '60233',
        'status' => '1',
        'timestamp' => '1466118392',
        'origname' => 'Kimberlyn-Parris-Wendy-Hope8.jpg',
      ),
      '7' => array(
        'fid' => '43105',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kimberlyn-Parris-Wendy-Hope9.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/Kimberlyn-Parris-Wendy-Hope9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58695',
        'status' => '1',
        'timestamp' => '1466118398',
        'origname' => 'Kimberlyn-Parris-Wendy-Hope9.jpg',
      ),
    ),
    'path' => 'stories/cool-kimberlyn-parris-wendy-hope',
    'tags' => NULL,
    'taxonomy' => array(),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
