array(
  array(
    'nid' => '5461',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1467320406',
    'changed' => 1475181781,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5461',
    'revision_uid' => '1',
    'title' => 'Cool: Zoe Canada',
    'body' => '<p>
	Zoe is cool.<br />
	Exclusive photography by <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a>.</p>
',
    'teaser' => '<p>
	Zoe is cool.<br />
	Exclusive photography by <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a>.</p>
',
    'revision_timestamp' => '1467835522',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a> essays <a href="http://www.qmanagementinc.com/">Q Model</a> Zoe Canada.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHER<br />
	<a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope<br />
	at ABTP</a><br />
	&nbsp;</p>
<p>
	SUBJECT<br />
	Zoe Canada<br />
	&nbsp;</p>
<p>
	HAIR<br />
	<a href="http://abtp.com/Hair/Hair/Bradley-Irion/Biography">Bradley Irion<br />
	at ABTP&nbsp;&nbsp; &nbsp;</a></p>
<p>
	MAKEUP<br />
	Margina Dennis<br />
	at <a href="http://www.stocklandmartel.com/talent/margina-dennis/photography">Stockland Martel</a><br />
	&amp;<br />
	Anastasia Skye</p>
<p>
	STYLING<br />
	<a href="http://www.jadechung.co/about/">Jade C. Chung</a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://www.qmanagementinc.com/">Q Model Management</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '43388',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada2.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136192',
        'status' => '1',
        'timestamp' => '1467320485',
        'origname' => 'COOL-Zoe-Canada2.jpg',
      ),
      '1' => array(
        'fid' => '43408',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada3sm.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada3sm.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '43221',
        'status' => '1',
        'timestamp' => '1467835516',
        'origname' => 'COOL-Zoe-Canada3sm.jpg',
      ),
      '2' => array(
        'fid' => '43391',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada4.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134388',
        'status' => '1',
        'timestamp' => '1467320501',
        'origname' => 'COOL-Zoe-Canada4.jpg',
      ),
      '3' => array(
        'fid' => '43393',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada5.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29084',
        'status' => '1',
        'timestamp' => '1467320510',
        'origname' => 'COOL-Zoe-Canada5.jpg',
      ),
      '4' => array(
        'fid' => '43394',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada6.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29084',
        'status' => '1',
        'timestamp' => '1467320519',
        'origname' => 'COOL-Zoe-Canada6.jpg',
      ),
      '5' => array(
        'fid' => '43396',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada7.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116942',
        'status' => '1',
        'timestamp' => '1467320656',
        'origname' => 'COOL-Zoe-Canada7.jpg',
      ),
      '6' => array(
        'fid' => '43398',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada8.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95261',
        'status' => '1',
        'timestamp' => '1467320665',
        'origname' => 'COOL-Zoe-Canada8.jpg',
      ),
      '7' => array(
        'fid' => '43400',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada9.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '105070',
        'status' => '1',
        'timestamp' => '1467320673',
        'origname' => 'COOL-Zoe-Canada9.jpg',
      ),
      '8' => array(
        'fid' => '43402',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada10.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83584',
        'status' => '1',
        'timestamp' => '1467320683',
        'origname' => 'COOL-Zoe-Canada10.jpg',
      ),
      '9' => array(
        'fid' => '43403',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada11.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78385',
        'status' => '1',
        'timestamp' => '1467320690',
        'origname' => 'COOL-Zoe-Canada11.jpg',
      ),
      '10' => array(
        'fid' => '43405',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada12.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '57570',
        'status' => '1',
        'timestamp' => '1467320719',
        'origname' => 'COOL-Zoe-Canada12.jpg',
      ),
      '11' => array(
        'fid' => '43406',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL-Zoe-Canada13.jpg',
        'filepath' => 'files/fmag_story/2016/Jun/COOL-Zoe-Canada13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93495',
        'status' => '1',
        'timestamp' => '1467320725',
        'origname' => 'COOL-Zoe-Canada13.jpg',
      ),
    ),
    'path' => 'stories/cool-zoe-canada',
    'tags' => NULL,
    'taxonomy' => array(),
    'files' => array(),
    'page_title' => '',
    'uuid' => '50089be0-8685-11e6-8e23-251e245d64df',
    'is_new' => FALSE,
    'timestamp' => 1475181781,
    'xmlsitemap' => array(
      'id' => '5461',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5461',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1475181781',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5461',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
