array(
  array(
    'nid' => '5463',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1468242000',
    'changed' => 1475181783,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5463',
    'revision_uid' => '1',
    'title' => 'GIG: Michael Stewart',
    'body' => '<p>
	<a href="http://thebeautybar.com/home-new-york/">The Beauty Bar</a>&#39;s Michael Stewart talks up his gig.<br />
	Exclusive photography by <a href="http://www.jasonobrotka.com/">Jason Obrotka</a>.</p>
',
    'teaser' => '<p>
	<a href="http://thebeautybar.com/home-new-york/">The Beauty Bar</a>&#39;s Michael Stewart talks up his gig.<br />
	Exclusive photography by <a href="http://www.jasonobrotka.com/">Jason Obrotka</a>.</p>
',
    'revision_timestamp' => '1468246496',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	New York City&#39;s <a href="http://thebeautybar.com/home-new-york/">The Beauty Bar</a> owner and operator Michael Stewart.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://Portraits by Nina Duncan">The Beauty Bar</a><br />
	231 E 14th Street<br />
	New York NY 10003<br />
	212. 539 1389</p>
<p>
	&nbsp;</p>
<p>
	Portraits by <a href="http://www.jasonobrotka.com/">Jason Obrotka</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '43411',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Michael-stewart-beauty-bar-gig2.jpg',
        'filepath' => 'files/fmag_story/2016/Jul/Michael-stewart-beauty-bar-gig2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '149156',
        'status' => '1',
        'timestamp' => '1468086050',
        'origname' => 'Michael-stewart-beauty-bar-gig2.jpg',
      ),
      '1' => array(
        'fid' => '43412',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Michael-stewart-beauty-bar-gig3.jpg',
        'filepath' => 'files/fmag_story/2016/Jul/Michael-stewart-beauty-bar-gig3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68182',
        'status' => '1',
        'timestamp' => '1468086058',
        'origname' => 'Michael-stewart-beauty-bar-gig3.jpg',
      ),
      '2' => array(
        'fid' => '43414',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Michael-stewart-beauty-bar-gig4.jpg',
        'filepath' => 'files/fmag_story/2016/Jul/Michael-stewart-beauty-bar-gig4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107224',
        'status' => '1',
        'timestamp' => '1468086069',
        'origname' => 'Michael-stewart-beauty-bar-gig4.jpg',
      ),
      '3' => array(
        'fid' => '43416',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Michael-stewart-beauty-bar-gig5.jpg',
        'filepath' => 'files/fmag_story/2016/Jul/Michael-stewart-beauty-bar-gig5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108868',
        'status' => '1',
        'timestamp' => '1468086081',
        'origname' => 'Michael-stewart-beauty-bar-gig5.jpg',
      ),
      '4' => array(
        'fid' => '43418',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Michael-stewart-beauty-bar-gig6.jpg',
        'filepath' => 'files/fmag_story/2016/Jul/Michael-stewart-beauty-bar-gig6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122103',
        'status' => '1',
        'timestamp' => '1468086090',
        'origname' => 'Michael-stewart-beauty-bar-gig6.jpg',
      ),
      '5' => array(
        'fid' => '43420',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Michael-stewart-beauty-bar-gig7.jpg',
        'filepath' => 'files/fmag_story/2016/Jul/Michael-stewart-beauty-bar-gig7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113403',
        'status' => '1',
        'timestamp' => '1468086098',
        'origname' => 'Michael-stewart-beauty-bar-gig7.jpg',
      ),
    ),
    'path' => 'stories/gig-michael-stewart',
    'tags' => NULL,
    'taxonomy' => array(),
    'files' => array(),
    'page_title' => '',
    'uuid' => '5180c858-8685-11e6-8e23-251e245d64df',
    'is_new' => FALSE,
    'timestamp' => 1475181783,
    'xmlsitemap' => array(
      'id' => '5463',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5463',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1475181783',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5463',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
