array(
  array(
    'nid' => '5501',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1472758821',
    'changed' => 1475181828,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5501',
    'revision_uid' => '1',
    'title' => 'Note This: Wares We Like',
    'body' => '<p>
	We recommend cuz we really like it.<br />
	Exclusive photography by James N.<br />
	Model. Coleman at <a href="http://www.plutinogroup.com/">Plutino</a>.</p>
',
    'teaser' => '<p>
	We recommend cuz we really like it.<br />
	Exclusive photography by James N.<br />
	Model. Coleman at <a href="http://www.plutinogroup.com/">Plutino</a>.</p>
',
    'revision_timestamp' => '1472772726',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Wares we really like.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.reuzelpomade.com/">REUZEL POMADE</a></p>
<p>
	<a href="https://www.pusherscollective.com/">PUSHERS COLLECTIVE CLOTHING</a></p>
<p>
	<a href="https://www.previsecare.com/">PREVISE CUSTOMZED SKIN CARE SOLUTIONS</a></p>
<p>
	<a href="http://www.brunochaussignand.com/">BRUNO CHAUSSIGNAND EYEWEAR</a></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	James N</p>
<p>
	MODEL<br />
	Coleman<br />
	at <a href="http://www.plutinogroup.com/">Plutino</a><br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '43865',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Coleman-NOTE-THIS2.jpg',
        'filepath' => 'files/fmag_story/2016/Sep/Coleman-NOTE-THIS2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92553',
        'status' => '1',
        'timestamp' => '1472758741',
        'origname' => 'Coleman-NOTE-THIS2.jpg',
      ),
      '1' => array(
        'fid' => '43867',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Coleman-NOTE-THIS3.jpg',
        'filepath' => 'files/fmag_story/2016/Sep/Coleman-NOTE-THIS3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58600',
        'status' => '1',
        'timestamp' => '1472758751',
        'origname' => 'Coleman-NOTE-THIS3.jpg',
      ),
      '2' => array(
        'fid' => '43893',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Coleman-NOTE-THIS4.jpg',
        'filepath' => 'files/fmag_story/2016/Sep/Coleman-NOTE-THIS4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117228',
        'status' => '1',
        'timestamp' => '1472760035',
        'origname' => 'Coleman-NOTE-THIS4.jpg',
      ),
      '3' => array(
        'fid' => '43871',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Coleman-NOTE-THIS5.jpg',
        'filepath' => 'files/fmag_story/2016/Sep/Coleman-NOTE-THIS5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66245',
        'status' => '1',
        'timestamp' => '1472758767',
        'origname' => 'Coleman-NOTE-THIS5.jpg',
      ),
      '4' => array(
        'fid' => '43894',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Coleman-NOTE-THIS6.jpg',
        'filepath' => 'files/fmag_story/2016/Sep/Coleman-NOTE-THIS6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65062',
        'status' => '1',
        'timestamp' => '1472760050',
        'origname' => 'Coleman-NOTE-THIS6.jpg',
      ),
      '5' => array(
        'fid' => '43895',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Coleman-NOTE-THIS7.jpg',
        'filepath' => 'files/fmag_story/2016/Sep/Coleman-NOTE-THIS7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97384',
        'status' => '1',
        'timestamp' => '1472760061',
        'origname' => 'Coleman-NOTE-THIS7.jpg',
      ),
      '6' => array(
        'fid' => '43877',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Coleman-NOTE-THIS8.jpg',
        'filepath' => 'files/fmag_story/2016/Sep/Coleman-NOTE-THIS8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76625',
        'status' => '1',
        'timestamp' => '1472758792',
        'origname' => 'Coleman-NOTE-THIS8.jpg',
      ),
      '7' => array(
        'fid' => '43896',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Coleman-NOTE-THIS9.jpg',
        'filepath' => 'files/fmag_story/2016/Sep/Coleman-NOTE-THIS9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94914',
        'status' => '1',
        'timestamp' => '1472760078',
        'origname' => 'Coleman-NOTE-THIS9.jpg',
      ),
      '8' => array(
        'fid' => '43891',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Coleman-NOTE-THIS10.jpg',
        'filepath' => 'files/fmag_story/2016/Sep/Coleman-NOTE-THIS10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58300',
        'status' => '1',
        'timestamp' => '1472759772',
        'origname' => 'Coleman-NOTE-THIS10.jpg',
      ),
      '9' => array(
        'fid' => '43882',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Coleman-NOTE-THIS11.jpg',
        'filepath' => 'files/fmag_story/2016/Sep/Coleman-NOTE-THIS11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85640',
        'status' => '1',
        'timestamp' => '1472758821',
        'origname' => 'Coleman-NOTE-THIS11.jpg',
      ),
    ),
    'path' => 'stories/note-wares-we',
    'tags' => NULL,
    'taxonomy' => array(),
    'files' => array(),
    'page_title' => '',
    'uuid' => '6c5d90c0-8685-11e6-8e23-251e245d64df',
    'is_new' => FALSE,
    'timestamp' => 1475181828,
    'xmlsitemap' => array(
      'id' => '5501',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5501',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1475181828',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5501',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
