array(
  array(
    'nid' => '5388',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1457358300',
    'changed' => 1464902757,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5388',
    'revision_uid' => '1',
    'title' => 'Soundbites: Apigeon',
    'body' => '<p>
	We talk to musical wonder <a href="http://apigeon.com/">Apigeon</a>.<br />
	Exclusive photography by <a href="http://www.johnnyrozsa.photo/">Johnny Rozsa</a>.</p>
',
    'teaser' => '<p>
	We talk to musical wonder <a href="http://apigeon.com/">Apigeon</a>.<br />
	Exclusive photography by <a href="http://www.johnnyrozsa.photo/">Johnny Rozsa</a>.</p>
',
    'revision_timestamp' => '1457355810',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.johnnyrozsa.photo/">Johnny Rozsa</a> essays songstress <a href="http://apigeon.com/">Apigeon</a>.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://apigeon.com/">Apigeon</a></p>
<p>
	&nbsp;</p>
<p>
	<a href="https://itunes.apple.com/ca/artist/apigeon/id829771874">Apigeon on iTunes</a></p>
<p>
	&nbsp;</p>
<p>
	<a href="https://soundcloud.com/apigeonisborn">Apigeon on Soundcloud</a></p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHER<br />
	<a href="http://www.johnnyrozsa.photo/">Johnny Rozsa</a><br />
	<br />
	&nbsp;</p>
<p>
	MAKEUP<br />
	Dominque Jenelle</p>
<p>
	HAIR<br />
	Marco at Marco&#39;s Wigs</p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY ASSISTANT<br />
	Jeremiah Cumberbatch<br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '41862',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SOUNDBITES_Apigeon2.jpg',
        'filepath' => 'files/fmag_story/2016/Feb/SOUNDBITES_Apigeon2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '461045',
        'status' => '1',
        'timestamp' => '1455205633',
        'origname' => 'SOUNDBITES_Apigeon2.jpg',
      ),
      '1' => array(
        'fid' => '42069',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SOUNDBITES_Apigeon3.jpg',
        'filepath' => 'files/fmag_story/2016/Feb/SOUNDBITES_Apigeon3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155299',
        'status' => '1',
        'timestamp' => '1457355512',
        'origname' => 'SOUNDBITES_Apigeon3.jpg',
      ),
      '2' => array(
        'fid' => '42070',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SOUNDBITES_Apigeon4.jpg',
        'filepath' => 'files/fmag_story/2016/Feb/SOUNDBITES_Apigeon4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160993',
        'status' => '1',
        'timestamp' => '1457355524',
        'origname' => 'SOUNDBITES_Apigeon4.jpg',
      ),
      '3' => array(
        'fid' => '42072',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SOUNDBITES_Apigeon5.jpg',
        'filepath' => 'files/fmag_story/2016/Feb/SOUNDBITES_Apigeon5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '713204',
        'status' => '1',
        'timestamp' => '1457355560',
        'origname' => 'SOUNDBITES_Apigeon5.jpg',
      ),
      '4' => array(
        'fid' => '42073',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SOUNDBITES_Apigeon6.jpg',
        'filepath' => 'files/fmag_story/2016/Feb/SOUNDBITES_Apigeon6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '294999',
        'status' => '1',
        'timestamp' => '1457355573',
        'origname' => 'SOUNDBITES_Apigeon6.jpg',
      ),
      '5' => array(
        'fid' => '42074',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SOUNDBITES_Apigeon7.jpg',
        'filepath' => 'files/fmag_story/2016/Feb/SOUNDBITES_Apigeon7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '551113',
        'status' => '1',
        'timestamp' => '1457355586',
        'origname' => 'SOUNDBITES_Apigeon7.jpg',
      ),
    ),
    'path' => 'stories/soundbites-apigeon',
    'tags' => array(
      '1' => array(
        '3412' => array(
          'tid' => '3412',
          'vid' => '1',
          'name' => 'SCOOTER LaFORGE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'SCOOTER LaFORGE',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => '985d790e-2908-11e6-9079-3cfd4048aa7d',
    'is_new' => FALSE,
    'timestamp' => 1464902757,
    'xmlsitemap' => array(
      'id' => '5388',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5388',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1464902757',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5388',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
