array(
  array(
    'nid' => '5424',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1462922685',
    'changed' => 1464902792,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5424',
    'revision_uid' => '1',
    'title' => 'Cool: Logan Trent by Wendy Hope',
    'body' => '<p>
	Logan is cool.<br />
	Exclusive photography by <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a>.</p>
',
    'teaser' => '<p>
	Logan is cool.<br />
	Exclusive photography by <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a>.</p>
',
    'revision_timestamp' => '1462923084',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope</a> essays <a href="http://rednyc.com/">Red</a> model Logan Trent.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHER<br />
	<a href="http://abtp.com/Photographers/Beauty/Wendy-Hope">Wendy Hope<br />
	at ABTP</a><br />
	&nbsp;</p>
<p>
	SUBJECT<br />
	Logan Trent</p>
<p>
	HAIR<br />
	<a href="http://abtp.com/Hair/Hair/Bradley-Irion/Biography">Bradley Irion<br />
	at ABTP&nbsp;&nbsp; &nbsp;</a></p>
<p>
	MAKEUP<br />
	Margina Dennis<br />
	at <a href="http://www.stocklandmartel.com/talent/margina-dennis/photography">Stockland Martel</a></p>
<p>
	STYLING<br />
	<a href="http://www.jadechung.co/about/">Jade C. Chung</a></p>
<p>
	<a href="http://rednyc.com/">Red NYC</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '42604',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL Logan FINAL2.jpg',
        'filepath' => 'files/fmag_story/2016/May/COOL Logan FINAL2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102848',
        'status' => '1',
        'timestamp' => '1462922599',
        'origname' => 'COOL Logan FINAL2.jpg',
      ),
      '1' => array(
        'fid' => '42605',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL Logan FINAL3.jpg',
        'filepath' => 'files/fmag_story/2016/May/COOL Logan FINAL3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '415029',
        'status' => '1',
        'timestamp' => '1462922607',
        'origname' => 'COOL Logan FINAL3.jpg',
      ),
      '2' => array(
        'fid' => '42607',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL Logan FINAL4.jpg',
        'filepath' => 'files/fmag_story/2016/May/COOL Logan FINAL4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '373051',
        'status' => '1',
        'timestamp' => '1462922621',
        'origname' => 'COOL Logan FINAL4.jpg',
      ),
      '3' => array(
        'fid' => '42609',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL Logan FINAL5.jpg',
        'filepath' => 'files/fmag_story/2016/May/COOL Logan FINAL5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '385070',
        'status' => '1',
        'timestamp' => '1462922643',
        'origname' => 'COOL Logan FINAL5.jpg',
      ),
      '4' => array(
        'fid' => '42611',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL Logan FINAL6.jpg',
        'filepath' => 'files/fmag_story/2016/May/COOL Logan FINAL6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '488146',
        'status' => '1',
        'timestamp' => '1462922652',
        'origname' => 'COOL Logan FINAL6.jpg',
      ),
      '5' => array(
        'fid' => '42613',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL Logan FINAL7.jpg',
        'filepath' => 'files/fmag_story/2016/May/COOL Logan FINAL7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '277941',
        'status' => '1',
        'timestamp' => '1462922661',
        'origname' => 'COOL Logan FINAL7.jpg',
      ),
      '6' => array(
        'fid' => '42615',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL Logan FINAL8.jpg',
        'filepath' => 'files/fmag_story/2016/May/COOL Logan FINAL8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '326377',
        'status' => '1',
        'timestamp' => '1462922670',
        'origname' => 'COOL Logan FINAL8.jpg',
      ),
      '7' => array(
        'fid' => '42616',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'COOL Logan FINAL9.jpg',
        'filepath' => 'files/fmag_story/2016/May/COOL Logan FINAL9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '192096',
        'status' => '1',
        'timestamp' => '1462922680',
        'origname' => 'COOL Logan FINAL9.jpg',
      ),
    ),
    'path' => 'stories/cool-logan-trent-wendy-hope',
    'tags' => NULL,
    'taxonomy' => array(),
    'files' => array(),
    'page_title' => '',
    'uuid' => 'ad241546-2908-11e6-9079-3cfd4048aa7d',
    'is_new' => FALSE,
    'timestamp' => 1464902792,
    'xmlsitemap' => array(
      'id' => '5424',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5424',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1464902792',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5424',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
