array(
  array(
    'nid' => '309',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1167967591',
    'changed' => '1403919990',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '309',
    'revision_uid' => '1',
    'title' => ' GOLDEN BOY',
    'body' => '<p>
	Fair-haired dazzler Jamesson Beane.<br />
	Photography by Ryan Prado.</p>
',
    'teaser' => '<p>
	Fair-haired dazzler Jamesson Beane.<br />
	Photography by Ryan Prado.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919990',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	RYAN PRADO</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1167',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blonde_JAN07.jpg',
        'filepath' => 'files/fmag_story/2007/Jan/blonde_JAN07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '256733',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blonde_JAN07.jpg',
      ),
      '1' => array(
        'fid' => '1168',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blonde2_JAN07.jpg',
        'filepath' => 'files/fmag_story/2007/Jan/blonde2_JAN07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '328278',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blonde2_JAN07.jpg',
      ),
      '2' => array(
        'fid' => '1169',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blonde3_JAN07.jpg',
        'filepath' => 'files/fmag_story/2007/Jan/blonde3_JAN07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '256830',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blonde3_JAN07.jpg',
      ),
      '3' => array(
        'fid' => '1170',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blonde4_JAN07.jpg',
        'filepath' => 'files/fmag_story/2007/Jan/blonde4_JAN07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '264884',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blonde4_JAN07.jpg',
      ),
      '4' => array(
        'fid' => '1171',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blonde5_JAN07.jpg',
        'filepath' => 'files/fmag_story/2007/Jan/blonde5_JAN07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128003',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blonde5_JAN07.jpg',
      ),
      '5' => array(
        'fid' => '1172',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'blonde6_JAN07.jpg',
        'filepath' => 'files/fmag_story/2007/Jan/blonde6_JAN07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '197756',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'blonde6_JAN07.jpg',
      ),
    ),
    'path' => 'stories/golden-boy',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2438' => array(
          'tid' => '2438',
          'vid' => '5',
          'name' => 'RYAN PRADO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'men',
        '5' => 'RYAN PRADO',
      ),
      '2' => array(
        '2' => '2',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)