array(
  array(
    'nid' => '321',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1168896970',
    'changed' => '1337806633',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '321',
    'revision_uid' => '1',
    'title' => ' SWEATER BOY',
    'body' => '<p>
	Pull one over on yourself.<br />
	Photography by Sophie Kinachtchouk.</p>
',
    'teaser' => '<p>
	Pull one over on yourself.<br />
	Photography by Sophie Kinachtchouk.</p>
',
    'log' => '',
    'revision_timestamp' => '1337806633',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	SOPHIE KINACHTCHOUK</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1200',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sweater1_JAN07.jpg',
        'filepath' => 'files/fmag_story/2007/Jan/sweater1_JAN07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '221213',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sweater1_JAN07.jpg',
      ),
      '1' => array(
        'fid' => '1201',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sweater2_JAN07.jpg',
        'filepath' => 'files/fmag_story/2007/Jan/sweater2_JAN07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '199668',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sweater2_JAN07.jpg',
      ),
      '2' => array(
        'fid' => '1202',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sweater3_JAN07.jpg',
        'filepath' => 'files/fmag_story/2007/Jan/sweater3_JAN07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '220300',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sweater3_JAN07.jpg',
      ),
      '3' => array(
        'fid' => '1203',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sweater4_JAN07.jpg',
        'filepath' => 'files/fmag_story/2007/Jan/sweater4_JAN07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '281678',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sweater4_JAN07.jpg',
      ),
    ),
    'path' => 'stories/sweater-boy',
    'tags' => array(
      '1' => array(
        '649' => array(
          'tid' => '649',
          'vid' => '1',
          'name' => '4you',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '648' => array(
          'tid' => '648',
          'vid' => '1',
          'name' => 'Izod',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '189' => array(
          'tid' => '189',
          'vid' => '1',
          'name' => 'RALPH LAUREN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2429' => array(
          'tid' => '2429',
          'vid' => '5',
          'name' => 'Sophie Kinachtchouk',
          'description' => 'http://www.skphotography.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => '4you, Izod, RALPH LAUREN',
        '5' => 'Sophie Kinachtchouk',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)