array(
  array(
    'nid' => '442',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1173911454',
    'changed' => '1337806750',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '442',
    'revision_uid' => '1',
    'title' => ' NO ASSEMBLY REQUIRED',
    'body' => '<p>
	Effortless Spring looks baby.<br />
	Photography by Sophie Kinachtchouk.</p>
',
    'teaser' => '<p>
	Effortless Spring looks baby.<br />
	Photography by Sophie Kinachtchouk.</p>
',
    'log' => '',
    'revision_timestamp' => '1337806750',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	SOPHIE KINACHTCHOUK</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1311',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'no_MAR07.jpg',
        'filepath' => 'files/fmag_story/2007/Mar/no_MAR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '184818',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'no_MAR07.jpg',
      ),
      '1' => array(
        'fid' => '1312',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'no2_MAR07.jpg',
        'filepath' => 'files/fmag_story/2007/Mar/no2_MAR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '110768',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'no2_MAR07.jpg',
      ),
      '2' => array(
        'fid' => '1313',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'no4_MAR07.jpg',
        'filepath' => 'files/fmag_story/2007/Mar/no4_MAR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92744',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'no4_MAR07.jpg',
      ),
      '3' => array(
        'fid' => '1316',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'no3_MAR07.jpg',
        'filepath' => 'files/fmag_story/2007/Mar/no3_MAR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86803',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'no3_MAR07.jpg',
      ),
      '4' => array(
        'fid' => '1314',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'no5_MAR07.jpg',
        'filepath' => 'files/fmag_story/2007/Mar/no5_MAR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '474005',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'no5_MAR07.jpg',
      ),
      '5' => array(
        'fid' => '1315',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'no6_MAR07.jpg',
        'filepath' => 'files/fmag_story/2007/Mar/no6_MAR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102476',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'no6_MAR07.jpg',
      ),
    ),
    'path' => 'stories/no-assembly-required',
    'tags' => array(
      '1' => array(
        '261' => array(
          'tid' => '261',
          'vid' => '1',
          'name' => 'old navy',
          'description' => '<a href="http://rstyle.me/ad/u6qpukw">oldnavy.com</a><div class="gallery-adbanner"><a href="http://rstyle.me/ad/u6qpukw" target="_blank"><img src="http://www.awltovhc.com/image-4441350-10838400" /></a></div>',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2429' => array(
          'tid' => '2429',
          'vid' => '5',
          'name' => 'Sophie Kinachtchouk',
          'description' => 'http://www.skphotography.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'old navy',
        '5' => 'Sophie Kinachtchouk',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)