array(
  array(
    'nid' => '495',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1176704311',
    'changed' => '1403920372',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '495',
    'revision_uid' => '1',
    'title' => ' RAW LIKE SUSHI',
    'body' => '<p>
	Sexy looks to eat up fresh.<br />
	Photography by Sophie Kinachtchouk.</p>
',
    'teaser' => '<p>
	Sexy looks to eat up fresh.<br />
	Photography by Sophie Kinachtchouk.</p>
',
    'log' => '',
    'revision_timestamp' => '1403920372',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	SOPHIE KINCHTCHOUK</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1341',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'raw_APR07.jpg',
        'filepath' => 'files/fmag_story/2007/Apr/raw_APR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '121197',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'raw_APR07.jpg',
      ),
      '1' => array(
        'fid' => '1342',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'raw2_APR07.jpg',
        'filepath' => 'files/fmag_story/2007/Apr/raw2_APR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '225022',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'raw2_APR07.jpg',
      ),
      '2' => array(
        'fid' => '1343',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'raw4_APR07.jpg',
        'filepath' => 'files/fmag_story/2007/Apr/raw4_APR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '238680',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'raw4_APR07.jpg',
      ),
      '3' => array(
        'fid' => '1344',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'raw5_APR07.jpg',
        'filepath' => 'files/fmag_story/2007/Apr/raw5_APR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97455',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'raw5_APR07.jpg',
      ),
    ),
    'path' => 'stories/raw-sushi',
    'tags' => array(
      '1' => array(
        '261' => array(
          'tid' => '261',
          'vid' => '1',
          'name' => 'old navy',
          'description' => '<a href="http://rstyle.me/ad/u6qpukw">oldnavy.com</a><div class="gallery-adbanner"><a href="http://rstyle.me/ad/u6qpukw" target="_blank"><img src="http://www.awltovhc.com/image-4441350-10838400" /></a></div>',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2435' => array(
          'tid' => '2435',
          'vid' => '5',
          'name' => 'SOPHIE KINCHTCHOUK',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'old navy',
        '5' => 'SOPHIE KINCHTCHOUK',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)