array(
  array(
    'nid' => '503',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1177563725',
    'changed' => '1403919990',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '503',
    'revision_uid' => '1',
    'title' => ' SPARKS IT UP',
    'body' => '<p>
	Designer Philip Sparks does dashing duds.<br />
	Photography by Sophie Kinachtchouk.<br />
	Model ~ Jason.</p>
',
    'teaser' => '<p>
	Designer Philip Sparks does dashing duds.<br />
	Photography by Sophie Kinachtchouk.<br />
	Model ~ Jason.</p>
',
    'log' => '',
    'revision_timestamp' => '1403919990',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	SOPHIE KINACHTCHOUK</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1347',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sparks_APR07.jpg',
        'filepath' => 'files/fmag_story/2007/Apr/sparks_APR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '293374',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sparks_APR07.jpg',
      ),
      '1' => array(
        'fid' => '1348',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sparks2_APR07.jpg',
        'filepath' => 'files/fmag_story/2007/Apr/sparks2_APR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '263325',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sparks2_APR07.jpg',
      ),
      '2' => array(
        'fid' => '1349',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sparks3_APR07.jpg',
        'filepath' => 'files/fmag_story/2007/Apr/sparks3_APR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '306073',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sparks3_APR07.jpg',
      ),
      '3' => array(
        'fid' => '1350',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sparks4_APR07.jpg',
        'filepath' => 'files/fmag_story/2007/Apr/sparks4_APR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '183590',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sparks4_APR07.jpg',
      ),
      '4' => array(
        'fid' => '1351',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sparks5_APR07.jpg',
        'filepath' => 'files/fmag_story/2007/Apr/sparks5_APR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '426442',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sparks5_APR07.jpg',
      ),
      '5' => array(
        'fid' => '1352',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sparks6_APR07.jpg',
        'filepath' => 'files/fmag_story/2007/Apr/sparks6_APR07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '358734',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sparks6_APR07.jpg',
      ),
    ),
    'path' => 'stories/sparks-it',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '259' => array(
          'tid' => '259',
          'vid' => '1',
          'name' => 'philip sparks',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2429' => array(
          'tid' => '2429',
          'vid' => '5',
          'name' => 'Sophie Kinachtchouk',
          'description' => 'http://www.skphotography.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'men',
        '1' => 'philip sparks',
        '5' => 'Sophie Kinachtchouk',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)