array(
  array(
    'nid' => '5216',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1437417355',
    'changed' => '1437503447',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5216',
    'revision_uid' => '0',
    'title' => 'Flower Power',
    'body' => '<p>
	The dash of linen. Where wrinkled - for once - is right.<br />
	Exclusive photography by <a href="http://scottteitler.com/">Scott Teitler</a>.<br />
	Model - <span>Casey Levens at <a href="http://www.chosenmodels.com/">Chosen</a> &amp; <a href="http://www.mc2models.com/">MC2</a></span></p>
',
    'teaser' => '<p>
	The dash of linen. Where wrinkled - for once - is right.<br />
	Exclusive photography by <a href="http://scottteitler.com/">Scott Teitler</a>.<br />
	Model - <span>Casey Levens at <a href="http://www.chosenmodels.com/">Chosen</a> &amp; <a href="http://www.mc2models.com/">MC2</a></span></p>
',
    'log' => '',
    'revision_timestamp' => '1437503447',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Maestro <a href="http://scottteitler.com/">Scott Teitler</a> shoots <a href="http://www.chosenmodels.com/">Chosen</a> Models cool Casey Levens in summerlicious linens. Styling by Anthony Bermudez.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://scottteitler.com/">Scott Teitler</a><br />
	<br />
	<br />
	<br />
	STYLING<br />
	<a href="http://styledbybermudez.format.com/"><span style="font-family:-webkit-system-font,Helvetica Neue,Helvetica,sans-serif">Anthony Bermudez</span></a></p>
<p>
	<br />
	GROOMING<br />
	Evy Edelman<br />
	at GlossandGroom<br />
	using Oribe<br />
	&amp; <a href="http://camerareadycosmetics.com/">Camera Ready Cosmetics</a><br />
	<a href="http://www.courtneyhagen.com/"> </a></p>
<p>
	&nbsp;</p>
<p>
	<span>MODEL<br />
	Casey Levens<br />
	at <a href="http://www.chosenmodels.com/">Chosen</a> &amp; <a href="http://www.mc2models.com/">MC2</a><br />
	</span></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '38387',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer2.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '933743',
        'status' => '1',
        'timestamp' => '1437417175',
        'origname' => 'erin-van-dongen-alex-beer2.jpg',
      ),
      '1' => array(
        'fid' => '38389',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer3.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '145012',
        'status' => '1',
        'timestamp' => '1437417186',
        'origname' => 'erin-van-dongen-alex-beer3.jpg',
      ),
      '2' => array(
        'fid' => '38391',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer4.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '70632',
        'status' => '1',
        'timestamp' => '1437417194',
        'origname' => 'erin-van-dongen-alex-beer4.jpg',
      ),
      '3' => array(
        'fid' => '38392',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer5.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1018789',
        'status' => '1',
        'timestamp' => '1437417209',
        'origname' => 'erin-van-dongen-alex-beer5.jpg',
      ),
      '4' => array(
        'fid' => '38393',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer6.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '884352',
        'status' => '1',
        'timestamp' => '1437417251',
        'origname' => 'erin-van-dongen-alex-beer6.jpg',
      ),
      '5' => array(
        'fid' => '38395',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer7.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '629528',
        'status' => '1',
        'timestamp' => '1437417266',
        'origname' => 'erin-van-dongen-alex-beer7.jpg',
      ),
      '6' => array(
        'fid' => '38397',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer8.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66275',
        'status' => '1',
        'timestamp' => '1437417276',
        'origname' => 'erin-van-dongen-alex-beer8.jpg',
      ),
      '7' => array(
        'fid' => '38399',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer9.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '561660',
        'status' => '1',
        'timestamp' => '1437417289',
        'origname' => 'erin-van-dongen-alex-beer9.jpg',
      ),
      '8' => array(
        'fid' => '38400',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer10.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '635086',
        'status' => '1',
        'timestamp' => '1437417300',
        'origname' => 'erin-van-dongen-alex-beer10.jpg',
      ),
      '9' => array(
        'fid' => '38402',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer11.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63071',
        'status' => '1',
        'timestamp' => '1437417322',
        'origname' => 'erin-van-dongen-alex-beer11.jpg',
      ),
      '10' => array(
        'fid' => '38404',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer12.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97082',
        'status' => '1',
        'timestamp' => '1437417333',
        'origname' => 'erin-van-dongen-alex-beer12.jpg',
      ),
      '11' => array(
        'fid' => '38405',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'erin-van-dongen-alex-beer13.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/erin-van-dongen-alex-beer13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '880492',
        'status' => '1',
        'timestamp' => '1437417342',
        'origname' => 'erin-van-dongen-alex-beer13.jpg',
      ),
    ),
    'path' => 'stories/flower-power',
    'tags' => NULL,
    'publish_on' => '1437472800',
    'unpublish_on' => '0',
    'scheduler' => array(
      'publish_on' => '1437472800',
      'unpublish_on' => '0',
      'published' => 'Tuesday, July 21, 2015 - 06:00',
      'unpublished' => NULL,
    ),
    'taxonomy' => array(),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
