array(
  array(
    'nid' => '529',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1179845769',
    'changed' => '1403920372',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '529',
    'revision_uid' => '1',
    'title' => ' SEXY BLACK',
    'body' => '<p>
	Sleek skinbaring looks.<br />
	Photography by Steve Carty.<br />
	Model ~ Magda.</p>
',
    'teaser' => '<p>
	Sleek skinbaring looks.<br />
	Photography by Steve Carty.<br />
	Model ~ Magda.</p>
',
    'log' => '',
    'revision_timestamp' => '1403920372',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	STEVE CARTY</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1372',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sexyblack_MAY07.jpg',
        'filepath' => 'files/fmag_story/2007/May/sexyblack_MAY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '316236',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sexyblack_MAY07.jpg',
      ),
      '1' => array(
        'fid' => '1373',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sexyblack2_MAY07.jpg',
        'filepath' => 'files/fmag_story/2007/May/sexyblack2_MAY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '196529',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sexyblack2_MAY07.jpg',
      ),
      '2' => array(
        'fid' => '1374',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sexyblack5_MAY07.jpg',
        'filepath' => 'files/fmag_story/2007/May/sexyblack5_MAY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '209271',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sexyblack5_MAY07.jpg',
      ),
      '3' => array(
        'fid' => '1375',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'sexyblack6_MAY07.jpg',
        'filepath' => 'files/fmag_story/2007/May/sexyblack6_MAY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63563',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'sexyblack6_MAY07.jpg',
      ),
    ),
    'path' => 'stories/sexy-black',
    'tags' => array(
      '1' => array(
        '129' => array(
          'tid' => '129',
          'vid' => '1',
          'name' => 'American Apparel',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2441' => array(
          'tid' => '2441',
          'vid' => '5',
          'name' => 'STEVE CARTY',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'American Apparel',
        '5' => 'STEVE CARTY',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)