array(
  array(
    'nid' => '587',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1182473703',
    'changed' => '1403920372',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '587',
    'revision_uid' => '1',
    'title' => ' Jiffy Pop',
    'body' => '<p>
	Little dresses that make a big noise.<br />
	Photography by Sophie Kinactchouk.<br />
	Grooming by Jodi Thibodeau.<br />
	Styling by Reid &amp; Nixon.</p>
',
    'teaser' => '<p>
	Little dresses that make a big noise.<br />
	Photography by Sophie Kinactchouk.<br />
	Grooming by Jodi Thibodeau.<br />
	Styling by Reid &amp; Nixon.</p>
',
    'log' => '',
    'revision_timestamp' => '1403920372',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	SOPHIE KINACHTCHOUK</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1425',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'jiffypop-1.jpg',
        'filepath' => 'files/fmag_story/2007/Jun/jiffypop-1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '200420',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'jiffypop-1.jpg',
      ),
      '1' => array(
        'fid' => '1426',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'jiffypop-2.jpg',
        'filepath' => 'files/fmag_story/2007/Jun/jiffypop-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '187182',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'jiffypop-2.jpg',
      ),
      '2' => array(
        'fid' => '1427',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'jiffypop-3.jpg',
        'filepath' => 'files/fmag_story/2007/Jun/jiffypop-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167881',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'jiffypop-3.jpg',
      ),
      '3' => array(
        'fid' => '1428',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'jiffypop-4.jpg',
        'filepath' => 'files/fmag_story/2007/Jun/jiffypop-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '176249',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'jiffypop-4.jpg',
      ),
      '4' => array(
        'fid' => '1429',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'jiffypop-5.jpg',
        'filepath' => 'files/fmag_story/2007/Jun/jiffypop-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '218043',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'jiffypop-5.jpg',
      ),
      '5' => array(
        'fid' => '1430',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'jiffypop-6.jpg',
        'filepath' => 'files/fmag_story/2007/Jun/jiffypop-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124182',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'jiffypop-6.jpg',
      ),
    ),
    'path' => 'stories/jiffy-pop',
    'tags' => array(
      '1' => array(
        '676' => array(
          'tid' => '676',
          'vid' => '1',
          'name' => 'Annistar',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '677' => array(
          'tid' => '677',
          'vid' => '1',
          'name' => 'Ripe',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2429' => array(
          'tid' => '2429',
          'vid' => '5',
          'name' => 'Sophie Kinachtchouk',
          'description' => 'http://www.skphotography.ca/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Annistar, Ripe',
        '5' => 'Sophie Kinachtchouk',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)