array(
  array(
    'nid' => '627',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1191939081',
    'changed' => '1303573026',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '627',
    'revision_uid' => '1',
    'title' => ' HEY MR DJ',
    'body' => '<p>
	Spinmaster DJ Nickel.<br />
	Photography by Edward StGeorge.</p>
',
    'teaser' => '<p>
	Spinmaster DJ Nickel.<br />
	Photography by Edward StGeorge.</p>
',
    'log' => '',
    'revision_timestamp' => '1303573026',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	EDWARD S+GEORGE</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1464',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nickel_JULY07.jpg',
        'filepath' => 'files/fmag_story/2007/Jul/nickel_JULY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128748',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'nickel_JULY07.jpg',
      ),
      '1' => array(
        'fid' => '1465',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nickel2_JULY07.jpg',
        'filepath' => 'files/fmag_story/2007/Jul/nickel2_JULY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '143832',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'nickel2_JULY07.jpg',
      ),
      '2' => array(
        'fid' => '1466',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nickel3_JULY07.jpg',
        'filepath' => 'files/fmag_story/2007/Jul/nickel3_JULY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '189970',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'nickel3_JULY07.jpg',
      ),
      '3' => array(
        'fid' => '1467',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nickel4_JULY07.jpg',
        'filepath' => 'files/fmag_story/2007/Jul/nickel4_JULY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '192699',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'nickel4_JULY07.jpg',
      ),
      '4' => array(
        'fid' => '1468',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nickel5_JULY07.jpg',
        'filepath' => 'files/fmag_story/2007/Jul/nickel5_JULY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '180519',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'nickel5_JULY07.jpg',
      ),
      '5' => array(
        'fid' => '1469',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'nickel6_JULY07.jpg',
        'filepath' => 'files/fmag_story/2007/Jul/nickel6_JULY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156826',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'nickel6_JULY07.jpg',
      ),
    ),
    'path' => 'stories/hey-mr-dj',
    'tags' => array(
      '5' => array(
        '2406' => array(
          'tid' => '2406',
          'vid' => '5',
          'name' => 'EDWARD S+GEORGE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'EDWARD S+GEORGE',
      ),
      '2' => array(
        '2' => '2',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)