array(
  array(
    'nid' => '649',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1185565429',
    'changed' => '1337806905',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '649',
    'revision_uid' => '1',
    'title' => ' BLACK AND WHITE in Color',
    'body' => '<p>
	Sexy evening glam.<br />
	Photography by Andy Lee .<br />
	Styling by Sandra D&#39;Angelo.<br />
	Model ~ Rachel.</p>
',
    'teaser' => '<p>
	Sexy evening glam.<br />
	Photography by Andy Lee .<br />
	Styling by Sandra D&#39;Angelo.<br />
	Model ~ Rachel.</p>
',
    'log' => '',
    'revision_timestamp' => '1337806905',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	ANDY LEE</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1476',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BW_JULY07.jpg',
        'filepath' => 'files/fmag_story/2007/Jul/BW_JULY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '261179',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BW_JULY07.jpg',
      ),
      '1' => array(
        'fid' => '1477',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BW2_JULY07.jpg',
        'filepath' => 'files/fmag_story/2007/Jul/BW2_JULY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '364941',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BW2_JULY07.jpg',
      ),
      '2' => array(
        'fid' => '1478',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BW3_JULY07.jpg',
        'filepath' => 'files/fmag_story/2007/Jul/BW3_JULY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '212945',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BW3_JULY07.jpg',
      ),
      '3' => array(
        'fid' => '1479',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BW4_JULY07.jpg',
        'filepath' => 'files/fmag_story/2007/Jul/BW4_JULY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '217087',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BW4_JULY07.jpg',
      ),
      '4' => array(
        'fid' => '1480',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BW5_JULY07.jpg',
        'filepath' => 'files/fmag_story/2007/Jul/BW5_JULY07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '304072',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'BW5_JULY07.jpg',
      ),
    ),
    'path' => 'stories/black-and-white-color',
    'tags' => array(
      '1' => array(
        '266' => array(
          'tid' => '266',
          'vid' => '1',
          'name' => 'ALICE  and OLIVIA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '267' => array(
          'tid' => '267',
          'vid' => '1',
          'name' => 'carmen marc valvo',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '200' => array(
          'tid' => '200',
          'vid' => '1',
          'name' => 'TOPSHOP',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '239' => array(
          'tid' => '239',
          'vid' => '1',
          'name' => 'TORY BURCH',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2436' => array(
          'tid' => '2436',
          'vid' => '5',
          'name' => 'ANDY LEE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'ALICE  and OLIVIA, carmen marc valvo, TOPSHOP, TORY BURCH',
        '5' => 'ANDY LEE',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)