array(
  array(
    'nid' => '689',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1187048960',
    'changed' => '1303572729',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '689',
    'revision_uid' => '1',
    'title' => ' KNOT NOW',
    'body' => '<p>
	Tie him up.<br />
	Photography by <a href="http://www.lindsaylozon.com/" target="_blank">Lindsay Lozon</a>.<br />
	Styling by Reid and Nixon.<br />
	Model ~ Doron.</p>
',
    'teaser' => '<p>
	Tie him up.<br />
	Photography by <a href="http://www.lindsaylozon.com/" target="_blank">Lindsay Lozon</a>.<br />
	Styling by Reid and Nixon.<br />
	Model ~ Doron.</p>
',
    'log' => '',
    'revision_timestamp' => '1303572729',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.lindsaylozon.com/" target="_blank">Lindsay Lozon</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1506',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'knot_AUG07.jpg',
        'filepath' => 'files/fmag_story/2007/Aug/knot_AUG07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95614',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'knot_AUG07.jpg',
      ),
      '1' => array(
        'fid' => '1507',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'knot2_AUG07.jpg',
        'filepath' => 'files/fmag_story/2007/Aug/knot2_AUG07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76789',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'knot2_AUG07.jpg',
      ),
      '2' => array(
        'fid' => '1508',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'knot3_AUG07.jpg',
        'filepath' => 'files/fmag_story/2007/Aug/knot3_AUG07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88900',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'knot3_AUG07.jpg',
      ),
      '3' => array(
        'fid' => '1509',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'knot4_AUG07.jpg',
        'filepath' => 'files/fmag_story/2007/Aug/knot4_AUG07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '64504',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'knot4_AUG07.jpg',
      ),
    ),
    'path' => 'stories/knot-now',
    'tags' => array(
      '5' => array(
        '2417' => array(
          'tid' => '2417',
          'vid' => '5',
          'name' => 'Lindsay Lozon',
          'description' => 'http://www.lindsaylozon.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Lindsay Lozon',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)