array(
  array(
    'nid' => '740',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1189445859',
    'changed' => '1403920372',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '740',
    'revision_uid' => '1',
    'title' => 'THE SHIPPING NEWS',
    'body' => '<p>
	Fall fashion arrives. Toronto&#39;s Boutique Le Trou gets the goods.<br />
	Photography by <a href="http://www.kirkimages.com/" target="_blank">Jeff Kirk</a>.<br />
	Model ~ Anna@NAM Toronto.</p>
',
    'teaser' => '<p>
	Fall fashion arrives. Toronto&#39;s Boutique Le Trou gets the goods.<br />
	Photography by <a href="http://www.kirkimages.com/" target="_blank">Jeff Kirk</a>.<br />
	Model ~ Anna@NAM Toronto.</p>
',
    'log' => '',
    'revision_timestamp' => '1403920372',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.kirkimages.com/" target="_blank">Jeff Kirk</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1546',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shipping_SEPT07.jpg',
        'filepath' => 'files/fmag_story/2007/Sep/shipping_SEPT07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88162',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shipping_SEPT07.jpg',
      ),
      '1' => array(
        'fid' => '1547',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shipping2_SEPT07.jpg',
        'filepath' => 'files/fmag_story/2007/Sep/shipping2_SEPT07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74222',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shipping2_SEPT07.jpg',
      ),
      '2' => array(
        'fid' => '1548',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shipping3_SEPT07.jpg',
        'filepath' => 'files/fmag_story/2007/Sep/shipping3_SEPT07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '121412',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shipping3_SEPT07.jpg',
      ),
      '3' => array(
        'fid' => '1549',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'shipping4_SEPT07.jpg',
        'filepath' => 'files/fmag_story/2007/Sep/shipping4_SEPT07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72511',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'shipping4_SEPT07.jpg',
      ),
    ),
    'path' => 'stories/shipping-news',
    'tags' => array(
      '5' => array(
        '2440' => array(
          'tid' => '2440',
          'vid' => '5',
          'name' => 'Jeff Kirk',
          'description' => 'http://www.kirkimages.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '262' => array(
          'tid' => '262',
          'vid' => '1',
          'name' => 'penny black',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '268' => array(
          'tid' => '268',
          'vid' => '1',
          'name' => 'sarah pacini',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '269' => array(
          'tid' => '269',
          'vid' => '1',
          'name' => 'zoran dobric',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Jeff Kirk',
        '1' => 'penny black, sarah pacini, zoran dobric',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)