array(
  array(
    'nid' => '825',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1196700549',
    'changed' => '1300828361',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '825',
    'revision_uid' => '1',
    'title' => ' TURNING JAPANESE',
    'body' => '<p>
	Photographer Andrea Vecchiato reports.<br />
	Photography by <a href="http://www.andreavecchiatophotography.com" target="_blank">Andrea Vecchiato</a>.</p>
',
    'teaser' => '<p>
	Photographer Andrea Vecchiato reports.<br />
	Photography by <a href="http://www.andreavecchiatophotography.com" target="_blank">Andrea Vecchiato</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1300828361',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.andreavecchiatophotography.com" target="_blank">Andrea Vecchiato</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1569',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'japan_SEPT07.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/japan_SEPT07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '184528',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'japan_SEPT07.jpg',
      ),
      '1' => array(
        'fid' => '1570',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'japan3_EPT07.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/japan3_EPT07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131955',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'japan3_EPT07.jpg',
      ),
      '2' => array(
        'fid' => '1571',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'japan4_SEPT07.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/japan4_SEPT07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '146465',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'japan4_SEPT07.jpg',
      ),
      '3' => array(
        'fid' => '1572',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'japan5_SEPT07.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/japan5_SEPT07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124258',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'japan5_SEPT07.jpg',
      ),
      '4' => array(
        'fid' => '1573',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'japan6_SEPT07.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/japan6_SEPT07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153676',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'japan6_SEPT07.jpg',
      ),
      '5' => array(
        'fid' => '1574',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'japan7_SEPT07.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/japan7_SEPT07.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '152647',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'japan7_SEPT07.jpg',
      ),
    ),
    'path' => 'stories/turning-japanese',
    'tags' => array(
      '5' => array(
        '2446' => array(
          'tid' => '2446',
          'vid' => '5',
          'name' => 'Andrea Vecchiato',
          'description' => 'http://www.andreavecchiatophotography.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Andrea Vecchiato',
      ),
      '2' => array(
        '2' => '2',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)