array(
  array(
    'nid' => '884',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1193611518',
    'changed' => '1300828455',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '884',
    'revision_uid' => '1',
    'title' => ' SPECIAL K',
    'body' => '<p>
	James chats up actress Kristen Kerr.<br />
	Photography by Edward StGeorge.</p>
',
    'teaser' => '<p>
	James chats up actress Kristen Kerr.<br />
	Photography by Edward StGeorge.</p>
',
    'log' => '',
    'revision_timestamp' => '1300828455',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	EDWARD S+GEORGE</p>
<p>
	INTERVIEW<br />
	JAMES N</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1621',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kerr.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/kerr.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '214524',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'kerr.jpg',
      ),
      '1' => array(
        'fid' => '1625',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kerr5.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/kerr5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '135730',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'kerr5.jpg',
      ),
      '2' => array(
        'fid' => '1622',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kerr2.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/kerr2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '254349',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'kerr2.jpg',
      ),
      '3' => array(
        'fid' => '1623',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kerr3.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/kerr3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '289199',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'kerr3.jpg',
      ),
      '4' => array(
        'fid' => '1624',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kerr4.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/kerr4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '286364',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'kerr4.jpg',
      ),
      '5' => array(
        'fid' => '1626',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kerr6.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/kerr6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '206070',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'kerr6.jpg',
      ),
      '6' => array(
        'fid' => '1627',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kerr7.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/kerr7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '200507',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'kerr7.jpg',
      ),
      '7' => array(
        'fid' => '1628',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'kerr8.jpg',
        'filepath' => 'files/fmag_story/2007/Oct/kerr8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '191803',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'kerr8.jpg',
      ),
    ),
    'path' => 'stories/special-k',
    'tags' => array(
      '5' => array(
        '2406' => array(
          'tid' => '2406',
          'vid' => '5',
          'name' => 'EDWARD S+GEORGE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'EDWARD S+GEORGE',
      ),
      '2' => array(
        '2' => '2',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)