#!/bin/bash
wp fmagimport node update 1002.inc
wp fmagimport node update 1018.inc
wp fmagimport node update 1039.inc
wp fmagimport node update 15.inc
wp fmagimport node update 1976.inc
wp fmagimport node update 2593.inc
wp fmagimport node update 309.inc
wp fmagimport node update 316.inc
wp fmagimport node update 321.inc
wp fmagimport node update 323.inc
wp fmagimport node update 332.inc
wp fmagimport node update 338.inc
wp fmagimport node update 345.inc
wp fmagimport node update 350.inc
wp fmagimport node update 354.inc
wp fmagimport node update 360.inc
wp fmagimport node update 372.inc
wp fmagimport node update 378.inc
wp fmagimport node update 391.inc
wp fmagimport node update 415.inc
wp fmagimport node update 426.inc
wp fmagimport node update 436.inc
wp fmagimport node update 442.inc
wp fmagimport node update 461.inc
wp fmagimport node update 468.inc
wp fmagimport node update 488.inc
wp fmagimport node update 495.inc
wp fmagimport node update 497.inc
wp fmagimport node update 503.inc
wp fmagimport node update 512.inc
wp fmagimport node update 5198.inc
wp fmagimport node update 5216.inc
wp fmagimport node update 522.inc
wp fmagimport node update 529.inc
wp fmagimport node update 537.inc
wp fmagimport node update 540.inc
wp fmagimport node update 552.inc
wp fmagimport node update 557.inc
wp fmagimport node update 559.inc
wp fmagimport node update 574.inc
wp fmagimport node update 581.inc
wp fmagimport node update 587.inc
wp fmagimport node update 595.inc
wp fmagimport node update 614.inc
wp fmagimport node update 621.inc
wp fmagimport node update 627.inc
wp fmagimport node update 641.inc
wp fmagimport node update 644.inc
wp fmagimport node update 649.inc
wp fmagimport node update 674.inc
wp fmagimport node update 689.inc
wp fmagimport node update 700.inc
wp fmagimport node update 723.inc
wp fmagimport node update 725.inc
wp fmagimport node update 735.inc
wp fmagimport node update 740.inc
wp fmagimport node update 743.inc
wp fmagimport node update 75.inc
wp fmagimport node update 774.inc
wp fmagimport node update 799.inc
wp fmagimport node update 825.inc
wp fmagimport node update 828.inc
wp fmagimport node update 841.inc
wp fmagimport node update 851.inc
wp fmagimport node update 863.inc
wp fmagimport node update 876.inc
wp fmagimport node update 884.inc
wp fmagimport node update 897.inc
wp fmagimport node update 912.inc
wp fmagimport node update 919.inc
wp fmagimport node update 927.inc
wp fmagimport node update 950.inc
wp fmagimport node update 957.inc
wp fmagimport node update 967.inc