array(
  array(
    'nid' => '4330',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1357266483',
    'changed' => '1403837916',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4330',
    'revision_uid' => '1',
    'title' => 'The Widow',
    'body' => '<p>
	Mourning Becomes Larissa.<br />
	Exclusive photography by <a href="http://www.alexanderbeerphotography.com/">Alexander Beer</a>.<br />
	Model - Larissa at Nevs.</p>
',
    'teaser' => '<p>
	Mourning Becomes Larissa.<br />
	Exclusive photography by <a href="http://www.alexanderbeerphotography.com/">Alexander Beer</a>.<br />
	Model - Larissa at Nevs.</p>
',
    'log' => '',
    'revision_timestamp' => '1403837916',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<a href="http://www.alexanderbeerphotography.com/"><br />
	ALEXANDER BEER</a></p>
<p>
	STYLING<br />
	VXI ADAMS</p>
<p>
	HAIR<br />
	MICHAEL BOSACKI</p>
<p>
	MAKEUP<br />
	JONAS OLIVER<br />
	USING MAC PRO</p>
<p>
	MODEL<br />
	LARISSA<br />
	AT NEVS</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '23256',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'The-Widow_2.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/The-Widow_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '365680',
        'status' => '1',
        'timestamp' => '1357266399',
        'origname' => 'The-Widow_2.jpg',
      ),
      '1' => array(
        'fid' => '23275',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'The-Widow_3.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/The-Widow_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '65129',
        'status' => '1',
        'timestamp' => '1357325567',
        'origname' => 'The-Widow_3.jpg',
      ),
      '2' => array(
        'fid' => '23260',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'The-Widow_4.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/The-Widow_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '226753',
        'status' => '1',
        'timestamp' => '1357266416',
        'origname' => 'The-Widow_4.jpg',
      ),
      '3' => array(
        'fid' => '23262',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'The-Widow_5.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/The-Widow_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '237862',
        'status' => '1',
        'timestamp' => '1357266427',
        'origname' => 'The-Widow_5.jpg',
      ),
      '4' => array(
        'fid' => '23264',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'The-Widow_6.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/The-Widow_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13682',
        'status' => '1',
        'timestamp' => '1357266434',
        'origname' => 'The-Widow_6.jpg',
      ),
      '5' => array(
        'fid' => '23266',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'The-Widow_7.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/The-Widow_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '152806',
        'status' => '1',
        'timestamp' => '1357266442',
        'origname' => 'The-Widow_7.jpg',
      ),
      '6' => array(
        'fid' => '23268',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'The-Widow_8.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/The-Widow_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16961',
        'status' => '1',
        'timestamp' => '1357266449',
        'origname' => 'The-Widow_8.jpg',
      ),
      '7' => array(
        'fid' => '23270',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'The-Widow_9.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/The-Widow_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '265416',
        'status' => '1',
        'timestamp' => '1357266459',
        'origname' => 'The-Widow_9.jpg',
      ),
      '8' => array(
        'fid' => '23272',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'The-Widow_10.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/The-Widow_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '231283',
        'status' => '1',
        'timestamp' => '1357266469',
        'origname' => 'The-Widow_10.jpg',
      ),
      '9' => array(
        'fid' => '23273',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'The-Widow_11.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/The-Widow_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17139',
        'status' => '1',
        'timestamp' => '1357266476',
        'origname' => 'The-Widow_11.jpg',
      ),
    ),
    'path' => 'stories/widow',
    'tags' => array(
      '5' => array(
        '2525' => array(
          'tid' => '2525',
          'vid' => '5',
          'name' => 'Alexander Beer',
          'description' => 'http://www.alexanderbeerphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '129' => array(
          'tid' => '129',
          'vid' => '1',
          'name' => 'American Apparel',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1101' => array(
          'tid' => '1101',
          'vid' => '1',
          'name' => 'astrid and miyu',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1104' => array(
          'tid' => '1104',
          'vid' => '1',
          'name' => 'nico dadonna',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1103' => array(
          'tid' => '1103',
          'vid' => '1',
          'name' => 'selfridges',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1105' => array(
          'tid' => '1105',
          'vid' => '1',
          'name' => 'suzie turner',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1102' => array(
          'tid' => '1102',
          'vid' => '1',
          'name' => 'terri leigh',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Alexander Beer',
        '1' => 'American Apparel, astrid and miyu, nico dadonna, selfridges, suzie turner, terri leigh',
        '4' => 'women',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
