array(
  array(
    'nid' => '4332',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1357702193',
    'changed' => '1403837916',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4332',
    'revision_uid' => '1',
    'title' => 'The Bloom Is On The Rose',
    'body' => '<p>
	Sparkling spring beauty from Paul &amp; Joe.<br />
	Exclusive photography by <a href="http://www.ariabramczyk.com/">Ari Abramczyk</a>.<br />
	Models - Nicole Linkletter at Nous, Jessica Cook &amp; Cailin Russo at No Ties.</p>
',
    'teaser' => '<p>
	Sparkling spring beauty from Paul &amp; Joe.<br />
	Exclusive photography by <a href="http://www.ariabramczyk.com/">Ari Abramczyk</a>.<br />
	Models - Nicole Linkletter at Nous, Jessica Cook &amp; Cailin Russo at No Ties.</p>
',
    'log' => '',
    'revision_timestamp' => '1403837916',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.ariabramczyk.com/">ARI ABRAMCZYK</a></p>
<p>
	EDITOR<br />
	DERRIC LOWE</p>
<p>
	MAKEUP<br />
	JOCELYN ZAYCO<br />
	VERONICA LANE</p>
<p>
	HAIR<br />
	CAROLINA YASUKAWA<br />
	&nbsp;</p>
<p>
	MODELS<br />
	NICOLE LINKLETTER<br />
	AT NOUS<br />
	JESSICA COOK<br />
	&amp; CAILIN RUSSO<br />
	AT NO TIES</p>
<p>
	&nbsp;</p>
<p>
	FASHION &amp; ACCESSORIES<br />
	FASHIONS BY ROBERT BLACK</p>
<p>
	&nbsp;</p>
<p>
	BEAUTY<br />
	<a href="http://www.paul-joe-beaute.com/en/index.html">PAUL &amp; JOE</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '23322',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_2.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136269',
        'status' => '1',
        'timestamp' => '1357732230',
        'origname' => 'TheBloomIsOnTheRose_2.jpg',
      ),
      '1' => array(
        'fid' => '23281',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_3.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68415',
        'status' => '1',
        'timestamp' => '1357701953',
        'origname' => 'TheBloomIsOnTheRose_3.jpg',
      ),
      '2' => array(
        'fid' => '23282',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_4.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '111776',
        'status' => '1',
        'timestamp' => '1357701962',
        'origname' => 'TheBloomIsOnTheRose_4.jpg',
      ),
      '3' => array(
        'fid' => '23284',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_5.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71647',
        'status' => '1',
        'timestamp' => '1357701976',
        'origname' => 'TheBloomIsOnTheRose_5.jpg',
      ),
      '4' => array(
        'fid' => '23323',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_6.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89712',
        'status' => '1',
        'timestamp' => '1357732262',
        'origname' => 'TheBloomIsOnTheRose_6.jpg',
      ),
      '5' => array(
        'fid' => '23288',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_7.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '144406',
        'status' => '1',
        'timestamp' => '1357701995',
        'origname' => 'TheBloomIsOnTheRose_7.jpg',
      ),
      '6' => array(
        'fid' => '23290',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_8.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98558',
        'status' => '1',
        'timestamp' => '1357702007',
        'origname' => 'TheBloomIsOnTheRose_8.jpg',
      ),
      '7' => array(
        'fid' => '23324',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_9.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116260',
        'status' => '1',
        'timestamp' => '1357732277',
        'origname' => 'TheBloomIsOnTheRose_9.jpg',
      ),
      '8' => array(
        'fid' => '23293',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_10.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90952',
        'status' => '1',
        'timestamp' => '1357702030',
        'origname' => 'TheBloomIsOnTheRose_10.jpg',
      ),
      '9' => array(
        'fid' => '23295',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_11.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74810',
        'status' => '1',
        'timestamp' => '1357702040',
        'origname' => 'TheBloomIsOnTheRose_11.jpg',
      ),
      '10' => array(
        'fid' => '23297',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_12.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112204',
        'status' => '1',
        'timestamp' => '1357702050',
        'origname' => 'TheBloomIsOnTheRose_12.jpg',
      ),
      '11' => array(
        'fid' => '23325',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_13.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66622',
        'status' => '1',
        'timestamp' => '1357732290',
        'origname' => 'TheBloomIsOnTheRose_13.jpg',
      ),
      '12' => array(
        'fid' => '23301',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_14.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131656',
        'status' => '1',
        'timestamp' => '1357702071',
        'origname' => 'TheBloomIsOnTheRose_14.jpg',
      ),
      '13' => array(
        'fid' => '23303',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_15.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161126',
        'status' => '1',
        'timestamp' => '1357702082',
        'origname' => 'TheBloomIsOnTheRose_15.jpg',
      ),
      '14' => array(
        'fid' => '23305',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_16.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '219915',
        'status' => '1',
        'timestamp' => '1357702094',
        'origname' => 'TheBloomIsOnTheRose_16.jpg',
      ),
      '15' => array(
        'fid' => '23306',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_17.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1357702105',
        'origname' => 'TheBloomIsOnTheRose_17.jpg',
      ),
      '16' => array(
        'fid' => '23308',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_18.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108212',
        'status' => '1',
        'timestamp' => '1357702116',
        'origname' => 'TheBloomIsOnTheRose_18.jpg',
      ),
      '17' => array(
        'fid' => '23326',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_19.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_19.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118597',
        'status' => '1',
        'timestamp' => '1357732309',
        'origname' => 'TheBloomIsOnTheRose_19.jpg',
      ),
      '18' => array(
        'fid' => '23327',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_20.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_20.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153151',
        'status' => '1',
        'timestamp' => '1357732320',
        'origname' => 'TheBloomIsOnTheRose_20.jpg',
      ),
      '19' => array(
        'fid' => '23313',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_21.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_21.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '111013',
        'status' => '1',
        'timestamp' => '1357702149',
        'origname' => 'TheBloomIsOnTheRose_21.jpg',
      ),
      '20' => array(
        'fid' => '23315',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_22.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_22.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15360',
        'status' => '1',
        'timestamp' => '1357702161',
        'origname' => 'TheBloomIsOnTheRose_22.jpg',
      ),
      '21' => array(
        'fid' => '23317',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_23.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_23.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '121338',
        'status' => '1',
        'timestamp' => '1357702169',
        'origname' => 'TheBloomIsOnTheRose_23.jpg',
      ),
      '22' => array(
        'fid' => '23319',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_24.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_24.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119717',
        'status' => '1',
        'timestamp' => '1357702178',
        'origname' => 'TheBloomIsOnTheRose_24.jpg',
      ),
      '23' => array(
        'fid' => '23328',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheBloomIsOnTheRose_25.jpg',
        'filepath' => 'files/fmag_story/2013/Jan/TheBloomIsOnTheRose_25.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78282',
        'status' => '1',
        'timestamp' => '1357732339',
        'origname' => 'TheBloomIsOnTheRose_25.jpg',
      ),
    ),
    'path' => 'stories/bloom-rose',
    'tags' => array(
      '5' => array(
        '2595' => array(
          'tid' => '2595',
          'vid' => '5',
          'name' => 'ARI ABRAMCZYK',
          'description' => 'http://www.ariabramczyk.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '1106' => array(
          'tid' => '1106',
          'vid' => '1',
          'name' => 'PAUL & JOE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ARI ABRAMCZYK',
        '1' => 'PAUL & JOE',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
