array(
  array(
    'nid' => '4360',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1359990173',
    'changed' => '1403837915',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4360',
    'revision_uid' => '1',
    'title' => 'Down Town Abbey',
    'body' => '<p>
	No uptown girl.<br />
	Exclusive photography by <a href="http://www.rikerbrothers.com/">The Riker Brothers</a>.<br />
	Model - Hanna Paat at LA Models.</p>
',
    'teaser' => '<p>
	No uptown girl.<br />
	Exclusive photography by <a href="http://www.rikerbrothers.com/">The Riker Brothers</a>.<br />
	Model - Hanna Paat at LA Models.</p>
',
    'log' => '',
    'revision_timestamp' => '1403837915',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.rikerbrothers.com/">THE RIKER BROTHERS</a></p>
<p>
	CONCEPT &amp; STYLING<br />
	MARCELLAS REYNOLDS<br />
	AT FORD ARTISTS</p>
<p>
	MAKEUP<br />
	SARAH USLAN<br />
	AT JED ROOT</p>
<p>
	HAIR<br />
	JEFFREY JAGGED</p>
<p>
	MODEL<br />
	HANNA PAAT<br />
	LA MODELS</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '23993',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DowntownAbbey_2 copy.jpg',
        'filepath' => 'files/fmag_story/2013/Feb/DowntownAbbey_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '165339',
        'status' => '1',
        'timestamp' => '1359989771',
        'origname' => 'DowntownAbbey_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '23995',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DowntownAbbey_3 copy.jpg',
        'filepath' => 'files/fmag_story/2013/Feb/DowntownAbbey_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '614008',
        'status' => '1',
        'timestamp' => '1359989783',
        'origname' => 'DowntownAbbey_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '23996',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DowntownAbbey_4 copy.jpg',
        'filepath' => 'files/fmag_story/2013/Feb/DowntownAbbey_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96513',
        'status' => '1',
        'timestamp' => '1359989790',
        'origname' => 'DowntownAbbey_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '23997',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DowntownAbbey_5 copy.jpg',
        'filepath' => 'files/fmag_story/2013/Feb/DowntownAbbey_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '592165',
        'status' => '1',
        'timestamp' => '1359989803',
        'origname' => 'DowntownAbbey_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '24008',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DowntownAbbey_6 copy.jpg',
        'filepath' => 'files/fmag_story/2013/Feb/DowntownAbbey_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '996064',
        'status' => '1',
        'timestamp' => '1359990496',
        'origname' => 'DowntownAbbey_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '24000',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DowntownAbbey_7 copy.jpg',
        'filepath' => 'files/fmag_story/2013/Feb/DowntownAbbey_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '849764',
        'status' => '1',
        'timestamp' => '1359989836',
        'origname' => 'DowntownAbbey_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '24002',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DowntownAbbey_8 copy.jpg',
        'filepath' => 'files/fmag_story/2013/Feb/DowntownAbbey_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '483011',
        'status' => '1',
        'timestamp' => '1359989851',
        'origname' => 'DowntownAbbey_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '24009',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DowntownAbbey_9 copy.jpg',
        'filepath' => 'files/fmag_story/2013/Feb/DowntownAbbey_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '501600',
        'status' => '1',
        'timestamp' => '1359990512',
        'origname' => 'DowntownAbbey_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '24004',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DowntownAbbey_10 copy.jpg',
        'filepath' => 'files/fmag_story/2013/Feb/DowntownAbbey_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '992193',
        'status' => '1',
        'timestamp' => '1359989896',
        'origname' => 'DowntownAbbey_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '24005',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DowntownAbbey_11 copy.jpg',
        'filepath' => 'files/fmag_story/2013/Feb/DowntownAbbey_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '768792',
        'status' => '1',
        'timestamp' => '1359990166',
        'origname' => 'DowntownAbbey_11 copy.jpg',
      ),
    ),
    'path' => 'stories/down-town-abbey',
    'tags' => array(
      '1' => array(
        '1150' => array(
          'tid' => '1150',
          'vid' => '1',
          'name' => 'BALMAIN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1152' => array(
          'tid' => '1152',
          'vid' => '1',
          'name' => 'CHARLES JOURDAN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1151' => array(
          'tid' => '1151',
          'vid' => '1',
          'name' => 'MEREDITH MARK',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '480' => array(
          'tid' => '480',
          'vid' => '1',
          'name' => 'RICK OWENS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1149' => array(
          'tid' => '1149',
          'vid' => '1',
          'name' => 'THOMAS WYLDE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2741' => array(
          'tid' => '2741',
          'vid' => '5',
          'name' => 'THE RIKER BROTHERS',
          'description' => 'http://www.rikerbrothers.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'BALMAIN, CHARLES JOURDAN, MEREDITH MARK, RICK OWENS, THOMAS WYLDE',
        '5' => 'THE RIKER BROTHERS',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
