array(
  array(
    'nid' => '4438',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1368807664',
    'changed' => '1403837911',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4438',
    'revision_uid' => '1',
    'title' => 'Elemental',
    'body' => '<p>
	Advanced and elementary.<br />
	Exclusive photography by <a href="http://www.freshew.com">Fredric Reshew</a>.<br />
	Model - Serena at Photogenics.</p>
',
    'teaser' => '<p>
	Advanced and elementary.<br />
	Exclusive photography by <a href="http://www.freshew.com">Fredric Reshew</a>.<br />
	Model - Serena at Photogenics.</p>
',
    'log' => '',
    'revision_timestamp' => '1403837911',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.freshew.com">FREDRIC RESHEW</a><br />
	&nbsp;</p>
<p>
	STYLIST<br />
	<a href="http://www.alejandrostyles.com/">ALEJANDRO PERAZA</a></p>
<p>
	MAKEUP<br />
	<a href="http://www.irismoreau.com">IRIS MOREAU</a></p>
<p>
	HAIR<br />
	LUCIE DOUGHTY</p>
<p>
	NAILS<br />
	STEPHANIE STONE</p>
<p>
	MODEL<br />
	SERENA<br />
	AT PHOTOGENICS</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '25424',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_2 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '714426',
        'status' => '1',
        'timestamp' => '1368807553',
        'origname' => 'Elemental_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '25426',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_3 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '169197',
        'status' => '1',
        'timestamp' => '1368807562',
        'origname' => 'Elemental_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '25428',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_4 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '859199',
        'status' => '1',
        'timestamp' => '1368807576',
        'origname' => 'Elemental_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '25430',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_5 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '135163',
        'status' => '1',
        'timestamp' => '1368807584',
        'origname' => 'Elemental_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '25447',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_6 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87925',
        'status' => '1',
        'timestamp' => '1368808936',
        'origname' => 'Elemental_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '25434',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_7 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '706831',
        'status' => '1',
        'timestamp' => '1368807603',
        'origname' => 'Elemental_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '25436',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_8 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90246',
        'status' => '1',
        'timestamp' => '1368807611',
        'origname' => 'Elemental_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '25438',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_9 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '833096',
        'status' => '1',
        'timestamp' => '1368807621',
        'origname' => 'Elemental_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '25440',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_10 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '620158',
        'status' => '1',
        'timestamp' => '1368807631',
        'origname' => 'Elemental_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '25442',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_11 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87863',
        'status' => '1',
        'timestamp' => '1368807639',
        'origname' => 'Elemental_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '25443',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_12 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78658',
        'status' => '1',
        'timestamp' => '1368807645',
        'origname' => 'Elemental_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '25444',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Elemental_13 copy.jpg',
        'filepath' => 'files/fmag_story/2013/May/Elemental_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '643693',
        'status' => '1',
        'timestamp' => '1368807655',
        'origname' => 'Elemental_13 copy.jpg',
      ),
    ),
    'path' => 'stories/elemental',
    'tags' => array(
      '1' => array(
        '1316' => array(
          'tid' => '1316',
          'vid' => '1',
          'name' => 'Aiko ITO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1310' => array(
          'tid' => '1310',
          'vid' => '1',
          'name' => 'alpana neeraj',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1315' => array(
          'tid' => '1315',
          'vid' => '1',
          'name' => 'falguni and shane Peacock',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1312' => array(
          'tid' => '1312',
          'vid' => '1',
          'name' => 'Fern One',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1317' => array(
          'tid' => '1317',
          'vid' => '1',
          'name' => 'Marianna Harutunian',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1313' => array(
          'tid' => '1313',
          'vid' => '1',
          'name' => 'Michael Cinco',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1318' => array(
          'tid' => '1318',
          'vid' => '1',
          'name' => 'Mishka Piaf',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2757' => array(
          'tid' => '2757',
          'vid' => '5',
          'name' => 'FREDRIC RESHEW',
          'description' => 'http://www.freshew.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Aiko ITO, alpana neeraj, falguni and shane Peacock, Fern One, Marianna Harutunian, Michael Cinco, Mishka Piaf',
        '5' => 'FREDRIC RESHEW',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
