array(
  array(
    'nid' => '4479',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1373065804',
    'changed' => '1403837910',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4479',
    'revision_uid' => '1',
    'title' => 'Butterfly In The Attic',
    'body' => '<p>
	Color &amp; print burst out.<br />
	Exclusive photography by <a href="http://jsetiawan.com/">Jason Setiawan</a>.<br />
	Model - Ugne at Muse.</p>
',
    'teaser' => '<p>
	Color &amp; print burst out.<br />
	Exclusive photography by <a href="http://jsetiawan.com/">Jason Setiawan</a>.<br />
	Model - Ugne at Muse.</p>
',
    'log' => '',
    'revision_timestamp' => '1403837910',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<a href="http://jsetiawan.com/"><br />
	JASON SETIAWAN<br />
	</a></p>
<p>
	STYLIST<br />
	FABIOLA LEDESMA</p>
<p>
	MAKEUP<br />
	BANK NATDANAI</p>
<p>
	HAIR<br />
	<a href="http://www.seldacortes.com/"> SELDA CORTES</a></p>
<p>
	MODEL<br />
	UGNE<br />
	AT MUSE</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '26103',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'setiawan_2.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/setiawan_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '197522',
        'status' => '1',
        'timestamp' => '1372892878',
        'origname' => 'setiawan_2.jpg',
      ),
      '1' => array(
        'fid' => '26104',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'setiawan_3.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/setiawan_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66219',
        'status' => '1',
        'timestamp' => '1372892888',
        'origname' => 'setiawan_3.jpg',
      ),
      '2' => array(
        'fid' => '26105',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'setiawan_4.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/setiawan_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '252140',
        'status' => '1',
        'timestamp' => '1372892902',
        'origname' => 'setiawan_4.jpg',
      ),
      '3' => array(
        'fid' => '26106',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'setiawan_5.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/setiawan_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '238991',
        'status' => '1',
        'timestamp' => '1372892915',
        'origname' => 'setiawan_5.jpg',
      ),
      '4' => array(
        'fid' => '26107',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'setiawan_6.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/setiawan_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '16255',
        'status' => '1',
        'timestamp' => '1372892925',
        'origname' => 'setiawan_6.jpg',
      ),
      '5' => array(
        'fid' => '26108',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'setiawan_7.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/setiawan_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '307930',
        'status' => '1',
        'timestamp' => '1372892939',
        'origname' => 'setiawan_7.jpg',
      ),
      '6' => array(
        'fid' => '26109',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'setiawan_8.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/setiawan_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15881',
        'status' => '1',
        'timestamp' => '1372892949',
        'origname' => 'setiawan_8.jpg',
      ),
      '7' => array(
        'fid' => '26110',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'setiawan_9.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/setiawan_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '248801',
        'status' => '1',
        'timestamp' => '1372892961',
        'origname' => 'setiawan_9.jpg',
      ),
      '8' => array(
        'fid' => '26111',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'setiawan_10.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/setiawan_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15030',
        'status' => '1',
        'timestamp' => '1372892975',
        'origname' => 'setiawan_10.jpg',
      ),
      '9' => array(
        'fid' => '26112',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'setiawan_11.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/setiawan_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '204134',
        'status' => '1',
        'timestamp' => '1372892992',
        'origname' => 'setiawan_11.jpg',
      ),
    ),
    'path' => 'stories/butterfly-attic',
    'tags' => array(
      '1' => array(
        '1393' => array(
          'tid' => '1393',
          'vid' => '1',
          'name' => 'alice & Olivia',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1389' => array(
          'tid' => '1389',
          'vid' => '1',
          'name' => 'althea harper',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1388' => array(
          'tid' => '1388',
          'vid' => '1',
          'name' => 'bcbgeneration',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1392' => array(
          'tid' => '1392',
          'vid' => '1',
          'name' => 'duro Olowu',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1387' => array(
          'tid' => '1387',
          'vid' => '1',
          'name' => 'Michale kors',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1391' => array(
          'tid' => '1391',
          'vid' => '1',
          'name' => 'rachel roy',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '189' => array(
          'tid' => '189',
          'vid' => '1',
          'name' => 'RALPH LAUREN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1390' => array(
          'tid' => '1390',
          'vid' => '1',
          'name' => 'xscape',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2676' => array(
          'tid' => '2676',
          'vid' => '5',
          'name' => 'JASON SETIAWAN',
          'description' => 'http://jsetiawan.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'alice & Olivia, althea harper, bcbgeneration, duro Olowu, Michale kors, rachel roy, RALPH LAUREN, xscape',
        '5' => 'JASON SETIAWAN',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
