array(
  array(
    'nid' => '4513',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1375144914',
    'changed' => '1403837909',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4513',
    'revision_uid' => '1',
    'title' => 'Tom Boy',
    'body' => '<p>
	Boy it up Girl.<br />
	Exclusive photography by <a href="http://brettadavis.com/"><span>Brett Davis</span></a>.<br />
	Models - Alena Chetoka &amp; Kristi Welch at Re:Quest, Mika Furuya at Agency.</p>
',
    'teaser' => '<p>
	Boy it up Girl.<br />
	Exclusive photography by <a href="http://brettadavis.com/"><span>Brett Davis</span></a>.<br />
	Models - Alena Chetoka &amp; Kristi Welch at Re:Quest, Mika Furuya at Agency.</p>
',
    'log' => '',
    'revision_timestamp' => '1403837909',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://brettadavis.com/">BRETT DAVIS</a></p>
<p>
	STYLING<br />
	SHERAH JONES</p>
<p>
	MODELS<br />
	ALENA CHETOKA&nbsp;<br />
	&amp; KRISTI WELCH<br />
	AT RE:QUEST<br />
	MIKA FURUYA<br />
	AT AGENCY</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '26615',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TomBoy_2.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/TomBoy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '22883',
        'status' => '1',
        'timestamp' => '1375144876',
        'origname' => 'TomBoy_2.jpg',
      ),
      '1' => array(
        'fid' => '26617',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TomBoy_3.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/TomBoy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '191263',
        'status' => '1',
        'timestamp' => '1375144882',
        'origname' => 'TomBoy_3.jpg',
      ),
      '2' => array(
        'fid' => '26619',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TomBoy_4.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/TomBoy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '59331',
        'status' => '1',
        'timestamp' => '1375144888',
        'origname' => 'TomBoy_4.jpg',
      ),
      '3' => array(
        'fid' => '26621',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TomBoy_5.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/TomBoy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134356',
        'status' => '1',
        'timestamp' => '1375144894',
        'origname' => 'TomBoy_5.jpg',
      ),
      '4' => array(
        'fid' => '26623',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TomBoy_6.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/TomBoy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73538',
        'status' => '1',
        'timestamp' => '1375144899',
        'origname' => 'TomBoy_6.jpg',
      ),
      '5' => array(
        'fid' => '26624',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TomBoy_7.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/TomBoy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116435',
        'status' => '1',
        'timestamp' => '1375144905',
        'origname' => 'TomBoy_7.jpg',
      ),
    ),
    'path' => 'stories/tom-boy',
    'tags' => array(
      '5' => array(
        '2767' => array(
          'tid' => '2767',
          'vid' => '5',
          'name' => 'BRETT DAVIS',
          'description' => 'http://brettadavis.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '1489' => array(
          'tid' => '1489',
          'vid' => '1',
          'name' => 'element x jac vanek',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1486' => array(
          'tid' => '1486',
          'vid' => '1',
          'name' => 'hot topic',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1210' => array(
          'tid' => '1210',
          'vid' => '1',
          'name' => 'Lee',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '156' => array(
          'tid' => '156',
          'vid' => '1',
          'name' => 'UNIQLO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1487' => array(
          'tid' => '1487',
          'vid' => '1',
          'name' => 'verameat',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1488' => array(
          'tid' => '1488',
          'vid' => '1',
          'name' => 'volcom',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1485' => array(
          'tid' => '1485',
          'vid' => '1',
          'name' => 'worth & worth',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'BRETT DAVIS',
        '1' => 'element x jac vanek, hot topic, Lee, UNIQLO, verameat, volcom, worth & worth',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
