array(
  array(
    'nid' => '4518',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1375309784',
    'changed' => '1403837620',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4518',
    'revision_uid' => '1',
    'title' => 'Boho Mod',
    'body' => '<p>
	Surfing Bohemia.<br />
	Exclusive photography by <a href="http://www.naotografie.com"><span>Naoto Hayasaka</span></a>.<br />
	Model - Paul Maitland Day.</p>
',
    'teaser' => '<p>
	Surfing Bohemia.<br />
	Exclusive photography by <a href="http://www.naotografie.com"><span>Naoto Hayasaka</span></a>.<br />
	Model - Paul Maitland Day.</p>
',
    'log' => '',
    'revision_timestamp' => '1403837620',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.naotografie.com">NAOTO HAYASAKA</a></p>
<p>
	STYLING<br />
	PAUL MAITLAND DAY</p>
<p>
	PRODUCTION<br />
	ICTD INC</p>
<p>
	MODEL<br />
	PAUL MAITLAND DAY</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '26721',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_2.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132962',
        'status' => '1',
        'timestamp' => '1375309681',
        'origname' => 'bohemian-mod_2.jpg',
      ),
      '1' => array(
        'fid' => '26723',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_3.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '36548',
        'status' => '1',
        'timestamp' => '1375309687',
        'origname' => 'bohemian-mod_3.jpg',
      ),
      '2' => array(
        'fid' => '26725',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_4.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '209804',
        'status' => '1',
        'timestamp' => '1375309694',
        'origname' => 'bohemian-mod_4.jpg',
      ),
      '3' => array(
        'fid' => '26727',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_5.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '214095',
        'status' => '1',
        'timestamp' => '1375309700',
        'origname' => 'bohemian-mod_5.jpg',
      ),
      '4' => array(
        'fid' => '26729',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_6.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '403260',
        'status' => '1',
        'timestamp' => '1375309708',
        'origname' => 'bohemian-mod_6.jpg',
      ),
      '5' => array(
        'fid' => '26731',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_7.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '239654',
        'status' => '1',
        'timestamp' => '1375309714',
        'origname' => 'bohemian-mod_7.jpg',
      ),
      '6' => array(
        'fid' => '26733',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_8.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '149989',
        'status' => '1',
        'timestamp' => '1375309721',
        'origname' => 'bohemian-mod_8.jpg',
      ),
      '7' => array(
        'fid' => '26735',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_9.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139910',
        'status' => '1',
        'timestamp' => '1375309728',
        'origname' => 'bohemian-mod_9.jpg',
      ),
      '8' => array(
        'fid' => '26740',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_10.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131824',
        'status' => '1',
        'timestamp' => '1375309757',
        'origname' => 'bohemian-mod_10.jpg',
      ),
      '9' => array(
        'fid' => '26737',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_11.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126997',
        'status' => '1',
        'timestamp' => '1375309735',
        'origname' => 'bohemian-mod_11.jpg',
      ),
      '10' => array(
        'fid' => '26741',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_12.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173046',
        'status' => '1',
        'timestamp' => '1375309766',
        'origname' => 'bohemian-mod_12.jpg',
      ),
      '11' => array(
        'fid' => '26742',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'bohemian-mod_13.jpg',
        'filepath' => 'files/fmag_story/2013/Jul/bohemian-mod_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '143218',
        'status' => '1',
        'timestamp' => '1375309777',
        'origname' => 'bohemian-mod_13.jpg',
      ),
    ),
    'path' => 'stories/boho-mod',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2770' => array(
          'tid' => '2770',
          'vid' => '5',
          'name' => 'NAOTO HAYASAKA',
          'description' => 'http://www.naotografie.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '951' => array(
          'tid' => '951',
          'vid' => '1',
          'name' => 'thom browne',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'men',
        '5' => 'NAOTO HAYASAKA',
        '1' => 'thom browne',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
