array(
  array(
    'nid' => '4549',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1379895306',
    'changed' => '1379895881',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4549',
    'revision_uid' => '1',
    'title' => 'Living Color',
    'body' => '<p>
	Color up.<br />
	Exclusive photography by <a href="http://www.omitanaka.com/">Omi Tanaka</a>.<br />
	Model - L&#39;Wren Hodgins at Major.</p>
',
    'teaser' => '<p>
	Color up.<br />
	Exclusive photography by <a href="http://www.omitanaka.com/">Omi Tanaka</a>.<br />
	Model - L&#39;Wren Hodgins at Major.</p>
',
    'log' => '',
    'revision_timestamp' => '1379895881',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.omitanaka.com/">OMI TANAKA</a></p>
<p>
	STYLIST<br />
	<a href="http://www.raymondgee.com/">RAYMOND GEE</a></p>
<p>
	MAKEUP<br />
	<a href="http://www.grisellemua.com/">GRISELLE ROSARIO</a></p>
<p>
	HAIR<br />
	<a href="http://www.takayoshitsukisawa.com/">TAKAYOSHI TSUKISAWA</a></p>
<p>
	MODEL<br />
	L&#39;WREN HODGINS<br />
	AT MAJOR</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '27277',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LivingColor_2.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/LivingColor_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '52223',
        'status' => '1',
        'timestamp' => '1379895225',
        'origname' => 'LivingColor_2.jpg',
      ),
      '1' => array(
        'fid' => '27279',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LivingColor_3.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/LivingColor_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '188189',
        'status' => '1',
        'timestamp' => '1379895233',
        'origname' => 'LivingColor_3.jpg',
      ),
      '2' => array(
        'fid' => '27281',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LivingColor_4.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/LivingColor_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15432',
        'status' => '1',
        'timestamp' => '1379895240',
        'origname' => 'LivingColor_4.jpg',
      ),
      '3' => array(
        'fid' => '27283',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LivingColor_5.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/LivingColor_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '365425',
        'status' => '1',
        'timestamp' => '1379895250',
        'origname' => 'LivingColor_5.jpg',
      ),
      '4' => array(
        'fid' => '27285',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LivingColor_6.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/LivingColor_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13855',
        'status' => '1',
        'timestamp' => '1379895259',
        'origname' => 'LivingColor_6.jpg',
      ),
      '5' => array(
        'fid' => '27287',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LivingColor_7.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/LivingColor_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '133479',
        'status' => '1',
        'timestamp' => '1379895266',
        'origname' => 'LivingColor_7.jpg',
      ),
      '6' => array(
        'fid' => '27289',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LivingColor_8.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/LivingColor_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13922',
        'status' => '1',
        'timestamp' => '1379895274',
        'origname' => 'LivingColor_8.jpg',
      ),
      '7' => array(
        'fid' => '27291',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LivingColor_9.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/LivingColor_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '180882',
        'status' => '1',
        'timestamp' => '1379895282',
        'origname' => 'LivingColor_9.jpg',
      ),
      '8' => array(
        'fid' => '27293',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LivingColor_10.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/LivingColor_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1379895290',
        'origname' => 'LivingColor_10.jpg',
      ),
      '9' => array(
        'fid' => '27294',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LivingColor_11.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/LivingColor_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '223907',
        'status' => '1',
        'timestamp' => '1379895297',
        'origname' => 'LivingColor_11.jpg',
      ),
    ),
    'path' => 'stories/living-color-0',
    'tags' => array(
      '1' => array(
        '1565' => array(
          'tid' => '1565',
          'vid' => '1',
          'name' => 'Cynthia Rowley',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '249' => array(
          'tid' => '249',
          'vid' => '1',
          'name' => 'ETRO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1566' => array(
          'tid' => '1566',
          'vid' => '1',
          'name' => 'Katia Leonovich',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '79' => array(
          'tid' => '79',
          'vid' => '1',
          'name' => 'Lie Sang Bong',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1564' => array(
          'tid' => '1564',
          'vid' => '1',
          'name' => 'Noon by Noor',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2777' => array(
          'tid' => '2777',
          'vid' => '5',
          'name' => 'OMI TANAKA',
          'description' => 'http://www.omitanaka.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Cynthia Rowley, ETRO, Katia Leonovich, Lie Sang Bong, Noon by Noor',
        '5' => 'OMI TANAKA',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
