array(
  array(
    'nid' => '4554',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1379725845',
    'changed' => '1403388316',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4554',
    'revision_uid' => '1',
    'title' => 'Noted - Bruce Weber In Vogue',
    'body' => '<p>
	Bruce Weber Vogues it up.</p>
',
    'teaser' => '<p>
	Bruce Weber Vogues it up.</p>
',
    'log' => '',
    'revision_timestamp' => '1403388316',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.vogue.com/‎">VOGUE</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '27329',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED_BruceWeber_2.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/NOTED_BruceWeber_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '310835',
        'status' => '1',
        'timestamp' => '1380071404',
        'origname' => 'NOTED_BruceWeber_2.jpg',
      ),
      '1' => array(
        'fid' => '27330',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED_BruceWeber_3.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/NOTED_BruceWeber_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '247244',
        'status' => '1',
        'timestamp' => '1380071415',
        'origname' => 'NOTED_BruceWeber_3.jpg',
      ),
      '2' => array(
        'fid' => '27332',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED_BruceWeber_4.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/NOTED_BruceWeber_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '220328',
        'status' => '1',
        'timestamp' => '1380071429',
        'origname' => 'NOTED_BruceWeber_4.jpg',
      ),
      '3' => array(
        'fid' => '27334',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED_BruceWeber_5.jpg',
        'filepath' => 'files/fmag_story/2013/Sep/NOTED_BruceWeber_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '181975',
        'status' => '1',
        'timestamp' => '1380071949',
        'origname' => 'NOTED_BruceWeber_5.jpg',
      ),
    ),
    'path' => 'stories/noted-bruce-weber-vogue',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2778' => array(
          'tid' => '2778',
          'vid' => '5',
          'name' => 'ROBERT ASCROFT',
          'description' => 'http://robertascroft.com/?',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'men',
        '5' => 'ROBERT ASCROFT',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
