array(
  array(
    'nid' => '4568',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1382058563',
    'changed' => '1403388315',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4568',
    'revision_uid' => '1',
    'title' => 'SNAP',
    'body' => '<p>
	Snap it up this fall.<br />
	Exclusive photography by <a href="http://www.mckenziejames.com">Mckenzie James</a>.<br />
	Model - Andrew Basso at Plutino.</p>
',
    'teaser' => '<p>
	Snap it up this fall.<br />
	Exclusive photography by <a href="http://www.mckenziejames.com">Mckenzie James</a>.<br />
	Model - Andrew Basso at Plutino.</p>
',
    'log' => '',
    'revision_timestamp' => '1403388315',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.mckenziejames.com">MCKENZIE JAMES</a></p>
<p>
	FASHION EDITOR<br />
	JAMES NIXON<br />
	&nbsp;</p>
<p>
	MODEL<br />
	ANDREW BASSO<br />
	AT PLUTINO</p>
<p>
	<a href="http://www.fredperry.com/shopfinder/shops/view/shop/toronto/">FED PERRY<br />
	TORONTO<br />
	964 QUEEN WEST<br />
	416 538 3733</a></p>
<p>
	<a href="http://oliverspencer.co.uk/‎">OLIVER SPENCER </a><br />
	TORONTO<br />
	962 QUEEN WEST<br />
	647 348 7673</p>

',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '27563',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_2.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '121413',
        'status' => '1',
        'timestamp' => '1382058732',
        'origname' => 'SNAP_2.jpg',
      ),
      '1' => array(
        'fid' => '27545',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_3.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '28649',
        'status' => '1',
        'timestamp' => '1382058388',
        'origname' => 'SNAP_3.jpg',
      ),
      '2' => array(
        'fid' => '27547',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_4.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18059',
        'status' => '1',
        'timestamp' => '1382058398',
        'origname' => 'SNAP_4.jpg',
      ),
      '3' => array(
        'fid' => '27548',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_5.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '162910',
        'status' => '1',
        'timestamp' => '1382058405',
        'origname' => 'SNAP_5.jpg',
      ),
      '4' => array(
        'fid' => '27550',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_6.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '120144',
        'status' => '1',
        'timestamp' => '1382058415',
        'origname' => 'SNAP_6.jpg',
      ),
      '5' => array(
        'fid' => '27552',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_7.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103342',
        'status' => '1',
        'timestamp' => '1382058423',
        'origname' => 'SNAP_7.jpg',
      ),
      '6' => array(
        'fid' => '27554',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_8.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1382058432',
        'origname' => 'SNAP_8.jpg',
      ),
      '7' => array(
        'fid' => '27556',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_9.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107679',
        'status' => '1',
        'timestamp' => '1382058440',
        'origname' => 'SNAP_9.jpg',
      ),
      '8' => array(
        'fid' => '27558',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_10.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '219580',
        'status' => '1',
        'timestamp' => '1382058450',
        'origname' => 'SNAP_10.jpg',
      ),
      '9' => array(
        'fid' => '27560',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_11.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77376',
        'status' => '1',
        'timestamp' => '1382058457',
        'origname' => 'SNAP_11.jpg',
      ),
      '10' => array(
        'fid' => '27561',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_12.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14089',
        'status' => '1',
        'timestamp' => '1382058464',
        'origname' => 'SNAP_12.jpg',
      ),
      '11' => array(
        'fid' => '27562',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'SNAP_13.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/SNAP_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173281',
        'status' => '1',
        'timestamp' => '1382058472',
        'origname' => 'SNAP_13.jpg',
      ),
    ),
    'path' => 'stories/snap-0',
    'tags' => array(
      '1' => array(
        '1606' => array(
          'tid' => '1606',
          'vid' => '1',
          'name' => 'AIGLE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1079' => array(
          'tid' => '1079',
          'vid' => '1',
          'name' => 'Fred Perry',
          'description' => 'www.fredperry.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1605' => array(
          'tid' => '1605',
          'vid' => '1',
          'name' => 'MADS NORGAARD',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '831' => array(
          'tid' => '831',
          'vid' => '1',
          'name' => 'Oliver Spencer',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2415' => array(
          'tid' => '2415',
          'vid' => '5',
          'name' => 'McKenzie James',
          'description' => 'http://www.modelmayhem.com/29023',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'AIGLE, Fred Perry, MADS NORGAARD, Oliver Spencer',
        '5' => 'McKenzie James',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
