array(
  array(
    'nid' => '4576',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1382966992',
    'changed' => '1403388315',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4576',
    'revision_uid' => '1',
    'title' => '12 Years A Slave',
    'body' => '<p>
	Actor Jay Huguley on 12 Years A Slave.</p>
',
    'teaser' => '<p>
	Actor Jay Huguley on 12 Years A Slave.</p>
',
    'log' => '',
    'revision_timestamp' => '1403388315',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	12 YEARS A SLAVE</p>
<p>
	JAY HUGULEY PHOTOGRAPHY<br />
	BY <a href="http://www.kristineambrose.com">KRISTINE AMBROSE</a></p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '27656',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'jay-huguley-12-years-a-slave_2.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/jay-huguley-12-years-a-slave_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '117894',
        'status' => '1',
        'timestamp' => '1382966963',
        'origname' => 'jay-huguley-12-years-a-slave_2.jpg',
      ),
      '1' => array(
        'fid' => '27658',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'jay-huguley-12-years-a-slave_3.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/jay-huguley-12-years-a-slave_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167819',
        'status' => '1',
        'timestamp' => '1382966970',
        'origname' => 'jay-huguley-12-years-a-slave_3.jpg',
      ),
      '2' => array(
        'fid' => '27660',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'jay-huguley-12-years-a-slave_4.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/jay-huguley-12-years-a-slave_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78517',
        'status' => '1',
        'timestamp' => '1382966978',
        'origname' => 'jay-huguley-12-years-a-slave_4.jpg',
      ),
      '3' => array(
        'fid' => '27661',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'jay-huguley-12-years-a-slave_5.jpg',
        'filepath' => 'files/fmag_story/2013/Oct/jay-huguley-12-years-a-slave_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '214391',
        'status' => '1',
        'timestamp' => '1382966986',
        'origname' => 'jay-huguley-12-years-a-slave_5.jpg',
      ),
    ),
    'path' => 'stories/12-years-slave',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2771' => array(
          'tid' => '2771',
          'vid' => '5',
          'name' => 'SOFIE KIRK',
          'description' => 'http://www.sofiekirk.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'men',
        '5' => 'SOFIE KIRK',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(
      '27662' => array(
        'fid' => '27662',
        'uid' => '1',
        'filename' => 'TwelveYears.pdf',
        'filepath' => 'files/TwelveYears.pdf',
        'filemime' => 'application/pdf',
        'filesize' => '854940',
        'status' => '1',
        'timestamp' => '1382967197',
        'origname' => '',
        'vid' => '4576',
        'description' => 'TwelveYears.pdf',
        'list' => '1',
        'nid' => '4576',
        'weight' => '0',
        '#_export_node_encode_object' => '1',
      ),
    ),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
