array(
  array(
    'nid' => '5387',
    'type' => 'fmag_video',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1455194836',
    'changed' => 1457636469,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5387',
    'revision_uid' => '1',
    'title' => 'Video Video - Jacob Jonas The Company',
    'body' => '<p>VIDEO VIDEO - Jacob Jonas The Company<br />
	Directed by Jacob Jonas.</p>
',
    'teaser' => '<p>VIDEO VIDEO - Jacob Jonas The Company<br />
	Directed by Jacob Jonas.</p>
',
    'revision_timestamp' => '1455201277',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	DIRECTOR<br />
	JACOB JONAS</p>
<p>
	CHOREOGRAPHER<br />
	JACOB JONAS</p>
<p>
	PERFORMERS<br />
	BROOKLIN REEVES &amp; JILL WILSON</p>
',
      ),
    ),
    'field_videoembed' => array(
      '0' => array(
        'value' => '<!-- here is the documentation you will need for adding videos --><!--first, you have the embed tag: -->
<p>
	<iframe allowfullscreen="" frameborder="0&amp;" height=" 550" src="http://www.youtube.com/embed/uHi_XyquXFs?&amp;autoplay=1&amp;amp;rel=0&amp;showinfo=0&amp;modestbranding=1&amp;hd=1&amp;autohide=1&amp;color=white&amp;vq=hd720" width="1000"></iframe><!-- 

--></p>
',
      ),
    ),
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'path' => 'videos/video-video-jacob-jonas-company',
    'tags' => array(
      '5' => array(
        '3415' => array(
          'tid' => '3415',
          'vid' => '5',
          'name' => 'Jacob Jonas',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Jacob Jonas',
      ),
    ),
    'files' => array(
      '41860' => array(
        'fid' => '41860',
        'uid' => '1',
        'filename' => 'Jacob-Jonas-The-Company.jpg',
        'filepath' => 'files/Jacob-Jonas-The-Company_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141785',
        'status' => '1',
        'timestamp' => '1455130291',
        'origname' => '',
        'vid' => '5387',
        'description' => 'Jacob-Jonas-The-Company.jpg',
        'list' => '1',
        'nid' => '5387',
        'weight' => '0',
      ),
    ),
    'page_title' => '',
    'uuid' => '735c1762-e6f2-11e5-b369-cf2e79d5c249',
    'is_new' => FALSE,
    'timestamp' => 1457636469,
    'xmlsitemap' => array(
      'id' => '5387',
      'type' => 'node',
      'subtype' => 'fmag_video',
      'loc' => 'node/5387',
      'language' => '',
      'access' => TRUE,
      'status' => '0',
      'status_override' => '0',
      'lastmod' => '1457636469',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '0',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5387',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
