array(
  array(
    'nid' => '5392',
    'type' => 'fmag_video',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1456164485',
    'changed' => 1457636478,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5392',
    'revision_uid' => '1',
    'title' => 'Video Video - Nowhere To Run',
    'body' => '<p>
	VIDEO VIDEO - Nowhere To Run<br />
	Directed by Ryan Cooper.</p>
',
    'teaser' => '<p>
	VIDEO VIDEO - Nowhere To Run<br />
	Directed by Ryan Cooper.</p>
',
    'revision_timestamp' => '1456249580',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	DIRECTOR<br />
	RYAN COOPER</p>
<p>
	CREATIVE DIRECTOR<br />
	PAUL LAMB</p>
<p>
	PHOTOGRAPHER<br />
	FABRICE TROMBERT</p>
<p>
	TALENT<br />
	CLARA SETJE AT TRUMP</p>
<p>
	<a href="http://www.kateryaninc.com/styling/basia-zamorska">FASHION EDITING<br />
	Basia Zomorska<br />
	at Kate Ryan</a></p>
<p>
	MAKEUP<br />
	STEPHANIE PETERSON AT ART DEPARTMENT</p>
<p>
	HAIR<br />
	DAMIAN MONZILLO AT ARTMIX</p>
<p>
	LIGHTING ASSISTANT<br />
	ZACH RAMEY</p>
<p>
	MUSIC<br />
	THE MIDNIGHT HOLLOW - HER MORNING GLOW</p>
',
      ),
    ),
    'field_videoembed' => array(
      '0' => array(
        'value' => '<!-- here is the documentation you will need for adding videos --><!--first, you have the embed tag: -->
<p>
	<iframe allowfullscreen="" frameborder="0&amp;" height=" 550" src="http://www.youtube.com/embed/WWF1l5aG1LQ?&amp;autoplay=1&amp;amp;rel=0&amp;showinfo=0&amp;modestbranding=1&amp;hd=1&amp;autohide=1&amp;color=white&amp;vq=hd720" width="1000"></iframe><!-- 

--></p>
',
      ),
    ),
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'path' => 'videos/video-video-nowhere-run',
    'tags' => NULL,
    'taxonomy' => array(),
    'files' => array(
      '41918' => array(
        'fid' => '41918',
        'uid' => '1',
        'filename' => 'NowhereToRun.jpg',
        'filepath' => 'files/NowhereToRun.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '110579',
        'status' => '1',
        'timestamp' => '1455214420',
        'origname' => '',
        'vid' => '5392',
        'description' => 'NowhereToRun.jpg',
        'list' => '1',
        'nid' => '5392',
        'weight' => '0',
      ),
    ),
    'page_title' => '',
    'uuid' => '78932e82-e6f2-11e5-b369-cf2e79d5c249',
    'is_new' => FALSE,
    'timestamp' => 1457636478,
    'xmlsitemap' => array(
      'id' => '5392',
      'type' => 'node',
      'subtype' => 'fmag_video',
      'loc' => 'node/5392',
      'language' => '',
      'access' => TRUE,
      'status' => '0',
      'status_override' => '0',
      'lastmod' => '1457636478',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '0',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5392',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
