array(
  array(
    'nid' => '4628',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1388968697',
    'changed' => '1403388312',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4628',
    'revision_uid' => '1',
    'title' => 'Captures - Kenny Sale',
    'body' => '<p>
	Captured on set - Kenny Sale<br />
	Exclusive photography by David Apeji.<br />
	Model - Kenny Sale NTA, No Ties &amp; Joy.</p>
',
    'teaser' => '<p>
	Captured on set - Kenny Sale<br />
	Exclusive photography by David Apeji.<br />
	Model - Kenny Sale NTA, No Ties &amp; Joy.</p>
',
    'log' => '',
    'revision_timestamp' => '1403388312',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	DAVID APEJI</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	GROOMING<br />
	DERRIC LOWE</p>
<p>
	MODEL<br />
	KENNY SALE<br />
	AT NTA, NO TIES<br />
	&amp; JOY MILAN</p>
<p>
	PIXYST PHOTO STUDIOS</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '28481',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_2.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '166317',
        'status' => '1',
        'timestamp' => '1388969087',
        'origname' => 'Kenny_2.jpg',
      ),
      '1' => array(
        'fid' => '28483',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_3.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '163604',
        'status' => '1',
        'timestamp' => '1388969094',
        'origname' => 'Kenny_3.jpg',
      ),
      '2' => array(
        'fid' => '28484',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_4.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93589',
        'status' => '1',
        'timestamp' => '1388969099',
        'origname' => 'Kenny_4.jpg',
      ),
      '3' => array(
        'fid' => '28485',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_5.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112540',
        'status' => '1',
        'timestamp' => '1388969107',
        'origname' => 'Kenny_5.jpg',
      ),
      '4' => array(
        'fid' => '28487',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_6.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1388969116',
        'origname' => 'Kenny_6.jpg',
      ),
      '5' => array(
        'fid' => '28489',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_7.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107256',
        'status' => '1',
        'timestamp' => '1388969124',
        'origname' => 'Kenny_7.jpg',
      ),
      '6' => array(
        'fid' => '28491',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_8.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1388969130',
        'origname' => 'Kenny_8.jpg',
      ),
      '7' => array(
        'fid' => '28493',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_9.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76324',
        'status' => '1',
        'timestamp' => '1388969137',
        'origname' => 'Kenny_9.jpg',
      ),
      '8' => array(
        'fid' => '28495',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_10.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1388969143',
        'origname' => 'Kenny_10.jpg',
      ),
      '9' => array(
        'fid' => '28497',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_11.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82202',
        'status' => '1',
        'timestamp' => '1388969148',
        'origname' => 'Kenny_11.jpg',
      ),
      '10' => array(
        'fid' => '28499',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_12.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1388969153',
        'origname' => 'Kenny_12.jpg',
      ),
      '11' => array(
        'fid' => '28500',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kenny_13.jpg',
        'filepath' => 'files/fmag_story/2014/Jan/Kenny_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '99474',
        'status' => '1',
        'timestamp' => '1388969158',
        'origname' => 'Kenny_13.jpg',
      ),
    ),
    'path' => 'stories/captures-kenny-sale',
    'tags' => array(
      '1' => array(
        '1717' => array(
          'tid' => '1717',
          'vid' => '1',
          'name' => 'ARMY SURPLUS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1714' => array(
          'tid' => '1714',
          'vid' => '1',
          'name' => 'BLEULAB',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1716' => array(
          'tid' => '1716',
          'vid' => '1',
          'name' => 'MERRELL BOOTS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '111' => array(
          'tid' => '111',
          'vid' => '1',
          'name' => 'MICHAEL KORS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1715' => array(
          'tid' => '1715',
          'vid' => '1',
          'name' => 'PENDELTON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1718' => array(
          'tid' => '1718',
          'vid' => '1',
          'name' => 'PROGRESSIVE FLOW',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1713' => array(
          'tid' => '1713',
          'vid' => '1',
          'name' => 'SAFETY CLOTHING CO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2776' => array(
          'tid' => '2776',
          'vid' => '5',
          'name' => 'DAVID APEJI',
          'description' => 'http://www.pixyst.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'ARMY SURPLUS, BLEULAB, MERRELL BOOTS, MICHAEL KORS, PENDELTON, PROGRESSIVE FLOW, SAFETY CLOTHING CO',
        '5' => 'DAVID APEJI',
        '4' => 'men',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
