array(
  array(
    'nid' => '4667',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1393295997',
    'changed' => '1393338400',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4667',
    'revision_uid' => '1',
    'title' => 'Brothers, Sisters, Sons & Daughters',
    'body' => '<p>
	Barneys New York &amp; Bruce Weber celebrate Brothers, Sisters, Sons &amp; Daughters.<br />
	Photography by Bruce Weber.<br />
	&nbsp;</p>
',
    'teaser' => '<p>
	Barneys New York &amp; Bruce Weber celebrate Brothers, Sisters, Sons &amp; Daughters.<br />
	Photography by Bruce Weber.<br />
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1393338400',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://thewindow.barneys.com/brothers-sisters-sons-daughters-the-film/">BROTHERS, SISTERS, SONS &amp; DAUGHTERS</a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://thewindow.barneys.com/">THE WINDOW</a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://www.barneys.com/on/demandware.store/Sites-BNY-Site/default/Home-Show">BARNEYS NEW YORK</a></p>
<p>
	<a href="http://transequality.org/">NATIONAL CENTER<br />
	FOR TRANSGENDER EQUALITY</a></p>
<p>
	<a href="http://www.gaycenter.org">LGBT COMMUNITY CENTER NYC</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '29091',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED_BarneysNY_BruceWeber_2.jpg',
        'filepath' => 'files/fmag_story/2014/Feb/NOTED_BarneysNY_BruceWeber_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84532',
        'status' => '1',
        'timestamp' => '1393296786',
        'origname' => 'NOTED_BarneysNY_BruceWeber_2.jpg',
      ),
      '1' => array(
        'fid' => '29092',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED_BarneysNY_BruceWeber_3.jpg',
        'filepath' => 'files/fmag_story/2014/Feb/NOTED_BarneysNY_BruceWeber_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '288745',
        'status' => '1',
        'timestamp' => '1393296794',
        'origname' => 'NOTED_BarneysNY_BruceWeber_3.jpg',
      ),
      '2' => array(
        'fid' => '29085',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED_BarneysNY_BruceWeber_4.jpg',
        'filepath' => 'files/fmag_story/2014/Feb/NOTED_BarneysNY_BruceWeber_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '134526',
        'status' => '1',
        'timestamp' => '1393295964',
        'origname' => 'NOTED_BarneysNY_BruceWeber_4.jpg',
      ),
      '3' => array(
        'fid' => '29086',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED_BarneysNY_BruceWeber_5.jpg',
        'filepath' => 'files/fmag_story/2014/Feb/NOTED_BarneysNY_BruceWeber_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128179',
        'status' => '1',
        'timestamp' => '1393295972',
        'origname' => 'NOTED_BarneysNY_BruceWeber_5.jpg',
      ),
      '4' => array(
        'fid' => '29088',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED_BarneysNY_BruceWeber_6.jpg',
        'filepath' => 'files/fmag_story/2014/Feb/NOTED_BarneysNY_BruceWeber_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122856',
        'status' => '1',
        'timestamp' => '1393295981',
        'origname' => 'NOTED_BarneysNY_BruceWeber_6.jpg',
      ),
      '5' => array(
        'fid' => '29089',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED_BarneysNY_BruceWeber_7.jpg',
        'filepath' => 'files/fmag_story/2014/Feb/NOTED_BarneysNY_BruceWeber_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '162542',
        'status' => '1',
        'timestamp' => '1393295989',
        'origname' => 'NOTED_BarneysNY_BruceWeber_7.jpg',
      ),
    ),
    'path' => 'stories/brothers-sisters-sons-daughters-barneysNY-bruce-weber',
    'tags' => array(
      '5' => array(
        '2795' => array(
          'tid' => '2795',
          'vid' => '5',
          'name' => 'DAN CROSBY',
          'description' => 'http://dancrosby.4ormat.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'DAN CROSBY',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
