array(
  array(
    'nid' => '4703',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1397160919',
    'changed' => '1406005270',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4703',
    'revision_uid' => '1',
    'title' => 'NOTED - KATE MOSS & TOPSHOP',
    'body' => '<p>
	The Kate Moss Topshop Collection rocks.</p>
<p>
	Get it at Hudson&#39;s Bay &amp; Topshop April 30th.</p>
',
    'teaser' => '<p>
	The Kate Moss Topshop Collection rocks.</p>
<p>
	Get it at Hudson&#39;s Bay &amp; Topshop April 30th.</p>
',
    'log' => '',
    'revision_timestamp' => '1406005270',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	KATE MOSS &amp; TOPSHOP</p>
<p>
	<a href="http://www.thebay.com/webapp/wcs/stores/servlet/en/thebay/search/womens-apparel/topshop-kate-moss-collection">AVAILABLE AT<br />
	HUDSON&#39;S BAY</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '29718',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kate-Moss-topshop_2.jpg',
        'filepath' => 'files/fmag_story/2014/Apr/Kate-Moss-topshop_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '192301',
        'status' => '1',
        'timestamp' => '1397160815',
        'origname' => 'Kate-Moss-topshop_2.jpg',
      ),
      '1' => array(
        'fid' => '29720',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kate-Moss-topshop_3.jpg',
        'filepath' => 'files/fmag_story/2014/Apr/Kate-Moss-topshop_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104017',
        'status' => '1',
        'timestamp' => '1397160823',
        'origname' => 'Kate-Moss-topshop_3.jpg',
      ),
      '2' => array(
        'fid' => '29722',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kate-Moss-topshop_4.jpg',
        'filepath' => 'files/fmag_story/2014/Apr/Kate-Moss-topshop_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131428',
        'status' => '1',
        'timestamp' => '1397160832',
        'origname' => 'Kate-Moss-topshop_4.jpg',
      ),
      '3' => array(
        'fid' => '29724',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kate-Moss-topshop_5.jpg',
        'filepath' => 'files/fmag_story/2014/Apr/Kate-Moss-topshop_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '157781',
        'status' => '1',
        'timestamp' => '1397160841',
        'origname' => 'Kate-Moss-topshop_5.jpg',
      ),
      '4' => array(
        'fid' => '29726',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kate-Moss-topshop_6.jpg',
        'filepath' => 'files/fmag_story/2014/Apr/Kate-Moss-topshop_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118164',
        'status' => '1',
        'timestamp' => '1397160848',
        'origname' => 'Kate-Moss-topshop_6.jpg',
      ),
      '5' => array(
        'fid' => '29727',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Kate-Moss-topshop_7.jpg',
        'filepath' => 'files/fmag_story/2014/Apr/Kate-Moss-topshop_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118763',
        'status' => '1',
        'timestamp' => '1397160855',
        'origname' => 'Kate-Moss-topshop_7.jpg',
      ),
    ),
    'path' => 'stories/noted-kate-moss-topshop',
    'tags' => array(
      '5' => array(
        '2525' => array(
          'tid' => '2525',
          'vid' => '5',
          'name' => 'Alexander Beer',
          'description' => 'http://www.alexanderbeerphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '1925' => array(
          'tid' => '1925',
          'vid' => '1',
          'name' => 'Hudson\'s Bay',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '200' => array(
          'tid' => '200',
          'vid' => '1',
          'name' => 'TOPSHOP',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2136' => array(
          'tid' => '2136',
          'vid' => '4',
          'name' => 'kate moss',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Alexander Beer',
        '1' => 'Hudson\'s Bay, TOPSHOP',
        '4' => 'kate moss',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
