array(
  array(
    'nid' => '4760',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1400198354',
    'changed' => '1403388307',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4760',
    'revision_uid' => '1',
    'title' => 'Jord Watches',
    'body' => '<p>
	Finally a watch you wood want.<br />
	Timepieces by <a href="http://www.woodwatches.com/">Jord</a>.</p>
',
    'teaser' => '<p>
	Finally a watch you wood want.<br />
	Timepieces by <a href="http://www.woodwatches.com/">Jord</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1403388307',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.woodwatches.com/">JORD WATCHES</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	KENNY SALE<br />
	AT CLICK</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '30449',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jord-watches_2.jpg',
        'filepath' => 'files/fmag_story/2014/May/Jord-watches_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '178859',
        'status' => '1',
        'timestamp' => '1400198326',
        'origname' => 'Jord-watches_2.jpg',
      ),
      '1' => array(
        'fid' => '30451',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jord-watches_3.jpg',
        'filepath' => 'files/fmag_story/2014/May/Jord-watches_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '150053',
        'status' => '1',
        'timestamp' => '1400198335',
        'origname' => 'Jord-watches_3.jpg',
      ),
      '2' => array(
        'fid' => '30453',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jord-watches_4.jpg',
        'filepath' => 'files/fmag_story/2014/May/Jord-watches_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '183427',
        'status' => '1',
        'timestamp' => '1400198343',
        'origname' => 'Jord-watches_4.jpg',
      ),
      '3' => array(
        'fid' => '30454',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jord-watches_5.jpg',
        'filepath' => 'files/fmag_story/2014/May/Jord-watches_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '149754',
        'status' => '1',
        'timestamp' => '1400198349',
        'origname' => 'Jord-watches_5.jpg',
      ),
    ),
    'path' => 'stories/jord-watches',
    'tags' => array(
      '5' => array(
        '2041' => array(
          'tid' => '2041',
          'vid' => '5',
          'name' => 'Gail Hadani',
          'description' => 'http://www.gailhadani.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '1985' => array(
          'tid' => '1985',
          'vid' => '1',
          'name' => 'Jord Watches',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Gail Hadani',
        '1' => 'Jord Watches',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
