array(
  array(
    'nid' => '4770',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1400439923',
    'changed' => '1402015298',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4770',
    'revision_uid' => '1',
    'title' => 'Brief Encounter',
    'body' => '<p>
	A brief story.<br />
	Exclusive photography by Hudson Taylor.<br />
	Model - Caio Cesar at LA Models &amp; Soul.</p>
',
    'teaser' => '<p>
	A brief story.<br />
	Exclusive photography by Hudson Taylor.<br />
	Model - Caio Cesar at LA Models &amp; Soul.</p>
',
    'log' => '',
    'revision_timestamp' => '1402015298',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	HUDSON TAYLOR</p>
<p>
	STYLING<br />
	VICTOR VALDEZ</p>
<p>
	MODEL<br />
	CAIO CESAR<br />
	AT LA MODELS &amp; SOUL</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '30578',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'caio-cesar_2.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/caio-cesar_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104454',
        'status' => '1',
        'timestamp' => '1401649449',
        'origname' => 'caio-cesar_2.jpg',
      ),
      '1' => array(
        'fid' => '30580',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'caio-cesar_3.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/caio-cesar_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '45607',
        'status' => '1',
        'timestamp' => '1401649457',
        'origname' => 'caio-cesar_3.jpg',
      ),
      '2' => array(
        'fid' => '30582',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'caio-cesar_4.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/caio-cesar_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132937',
        'status' => '1',
        'timestamp' => '1401649464',
        'origname' => 'caio-cesar_4.jpg',
      ),
      '3' => array(
        'fid' => '30584',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'caio-cesar_5.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/caio-cesar_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88891',
        'status' => '1',
        'timestamp' => '1401649471',
        'origname' => 'caio-cesar_5.jpg',
      ),
      '4' => array(
        'fid' => '30586',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'caio-cesar_6.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/caio-cesar_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1401649478',
        'origname' => 'caio-cesar_6.jpg',
      ),
      '5' => array(
        'fid' => '30588',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'caio-cesar_7.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/caio-cesar_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112637',
        'status' => '1',
        'timestamp' => '1401649485',
        'origname' => 'caio-cesar_7.jpg',
      ),
      '6' => array(
        'fid' => '30590',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'caio-cesar_8.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/caio-cesar_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132877',
        'status' => '1',
        'timestamp' => '1401649492',
        'origname' => 'caio-cesar_8.jpg',
      ),
      '7' => array(
        'fid' => '30592',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'caio-cesar_9.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/caio-cesar_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108722',
        'status' => '1',
        'timestamp' => '1401649501',
        'origname' => 'caio-cesar_9.jpg',
      ),
      '8' => array(
        'fid' => '30594',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'caio-cesar_10.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/caio-cesar_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85984',
        'status' => '1',
        'timestamp' => '1401649510',
        'origname' => 'caio-cesar_10.jpg',
      ),
      '9' => array(
        'fid' => '30595',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'caio-cesar_11.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/caio-cesar_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104178',
        'status' => '1',
        'timestamp' => '1401649516',
        'origname' => 'caio-cesar_11.jpg',
      ),
    ),
    'path' => 'stories/brief-encounter-0',
    'tags' => array(
      '5' => array(
        '2805' => array(
          'tid' => '2805',
          'vid' => '5',
          'name' => 'HUDSON TAYLOR',
          'description' => 'http://www.hudsontaylorphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'HUDSON TAYLOR',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
