array(
  array(
    'nid' => '4810',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1404147466',
    'changed' => '1404919683',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4810',
    'revision_uid' => '1',
    'title' => 'Cause A Stir',
    'body' => '<p>
	Stir it up.<br />
	Exclusive photography by <a href="http://richarddubois.com/">Richard Dubois</a>.<br />
	Model - Caitlin Dudar at <a href="http://www.plutinogroup.com/">Plutino</a>.</p>
',
    'teaser' => '<p>
	Stir it up.<br />
	Exclusive photography by <a href="http://richarddubois.com/">Richard Dubois</a>.<br />
	Model - Caitlin Dudar at <a href="http://www.plutinogroup.com/">Plutino</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1404919683',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Master photographer <a href="http://richarddubois.com/">Richard DuBois</a> get <a href="http://www.plutinogroup.com/">Plutino</a>&#39;s Caitlin Dudar to stir things up!</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://richarddubois.com/">RICHARD DUBOIS</a></p>
<p>
	STYLIST<br />
	Annie Lam<br />
	&nbsp;</p>
<p>
	MAKEUP<br />
	Elena Pacienza<br />
	HAIR<br />
	Dat Tran<br />
	at <a href="http://www.pushthetalent.com/">Push</a></p>
<p>
	<br />
	MODEL<br />
	Caitlin Dudar<br />
	at <a href="http://www.plutinogroup.com/">Plutino</a><br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '31197',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_2.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '35188',
        'status' => '1',
        'timestamp' => '1404147424',
        'origname' => 'Caitlin-Dudar-dubois_2.jpg',
      ),
      '1' => array(
        'fid' => '31199',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_3.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140532',
        'status' => '1',
        'timestamp' => '1404147434',
        'origname' => 'Caitlin-Dudar-dubois_3.jpg',
      ),
      '2' => array(
        'fid' => '31201',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_4.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87611',
        'status' => '1',
        'timestamp' => '1404147446',
        'origname' => 'Caitlin-Dudar-dubois_4.jpg',
      ),
      '3' => array(
        'fid' => '31203',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_5.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '72584',
        'status' => '1',
        'timestamp' => '1404147458',
        'origname' => 'Caitlin-Dudar-dubois_5.jpg',
      ),
      '4' => array(
        'fid' => '31205',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_6.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '71527',
        'status' => '1',
        'timestamp' => '1404147498',
        'origname' => 'Caitlin-Dudar-dubois_6.jpg',
      ),
      '5' => array(
        'fid' => '31207',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_7.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '99861',
        'status' => '1',
        'timestamp' => '1404147506',
        'origname' => 'Caitlin-Dudar-dubois_7.jpg',
      ),
      '6' => array(
        'fid' => '31209',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_8.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84218',
        'status' => '1',
        'timestamp' => '1404147517',
        'origname' => 'Caitlin-Dudar-dubois_8.jpg',
      ),
      '7' => array(
        'fid' => '31211',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_9.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82431',
        'status' => '1',
        'timestamp' => '1404147525',
        'origname' => 'Caitlin-Dudar-dubois_9.jpg',
      ),
      '8' => array(
        'fid' => '31213',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_10.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1404147534',
        'origname' => 'Caitlin-Dudar-dubois_10.jpg',
      ),
      '9' => array(
        'fid' => '31215',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_11.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160906',
        'status' => '1',
        'timestamp' => '1404147546',
        'origname' => 'Caitlin-Dudar-dubois_11.jpg',
      ),
      '10' => array(
        'fid' => '31216',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_12.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19990',
        'status' => '1',
        'timestamp' => '1404147556',
        'origname' => 'Caitlin-Dudar-dubois_12.jpg',
      ),
      '11' => array(
        'fid' => '31218',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_13.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77663',
        'status' => '1',
        'timestamp' => '1404147572',
        'origname' => 'Caitlin-Dudar-dubois_13.jpg',
      ),
      '12' => array(
        'fid' => '31220',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_14.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95003',
        'status' => '1',
        'timestamp' => '1404147584',
        'origname' => 'Caitlin-Dudar-dubois_14.jpg',
      ),
      '13' => array(
        'fid' => '31221',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Caitlin-Dudar-dubois_15.jpg',
        'filepath' => 'files/fmag_story/2014/Jun/Caitlin-Dudar-dubois_15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109083',
        'status' => '1',
        'timestamp' => '1404147594',
        'origname' => 'Caitlin-Dudar-dubois_15.jpg',
      ),
    ),
    'path' => 'stories/cause-stir',
    'tags' => array(
      '1' => array(
        '661' => array(
          'tid' => '661',
          'vid' => '1',
          'name' => 'chinese laundry',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '2077' => array(
          'tid' => '2077',
          'vid' => '1',
          'name' => 'James Perse',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '232' => array(
          'tid' => '232',
          'vid' => '1',
          'name' => 'KARA ROSS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '2076' => array(
          'tid' => '2076',
          'vid' => '1',
          'name' => 'Marciano',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '2075' => array(
          'tid' => '2075',
          'vid' => '1',
          'name' => 'Tia Cibani',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2548' => array(
          'tid' => '2548',
          'vid' => '5',
          'name' => 'Richard Dubois',
          'description' => 'http://www.duboisphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'chinese laundry, James Perse, KARA ROSS, Marciano, Tia Cibani',
        '5' => 'Richard Dubois',
        '4' => 'women',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
