array(
  array(
    'nid' => '4814',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1405095420',
    'changed' => '1405515540',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4814',
    'revision_uid' => '1',
    'title' => 'Anomaly',
    'body' => '<p>
	Some definite patterns developing.<br />
	Exclusive photography by <a href="http://www.loisbielefeld.com/">Lois Bielefeld</a>.<br />
	Model - Leah Reynolds at <a href="http://models.fordmodels.com">Ford Chicago</a>.</p>
',
    'teaser' => '<p>
	Some definite patterns developing.<br />
	Exclusive photography by <a href="http://www.loisbielefeld.com/">Lois Bielefeld</a>.<br />
	Model - Leah Reynolds at <a href="http://models.fordmodels.com">Ford Chicago</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1405515540',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Fantabulous photographer <a href="http://www.loisbielefeld.com/">Lois Bielefeld</a> shoots <a href="http://models.fordmodels.com">Ford Chicago</a> model Leah Reynolds in provocative prints and patterns from <a href="http://www.etro.com/en_us/">Etro</a>, <a href="http://www.givenchy.com/">Givenchy</a>, <a href="http://www.peterpilotto.com">Peter Pilotto</a>, and <a href="http://www.robertocavalli.com/">Cavalli</a>. Printastic!<br />
	See the <a href="http://www.fantasticsmag.com/videos/video-anomaly-film-justin-linnemeier-lois-bielefeld">video</a>!</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.loisbielefeld.com/">LOIS Bielefeld</a></p>
<p>
	DIRECTION<br />
	Saud Khazal</p>
<p>
	STYLING &amp; CONCEPT<br />
	Maggie Cressman</p>
<p>
	VIDEO<br />
	Justin Linnemeier<br />
	&nbsp;</p>
<p>
	MAKEUP<br />
	Tonya Noland</p>
<p>
	<br />
	HAIR<br />
	Kristen Baker</p>
<p>
	PROP &amp; SET STYLIST<br />
	Sheila Teruty</p>
<p>
	<br />
	MODEL<br />
	Leah Reynolds<br />
	at <a href="http://models.fordmodels.com">Ford Chicago</a><br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '31251',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_2 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113645',
        'status' => '1',
        'timestamp' => '1405007847',
        'origname' => 'leah-reynolds-anomaly_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '31312',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '889125',
        'status' => '1',
        'timestamp' => '1405515534',
        'origname' => 'leah-reynolds-anomaly copy.jpg',
      ),
      '2' => array(
        'fid' => '31255',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_4 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1013469',
        'status' => '1',
        'timestamp' => '1405007863',
        'origname' => 'leah-reynolds-anomaly_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '31256',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_5 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93416',
        'status' => '1',
        'timestamp' => '1405007869',
        'origname' => 'leah-reynolds-anomaly_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '31258',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_6 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91675',
        'status' => '1',
        'timestamp' => '1405007882',
        'origname' => 'leah-reynolds-anomaly_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '31260',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_7 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '924221',
        'status' => '1',
        'timestamp' => '1405007890',
        'origname' => 'leah-reynolds-anomaly_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '31262',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_8 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '982928',
        'status' => '1',
        'timestamp' => '1405007899',
        'origname' => 'leah-reynolds-anomaly_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '31264',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_9 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86190',
        'status' => '1',
        'timestamp' => '1405007908',
        'origname' => 'leah-reynolds-anomaly_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '31266',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_10 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '745129',
        'status' => '1',
        'timestamp' => '1405007917',
        'origname' => 'leah-reynolds-anomaly_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '31268',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_11 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1061741',
        'status' => '1',
        'timestamp' => '1405007925',
        'origname' => 'leah-reynolds-anomaly_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '31270',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_12 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83268',
        'status' => '1',
        'timestamp' => '1405007933',
        'origname' => 'leah-reynolds-anomaly_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '31271',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_13 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '738491',
        'status' => '1',
        'timestamp' => '1405007940',
        'origname' => 'leah-reynolds-anomaly_13 copy.jpg',
      ),
      '12' => array(
        'fid' => '31272',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_14 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '933680',
        'status' => '1',
        'timestamp' => '1405007950',
        'origname' => 'leah-reynolds-anomaly_14 copy.jpg',
      ),
      '13' => array(
        'fid' => '31273',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'leah-reynolds-anomaly_15 copy.jpg',
        'filepath' => 'files/fmag_story/2014/Jul/leah-reynolds-anomaly_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83539',
        'status' => '1',
        'timestamp' => '1405007961',
        'origname' => 'leah-reynolds-anomaly_15 copy.jpg',
      ),
    ),
    'path' => 'stories/anomaly',
    'tags' => array(
      '1' => array(
        '2107' => array(
          'tid' => '2107',
          'vid' => '1',
          'name' => 'CAVALLI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1163' => array(
          'tid' => '1163',
          'vid' => '1',
          'name' => 'costume national',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '249' => array(
          'tid' => '249',
          'vid' => '1',
          'name' => 'ETRO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '372' => array(
          'tid' => '372',
          'vid' => '1',
          'name' => 'givenchy',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '2104' => array(
          'tid' => '2104',
          'vid' => '1',
          'name' => 'LAPIS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1583' => array(
          'tid' => '1583',
          'vid' => '1',
          'name' => 'Peter Pilotto',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '2106' => array(
          'tid' => '2106',
          'vid' => '1',
          'name' => 'PREEN BY THORTON BREGAZZI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '2105' => array(
          'tid' => '2105',
          'vid' => '1',
          'name' => 'TEMPERLEY LONDON',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2102' => array(
          'tid' => '2102',
          'vid' => '4',
          'name' => 'ford models',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2101' => array(
          'tid' => '2101',
          'vid' => '4',
          'name' => 'leah reynolds',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2100' => array(
          'tid' => '2100',
          'vid' => '4',
          'name' => 'lois bielefeld',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2103' => array(
          'tid' => '2103',
          'vid' => '4',
          'name' => 'prints',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2718' => array(
          'tid' => '2718',
          'vid' => '5',
          'name' => 'LOIS BIELEFELD',
          'description' => 'http://www.loisbielefeld.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'CAVALLI, costume national, ETRO, givenchy, LAPIS, Peter Pilotto, PREEN BY THORTON BREGAZZI, TEMPERLEY LONDON',
        '4' => 'ford models, leah reynolds, lois bielefeld, prints, women',
        '5' => 'LOIS BIELEFELD',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
