array(
  array(
    'nid' => '4947',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1414766296',
    'changed' => '1415402308',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4947',
    'revision_uid' => '1',
    'title' => 'Noted - Geisha by ',
    'body' => '<p>
	Note <a href="http://www.balijames.com">Geisha by Bali James</a>.<br />
	Exclusive photography by <a href="http://www.pixyst.com">David Apeji</a>.</p>
',
    'teaser' => '<p>
	Note <a href="http://www.balijames.com">Geisha by Bali James</a>.<br />
	Exclusive photography by <a href="http://www.pixyst.com">David Apeji</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1415402308',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Beauty Editor Derric Lowe says indulge in skin care collection <a href="http://www.balijames.com">Geisha by Bali James</a>.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.pixyst.com">David Apeji</a></p>
<p>
	BEAUTY EDITOR<br />
	Derric Lowe<br />
	<br />
	MAKEUP &amp; HAIR<br />
	Pearl Espinoza</p>
<p>
	MODEL<br />
	Taylor Howard<br />
	at Ford/RBA</p>
<p>
	VINTAGE FASHION<br />
	Fashion by Robert Black</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '33623',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED-Geisha-Bali_James2.jpg',
        'filepath' => 'files/fmag_story/2014/Nov/NOTED-Geisha-Bali_James2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '737524',
        'status' => '1',
        'timestamp' => '1415211071',
        'origname' => 'NOTED-Geisha-Bali_James2.jpg',
      ),
      '1' => array(
        'fid' => '33624',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED-Geisha-Bali_James3.jpg',
        'filepath' => 'files/fmag_story/2014/Nov/NOTED-Geisha-Bali_James3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '518638',
        'status' => '1',
        'timestamp' => '1415211078',
        'origname' => 'NOTED-Geisha-Bali_James3.jpg',
      ),
      '2' => array(
        'fid' => '33626',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED-Geisha-Bali_James4.jpg',
        'filepath' => 'files/fmag_story/2014/Nov/NOTED-Geisha-Bali_James4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '624043',
        'status' => '1',
        'timestamp' => '1415211091',
        'origname' => 'NOTED-Geisha-Bali_James4.jpg',
      ),
      '3' => array(
        'fid' => '33628',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED-Geisha-Bali_James5.jpg',
        'filepath' => 'files/fmag_story/2014/Nov/NOTED-Geisha-Bali_James5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '479159',
        'status' => '1',
        'timestamp' => '1415211100',
        'origname' => 'NOTED-Geisha-Bali_James5.jpg',
      ),
      '4' => array(
        'fid' => '33630',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED-Geisha-Bali_James6.jpg',
        'filepath' => 'files/fmag_story/2014/Nov/NOTED-Geisha-Bali_James6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '403294',
        'status' => '1',
        'timestamp' => '1415211109',
        'origname' => 'NOTED-Geisha-Bali_James6.jpg',
      ),
      '5' => array(
        'fid' => '33631',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTED-Geisha-Bali_James7.jpg',
        'filepath' => 'files/fmag_story/2014/Nov/NOTED-Geisha-Bali_James7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '516574',
        'status' => '1',
        'timestamp' => '1415211117',
        'origname' => 'NOTED-Geisha-Bali_James7.jpg',
      ),
    ),
    'path' => 'stories/noted-geisha',
    'tags' => array(
      '5' => array(
        '2776' => array(
          'tid' => '2776',
          'vid' => '5',
          'name' => 'DAVID APEJI',
          'description' => 'http://www.pixyst.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '2343' => array(
          'tid' => '2343',
          'vid' => '1',
          'name' => 'Fashion by Robert Black',
          'description' => 'www.fashionbyrobertblack.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => array(
            'ext_url' => '',
          ),
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'DAVID APEJI',
        '1' => 'Fashion by Robert Black',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
