array(
  array(
    'nid' => '3924',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1325448454',
    'changed' => '1331214723',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3924',
    'revision_uid' => '1',
    'title' => 'Choice 6',
    'body' => '<p>
	Some of our choicest cuts from 2011. The year in review part six.</p>
<p>
	&nbsp;</p>
',
    'teaser' => '<p>
	Some of our choicest cuts from 2011. The year in review part six.</p>
<p>
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1331214723',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	THE YEAR<br />
	IN REVIEW<br />
	PART SIX</p>
<p>
	COVER STORY<br />
	<a href="http://www.fantasticsmag.com/stories/i-want-be-perfect">I WANT TO BE PERFECT</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/house-dress">HOUSE DRESS</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/stardust">STARDUST</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/prepitary-academy">PREPITARY ACADEMY</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/hair-cut">HAIR CUT</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/kris-kranz">KRIS KRANZ</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/renata">RENATA</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/leather-weather">LEATHER WEATHER</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/knit-happy">KNIT HAPPY</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/hook">HOOK UP</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/sharp">SHARP</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/roman-fisher">ROMAN FISHER</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/brisk">BRISK</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/coat-check">COAT CHECK</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/stormy-weather">STORMY WEATHER</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/twist">TWIST</a></p>
<p>
	<a href="http://www.fantasticsmag.com/stories/nate-voronyak">NATE VORONYAK</a></p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '15978',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-142.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-142.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156897',
        'status' => '1',
        'timestamp' => '1325102884',
        'origname' => 'Layout-1_Page-142.jpg',
      ),
      '1' => array(
        'fid' => '15979',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-143.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-143.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161901',
        'status' => '1',
        'timestamp' => '1325102895',
        'origname' => 'Layout-1_Page-143.jpg',
      ),
      '2' => array(
        'fid' => '16106',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-104.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-104.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '153816',
        'status' => '1',
        'timestamp' => '1325104152',
        'origname' => 'Layout-1_Page-104.jpg',
      ),
      '3' => array(
        'fid' => '16108',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-105.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-105.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161646',
        'status' => '1',
        'timestamp' => '1325104164',
        'origname' => 'Layout-1_Page-105.jpg',
      ),
      '4' => array(
        'fid' => '16110',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-106.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-106.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101097',
        'status' => '1',
        'timestamp' => '1325104173',
        'origname' => 'Layout-1_Page-106.jpg',
      ),
      '5' => array(
        'fid' => '16112',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-107.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-107.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83996',
        'status' => '1',
        'timestamp' => '1325104182',
        'origname' => 'Layout-1_Page-107.jpg',
      ),
      '6' => array(
        'fid' => '16114',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-108.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-108.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82842',
        'status' => '1',
        'timestamp' => '1325104192',
        'origname' => 'Layout-1_Page-108.jpg',
      ),
      '7' => array(
        'fid' => '16116',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-109.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-109.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84134',
        'status' => '1',
        'timestamp' => '1325104201',
        'origname' => 'Layout-1_Page-109.jpg',
      ),
      '8' => array(
        'fid' => '16118',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-110.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-110.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '186574',
        'status' => '1',
        'timestamp' => '1325104215',
        'origname' => 'Layout-1_Page-110.jpg',
      ),
      '9' => array(
        'fid' => '16120',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-111.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-111.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '231699',
        'status' => '1',
        'timestamp' => '1325104228',
        'origname' => 'Layout-1_Page-111.jpg',
      ),
      '10' => array(
        'fid' => '16122',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-112.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-112.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102125',
        'status' => '1',
        'timestamp' => '1325104240',
        'origname' => 'Layout-1_Page-112.jpg',
      ),
      '11' => array(
        'fid' => '16124',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-113.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-113.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87635',
        'status' => '1',
        'timestamp' => '1325104250',
        'origname' => 'Layout-1_Page-113.jpg',
      ),
      '12' => array(
        'fid' => '16126',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-114.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-114.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84343',
        'status' => '1',
        'timestamp' => '1325104262',
        'origname' => 'Layout-1_Page-114.jpg',
      ),
      '13' => array(
        'fid' => '16128',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-115.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-115.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '30642',
        'status' => '1',
        'timestamp' => '1325104271',
        'origname' => 'Layout-1_Page-115.jpg',
      ),
      '14' => array(
        'fid' => '16130',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-116.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-116.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155320',
        'status' => '1',
        'timestamp' => '1325104284',
        'origname' => 'Layout-1_Page-116.jpg',
      ),
      '15' => array(
        'fid' => '16132',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-117.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-117.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88807',
        'status' => '1',
        'timestamp' => '1325104294',
        'origname' => 'Layout-1_Page-117.jpg',
      ),
      '16' => array(
        'fid' => '16134',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-118.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-118.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '177356',
        'status' => '1',
        'timestamp' => '1325104308',
        'origname' => 'Layout-1_Page-118.jpg',
      ),
      '17' => array(
        'fid' => '16136',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-119.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-119.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73628',
        'status' => '1',
        'timestamp' => '1325104317',
        'origname' => 'Layout-1_Page-119.jpg',
      ),
      '18' => array(
        'fid' => '16138',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-120.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-120.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '254643',
        'status' => '1',
        'timestamp' => '1325104333',
        'origname' => 'Layout-1_Page-120.jpg',
      ),
      '19' => array(
        'fid' => '16140',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-121.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-121.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88955',
        'status' => '1',
        'timestamp' => '1325104343',
        'origname' => 'Layout-1_Page-121.jpg',
      ),
      '20' => array(
        'fid' => '16142',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-122.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-122.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158328',
        'status' => '1',
        'timestamp' => '1325104356',
        'origname' => 'Layout-1_Page-122.jpg',
      ),
      '21' => array(
        'fid' => '16143',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-123.jpg',
        'filepath' => 'files/fmag_story/2011/Dec/Layout-1_Page-123.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '159252',
        'status' => '1',
        'timestamp' => '1325104364',
        'origname' => 'Layout-1_Page-123.jpg',
      ),
    ),
    'path' => 'stories/choice-6',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
