array(
  array(
    'nid' => '3934',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1326222523',
    'changed' => '1403838948',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3934',
    'revision_uid' => '1',
    'title' => 'Heather DePriest',
    'body' => '<p>
	Hurray for Heather.<br />
	Exclusive photography by <a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">Aldo Rossi</a>.</p>
',
    'teaser' => '<p>
	Hurray for Heather.<br />
	Exclusive photography by <a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">Aldo Rossi</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838948',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">ALDO ROSSI</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	ERIC BERG<br />
	AT REX ARTISTS</p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	DINA GREGG<br />
	AT AIM ARTISTS<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	RAMSELL MARTINEZ<br />
	AT REX ARTISTS</p>
<p>
	&nbsp;</p>
<p>
	REPRESENTED<br />
	BY PINKERTON</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16251',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 2 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141213',
        'status' => '1',
        'timestamp' => '1326229361',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '16215',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 3 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '440550',
        'status' => '1',
        'timestamp' => '1326222312',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '16217',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 4 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88194',
        'status' => '1',
        'timestamp' => '1326222321',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '16219',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 5 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1294422',
        'status' => '1',
        'timestamp' => '1326222331',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '16222',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 6 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1122224',
        'status' => '1',
        'timestamp' => '1326222353',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '16223',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 7 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '404307',
        'status' => '1',
        'timestamp' => '1326222371',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '16225',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 8 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1191241',
        'status' => '1',
        'timestamp' => '1326222388',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '16227',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 9 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1109813',
        'status' => '1',
        'timestamp' => '1326222397',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '16229',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 10 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1134455',
        'status' => '1',
        'timestamp' => '1326222406',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '16231',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 11 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1092700',
        'status' => '1',
        'timestamp' => '1326222416',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '16233',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 12 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75378',
        'status' => '1',
        'timestamp' => '1326222424',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '16235',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 13 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1140063',
        'status' => '1',
        'timestamp' => '1326222434',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
      '12' => array(
        'fid' => '16237',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 14 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1143226',
        'status' => '1',
        'timestamp' => '1326222444',
        'origname' => 'Layout 1_Page 14 copy.jpg',
      ),
      '13' => array(
        'fid' => '16239',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 15 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1129453',
        'status' => '1',
        'timestamp' => '1326222456',
        'origname' => 'Layout 1_Page 15 copy.jpg',
      ),
      '14' => array(
        'fid' => '16241',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 16 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 16 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1080711',
        'status' => '1',
        'timestamp' => '1326222468',
        'origname' => 'Layout 1_Page 16 copy.jpg',
      ),
      '15' => array(
        'fid' => '16243',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 17 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 17 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1103464',
        'status' => '1',
        'timestamp' => '1326222476',
        'origname' => 'Layout 1_Page 17 copy.jpg',
      ),
      '16' => array(
        'fid' => '16244',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 18 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 18 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1419553',
        'status' => '1',
        'timestamp' => '1326222486',
        'origname' => 'Layout 1_Page 18 copy.jpg',
      ),
      '17' => array(
        'fid' => '16246',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 19 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 19 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '284348',
        'status' => '1',
        'timestamp' => '1326222497',
        'origname' => 'Layout 1_Page 19 copy.jpg',
      ),
      '18' => array(
        'fid' => '16252',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 20 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 20 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '171202',
        'status' => '1',
        'timestamp' => '1326286629',
        'origname' => 'Layout 1_Page 20 copy.jpg',
      ),
      '19' => array(
        'fid' => '16249',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 21 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 21 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1149739',
        'status' => '1',
        'timestamp' => '1326222515',
        'origname' => 'Layout 1_Page 21 copy.jpg',
      ),
    ),
    'path' => 'stories/heather-depriest',
    'tags' => array(
      '5' => array(
        '2633' => array(
          'tid' => '2633',
          'vid' => '5',
          'name' => 'ALDO ROSSI',
          'description' => 'http://www.studioaldorossi.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ALDO ROSSI',
        '4' => 'women',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
