array(
  array(
    'nid' => '3942',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1326988427',
    'changed' => '1403838733',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3942',
    'revision_uid' => '1',
    'title' => 'Isaac Sullivan',
    'body' => '<p>
	Eyes on Isaac.<br />
	Exclusive photography by <a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">Aldo Rossi</a>.</p>
',
    'teaser' => '<p>
	Eyes on Isaac.<br />
	Exclusive photography by <a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">Aldo Rossi</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838733',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.studioaldorossi.com/3/artist.asp?ArtistID=7425&amp;Akey=T8KNT945">ALDO ROSSI</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	ERIC BERG<br />
	AT REX ARTISTS</p>
<p>
	&nbsp;</p>
<p>
	GROOMING<br />
	DINA GREGG<br />
	AT AIM ARTISTS</p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	RAMSELL MARTINEZ<br />
	AT REX ARTISTS</p>
<p>
	&nbsp;</p>
<p>
	REPRESENTED<br />
	BY BOSS</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16321',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 2 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '113839',
        'status' => '1',
        'timestamp' => '1326988218',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '16323',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 3 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '456011',
        'status' => '1',
        'timestamp' => '1326988228',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '16325',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 4 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '446572',
        'status' => '1',
        'timestamp' => '1326988238',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '16326',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 5 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '254697',
        'status' => '1',
        'timestamp' => '1326988251',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '16328',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 6 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '276394',
        'status' => '1',
        'timestamp' => '1326988269',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '16329',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 7 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '276536',
        'status' => '1',
        'timestamp' => '1326988307',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '16331',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 8 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173358',
        'status' => '1',
        'timestamp' => '1326988328',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '16332',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 9 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '232501',
        'status' => '1',
        'timestamp' => '1326988343',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '16333',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 10 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75240',
        'status' => '1',
        'timestamp' => '1326988362',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '16334',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 11 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '265806',
        'status' => '1',
        'timestamp' => '1326988382',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '16335',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 12 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '321977',
        'status' => '1',
        'timestamp' => '1326988400',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '16336',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 13 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '350123',
        'status' => '1',
        'timestamp' => '1326988415',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
    ),
    'path' => 'stories/isaac-sullivan',
    'tags' => array(
      '5' => array(
        '2633' => array(
          'tid' => '2633',
          'vid' => '5',
          'name' => 'ALDO ROSSI',
          'description' => 'http://www.studioaldorossi.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '606' => array(
          'tid' => '606',
          'vid' => '1',
          'name' => 'Belgium',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '604' => array(
          'tid' => '604',
          'vid' => '1',
          'name' => 'Dirtee Hollywood',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '547' => array(
          'tid' => '547',
          'vid' => '1',
          'name' => 'g-star',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '605' => array(
          'tid' => '605',
          'vid' => '1',
          'name' => 'Goodsouls',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '603' => array(
          'tid' => '603',
          'vid' => '1',
          'name' => 'Nicholas K',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '157' => array(
          'tid' => '157',
          'vid' => '1',
          'name' => 'Tommy Hilfiger',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ALDO ROSSI',
        '1' => 'Belgium, Dirtee Hollywood, g-star, Goodsouls, Nicholas K, Tommy Hilfiger',
        '4' => 'men',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
