array(
  array(
    'nid' => '3946',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1327524058',
    'changed' => '1405544107',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3946',
    'revision_uid' => '1',
    'title' => 'Under',
    'body' => '<p>
	Under says it all.<br />
	Exclusive photography by <a href="http://www.michaelfranco.net/">Michael Franco</a>.</p>
',
    'teaser' => '<p>
	Under says it all.<br />
	Exclusive photography by <a href="http://www.michaelfranco.net/">Michael Franco</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1405544107',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://underunderwear.com/">UNDER UNDERWEAR</a></p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.michaelfranco.net/">MICHAEL FRANCO</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	CHRISTIAN O&#39;CONNELL<br />
	AT THE AGENCY</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16369',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 2 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '618691',
        'status' => '1',
        'timestamp' => '1327523848',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '16370',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 3 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '135308',
        'status' => '1',
        'timestamp' => '1327523865',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '16371',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 4 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '324808',
        'status' => '1',
        'timestamp' => '1327523886',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '16372',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 5 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '346093',
        'status' => '1',
        'timestamp' => '1327523910',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '16373',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 6 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '686648',
        'status' => '1',
        'timestamp' => '1327523934',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '16374',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 7 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '706388',
        'status' => '1',
        'timestamp' => '1327523957',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '16375',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 8 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '311046',
        'status' => '1',
        'timestamp' => '1327523979',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '16376',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 9 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '387704',
        'status' => '1',
        'timestamp' => '1327524006',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '16378',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 10 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131220',
        'status' => '1',
        'timestamp' => '1327524036',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '16379',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jan/Layout 1_Page 11 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '592040',
        'status' => '1',
        'timestamp' => '1327524046',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
    ),
    'path' => 'stories/under',
    'tags' => array(
      '4' => array(
        '2114' => array(
          'tid' => '2114',
          'vid' => '4',
          'name' => 'beards',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2624' => array(
          'tid' => '2624',
          'vid' => '5',
          'name' => 'KAT + DUCK',
          'description' => 'http://www.katandduck.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'beards, men',
        '5' => 'KAT + DUCK',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
