array(
  array(
    'nid' => '3958',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1328552999',
    'changed' => '1403838733',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3958',
    'revision_uid' => '1',
    'title' => 'Spring Awakening',
    'body' => '<p>
	Spruce up for spring.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.<br />
	Model ~ Josh Copeland at Select.</p>
',
    'teaser' => '<p>
	Spruce up for spring.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.<br />
	Model ~ Josh Copeland at Select.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838733',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://darrenblackphotography.com/">DARREN BLACK</a></p>
<p>
	&nbsp;</p>
<p>
	ALL FASHION<br />
	AT <a href="http://www.harveynichols.com/">HARVEY NICHOLS</a></p>
<p>
	&nbsp;</p>
<p>
	CONCEPT<br />
	NEIL HOLBROOK</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	MICHAEL TEMPRANO</p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	JOSH COPELAND<br />
	AT SELECT</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16604',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 2 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '596914',
        'status' => '1',
        'timestamp' => '1328552860',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '16606',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 3 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '708766',
        'status' => '1',
        'timestamp' => '1328552877',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '16607',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 4 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '105569',
        'status' => '1',
        'timestamp' => '1328552885',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '16609',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 5 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1013165',
        'status' => '1',
        'timestamp' => '1328552903',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '16610',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 6 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '837544',
        'status' => '1',
        'timestamp' => '1328552912',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '16611',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 7 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96212',
        'status' => '1',
        'timestamp' => '1328552927',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '16612',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 8 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1042232',
        'status' => '1',
        'timestamp' => '1328552945',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '16613',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 9 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1072128',
        'status' => '1',
        'timestamp' => '1328552962',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '16615',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 10 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102781',
        'status' => '1',
        'timestamp' => '1328552977',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '16616',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 11 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1043892',
        'status' => '1',
        'timestamp' => '1328552990',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
    ),
    'path' => 'stories/spring-awakening-0',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
