array(
  array(
    'nid' => '3960',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1328636756',
    'changed' => '1403838946',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3960',
    'revision_uid' => '1',
    'title' => 'Blonde Moment',
    'body' => '<p>
	Get wiggy with it.<br />
	Exclusive photography by <a href="http://www.katandduck.com/">KAT + DUCK</a>.<br />
	Model ~ Davis at Red.</p>
',
    'teaser' => '<p>
	Get wiggy with it.<br />
	Exclusive photography by <a href="http://www.katandduck.com/">KAT + DUCK</a>.<br />
	Model ~ Davis at Red.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838946',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.katandduck.com/">KAT + DUCK</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	DAVIS AT RED</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16619',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 2 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '327134',
        'status' => '1',
        'timestamp' => '1328636588',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '16621',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 3 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '562657',
        'status' => '1',
        'timestamp' => '1328636601',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '16623',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 4 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '636619',
        'status' => '1',
        'timestamp' => '1328636615',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '16624',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 5 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '628127',
        'status' => '1',
        'timestamp' => '1328636627',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '16626',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 6 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '358045',
        'status' => '1',
        'timestamp' => '1328636650',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '16627',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 7 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '584774',
        'status' => '1',
        'timestamp' => '1328636664',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '16629',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 8 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '411166',
        'status' => '1',
        'timestamp' => '1328636685',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '16631',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 9 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '397603',
        'status' => '1',
        'timestamp' => '1328636700',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '16632',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 10 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '420962',
        'status' => '1',
        'timestamp' => '1328636710',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '16634',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 11 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '443237',
        'status' => '1',
        'timestamp' => '1328636727',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '16636',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 12 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '608243',
        'status' => '1',
        'timestamp' => '1328636737',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '16637',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 13 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '668119',
        'status' => '1',
        'timestamp' => '1328636746',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
    ),
    'path' => 'stories/blonde-moment',
    'tags' => array(
      '5' => array(
        '2624' => array(
          'tid' => '2624',
          'vid' => '5',
          'name' => 'KAT + DUCK',
          'description' => 'http://www.katandduck.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'KAT + DUCK',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
