array(
  array(
    'nid' => '3962',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1328815061',
    'changed' => '1403838733',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3962',
    'revision_uid' => '1',
    'title' => 'Timoteo Ocampo',
    'body' => '<p>
	Designer &amp; retailer&nbsp; <a href="https://www.timoteo.net/store/index.php?&amp;ccUser=">Timoteo</a> Ocampo.<br />
	Exclusive photography by <a href="http://www.modelmayhem.com/1693912">David Wagner</a>.<br />
	Interview by James Nixon.</p>
',
    'teaser' => '<p>
	Designer &amp; retailer&nbsp; <a href="https://www.timoteo.net/store/index.php?&amp;ccUser=">Timoteo</a> Ocampo.<br />
	Exclusive photography by <a href="http://www.modelmayhem.com/1693912">David Wagner</a>.<br />
	Interview by James Nixon.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838733',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="https://www.timoteo.net/store/index.php?&amp;ccUser=a59ea4769211688676813b691f915269">TIMOTEO</a></p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.modelmayhem.com/1693912">DAVID WAGNER</a></p>
<p>
	&nbsp;</p>
<p>
	INTERVIEW BY<br />
	JAMES NIXON</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	MICHAEL HOLLAND</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16662',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 2 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '163000',
        'status' => '1',
        'timestamp' => '1328816375',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '16641',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 3 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '587745',
        'status' => '1',
        'timestamp' => '1328814907',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '16643',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 4 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '559179',
        'status' => '1',
        'timestamp' => '1328814946',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '16645',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 5 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '367624',
        'status' => '1',
        'timestamp' => '1328814956',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '16647',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 6 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '609837',
        'status' => '1',
        'timestamp' => '1328814968',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '16649',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 7 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '573335',
        'status' => '1',
        'timestamp' => '1328814978',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '16651',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 8 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '389824',
        'status' => '1',
        'timestamp' => '1328814990',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '16653',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 9 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '651425',
        'status' => '1',
        'timestamp' => '1328815000',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '16655',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 10 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '611149',
        'status' => '1',
        'timestamp' => '1328815012',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '16657',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 11 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '621967',
        'status' => '1',
        'timestamp' => '1328815025',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '16659',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 12 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '306767',
        'status' => '1',
        'timestamp' => '1328815036',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '16660',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 13 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '597436',
        'status' => '1',
        'timestamp' => '1328815048',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
    ),
    'path' => 'stories/timoteo-ocampo',
    'tags' => array(
      '5' => array(
        '2624' => array(
          'tid' => '2624',
          'vid' => '5',
          'name' => 'KAT + DUCK',
          'description' => 'http://www.katandduck.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'KAT + DUCK',
        '4' => 'men',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
