array(
  array(
    'nid' => '3964',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1328909269',
    'changed' => '1403838946',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3964',
    'revision_uid' => '1',
    'title' => 'Fever Pitch',
    'body' => '<p>
	Temperatures rising.<br />
	Exclusive photography by <a href="http://www.adamodepax.com/site/site.html">A</a><a href="http://www.adamodepax.com/site/site.html">Damo De Pax</a>.<br />
	Model ~ Irina F at Elite.</p>
',
    'teaser' => '<p>
	Temperatures rising.<br />
	Exclusive photography by <a href="http://www.adamodepax.com/site/site.html">A</a><a href="http://www.adamodepax.com/site/site.html">Damo De Pax</a>.<br />
	Model ~ Irina F at Elite.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838946',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.adamodepax.com/site/site.html">ADAMO DE PA</a><a href="http://darrenblackphotography.com/">X</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	JOELLE LITT<br />
	AT PLUTINO</p>
<p>
	<br />
	<br />
	HAIR &amp; MAKEUP<br />
	NINA FARRAUTO<br />
	AT PLUTINO</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	IRINA F<br />
	AT ELITE</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16665',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 2 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '533137',
        'status' => '1',
        'timestamp' => '1328909088',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '16667',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 3 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '171672',
        'status' => '1',
        'timestamp' => '1328909103',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '16669',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 4 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '115895',
        'status' => '1',
        'timestamp' => '1328909113',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '16671',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 5 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '327750',
        'status' => '1',
        'timestamp' => '1328909125',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '16673',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 6 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '427490',
        'status' => '1',
        'timestamp' => '1328909139',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '16675',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 7 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '437378',
        'status' => '1',
        'timestamp' => '1328909154',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '16677',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 8 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82193',
        'status' => '1',
        'timestamp' => '1328909170',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '16679',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 9 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '406665',
        'status' => '1',
        'timestamp' => '1328909183',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '16681',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 10 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '383763',
        'status' => '1',
        'timestamp' => '1328909197',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '16683',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 11 copy_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78914',
        'status' => '1',
        'timestamp' => '1328909206',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '16685',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 12 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '429405',
        'status' => '1',
        'timestamp' => '1328909221',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '16692',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout-1_Page-13_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '52182',
        'status' => '1',
        'timestamp' => '1328969351',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '16689',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 14 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98889',
        'status' => '1',
        'timestamp' => '1328909243',
        'origname' => 'Layout 1_Page 14 copy.jpg',
      ),
      '13' => array(
        'fid' => '16690',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 15 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '428086',
        'status' => '1',
        'timestamp' => '1328909253',
        'origname' => 'Layout 1_Page 15 copy.jpg',
      ),
    ),
    'path' => 'stories/fever-pitch',
    'tags' => array(
      '5' => array(
        '2665' => array(
          'tid' => '2665',
          'vid' => '5',
          'name' => 'ADAMO DE PAX',
          'description' => 'http://www.adamodepax.com/site/site.html',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ADAMO DE PAX',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
