array(
  array(
    'nid' => '3976',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1330458411',
    'changed' => '1403838945',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3976',
    'revision_uid' => '1',
    'title' => 'Earth and Sea',
    'body' => '<p>
	Nature inspires.<br />
	Exclusive photography by <a href="http://www.emasuvajac.com/">EMA SUVAJAC.</a><br />
	Model ~ Nicole S at Elite.</p>
',
    'teaser' => '<p>
	Nature inspires.<br />
	Exclusive photography by <a href="http://www.emasuvajac.com/">EMA SUVAJAC.</a><br />
	Model ~ Nicole S at Elite.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838945',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.emasuvajac.com/"> EMA SUVAJAC</a></p>
<p>
	<br />
	<br />
	MAKEUP &amp; CONCEPT<br />
	CARRIE TIBBS</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	NICOLE S<br />
	AT ELITE</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16889',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 2 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '181247',
        'status' => '1',
        'timestamp' => '1330458260',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '16891',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 3 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '862985',
        'status' => '1',
        'timestamp' => '1330458270',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '16892',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 4 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '372997',
        'status' => '1',
        'timestamp' => '1330458280',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '16893',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 5 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '497860',
        'status' => '1',
        'timestamp' => '1330458295',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '16895',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 6 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '652309',
        'status' => '1',
        'timestamp' => '1330458309',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '16897',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 7 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '760712',
        'status' => '1',
        'timestamp' => '1330458320',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '16899',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 8 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '531577',
        'status' => '1',
        'timestamp' => '1330458331',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '16901',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 9 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '538187',
        'status' => '1',
        'timestamp' => '1330458342',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '16903',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 10 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '415536',
        'status' => '1',
        'timestamp' => '1330458352',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '16904',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Feb/Layout 1_Page 11 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '597709',
        'status' => '1',
        'timestamp' => '1330458363',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
    ),
    'path' => 'stories/earth-and-sea',
    'tags' => array(
      '5' => array(
        '2672' => array(
          'tid' => '2672',
          'vid' => '5',
          'name' => ' EMA SUVAJAC',
          'description' => 'http://www.emasuvajac.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => ' EMA SUVAJAC',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
