array(
  array(
    'nid' => '3978',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1330611436',
    'changed' => '1403838945',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3978',
    'revision_uid' => '1',
    'title' => 'Pious Lie',
    'body' => '<p>
	Wedding bell blues.<br />
	Exclusive photography by <a href="http://www.seeboth-photo.de/">UTA SEELOS</a>.<br />
	Model ~ Nastassja at Eastwestmodels.</p>
',
    'teaser' => '<p>
	Wedding bell blues.<br />
	Exclusive photography by <a href="http://www.seeboth-photo.de/">UTA SEELOS</a>.<br />
	Model ~ Nastassja at Eastwestmodels.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838945',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.seeboth-photo.de/">UTA SEELOS</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	ALEXANDRA SOLOWSKI</p>
<p>
	<br />
	<br />
	MAKEUP &amp; HAIR<br />
	JULIA GOTZ</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	NASTASSJA<br />
	AT EASTWESTMODELS</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16906',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '425172',
        'status' => '1',
        'timestamp' => '1330611296',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '16907',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '140342',
        'status' => '1',
        'timestamp' => '1330611317',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '16909',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '451678',
        'status' => '1',
        'timestamp' => '1330611331',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '16910',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78892',
        'status' => '1',
        'timestamp' => '1330611342',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '16911',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '887662',
        'status' => '1',
        'timestamp' => '1330611361',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '16912',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '452785',
        'status' => '1',
        'timestamp' => '1330611379',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '6' => array(
        'fid' => '16913',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77256',
        'status' => '1',
        'timestamp' => '1330611395',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '7' => array(
        'fid' => '16925',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '489546',
        'status' => '1',
        'timestamp' => '1330612735',
        'origname' => 'Layout 1_Page 15 copy.jpg',
      ),
    ),
    'path' => 'stories/pious-lie',
    'tags' => array(
      '1' => array(
        '710' => array(
          'tid' => '710',
          'vid' => '1',
          'name' => 'alteza',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2673' => array(
          'tid' => '2673',
          'vid' => '5',
          'name' => 'UTA SEELOS',
          'description' => 'http://www.seeboth-photo.de/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'alteza',
        '5' => 'UTA SEELOS',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
