array(
  array(
    'nid' => '3982',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1331159359',
    'changed' => '1403838945',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3982',
    'revision_uid' => '1',
    'title' => 'Flair for the Dramatic',
    'body' => '<p>
	Dramatic looks.<br />
	Exclusive photography by <a href="http://heikehimmel.blogspot.com/">Heike Himmel</a>.<br />
	Model ~ Marianne Bittencourt at Karacter.</p>
',
    'teaser' => '<p>
	Dramatic looks.<br />
	Exclusive photography by <a href="http://heikehimmel.blogspot.com/">Heike Himmel</a>.<br />
	Model ~ Marianne Bittencourt at Karacter.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838945',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://heikehimmel.blogspot.com/">HEIKE HIMMEL</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	JO&Atilde;O DIOGO<br />
	FASHION SHOWER</p>
<p>
	<br />
	<br />
	HAIR<br />
	SANDRA RIBEIRO</p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	MALFADO BELO</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	MARIANNE BITTENCOURT<br />
	AT KARACTER</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16941',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '43255',
        'status' => '1',
        'timestamp' => '1330900018',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '16943',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101221',
        'status' => '1',
        'timestamp' => '1330900032',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '16945',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '181722',
        'status' => '1',
        'timestamp' => '1330900043',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '16947',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11378',
        'status' => '1',
        'timestamp' => '1330900051',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '16949',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13874',
        'status' => '1',
        'timestamp' => '1330900060',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '16951',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139234',
        'status' => '1',
        'timestamp' => '1330900070',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '16953',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12524',
        'status' => '1',
        'timestamp' => '1330900080',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '16955',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141223',
        'status' => '1',
        'timestamp' => '1330900090',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '16956',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '151012',
        'status' => '1',
        'timestamp' => '1330900099',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '16958',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14208',
        'status' => '1',
        'timestamp' => '1330900112',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '16960',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14355',
        'status' => '1',
        'timestamp' => '1330900121',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '16962',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '176938',
        'status' => '1',
        'timestamp' => '1330900131',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
      '12' => array(
        'fid' => '16963',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-14.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '162330',
        'status' => '1',
        'timestamp' => '1330900140',
        'origname' => 'Layout-1_Page-14.jpg',
      ),
      '13' => array(
        'fid' => '16964',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-15.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15826',
        'status' => '1',
        'timestamp' => '1330900150',
        'origname' => 'Layout-1_Page-15.jpg',
      ),
    ),
    'path' => 'stories/flair-dramatic-0',
    'tags' => array(
      '5' => array(
        '2659' => array(
          'tid' => '2659',
          'vid' => '5',
          'name' => 'HEIKE HIMMEL',
          'description' => 'http://heikehimmel.blogspot.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '715' => array(
          'tid' => '715',
          'vid' => '1',
          'name' => 'nine west',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '714' => array(
          'tid' => '714',
          'vid' => '1',
          'name' => 'storytailors',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '713' => array(
          'tid' => '713',
          'vid' => '1',
          'name' => 'triumph',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '712' => array(
          'tid' => '712',
          'vid' => '1',
          'name' => 'uterque',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '711' => array(
          'tid' => '711',
          'vid' => '1',
          'name' => 'vicente internacional',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'HEIKE HIMMEL',
        '1' => 'nine west, storytailors, triumph, uterque, vicente internacional',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
