array(
  array(
    'nid' => '3984',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1330903341',
    'changed' => '1403838945',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3984',
    'revision_uid' => '1',
    'title' => 'Flo Dron',
    'body' => '<p>
	So Flo.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.</p>
',
    'teaser' => '<p>
	So Flo.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838945',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://darrenblackphotography.com/">DARREN BLACK</a></p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	BELLA CRUIKSHANK</p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	NIKI BLACK</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16966',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-2_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '42206',
        'status' => '1',
        'timestamp' => '1330903265',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '16968',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-3_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73332',
        'status' => '1',
        'timestamp' => '1330903277',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '16970',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-4_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79285',
        'status' => '1',
        'timestamp' => '1330903286',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '16972',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-5_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92377',
        'status' => '1',
        'timestamp' => '1330903295',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '16974',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-6_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11377',
        'status' => '1',
        'timestamp' => '1330903306',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '16976',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-7_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75820',
        'status' => '1',
        'timestamp' => '1330903313',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '16978',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-8_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95449',
        'status' => '1',
        'timestamp' => '1330903322',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '16979',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-9_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61488',
        'status' => '1',
        'timestamp' => '1330903328',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
    ),
    'path' => 'stories/flo-dron',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
        '4' => 'women',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
