array(
  array(
    'nid' => '3987',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1330908379',
    'changed' => '1403838732',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3987',
    'revision_uid' => '1',
    'title' => 'Serie Noir',
    'body' => '<p>
	Look into the dark.<br />
	Exclusive photography by <a href="http://www.giorgiopescephotography.com/">Giorgio Pesce</a>.<br />
	Model ~ Nicol Marzio at Major Milan.</p>
',
    'teaser' => '<p>
	Look into the dark.<br />
	Exclusive photography by <a href="http://www.giorgiopescephotography.com/">Giorgio Pesce</a>.<br />
	Model ~ Nicol Marzio at Major Milan.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838732',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.giorgiopescephotography.com/">GIORGIO PESCE</a><br />
	AT PARIS AGENCY</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	VIKTOR ALEKSANDROVIC</p>
<p>
	<br />
	<br />
	HAIR &amp; MAKEUP<br />
	SARA PRIORI</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	NICOLA MARZIO<br />
	AT MAJOR MILAN</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '16982',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-2_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116616',
        'status' => '1',
        'timestamp' => '1330908227',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '17002',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-3_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '40133',
        'status' => '1',
        'timestamp' => '1330908409',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '17004',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-4_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '69055',
        'status' => '1',
        'timestamp' => '1330908418',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '17006',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18080',
        'status' => '1',
        'timestamp' => '1330908426',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '17008',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-6_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84909',
        'status' => '1',
        'timestamp' => '1330908435',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '17010',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-7_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80947',
        'status' => '1',
        'timestamp' => '1330908444',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '17012',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-8_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '94126',
        'status' => '1',
        'timestamp' => '1330908454',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '17014',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-9_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13129',
        'status' => '1',
        'timestamp' => '1330908464',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '17016',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-10_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61368',
        'status' => '1',
        'timestamp' => '1330908473',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '17018',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-11_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67027',
        'status' => '1',
        'timestamp' => '1330908484',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '17020',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-12_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14912',
        'status' => '1',
        'timestamp' => '1330908494',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '17021',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout-1_Page-13_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '121231',
        'status' => '1',
        'timestamp' => '1330908505',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/serie-noir',
    'tags' => array(
      '5' => array(
        '2675' => array(
          'tid' => '2675',
          'vid' => '5',
          'name' => 'GIORGIO PESCE',
          'description' => 'http://www.giorgiopescephotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'GIORGIO PESCE',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
