array(
  array(
    'nid' => '3991',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1331906666',
    'changed' => '1406008093',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3991',
    'revision_uid' => '1',
    'title' => 'Sun Day',
    'body' => '<p>
	Here it comes.<br />
	Exclusive photography by <a href="http://jsetiawan.com/">Jason Setiawan</a>.<br />
	Model ~ Valerie White at Elite.</p>
',
    'teaser' => '<p>
	Here it comes.<br />
	Exclusive photography by <a href="http://jsetiawan.com/">Jason Setiawan</a>.<br />
	Model ~ Valerie White at Elite.</p>
',
    'log' => '',
    'revision_timestamp' => '1406008093',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://jsetiawan.com/">JASON SETIAWAN</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	DARRYL GLOVER</p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	JUDI GABRAY</p>
<p>
	<br />
	<br />
	HAIR<br />
	JENNIFER MACDOUGALL</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	VALERIE WHITE<br />
	AT ELITE</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17046',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 2 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '660638',
        'status' => '1',
        'timestamp' => '1331128864',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '17047',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 3 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '765089',
        'status' => '1',
        'timestamp' => '1331128874',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '17048',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 4 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '619979',
        'status' => '1',
        'timestamp' => '1331128887',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '17050',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 5 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82115',
        'status' => '1',
        'timestamp' => '1331128898',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '17052',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 6 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93386',
        'status' => '1',
        'timestamp' => '1331128907',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '17054',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 7 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '565667',
        'status' => '1',
        'timestamp' => '1331128919',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '17056',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 8 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '945860',
        'status' => '1',
        'timestamp' => '1331128929',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '17058',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 9 copy_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102584',
        'status' => '1',
        'timestamp' => '1331128940',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '17059',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 10 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75240',
        'status' => '1',
        'timestamp' => '1331128957',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '17060',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 11 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '616070',
        'status' => '1',
        'timestamp' => '1331128974',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '17062',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 12 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '570472',
        'status' => '1',
        'timestamp' => '1331128988',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '17064',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 13 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '734202',
        'status' => '1',
        'timestamp' => '1331128997',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
      '12' => array(
        'fid' => '17066',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 14 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75240',
        'status' => '1',
        'timestamp' => '1331129006',
        'origname' => 'Layout 1_Page 14 copy.jpg',
      ),
      '13' => array(
        'fid' => '17068',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 15 copy_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '545213',
        'status' => '1',
        'timestamp' => '1331129016',
        'origname' => 'Layout 1_Page 15 copy.jpg',
      ),
      '14' => array(
        'fid' => '17070',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 16 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 16 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '606007',
        'status' => '1',
        'timestamp' => '1331129028',
        'origname' => 'Layout 1_Page 16 copy.jpg',
      ),
      '15' => array(
        'fid' => '17072',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 17 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 17 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85150',
        'status' => '1',
        'timestamp' => '1331129038',
        'origname' => 'Layout 1_Page 17 copy.jpg',
      ),
      '16' => array(
        'fid' => '17073',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 18 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 18 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85193',
        'status' => '1',
        'timestamp' => '1331129044',
        'origname' => 'Layout 1_Page 18 copy.jpg',
      ),
      '17' => array(
        'fid' => '17074',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 19 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 19 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '674231',
        'status' => '1',
        'timestamp' => '1331129058',
        'origname' => 'Layout 1_Page 19 copy.jpg',
      ),
    ),
    'path' => 'stories/sun-day',
    'tags' => array(
      '5' => array(
        '2676' => array(
          'tid' => '2676',
          'vid' => '5',
          'name' => 'JASON SETIAWAN',
          'description' => 'http://jsetiawan.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2135' => array(
          'tid' => '2135',
          'vid' => '4',
          'name' => 'skin',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2129' => array(
          'tid' => '2129',
          'vid' => '4',
          'name' => 'swimwear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JASON SETIAWAN',
        '4' => 'skin, swimwear, women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
