array(
  array(
    'nid' => '3995',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1332360561',
    'changed' => '1403838731',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '3995',
    'revision_uid' => '1',
    'title' => 'Boys Life',
    'body' => '<p>
	Look sharp young man.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.<br />
	Model ~ Barney Lee at Select.</p>
',
    'teaser' => '<p>
	Look sharp young man.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.<br />
	Model ~ Barney Lee at Select.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838731',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://darrenblackphotography.com/">DARREN BLACK</a></p>
<p>
	&nbsp;</p>
<p>
	ALL FASHION<br />
	AT <a href="http://www.harveynichols.com/">HARVEY NICHOLS</a></p>
<p>
	&nbsp;</p>
<p>
	CONCEPT<br />
	NEIL HOLBROOK</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	MICHAEL TEMPRANO</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	BARNEY LEE<br />
	AT SELECT</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17172',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 2 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '133344',
        'status' => '1',
        'timestamp' => '1331150784',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '17173',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 3 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '462347',
        'status' => '1',
        'timestamp' => '1331150794',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '17174',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 4 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91132',
        'status' => '1',
        'timestamp' => '1331150805',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '17175',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 5 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '339678',
        'status' => '1',
        'timestamp' => '1331150818',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '17176',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 6 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83447',
        'status' => '1',
        'timestamp' => '1331150830',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '17177',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 7 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '319890',
        'status' => '1',
        'timestamp' => '1331150860',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '17178',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 8 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '350372',
        'status' => '1',
        'timestamp' => '1331150891',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '17180',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 9 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75238',
        'status' => '1',
        'timestamp' => '1331150912',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '17182',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 10 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84856',
        'status' => '1',
        'timestamp' => '1331150922',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '17184',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 11 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '388136',
        'status' => '1',
        'timestamp' => '1331150931',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '17185',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 12 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80863',
        'status' => '1',
        'timestamp' => '1331150939',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '17186',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 13 copy_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '262122',
        'status' => '1',
        'timestamp' => '1331150951',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
    ),
    'path' => 'stories/boys-life',
    'tags' => array(
      '1' => array(
        '230' => array(
          'tid' => '230',
          'vid' => '1',
          'name' => 'ALEXANDER MCQUEEN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '566' => array(
          'tid' => '566',
          'vid' => '1',
          'name' => 'dsquared',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '372' => array(
          'tid' => '372',
          'vid' => '1',
          'name' => 'givenchy',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '417' => array(
          'tid' => '417',
          'vid' => '1',
          'name' => 'Harvey Nichols',
          'description' => 'www.harveynichols.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '716' => array(
          'tid' => '716',
          'vid' => '1',
          'name' => 'Pierre Balmain',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '541' => array(
          'tid' => '541',
          'vid' => '1',
          'name' => 'vivienne westwood',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'ALEXANDER MCQUEEN, dsquared, givenchy, Harvey Nichols, Pierre Balmain, vivienne westwood',
        '5' => 'Darren Black',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
