array(
  array(
    'nid' => '4004',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1332764465',
    'changed' => '1405544107',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4004',
    'revision_uid' => '1',
    'title' => 'Right Stuff',
    'body' => '<p>
	Right of way bud.<br />
	Exclusive photography by Lane Dorsey.<br />
	Model ~ Jordan Weller at Ford.</p>
',
    'teaser' => '<p>
	Right of way bud.<br />
	Exclusive photography by Lane Dorsey.<br />
	Model ~ Jordan Weller at Ford.</p>
',
    'log' => '',
    'revision_timestamp' => '1405544107',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	LANE DORSEY</p>
<p>
	&nbsp;</p>
<p>
	STYLING &amp; GROOMING<br />
	PAUL LANGILL</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	JORDAN WELLER<br />
	AT FORD</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17253',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 2 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '427016',
        'status' => '1',
        'timestamp' => '1332505102',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '17254',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 3 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '149425',
        'status' => '1',
        'timestamp' => '1332505114',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '17255',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 4 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '495472',
        'status' => '1',
        'timestamp' => '1332505125',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '17256',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 5 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '206075',
        'status' => '1',
        'timestamp' => '1332505139',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '17257',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 6 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75376',
        'status' => '1',
        'timestamp' => '1332505150',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '17258',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 7 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '373881',
        'status' => '1',
        'timestamp' => '1332505162',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '17259',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 8 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75238',
        'status' => '1',
        'timestamp' => '1332505174',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '17260',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 9 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '489922',
        'status' => '1',
        'timestamp' => '1332505193',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '17261',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 10 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '659205',
        'status' => '1',
        'timestamp' => '1332505209',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '17264',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 11 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75240',
        'status' => '1',
        'timestamp' => '1332505365',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '17262',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 12 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '869564',
        'status' => '1',
        'timestamp' => '1332505222',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '17263',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 13 copy_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '850185',
        'status' => '1',
        'timestamp' => '1332505242',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
    ),
    'path' => 'stories/right-stuff',
    'tags' => array(
      '4' => array(
        '2114' => array(
          'tid' => '2114',
          'vid' => '4',
          'name' => 'beards',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2679' => array(
          'tid' => '2679',
          'vid' => '5',
          'name' => 'LANE DORSEY',
          'description' => 'http://www.lanedorsey.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'beards, men',
        '5' => 'LANE DORSEY',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
