array(
  array(
    'nid' => '4006',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1332950991',
    'changed' => '1403838943',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4006',
    'revision_uid' => '1',
    'title' => 'Excellent',
    'body' => '<p>
	Top notch looks.<br />
	Exclusive photography by Ryan Wibawa.<br />
	Model ~ Ashley at Panache.</p>
',
    'teaser' => '<p>
	Top notch looks.<br />
	Exclusive photography by Ryan Wibawa.<br />
	Model ~ Ashley at Panache.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838943',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	RYAN WIBAWA</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	THAI TRAN</p>
<p>
	&nbsp;</p>
<p>
	MAKEUP BY<br />
	ANGIE ZACHARY</p>
<p>
	&nbsp;</p>
<p>
	HAIR BY<br />
	GUY LEMIEUX</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	ASHLEY<br />
	AT PANACHE</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17266',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 2 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130067',
        'status' => '1',
        'timestamp' => '1332518872',
        'origname' => 'Layout 1_Page 2 copy.jpg',
      ),
      '1' => array(
        'fid' => '17268',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 3 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '532105',
        'status' => '1',
        'timestamp' => '1332518884',
        'origname' => 'Layout 1_Page 3 copy.jpg',
      ),
      '2' => array(
        'fid' => '17270',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 4 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '556722',
        'status' => '1',
        'timestamp' => '1332518893',
        'origname' => 'Layout 1_Page 4 copy.jpg',
      ),
      '3' => array(
        'fid' => '17272',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 5 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '516282',
        'status' => '1',
        'timestamp' => '1332518901',
        'origname' => 'Layout 1_Page 5 copy.jpg',
      ),
      '4' => array(
        'fid' => '17273',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 6 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '318113',
        'status' => '1',
        'timestamp' => '1332518912',
        'origname' => 'Layout 1_Page 6 copy.jpg',
      ),
      '5' => array(
        'fid' => '17275',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 7 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '471754',
        'status' => '1',
        'timestamp' => '1332518925',
        'origname' => 'Layout 1_Page 7 copy.jpg',
      ),
      '6' => array(
        'fid' => '17277',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 8 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '516032',
        'status' => '1',
        'timestamp' => '1332518935',
        'origname' => 'Layout 1_Page 8 copy.jpg',
      ),
      '7' => array(
        'fid' => '17279',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 9 copy_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '536259',
        'status' => '1',
        'timestamp' => '1332518944',
        'origname' => 'Layout 1_Page 9 copy.jpg',
      ),
      '8' => array(
        'fid' => '17281',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 10 copy_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '443283',
        'status' => '1',
        'timestamp' => '1332518953',
        'origname' => 'Layout 1_Page 10 copy.jpg',
      ),
      '9' => array(
        'fid' => '17283',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 11 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '555922',
        'status' => '1',
        'timestamp' => '1332518963',
        'origname' => 'Layout 1_Page 11 copy.jpg',
      ),
      '10' => array(
        'fid' => '17285',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 12 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '534624',
        'status' => '1',
        'timestamp' => '1332518972',
        'origname' => 'Layout 1_Page 12 copy.jpg',
      ),
      '11' => array(
        'fid' => '17286',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout 1_Page 13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Mar/Layout 1_Page 13 copy_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '653457',
        'status' => '1',
        'timestamp' => '1332518981',
        'origname' => 'Layout 1_Page 13 copy.jpg',
      ),
    ),
    'path' => 'stories/excellent',
    'tags' => array(
      '5' => array(
        '2680' => array(
          'tid' => '2680',
          'vid' => '5',
          'name' => 'RYAN WIBAWA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'RYAN WIBAWA',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
