array(
  array(
    'nid' => '4008',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1333492031',
    'changed' => '1333571906',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4008',
    'revision_uid' => '1',
    'title' => 'Caution',
    'body' => '<p>
	Careful my dear.<br />
	Exclusive photography by <a href="http://www.matthewlyn.com/matthewlyn/Home.html">Matthew Lyn</a>.<br />
	Model ~ Stefanie at Spot 6.</p>
',
    'teaser' => '<p>
	Careful my dear.<br />
	Exclusive photography by <a href="http://www.matthewlyn.com/matthewlyn/Home.html">Matthew Lyn</a>.<br />
	Model ~ Stefanie at Spot 6.</p>
',
    'log' => '',
    'revision_timestamp' => '1333571906',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.matthewlyn.com/matthewlyn/Home.html">MATTHEW LYN</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	JOELLE LITT<br />
	AT JUDY INC</p>
<p>
	&nbsp;</p>
<p>
	HAIR &amp; MAKEUP<br />
	CHANTALE HUBENS<br />
	AT JUDY INC</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	STEFANIE<br />
	AT SPOT 6</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17289',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '33095',
        'status' => '1',
        'timestamp' => '1333491940',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '17304',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '251064',
        'status' => '1',
        'timestamp' => '1333571878',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '17293',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '177579',
        'status' => '1',
        'timestamp' => '1333491960',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '17305',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87749',
        'status' => '1',
        'timestamp' => '1333571900',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '17297',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '266732',
        'status' => '1',
        'timestamp' => '1333491981',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '17299',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '174658',
        'status' => '1',
        'timestamp' => '1333491991',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '17301',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '195858',
        'status' => '1',
        'timestamp' => '1333492002',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '17302',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '173299',
        'status' => '1',
        'timestamp' => '1333492011',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
    ),
    'path' => 'stories/caution',
    'tags' => array(
      '5' => array(
        '2413' => array(
          'tid' => '2413',
          'vid' => '5',
          'name' => 'Matthew Lyn',
          'description' => 'http://www.matthewlyn.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Matthew Lyn',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
