array(
  array(
    'nid' => '4014',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1333942178',
    'changed' => '1406008214',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4014',
    'revision_uid' => '1',
    'title' => 'Under Fire',
    'body' => '<p>
	It&#39;s hot under there.<br />
	Exclusive photography by <a href="http://www.photodesign-wolf.com/">Matthias Wolf</a>.<br />
	Model ~ Kristina M&ouml;ller at M4.</p>
',
    'teaser' => '<p>
	It&#39;s hot under there.<br />
	Exclusive photography by <a href="http://www.photodesign-wolf.com/">Matthias Wolf</a>.<br />
	Model ~ Kristina M&ouml;ller at M4.</p>
',
    'log' => '',
    'revision_timestamp' => '1406008214',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.photodesign-wolf.com/">MATTHIAS WOLF</a><br />
	REPRESENTATION<br />
	PAM.HAMBURG</p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	<a href="http://www.andreakadler.de/">ANDREA KADLER</a></p>
<p>
	&nbsp;</p>
<p>
	HAIR &amp; MAKEUP<br />
	CAROLINE WOLF<br />
	PRODUCT<br />
	BY CHANEL</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	KRISTIN M&Ouml;LLER<br />
	AT M4</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17357',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-2_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86895',
        'status' => '1',
        'timestamp' => '1333942081',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '17359',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-3_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '41333',
        'status' => '1',
        'timestamp' => '1333942092',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '17361',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-4_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '23234',
        'status' => '1',
        'timestamp' => '1333942101',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '17363',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-5_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68064',
        'status' => '1',
        'timestamp' => '1333942109',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '17365',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-6_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100535',
        'status' => '1',
        'timestamp' => '1333942124',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '17367',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-7_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61623',
        'status' => '1',
        'timestamp' => '1333942131',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '17369',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-8_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '28326',
        'status' => '1',
        'timestamp' => '1333942139',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '17371',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-9_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '64216',
        'status' => '1',
        'timestamp' => '1333942150',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '17373',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-10_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15907',
        'status' => '1',
        'timestamp' => '1333942160',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '17375',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-11_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93518',
        'status' => '1',
        'timestamp' => '1333942170',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
    ),
    'path' => 'stories/under-fire',
    'tags' => array(
      '4' => array(
        '2137' => array(
          'tid' => '2137',
          'vid' => '4',
          'name' => 'lingerie',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2681' => array(
          'tid' => '2681',
          'vid' => '5',
          'name' => 'MATTHIAS WOLF',
          'description' => 'http://www.photodesign-wolf.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'lingerie, women',
        '5' => 'MATTHIAS WOLF',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
