array(
  array(
    'nid' => '4016',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1334527578',
    'changed' => '1403838943',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4016',
    'revision_uid' => '1',
    'title' => 'Genesis',
    'body' => '<p>
	Gee it&#39;s Genesis.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.</p>
',
    'teaser' => '<p>
	Gee it&#39;s Genesis.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838943',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://darrenblackphotography.com/">DARREN BLACK</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	OLIVER VAUGHN</p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	NIKI BLACK</p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	JEMMA HARWOOD</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17378',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-2.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-2_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79621',
        'status' => '1',
        'timestamp' => '1334527412',
        'origname' => 'Layout-1_Page-2.jpg',
      ),
      '1' => array(
        'fid' => '17380',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-3.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-3_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104298',
        'status' => '1',
        'timestamp' => '1334527425',
        'origname' => 'Layout-1_Page-3.jpg',
      ),
      '2' => array(
        'fid' => '17382',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-4.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-4_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11378',
        'status' => '1',
        'timestamp' => '1334527439',
        'origname' => 'Layout-1_Page-4.jpg',
      ),
      '3' => array(
        'fid' => '17384',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-5.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-5_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131605',
        'status' => '1',
        'timestamp' => '1334527449',
        'origname' => 'Layout-1_Page-5.jpg',
      ),
      '4' => array(
        'fid' => '17386',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-6.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-6_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100024',
        'status' => '1',
        'timestamp' => '1334527461',
        'origname' => 'Layout-1_Page-6.jpg',
      ),
      '5' => array(
        'fid' => '17388',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-7.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-7_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101784',
        'status' => '1',
        'timestamp' => '1334527470',
        'origname' => 'Layout-1_Page-7.jpg',
      ),
      '6' => array(
        'fid' => '17390',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-8.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-8_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '99418',
        'status' => '1',
        'timestamp' => '1334527480',
        'origname' => 'Layout-1_Page-8.jpg',
      ),
      '7' => array(
        'fid' => '17392',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-9.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-9_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75866',
        'status' => '1',
        'timestamp' => '1334527491',
        'origname' => 'Layout-1_Page-9.jpg',
      ),
      '8' => array(
        'fid' => '17394',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-10.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-10_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128675',
        'status' => '1',
        'timestamp' => '1334527503',
        'origname' => 'Layout-1_Page-10.jpg',
      ),
      '9' => array(
        'fid' => '17396',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-11.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-11_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67783',
        'status' => '1',
        'timestamp' => '1334527513',
        'origname' => 'Layout-1_Page-11.jpg',
      ),
      '10' => array(
        'fid' => '17398',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-12.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-12_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '47488',
        'status' => '1',
        'timestamp' => '1334527523',
        'origname' => 'Layout-1_Page-12.jpg',
      ),
      '11' => array(
        'fid' => '17399',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Layout-1_Page-13.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/Layout-1_Page-13_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '199040',
        'status' => '1',
        'timestamp' => '1334527533',
        'origname' => 'Layout-1_Page-13.jpg',
      ),
    ),
    'path' => 'stories/genesis',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
        '4' => 'women',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
