array(
  array(
    'nid' => '4028',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1335206255',
    'changed' => '1403838943',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4028',
    'revision_uid' => '1',
    'title' => 'Bohemian Rhapsody',
    'body' => '<p>
	Boho girl.<br />
	Exclusive photography by <a href="http://www.iremharnak.com/">Irem Harnak</a>.<br />
	Model - Ana Kurylo at Sutherland</p>
',
    'teaser' => '<p>
	Boho girl.<br />
	Exclusive photography by <a href="http://www.iremharnak.com/">Irem Harnak</a>.<br />
	Model - Ana Kurylo at Sutherland</p>
',
    'log' => '',
    'revision_timestamp' => '1403838943',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.iremharnak.com/">IREM HARNAK</a><br />
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	CHARLOTTE CARSON<br />
	AT JUDY INC</p>
<p>
	<br />
	<br />
	MAKEUP &amp; HAIR<br />
	GIANLUCA ORIENTI<br />
	AT JUDY INC<br />
	&nbsp;</p>
<p>
	MODEL<br />
	ANA KURYLO<br />
	AT SUTHERLAND</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17572',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_2.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '55554',
        'status' => '1',
        'timestamp' => '1335119631',
        'origname' => 'BOHEMIAN-RHAPSODY_2.jpg',
      ),
      '1' => array(
        'fid' => '17596',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_3.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '286620',
        'status' => '1',
        'timestamp' => '1335120595',
        'origname' => 'BOHEMIAN-RHAPSODY_3.jpg',
      ),
      '2' => array(
        'fid' => '17597',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_4.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1335120604',
        'origname' => 'BOHEMIAN-RHAPSODY_4.jpg',
      ),
      '3' => array(
        'fid' => '17598',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_5.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '205853',
        'status' => '1',
        'timestamp' => '1335120616',
        'origname' => 'BOHEMIAN-RHAPSODY_5.jpg',
      ),
      '4' => array(
        'fid' => '17580',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_6.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137979',
        'status' => '1',
        'timestamp' => '1335119689',
        'origname' => 'BOHEMIAN-RHAPSODY_6.jpg',
      ),
      '5' => array(
        'fid' => '17582',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_7.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '112618',
        'status' => '1',
        'timestamp' => '1335119702',
        'origname' => 'BOHEMIAN-RHAPSODY_7.jpg',
      ),
      '6' => array(
        'fid' => '17584',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_8.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15641',
        'status' => '1',
        'timestamp' => '1335119714',
        'origname' => 'BOHEMIAN-RHAPSODY_8.jpg',
      ),
      '7' => array(
        'fid' => '17586',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_9.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '232104',
        'status' => '1',
        'timestamp' => '1335119777',
        'origname' => 'BOHEMIAN-RHAPSODY_9.jpg',
      ),
      '8' => array(
        'fid' => '17585',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_10.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1335119724',
        'origname' => 'BOHEMIAN-RHAPSODY_10.jpg',
      ),
      '9' => array(
        'fid' => '17587',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_11.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '261207',
        'status' => '1',
        'timestamp' => '1335119797',
        'origname' => 'BOHEMIAN-RHAPSODY_11.jpg',
      ),
      '10' => array(
        'fid' => '17589',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_12.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '197689',
        'status' => '1',
        'timestamp' => '1335119814',
        'origname' => 'BOHEMIAN-RHAPSODY_12.jpg',
      ),
      '11' => array(
        'fid' => '17591',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_13.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '272684',
        'status' => '1',
        'timestamp' => '1335119827',
        'origname' => 'BOHEMIAN-RHAPSODY_13.jpg',
      ),
      '12' => array(
        'fid' => '17593',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_14.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139175',
        'status' => '1',
        'timestamp' => '1335119838',
        'origname' => 'BOHEMIAN-RHAPSODY_14.jpg',
      ),
      '13' => array(
        'fid' => '17594',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BOHEMIAN-RHAPSODY_15.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/BOHEMIAN-RHAPSODY_15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '159279',
        'status' => '1',
        'timestamp' => '1335119847',
        'origname' => 'BOHEMIAN-RHAPSODY_15.jpg',
      ),
    ),
    'path' => 'stories/bohemian-rhapsody-0',
    'tags' => array(
      '1' => array(
        '557' => array(
          'tid' => '557',
          'vid' => '1',
          'name' => 'DIANE VON FURSTENBERG',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '89' => array(
          'tid' => '89',
          'vid' => '1',
          'name' => 'DIESEL',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2574' => array(
          'tid' => '2574',
          'vid' => '5',
          'name' => 'Irem Harnak',
          'description' => 'http://www.iremharnak.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'DIANE VON FURSTENBERG, DIESEL',
        '5' => 'Irem Harnak',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
