array(
  array(
    'nid' => '4032',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1335548849',
    'changed' => '1403838942',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4032',
    'revision_uid' => '1',
    'title' => 'Femme Fatale',
    'body' => '<p>
	Bad girl looks good.<br />
	Exclusive photography by Darren Black.<br />
	Model - Kathleen B at Premier.</p>
',
    'teaser' => '<p>
	Bad girl looks good.<br />
	Exclusive photography by Darren Black.<br />
	Model - Kathleen B at Premier.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838942',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	DARREN BLACK<br />
	&nbsp;</p>
<p>
	CONCEPT<br />
	NEIL HOLBROOK</p>
<p>
	&nbsp;</p>
<p>
	ALL AT<br />
	<a href="http://www.harveynichols.com/">HARVEY NICHOLS</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	MICHAEL TEMPRANO</p>
<p>
	<br />
	<br />
	HAIR<br />
	NIKI BLACK</p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	NATASHA LAWES<br />
	<br />
	<br />
	&nbsp;</p>
<p>
	MODEL<br />
	KATHLEEN B<br />
	AT PREMIER</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17627',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '872144',
        'status' => '1',
        'timestamp' => '1335375778',
        'origname' => 'FemmeFatale_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '17628',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '960487',
        'status' => '1',
        'timestamp' => '1335375795',
        'origname' => 'FemmeFatale_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '17629',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '870676',
        'status' => '1',
        'timestamp' => '1335375814',
        'origname' => 'FemmeFatale_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '17667',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93019',
        'status' => '1',
        'timestamp' => '1335384340',
        'origname' => 'FemmeFatale_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '17632',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74934',
        'status' => '1',
        'timestamp' => '1335375840',
        'origname' => 'FemmeFatale_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '17658',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '890762',
        'status' => '1',
        'timestamp' => '1335383817',
        'origname' => 'FemmeFatale_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '17635',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '964915',
        'status' => '1',
        'timestamp' => '1335375872',
        'origname' => 'FemmeFatale_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '17657',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86374',
        'status' => '1',
        'timestamp' => '1335383584',
        'origname' => 'FemmeFatale_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '17639',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74930',
        'status' => '1',
        'timestamp' => '1335375899',
        'origname' => 'FemmeFatale_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '17659',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '799194',
        'status' => '1',
        'timestamp' => '1335383844',
        'origname' => 'FemmeFatale_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '17643',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '606196',
        'status' => '1',
        'timestamp' => '1335375926',
        'origname' => 'FemmeFatale_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '17668',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '911737',
        'status' => '1',
        'timestamp' => '1335384359',
        'origname' => 'FemmeFatale_13 copy.jpg',
      ),
      '12' => array(
        'fid' => '17661',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '845843',
        'status' => '1',
        'timestamp' => '1335383884',
        'origname' => 'FemmeFatale_14 copy.jpg',
      ),
      '13' => array(
        'fid' => '17662',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1063583',
        'status' => '1',
        'timestamp' => '1335383902',
        'origname' => 'FemmeFatale_15 copy.jpg',
      ),
      '14' => array(
        'fid' => '17663',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_16 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_16 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '871441',
        'status' => '1',
        'timestamp' => '1335383920',
        'origname' => 'FemmeFatale_16 copy.jpg',
      ),
      '15' => array(
        'fid' => '17651',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_17 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_17 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '993005',
        'status' => '1',
        'timestamp' => '1335376017',
        'origname' => 'FemmeFatale_17 copy.jpg',
      ),
      '16' => array(
        'fid' => '17653',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_18 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_18 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74936',
        'status' => '1',
        'timestamp' => '1335376028',
        'origname' => 'FemmeFatale_18 copy.jpg',
      ),
      '17' => array(
        'fid' => '17664',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FemmeFatale_19 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/FemmeFatale_19 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '841525',
        'status' => '1',
        'timestamp' => '1335383944',
        'origname' => 'FemmeFatale_19 copy.jpg',
      ),
    ),
    'path' => 'stories/femme-fatale',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
