array(
  array(
    'nid' => '4034',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1335793623',
    'changed' => '1403838730',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4034',
    'revision_uid' => '1',
    'title' => 'The Knack',
    'body' => '<p>
	He&#39;s got a flair for fashion.<br />
	Exclusive photography by <span style="text-decoration: underline;">Jessica Pechet</span>.<br />
	Model - Bailey at I Model.</p>
',
    'teaser' => '<p>
	He&#39;s got a flair for fashion.<br />
	Exclusive photography by <span style="text-decoration: underline;">Jessica Pechet</span>.<br />
	Model - Bailey at I Model.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838730',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	JESSICA PECHET<br />
	&nbsp;</p>
<p>
	STYLING<br />
	JENNIFER LYLE</p>
<p>
	<br />
	<br />
	GROOMING<br />
	KIM AT<br />
	THE ARTIST GROUP<br />
	&nbsp;</p>
<p>
	MODEL<br />
	BAILEY AT<br />
	I MODEL</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17669',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '185973',
        'status' => '1',
        'timestamp' => '1335448073',
        'origname' => 'TheKnack_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '17671',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '462104',
        'status' => '1',
        'timestamp' => '1335448095',
        'origname' => 'TheKnack_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '17673',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '744854',
        'status' => '1',
        'timestamp' => '1335448112',
        'origname' => 'TheKnack_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '17674',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88540',
        'status' => '1',
        'timestamp' => '1335448121',
        'origname' => 'TheKnack_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '17676',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96154',
        'status' => '1',
        'timestamp' => '1335448137',
        'origname' => 'TheKnack_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '17678',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '428770',
        'status' => '1',
        'timestamp' => '1335448148',
        'origname' => 'TheKnack_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '17696',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101093',
        'status' => '1',
        'timestamp' => '1335448320',
        'origname' => 'TheKnack_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '17680',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '381520',
        'status' => '1',
        'timestamp' => '1335448158',
        'origname' => 'TheKnack_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '17682',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '910147',
        'status' => '1',
        'timestamp' => '1335448167',
        'origname' => 'TheKnack_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '17684',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102886',
        'status' => '1',
        'timestamp' => '1335448176',
        'origname' => 'TheKnack_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '17686',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91157',
        'status' => '1',
        'timestamp' => '1335448185',
        'origname' => 'TheKnack_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '17688',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '513149',
        'status' => '1',
        'timestamp' => '1335448195',
        'origname' => 'TheKnack_13 copy.jpg',
      ),
      '12' => array(
        'fid' => '17690',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '395464',
        'status' => '1',
        'timestamp' => '1335448205',
        'origname' => 'TheKnack_14 copy.jpg',
      ),
      '13' => array(
        'fid' => '17692',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87255',
        'status' => '1',
        'timestamp' => '1335448217',
        'origname' => 'TheKnack_15 copy.jpg',
      ),
      '14' => array(
        'fid' => '17694',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_16 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_16 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104158',
        'status' => '1',
        'timestamp' => '1335448226',
        'origname' => 'TheKnack_16 copy.jpg',
      ),
      '15' => array(
        'fid' => '17695',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TheKnack_17 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/TheKnack_17 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '891286',
        'status' => '1',
        'timestamp' => '1335448236',
        'origname' => 'TheKnack_17 copy.jpg',
      ),
    ),
    'path' => 'stories/knack',
    'tags' => array(
      '5' => array(
        '2684' => array(
          'tid' => '2684',
          'vid' => '5',
          'name' => 'JESSICA PECHET',
          'description' => 'http://jessica-pechet.com/?',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JESSICA PECHET',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
