array(
  array(
    'nid' => '4036',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1334242916',
    'changed' => '1403838943',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4036',
    'revision_uid' => '1',
    'title' => 'Temperate',
    'body' => '<p>
	Moderate modern.<br />
	Exclusive photography by <a href="http://joshmcgeephotography.com/">Josh McGee</a>.<br />
	Models ~ Sam Frost at Viviens.</p>
',
    'teaser' => '<p>
	Moderate modern.<br />
	Exclusive photography by <a href="http://joshmcgeephotography.com/">Josh McGee</a>.<br />
	Models ~ Sam Frost at Viviens.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838943',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://joshmcgeephotography.com/">JOSH MCGEE</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	SAM FROST<br />
	AT VIVIENS</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17700',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/temperate_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '625888',
        'status' => '1',
        'timestamp' => '1335452421',
        'origname' => 'temperate_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '17702',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/temperate_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '588106',
        'status' => '1',
        'timestamp' => '1335452430',
        'origname' => 'temperate_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '17704',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/temperate_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '231424',
        'status' => '1',
        'timestamp' => '1335452440',
        'origname' => 'temperate_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '17706',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/temperate_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '546121',
        'status' => '1',
        'timestamp' => '1335452447',
        'origname' => 'temperate_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '17708',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/temperate_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '649396',
        'status' => '1',
        'timestamp' => '1335452455',
        'origname' => 'temperate_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '17710',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/temperate_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74930',
        'status' => '1',
        'timestamp' => '1335452463',
        'origname' => 'temperate_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '17712',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/temperate_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84451',
        'status' => '1',
        'timestamp' => '1335452470',
        'origname' => 'temperate_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '17714',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/temperate_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '669591',
        'status' => '1',
        'timestamp' => '1335452478',
        'origname' => 'temperate_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '17751',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/temperate_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81247',
        'status' => '1',
        'timestamp' => '1336659504',
        'origname' => 'temperate_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '17752',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/temperate_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '580170',
        'status' => '1',
        'timestamp' => '1336659516',
        'origname' => 'temperate_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '17720',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/temperate_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '506308',
        'status' => '1',
        'timestamp' => '1335452504',
        'origname' => 'temperate_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '17721',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'temperate_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Apr/temperate_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84000',
        'status' => '1',
        'timestamp' => '1335452510',
        'origname' => 'temperate_13 copy.jpg',
      ),
    ),
    'path' => 'stories/temperate',
    'tags' => array(
      '5' => array(
        '2677' => array(
          'tid' => '2677',
          'vid' => '5',
          'name' => 'JOSH MCGEE',
          'description' => 'http://joshmcgeephotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JOSH MCGEE',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
