array(
  array(
    'nid' => '4040',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1336660981',
    'changed' => '1403838942',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4040',
    'revision_uid' => '1',
    'title' => 'London Calling',
    'body' => '<p>
	English accents.<br />
	Exclusive photography by Lyall Aston.<br />
	Models - Agatha &amp; Tim at MC2, Brandon at Front, Ariane &amp; Bruna at Mega.</p>
',
    'teaser' => '<p>
	English accents.<br />
	Exclusive photography by Lyall Aston.<br />
	Models - Agatha &amp; Tim at MC2, Brandon at Front, Ariane &amp; Bruna at Mega.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838942',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	LYALL ASTON<br />
	AT<a href="http://www.artistsbytimothypriano.com/fashion/lyall-aston"><br />
	ARTISTS<br />
	BY TIMOTHY PRIANO</a><br />
	&nbsp;</p>
<p>
	STYLING<br />
	LINA RODRIGUEZ<br />
	AT AGENCY GERARD</p>
<p>
	<br />
	<br />
	MAKEUP<br />
	NANCY CIADELLA<br />
	AT AGENCY GERARD<br />
	&nbsp;</p>
<p>
	<br />
	HAIR<br />
	CASEY GEREN<br />
	AT<br />
	ARTISTS<br />
	BY TIMOTHY PRIANO</p>
<p>
	&nbsp;</p>
<p>
	NAIL STYLIST<br />
	<a href="http://www.marysoul.com/">MAR Y SOUL INZERILLO FOR ESSIE</a></p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	AGATHA &amp; TIM<br />
	AT MC2<br />
	BRANDON<br />
	FRONT<br />
	ARIANE &amp; BRUNA<br />
	AT MEGA</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17805',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCallingpage copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCallingpage copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '849775',
        'status' => '1',
        'timestamp' => '1336668954',
        'origname' => 'LondonCallingpage copy.jpg',
      ),
      '1' => array(
        'fid' => '17756',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '953567',
        'status' => '1',
        'timestamp' => '1336660930',
        'origname' => 'LondonCalling_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '17758',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '559552',
        'status' => '1',
        'timestamp' => '1336660940',
        'origname' => 'LondonCalling_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '17759',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '577867',
        'status' => '1',
        'timestamp' => '1336660949',
        'origname' => 'LondonCalling_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '17804',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1086164',
        'status' => '1',
        'timestamp' => '1336668575',
        'origname' => 'LondonCalling copy.jpg',
      ),
      '5' => array(
        'fid' => '17761',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1070491',
        'status' => '1',
        'timestamp' => '1336660974',
        'origname' => 'LondonCalling_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '17763',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '759081',
        'status' => '1',
        'timestamp' => '1336666088',
        'origname' => 'LondonCalling_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '17765',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90658',
        'status' => '1',
        'timestamp' => '1336666099',
        'origname' => 'LondonCalling_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '17767',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '946606',
        'status' => '1',
        'timestamp' => '1336666109',
        'origname' => 'LondonCalling_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '17769',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '846848',
        'status' => '1',
        'timestamp' => '1336666117',
        'origname' => 'LondonCalling_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '17771',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '106268',
        'status' => '1',
        'timestamp' => '1336666125',
        'origname' => 'LondonCalling_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '17773',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1122551',
        'status' => '1',
        'timestamp' => '1336666136',
        'origname' => 'LondonCalling_13 copy.jpg',
      ),
      '12' => array(
        'fid' => '17775',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '966415',
        'status' => '1',
        'timestamp' => '1336666148',
        'origname' => 'LondonCalling_14 copy.jpg',
      ),
      '13' => array(
        'fid' => '17777',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1038522',
        'status' => '1',
        'timestamp' => '1336666156',
        'origname' => 'LondonCalling_15 copy.jpg',
      ),
      '14' => array(
        'fid' => '17779',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_16 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_16 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '119207',
        'status' => '1',
        'timestamp' => '1336666164',
        'origname' => 'LondonCalling_16 copy.jpg',
      ),
      '15' => array(
        'fid' => '17781',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_17 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_17 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '918629',
        'status' => '1',
        'timestamp' => '1336666172',
        'origname' => 'LondonCalling_17 copy.jpg',
      ),
      '16' => array(
        'fid' => '17798',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_18 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_18 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '947396',
        'status' => '1',
        'timestamp' => '1336667571',
        'origname' => 'LondonCalling_18 copy.jpg',
      ),
      '17' => array(
        'fid' => '17799',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_19 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_19 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '733403',
        'status' => '1',
        'timestamp' => '1336667580',
        'origname' => 'LondonCalling_19 copy.jpg',
      ),
      '18' => array(
        'fid' => '17790',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_22 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_22 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107080',
        'status' => '1',
        'timestamp' => '1336666217',
        'origname' => 'LondonCalling_22 copy.jpg',
      ),
      '19' => array(
        'fid' => '17792',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_23 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_23 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '914209',
        'status' => '1',
        'timestamp' => '1336666226',
        'origname' => 'LondonCalling_23 copy.jpg',
      ),
      '20' => array(
        'fid' => '17800',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_22 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_22 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '985099',
        'status' => '1',
        'timestamp' => '1336667610',
        'origname' => 'LondonCalling_22 copy.jpg',
      ),
      '21' => array(
        'fid' => '17801',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_23 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_23 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '870837',
        'status' => '1',
        'timestamp' => '1336667624',
        'origname' => 'LondonCalling_23 copy.jpg',
      ),
      '22' => array(
        'fid' => '17802',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_24 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_24 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1083846',
        'status' => '1',
        'timestamp' => '1336667642',
        'origname' => 'LondonCalling_24 copy.jpg',
      ),
      '23' => array(
        'fid' => '17803',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'LondonCalling_25 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/LondonCalling_25 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1026687',
        'status' => '1',
        'timestamp' => '1336667657',
        'origname' => 'LondonCalling_25 copy.jpg',
      ),
    ),
    'path' => 'stories/london-calling',
    'tags' => array(
      '5' => array(
        '2447' => array(
          'tid' => '2447',
          'vid' => '5',
          'name' => 'LYALL ASTON',
          'description' => 'http://www.LyallAstonPhoto.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'LYALL ASTON',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
