array(
  array(
    'nid' => '4049',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1337456171',
    'changed' => '1403838941',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4049',
    'revision_uid' => '1',
    'title' => 'Sequentia',
    'body' => '<p>
	Get ordered.<br />
	Exclusive photography by <a href="http://wesleystringer.com/">WESLEY STRINGER</a>.<br />
	Models - Jessica Roffey at One.1 and Isabeau at New York Models.</p>
',
    'teaser' => '<p>
	Get ordered.<br />
	Exclusive photography by <a href="http://wesleystringer.com/">WESLEY STRINGER</a>.<br />
	Models - Jessica Roffey at One.1 and Isabeau at New York Models.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838941',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://wesleystringer.com/">WESLEY STRINGER</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	<a href="http://www.andrewzumbo.com/">ANDREW ZUMBO</a><br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	<a href="http://www.maricomakeup.com/">MARICO HIRANO</a></p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	FRANKIE</p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	JESSICA ROFFEY<br />
	AT ONE.1<br />
	ISABEAU<br />
	AT NEW YORK MODELS</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17947',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_2.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '62022',
        'status' => '1',
        'timestamp' => '1337456539',
        'origname' => 'squentia_2.jpg',
      ),
      '1' => array(
        'fid' => '17948',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_3.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90422',
        'status' => '1',
        'timestamp' => '1337456546',
        'origname' => 'squentia_3.jpg',
      ),
      '2' => array(
        'fid' => '17949',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_4.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '192180',
        'status' => '1',
        'timestamp' => '1337456554',
        'origname' => 'squentia_4.jpg',
      ),
      '3' => array(
        'fid' => '17950',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_5.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131735',
        'status' => '1',
        'timestamp' => '1337456560',
        'origname' => 'squentia_5.jpg',
      ),
      '4' => array(
        'fid' => '17951',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_6.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82086',
        'status' => '1',
        'timestamp' => '1337456566',
        'origname' => 'squentia_6.jpg',
      ),
      '5' => array(
        'fid' => '17952',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_7.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15981',
        'status' => '1',
        'timestamp' => '1337456572',
        'origname' => 'squentia_7.jpg',
      ),
      '6' => array(
        'fid' => '17953',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_8.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90982',
        'status' => '1',
        'timestamp' => '1337456582',
        'origname' => 'squentia_8.jpg',
      ),
      '7' => array(
        'fid' => '17954',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_9.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '83165',
        'status' => '1',
        'timestamp' => '1337456592',
        'origname' => 'squentia_9.jpg',
      ),
      '8' => array(
        'fid' => '17955',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_10.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '135491',
        'status' => '1',
        'timestamp' => '1337456603',
        'origname' => 'squentia_10.jpg',
      ),
      '9' => array(
        'fid' => '17956',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_11.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86037',
        'status' => '1',
        'timestamp' => '1337456612',
        'origname' => 'squentia_11.jpg',
      ),
      '10' => array(
        'fid' => '17957',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_12.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '111221',
        'status' => '1',
        'timestamp' => '1337456627',
        'origname' => 'squentia_12.jpg',
      ),
      '11' => array(
        'fid' => '17958',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_13.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '142146',
        'status' => '1',
        'timestamp' => '1337456644',
        'origname' => 'squentia_13.jpg',
      ),
      '12' => array(
        'fid' => '17959',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_14.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61335',
        'status' => '1',
        'timestamp' => '1337456656',
        'origname' => 'squentia_14.jpg',
      ),
      '13' => array(
        'fid' => '17960',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_15.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '122610',
        'status' => '1',
        'timestamp' => '1337456664',
        'origname' => 'squentia_15.jpg',
      ),
      '14' => array(
        'fid' => '17961',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_16.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19349',
        'status' => '1',
        'timestamp' => '1337456674',
        'origname' => 'squentia_16.jpg',
      ),
      '15' => array(
        'fid' => '17962',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'squentia_17.jpg',
        'filepath' => 'files/fmag_story/2012/May/squentia_17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87323',
        'status' => '1',
        'timestamp' => '1337456684',
        'origname' => 'squentia_17.jpg',
      ),
    ),
    'path' => 'stories/sequentia',
    'tags' => array(
      '5' => array(
        '2686' => array(
          'tid' => '2686',
          'vid' => '5',
          'name' => 'WESLEY STRINGER',
          'description' => 'http://wesleystringer.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '1' => '1',
      ),
      'tags' => array(
        '5' => 'WESLEY STRINGER',
        '4' => 'women',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
