array(
  array(
    'nid' => '4051',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1337616655',
    'changed' => '1403838729',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4051',
    'revision_uid' => '1',
    'title' => 'The Thine White Line',
    'body' => '<p>
	Walk the line.<br />
	Exclusive photography by <a href="http://www.harenmehta.com/">Haren Mehta</a>.<br />
	Model - Jay Holanda at Look.</p>
',
    'teaser' => '<p>
	Walk the line.<br />
	Exclusive photography by <a href="http://www.harenmehta.com/">Haren Mehta</a>.<br />
	Model - Jay Holanda at Look.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838729',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.harenmehta.com/">HAREN MEHTA</a></p>
<p>
	&nbsp;</p>
<p>
	STYLIST<br />
	LAURA ANNE HOLLABAUGH<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	HAIR &amp; MAKEUP<br />
	PRESTON NESBIT</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	JAY HOLANDA<br />
	AT LOOK</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17964',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_2.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '40277',
        'status' => '1',
        'timestamp' => '1337616531',
        'origname' => 'ThinWhiteLine_2.jpg',
      ),
      '1' => array(
        'fid' => '17967',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_3.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '27941',
        'status' => '1',
        'timestamp' => '1337616539',
        'origname' => 'ThinWhiteLine_3.jpg',
      ),
      '2' => array(
        'fid' => '17969',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_4.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '53241',
        'status' => '1',
        'timestamp' => '1337616548',
        'origname' => 'ThinWhiteLine_4.jpg',
      ),
      '3' => array(
        'fid' => '17971',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_5.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17709',
        'status' => '1',
        'timestamp' => '1337616556',
        'origname' => 'ThinWhiteLine_5.jpg',
      ),
      '4' => array(
        'fid' => '17973',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_6.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101890',
        'status' => '1',
        'timestamp' => '1337616570',
        'origname' => 'ThinWhiteLine_6.jpg',
      ),
      '5' => array(
        'fid' => '17975',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_7.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '95759',
        'status' => '1',
        'timestamp' => '1337616578',
        'origname' => 'ThinWhiteLine_7.jpg',
      ),
      '6' => array(
        'fid' => '17977',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_8.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '27352',
        'status' => '1',
        'timestamp' => '1337616586',
        'origname' => 'ThinWhiteLine_8.jpg',
      ),
      '7' => array(
        'fid' => '17979',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_9.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86347',
        'status' => '1',
        'timestamp' => '1337616595',
        'origname' => 'ThinWhiteLine_9.jpg',
      ),
      '8' => array(
        'fid' => '17981',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_10.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '38799',
        'status' => '1',
        'timestamp' => '1337616602',
        'origname' => 'ThinWhiteLine_10.jpg',
      ),
      '9' => array(
        'fid' => '17983',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_11.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75101',
        'status' => '1',
        'timestamp' => '1337616609',
        'origname' => 'ThinWhiteLine_11.jpg',
      ),
      '10' => array(
        'fid' => '17985',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_12.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19150',
        'status' => '1',
        'timestamp' => '1337616617',
        'origname' => 'ThinWhiteLine_12.jpg',
      ),
      '11' => array(
        'fid' => '17987',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ThinWhiteLine_13.jpg',
        'filepath' => 'files/fmag_story/2012/May/ThinWhiteLine_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61178',
        'status' => '1',
        'timestamp' => '1337616626',
        'origname' => 'ThinWhiteLine_13.jpg',
      ),
    ),
    'path' => 'stories/thine-white-line',
    'tags' => array(
      '5' => array(
        '2687' => array(
          'tid' => '2687',
          'vid' => '5',
          'name' => 'HAREN MEHTA',
          'description' => 'http://www.harenmehta.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'HAREN MEHTA',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
