array(
  array(
    'nid' => '4053',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1337795356',
    'changed' => '1411162040',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4053',
    'revision_uid' => '1',
    'title' => 'Chain Reaction',
    'body' => '<p>
	Linked in.<br />
	Exclusive photography by <a href="http://jessica-pechet.com/">Jessica Pechet</a>.<br />
	Model - Marie Cruttenden at Numa.</p>
',
    'teaser' => '<p>
	Linked in.<br />
	Exclusive photography by <a href="http://jessica-pechet.com/">Jessica Pechet</a>.<br />
	Model - Marie Cruttenden at Numa.</p>
',
    'log' => '',
    'revision_timestamp' => '1411162040',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://jessica-pechet.com/?">JESSICA PECHET</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	JENNIE LYLE<br />
	&nbsp;</p>
<p>
	MAKEUP<br />
	TESLIN WARD</p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	NICOLE SANDERS<br />
	AT HEDKANDI</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	MARIE CRUTTENDEN<br />
	AT NUMA</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '17992',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '654229',
        'status' => '1',
        'timestamp' => '1337795088',
        'origname' => 'ChainReaction_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '18008',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '687460',
        'status' => '1',
        'timestamp' => '1337798201',
        'origname' => 'ChainReaction_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '17994',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '420821',
        'status' => '1',
        'timestamp' => '1337795114',
        'origname' => 'ChainReaction_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '17995',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '603231',
        'status' => '1',
        'timestamp' => '1337795126',
        'origname' => 'ChainReaction_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '17997',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '363543',
        'status' => '1',
        'timestamp' => '1337795140',
        'origname' => 'ChainReaction_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '17998',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '380917',
        'status' => '1',
        'timestamp' => '1337795147',
        'origname' => 'ChainReaction_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '18000',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '640810',
        'status' => '1',
        'timestamp' => '1337795163',
        'origname' => 'ChainReaction_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '18002',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '802557',
        'status' => '1',
        'timestamp' => '1337795172',
        'origname' => 'ChainReaction_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '18004',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '105667',
        'status' => '1',
        'timestamp' => '1337795183',
        'origname' => 'ChainReaction_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '18005',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '444465',
        'status' => '1',
        'timestamp' => '1337795195',
        'origname' => 'ChainReaction_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '18006',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89024',
        'status' => '1',
        'timestamp' => '1337795332',
        'origname' => 'ChainReaction_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '18007',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'ChainReaction_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/ChainReaction_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '573891',
        'status' => '1',
        'timestamp' => '1337795345',
        'origname' => 'ChainReaction_13 copy.jpg',
      ),
    ),
    'path' => 'stories/chain-reaction',
    'tags' => array(
      '5' => array(
        '2684' => array(
          'tid' => '2684',
          'vid' => '5',
          'name' => 'JESSICA PECHET',
          'description' => 'http://jessica-pechet.com/?',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2273' => array(
          'tid' => '2273',
          'vid' => '4',
          'name' => 'kink',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2137' => array(
          'tid' => '2137',
          'vid' => '4',
          'name' => 'lingerie',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JESSICA PECHET',
        '4' => 'kink, lingerie, women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
