array(
  array(
    'nid' => '4058',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1338221417',
    'changed' => '1403838941',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4058',
    'revision_uid' => '1',
    'title' => 'White Pages',
    'body' => '<p>
	The white stuff.<br />
	Exclusive photography by <a href="http://www.stephaniematthewsphotography.dphoto.com"><span style="text-decoration: underline;">Stephanie Matthews</span></a>.<br />
	Model - Alina at Fenton Moon.</p>
',
    'teaser' => '<p>
	The white stuff.<br />
	Exclusive photography by <a href="http://www.stephaniematthewsphotography.dphoto.com"><span style="text-decoration: underline;">Stephanie Matthews</span></a>.<br />
	Model - Alina at Fenton Moon.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838941',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.stephaniematthewsphotography.dphoto.com">STEPHANIE MATTHEWS</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	JUSTINE ALIOTTA<br />
	&nbsp;</p>
<p>
	MAKEUP<br />
	LATISHA NICOLE RANKIN</p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	KIA STERLING</p>
<p>
	&nbsp;</p>
<p>
	NAIL STYLING<br />
	DAPHNE ALLENDE</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	ALINA AT<br />
	FENTON MOON</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18074',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '489771',
        'status' => '1',
        'timestamp' => '1338221275',
        'origname' => 'WhitePages_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '18076',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126214',
        'status' => '1',
        'timestamp' => '1338221282',
        'origname' => 'WhitePages_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '18082',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '422791',
        'status' => '1',
        'timestamp' => '1338221306',
        'origname' => 'WhitePages_6 copy.jpg',
      ),
      '3' => array(
        'fid' => '18083',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90499',
        'status' => '1',
        'timestamp' => '1338221314',
        'origname' => 'WhitePages_7 copy.jpg',
      ),
      '4' => array(
        'fid' => '18085',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88730',
        'status' => '1',
        'timestamp' => '1338221326',
        'origname' => 'WhitePages_8 copy.jpg',
      ),
      '5' => array(
        'fid' => '18087',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '481422',
        'status' => '1',
        'timestamp' => '1338221334',
        'origname' => 'WhitePages_9 copy.jpg',
      ),
      '6' => array(
        'fid' => '18089',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '431269',
        'status' => '1',
        'timestamp' => '1338221342',
        'origname' => 'WhitePages_10 copy.jpg',
      ),
      '7' => array(
        'fid' => '18091',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81492',
        'status' => '1',
        'timestamp' => '1338221349',
        'origname' => 'WhitePages_11 copy.jpg',
      ),
      '8' => array(
        'fid' => '18092',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82180',
        'status' => '1',
        'timestamp' => '1338221356',
        'origname' => 'WhitePages_12 copy.jpg',
      ),
      '9' => array(
        'fid' => '18094',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '353327',
        'status' => '1',
        'timestamp' => '1338221370',
        'origname' => 'WhitePages_13 copy.jpg',
      ),
      '10' => array(
        'fid' => '18096',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '427166',
        'status' => '1',
        'timestamp' => '1338221378',
        'origname' => 'WhitePages_14 copy.jpg',
      ),
      '11' => array(
        'fid' => '18098',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82232',
        'status' => '1',
        'timestamp' => '1338221389',
        'origname' => 'WhitePages_15 copy.jpg',
      ),
      '12' => array(
        'fid' => '18100',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_16 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_16 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80617',
        'status' => '1',
        'timestamp' => '1338221398',
        'origname' => 'WhitePages_16 copy.jpg',
      ),
      '13' => array(
        'fid' => '18101',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WhitePages_17 copy.jpg',
        'filepath' => 'files/fmag_story/2012/May/WhitePages_17 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '577827',
        'status' => '1',
        'timestamp' => '1338221408',
        'origname' => 'WhitePages_17 copy.jpg',
      ),
    ),
    'path' => 'stories/white-pages',
    'tags' => array(
      '5' => array(
        '2688' => array(
          'tid' => '2688',
          'vid' => '5',
          'name' => 'STEPHANIE MATTHEWS',
          'description' => 'http://www.stephaniematthewsphotography.dphoto.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'STEPHANIE MATTHEWS',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
