array(
  array(
    'nid' => '4062',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1338492126',
    'changed' => '1403838941',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4062',
    'revision_uid' => '1',
    'title' => 'Night Fever',
    'body' => '<p>
	Hot in the evening.<br />
	Exclusive photography by <a href="http://www.kenpao.com/">Ken Pao</a>.<br />
	Model - Ola at MC2.</p>
',
    'teaser' => '<p>
	Hot in the evening.<br />
	Exclusive photography by <a href="http://www.kenpao.com/">Ken Pao</a>.<br />
	Model - Ola at MC2.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838941',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.kenpao.com/">KEN PAO</a></p>
<p>
	&nbsp;</p>
<p>
	FASHION EDITOR<br />
	<a href="http://www.andrewzumbo.com/">ANDREW ZUMBO</a><br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	<a href="http://www.belindazollo.com/">BELINDA ZOLLO</a></p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	<a href="http://www.elsahair.com/">ELSA CANEDO</a></p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	OLA AT MC2</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18133',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NightFever_2.jpg',
        'filepath' => 'files/fmag_story/2012/May/NightFever_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '162209',
        'status' => '1',
        'timestamp' => '1338492415',
        'origname' => 'NightFever_2.jpg',
      ),
      '1' => array(
        'fid' => '18135',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NightFever_3.jpg',
        'filepath' => 'files/fmag_story/2012/May/NightFever_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '223496',
        'status' => '1',
        'timestamp' => '1338492432',
        'origname' => 'NightFever_3.jpg',
      ),
      '2' => array(
        'fid' => '18137',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NightFever_4.jpg',
        'filepath' => 'files/fmag_story/2012/May/NightFever_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '23364',
        'status' => '1',
        'timestamp' => '1338492442',
        'origname' => 'NightFever_4.jpg',
      ),
      '3' => array(
        'fid' => '18139',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NightFever_5.jpg',
        'filepath' => 'files/fmag_story/2012/May/NightFever_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '262722',
        'status' => '1',
        'timestamp' => '1338492453',
        'origname' => 'NightFever_5.jpg',
      ),
      '4' => array(
        'fid' => '18141',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NightFever_6.jpg',
        'filepath' => 'files/fmag_story/2012/May/NightFever_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '292279',
        'status' => '1',
        'timestamp' => '1338492465',
        'origname' => 'NightFever_6.jpg',
      ),
      '5' => array(
        'fid' => '18143',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NightFever_7.jpg',
        'filepath' => 'files/fmag_story/2012/May/NightFever_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '281777',
        'status' => '1',
        'timestamp' => '1338492477',
        'origname' => 'NightFever_7.jpg',
      ),
      '6' => array(
        'fid' => '18145',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NightFever_8.jpg',
        'filepath' => 'files/fmag_story/2012/May/NightFever_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '163834',
        'status' => '1',
        'timestamp' => '1338492490',
        'origname' => 'NightFever_8.jpg',
      ),
      '7' => array(
        'fid' => '18147',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NightFever_9.jpg',
        'filepath' => 'files/fmag_story/2012/May/NightFever_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '160717',
        'status' => '1',
        'timestamp' => '1338492503',
        'origname' => 'NightFever_9.jpg',
      ),
      '8' => array(
        'fid' => '18149',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NightFever_10.jpg',
        'filepath' => 'files/fmag_story/2012/May/NightFever_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '218675',
        'status' => '1',
        'timestamp' => '1338492516',
        'origname' => 'NightFever_10.jpg',
      ),
      '9' => array(
        'fid' => '18150',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NightFever_11.jpg',
        'filepath' => 'files/fmag_story/2012/May/NightFever_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '217241',
        'status' => '1',
        'timestamp' => '1338492525',
        'origname' => 'NightFever_11.jpg',
      ),
    ),
    'path' => 'stories/night-fever',
    'tags' => array(
      '1' => array(
        '574' => array(
          'tid' => '574',
          'vid' => '1',
          'name' => 'Alexis Bittar',
          'description' => 'www.alexisbittar.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '90' => array(
          'tid' => '90',
          'vid' => '1',
          'name' => 'ARMANI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '700' => array(
          'tid' => '700',
          'vid' => '1',
          'name' => 'BCBG',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '77' => array(
          'tid' => '77',
          'vid' => '1',
          'name' => 'chanel',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '763' => array(
          'tid' => '763',
          'vid' => '1',
          'name' => 'david meister',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '249' => array(
          'tid' => '249',
          'vid' => '1',
          'name' => 'ETRO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '215' => array(
          'tid' => '215',
          'vid' => '1',
          'name' => 'GUCCI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '203' => array(
          'tid' => '203',
          'vid' => '1',
          'name' => 'MARC JACOBS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '582' => array(
          'tid' => '582',
          'vid' => '1',
          'name' => 'opening ceremony',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '765' => array(
          'tid' => '765',
          'vid' => '1',
          'name' => 'van cleef and arpels',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '764' => array(
          'tid' => '764',
          'vid' => '1',
          'name' => 'walter steiger',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2689' => array(
          'tid' => '2689',
          'vid' => '5',
          'name' => 'KEN PAO',
          'description' => 'http://www.kenpao.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Alexis Bittar, ARMANI, BCBG, chanel, david meister, ETRO, GUCCI, MARC JACOBS, opening ceremony, van cleef and arpels, walter steiger',
        '5' => 'KEN PAO',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
