array(
  array(
    'nid' => '4066',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1338826086',
    'changed' => '1403838941',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4066',
    'revision_uid' => '1',
    'title' => 'Dress It Up',
    'body' => '<p>
	Re-dress yourself.<br />
	Exclusive photography by <a href="http://patricklacsina.com/">Patrick Lacsina</a>.<br />
	Model - Elena at Next.</p>
',
    'teaser' => '<p>
	Re-dress yourself.<br />
	Exclusive photography by <a href="http://patricklacsina.com/">Patrick Lacsina</a>.<br />
	Model - Elena at Next.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838941',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://patricklacsina.com/">PATRICK LACSINA</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	CHRISTOPHER NEVIN<br />
	<br />
	&nbsp;</p>
<p>
	HAIR &amp; MAKEUP<br />
	EMILY FUNG</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	ELENA&nbsp;<br />
	AT NEXT</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18211',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '431597',
        'status' => '1',
        'timestamp' => '1338826196',
        'origname' => 'DressItUp_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '18212',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '115039',
        'status' => '1',
        'timestamp' => '1338826207',
        'origname' => 'DressItUp_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '18214',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '420279',
        'status' => '1',
        'timestamp' => '1338826219',
        'origname' => 'DressItUp_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '18216',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '433381',
        'status' => '1',
        'timestamp' => '1338826226',
        'origname' => 'DressItUp_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '18218',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81254',
        'status' => '1',
        'timestamp' => '1338826233',
        'origname' => 'DressItUp_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '18220',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '392249',
        'status' => '1',
        'timestamp' => '1338826241',
        'origname' => 'DressItUp_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '18222',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '395023',
        'status' => '1',
        'timestamp' => '1338826249',
        'origname' => 'DressItUp_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '18224',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '389196',
        'status' => '1',
        'timestamp' => '1338826259',
        'origname' => 'DressItUp_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '18226',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '396644',
        'status' => '1',
        'timestamp' => '1338826268',
        'origname' => 'DressItUp_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '18228',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '443679',
        'status' => '1',
        'timestamp' => '1338826275',
        'origname' => 'DressItUp_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '18230',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90550',
        'status' => '1',
        'timestamp' => '1338826283',
        'origname' => 'DressItUp_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '18232',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '382576',
        'status' => '1',
        'timestamp' => '1338826291',
        'origname' => 'DressItUp_13 copy.jpg',
      ),
      '12' => array(
        'fid' => '18234',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '426472',
        'status' => '1',
        'timestamp' => '1338826299',
        'origname' => 'DressItUp_14 copy.jpg',
      ),
      '13' => array(
        'fid' => '18236',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '490008',
        'status' => '1',
        'timestamp' => '1338826307',
        'origname' => 'DressItUp_15 copy.jpg',
      ),
      '14' => array(
        'fid' => '18238',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_16 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_16 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '388441',
        'status' => '1',
        'timestamp' => '1338826316',
        'origname' => 'DressItUp_16 copy.jpg',
      ),
      '15' => array(
        'fid' => '18240',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressItUp_17 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/DressItUp_17 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82685',
        'status' => '1',
        'timestamp' => '1338826324',
        'origname' => 'DressItUp_17 copy.jpg',
      ),
    ),
    'path' => 'stories/dress-it',
    'tags' => array(
      '5' => array(
        '2690' => array(
          'tid' => '2690',
          'vid' => '5',
          'name' => 'PATRICK LACSINA',
          'description' => 'http://patricklacsina.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'PATRICK LACSINA',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
