array(
  array(
    'nid' => '4070',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1339777589',
    'changed' => '1403838426',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4070',
    'revision_uid' => '1',
    'title' => 'Block Party',
    'body' => '<p>
	Live the color.<br />
	Exclusive photography by <a href="http://www.farzamhd.com">Farzam hd</a><br />
	Model - Andrea at Ford.</p>
',
    'teaser' => '<p>
	Live the color.<br />
	Exclusive photography by <a href="http://www.farzamhd.com">Farzam hd</a><br />
	Model - Andrea at Ford.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838426',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.farzamhd.com">FARZAM HD</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	OFFELIA LIU<br />
	<br />
	&nbsp;</p>
<p>
	HAIR<br />
	&amp; MAKEUP<br />
	KARIMA SUMA<br />
	AT JUDY INC</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	ANDREA<br />
	AT FORD</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18305',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '478170',
        'status' => '1',
        'timestamp' => '1339518247',
        'origname' => 'farzam_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '18306',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '577990',
        'status' => '1',
        'timestamp' => '1339518257',
        'origname' => 'farzam_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '18309',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '515679',
        'status' => '1',
        'timestamp' => '1339518265',
        'origname' => 'farzam_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '18311',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '517921',
        'status' => '1',
        'timestamp' => '1339518272',
        'origname' => 'farzam_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '18313',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82739',
        'status' => '1',
        'timestamp' => '1339518283',
        'origname' => 'farzam_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '18315',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '533971',
        'status' => '1',
        'timestamp' => '1339518294',
        'origname' => 'farzam_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '18317',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82809',
        'status' => '1',
        'timestamp' => '1339518306',
        'origname' => 'farzam_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '18319',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '493923',
        'status' => '1',
        'timestamp' => '1339518316',
        'origname' => 'farzam_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '18323',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '563399',
        'status' => '1',
        'timestamp' => '1339518345',
        'origname' => 'farzam_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '18321',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '469543',
        'status' => '1',
        'timestamp' => '1339518325',
        'origname' => 'farzam_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '18324',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79257',
        'status' => '1',
        'timestamp' => '1339518358',
        'origname' => 'farzam_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '18325',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'farzam_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/farzam_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '593876',
        'status' => '1',
        'timestamp' => '1339518381',
        'origname' => 'farzam_13 copy.jpg',
      ),
    ),
    'path' => 'stories/block-party-0',
    'tags' => array(
      '5' => array(
        '2691' => array(
          'tid' => '2691',
          'vid' => '5',
          'name' => 'FARZAM HD',
          'description' => 'http://www.farzamhd.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'FARZAM HD',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
