array(
  array(
    'nid' => '4072',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1339361282',
    'changed' => '1403838728',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4072',
    'revision_uid' => '1',
    'title' => 'Health',
    'body' => '<p>
	Good fit.<br />
	Exclusive photography by <a href="http://www.andylonghoang.com/">ANDY LONG HOANG</a>.<br />
	Models - Feliz &amp; Deiss at Dulcedo.</p>
',
    'teaser' => '<p>
	Good fit.<br />
	Exclusive photography by <a href="http://www.andylonghoang.com/">ANDY LONG HOANG</a>.<br />
	Models - Feliz &amp; Deiss at Dulcedo.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838728',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.andylonghoang.com/">ANDY LONG HOANG</a></p>
<p>
	&nbsp;</p>
<p>
	STYLING<br />
	RIMA CHAHINE<br />
	&amp; ANTHONY GOSHGARIAN</p>
<p>
	&nbsp;</p>
<p>
	MODELS<br />
	FELIZ &amp; DEISS<br />
	AT DULCEDO</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18328',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '104547',
        'status' => '1',
        'timestamp' => '1339620382',
        'origname' => 'HEALTH_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '18330',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '516003',
        'status' => '1',
        'timestamp' => '1339620391',
        'origname' => 'HEALTH_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '18332',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '101459',
        'status' => '1',
        'timestamp' => '1339620400',
        'origname' => 'HEALTH_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '18334',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '551078',
        'status' => '1',
        'timestamp' => '1339620406',
        'origname' => 'HEALTH_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '18336',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '317858',
        'status' => '1',
        'timestamp' => '1339620413',
        'origname' => 'HEALTH_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '18338',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '310614',
        'status' => '1',
        'timestamp' => '1339620420',
        'origname' => 'HEALTH_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '18340',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79569',
        'status' => '1',
        'timestamp' => '1339620428',
        'origname' => 'HEALTH_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '18342',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '547124',
        'status' => '1',
        'timestamp' => '1339620436',
        'origname' => 'HEALTH_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '18344',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '317898',
        'status' => '1',
        'timestamp' => '1339620443',
        'origname' => 'HEALTH_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '18346',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81250',
        'status' => '1',
        'timestamp' => '1339620451',
        'origname' => 'HEALTH_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '18350',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '465089',
        'status' => '1',
        'timestamp' => '1339621098',
        'origname' => 'HEALTH copy.jpg',
      ),
      '11' => array(
        'fid' => '18348',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'HEALTH_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/HEALTH_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '572035',
        'status' => '1',
        'timestamp' => '1339620467',
        'origname' => 'HEALTH_13 copy.jpg',
      ),
    ),
    'path' => 'stories/health',
    'tags' => array(
      '5' => array(
        '2692' => array(
          'tid' => '2692',
          'vid' => '5',
          'name' => 'ANDY LONG HOANG',
          'description' => 'http://www.andylonghoang.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'ANDY LONG HOANG',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
