array(
  array(
    'nid' => '4074',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1339766695',
    'changed' => '1403838165',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4074',
    'revision_uid' => '1',
    'title' => 'Breather',
    'body' => '<p>
	Take it.<br />
	Exclusive photography by <a href="http://www.sarahmccolgan.com/">Sarah MCColgan</a>.<br />
	Models - Jeremy Wardlaw at Request.</p>
',
    'teaser' => '<p>
	Take it.<br />
	Exclusive photography by <a href="http://www.sarahmccolgan.com/">Sarah MCColgan</a>.<br />
	Models - Jeremy Wardlaw at Request.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838165',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.sarahmccolgan.com/">SARAH MCCOLGAN</a></p>
<p>
	&nbsp;</p>
<p>
	MAKEUP &amp; GROOMING<br />
	VICTOR HENAO<br />
	AT TOP 5</p>
<p>
	&nbsp;</p>
<p>
	MODEL<br />
	JEREMY WARDLAW</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18352',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'breather_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/breather_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '510858',
        'status' => '1',
        'timestamp' => '1339766613',
        'origname' => 'breather_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '18353',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'breather_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/breather_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '247740',
        'status' => '1',
        'timestamp' => '1339766624',
        'origname' => 'breather_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '18354',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'breather_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/breather_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '389324',
        'status' => '1',
        'timestamp' => '1339766640',
        'origname' => 'breather_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '18356',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'breather_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/breather_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '392358',
        'status' => '1',
        'timestamp' => '1339766653',
        'origname' => 'breather_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '18358',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'breather_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/breather_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '314686',
        'status' => '1',
        'timestamp' => '1339766661',
        'origname' => 'breather_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '18360',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'breather_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/breather_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '427299',
        'status' => '1',
        'timestamp' => '1339766670',
        'origname' => 'breather_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '18362',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'breather_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/breather_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74928',
        'status' => '1',
        'timestamp' => '1339766677',
        'origname' => 'breather_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '18363',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'breather_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/breather_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '405015',
        'status' => '1',
        'timestamp' => '1339766684',
        'origname' => 'breather_9 copy.jpg',
      ),
    ),
    'path' => 'stories/breather',
    'tags' => array(
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2693' => array(
          'tid' => '2693',
          'vid' => '5',
          'name' => 'SARAH MCCOLGAN',
          'description' => 'http://www.sarahmccolgan.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'men',
        '5' => 'SARAH MCCOLGAN',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
