array(
  array(
    'nid' => '4083',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1340756873',
    'changed' => '1403838165',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4083',
    'revision_uid' => '1',
    'title' => 'Luke Worrall',
    'body' => '<p>
	Worrall around.<br />
	Exclusive photography by<a href="http://www.thejamesbarnes.com/"> JD Barnes</a>.<br />
	&nbsp;</p>
',
    'teaser' => '<p>
	Worrall around.<br />
	Exclusive photography by<a href="http://www.thejamesbarnes.com/"> JD Barnes</a>.<br />
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1403838165',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.thejamesbarnes.com/">JD BARNES</a></p>
<p>
	STYLING<br />
	NADIA CHIN</p>
<p>
	GROOMING<br />
	ZAN VONG</p>
<p>
	REPRESENTATION<br />
	D1</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18568',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'noteLukeWorrall2.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/noteLukeWorrall2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '215645',
        'status' => '1',
        'timestamp' => '1340844203',
        'origname' => 'noteLukeWorrall2.jpg',
      ),
      '1' => array(
        'fid' => '18545',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'noteLukeWorrall_3.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/noteLukeWorrall_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '54089',
        'status' => '1',
        'timestamp' => '1340756803',
        'origname' => 'noteLukeWorrall_3.jpg',
      ),
      '2' => array(
        'fid' => '18547',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'noteLukeWorrall_4.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/noteLukeWorrall_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '162600',
        'status' => '1',
        'timestamp' => '1340756811',
        'origname' => 'noteLukeWorrall_4.jpg',
      ),
      '3' => array(
        'fid' => '18549',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'noteLukeWorrall_5.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/noteLukeWorrall_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18720',
        'status' => '1',
        'timestamp' => '1340756819',
        'origname' => 'noteLukeWorrall_5.jpg',
      ),
      '4' => array(
        'fid' => '18551',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'noteLukeWorrall_6.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/noteLukeWorrall_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '24993',
        'status' => '1',
        'timestamp' => '1340756826',
        'origname' => 'noteLukeWorrall_6.jpg',
      ),
      '5' => array(
        'fid' => '18553',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'noteLukeWorrall_7.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/noteLukeWorrall_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '163737',
        'status' => '1',
        'timestamp' => '1340756835',
        'origname' => 'noteLukeWorrall_7.jpg',
      ),
      '6' => array(
        'fid' => '18555',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'noteLukeWorrall_8.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/noteLukeWorrall_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '157826',
        'status' => '1',
        'timestamp' => '1340756843',
        'origname' => 'noteLukeWorrall_8.jpg',
      ),
      '7' => array(
        'fid' => '18557',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'noteLukeWorrall_9.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/noteLukeWorrall_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102603',
        'status' => '1',
        'timestamp' => '1340756851',
        'origname' => 'noteLukeWorrall_9.jpg',
      ),
      '8' => array(
        'fid' => '18561',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'noteLukeWorrall_10.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/noteLukeWorrall_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58399',
        'status' => '1',
        'timestamp' => '1340757122',
        'origname' => 'noteLukeWorrall_10.jpg',
      ),
      '9' => array(
        'fid' => '18562',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'noteLukeWorrall_11.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/noteLukeWorrall_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161929',
        'status' => '1',
        'timestamp' => '1340757130',
        'origname' => 'noteLukeWorrall_11.jpg',
      ),
    ),
    'path' => 'stories/luke-worrall',
    'tags' => array(
      '5' => array(
        '2694' => array(
          'tid' => '2694',
          'vid' => '5',
          'name' => 'JD BARNES',
          'description' => 'http://www.thejamesbarnes.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '229' => array(
          'tid' => '229',
          'vid' => '1',
          'name' => 'TOPMAN',
          'description' => 'www.topman.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'JD BARNES',
        '4' => 'men',
        '1' => 'TOPMAN',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
