array(
  array(
    'nid' => '4085',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1340846555',
    'changed' => '1403838426',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4085',
    'revision_uid' => '1',
    'title' => 'Molly O\'Connell',
    'body' => '<p>
	Miss Molly.<br />
	Exclusive photography by <a href="http://www.nncphoto.com/">Nelson N Castillo</a>.</p>
',
    'teaser' => '<p>
	Miss Molly.<br />
	Exclusive photography by <a href="http://www.nncphoto.com/">Nelson N Castillo</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838426',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.nncphoto.com/">NELSON N CASTILLO</a></p>
<p>
	WARDROBE<br />
	HERNAN LANDER</p>
<p>
	MAKEUP<br />
	RENARDA JOY<br />
	<br />
	HAIR<br />
	PATRICK NAVARRO<br />
	AT STELLA NOVA</p>
<p>
	REPRESENTATION<br />
	IMAGES</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18572',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note-MollyO_2.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Note-MollyO_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '58891',
        'status' => '1',
        'timestamp' => '1340846423',
        'origname' => 'Note-MollyO_2.jpg',
      ),
      '1' => array(
        'fid' => '18574',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note-MollyO_3.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Note-MollyO_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78774',
        'status' => '1',
        'timestamp' => '1340846437',
        'origname' => 'Note-MollyO_3.jpg',
      ),
      '2' => array(
        'fid' => '18576',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note-MollyO_4.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Note-MollyO_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '21193',
        'status' => '1',
        'timestamp' => '1340846447',
        'origname' => 'Note-MollyO_4.jpg',
      ),
      '3' => array(
        'fid' => '18578',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note-MollyO_5.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Note-MollyO_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128525',
        'status' => '1',
        'timestamp' => '1340846482',
        'origname' => 'Note-MollyO_5.jpg',
      ),
      '4' => array(
        'fid' => '18580',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note-MollyO_6.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Note-MollyO_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '56101',
        'status' => '1',
        'timestamp' => '1340846491',
        'origname' => 'Note-MollyO_6.jpg',
      ),
      '5' => array(
        'fid' => '18582',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note-MollyO_7.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Note-MollyO_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '64785',
        'status' => '1',
        'timestamp' => '1340846499',
        'origname' => 'Note-MollyO_7.jpg',
      ),
      '6' => array(
        'fid' => '18584',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note-MollyO_8.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Note-MollyO_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1340846508',
        'origname' => 'Note-MollyO_8.jpg',
      ),
      '7' => array(
        'fid' => '18586',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note-MollyO_9.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Note-MollyO_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127508',
        'status' => '1',
        'timestamp' => '1340846518',
        'origname' => 'Note-MollyO_9.jpg',
      ),
      '8' => array(
        'fid' => '18588',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note-MollyO_10.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Note-MollyO_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '49914',
        'status' => '1',
        'timestamp' => '1340846528',
        'origname' => 'Note-MollyO_10.jpg',
      ),
      '9' => array(
        'fid' => '18589',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note-MollyO_11.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Note-MollyO_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93795',
        'status' => '1',
        'timestamp' => '1340846550',
        'origname' => 'Note-MollyO_11.jpg',
      ),
    ),
    'path' => 'stories/molly-oconnell',
    'tags' => array(
      '5' => array(
        '2695' => array(
          'tid' => '2695',
          'vid' => '5',
          'name' => 'NELSON N CASTILLO',
          'description' => 'http://www.nncphoto.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      '2' => array(
        '354' => '354',
      ),
      'tags' => array(
        '5' => 'NELSON N CASTILLO',
        '4' => 'women',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
