array(
  array(
    'nid' => '4089',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1340908913',
    'changed' => '1403838165',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4089',
    'revision_uid' => '1',
    'title' => 'Visionaries',
    'body' => '<p>
	The eyes have it.<br />
	Exclusive photography by <a href="http://www.daniel-archer.com/home/">Daniel Archer</a>.<br />
	Models - Blair Norfolk at Chadwicks, Daniel Dinuzzo at London, Dom O&#39;Keefe at Giant.</p>
',
    'teaser' => '<p>
	The eyes have it.<br />
	Exclusive photography by <a href="http://www.daniel-archer.com/home/">Daniel Archer</a>.<br />
	Models - Blair Norfolk at Chadwicks, Daniel Dinuzzo at London, Dom O&#39;Keefe at Giant.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838165',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.daniel-archer.com/home/">DANIEL ARCHER</a></p>
<p>
	FASHION EDITOR<br />
	<a href="http://www.andrewzumbo.com/">ANDREW ZUMBO</a></p>
<p>
	HAIR<br />
	PHOENIX THOMSON<br />
	FOR AMERICAN CREW</p>
<p>
	MAKEUP<br />
	SHEV KELLY<br />
	FOR NAPOLEON PERDIS</p>
<p>
	MODELS<br />
	BLAIR NORFOLK<br />
	AT CHADWICKS<br />
	DANIEL DINUZZO<br />
	AT LONDON<br />
	DOM O&#39;KEEFE<br />
	AT GIANT<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18611',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '636383',
        'status' => '1',
        'timestamp' => '1340908742',
        'origname' => 'Visionaries_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '18613',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '471998',
        'status' => '1',
        'timestamp' => '1340908753',
        'origname' => 'Visionaries_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '18615',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '532697',
        'status' => '1',
        'timestamp' => '1340908762',
        'origname' => 'Visionaries_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '18617',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '606118',
        'status' => '1',
        'timestamp' => '1340908775',
        'origname' => 'Visionaries_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '18619',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '796175',
        'status' => '1',
        'timestamp' => '1340908786',
        'origname' => 'Visionaries_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '18621',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '792949',
        'status' => '1',
        'timestamp' => '1340908795',
        'origname' => 'Visionaries_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '18623',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '701594',
        'status' => '1',
        'timestamp' => '1340908805',
        'origname' => 'Visionaries_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '18625',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81898',
        'status' => '1',
        'timestamp' => '1340908812',
        'origname' => 'Visionaries_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '18627',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '658857',
        'status' => '1',
        'timestamp' => '1340908823',
        'origname' => 'Visionaries_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '18629',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '485933',
        'status' => '1',
        'timestamp' => '1340908831',
        'origname' => 'Visionaries_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '18630',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '598541',
        'status' => '1',
        'timestamp' => '1340908839',
        'origname' => 'Visionaries_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '18632',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '82522',
        'status' => '1',
        'timestamp' => '1340908864',
        'origname' => 'Visionaries_13 copy.jpg',
      ),
      '12' => array(
        'fid' => '18633',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '469219',
        'status' => '1',
        'timestamp' => '1340908872',
        'origname' => 'Visionaries_14 copy.jpg',
      ),
      '13' => array(
        'fid' => '18635',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '570025',
        'status' => '1',
        'timestamp' => '1340908885',
        'origname' => 'Visionaries_15 copy.jpg',
      ),
      '14' => array(
        'fid' => '18637',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_16 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_16 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '846814',
        'status' => '1',
        'timestamp' => '1340908897',
        'origname' => 'Visionaries_16 copy.jpg',
      ),
      '15' => array(
        'fid' => '18638',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Visionaries_17 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jun/Visionaries_17 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '785814',
        'status' => '1',
        'timestamp' => '1340908905',
        'origname' => 'Visionaries_17 copy.jpg',
      ),
    ),
    'path' => 'stories/visionaries',
    'tags' => array(
      '5' => array(
        '2697' => array(
          'tid' => '2697',
          'vid' => '5',
          'name' => 'DANIEL ARCHER',
          'description' => 'http://www.daniel-archer.com/home/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'DANIEL ARCHER',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
