array(
  array(
    'nid' => '4092',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1342031549',
    'changed' => '1403838426',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4092',
    'revision_uid' => '1',
    'title' => 'Lise',
    'body' => '<p>
	Lovely Lise.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com">Darren Black</a>.</p>
',
    'teaser' => '<p>
	Lovely Lise.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com">Darren Black</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838426',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHER<br />
	&amp; EDITOR<br />
	<a href="http://darrenblackphotography.com">DARREN BLACK</a></p>
<p>
	MAKEUP<br />
	RHEA LE RICHE</p>
<p>
	REPRESENTATION<br />
	SELECT</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18693',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '236844',
        'status' => '1',
        'timestamp' => '1342031451',
        'origname' => 'Note LISE_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '18695',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '365395',
        'status' => '1',
        'timestamp' => '1342031463',
        'origname' => 'Note LISE copy.jpg',
      ),
      '2' => array(
        'fid' => '18697',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '543092',
        'status' => '1',
        'timestamp' => '1342031472',
        'origname' => 'Note LISE_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '18699',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '392915',
        'status' => '1',
        'timestamp' => '1342031478',
        'origname' => 'Note LISE_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '18701',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '465727',
        'status' => '1',
        'timestamp' => '1342031484',
        'origname' => 'Note LISE_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '18703',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '363227',
        'status' => '1',
        'timestamp' => '1342031491',
        'origname' => 'Note LISE_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '18705',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '452471',
        'status' => '1',
        'timestamp' => '1342031499',
        'origname' => 'Note LISE_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '18707',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '444382',
        'status' => '1',
        'timestamp' => '1342031508',
        'origname' => 'Note LISE_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '18709',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '370662',
        'status' => '1',
        'timestamp' => '1342031517',
        'origname' => 'Note LISE_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '18710',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '502446',
        'status' => '1',
        'timestamp' => '1342031524',
        'origname' => 'Note LISE_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '18712',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '465957',
        'status' => '1',
        'timestamp' => '1342031535',
        'origname' => 'Note LISE_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '18713',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note LISE_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/Note LISE_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '187230',
        'status' => '1',
        'timestamp' => '1342031542',
        'origname' => 'Note LISE_13 copy.jpg',
      ),
    ),
    'path' => 'stories/lise',
    'tags' => array(
      '5' => array(
        '2698' => array(
          'tid' => '2698',
          'vid' => '5',
          'name' => '& EDITOR',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => '& EDITOR',
        '4' => 'women',
      ),
      '2' => array(
        '354' => '354',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
