array(
  array(
    'nid' => '4094',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1342222013',
    'changed' => '1403838425',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4094',
    'revision_uid' => '1',
    'title' => 'Altar Girls',
    'body' => '<p>
	Altar states.<br />
	Exclusive photography by <a href="http://kyriakosandkolette.com/">Kyriakos + Kolette</a>.&nbsp;<br />
	Models - Madalina, Samara, Siobhan, &amp; Whitney at Premier.</p>
',
    'teaser' => '<p>
	Altar states.<br />
	Exclusive photography by <a href="http://kyriakosandkolette.com/">Kyriakos + Kolette</a>.&nbsp;<br />
	Models - Madalina, Samara, Siobhan, &amp; Whitney at Premier.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838425',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://kyriakosandkolette.com/">KYRIAKOS + KOLETTE</a></p>
<p>
	STYLING<br />
	KATHERINE DOYLE</p>
<p>
	HAIR &amp; MAKEUP<br />
	TRICIA TEMPLE</p>
<p>
	MODELS<br />
	MADALINA<br />
	SAMARA<br />
	SIOBHAN<br />
	&amp; WHITNEY<br />
	AT PREMIER<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18719',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_2.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '17138',
        'status' => '1',
        'timestamp' => '1342221893',
        'origname' => 'AltarGirls_2.jpg',
      ),
      '1' => array(
        'fid' => '18721',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_3.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98209',
        'status' => '1',
        'timestamp' => '1342221902',
        'origname' => 'AltarGirls_3.jpg',
      ),
      '2' => array(
        'fid' => '18723',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_4.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '187225',
        'status' => '1',
        'timestamp' => '1342221912',
        'origname' => 'AltarGirls_4.jpg',
      ),
      '3' => array(
        'fid' => '18725',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_5.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '15748',
        'status' => '1',
        'timestamp' => '1342221920',
        'origname' => 'AltarGirls_5.jpg',
      ),
      '4' => array(
        'fid' => '18727',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_6.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '12200',
        'status' => '1',
        'timestamp' => '1342221929',
        'origname' => 'AltarGirls_6.jpg',
      ),
      '5' => array(
        'fid' => '18729',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_7.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '165949',
        'status' => '1',
        'timestamp' => '1342221939',
        'origname' => 'AltarGirls_7.jpg',
      ),
      '6' => array(
        'fid' => '18731',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_8.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161887',
        'status' => '1',
        'timestamp' => '1342221948',
        'origname' => 'AltarGirls_8.jpg',
      ),
      '7' => array(
        'fid' => '18733',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_9.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '231865',
        'status' => '1',
        'timestamp' => '1342221964',
        'origname' => 'AltarGirls_9.jpg',
      ),
      '8' => array(
        'fid' => '18735',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_10.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '214344',
        'status' => '1',
        'timestamp' => '1342221977',
        'origname' => 'AltarGirls_10.jpg',
      ),
      '9' => array(
        'fid' => '18737',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_11.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14646',
        'status' => '1',
        'timestamp' => '1342221986',
        'origname' => 'AltarGirls_11.jpg',
      ),
      '10' => array(
        'fid' => '18739',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_12.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '14072',
        'status' => '1',
        'timestamp' => '1342221995',
        'origname' => 'AltarGirls_12.jpg',
      ),
      '11' => array(
        'fid' => '18740',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'AltarGirls_13.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/AltarGirls_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '162030',
        'status' => '1',
        'timestamp' => '1342222004',
        'origname' => 'AltarGirls_13.jpg',
      ),
    ),
    'path' => 'stories/altar-girls',
    'tags' => array(
      '1' => array(
        '781' => array(
          'tid' => '781',
          'vid' => '1',
          'name' => 'Alter Ego',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '780' => array(
          'tid' => '780',
          'vid' => '1',
          'name' => 'Asudari',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '783' => array(
          'tid' => '783',
          'vid' => '1',
          'name' => 'Rachael Maria Graham',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '782' => array(
          'tid' => '782',
          'vid' => '1',
          'name' => 'Stency Kidega',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '784' => array(
          'tid' => '784',
          'vid' => '1',
          'name' => 'Victoria Campbell',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2699' => array(
          'tid' => '2699',
          'vid' => '5',
          'name' => 'KYRIAKOS + KOLETTE',
          'description' => 'http://kyriakosandkolette.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Alter Ego, Asudari, Rachael Maria Graham, Stency Kidega, Victoria Campbell',
        '5' => 'KYRIAKOS + KOLETTE',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
