array(
  array(
    'nid' => '4104',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1343408488',
    'changed' => '1403838164',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4104',
    'revision_uid' => '1',
    'title' => 'Studio in Bushwick',
    'body' => '<p>
	Smells like turpentine.<br />
	Exclusive photography by <a href="http://www.samdevriesphoto.com/">Sam Devries</a>.&nbsp;<br />
	Model - Dustin Kime &amp; Elijah Johnston at Red Citizen.</p>
',
    'teaser' => '<p>
	Smells like turpentine.<br />
	Exclusive photography by <a href="http://www.samdevriesphoto.com/">Sam Devries</a>.&nbsp;<br />
	Model - Dustin Kime &amp; Elijah Johnston at Red Citizen.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838164',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.samdevriesphoto.com/">SAM DEVRIES</a></p>
<p>
	<br />
	STYLIST<br />
	PIERRE MERCIER</p>
<p>
	MODELS<br />
	DUSTIN KIME<br />
	&amp; ELIJAH JOHNSTON<br />
	AT RED CITIZEN</p>
<p>
	&nbsp;</p>
<p>
	<a href="http://artsinbushwick.org/bos2012/">ARTS IN BUSHWICK</a></p>
<p>
	<a href="http://www.artistchain.com/"><br />
	CHAIN</a></p>
<p>
	<a href="http://www.cristianadepedrini.com/">CHRISTIANA DEPEDRINI</a></p>
<p>
	<a href="http://www.meghitchcock.com/">MEG HITCHCOCK</a></p>
<p>
	<a href="http://www.lorikirkbride.co/">LORI KIRKBRIDE</a></p>
<p>
	<a href="http://seung mo park"><br />
	SEUNG MO PARK</a></p>
<p>
	<a href="http://sparrenbergerstudio.com/"><br />
	CYNTHIA SPARRENBERGER</a></p>
<p>
	<a href="http://www.stegersculpture.com/"><br />
	KURT ERNEST STEGER</a></p>
<p>
	<a href="http://www.salman-toor.com/">SALMAN TOOR</a><br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18882',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '478431',
        'status' => '1',
        'timestamp' => '1342721727',
        'origname' => 'BUSHWICK_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '18884',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '582471',
        'status' => '1',
        'timestamp' => '1342721741',
        'origname' => 'BUSHWICK_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '18886',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '394400',
        'status' => '1',
        'timestamp' => '1342721752',
        'origname' => 'BUSHWICK_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '18887',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '442409',
        'status' => '1',
        'timestamp' => '1342721761',
        'origname' => 'BUSHWICK_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '18904',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_16 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_16 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '617486',
        'status' => '1',
        'timestamp' => '1342721919',
        'origname' => 'BUSHWICK_16 copy.jpg',
      ),
      '5' => array(
        'fid' => '18905',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_17 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_17 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84322',
        'status' => '1',
        'timestamp' => '1342721938',
        'origname' => 'BUSHWICK_17 copy.jpg',
      ),
      '6' => array(
        'fid' => '18889',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '506130',
        'status' => '1',
        'timestamp' => '1342721780',
        'origname' => 'BUSHWICK_6 copy.jpg',
      ),
      '7' => array(
        'fid' => '18890',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '390505',
        'status' => '1',
        'timestamp' => '1342721804',
        'origname' => 'BUSHWICK_7 copy.jpg',
      ),
      '8' => array(
        'fid' => '18892',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '562567',
        'status' => '1',
        'timestamp' => '1342721819',
        'origname' => 'BUSHWICK_8 copy.jpg',
      ),
      '9' => array(
        'fid' => '18893',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '401967',
        'status' => '1',
        'timestamp' => '1342721834',
        'origname' => 'BUSHWICK_9 copy.jpg',
      ),
      '10' => array(
        'fid' => '18907',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_18 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_18 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1086039',
        'status' => '1',
        'timestamp' => '1342721959',
        'origname' => 'BUSHWICK_18 copy.jpg',
      ),
      '11' => array(
        'fid' => '18913',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICKb copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICKb copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '283102',
        'status' => '1',
        'timestamp' => '1342725348',
        'origname' => 'BUSHWICKb copy.jpg',
      ),
      '12' => array(
        'fid' => '18909',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_20 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_20 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '310853',
        'status' => '1',
        'timestamp' => '1342721984',
        'origname' => 'BUSHWICK_20 copy.jpg',
      ),
      '13' => array(
        'fid' => '18914',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '255288',
        'status' => '1',
        'timestamp' => '1342725362',
        'origname' => 'BUSHWICK copy.jpg',
      ),
      '14' => array(
        'fid' => '18895',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78916',
        'status' => '1',
        'timestamp' => '1342721863',
        'origname' => 'BUSHWICK_10 copy.jpg',
      ),
      '15' => array(
        'fid' => '18897',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '881884',
        'status' => '1',
        'timestamp' => '1342721874',
        'origname' => 'BUSHWICK_11 copy.jpg',
      ),
      '16' => array(
        'fid' => '18901',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '565997',
        'status' => '1',
        'timestamp' => '1342721897',
        'origname' => 'BUSHWICK_14 copy.jpg',
      ),
      '17' => array(
        'fid' => '18903',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '457319',
        'status' => '1',
        'timestamp' => '1342721908',
        'origname' => 'BUSHWICK_15 copy.jpg',
      ),
      '18' => array(
        'fid' => '18899',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '428849',
        'status' => '1',
        'timestamp' => '1342721885',
        'origname' => 'BUSHWICK_12 copy.jpg',
      ),
      '19' => array(
        'fid' => '18911',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BUSHWICK_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/BUSHWICK_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '366089',
        'status' => '1',
        'timestamp' => '1342722336',
        'origname' => 'BUSHWICK_13 copy.jpg',
      ),
    ),
    'path' => 'stories/studio-bushwick',
    'tags' => array(
      '1' => array(
        '806' => array(
          'tid' => '806',
          'vid' => '1',
          'name' => 'insight',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '805' => array(
          'tid' => '805',
          'vid' => '1',
          'name' => 'koto',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '802' => array(
          'tid' => '802',
          'vid' => '1',
          'name' => 'levi\'s',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '804' => array(
          'tid' => '804',
          'vid' => '1',
          'name' => 'obey',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '803' => array(
          'tid' => '803',
          'vid' => '1',
          'name' => 'sonoma',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '167' => array(
          'tid' => '167',
          'vid' => '1',
          'name' => 'Urban Outfitters',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '155' => array(
          'tid' => '155',
          'vid' => '1',
          'name' => 'ZARA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2700' => array(
          'tid' => '2700',
          'vid' => '5',
          'name' => 'SAM DEVRIES',
          'description' => 'http://www.samdevriesphoto.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'insight, koto, levi\'s, obey, sonoma, Urban Outfitters, ZARA',
        '4' => 'men',
        '5' => 'SAM DEVRIES',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
