array(
  array(
    'nid' => '4107',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1342800235',
    'changed' => '1403838165',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4107',
    'revision_uid' => '1',
    'title' => 'Today In Briefs ',
    'body' => '<p>
	Unexpected unders.<br />
	Exclusive photography by <a href="http://www.rodneyrayphotography.com/">Rodney Ray</a>.&nbsp;<br />
	Model - Anthony Stephens at LA Models.</p>
',
    'teaser' => '<p>
	Unexpected unders.<br />
	Exclusive photography by <a href="http://www.rodneyrayphotography.com/">Rodney Ray</a>.&nbsp;<br />
	Model - Anthony Stephens at LA Models.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838165',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.rodneyrayphotography.com/">RODNEY RAY</a></p>
<p>
	<br />
	FASHION EDITOR<br />
	DERRIC LOWE<br />
	&nbsp;</p>
<p>
	GROOMING<br />
	<a href="http://www.jamiedorman.com/">JAMIE DORMAN</a></p>
<p>
	MODEL<br />
	ANTHONY STEPHENS<br />
	AT LA MODELS</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18917',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIBONE FINAL_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIBONE FINAL_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1272795',
        'status' => '1',
        'timestamp' => '1342810930',
        'origname' => 'TIBONE FINAL_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '18919',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIBONE FINAL_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIBONE FINAL_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1216170',
        'status' => '1',
        'timestamp' => '1342810945',
        'origname' => 'TIBONE FINAL_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '18920',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIBONE FINAL_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIBONE FINAL_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '758707',
        'status' => '1',
        'timestamp' => '1342810952',
        'origname' => 'TIBONE FINAL_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '18922',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIBONE FINAL_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIBONE FINAL_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '591375',
        'status' => '1',
        'timestamp' => '1342810963',
        'origname' => 'TIBONE FINAL_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '18924',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIBONE FINAL_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIBONE FINAL_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '952719',
        'status' => '1',
        'timestamp' => '1342810972',
        'origname' => 'TIBONE FINAL_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '18925',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIBONE FINAL_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIBONE FINAL_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '890413',
        'status' => '1',
        'timestamp' => '1342810980',
        'origname' => 'TIBONE FINAL_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '18927',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIBONE FINAL_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIBONE FINAL_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '586933',
        'status' => '1',
        'timestamp' => '1342810994',
        'origname' => 'TIBONE FINAL_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '18929',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIBONE FINAL_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIBONE FINAL_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74936',
        'status' => '1',
        'timestamp' => '1342811004',
        'origname' => 'TIBONE FINAL_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '18930',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIBONE FINAL_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIBONE FINAL_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '989874',
        'status' => '1',
        'timestamp' => '1342811013',
        'origname' => 'TIBONE FINAL_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '18931',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIBONE FINAL_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIBONE FINAL_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '964945',
        'status' => '1',
        'timestamp' => '1342811027',
        'origname' => 'TIBONE FINAL_11 copy.jpg',
      ),
    ),
    'path' => 'stories/today-briefs',
    'tags' => array(
      '1' => array(
        '470' => array(
          'tid' => '470',
          'vid' => '1',
          'name' => 'Hi Panda',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '808' => array(
          'tid' => '808',
          'vid' => '1',
          'name' => 'lancioni',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '807' => array(
          'tid' => '807',
          'vid' => '1',
          'name' => 'lawman',
          'description' => 'http://www.kewalkiran.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2545' => array(
          'tid' => '2545',
          'vid' => '5',
          'name' => 'RODNEY RAY',
          'description' => 'http://www.RodneyRayPhotography.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Hi Panda, lancioni, lawman',
        '4' => 'men',
        '5' => 'RODNEY RAY',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
