array(
  array(
    'nid' => '4109',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1343244162',
    'changed' => '1403838165',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4109',
    'revision_uid' => '1',
    'title' => 'Today In Briefs 4',
    'body' => '<p>
	Unexpected unders.<br />
	Exclusive photography by <a href="http://www.michaellohrphotography.com/">Michael Lohr</a>.&nbsp;<br />
	Model - Chad Taylor at City.</p>
',
    'teaser' => '<p>
	Unexpected unders.<br />
	Exclusive photography by <a href="http://www.michaellohrphotography.com/">Michael Lohr</a>.&nbsp;<br />
	Model - Chad Taylor at City.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838165',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.michaellohrphotography.com/">MICHAEL LOHR</a></p>
<p>
	<br />
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	MODEL<br />
	CHAD TAYLOR<br />
	AT CITY</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18934',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB3_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB3_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86603',
        'status' => '1',
        'timestamp' => '1342812077',
        'origname' => 'TIB3_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '19088',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '766337',
        'status' => '1',
        'timestamp' => '1343067252',
        'origname' => 'TIB4 copy.jpg',
      ),
      '2' => array(
        'fid' => '18938',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB3_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB3_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81342',
        'status' => '1',
        'timestamp' => '1342812094',
        'origname' => 'TIB3_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '18940',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB3_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB3_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '849340',
        'status' => '1',
        'timestamp' => '1342812102',
        'origname' => 'TIB3_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '18942',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB3_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB3_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '839585',
        'status' => '1',
        'timestamp' => '1342812112',
        'origname' => 'TIB3_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '18944',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB3_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB3_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '831997',
        'status' => '1',
        'timestamp' => '1342812119',
        'origname' => 'TIB3_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '18946',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB3_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB3_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '701168',
        'status' => '1',
        'timestamp' => '1342812128',
        'origname' => 'TIB3_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '18948',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB3_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB3_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '665291',
        'status' => '1',
        'timestamp' => '1342812137',
        'origname' => 'TIB3_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '18950',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB3_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB3_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1040744',
        'status' => '1',
        'timestamp' => '1342812146',
        'origname' => 'TIB3_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '18951',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB3_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB3_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75198',
        'status' => '1',
        'timestamp' => '1342812154',
        'origname' => 'TIB3_11 copy.jpg',
      ),
    ),
    'path' => 'stories/today-briefs-4',
    'tags' => array(
      '1' => array(
        '811' => array(
          'tid' => '811',
          'vid' => '1',
          'name' => 'bodyaware',
          'description' => 'http://bodyaware.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2502' => array(
          'tid' => '2502',
          'vid' => '5',
          'name' => 'Michael Lohr',
          'description' => 'http://www.michaellohrphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'bodyaware',
        '4' => 'men',
        '5' => 'Michael Lohr',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
