array(
  array(
    'nid' => '4111',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1343068313',
    'changed' => '1403838165',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4111',
    'revision_uid' => '1',
    'title' => 'Today In Briefs 2',
    'body' => '<p>
	Unexpected unders.<br />
	Exclusive photography by Jose Corella.&nbsp;<br />
	Model - Brandin Whitker.</p>
',
    'teaser' => '<p>
	Unexpected unders.<br />
	Exclusive photography by Jose Corella.&nbsp;<br />
	Model - Brandin Whitker.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838165',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	JOSE CORELLA</p>
<p>
	<br />
	FASHION EDITOR<br />
	DERRIC LOWE<br />
	&nbsp;</p>
<p>
	MAKEUP<br />
	NOELLE CAMACHO MURRAY</p>
<p>
	HAIR<br />
	LUIS SOLIS</p>
<p>
	MODEL<br />
	BRANDIN WHITKER</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '18954',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB2_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB2_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87135',
        'status' => '1',
        'timestamp' => '1342812615',
        'origname' => 'TIB2_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '19087',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '642195',
        'status' => '1',
        'timestamp' => '1343066677',
        'origname' => 'TIB2 copy.jpg',
      ),
      '2' => array(
        'fid' => '18958',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB2_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB2_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '591226',
        'status' => '1',
        'timestamp' => '1342812631',
        'origname' => 'TIB2_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '18960',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB2_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB2_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '582834',
        'status' => '1',
        'timestamp' => '1342812640',
        'origname' => 'TIB2_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '18962',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB2_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB2_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '943368',
        'status' => '1',
        'timestamp' => '1342812649',
        'origname' => 'TIB2_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '18964',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB2_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB2_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '941414',
        'status' => '1',
        'timestamp' => '1342812658',
        'origname' => 'TIB2_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '18966',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB2_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB2_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '637184',
        'status' => '1',
        'timestamp' => '1342812666',
        'origname' => 'TIB2_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '18968',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB2_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB2_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '657982',
        'status' => '1',
        'timestamp' => '1342812675',
        'origname' => 'TIB2_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '18969',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB2_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB2_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '932519',
        'status' => '1',
        'timestamp' => '1342812682',
        'origname' => 'TIB2_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '18970',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TIB2_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Jul/TIB2_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '454635',
        'status' => '1',
        'timestamp' => '1342812692',
        'origname' => 'TIB2_11 copy.jpg',
      ),
    ),
    'path' => 'stories/today-briefs-2',
    'tags' => array(
      '5' => array(
        '2701' => array(
          'tid' => '2701',
          'vid' => '5',
          'name' => 'JOSE CORELLA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '810' => array(
          'tid' => '810',
          'vid' => '1',
          'name' => 'Under',
          'description' => 'http://www.underunderwear.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'JOSE CORELLA',
        '4' => 'men',
        '1' => 'Under',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
