array(
  array(
    'nid' => '4149',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1345655530',
    'changed' => '1403838163',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4149',
    'revision_uid' => '1',
    'title' => 'Ruben Amen',
    'body' => '<p>
	Rapid about Ruben.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.&nbsp;<br />
	&nbsp;</p>
',
    'teaser' => '<p>
	Rapid about Ruben.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.&nbsp;<br />
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1403838163',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://darrenblackphotography.com/">DARREN BLACK</a></p>
<p>
	&nbsp;</p>
<p>
	REPRESENTED<br />
	BY AMCK</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '19656',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note Ruben_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/Note Ruben_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '550891',
        'status' => '1',
        'timestamp' => '1344618623',
        'origname' => 'Note Ruben_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '19657',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note Ruben_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/Note Ruben_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '582603',
        'status' => '1',
        'timestamp' => '1344618634',
        'origname' => 'Note Ruben_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '19659',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note Ruben_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/Note Ruben_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '546981',
        'status' => '1',
        'timestamp' => '1344618647',
        'origname' => 'Note Ruben_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '19661',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note Ruben_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/Note Ruben_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '520308',
        'status' => '1',
        'timestamp' => '1344618656',
        'origname' => 'Note Ruben_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '19663',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note Ruben_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/Note Ruben_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '590222',
        'status' => '1',
        'timestamp' => '1344618665',
        'origname' => 'Note Ruben_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '19665',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note Ruben_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/Note Ruben_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81256',
        'status' => '1',
        'timestamp' => '1344618674',
        'origname' => 'Note Ruben_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '19667',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note Ruben_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/Note Ruben_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '482305',
        'status' => '1',
        'timestamp' => '1344618690',
        'origname' => 'Note Ruben_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '19669',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note Ruben_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/Note Ruben_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '373784',
        'status' => '1',
        'timestamp' => '1344618702',
        'origname' => 'Note Ruben_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '19670',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note Ruben_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/Note Ruben_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '327874',
        'status' => '1',
        'timestamp' => '1344618712',
        'origname' => 'Note Ruben_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '19671',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Note Ruben_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/Note Ruben_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '222145',
        'status' => '1',
        'timestamp' => '1344618723',
        'origname' => 'Note Ruben_11 copy.jpg',
      ),
    ),
    'path' => 'stories/ruben-amen',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
        '4' => 'men',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
