array(
  array(
    'nid' => '4157',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1346174563',
    'changed' => '1403838163',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4157',
    'revision_uid' => '1',
    'title' => 'Sweat Shop',
    'body' => '<p>
	Get sweatin&#39;.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.&nbsp;<br />
	Model - Nathan.</p>
',
    'teaser' => '<p>
	Get sweatin&#39;.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.&nbsp;<br />
	Model - Nathan.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838163',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://darrenblackphotography.com/">DARREN BLACK</a></p>
<p>
	STYLING<br />
	ASH HILL</p>
<p>
	GROOMING<br />
	VICTORIA BOND</p>
<p>
	HAIR<br />
	JOHNNY MACFERSON</p>
<p>
	MODEL<br />
	NATHAN</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '19828',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'STYLE-template-CS5.5TEST_2.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/STYLE-template-CS5.5TEST_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '218902',
        'status' => '1',
        'timestamp' => '1346174464',
        'origname' => 'STYLE-template-CS5.5TEST_2.jpg',
      ),
      '1' => array(
        'fid' => '19831',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'STYLE-template-CS5.5TEST_3.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/STYLE-template-CS5.5TEST_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '143882',
        'status' => '1',
        'timestamp' => '1346174476',
        'origname' => 'STYLE-template-CS5.5TEST_3.jpg',
      ),
      '2' => array(
        'fid' => '19833',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'STYLE-template-CS5.5TEST_4.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/STYLE-template-CS5.5TEST_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '175368',
        'status' => '1',
        'timestamp' => '1346174486',
        'origname' => 'STYLE-template-CS5.5TEST_4.jpg',
      ),
      '3' => array(
        'fid' => '19835',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'STYLE-template-CS5.5TEST_5.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/STYLE-template-CS5.5TEST_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91845',
        'status' => '1',
        'timestamp' => '1346174496',
        'origname' => 'STYLE-template-CS5.5TEST_5.jpg',
      ),
      '4' => array(
        'fid' => '19837',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'STYLE-template-CS5.5TEST_6.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/STYLE-template-CS5.5TEST_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '111758',
        'status' => '1',
        'timestamp' => '1346174507',
        'origname' => 'STYLE-template-CS5.5TEST_6.jpg',
      ),
      '5' => array(
        'fid' => '19839',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'STYLE-template-CS5.5TEST_7.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/STYLE-template-CS5.5TEST_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141626',
        'status' => '1',
        'timestamp' => '1346174518',
        'origname' => 'STYLE-template-CS5.5TEST_7.jpg',
      ),
      '6' => array(
        'fid' => '19841',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'STYLE-template-CS5.5TEST_8.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/STYLE-template-CS5.5TEST_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109555',
        'status' => '1',
        'timestamp' => '1346174530',
        'origname' => 'STYLE-template-CS5.5TEST_8.jpg',
      ),
      '7' => array(
        'fid' => '19843',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'STYLE-template-CS5.5TEST_9.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/STYLE-template-CS5.5TEST_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124146',
        'status' => '1',
        'timestamp' => '1346174540',
        'origname' => 'STYLE-template-CS5.5TEST_9.jpg',
      ),
      '8' => array(
        'fid' => '19845',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'STYLE-template-CS5.5TEST_10.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/STYLE-template-CS5.5TEST_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '181522',
        'status' => '1',
        'timestamp' => '1346174549',
        'origname' => 'STYLE-template-CS5.5TEST_10.jpg',
      ),
      '9' => array(
        'fid' => '19846',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'STYLE-template-CS5.5TEST_11.jpg',
        'filepath' => 'files/fmag_story/2012/Aug/STYLE-template-CS5.5TEST_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '141623',
        'status' => '1',
        'timestamp' => '1346174558',
        'origname' => 'STYLE-template-CS5.5TEST_11.jpg',
      ),
    ),
    'path' => 'stories/sweat-shop',
    'tags' => array(
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Darren Black',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
