array(
  array(
    'nid' => '4189',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1349203654',
    'changed' => '1403838162',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4189',
    'revision_uid' => '1',
    'title' => 'Big Bear Weekend',
    'body' => '<p>
	Get up and go.<br />
	Exclusive photography by Fidel Gonzales.<br />
	Models - Channce Condit at NTA &amp; Charlie Shades at LA Models.</p>
',
    'teaser' => '<p>
	Get up and go.<br />
	Exclusive photography by Fidel Gonzales.<br />
	Models - Channce Condit at NTA &amp; Charlie Shades at LA Models.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838162',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	FIDEL GONZALEZ</p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	STYLING&nbsp;<br />
	REGINALD MICHAEL</p>
<p>
	GROOMING<br />
	FIDEL GONZALEZ</p>
<p>
	HAIR<br />
	BRITTANY RENEE</p>
<p>
	MODELS<br />
	CHANNCE CONDIT<br />
	AT NTA<br />
	CHARLIE SHADES<br />
	AT LA MODELS<br />
	<br />
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '20381',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '152529',
        'status' => '1',
        'timestamp' => '1349203510',
        'origname' => 'BIgBearWeekend_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '20382',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1061017',
        'status' => '1',
        'timestamp' => '1349203518',
        'origname' => 'BIgBearWeekend_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '20384',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1019382',
        'status' => '1',
        'timestamp' => '1349203531',
        'origname' => 'BIgBearWeekend_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '20386',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '955010',
        'status' => '1',
        'timestamp' => '1349203543',
        'origname' => 'BIgBearWeekend_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '20388',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90830',
        'status' => '1',
        'timestamp' => '1349203552',
        'origname' => 'BIgBearWeekend_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '20390',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1451050',
        'status' => '1',
        'timestamp' => '1349203561',
        'origname' => 'BIgBearWeekend_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '20392',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '570131',
        'status' => '1',
        'timestamp' => '1349203569',
        'origname' => 'BIgBearWeekend_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '20394',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '790690',
        'status' => '1',
        'timestamp' => '1349203579',
        'origname' => 'BIgBearWeekend_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '20396',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '871808',
        'status' => '1',
        'timestamp' => '1349203594',
        'origname' => 'BIgBearWeekend_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '20398',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1204370',
        'status' => '1',
        'timestamp' => '1349203604',
        'origname' => 'BIgBearWeekend_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '20400',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '751086',
        'status' => '1',
        'timestamp' => '1349203613',
        'origname' => 'BIgBearWeekend_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '20402',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '197640',
        'status' => '1',
        'timestamp' => '1349203624',
        'origname' => 'BIgBearWeekend_13 copy.jpg',
      ),
      '12' => array(
        'fid' => '20403',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '814191',
        'status' => '1',
        'timestamp' => '1349203634',
        'origname' => 'BIgBearWeekend_14 copy.jpg',
      ),
      '13' => array(
        'fid' => '20404',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'BIgBearWeekend_15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/BIgBearWeekend_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1471100',
        'status' => '1',
        'timestamp' => '1349203646',
        'origname' => 'BIgBearWeekend_15 copy.jpg',
      ),
    ),
    'path' => 'stories/big-bear-weekend',
    'tags' => array(
      '1' => array(
        '904' => array(
          'tid' => '904',
          'vid' => '1',
          'name' => 'cole haan',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '106' => array(
          'tid' => '106',
          'vid' => '1',
          'name' => 'JEAN PAUL GAULTIER',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '82' => array(
          'tid' => '82',
          'vid' => '1',
          'name' => 'JOHN VARVATOS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '903' => array(
          'tid' => '903',
          'vid' => '1',
          'name' => 'raven denim',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '569' => array(
          'tid' => '569',
          'vid' => '1',
          'name' => 'tom ford',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '537' => array(
          'tid' => '537',
          'vid' => '1',
          'name' => 'VINCE',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '759' => array(
          'tid' => '759',
          'vid' => '1',
          'name' => 'ysl',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '155' => array(
          'tid' => '155',
          'vid' => '1',
          'name' => 'ZARA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2712' => array(
          'tid' => '2712',
          'vid' => '5',
          'name' => 'FIDEL GONZALEZ',
          'description' => 'http://xxfidelxx.wix.com/74',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'cole haan, JEAN PAUL GAULTIER, JOHN VARVATOS, raven denim, tom ford, VINCE, ysl, ZARA',
        '5' => 'FIDEL GONZALEZ',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
