array(
  array(
    'nid' => '4191',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1349445067',
    'changed' => '1406002209',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4191',
    'revision_uid' => '1',
    'title' => 'Decked Out',
    'body' => '<p>
	Poolish Girl.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.<br />
	Model - Charlotte Pallister at Select.<br />
	Location courtesy of <a href="http://www.thespringshotel.com/">The Springs Hotel</a>.</p>
',
    'teaser' => '<p>
	Poolish Girl.<br />
	Exclusive photography by <a href="http://darrenblackphotography.com/">Darren Black</a>.<br />
	Model - Charlotte Pallister at Select.<br />
	Location courtesy of <a href="http://www.thespringshotel.com/">The Springs Hotel</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1406002209',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://darrenblackphotography.com/">DARREN BLACK</a></p>
<p>
	STYLING&nbsp;<br />
	ASH HILL</p>
<p>
	MAKEUP<br />
	VICTORIA BOND<br />
	USING MAC</p>
<p>
	HAIR<br />
	JOHNNY MACPHERSON</p>
<p>
	LOCATION COURTESY OF&nbsp;<br />
	<a href="http://www.thespringshotel.com/">THE SPRINGS HOTEL</a></p>
<p>
	MODEL<br />
	CHARLOTTE PALLISTER<br />
	AT SELECT<br />
	<br />
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '20406',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '936110',
        'status' => '1',
        'timestamp' => '1349444909',
        'origname' => 'DeckedOut_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '20408',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '626860',
        'status' => '1',
        'timestamp' => '1349444920',
        'origname' => 'DeckedOut_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '20412',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_4 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '847109',
        'status' => '1',
        'timestamp' => '1349444939',
        'origname' => 'DeckedOut_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '20414',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '934434',
        'status' => '1',
        'timestamp' => '1349444948',
        'origname' => 'DeckedOut_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '20416',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '879740',
        'status' => '1',
        'timestamp' => '1349444956',
        'origname' => 'DeckedOut_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '20418',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '727221',
        'status' => '1',
        'timestamp' => '1349444967',
        'origname' => 'DeckedOut_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '20419',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89927',
        'status' => '1',
        'timestamp' => '1349444973',
        'origname' => 'DeckedOut_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '20421',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '822160',
        'status' => '1',
        'timestamp' => '1349444991',
        'origname' => 'DeckedOut_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '20423',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '564700',
        'status' => '1',
        'timestamp' => '1349445002',
        'origname' => 'DeckedOut_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '20425',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '387953',
        'status' => '1',
        'timestamp' => '1349445012',
        'origname' => 'DeckedOut_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '20427',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1051167',
        'status' => '1',
        'timestamp' => '1349445024',
        'origname' => 'DeckedOut_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '20429',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '934452',
        'status' => '1',
        'timestamp' => '1349445038',
        'origname' => 'DeckedOut_13 copy.jpg',
      ),
      '12' => array(
        'fid' => '20430',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '748800',
        'status' => '1',
        'timestamp' => '1349445051',
        'origname' => 'DeckedOut_14 copy.jpg',
      ),
      '13' => array(
        'fid' => '20431',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DeckedOut_15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DeckedOut_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '695661',
        'status' => '1',
        'timestamp' => '1349445063',
        'origname' => 'DeckedOut_15 copy.jpg',
      ),
    ),
    'path' => 'stories/decked-out',
    'tags' => array(
      '1' => array(
        '129' => array(
          'tid' => '129',
          'vid' => '1',
          'name' => 'American Apparel',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '838' => array(
          'tid' => '838',
          'vid' => '1',
          'name' => 'asos',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '916' => array(
          'tid' => '916',
          'vid' => '1',
          'name' => 'beyond vintage',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '776' => array(
          'tid' => '776',
          'vid' => '1',
          'name' => 'nike',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2134' => array(
          'tid' => '2134',
          'vid' => '4',
          'name' => 'bikini',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2129' => array(
          'tid' => '2129',
          'vid' => '4',
          'name' => 'swimwear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2046' => array(
          'tid' => '2046',
          'vid' => '5',
          'name' => 'Darren Black',
          'description' => 'http://darrenblackphotography.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'American Apparel, asos, beyond vintage, nike',
        '4' => 'bikini, swimwear, women',
        '5' => 'Darren Black',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
