array(
  array(
    'nid' => '4193',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1349456293',
    'changed' => '1403838162',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4193',
    'revision_uid' => '1',
    'title' => 'Two For The Road',
    'body' => '<p>
	Autumnal Dandies.<br />
	Exclusive photography by <a href="http://mrtphotograph.viewbook.com/">Marc Tousignant</a>.<br />
	Models - Marco &amp; Mathieu Lobaton at Click.</p>
',
    'teaser' => '<p>
	Autumnal Dandies.<br />
	Exclusive photography by <a href="http://mrtphotograph.viewbook.com/">Marc Tousignant</a>.<br />
	Models - Marco &amp; Mathieu Lobaton at Click.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838162',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://mrtphotograph.viewbook.com/">MARC TOUSIGNANT</a></p>
<p>
	FASHION EDITOR<br />
	DERRIC LOWE</p>
<p>
	STYLING&nbsp;<br />
	<a href="http://gracestyle.net/">JAMIE GRACE</a><br />
	AT WILHELMINA CREATIVE</p>
<p>
	GROOMING<br />
	ROY LIU</p>
<p>
	HAIR<br />
	D&#39;ANGELO THOMSON<br />
	AT WILHELMINA CREATIVE</p>
<p>
	MODEL<br />
	MARCO &amp; MATHIEU LOBATON<br />
	AT CLICK<br />
	<br />
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '20492',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '148494',
        'status' => '1',
        'timestamp' => '1349812411',
        'origname' => 'TwoForTheRoad copy.jpg',
      ),
      '1' => array(
        'fid' => '20436',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1135325',
        'status' => '1',
        'timestamp' => '1349456092',
        'origname' => 'TwoForTheRoad_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '20438',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '883808',
        'status' => '1',
        'timestamp' => '1349456099',
        'origname' => 'TwoForTheRoad_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '20440',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '876673',
        'status' => '1',
        'timestamp' => '1349456108',
        'origname' => 'TwoForTheRoad_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '20442',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1017057',
        'status' => '1',
        'timestamp' => '1349456116',
        'origname' => 'TwoForTheRoad_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '20444',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1040058',
        'status' => '1',
        'timestamp' => '1349456124',
        'origname' => 'TwoForTheRoad_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '20446',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '989649',
        'status' => '1',
        'timestamp' => '1349456133',
        'origname' => 'TwoForTheRoad_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '20447',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '979873',
        'status' => '1',
        'timestamp' => '1349456141',
        'origname' => 'TwoForTheRoad_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '20449',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '878880',
        'status' => '1',
        'timestamp' => '1349456155',
        'origname' => 'TwoForTheRoad_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '20451',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96128',
        'status' => '1',
        'timestamp' => '1349456164',
        'origname' => 'TwoForTheRoad_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '20454',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '875356',
        'status' => '1',
        'timestamp' => '1349456212',
        'origname' => 'TwoForTheRoad_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '20455',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '810863',
        'status' => '1',
        'timestamp' => '1349456231',
        'origname' => 'TwoForTheRoad_13 copy.jpg',
      ),
      '12' => array(
        'fid' => '20457',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '606047',
        'status' => '1',
        'timestamp' => '1349456243',
        'origname' => 'TwoForTheRoad_14 copy.jpg',
      ),
      '13' => array(
        'fid' => '20459',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107716',
        'status' => '1',
        'timestamp' => '1349456253',
        'origname' => 'TwoForTheRoad_15 copy.jpg',
      ),
      '14' => array(
        'fid' => '20461',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_16 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_16 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1043229',
        'status' => '1',
        'timestamp' => '1349456262',
        'origname' => 'TwoForTheRoad_16 copy.jpg',
      ),
      '15' => array(
        'fid' => '20463',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_17 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_17 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '953334',
        'status' => '1',
        'timestamp' => '1349456271',
        'origname' => 'TwoForTheRoad_17 copy.jpg',
      ),
      '16' => array(
        'fid' => '20465',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_18 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_18 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '85859',
        'status' => '1',
        'timestamp' => '1349456278',
        'origname' => 'TwoForTheRoad_18 copy.jpg',
      ),
      '17' => array(
        'fid' => '20466',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'TwoForTheRoad_19 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/TwoForTheRoad_19 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '732877',
        'status' => '1',
        'timestamp' => '1349456287',
        'origname' => 'TwoForTheRoad_19 copy.jpg',
      ),
    ),
    'path' => 'stories/two-road',
    'tags' => array(
      '5' => array(
        '2713' => array(
          'tid' => '2713',
          'vid' => '5',
          'name' => 'MARC TOUSIGNANT',
          'description' => 'http://mrtphotograph.viewbook.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '917' => array(
          'tid' => '917',
          'vid' => '1',
          'name' => 'william watson',
          'description' => 'http://store.williamwatsonnyc.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'MARC TOUSIGNANT',
        '4' => 'men',
        '1' => 'william watson',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
