array(
  array(
    'nid' => '4195',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1349806598',
    'changed' => '1403838422',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4195',
    'revision_uid' => '1',
    'title' => 'Dress Impressions',
    'body' => '<p>
	Dress extras.<br />
	Exclusive photography by <a href="http://www.mrkmfoto.com/">Marko Mijailovic</a>.<br />
	Model - Leigh Hoby at Ford.</p>
',
    'teaser' => '<p>
	Dress extras.<br />
	Exclusive photography by <a href="http://www.mrkmfoto.com/">Marko Mijailovic</a>.<br />
	Model - Leigh Hoby at Ford.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838422',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.mrkmfoto.com/">MARKO MIJAILOVIC</a></p>
<p>
	STYLING&nbsp;<br />
	AMARSANA GENDUNOVA<br />
	AT JUDY INC</p>
<p>
	MAKEUP<br />
	ANNA BARSEGHIAN<br />
	AT FORD</p>
<p>
	MODEL<br />
	LEIGH HOBY<br />
	AT FORD<br />
	<br />
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '20469',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '958538',
        'status' => '1',
        'timestamp' => '1349806440',
        'origname' => 'DressImpressions_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '20490',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '126282',
        'status' => '1',
        'timestamp' => '1349810779',
        'origname' => 'DressImpressions_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '20472',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '107628',
        'status' => '1',
        'timestamp' => '1349806465',
        'origname' => 'DressImpressions_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '20474',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '614713',
        'status' => '1',
        'timestamp' => '1349806477',
        'origname' => 'DressImpressions_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '20476',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80146',
        'status' => '1',
        'timestamp' => '1349806488',
        'origname' => 'DressImpressions_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '20477',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '915374',
        'status' => '1',
        'timestamp' => '1349806506',
        'origname' => 'DressImpressions_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '20488',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '79545',
        'status' => '1',
        'timestamp' => '1349806978',
        'origname' => 'DressImpressions_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '20489',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '622623',
        'status' => '1',
        'timestamp' => '1349806986',
        'origname' => 'DressImpressions_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '20482',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '80174',
        'status' => '1',
        'timestamp' => '1349806551',
        'origname' => 'DressImpressions_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '20483',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1105081',
        'status' => '1',
        'timestamp' => '1349806562',
        'origname' => 'DressImpressions_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '20485',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '707309',
        'status' => '1',
        'timestamp' => '1349806577',
        'origname' => 'DressImpressions_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '20486',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DressImpressions_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/DressImpressions_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '579458',
        'status' => '1',
        'timestamp' => '1349806589',
        'origname' => 'DressImpressions_13 copy.jpg',
      ),
    ),
    'path' => 'stories/dress-impressions',
    'tags' => array(
      '1' => array(
        '919' => array(
          'tid' => '919',
          'vid' => '1',
          'name' => 'bcbg maz azria',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '234' => array(
          'tid' => '234',
          'vid' => '1',
          'name' => 'GIUSEPPE ZANOTTI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '918' => array(
          'tid' => '918',
          'vid' => '1',
          'name' => 'greta constantine',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '859' => array(
          'tid' => '859',
          'vid' => '1',
          'name' => 'malene birger',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2714' => array(
          'tid' => '2714',
          'vid' => '5',
          'name' => 'MARKO MIJAILOVIC',
          'description' => 'http://www.mrkmfoto.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'bcbg maz azria, GIUSEPPE ZANOTTI, greta constantine, malene birger',
        '5' => 'MARKO MIJAILOVIC',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
