array(
  array(
    'nid' => '4216',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1351169101',
    'changed' => '1403838422',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4216',
    'revision_uid' => '1',
    'title' => 'Creeper',
    'body' => '<p>
	Who&#39;s that creepin&#39; around?<br />
	Exclusive photography by <a href="http://www.katandduck.com/">Kat + Duck</a>.<br />
	Model - Kate &amp; Oona Chanel at Red.</p>
',
    'teaser' => '<p>
	Who&#39;s that creepin&#39; around?<br />
	Exclusive photography by <a href="http://www.katandduck.com/">Kat + Duck</a>.<br />
	Model - Kate &amp; Oona Chanel at Red.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838422',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.katandduck.com/">KAT + DUCK</a></p>
<p>
	STYLING&nbsp;<br />
	ANGELINA VIVACE</p>
<p>
	HAIR<br />
	ADAM LIVERMORE</p>
<p>
	MAKEUP<br />
	STEPHANIE PEREZ</p>
<p>
	MODELS<br />
	KATE &amp;<br />
	OONA CHANEL<br />
	AT RED<br />
	<br />
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '20955',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '893403',
        'status' => '1',
        'timestamp' => '1351168836',
        'origname' => 'Creeper_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '20971',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1059749',
        'status' => '1',
        'timestamp' => '1351170381',
        'origname' => 'Creeper_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '20957',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '97869',
        'status' => '1',
        'timestamp' => '1351168856',
        'origname' => 'Creeper_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '20958',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '852354',
        'status' => '1',
        'timestamp' => '1351168872',
        'origname' => 'Creeper_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '20969',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_14 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_14 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '927273',
        'status' => '1',
        'timestamp' => '1351169045',
        'origname' => 'Creeper_14 copy.jpg',
      ),
      '5' => array(
        'fid' => '20970',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_15 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_15 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '992164',
        'status' => '1',
        'timestamp' => '1351169058',
        'origname' => 'Creeper_15 copy.jpg',
      ),
      '6' => array(
        'fid' => '20974',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_8 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87053',
        'status' => '1',
        'timestamp' => '1351171647',
        'origname' => 'Creeper_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '20975',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_9 copy_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '731973',
        'status' => '1',
        'timestamp' => '1351171657',
        'origname' => 'Creeper_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '20961',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '81526',
        'status' => '1',
        'timestamp' => '1351168914',
        'origname' => 'Creeper_8 copy.jpg',
      ),
      '9' => array(
        'fid' => '20962',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '964184',
        'status' => '1',
        'timestamp' => '1351168927',
        'origname' => 'Creeper_9 copy.jpg',
      ),
      '10' => array(
        'fid' => '20963',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '86807',
        'status' => '1',
        'timestamp' => '1351168974',
        'origname' => 'Creeper_10 copy.jpg',
      ),
      '11' => array(
        'fid' => '20965',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1117540',
        'status' => '1',
        'timestamp' => '1351168989',
        'origname' => 'Creeper_11 copy.jpg',
      ),
      '12' => array(
        'fid' => '20959',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '96535',
        'status' => '1',
        'timestamp' => '1351168883',
        'origname' => 'Creeper_6 copy.jpg',
      ),
      '13' => array(
        'fid' => '20960',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Creeper_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Creeper_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '775641',
        'status' => '1',
        'timestamp' => '1351168901',
        'origname' => 'Creeper_7 copy.jpg',
      ),
    ),
    'path' => 'stories/creeper',
    'tags' => array(
      '1' => array(
        '947' => array(
          'tid' => '947',
          'vid' => '1',
          'name' => 'bird of prey',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '948' => array(
          'tid' => '948',
          'vid' => '1',
          'name' => 'bod & christensen',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '434' => array(
          'tid' => '434',
          'vid' => '1',
          'name' => 'chromat',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '946' => array(
          'tid' => '946',
          'vid' => '1',
          'name' => 'heather lawton',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '950' => array(
          'tid' => '950',
          'vid' => '1',
          'name' => 'mateo Bijou',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '85' => array(
          'tid' => '85',
          'vid' => '1',
          'name' => 'NORDSTROM',
          'description' => '<a href="http://rstyle.me/n/s82pukw">nordstrom.com</a>',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => array(
            'ext_url' => '',
          ),
          '#_export_node_encode_object' => '1',
        ),
        '949' => array(
          'tid' => '949',
          'vid' => '1',
          'name' => 'TT Collection',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2624' => array(
          'tid' => '2624',
          'vid' => '5',
          'name' => 'KAT + DUCK',
          'description' => 'http://www.katandduck.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'bird of prey, bod & christensen, chromat, heather lawton, mateo Bijou, NORDSTROM, TT Collection',
        '5' => 'KAT + DUCK',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
