array(
  array(
    'nid' => '4220',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1351448447',
    'changed' => '1403838161',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4220',
    'revision_uid' => '1',
    'title' => 'Politic',
    'body' => '<p>
	Fashion is so political.<br />
	Exclusive photography by Leonardo De Angelis.<br />
	Model - Richeli Murari at Q.</p>
',
    'teaser' => '<p>
	Fashion is so political.<br />
	Exclusive photography by Leonardo De Angelis.<br />
	Model - Richeli Murari at Q.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838161',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	LEONARDO DE ANGELIS</p>
<p>
	DIRECTION<br />
	JIM TRZASKA</p>
<p>
	STYLING&nbsp;<br />
	ATHANASIA NICHOLS</p>
<p>
	GROOMING<br />
	BRYCE SCARLETT</p>
<p>
	MODEL<br />
	RICHELI MURARI<br />
	AT Q<br />
	<br />
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '21010',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Politic_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Politic_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '422232',
        'status' => '1',
        'timestamp' => '1351191007',
        'origname' => 'Politic_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '21011',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Politic_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Politic_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '217028',
        'status' => '1',
        'timestamp' => '1351191022',
        'origname' => 'Politic_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '21012',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Politic_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Politic_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109375',
        'status' => '1',
        'timestamp' => '1351191388',
        'origname' => 'Politic_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '21001',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Politic_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Politic_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '220736',
        'status' => '1',
        'timestamp' => '1351189174',
        'origname' => 'Politic_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '21002',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Politic_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Politic_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '180568',
        'status' => '1',
        'timestamp' => '1351189184',
        'origname' => 'Politic_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '21013',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Politic_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Politic_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88500',
        'status' => '1',
        'timestamp' => '1351191407',
        'origname' => 'Politic_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '21004',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Politic_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Politic_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88818',
        'status' => '1',
        'timestamp' => '1351189206',
        'origname' => 'Politic_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '21005',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Politic_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Politic_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '274077',
        'status' => '1',
        'timestamp' => '1351189219',
        'origname' => 'Politic_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '21007',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Politic_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Politic_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '226059',
        'status' => '1',
        'timestamp' => '1351189232',
        'origname' => 'Politic_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '21008',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Politic_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Oct/Politic_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '309338',
        'status' => '1',
        'timestamp' => '1351189240',
        'origname' => 'Politic_11 copy.jpg',
      ),
    ),
    'path' => 'stories/politic',
    'tags' => array(
      '1' => array(
        '953' => array(
          'tid' => '953',
          'vid' => '1',
          'name' => 'american rag',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '38' => array(
          'tid' => '38',
          'vid' => '1',
          'name' => 'club monaco',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '337' => array(
          'tid' => '337',
          'vid' => '1',
          'name' => 'J Crew',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '952' => array(
          'tid' => '952',
          'vid' => '1',
          'name' => 'johnston murphy',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '170' => array(
          'tid' => '170',
          'vid' => '1',
          'name' => 'PAUL SMITH',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '229' => array(
          'tid' => '229',
          'vid' => '1',
          'name' => 'TOPMAN',
          'description' => 'www.topman.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '156' => array(
          'tid' => '156',
          'vid' => '1',
          'name' => 'UNIQLO',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '155' => array(
          'tid' => '155',
          'vid' => '1',
          'name' => 'ZARA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2720' => array(
          'tid' => '2720',
          'vid' => '5',
          'name' => 'LEONARDO DE ANGELIS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'american rag, club monaco, J Crew, johnston murphy, PAUL SMITH, TOPMAN, UNIQLO, ZARA',
        '5' => 'LEONARDO DE ANGELIS',
        '4' => 'men',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
