array(
  array(
    'nid' => '4255',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1352735048',
    'changed' => '1403838421',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4255',
    'revision_uid' => '1',
    'title' => 'Brie Harding',
    'body' => '<p>
	Beautiful Brie.<br />
	Exclusive photography by <a href="http://www.nikolaidevera.com/">Nikolai De Vera</a>.</p>
',
    'teaser' => '<p>
	Beautiful Brie.<br />
	Exclusive photography by <a href="http://www.nikolaidevera.com/">Nikolai De Vera</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838421',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.nikolaidevera.com/">NIKOLAI DE VERA</a></p>
<p>
	STYLING<br />
	JOAQUIN GREGORIA</p>
<p>
	MAKEUP<br />
	DIANA JIMINEZ</p>
<p>
	HAIR<br />
	B NILES<br />
	&nbsp;</p>
<p>
	REPRESENTED<br />
	BY MAJOR</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '21836',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_2.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '34908',
        'status' => '1',
        'timestamp' => '1352734888',
        'origname' => 'NOTE-THIS-BrieHarding_2.jpg',
      ),
      '1' => array(
        'fid' => '21838',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_3.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73404',
        'status' => '1',
        'timestamp' => '1352734897',
        'origname' => 'NOTE-THIS-BrieHarding_3.jpg',
      ),
      '2' => array(
        'fid' => '21840',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_4.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98197',
        'status' => '1',
        'timestamp' => '1352734905',
        'origname' => 'NOTE-THIS-BrieHarding_4.jpg',
      ),
      '3' => array(
        'fid' => '21842',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_5.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '51002',
        'status' => '1',
        'timestamp' => '1352734911',
        'origname' => 'NOTE-THIS-BrieHarding_5.jpg',
      ),
      '4' => array(
        'fid' => '21844',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_6.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74106',
        'status' => '1',
        'timestamp' => '1352734918',
        'origname' => 'NOTE-THIS-BrieHarding_6.jpg',
      ),
      '5' => array(
        'fid' => '21846',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_7.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13279',
        'status' => '1',
        'timestamp' => '1352734925',
        'origname' => 'NOTE-THIS-BrieHarding_7.jpg',
      ),
      '6' => array(
        'fid' => '21855',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_12.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '13068',
        'status' => '1',
        'timestamp' => '1352734968',
        'origname' => 'NOTE-THIS-BrieHarding_12.jpg',
      ),
      '7' => array(
        'fid' => '21856',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_13.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '63990',
        'status' => '1',
        'timestamp' => '1352734981',
        'origname' => 'NOTE-THIS-BrieHarding_13.jpg',
      ),
      '8' => array(
        'fid' => '21848',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_8.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77135',
        'status' => '1',
        'timestamp' => '1352734932',
        'origname' => 'NOTE-THIS-BrieHarding_8.jpg',
      ),
      '9' => array(
        'fid' => '21850',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_9.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '53430',
        'status' => '1',
        'timestamp' => '1352734940',
        'origname' => 'NOTE-THIS-BrieHarding_9.jpg',
      ),
      '10' => array(
        'fid' => '21851',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_10.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68080',
        'status' => '1',
        'timestamp' => '1352734946',
        'origname' => 'NOTE-THIS-BrieHarding_10.jpg',
      ),
      '11' => array(
        'fid' => '21853',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-BrieHarding_11.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-BrieHarding_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '157235',
        'status' => '1',
        'timestamp' => '1352734961',
        'origname' => 'NOTE-THIS-BrieHarding_11.jpg',
      ),
    ),
    'path' => 'stories/brie-harding',
    'tags' => array(
      '1' => array(
        '603' => array(
          'tid' => '603',
          'vid' => '1',
          'name' => 'Nicholas K',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '899' => array(
          'tid' => '899',
          'vid' => '1',
          'name' => 'Tripp NYC',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2547' => array(
          'tid' => '2547',
          'vid' => '5',
          'name' => 'Nikolai de Vera',
          'description' => 'http://www.nikolaidevera.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Nicholas K, Tripp NYC',
        '5' => 'Nikolai de Vera',
        '4' => 'women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
