array(
  array(
    'nid' => '4259',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1353030268',
    'changed' => '1368913423',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4259',
    'revision_uid' => '1',
    'title' => 'Bryce Daniels',
    'body' => '<p>
	Beautiful Bryce.<br />
	Exclusive photography by Michael Franco.</p>
',
    'teaser' => '<p>
	Beautiful Bryce.<br />
	Exclusive photography by Michael Franco.</p>
',
    'log' => '',
    'revision_timestamp' => '1368913423',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	MICHAEL FRANCO</p>
<p>
	STYLING<br />
	DERRIC LOWE</p>
<p>
	REPRESENTED<br />
	BY THE AGENCY</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '21890',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-bryce_2.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-bryce_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '109347',
        'status' => '1',
        'timestamp' => '1353030020',
        'origname' => 'NOTE-THIS-bryce_2.jpg',
      ),
      '1' => array(
        'fid' => '21891',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-bryce_3.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-bryce_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '44331',
        'status' => '1',
        'timestamp' => '1353030031',
        'origname' => 'NOTE-THIS-bryce_3.jpg',
      ),
      '2' => array(
        'fid' => '21892',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-bryce_4.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-bryce_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93749',
        'status' => '1',
        'timestamp' => '1353030078',
        'origname' => 'NOTE-THIS-bryce_4.jpg',
      ),
      '3' => array(
        'fid' => '21893',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-bryce_5.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-bryce_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88826',
        'status' => '1',
        'timestamp' => '1353030092',
        'origname' => 'NOTE-THIS-bryce_5.jpg',
      ),
      '4' => array(
        'fid' => '21894',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-bryce_6.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-bryce_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73154',
        'status' => '1',
        'timestamp' => '1353030109',
        'origname' => 'NOTE-THIS-bryce_6.jpg',
      ),
      '5' => array(
        'fid' => '21895',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-bryce_7.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-bryce_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '77043',
        'status' => '1',
        'timestamp' => '1353030127',
        'origname' => 'NOTE-THIS-bryce_7.jpg',
      ),
      '6' => array(
        'fid' => '21896',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-bryce_8.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-bryce_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '98150',
        'status' => '1',
        'timestamp' => '1353030189',
        'origname' => 'NOTE-THIS-bryce_8.jpg',
      ),
      '7' => array(
        'fid' => '21897',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'NOTE-THIS-bryce_9.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/NOTE-THIS-bryce_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '120308',
        'status' => '1',
        'timestamp' => '1353030227',
        'origname' => 'NOTE-THIS-bryce_9.jpg',
      ),
    ),
    'path' => 'stories/bryce-daniels',
    'tags' => array(
      '5' => array(
        '2465' => array(
          'tid' => '2465',
          'vid' => '5',
          'name' => 'MICHAEL FRANCO',
          'description' => 'http://www.michaelfranco.net/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'MICHAEL FRANCO',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
