array(
  array(
    'nid' => '4265',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1353357734',
    'changed' => '1403838159',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4265',
    'revision_uid' => '1',
    'title' => 'Warming Trends',
    'body' => '<p>
	Warm it up kid.<br />
	Exclusive photography by <a href="http://www.michael-ching.com/">Michael Ching</a>.<br />
	Model - Jed Texas at Fusion.</p>
',
    'teaser' => '<p>
	Warm it up kid.<br />
	Exclusive photography by <a href="http://www.michael-ching.com/">Michael Ching</a>.<br />
	Model - Jed Texas at Fusion.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838159',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.michael-ching.com/">MICHAEL CHING</a></p>
<p>
	DIRECTION<br />
	JUAN CARLOS PARRAS</p>
<p>
	STYLING &amp; CASTING<br />
	GERALDINE LAIZ</p>
<p>
	MAKEU &amp; HAIR<br />
	PAMELA BARRIOS</p>
<p>
	<br />
	GROOMING<br />
	JOVAN CLOWERS</p>
<p>
	MODEL<br />
	JED TEXAS<br />
	AT FUSION</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '21951',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_2.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '291605',
        'status' => '1',
        'timestamp' => '1353357404',
        'origname' => 'Jed_Texas_2.jpg',
      ),
      '1' => array(
        'fid' => '21980',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_3.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '50766',
        'status' => '1',
        'timestamp' => '1353359059',
        'origname' => 'Jed_Texas_3.jpg',
      ),
      '2' => array(
        'fid' => '21955',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_4.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '219706',
        'status' => '1',
        'timestamp' => '1353357424',
        'origname' => 'Jed_Texas_4.jpg',
      ),
      '3' => array(
        'fid' => '21981',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_5.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '266186',
        'status' => '1',
        'timestamp' => '1353359075',
        'origname' => 'Jed_Texas_5.jpg',
      ),
      '4' => array(
        'fid' => '21959',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_6.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19282',
        'status' => '1',
        'timestamp' => '1353357445',
        'origname' => 'Jed_Texas_6.jpg',
      ),
      '5' => array(
        'fid' => '21982',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_7.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '279405',
        'status' => '1',
        'timestamp' => '1353359093',
        'origname' => 'Jed_Texas_7.jpg',
      ),
      '6' => array(
        'fid' => '21962',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_8.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '19085',
        'status' => '1',
        'timestamp' => '1353357468',
        'origname' => 'Jed_Texas_8.jpg',
      ),
      '7' => array(
        'fid' => '21963',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_9.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '226981',
        'status' => '1',
        'timestamp' => '1353357482',
        'origname' => 'Jed_Texas_9.jpg',
      ),
      '8' => array(
        'fid' => '21983',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_10.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '264384',
        'status' => '1',
        'timestamp' => '1353359114',
        'origname' => 'Jed_Texas_10.jpg',
      ),
      '9' => array(
        'fid' => '21984',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_11-2.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_11-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '218762',
        'status' => '1',
        'timestamp' => '1353359127',
        'origname' => 'Jed_Texas_11-2.jpg',
      ),
      '10' => array(
        'fid' => '21967',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_12.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '20398',
        'status' => '1',
        'timestamp' => '1353357517',
        'origname' => 'Jed_Texas_12.jpg',
      ),
      '11' => array(
        'fid' => '21985',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_13.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '289027',
        'status' => '1',
        'timestamp' => '1353359143',
        'origname' => 'Jed_Texas_13.jpg',
      ),
      '12' => array(
        'fid' => '21970',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_14.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '259957',
        'status' => '1',
        'timestamp' => '1353357579',
        'origname' => 'Jed_Texas_14.jpg',
      ),
      '13' => array(
        'fid' => '21971',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_15.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '233647',
        'status' => '1',
        'timestamp' => '1353357590',
        'origname' => 'Jed_Texas_15.jpg',
      ),
      '14' => array(
        'fid' => '21973',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_16.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '247773',
        'status' => '1',
        'timestamp' => '1353357715',
        'origname' => 'Jed_Texas_16.jpg',
      ),
      '15' => array(
        'fid' => '21974',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jed_Texas_17.jpg',
        'filepath' => 'files/fmag_story/2012/Nov/Jed_Texas_17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '124115',
        'status' => '1',
        'timestamp' => '1353357724',
        'origname' => 'Jed_Texas_17.jpg',
      ),
    ),
    'path' => 'stories/warming-trends',
    'tags' => array(
      '1' => array(
        '761' => array(
          'tid' => '761',
          'vid' => '1',
          'name' => 'alexander wang',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1019' => array(
          'tid' => '1019',
          'vid' => '1',
          'name' => 'superdr',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '155' => array(
          'tid' => '155',
          'vid' => '1',
          'name' => 'ZARA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2726' => array(
          'tid' => '2726',
          'vid' => '5',
          'name' => 'MICHAEL CHING',
          'description' => 'http://www.michael-ching.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'alexander wang, superdr, ZARA',
        '4' => 'men',
        '5' => 'MICHAEL CHING',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
