array(
  array(
    'nid' => '4284',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1354734076',
    'changed' => '1406007012',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4284',
    'revision_uid' => '1',
    'title' => 'Dark Side',
    'body' => '<p>
	Dark Lady.<br />
	Exclusive photography by <a href="http://www.jackclarkphoto.com">Jack Clark</a>.<br />
	Model - Alicia at Elite.</p>
',
    'teaser' => '<p>
	Dark Lady.<br />
	Exclusive photography by <a href="http://www.jackclarkphoto.com">Jack Clark</a>.<br />
	Model - Alicia at Elite.</p>
',
    'log' => '',
    'revision_timestamp' => '1406007012',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.jackclarkphoto.com">JACK CLARK</a></p>
<p>
	STYLING<br />
	<a href="http://desilazarova.4ormat.com/">DESI LAZAROVA</a></p>
<p>
	MAKEUP<br />
	<a href="http://www.pengphan.com/">PENG PHAN</a></p>
<p>
	HAIR<br />
	<a href="http://www.haruhideishizaki.com/">HARUHIDE ISIZAKI</a></p>
<p>
	MODEL<br />
	ALICIA<br />
	AT ELITE</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '22278',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_2 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_2 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '425181',
        'status' => '1',
        'timestamp' => '1354733818',
        'origname' => 'DarkSide_2 copy.jpg',
      ),
      '1' => array(
        'fid' => '22279',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_3 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_3 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '406734',
        'status' => '1',
        'timestamp' => '1354733834',
        'origname' => 'DarkSide_3 copy.jpg',
      ),
      '2' => array(
        'fid' => '22280',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_4 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_4 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74928',
        'status' => '1',
        'timestamp' => '1354733847',
        'origname' => 'DarkSide_4 copy.jpg',
      ),
      '3' => array(
        'fid' => '22281',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_5 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_5 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '377090',
        'status' => '1',
        'timestamp' => '1354733867',
        'origname' => 'DarkSide_5 copy.jpg',
      ),
      '4' => array(
        'fid' => '22283',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_6 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_6 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '78081',
        'status' => '1',
        'timestamp' => '1354733885',
        'origname' => 'DarkSide_6 copy.jpg',
      ),
      '5' => array(
        'fid' => '22284',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_7 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_7 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '379389',
        'status' => '1',
        'timestamp' => '1354733895',
        'origname' => 'DarkSide_7 copy.jpg',
      ),
      '6' => array(
        'fid' => '22285',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_8 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_8 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '398559',
        'status' => '1',
        'timestamp' => '1354733913',
        'origname' => 'DarkSide_8 copy.jpg',
      ),
      '7' => array(
        'fid' => '22286',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_9 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_9 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '436658',
        'status' => '1',
        'timestamp' => '1354733925',
        'origname' => 'DarkSide_9 copy.jpg',
      ),
      '8' => array(
        'fid' => '22287',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_10 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_10 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '74930',
        'status' => '1',
        'timestamp' => '1354733956',
        'origname' => 'DarkSide_10 copy.jpg',
      ),
      '9' => array(
        'fid' => '22288',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_11 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_11 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '456175',
        'status' => '1',
        'timestamp' => '1354733971',
        'origname' => 'DarkSide_11 copy.jpg',
      ),
      '10' => array(
        'fid' => '22289',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_12 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_12 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '349921',
        'status' => '1',
        'timestamp' => '1354733986',
        'origname' => 'DarkSide_12 copy.jpg',
      ),
      '11' => array(
        'fid' => '22290',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'DarkSide_13 copy.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/DarkSide_13 copy.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '400606',
        'status' => '1',
        'timestamp' => '1354733998',
        'origname' => 'DarkSide_13 copy.jpg',
      ),
    ),
    'path' => 'stories/dark-side-0',
    'tags' => array(
      '1' => array(
        '761' => array(
          'tid' => '761',
          'vid' => '1',
          'name' => 'alexander wang',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '544' => array(
          'tid' => '544',
          'vid' => '1',
          'name' => 'all saints',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '129' => array(
          'tid' => '129',
          'vid' => '1',
          'name' => 'American Apparel',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2730' => array(
          'tid' => '2730',
          'vid' => '5',
          'name' => 'JACK CLARK',
          'description' => 'http://www.jackclarkphoto.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2137' => array(
          'tid' => '2137',
          'vid' => '4',
          'name' => 'lingerie',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'alexander wang, all saints, American Apparel',
        '5' => 'JACK CLARK',
        '4' => 'lingerie, women',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
