array(
  array(
    'nid' => '4295',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1355446633',
    'changed' => '1403838420',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '4295',
    'revision_uid' => '1',
    'title' => 'Happy Family',
    'body' => '<p>
	All in the family.<br />
	Exclusive photography by <a href="http://www.staycool.it/florian-schmitt-photographer/">Florian Schmitt</a>.<br />
	Models - Catalina, Allesandro &amp; the kids.</p>
',
    'teaser' => '<p>
	All in the family.<br />
	Exclusive photography by <a href="http://www.staycool.it/florian-schmitt-photographer/">Florian Schmitt</a>.<br />
	Models - Catalina, Allesandro &amp; the kids.</p>
',
    'log' => '',
    'revision_timestamp' => '1403838420',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.photofloh.de">FLORIAN SCHMITT</a></p>
<p>
	STYLING<br />
	<a href="http://olimpialiberti.tumblr.com/">OLIMPIA LIBERTI</a></p>
<p>
	HAIR &amp; MAKEUP<br />
	CHYLA CAMACHO</p>
<p>
	MODELS<br />
	CATALINA MAGEE<br />
	ALESSANDRO G FURLAN<br />
	ALINA<br />
	DAKOTA<br />
	DESIREE<br />
	ELEANOR<br />
	LISA<br />
	NASEEM<br />
	SOPHIE<br />
	<br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '22451',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_2.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '157493',
        'status' => '1',
        'timestamp' => '1355187521',
        'origname' => 'Happy-Family_2.jpg',
      ),
      '1' => array(
        'fid' => '22453',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_3.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '196927',
        'status' => '1',
        'timestamp' => '1355187526',
        'origname' => 'Happy-Family_3.jpg',
      ),
      '2' => array(
        'fid' => '22455',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_4.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100262',
        'status' => '1',
        'timestamp' => '1355187537',
        'origname' => 'Happy-Family_4.jpg',
      ),
      '3' => array(
        'fid' => '22457',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_5.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '251639',
        'status' => '1',
        'timestamp' => '1355187545',
        'origname' => 'Happy-Family_5.jpg',
      ),
      '4' => array(
        'fid' => '22459',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_6.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137553',
        'status' => '1',
        'timestamp' => '1355187553',
        'origname' => 'Happy-Family_6.jpg',
      ),
      '5' => array(
        'fid' => '22461',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_7.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131080',
        'status' => '1',
        'timestamp' => '1355187562',
        'origname' => 'Happy-Family_7.jpg',
      ),
      '6' => array(
        'fid' => '22463',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_8.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67125',
        'status' => '1',
        'timestamp' => '1355187570',
        'origname' => 'Happy-Family_8.jpg',
      ),
      '7' => array(
        'fid' => '22465',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_9.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '214775',
        'status' => '1',
        'timestamp' => '1355187582',
        'origname' => 'Happy-Family_9.jpg',
      ),
      '8' => array(
        'fid' => '22467',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_10.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139416',
        'status' => '1',
        'timestamp' => '1355187593',
        'origname' => 'Happy-Family_10.jpg',
      ),
      '9' => array(
        'fid' => '22469',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_11.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137373',
        'status' => '1',
        'timestamp' => '1355187603',
        'origname' => 'Happy-Family_11.jpg',
      ),
      '10' => array(
        'fid' => '22471',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_12.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161410',
        'status' => '1',
        'timestamp' => '1355187611',
        'origname' => 'Happy-Family_12.jpg',
      ),
      '11' => array(
        'fid' => '22472',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Happy-Family_13.jpg',
        'filepath' => 'files/fmag_story/2012/Dec/Happy-Family_13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '147502',
        'status' => '1',
        'timestamp' => '1355187618',
        'origname' => 'Happy-Family_13.jpg',
      ),
    ),
    'path' => 'stories/happy-family',
    'tags' => array(
      '1' => array(
        '1075' => array(
          'tid' => '1075',
          'vid' => '1',
          'name' => 'Adriana Degiorgi',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1073' => array(
          'tid' => '1073',
          'vid' => '1',
          'name' => 'carlo Govanni',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1070' => array(
          'tid' => '1070',
          'vid' => '1',
          'name' => 'carters',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1071' => array(
          'tid' => '1071',
          'vid' => '1',
          'name' => 'chloe',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '1074' => array(
          'tid' => '1074',
          'vid' => '1',
          'name' => 'Gymboree',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '31' => array(
          'tid' => '31',
          'vid' => '1',
          'name' => 'H&M',
          'description' => 'www.hm.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
        '155' => array(
          'tid' => '155',
          'vid' => '1',
          'name' => 'ZARA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '5' => array(
        '2734' => array(
          'tid' => '2734',
          'vid' => '5',
          'name' => 'FLORIAN SCHMITT',
          'description' => 'http://www.photofloh.de',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Adriana Degiorgi, carlo Govanni, carters, chloe, Gymboree, H&M, ZARA',
        '5' => 'FLORIAN SCHMITT',
        '4' => 'men, women',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
