array(
  array(
    'nid' => '5255',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1441713600',
    'changed' => 1447887854,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5255',
    'revision_uid' => '0',
    'title' => 'Threesome',
    'body' => '<p>
	Part two.<br />
	Exclusive photography by <a href="http://www.gabriellerevere.com">Gabrielle Revere</a>.<br />
	Model - Seth Atwell at <a href="http://www.statemgmt.com">State Management</a> &amp; <a href="http://www.plutinogroup.com/">Plutino Toronto</a>.</p>
',
    'teaser' => '<p>
	Part two.<br />
	Exclusive photography by <a href="http://www.gabriellerevere.com">Gabrielle Revere</a>.<br />
	Model - Seth Atwell at <a href="http://www.statemgmt.com">State Management</a> &amp; <a href="http://www.plutinogroup.com/">Plutino Toronto</a>.</p>
',
    'revision_timestamp' => '1441713617',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.gabriellerevere.com">Gabrielle Revere</a> shoots <a href="http://www.statemgmt.com">State Management</a>&#39;s scintillating Seth Atwell in a triad of moods. Styling by <a href="http://honey-artists.com/">Honey Artist&#39;s Joshua Liebman</a> includes <a href="http://www.dior.com/couture/en_int/mens-fashion">Dior Homme</a>, <a href="http://www.viviennewestwood.com/">Vivienne Westwood</a> and <a href="http://michaelbastiannyc.com/">Michael Bastian</a>.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.gabriellerevere.com">Gabrielle Revere</a><br />
	<br />
	STYLING<br />
	<a href="http://honey-artists.com/">Joshua Liebman<br />
	Honey Artists</a></p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	<a href="http://honey-artists.com/">Robert Greene<br />
	Honey Artists</a><br />
	using M.A.C.</p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	<a href="http://honey-artists.com/">Wesley O&rsquo;Meara<br />
	Honey Artists </a><br />
	using AG</p>
<p>
	<br />
	<br />
	MODEL<br />
	Seth Atwell<br />
	<a href="http://www.statemgmt.com">State Management NYC</a><br />
	<a href="http://www.plutinogroup.com/">Plutino Toronto</a></p>
<p>
	&nbsp;</p>
<p>
	LOCATION<br />
	<a href="http://www.milkstudios.com/">MILK STUDIOS</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '39135',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere16.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '39941',
        'status' => '1',
        'timestamp' => '1441550517',
        'origname' => 'Seth-Atwell-Gabrielle-Revere16.jpg',
      ),
      '1' => array(
        'fid' => '39186',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere-edit.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere-edit.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '129747',
        'status' => '1',
        'timestamp' => '1441553082',
        'origname' => 'Seth-Atwell-Gabrielle-Revere-edit.jpg',
      ),
      '2' => array(
        'fid' => '39187',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere-edit2.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere-edit2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76961',
        'status' => '1',
        'timestamp' => '1441553093',
        'origname' => 'Seth-Atwell-Gabrielle-Revere-edit2.jpg',
      ),
      '3' => array(
        'fid' => '39143',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere21.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere21.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68658',
        'status' => '1',
        'timestamp' => '1441550570',
        'origname' => 'Seth-Atwell-Gabrielle-Revere21.jpg',
      ),
      '4' => array(
        'fid' => '39145',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere22.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere22.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '32166',
        'status' => '1',
        'timestamp' => '1441550584',
        'origname' => 'Seth-Atwell-Gabrielle-Revere22.jpg',
      ),
      '5' => array(
        'fid' => '39147',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere23.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere23.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102010',
        'status' => '1',
        'timestamp' => '1441550593',
        'origname' => 'Seth-Atwell-Gabrielle-Revere23.jpg',
      ),
      '6' => array(
        'fid' => '39149',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere24.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere24.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '30997',
        'status' => '1',
        'timestamp' => '1441550602',
        'origname' => 'Seth-Atwell-Gabrielle-Revere24.jpg',
      ),
      '7' => array(
        'fid' => '39151',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere25.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere25.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '149027',
        'status' => '1',
        'timestamp' => '1441550610',
        'origname' => 'Seth-Atwell-Gabrielle-Revere25.jpg',
      ),
      '8' => array(
        'fid' => '39153',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere26.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere26.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '31899',
        'status' => '1',
        'timestamp' => '1441550620',
        'origname' => 'Seth-Atwell-Gabrielle-Revere26.jpg',
      ),
      '9' => array(
        'fid' => '39155',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere27.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere27.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68931',
        'status' => '1',
        'timestamp' => '1441550630',
        'origname' => 'Seth-Atwell-Gabrielle-Revere27.jpg',
      ),
    ),
    'path' => 'stories/threesome-0',
    'tags' => array(
      '1' => array(
        '567' => array(
          'tid' => '567',
          'vid' => '1',
          'name' => 'calvin klein collection',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '373' => array(
          'tid' => '373',
          'vid' => '1',
          'name' => 'dior homme',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2260' => array(
          'tid' => '2260',
          'vid' => '1',
          'name' => 'michael bastian',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '541' => array(
          'tid' => '541',
          'vid' => '1',
          'name' => 'vivienne westwood',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '3268' => array(
          'tid' => '3268',
          'vid' => '4',
          'name' => 'gabrielle revere',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3084' => array(
          'tid' => '3084',
          'vid' => '4',
          'name' => 'plutino',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3269' => array(
          'tid' => '3269',
          'vid' => '4',
          'name' => 'state management',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'calvin klein collection, dior homme, michael bastian, vivienne westwood',
        '4' => 'gabrielle revere, plutino, state management',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => 'afdae1b2-8e48-11e5-859f-234f24c98333',
    'is_new' => FALSE,
    'timestamp' => 1447887854,
    'xmlsitemap' => array(
      'id' => '5255',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5255',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1447887854',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5255',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
