array(
  array(
    'nid' => '5257',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1441800000',
    'changed' => 1447887855,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5257',
    'revision_uid' => '0',
    'title' => 'Threesome',
    'body' => '<p>
	Part three.<br />
	Exclusive photography by <a href="http://www.gabriellerevere.com">Gabrielle Revere</a>.<br />
	Model - Seth Atwell at <a href="http://www.statemgmt.com">State Management</a> &amp; <a href="http://www.plutinogroup.com/">Plutino Toronto</a>.</p>
',
    'teaser' => '<p>
	Part three.<br />
	Exclusive photography by <a href="http://www.gabriellerevere.com">Gabrielle Revere</a>.<br />
	Model - Seth Atwell at <a href="http://www.statemgmt.com">State Management</a> &amp; <a href="http://www.plutinogroup.com/">Plutino Toronto</a>.</p>
',
    'revision_timestamp' => '1441800016',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.gabriellerevere.com">Gabrielle Revere</a> shoots <a href="http://www.statemgmt.com">State Management</a>&#39;s scintillating Seth Atwell in a triad of moods. Styling by <a href="http://honey-artists.com/">Honey Artist&#39;s Joshua Liebman</a> includes <a href="http://www.m-missoni.com/">Missoni</a>, <a href="http://www.viviennewestwood.com/">Vivienne Westwood</a> and <a href="http://www.elleryland.com/">Ellery</a>.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.gabriellerevere.com">Gabrielle Revere</a><br />
	<br />
	STYLING<br />
	<a href="http://honey-artists.com/">Joshua Liebman<br />
	Honey Artists</a></p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	<a href="http://honey-artists.com/">Robert Greene<br />
	Honey Artists</a><br />
	using M.A.C.</p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	<a href="http://honey-artists.com/">Wesley O&rsquo;Meara<br />
	Honey Artists </a><br />
	using AG</p>
<p>
	<br />
	<br />
	MODEL<br />
	Seth Atwell<br />
	<a href="http://www.statemgmt.com">State Management NYC</a><br />
	<a href="http://www.plutinogroup.com/">Plutino Toronto</a></p>
<p>
	&nbsp;</p>
<p>
	LOCATION<br />
	<a href="http://www.milkstudios.com/ ">MILK STUDIOS</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '39157',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere28.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere28.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '39853',
        'status' => '1',
        'timestamp' => '1441550794',
        'origname' => 'Seth-Atwell-Gabrielle-Revere28.jpg',
      ),
      '1' => array(
        'fid' => '39159',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere29.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere29.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '128934',
        'status' => '1',
        'timestamp' => '1441550806',
        'origname' => 'Seth-Atwell-Gabrielle-Revere29.jpg',
      ),
      '2' => array(
        'fid' => '39161',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere30.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere30.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '30750',
        'status' => '1',
        'timestamp' => '1441550814',
        'origname' => 'Seth-Atwell-Gabrielle-Revere30.jpg',
      ),
      '3' => array(
        'fid' => '39163',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere31.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere31.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '143170',
        'status' => '1',
        'timestamp' => '1441550824',
        'origname' => 'Seth-Atwell-Gabrielle-Revere31.jpg',
      ),
      '4' => array(
        'fid' => '39165',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere32.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere32.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '31650',
        'status' => '1',
        'timestamp' => '1441550832',
        'origname' => 'Seth-Atwell-Gabrielle-Revere32.jpg',
      ),
      '5' => array(
        'fid' => '39167',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere33.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere33.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '100135',
        'status' => '1',
        'timestamp' => '1441550841',
        'origname' => 'Seth-Atwell-Gabrielle-Revere33.jpg',
      ),
      '6' => array(
        'fid' => '39169',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere34.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere34.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29084',
        'status' => '1',
        'timestamp' => '1441550849',
        'origname' => 'Seth-Atwell-Gabrielle-Revere34.jpg',
      ),
      '7' => array(
        'fid' => '39171',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere35.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere35.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '56405',
        'status' => '1',
        'timestamp' => '1441550857',
        'origname' => 'Seth-Atwell-Gabrielle-Revere35.jpg',
      ),
      '8' => array(
        'fid' => '39173',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere36.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere36.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '35951',
        'status' => '1',
        'timestamp' => '1441550865',
        'origname' => 'Seth-Atwell-Gabrielle-Revere36.jpg',
      ),
      '9' => array(
        'fid' => '39175',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere37.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere37.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '89495',
        'status' => '1',
        'timestamp' => '1441550873',
        'origname' => 'Seth-Atwell-Gabrielle-Revere37.jpg',
      ),
      '10' => array(
        'fid' => '39177',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere38.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere38.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29771',
        'status' => '1',
        'timestamp' => '1441550883',
        'origname' => 'Seth-Atwell-Gabrielle-Revere38.jpg',
      ),
      '11' => array(
        'fid' => '39179',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere39.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere39.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91785',
        'status' => '1',
        'timestamp' => '1441550891',
        'origname' => 'Seth-Atwell-Gabrielle-Revere39.jpg',
      ),
      '12' => array(
        'fid' => '39181',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere40.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere40.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '30583',
        'status' => '1',
        'timestamp' => '1441550901',
        'origname' => 'Seth-Atwell-Gabrielle-Revere40.jpg',
      ),
      '13' => array(
        'fid' => '39182',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Seth-Atwell-Gabrielle-Revere41.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/Seth-Atwell-Gabrielle-Revere41.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '171327',
        'status' => '1',
        'timestamp' => '1441550910',
        'origname' => 'Seth-Atwell-Gabrielle-Revere41.jpg',
      ),
    ),
    'path' => 'stories/threesome-1',
    'tags' => array(
      '1' => array(
        '1113' => array(
          'tid' => '1113',
          'vid' => '1',
          'name' => 'Ellery',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3271' => array(
          'tid' => '3271',
          'vid' => '1',
          'name' => 'lars anderson',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '93' => array(
          'tid' => '93',
          'vid' => '1',
          'name' => 'MISSONI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '541' => array(
          'tid' => '541',
          'vid' => '1',
          'name' => 'vivienne westwood',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '3268' => array(
          'tid' => '3268',
          'vid' => '4',
          'name' => 'gabrielle revere',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3084' => array(
          'tid' => '3084',
          'vid' => '4',
          'name' => 'plutino',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3269' => array(
          'tid' => '3269',
          'vid' => '4',
          'name' => 'state management',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Ellery, lars anderson, MISSONI, vivienne westwood',
        '4' => 'gabrielle revere, plutino, state management',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => 'b0a7a184-8e48-11e5-859f-234f24c98333',
    'is_new' => FALSE,
    'timestamp' => 1447887855,
    'xmlsitemap' => array(
      'id' => '5257',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5257',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1447887855',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5257',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
