array(
  array(
    'nid' => '5259',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1441910864',
    'changed' => 1447887857,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5259',
    'revision_uid' => '1',
    'title' => 'Focus: Martina Troni by Michael Clifford',
    'body' => '<p>
	The focus is on model Martina Troni.<br />
	Exclusive photography by <a href="http://www.michaelcliffordphoto.com">Michael Clifford</a>.</p>
',
    'teaser' => '<p>
	The focus is on model Martina Troni.<br />
	Exclusive photography by <a href="http://www.michaelcliffordphoto.com">Michael Clifford</a>.</p>
',
    'revision_timestamp' => '1441998937',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.michaelcliffordphoto.com">Michael Clifford</a> essays <a href="http://www.nextmanagement.com/milan">Next Milan</a>&#39;s Martina Troni.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHER<br />
	<a href="http://www.michaelcliffordphoto.com">Michael Clifford</a><br />
	&nbsp;</p>
<p>
	SUBJECT<br />
	Martina Troni</p>
<p>
	&nbsp;</p>
<p>
	AGENCY<br />
	<a href="http://www.nextmanagement.com/milan">Next Milan</a></p>
<p>
	<br />
	FASHION EDITOR<br />
	Derric Lowe</p>
<p>
	STYLING<br />
	Tulip Hubbard</p>
<p>
	MAKEUP<br />
	Veronica Chanel</p>
<div>
	HAIR<br />
	Sasha Gold</div>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '39191',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina2.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '686540',
        'status' => '1',
        'timestamp' => '1441910686',
        'origname' => 'FOCUS_Martina2.jpg',
      ),
      '1' => array(
        'fid' => '39193',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina3.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '148357',
        'status' => '1',
        'timestamp' => '1441910696',
        'origname' => 'FOCUS_Martina3.jpg',
      ),
      '2' => array(
        'fid' => '39195',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina4.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '655809',
        'status' => '1',
        'timestamp' => '1441910706',
        'origname' => 'FOCUS_Martina4.jpg',
      ),
      '3' => array(
        'fid' => '39196',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina5.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61062',
        'status' => '1',
        'timestamp' => '1441910714',
        'origname' => 'FOCUS_Martina5.jpg',
      ),
      '4' => array(
        'fid' => '39198',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina6.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61062',
        'status' => '1',
        'timestamp' => '1441910726',
        'origname' => 'FOCUS_Martina6.jpg',
      ),
      '5' => array(
        'fid' => '39200',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina7.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '446349',
        'status' => '1',
        'timestamp' => '1441910735',
        'origname' => 'FOCUS_Martina7.jpg',
      ),
      '6' => array(
        'fid' => '39201',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina8.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '528125',
        'status' => '1',
        'timestamp' => '1441910744',
        'origname' => 'FOCUS_Martina8.jpg',
      ),
      '7' => array(
        'fid' => '39203',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina9.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '322259',
        'status' => '1',
        'timestamp' => '1441910756',
        'origname' => 'FOCUS_Martina9.jpg',
      ),
      '8' => array(
        'fid' => '39205',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina10.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '651994',
        'status' => '1',
        'timestamp' => '1441910766',
        'origname' => 'FOCUS_Martina10.jpg',
      ),
      '9' => array(
        'fid' => '39207',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina11.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '553465',
        'status' => '1',
        'timestamp' => '1441910778',
        'origname' => 'FOCUS_Martina11.jpg',
      ),
      '10' => array(
        'fid' => '39209',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina12.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '455305',
        'status' => '1',
        'timestamp' => '1441910787',
        'origname' => 'FOCUS_Martina12.jpg',
      ),
      '11' => array(
        'fid' => '39223',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina13.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '515952',
        'status' => '1',
        'timestamp' => '1441910965',
        'origname' => 'FOCUS_Martina13.jpg',
      ),
      '12' => array(
        'fid' => '39211',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina14.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '412535',
        'status' => '1',
        'timestamp' => '1441910795',
        'origname' => 'FOCUS_Martina14.jpg',
      ),
      '13' => array(
        'fid' => '39213',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina15.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '669934',
        'status' => '1',
        'timestamp' => '1441910805',
        'origname' => 'FOCUS_Martina15.jpg',
      ),
      '14' => array(
        'fid' => '39215',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina16.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '547891',
        'status' => '1',
        'timestamp' => '1441910817',
        'origname' => 'FOCUS_Martina16.jpg',
      ),
      '15' => array(
        'fid' => '39224',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina17.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61062',
        'status' => '1',
        'timestamp' => '1441911040',
        'origname' => 'FOCUS_Martina17.jpg',
      ),
      '16' => array(
        'fid' => '39217',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina18.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '698158',
        'status' => '1',
        'timestamp' => '1441910826',
        'origname' => 'FOCUS_Martina18.jpg',
      ),
      '17' => array(
        'fid' => '39219',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina19.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina19.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '714430',
        'status' => '1',
        'timestamp' => '1441910838',
        'origname' => 'FOCUS_Martina19.jpg',
      ),
      '18' => array(
        'fid' => '39221',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina20.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina20.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '383382',
        'status' => '1',
        'timestamp' => '1441910848',
        'origname' => 'FOCUS_Martina20.jpg',
      ),
      '19' => array(
        'fid' => '39222',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FOCUS_Martina21.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/FOCUS_Martina21.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '513250',
        'status' => '1',
        'timestamp' => '1441910857',
        'origname' => 'FOCUS_Martina21.jpg',
      ),
    ),
    'path' => 'stories/focus-martina-troni-michael-clifford',
    'tags' => array(
      '4' => array(
        '2356' => array(
          'tid' => '2356',
          'vid' => '4',
          'name' => 'focus',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'focus',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => 'b175ae12-8e48-11e5-859f-234f24c98333',
    'is_new' => FALSE,
    'timestamp' => 1447887857,
    'xmlsitemap' => array(
      'id' => '5259',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5259',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1447887857',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5259',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
