array(
  array(
    'nid' => '5283',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1444500026',
    'changed' => 1447887869,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5283',
    'revision_uid' => '1',
    'title' => 'Cool Season',
    'body' => '<p>
	Hot looks as things cool off.<br />
	Exclusive photography by <a href="http://www.tharrisonhillman.com/">T. Harrison Hillman</a>.<br />
	Model - Becky Billman at <a href="http://www.lamodels.com/">LA Models</a>.</p>
',
    'teaser' => '<p>
	Hot looks as things cool off.<br />
	Exclusive photography by <a href="http://www.tharrisonhillman.com/">T. Harrison Hillman</a>.<br />
	Model - Becky Billman at <a href="http://www.lamodels.com/">LA Models</a>.</p>
',
    'revision_timestamp' => '1446039199',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.tharrisonhillman.com/">T. Harrison Hillman</a> shoots <a href="http://www.lamodels.com/">LA Models</a>&#39; magnificent Becky Billman in the hottest of autumns cool looks. Styling by <a href="http://www.marissapeden.com/">Marissa Peden</a> includes <a href="http://Adwww.armani.com">Armani</a>, <a href="https://www.balmain.com/">Balmain</a> and <a href="http://www.tamaramellon.com/">Tamara Mellon</a>.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.tharrisonhillman.com/">T. Harrison Hillman</a></p>
<p>
	DIRECTION<br />
	Erika Wolfel</p>
<p>
	STYLING<br />
	<a href="http://www.marissapeden.com/">Marissa Peden</a><br />
	<br />
	HAIR &amp; MAKEUP<br />
	<a href="http://www.christinaculinskihairandmakeup.com/">Cristina Culinski </a></p>
<p>
	POST-PRODUCTION<br />
	Samantha Hylla</p>
<p>
	<br />
	MODEL<br />
	Becky Billman<br />
	at <a href="http://www.lamodels.com/">LA Models</a></p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '39784',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN2.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '156346',
        'status' => '1',
        'timestamp' => '1443549499',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN2.jpg',
      ),
      '1' => array(
        'fid' => '39786',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN3.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '822963',
        'status' => '1',
        'timestamp' => '1443549508',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN3.jpg',
      ),
      '2' => array(
        'fid' => '39788',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN4.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '820542',
        'status' => '1',
        'timestamp' => '1443549518',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN4.jpg',
      ),
      '3' => array(
        'fid' => '39790',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN5.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '685171',
        'status' => '1',
        'timestamp' => '1443549526',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN5.jpg',
      ),
      '4' => array(
        'fid' => '39792',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN6.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '814799',
        'status' => '1',
        'timestamp' => '1443549538',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN6.jpg',
      ),
      '5' => array(
        'fid' => '39794',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN7.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '472043',
        'status' => '1',
        'timestamp' => '1443549548',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN7.jpg',
      ),
      '6' => array(
        'fid' => '39796',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN8.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '936300',
        'status' => '1',
        'timestamp' => '1443549559',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN8.jpg',
      ),
      '7' => array(
        'fid' => '39798',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN9.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '620112',
        'status' => '1',
        'timestamp' => '1443549570',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN9.jpg',
      ),
      '8' => array(
        'fid' => '39800',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN10.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '622685',
        'status' => '1',
        'timestamp' => '1443549585',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN10.jpg',
      ),
      '9' => array(
        'fid' => '39802',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN11.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '758226',
        'status' => '1',
        'timestamp' => '1443549598',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN11.jpg',
      ),
      '10' => array(
        'fid' => '39804',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN12.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1195070',
        'status' => '1',
        'timestamp' => '1443549609',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN12.jpg',
      ),
      '11' => array(
        'fid' => '39805',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'THARRISON-HILLMAN_BECKY-BILLMAN13.jpg',
        'filepath' => 'files/fmag_story/2015/Sep/THARRISON-HILLMAN_BECKY-BILLMAN13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1289582',
        'status' => '1',
        'timestamp' => '1443549618',
        'origname' => 'THARRISON-HILLMAN_BECKY-BILLMAN13.jpg',
      ),
    ),
    'path' => 'stories/cool-season',
    'tags' => array(
      '1' => array(
        '90' => array(
          'tid' => '90',
          'vid' => '1',
          'name' => 'ARMANI',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '1150' => array(
          'tid' => '1150',
          'vid' => '1',
          'name' => 'BALMAIN',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3293' => array(
          'tid' => '3293',
          'vid' => '1',
          'name' => 'Guiseppe Zannoti',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '31' => array(
          'tid' => '31',
          'vid' => '1',
          'name' => 'H&M',
          'description' => 'www.hm.com',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3292' => array(
          'tid' => '3292',
          'vid' => '1',
          'name' => 'Tamara Mellon',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '1382' => array(
          'tid' => '1382',
          'vid' => '1',
          'name' => 'zimmerman',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '2857' => array(
          'tid' => '2857',
          'vid' => '4',
          'name' => 'LA Models',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3291' => array(
          'tid' => '3291',
          'vid' => '4',
          'name' => 't Harrison Hillman',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2882' => array(
          'tid' => '2882',
          'vid' => '4',
          'name' => 'womenswear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'ARMANI, BALMAIN, Guiseppe Zannoti, H&M, Tamara Mellon, zimmerman',
        '4' => 'LA Models, t Harrison Hillman, women, womenswear',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => 'b8b149e8-8e48-11e5-859f-234f24c98333',
    'is_new' => FALSE,
    'timestamp' => 1447887869,
    'xmlsitemap' => array(
      'id' => '5283',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5283',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1447887869',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5283',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
