array(
  array(
    'nid' => '5308',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1446051600',
    'changed' => 1447887900,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5308',
    'revision_uid' => '1',
    'title' => 'CloseUp Elliot James Langridge',
    'body' => '<p>
	We get close up to actor Elliot James Langridge.<br />
	&nbsp;</p>
',
    'teaser' => '<p>
	We get close up to actor Elliot James Langridge.<br />
	&nbsp;</p>
',
    'revision_timestamp' => '1446054515',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	We get close up to actor Elliot James Langridge.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.imdb.com/name/nm2930154/">ELLIOT JAMES </a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://www.northernsoulthefilm.com/">NORTHERN SOUL</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '40426',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FANTASTICS-Elliot-James-Langridge2.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/FANTASTICS-Elliot-James-Langridge2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '337853',
        'status' => '1',
        'timestamp' => '1446054510',
        'origname' => 'FANTASTICS-Elliot-James-Langridge2.jpg',
      ),
      '1' => array(
        'fid' => '40345',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FANTASTICS-Elliot-James-Langridge3.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/FANTASTICS-Elliot-James-Langridge3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108813',
        'status' => '1',
        'timestamp' => '1445961008',
        'origname' => 'FANTASTICS-Elliot-James-Langridge3.jpg',
      ),
      '2' => array(
        'fid' => '40347',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FANTASTICS-Elliot-James-Langridge4.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/FANTASTICS-Elliot-James-Langridge4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '232884',
        'status' => '1',
        'timestamp' => '1445961019',
        'origname' => 'FANTASTICS-Elliot-James-Langridge4.jpg',
      ),
      '3' => array(
        'fid' => '40349',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FANTASTICS-Elliot-James-Langridge5.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/FANTASTICS-Elliot-James-Langridge5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '388064',
        'status' => '1',
        'timestamp' => '1445961028',
        'origname' => 'FANTASTICS-Elliot-James-Langridge5.jpg',
      ),
      '4' => array(
        'fid' => '40351',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FANTASTICS-Elliot-James-Langridge6.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/FANTASTICS-Elliot-James-Langridge6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '389748',
        'status' => '1',
        'timestamp' => '1445961040',
        'origname' => 'FANTASTICS-Elliot-James-Langridge6.jpg',
      ),
      '5' => array(
        'fid' => '40352',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'FANTASTICS-Elliot-James-Langridge7.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/FANTASTICS-Elliot-James-Langridge7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '683243',
        'status' => '1',
        'timestamp' => '1445961047',
        'origname' => 'FANTASTICS-Elliot-James-Langridge7.jpg',
      ),
    ),
    'path' => 'stories/closeup-elliot-james-langridge',
    'tags' => array(
      '4' => array(
        '3098' => array(
          'tid' => '3098',
          'vid' => '4',
          'name' => 'CloseUp',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'CloseUp',
      ),
    ),
    'files' => array(
      '40356' => array(
        'fid' => '40356',
        'uid' => '1',
        'filename' => 'FANTASTICS-Elliot-James-Langridge.pdf',
        'filepath' => 'files/FANTASTICS-Elliot-James-Langridge.pdf',
        'filemime' => 'application/pdf',
        'filesize' => '205440',
        'status' => '1',
        'timestamp' => '1445962534',
        'origname' => '',
        'vid' => '5308',
        'description' => 'FANTASTICS-Elliot-James-Langridge.pdf',
        'list' => '1',
        'nid' => '5308',
        'weight' => '0',
      ),
    ),
    'page_title' => '',
    'uuid' => 'cb884490-8e48-11e5-859f-234f24c98333',
    'is_new' => FALSE,
    'timestamp' => 1447887900,
    'xmlsitemap' => array(
      'id' => '5308',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5308',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1447887900',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5308',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
