array(
  array(
    'nid' => '5312',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1446138000',
    'changed' => 1447887906,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5312',
    'revision_uid' => '1',
    'title' => 'CloseUp Kathleen Wilhoite',
    'body' => '<p>
	We get close up to actress &amp; singer Kathleen Wilhoite.<br />
	Exclusive photography by <a href="http://www.dripbook.com/edwardstgeorge/">Edward St George-Adams</a>.</p>
',
    'teaser' => '<p>
	We get close up to actress &amp; singer Kathleen Wilhoite.<br />
	Exclusive photography by <a href="http://www.dripbook.com/edwardstgeorge/">Edward St George-Adams</a>.</p>
',
    'revision_timestamp' => '1446227102',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	We get close up to actress &amp; singer Kathleen Wilhoite. Exclusive photography by <a href="http://www.dripbook.com/edwardstgeorge/">Edward St George-Adams</a>.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.kathleenwilhoite.com/">KATHLEEN WILHOITE </a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://suckthejoy.com/">SUCK THE JOY PODCAST</a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://www.vitellosrestaurant.com/home">KATHLEEN AT VITELLO&#39;s</a></p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.dripbook.com/edwardstgeorge/">Edward St George-Adams</a></p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	<a href="http://www.montevaldo.com/">Carla Montevaldo</a><br />
	using MAC Cosmetics</p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	<a href="http://www.dripbook.com/edwardstgeorge/">Edward St George-Adams</a><br />
	at Exclusive Artists<br />
	using Amika Hair Products</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '40398',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp2.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '185955',
        'status' => '1',
        'timestamp' => '1446050268',
        'origname' => 'KATHLEEN WILHOITE CloseUp2.jpg',
      ),
      '1' => array(
        'fid' => '40425',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp3.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '439381',
        'status' => '1',
        'timestamp' => '1446051361',
        'origname' => 'KATHLEEN WILHOITE CloseUp3.jpg',
      ),
      '2' => array(
        'fid' => '40431',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp4.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '208871',
        'status' => '1',
        'timestamp' => '1446139071',
        'origname' => 'KATHLEEN WILHOITE CloseUp4.jpg',
      ),
      '3' => array(
        'fid' => '40404',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp5.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '682270',
        'status' => '1',
        'timestamp' => '1446050294',
        'origname' => 'KATHLEEN WILHOITE CloseUp5.jpg',
      ),
      '4' => array(
        'fid' => '40406',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp6.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '390132',
        'status' => '1',
        'timestamp' => '1446050303',
        'origname' => 'KATHLEEN WILHOITE CloseUp6.jpg',
      ),
      '5' => array(
        'fid' => '40408',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp7.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '329480',
        'status' => '1',
        'timestamp' => '1446050312',
        'origname' => 'KATHLEEN WILHOITE CloseUp7.jpg',
      ),
      '6' => array(
        'fid' => '40410',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp8.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '284635',
        'status' => '1',
        'timestamp' => '1446050321',
        'origname' => 'KATHLEEN WILHOITE CloseUp8.jpg',
      ),
      '7' => array(
        'fid' => '40412',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp9.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '692718',
        'status' => '1',
        'timestamp' => '1446050331',
        'origname' => 'KATHLEEN WILHOITE CloseUp9.jpg',
      ),
      '8' => array(
        'fid' => '40414',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp10.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '404329',
        'status' => '1',
        'timestamp' => '1446050345',
        'origname' => 'KATHLEEN WILHOITE CloseUp10.jpg',
      ),
      '9' => array(
        'fid' => '40416',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp11.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '299146',
        'status' => '1',
        'timestamp' => '1446050355',
        'origname' => 'KATHLEEN WILHOITE CloseUp11.jpg',
      ),
      '10' => array(
        'fid' => '40418',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp12.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '654412',
        'status' => '1',
        'timestamp' => '1446050363',
        'origname' => 'KATHLEEN WILHOITE CloseUp12.jpg',
      ),
      '11' => array(
        'fid' => '40420',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp13.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '780219',
        'status' => '1',
        'timestamp' => '1446050372',
        'origname' => 'KATHLEEN WILHOITE CloseUp13.jpg',
      ),
      '12' => array(
        'fid' => '40422',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp14.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '344051',
        'status' => '1',
        'timestamp' => '1446050381',
        'origname' => 'KATHLEEN WILHOITE CloseUp14.jpg',
      ),
      '13' => array(
        'fid' => '40432',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp15.jpg',
        'filepath' => 'files/fmag_story/2015/Oct/KATHLEEN WILHOITE CloseUp15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '288891',
        'status' => '1',
        'timestamp' => '1446139336',
        'origname' => 'KATHLEEN WILHOITE CloseUp15.jpg',
      ),
    ),
    'path' => 'stories/closeup-kathleen-wilhoite',
    'tags' => array(
      '4' => array(
        '3098' => array(
          'tid' => '3098',
          'vid' => '4',
          'name' => 'CloseUp',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'CloseUp',
      ),
    ),
    'files' => array(
      '40430' => array(
        'fid' => '40430',
        'uid' => '1',
        'filename' => 'KATHLEEN WILHOITE CloseUp.pdf',
        'filepath' => 'files/KATHLEEN WILHOITE CloseUp.pdf',
        'filemime' => 'application/pdf',
        'filesize' => '3893552',
        'status' => '1',
        'timestamp' => '1446139030',
        'origname' => '',
        'vid' => '5312',
        'description' => 'KATHLEEN WILHOITE CloseUp.pdf',
        'list' => '1',
        'nid' => '5312',
        'weight' => '0',
      ),
    ),
    'page_title' => '',
    'uuid' => 'cea26f5c-8e48-11e5-859f-234f24c98333',
    'is_new' => FALSE,
    'timestamp' => 1447887906,
    'xmlsitemap' => array(
      'id' => '5312',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5312',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1447887906',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5312',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
