array(
  array(
    'nid' => '5614',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1490120864',
    'changed' => '1491715034',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5614',
    'revision_uid' => '0',
    'title' => 'Go Big',
    'body' => '<p>
	Snow goes wiggy.<br />
	Exclusive photography by <a href="http://www.mikeruiz.com/">Mike Ruiz</a>.<br />
	Model. Snow Dollkinson at <a href="http://www.qmodels.com/">Q Model.</a></p>
',
    'teaser' => '<p>
	Snow goes wiggy.<br />
	Exclusive photography by <a href="http://www.mikeruiz.com/">Mike Ruiz</a>.<br />
	Model. Snow Dollkinson at <a href="http://www.qmodels.com/">Q Model.</a></p>
',
    'log' => '',
    'revision_timestamp' => '1491715034',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.mikeruiz.com/">Mike Ruiz</a> gets <a href="http://www.qmodels.com/">Q Model</a> Snow Dollkinson to go big.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHER<br />
	<a href="http://www.mikeruiz.com/">Mike Ruiz</a><br />
	<br />
	<br />
	HAIR<br />
	<a href="http://www.cesarramirezhair.com/">Cesar DeLeon Ramirez </a><br />
	using wigs from Mane Beauty NYC</p>
<p>
	MAKEUP<br />
	<a href="http://merrellhollis.com/">Merrell Hollis</a><br />
	for Make Up For Ever</p>
<p>
	MODEL<br />
	Snow Dollkinson<br />
	<a href="http://www.qmodels.com/">Q Model</a><br />
	<br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '45245',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow2.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '205273',
        'status' => '1',
        'timestamp' => '1490120766',
        'origname' => 'Mike_Ruiz-Snow2.jpg',
      ),
      '1' => array(
        'fid' => '45246',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow3.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '591031',
        'status' => '1',
        'timestamp' => '1490120776',
        'origname' => 'Mike_Ruiz-Snow3.jpg',
      ),
      '2' => array(
        'fid' => '45247',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow4.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '700320',
        'status' => '1',
        'timestamp' => '1490120784',
        'origname' => 'Mike_Ruiz-Snow4.jpg',
      ),
      '3' => array(
        'fid' => '45248',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow5.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '161848',
        'status' => '1',
        'timestamp' => '1490120792',
        'origname' => 'Mike_Ruiz-Snow5.jpg',
      ),
      '4' => array(
        'fid' => '45256',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow6.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '182400',
        'status' => '1',
        'timestamp' => '1490120904',
        'origname' => 'Mike_Ruiz-Snow6.jpg',
      ),
      '5' => array(
        'fid' => '45249',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow7.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '764102',
        'status' => '1',
        'timestamp' => '1490120808',
        'origname' => 'Mike_Ruiz-Snow7.jpg',
      ),
      '6' => array(
        'fid' => '45250',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow8.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '712997',
        'status' => '1',
        'timestamp' => '1490120816',
        'origname' => 'Mike_Ruiz-Snow8.jpg',
      ),
      '7' => array(
        'fid' => '45251',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow9.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '206018',
        'status' => '1',
        'timestamp' => '1490120824',
        'origname' => 'Mike_Ruiz-Snow9.jpg',
      ),
      '8' => array(
        'fid' => '45252',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow10.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '204436',
        'status' => '1',
        'timestamp' => '1490120832',
        'origname' => 'Mike_Ruiz-Snow10.jpg',
      ),
      '9' => array(
        'fid' => '45253',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow11.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '770338',
        'status' => '1',
        'timestamp' => '1490120843',
        'origname' => 'Mike_Ruiz-Snow11.jpg',
      ),
      '10' => array(
        'fid' => '45254',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow12.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '807683',
        'status' => '1',
        'timestamp' => '1490120853',
        'origname' => 'Mike_Ruiz-Snow12.jpg',
      ),
      '11' => array(
        'fid' => '45255',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Mike_Ruiz-Snow13.jpg',
        'filepath' => 'files/fmag_story/2017/Mar/Mike_Ruiz-Snow13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '198990',
        'status' => '1',
        'timestamp' => '1490120864',
        'origname' => 'Mike_Ruiz-Snow13.jpg',
      ),
    ),
    'path' => 'stories/go-big',
    'tags' => NULL,
    'taxonomy' => array(),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
