array(
  array(
    'nid' => '1949',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1218062339',
    'changed' => '1303573397',
    'comment' => '1',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '1949',
    'revision_uid' => '1',
    'title' => ' HOODLUMS',
    'body' => '<p>
	Boys and hoods together.<br />
	Exclusive photography by <a href="http://www.lindsaylozon.com/" target="_blank">Lindsay Lozon</a>.<br />
	Models ~ Kyle Lyon and Rob, Stuart, Michael, and Mike @ <a href="http://www.nammodels.com" target="_blank">NAM</a>.</p>
',
    'teaser' => '<p>
	Boys and hoods together.<br />
	Exclusive photography by <a href="http://www.lindsaylozon.com/" target="_blank">Lindsay Lozon</a>.<br />
	Models ~ Kyle Lyon and Rob, Stuart, Michael, and Mike @ <a href="http://www.nammodels.com" target="_blank">NAM</a>.</p>
',
    'log' => '',
    'revision_timestamp' => '1303573397',
    'format' => '3',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.lindsaylozon.com/" target="_blank">Lindsay Lozon</a></p>
<p>
	FEATURED FASHION</p>
<ul>
	<li>
		<a href="http://www.hurley.com" target="_blank">Hurley</a></li>
	<li>
		<a href="http://americanapparel.net/" target="_blank">american apparel</a></li>
	<li>
		<a href="http://www.buffalojeans.com" target="_blank">buffalo</a></li>
</ul>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '2070',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '224098',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood_AUG08.jpg',
      ),
      '1' => array(
        'fid' => '2071',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood2_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood2_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '182566',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood2_AUG08.jpg',
      ),
      '2' => array(
        'fid' => '2072',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood3_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood3_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '179997',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood3_AUG08.jpg',
      ),
      '3' => array(
        'fid' => '2073',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood4_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood4_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '257486',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood4_AUG08.jpg',
      ),
      '4' => array(
        'fid' => '2074',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood5_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood5_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '264067',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood5_AUG08.jpg',
      ),
      '5' => array(
        'fid' => '2075',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood6_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood6_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '304661',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood6_AUG08.jpg',
      ),
      '6' => array(
        'fid' => '2076',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood7_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood7_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '198530',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood7_AUG08.jpg',
      ),
      '7' => array(
        'fid' => '2077',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood8_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood8_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '223888',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood8_AUG08.jpg',
      ),
      '8' => array(
        'fid' => '2078',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood10_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood10_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '222479',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood10_AUG08.jpg',
      ),
      '9' => array(
        'fid' => '2079',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood11_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood11_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '321759',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood11_AUG08.jpg',
      ),
      '10' => array(
        'fid' => '2080',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood12_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood12_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '431715',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood12_AUG08.jpg',
      ),
      '11' => array(
        'fid' => '2081',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood13_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood13_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '324181',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood13_AUG08.jpg',
      ),
      '12' => array(
        'fid' => '2082',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood14_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood14_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '174664',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood14_AUG08.jpg',
      ),
      '13' => array(
        'fid' => '2083',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'hood15_AUG08.jpg',
        'filepath' => 'files/fmag_story/2008/Aug/hood15_AUG08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '278141',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'hood15_AUG08.jpg',
      ),
    ),
    'path' => 'stories/hoodlums',
    'tags' => array(
      '5' => array(
        '2417' => array(
          'tid' => '2417',
          'vid' => '5',
          'name' => 'Lindsay Lozon',
          'description' => 'http://www.lindsaylozon.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Lindsay Lozon',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
