array(
  array(
    'nid' => '2596',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '3',
    'status' => '0',
    'created' => '1229518908',
    'changed' => '1232751515',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '2596',
    'revision_uid' => '1',
    'title' => 'IN THE PINK',
    'body' => '<p>Peachy style.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.colfordstudios.com/">Ryan Colford</a>.</p>
<p><br />Model ~ Bob Haglage @ <a target="_blank" href="http://www.newyorkmodels.com/">New York Model</a>.</p>',
    'teaser' => '<p>Peachy style.</p>
<p>Exclusive photography by <a target="_blank" href="http://www.colfordstudios.com/">Ryan Colford</a>.</p>
<p><br />Model ~ Bob Haglage @ <a target="_blank" href="http://www.newyorkmodels.com/">New York Model</a>.</p>',
    'log' => '',
    'revision_timestamp' => '1232751515',
    'format' => '1',
    'name' => 'James N',
    'picture' => 'files/userpics/picture-3.jpg',
    'data' => 'a:2:{s:14:"picture_delete";i:0;s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>PHOTOGRAPHY<br /><a target="_blank" href="http://www.colfordstudios.com/">RYAN COLFORD</a></p>
<p>FEATURED FASHION</p>
<ul>
<li><a target="_blank" href="http://www.bananarepublic.com/">BANANA REPUBLIC<br /></a></li>
<li><a target="_blank" href="http://www.hm.com">H&amp;M</a></li>
</ul>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '1304',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '3',
        'filename' => 'pink_DEC08.jpg',
        'filepath' => 'files/fmag_story/2008/Dec/pink_DEC08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66788',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pink_DEC08.jpg',
      ),
      '1' => array(
        'fid' => '1305',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '3',
        'filename' => 'pink2_DEC08.jpg',
        'filepath' => 'files/fmag_story/2008/Dec/pink2_DEC08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '49994',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pink2_DEC08.jpg',
      ),
      '2' => array(
        'fid' => '1306',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '3',
        'filename' => 'pink3_DEC08.jpg',
        'filepath' => 'files/fmag_story/2008/Dec/pink3_DEC08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '88090',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pink3_DEC08.jpg',
      ),
      '3' => array(
        'fid' => '1307',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '3',
        'filename' => 'pink4_DEC08.jpg',
        'filepath' => 'files/fmag_story/2008/Dec/pink4_DEC08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '108893',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pink4_DEC08.jpg',
      ),
      '4' => array(
        'fid' => '1308',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '3',
        'filename' => 'pink5_DEC08.jpg',
        'filepath' => 'files/fmag_story/2008/Dec/pink5_DEC08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '73076',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pink5_DEC08.jpg',
      ),
      '5' => array(
        'fid' => '1309',
        'list' => NULL,
        'data' => FALSE,
        'uid' => '3',
        'filename' => 'pink6_DEC08.jpg',
        'filepath' => 'files/fmag_story/2008/Dec/pink6_DEC08.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136195',
        'status' => '1',
        'timestamp' => '0',
        'origname' => 'pink6_DEC08.jpg',
      ),
    ),
    'path' => 'stories/pink',
    'tags' => array(
      '5' => array(
        '2411' => array(
          'tid' => '2411',
          'vid' => '5',
          'name' => 'Ryan Colford',
          'description' => 'http://www.colfordstudios.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'Ryan Colford',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
