#!/bin/bash
wp fmagimport node update  4.inc
wp fmagimport node update  16.inc
wp fmagimport node update  17.inc
wp fmagimport node update  18.inc
wp fmagimport node update  19.inc
wp fmagimport node update  20.inc
wp fmagimport node update  22.inc
wp fmagimport node update  23.inc
wp fmagimport node update  24.inc
wp fmagimport node update  25.inc
wp fmagimport node update  26.inc
wp fmagimport node update  27.inc
wp fmagimport node update  28.inc
wp fmagimport node update  29.inc
wp fmagimport node update  30.inc
wp fmagimport node update  42.inc
wp fmagimport node update  43.inc
wp fmagimport node update  44.inc
wp fmagimport node update  45.inc
wp fmagimport node update  46.inc
wp fmagimport node update  47.inc
wp fmagimport node update  48.inc
wp fmagimport node update  49.inc
wp fmagimport node update  50.inc
wp fmagimport node update  51.inc
wp fmagimport node update  52.inc
wp fmagimport node update  61.inc
wp fmagimport node update  62.inc
wp fmagimport node update  63.inc
wp fmagimport node update  65.inc
wp fmagimport node update  67.inc
wp fmagimport node update  69.inc
wp fmagimport node update  71.inc
wp fmagimport node update  72.inc
wp fmagimport node update  73.inc
wp fmagimport node update  74.inc
wp fmagimport node update  76.inc
wp fmagimport node update  77.inc
wp fmagimport node update  79.inc
wp fmagimport node update  81.inc
wp fmagimport node update  83.inc
wp fmagimport node update  85.inc
wp fmagimport node update  87.inc
wp fmagimport node update  88.inc
wp fmagimport node update  90.inc
wp fmagimport node update  92.inc
wp fmagimport node update  94.inc
wp fmagimport node update  96.inc
wp fmagimport node update  98.inc
wp fmagimport node update  100.inc
wp fmagimport node update  102.inc
wp fmagimport node update  104.inc
wp fmagimport node update  106.inc
wp fmagimport node update  108.inc
wp fmagimport node update  110.inc
wp fmagimport node update  112.inc
wp fmagimport node update  1061.inc
wp fmagimport node update  1071.inc
wp fmagimport node update  1082.inc
wp fmagimport node update  1091.inc
wp fmagimport node update  1112.inc
wp fmagimport node update  1165.inc
wp fmagimport node update  1175.inc
wp fmagimport node update  1218.inc
wp fmagimport node update  1243.inc
wp fmagimport node update  1286.inc
wp fmagimport node update  1315.inc
wp fmagimport node update  1337.inc
wp fmagimport node update  1346.inc
wp fmagimport node update  1358.inc
wp fmagimport node update  1376.inc
wp fmagimport node update  1398.inc
wp fmagimport node update  1418.inc
wp fmagimport node update  1478.inc
wp fmagimport node update  1480.inc
wp fmagimport node update  1884.inc
wp fmagimport node update  1893.inc
wp fmagimport node update  1912.inc
wp fmagimport node update  1921.inc
wp fmagimport node update  1934.inc
wp fmagimport node update  1949.inc
wp fmagimport node update  1960.inc
wp fmagimport node update  1978.inc
wp fmagimport node update  2022.inc
wp fmagimport node update  2029.inc
wp fmagimport node update  2050.inc
wp fmagimport node update  2070.inc
wp fmagimport node update  2503.inc
wp fmagimport node update  2515.inc
wp fmagimport node update  2539.inc
wp fmagimport node update  2557.inc
wp fmagimport node update  2574.inc
wp fmagimport node update  2580.inc
wp fmagimport node update  2589.inc
wp fmagimport node update  2591.inc
wp fmagimport node update  2594.inc
wp fmagimport node update  2596.inc
wp fmagimport node update  2598.inc
wp fmagimport node update  2599.inc
wp fmagimport node update  2600.inc
wp fmagimport node update  2601.inc
wp fmagimport node update  2602.inc
wp fmagimport node update  2603.inc
wp fmagimport node update  2604.inc
wp fmagimport node update  2606.inc
wp fmagimport node update  2608.inc
wp fmagimport node update  2731.inc
wp fmagimport node update  2732.inc
wp fmagimport node update  2734.inc