array(
  array(
    'nid' => '5039',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1425254423',
    'changed' => 1442513736,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5039',
    'revision_uid' => '1',
    'title' => 'Focus: Nicole Meyer by Jim Malucci',
    'body' => '<p>
	The focus is on Nicole Meyer.<br />
	Exclusive photography by <a href="http://www.jimmalucci.com">Jim Malucci</a>.</p>
',
    'teaser' => '<p>
	The focus is on Nicole Meyer.<br />
	Exclusive photography by <a href="http://www.jimmalucci.com">Jim Malucci</a>.</p>
',
    'revision_timestamp' => '1425346566',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.jimmalucci.com">Jim Malucci</a> essays <a href="http://www.mpmegamiami.com">MP Mega</a> model Nicole Meyer.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTGRAPHY<a href="http://www.jimmalucci.com"><br />
	Jim Malucci</a></p>
<p>
	MODEL<br />
	Nicole Meyer<br />
	at <a href="http://www.mpmegamiami.com">MP MEGA Miami</a></p>
<p>
	HAIR &amp; MAKEUP<br />
	Khadine Ali</p>
<p>
	<br />
	Location<br />
	Maps Backlot Wynwood Miami</p>
<p>
	<br />
	Bicycle<br />
	courtesy of derick G</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '35386',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer2.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '118523',
        'status' => '1',
        'timestamp' => '1425254261',
        'origname' => 'Jim-Malucci-Nicole-Meyer2.jpg',
      ),
      '1' => array(
        'fid' => '35388',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer3.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '541065',
        'status' => '1',
        'timestamp' => '1425254271',
        'origname' => 'Jim-Malucci-Nicole-Meyer3.jpg',
      ),
      '2' => array(
        'fid' => '35411',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer4.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '550830',
        'status' => '1',
        'timestamp' => '1425254659',
        'origname' => 'Jim-Malucci-Nicole-Meyer4.jpg',
      ),
      '3' => array(
        'fid' => '35392',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer5.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '551084',
        'status' => '1',
        'timestamp' => '1425254296',
        'origname' => 'Jim-Malucci-Nicole-Meyer5.jpg',
      ),
      '4' => array(
        'fid' => '35394',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer6.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61062',
        'status' => '1',
        'timestamp' => '1425254305',
        'origname' => 'Jim-Malucci-Nicole-Meyer6.jpg',
      ),
      '5' => array(
        'fid' => '35396',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer7.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '457152',
        'status' => '1',
        'timestamp' => '1425254317',
        'origname' => 'Jim-Malucci-Nicole-Meyer7.jpg',
      ),
      '6' => array(
        'fid' => '35397',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer8.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '399174',
        'status' => '1',
        'timestamp' => '1425254327',
        'origname' => 'Jim-Malucci-Nicole-Meyer8.jpg',
      ),
      '7' => array(
        'fid' => '35399',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer9.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61063',
        'status' => '1',
        'timestamp' => '1425254339',
        'origname' => 'Jim-Malucci-Nicole-Meyer9.jpg',
      ),
      '8' => array(
        'fid' => '35401',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer10.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '667062',
        'status' => '1',
        'timestamp' => '1425254352',
        'origname' => 'Jim-Malucci-Nicole-Meyer10.jpg',
      ),
      '9' => array(
        'fid' => '35403',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer11.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '576099',
        'status' => '1',
        'timestamp' => '1425254366',
        'origname' => 'Jim-Malucci-Nicole-Meyer11.jpg',
      ),
      '10' => array(
        'fid' => '35405',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer12.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '670973',
        'status' => '1',
        'timestamp' => '1425254382',
        'origname' => 'Jim-Malucci-Nicole-Meyer12.jpg',
      ),
      '11' => array(
        'fid' => '35407',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer13.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61062',
        'status' => '1',
        'timestamp' => '1425254393',
        'origname' => 'Jim-Malucci-Nicole-Meyer13.jpg',
      ),
      '12' => array(
        'fid' => '35409',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer14.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '574498',
        'status' => '1',
        'timestamp' => '1425254407',
        'origname' => 'Jim-Malucci-Nicole-Meyer14.jpg',
      ),
      '13' => array(
        'fid' => '35410',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Jim-Malucci-Nicole-Meyer15.jpg',
        'filepath' => 'files/fmag_story/2015/Mar/Jim-Malucci-Nicole-Meyer15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '678996',
        'status' => '1',
        'timestamp' => '1425254418',
        'origname' => 'Jim-Malucci-Nicole-Meyer15.jpg',
      ),
    ),
    'path' => 'stories/focus-nicole-meyer-jim-malucci',
    'tags' => array(
      '1' => array(
        '1726' => array(
          'tid' => '1726',
          'vid' => '1',
          'name' => 'minimale animale',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'minimale animale',
      ),
      '2' => array(
        '1' => '1',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => '1820e832-5d68-11e5-9f74-8e17caaf1146',
    'is_new' => FALSE,
    'timestamp' => 1442513736,
    'xmlsitemap' => array(
      'id' => '5039',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5039',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1442513736',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5039',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
