array(
  array(
    'nid' => '5071',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1427853545',
    'changed' => 1442513780,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5071',
    'revision_uid' => '1',
    'title' => 'Focus: James Tropeano III by Jason Obrotka',
    'body' => '<p>
	The focus is on James Tropeano III.<br />
	Exclusive photography by <a href="http://www.jasonobrotka.com/">Jason Obrotka.</a></p>
',
    'teaser' => '<p>
	The focus is on James Tropeano III.<br />
	Exclusive photography by <a href="http://www.jasonobrotka.com/">Jason Obrotka.</a></p>
',
    'revision_timestamp' => '1427855143',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.jasonobrotka.com/">Jason Obrotka</a> essays actor James Tropeano III.</p>
<p>
	&nbsp;</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<a href="http://www.jasonobrotka.com/"><br />
	Jason Obrotka</a></p>
<p>
	<br />
	SUBJECT<br />
	James Tropeano III<br />
	&nbsp;</p>
<p>
	<br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '35897',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'james-tropeano-jason-obrotka2.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/james-tropeano-jason-obrotka2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '387901',
        'status' => '1',
        'timestamp' => '1427853718',
        'origname' => 'james-tropeano-jason-obrotka2.jpg',
      ),
      '1' => array(
        'fid' => '35898',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'james-tropeano-jason-obrotka3.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/james-tropeano-jason-obrotka3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '452388',
        'status' => '1',
        'timestamp' => '1427853728',
        'origname' => 'james-tropeano-jason-obrotka3.jpg',
      ),
      '2' => array(
        'fid' => '35912',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'james-tropeano-jason-obrotka4.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/james-tropeano-jason-obrotka4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '369467',
        'status' => '1',
        'timestamp' => '1427855134',
        'origname' => 'james-tropeano-jason-obrotka4.jpg',
      ),
      '3' => array(
        'fid' => '35900',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'james-tropeano-jason-obrotka5.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/james-tropeano-jason-obrotka5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61063',
        'status' => '1',
        'timestamp' => '1427853745',
        'origname' => 'james-tropeano-jason-obrotka5.jpg',
      ),
      '4' => array(
        'fid' => '35901',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'james-tropeano-jason-obrotka6.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/james-tropeano-jason-obrotka6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61062',
        'status' => '1',
        'timestamp' => '1427853754',
        'origname' => 'james-tropeano-jason-obrotka6.jpg',
      ),
      '5' => array(
        'fid' => '35902',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'james-tropeano-jason-obrotka7.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/james-tropeano-jason-obrotka7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '302092',
        'status' => '1',
        'timestamp' => '1427853762',
        'origname' => 'james-tropeano-jason-obrotka7.jpg',
      ),
      '6' => array(
        'fid' => '35904',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'james-tropeano-jason-obrotka8.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/james-tropeano-jason-obrotka8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '505648',
        'status' => '1',
        'timestamp' => '1427853785',
        'origname' => 'james-tropeano-jason-obrotka8.jpg',
      ),
      '7' => array(
        'fid' => '35906',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'james-tropeano-jason-obrotka9.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/james-tropeano-jason-obrotka9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '518534',
        'status' => '1',
        'timestamp' => '1427853797',
        'origname' => 'james-tropeano-jason-obrotka9.jpg',
      ),
      '8' => array(
        'fid' => '35908',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'james-tropeano-jason-obrotka10.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/james-tropeano-jason-obrotka10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61062',
        'status' => '1',
        'timestamp' => '1427853810',
        'origname' => 'james-tropeano-jason-obrotka10.jpg',
      ),
      '9' => array(
        'fid' => '35909',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'james-tropeano-jason-obrotka11.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/james-tropeano-jason-obrotka11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '302063',
        'status' => '1',
        'timestamp' => '1427853824',
        'origname' => 'james-tropeano-jason-obrotka11.jpg',
      ),
    ),
    'path' => 'stories/focus-james-tropeano-iii-jason-obrotka',
    'tags' => array(
      '4' => array(
        '2356' => array(
          'tid' => '2356',
          'vid' => '4',
          'name' => 'focus',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'focus',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => '32653acc-5d68-11e5-9f74-8e17caaf1146',
    'is_new' => FALSE,
    'timestamp' => 1442513780,
    'xmlsitemap' => array(
      'id' => '5071',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5071',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1442513780',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5071',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
