array(
  array(
    'nid' => '5087',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1430142487',
    'changed' => 1442513806,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5087',
    'revision_uid' => '1',
    'title' => 'Guy Underground',
    'body' => '<p>
	Streetwear with street cred.<br />
	Exclusive photography by <a href="http://kimberlycapriotti.com/"><span class="il">Kimberly</span> Capriotti</a>.<br />
	Model. Guy Patrick.</p>
',
    'teaser' => '<p>
	Streetwear with street cred.<br />
	Exclusive photography by <a href="http://kimberlycapriotti.com/"><span class="il">Kimberly</span> Capriotti</a>.<br />
	Model. Guy Patrick.</p>
',
    'revision_timestamp' => '1431446001',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://kimberlycapriotti.com/">Kimberly Capriotti</a> photographs Guy Patrick in downtown looks with street cred and flair. Styling by Molly Haring includes <a href="http://www.openingceremony.us/">Opening Ceremony</a>, <a href="http://nicopanda.com/">Nicopanda</a> and <a href="http://www.adidas.com/">Adidas</a>.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://kimberlycapriotti.com/">Kimberly Capriotti</a><br />
	<br />
	<br />
	<br />
	STYLIST<br />
	Molly Haring<br />
	<br />
	&nbsp;</p>
<p>
	Grooming<br />
	Lydia Brock</p>
<p>
	MODEL<br />
	Guy Patrick<br />
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '36210',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Guy-Underground-Capriotti2.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/Guy-Underground-Capriotti2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '367426',
        'status' => '1',
        'timestamp' => '1430143307',
        'origname' => 'Guy-Underground-Capriotti2.jpg',
      ),
      '1' => array(
        'fid' => '36198',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Guy-Underground-Capriotti3.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/Guy-Underground-Capriotti3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '450546',
        'status' => '1',
        'timestamp' => '1430142420',
        'origname' => 'Guy-Underground-Capriotti3.jpg',
      ),
      '2' => array(
        'fid' => '36200',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Guy-Underground-Capriotti4.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/Guy-Underground-Capriotti4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87219',
        'status' => '1',
        'timestamp' => '1430142430',
        'origname' => 'Guy-Underground-Capriotti4.jpg',
      ),
      '3' => array(
        'fid' => '36202',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Guy-Underground-Capriotti5.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/Guy-Underground-Capriotti5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '581899',
        'status' => '1',
        'timestamp' => '1430142440',
        'origname' => 'Guy-Underground-Capriotti5.jpg',
      ),
      '4' => array(
        'fid' => '36204',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Guy-Underground-Capriotti6.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/Guy-Underground-Capriotti6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '474698',
        'status' => '1',
        'timestamp' => '1430142451',
        'origname' => 'Guy-Underground-Capriotti6.jpg',
      ),
      '5' => array(
        'fid' => '36205',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Guy-Underground-Capriotti7.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/Guy-Underground-Capriotti7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '402684',
        'status' => '1',
        'timestamp' => '1430142460',
        'origname' => 'Guy-Underground-Capriotti7.jpg',
      ),
      '6' => array(
        'fid' => '36207',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Guy-Underground-Capriotti8.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/Guy-Underground-Capriotti8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '455793',
        'status' => '1',
        'timestamp' => '1430142474',
        'origname' => 'Guy-Underground-Capriotti8.jpg',
      ),
      '7' => array(
        'fid' => '36208',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Guy-Underground-Capriotti9.jpg',
        'filepath' => 'files/fmag_story/2015/Apr/Guy-Underground-Capriotti9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '76012',
        'status' => '1',
        'timestamp' => '1430142481',
        'origname' => 'Guy-Underground-Capriotti9.jpg',
      ),
    ),
    'path' => 'stories/guy-underground',
    'tags' => array(
      '1' => array(
        '689' => array(
          'tid' => '689',
          'vid' => '1',
          'name' => 'adidas',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3049' => array(
          'tid' => '3049',
          'vid' => '1',
          'name' => 'Etudes Studio',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '820' => array(
          'tid' => '820',
          'vid' => '1',
          'name' => 'farah',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '297' => array(
          'tid' => '297',
          'vid' => '1',
          'name' => 'loewe',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3050' => array(
          'tid' => '3050',
          'vid' => '1',
          'name' => 'Maison Kitsune',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3048' => array(
          'tid' => '3048',
          'vid' => '1',
          'name' => 'Nicopanda',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '582' => array(
          'tid' => '582',
          'vid' => '1',
          'name' => 'opening ceremony',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '3047' => array(
          'tid' => '3047',
          'vid' => '4',
          'name' => 'Kimberly Capriotti',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2302' => array(
          'tid' => '2302',
          'vid' => '4',
          'name' => 'menswear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'adidas, Etudes Studio, farah, loewe, Maison Kitsune, Nicopanda, opening ceremony',
        '4' => 'Kimberly Capriotti, men, menswear',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => '41ab6132-5d68-11e5-9f74-8e17caaf1146',
    'is_new' => FALSE,
    'timestamp' => 1442513806,
    'xmlsitemap' => array(
      'id' => '5087',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5087',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1442513806',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5087',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
