array(
  array(
    'nid' => '5093',
    'type' => 'fmag_video',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1430160475',
    'changed' => 1442513812,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5093',
    'revision_uid' => '1',
    'title' => 'On The Beach by Rick Day',
    'body' => '<p> 
On The Beach - a film by Rick Day.<br />
<br /></p>
<p> Cast - Olivia Garson at Next.</p>
',
    'teaser' => '<p> 
On The Beach - a film by Rick Day.<br />
<br /></p>
<p> Cast - Olivia Garson at Next.</p>
',
    'revision_timestamp' => '1430758590',
    'format' => '4',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://rickdaynyc.com/">Rick Day</a></p>
<p>
	Director<br />
	Steve Benisty<br />
	<br />
	STYLIST<br />
	Dani Parets<br />
	<br />
	HAIR &amp; MAKEUP<br />
	Toni Feliciano</p>
<p>
	MODEL<br />
	Olivia Garson<br />
	at <a href="http://www.nextmanagement.com/">Next</a></p>
',
      ),
    ),
    'field_videoembed' => array(
      '0' => array(
        'value' => '<!-- here is the documentation you will need for adding videos --><!-- first, you have the embed tag: -->
<p>
	<iframe allowfullscreen="" frameborder="0" height="550" src="http://www.youtube.com/embed//B4nKMaB_5dk?&amp;autoplay=1&amp;rel=0&amp;showinfo=0&amp;modestbranding=1&amp;hd=1&amp;autohide=1&amp;color=white&amp;vq=hd720" width="1000"></iframe><!-- it is what will show on the turnpage. Use Youtube\'s embed feature, set "custom height" and use a height of 550.
<!-- this code is slightly modified to support autoplaying, a white progress bar, etc. Basically you just want to change the 
<!-- "z9oN0JdhA2o" part, and the width (the embed will show you what the width of the youtube vid should be based on 550px 
<!-- high.

<!-- the teaser image is attached in the "file attachments" area. It is very important to leave the "List" checkbox unchecked.
<!-- otherwise, the file will be listed on the turnpage. We don\'t want that! One other important thing that may not be set by default
<!-- is the "input format". See it right under this text area? Expand it, and make sure it is set to "unfiltered!" 
<!-- the videos will only show on the frontpage if you are logged in.--></p>
',
      ),
    ),
    'field_description' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'path' => 'videos/beach-rick-day',
    'tags' => array(
      '5' => array(
        '2660' => array(
          'tid' => '2660',
          'vid' => '5',
          'name' => 'RICK DAY',
          'description' => 'http://rickdaynyc.com/',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '5' => 'RICK DAY',
      ),
    ),
    'files' => array(
      '36287' => array(
        'fid' => '36287',
        'uid' => '1',
        'filename' => 'rick-day-olivia-garson.jpg',
        'filepath' => 'files/rick-day-olivia-garson_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '445070',
        'status' => '1',
        'timestamp' => '1430162284',
        'origname' => '',
        'vid' => '5093',
        'description' => 'rick-day-olivia-garson.jpg',
        'list' => '1',
        'nid' => '5093',
        'weight' => '0',
      ),
    ),
    'page_title' => '',
    'uuid' => '4500bd32-5d68-11e5-9f74-8e17caaf1146',
    'is_new' => FALSE,
    'timestamp' => 1442513812,
    'xmlsitemap' => array(
      'id' => '5093',
      'type' => 'node',
      'subtype' => 'fmag_video',
      'loc' => 'node/5093',
      'language' => '',
      'access' => TRUE,
      'status' => '0',
      'status_override' => '0',
      'lastmod' => '1442513812',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '0',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5093',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
