array(
  array(
    'nid' => '5177',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1435679757',
    'changed' => 1442513930,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5177',
    'revision_uid' => '1',
    'title' => 'Focus: Stelios Niakaris & Gil Soares by Gabe Ayala',
    'body' => '<p>
	The focus is on Stelios Niakaris &amp; Gil Soares.<br />
	Exclusive photography by <a href="http://www.gabeayalaphoto.com/">Gabe Ayala</a>.</p>
',
    'teaser' => '<p>
	The focus is on Stelios Niakaris &amp; Gil Soares.<br />
	Exclusive photography by <a href="http://www.gabeayalaphoto.com/">Gabe Ayala</a>.</p>
',
    'revision_timestamp' => '1435896026',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.gabeayalaphoto.com/">Gabe Ayala</a> essays <a href="http://www.twomanagement.com/">Two Management</a>&#39;s Stelios Niakaris &amp; Gil Soares .</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.gabeayalaphoto.com/">Gabe Ayala</a></p>
<p>
	STYLING<br />
	Malcolm Joris<br />
	<a href="http://jamobest.com/"> </a></p>
<p>
	&nbsp;</p>
<p>
	SUBJECTS<br />
	Stelios Niakaris<br />
	&amp; Gil Soares<br />
	At <a href="http://www.twomanagement.com/">Two Management</a></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '37674',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares2.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '165246',
        'status' => '1',
        'timestamp' => '1435679638',
        'origname' => 'gabe-stelios-niakaris-gil-soares2.jpg',
      ),
      '1' => array(
        'fid' => '37676',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares3.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '1134383',
        'status' => '1',
        'timestamp' => '1435679651',
        'origname' => 'gabe-stelios-niakaris-gil-soares3.jpg',
      ),
      '2' => array(
        'fid' => '37678',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares4.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '769825',
        'status' => '1',
        'timestamp' => '1435679659',
        'origname' => 'gabe-stelios-niakaris-gil-soares4.jpg',
      ),
      '3' => array(
        'fid' => '37680',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares5.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '716853',
        'status' => '1',
        'timestamp' => '1435679669',
        'origname' => 'gabe-stelios-niakaris-gil-soares5.jpg',
      ),
      '4' => array(
        'fid' => '37682',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares6.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '505331',
        'status' => '1',
        'timestamp' => '1435679678',
        'origname' => 'gabe-stelios-niakaris-gil-soares6.jpg',
      ),
      '5' => array(
        'fid' => '37684',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares7.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '428370',
        'status' => '1',
        'timestamp' => '1435679688',
        'origname' => 'gabe-stelios-niakaris-gil-soares7.jpg',
      ),
      '6' => array(
        'fid' => '37686',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares8.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '724193',
        'status' => '1',
        'timestamp' => '1435679697',
        'origname' => 'gabe-stelios-niakaris-gil-soares8.jpg',
      ),
      '7' => array(
        'fid' => '37688',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares9.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '595328',
        'status' => '1',
        'timestamp' => '1435679707',
        'origname' => 'gabe-stelios-niakaris-gil-soares9.jpg',
      ),
      '8' => array(
        'fid' => '37689',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares10.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '614307',
        'status' => '1',
        'timestamp' => '1435679716',
        'origname' => 'gabe-stelios-niakaris-gil-soares10.jpg',
      ),
      '9' => array(
        'fid' => '37691',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares11.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '607007',
        'status' => '1',
        'timestamp' => '1435679729',
        'origname' => 'gabe-stelios-niakaris-gil-soares11.jpg',
      ),
      '10' => array(
        'fid' => '37693',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares12.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '908877',
        'status' => '1',
        'timestamp' => '1435679738',
        'origname' => 'gabe-stelios-niakaris-gil-soares12.jpg',
      ),
      '11' => array(
        'fid' => '37694',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'gabe-stelios-niakaris-gil-soares13.jpg',
        'filepath' => 'files/fmag_story/2015/Jun/gabe-stelios-niakaris-gil-soares13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '493394',
        'status' => '1',
        'timestamp' => '1435679746',
        'origname' => 'gabe-stelios-niakaris-gil-soares13.jpg',
      ),
    ),
    'path' => 'stories/focus-stelios-niakaris-gil-soares-gabe-ayala',
    'tags' => array(
      '4' => array(
        '2356' => array(
          'tid' => '2356',
          'vid' => '4',
          'name' => 'focus',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'focus',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => '8b54bb26-5d68-11e5-9f74-8e17caaf1146',
    'is_new' => FALSE,
    'timestamp' => 1442513930,
    'xmlsitemap' => array(
      'id' => '5177',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5177',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1442513930',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5177',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
