array(
  array(
    'nid' => '5196',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1436839570',
    'changed' => 1442513956,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5196',
    'revision_uid' => '1',
    'title' => 'Color Flash',
    'body' => '<p>
	Big color.<br />
	Exclusive photography by <a href="http://www.bethsternbaum.com/">Beth Sternbaum</a>.<br />
	Model - Lauren Trotter at <a href="http://www.twomanagement.com/">Two Management</a>.</p>
',
    'teaser' => '<p>
	Big color.<br />
	Exclusive photography by <a href="http://www.bethsternbaum.com/">Beth Sternbaum</a>.<br />
	Model - Lauren Trotter at <a href="http://www.twomanagement.com/">Two Management</a>.</p>
',
    'revision_timestamp' => '1436879207',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.bethsternbaum.com/">Beth Sternbaum</a> shoots the glorious Lauren Trotter of Two Management in big bold color. Beauty looks by <a href="http://www.courtneyhagen.com/#0">Courtney Hagen.</a></p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.bethsternbaum.com/">Beth Sternbaum</a></p>
<p>
	<br />
	MAKEUP<br />
	<a href="http://www.courtneyhagen.com/#0">Courtney Hagen</a><br />
	<br />
	HAIR<br />
	<a href="http://www.bethanyruck.com/">Bethany Ruck</a></p>
<p>
	<span>MODEL<br />
	Lauren Trotter<br />
	at <a href="http://www.twomanagement.com/">Two Management</a><br />
	<br />
	</span></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '37986',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter2.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '196518',
        'status' => '1',
        'timestamp' => '1436839095',
        'origname' => 'beth-sternbaum-lauren-trotter2.jpg',
      ),
      '1' => array(
        'fid' => '37987',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter3.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '186416',
        'status' => '1',
        'timestamp' => '1436839104',
        'origname' => 'beth-sternbaum-lauren-trotter3.jpg',
      ),
      '2' => array(
        'fid' => '37989',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter4.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '32558',
        'status' => '1',
        'timestamp' => '1436839277',
        'origname' => 'beth-sternbaum-lauren-trotter4.jpg',
      ),
      '3' => array(
        'fid' => '37991',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter5.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132241',
        'status' => '1',
        'timestamp' => '1436839288',
        'origname' => 'beth-sternbaum-lauren-trotter5.jpg',
      ),
      '4' => array(
        'fid' => '37993',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter6.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155701',
        'status' => '1',
        'timestamp' => '1436839301',
        'origname' => 'beth-sternbaum-lauren-trotter6.jpg',
      ),
      '5' => array(
        'fid' => '37995',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter7.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '30459',
        'status' => '1',
        'timestamp' => '1436839311',
        'origname' => 'beth-sternbaum-lauren-trotter7.jpg',
      ),
      '6' => array(
        'fid' => '38008',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter8.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '31374',
        'status' => '1',
        'timestamp' => '1436839640',
        'origname' => 'beth-sternbaum-lauren-trotter8.jpg',
      ),
      '7' => array(
        'fid' => '37997',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter9.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '158534',
        'status' => '1',
        'timestamp' => '1436839325',
        'origname' => 'beth-sternbaum-lauren-trotter9.jpg',
      ),
      '8' => array(
        'fid' => '37998',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter10.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '147351',
        'status' => '1',
        'timestamp' => '1436839342',
        'origname' => 'beth-sternbaum-lauren-trotter10.jpg',
      ),
      '9' => array(
        'fid' => '37999',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter11.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29084',
        'status' => '1',
        'timestamp' => '1436839366',
        'origname' => 'beth-sternbaum-lauren-trotter11.jpg',
      ),
      '10' => array(
        'fid' => '38002',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter12.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '137473',
        'status' => '1',
        'timestamp' => '1436839386',
        'origname' => 'beth-sternbaum-lauren-trotter12.jpg',
      ),
      '11' => array(
        'fid' => '38004',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter13.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '31903',
        'status' => '1',
        'timestamp' => '1436839393',
        'origname' => 'beth-sternbaum-lauren-trotter13.jpg',
      ),
      '12' => array(
        'fid' => '38006',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter14.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '132738',
        'status' => '1',
        'timestamp' => '1436839404',
        'origname' => 'beth-sternbaum-lauren-trotter14.jpg',
      ),
      '13' => array(
        'fid' => '38007',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'beth-sternbaum-lauren-trotter15.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/beth-sternbaum-lauren-trotter15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '125783',
        'status' => '1',
        'timestamp' => '1436839418',
        'origname' => 'beth-sternbaum-lauren-trotter15.jpg',
      ),
    ),
    'path' => 'stories/color-flash',
    'tags' => array(
      '4' => array(
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2882' => array(
          'tid' => '2882',
          'vid' => '4',
          'name' => 'womenswear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'women, womenswear',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => '9b2641be-5d68-11e5-9f74-8e17caaf1146',
    'is_new' => FALSE,
    'timestamp' => 1442513956,
    'xmlsitemap' => array(
      'id' => '5196',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5196',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1442513956',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5196',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
