array(
  array(
    'nid' => '5201',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1438336800',
    'changed' => 1442513986,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5201',
    'revision_uid' => '0',
    'title' => 'Big Bang',
    'body' => '<p>
	Make some noise.<br />
	Exclusive photography by <a href="http://www.joshuapestka.com/">Joshua Pestka</a>.<br />
	Model - Natasha Remarchuk at <a href="http://www.suprememanagement.com/">Supreme</a>.</p>
',
    'teaser' => '<p>
	Make some noise.<br />
	Exclusive photography by <a href="http://www.joshuapestka.com/">Joshua Pestka</a>.<br />
	Model - Natasha Remarchuk at <a href="http://www.suprememanagement.com/">Supreme</a>.</p>
',
    'revision_timestamp' => '1438336817',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.joshuapestka.com/">Joshua Pestka</a> photographs Natasha Remarchuk at <a href="http://www.suprememanagement.com/">Supreme</a> in looks that will make some noise. Styling by Tiffani James.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.joshuapestka.com/">Joshua Pestka</a><br />
	<br />
	<br />
	STYLING<br />
	Tiffani James<br />
	<br />
	<br />
	HAIR<br />
	Daven Mayeda<br />
	&nbsp;</p>
<p>
	MAKEUP<br />
	Kelley Quan<br />
	for Nars Cosmetics<br />
	at Kramer and Kramer<br />
	<br />
	&nbsp;</p>
<p>
	<span>MODEL<br />
	Natasha Remarchuk </span><br />
	<span>at <a href="http://www.suprememanagement.com/">Supreme</a><br />
	<br />
	</span></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '38040',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk2.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '54247',
        'status' => '1',
        'timestamp' => '1437340610',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk2.jpg',
      ),
      '1' => array(
        'fid' => '38042',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk3.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '69852',
        'status' => '1',
        'timestamp' => '1437340621',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk3.jpg',
      ),
      '2' => array(
        'fid' => '38044',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk4.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29926',
        'status' => '1',
        'timestamp' => '1437340630',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk4.jpg',
      ),
      '3' => array(
        'fid' => '38046',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk5.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '67694',
        'status' => '1',
        'timestamp' => '1437340641',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk5.jpg',
      ),
      '4' => array(
        'fid' => '38048',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk6.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '59557',
        'status' => '1',
        'timestamp' => '1437340649',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk6.jpg',
      ),
      '5' => array(
        'fid' => '38050',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk7.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '30304',
        'status' => '1',
        'timestamp' => '1437340658',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk7.jpg',
      ),
      '6' => array(
        'fid' => '38052',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk8.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '31369',
        'status' => '1',
        'timestamp' => '1437340668',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk8.jpg',
      ),
      '7' => array(
        'fid' => '38054',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk9.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '51167',
        'status' => '1',
        'timestamp' => '1437340676',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk9.jpg',
      ),
      '8' => array(
        'fid' => '38056',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk10.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '49425',
        'status' => '1',
        'timestamp' => '1437340686',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk10.jpg',
      ),
      '9' => array(
        'fid' => '38058',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk11.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '30500',
        'status' => '1',
        'timestamp' => '1437340696',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk11.jpg',
      ),
      '10' => array(
        'fid' => '38060',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk12.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '29541',
        'status' => '1',
        'timestamp' => '1437340704',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk12.jpg',
      ),
      '11' => array(
        'fid' => '38061',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Joshua-Pestka-Natasha-Remarchuk13.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Joshua-Pestka-Natasha-Remarchuk13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '84765',
        'status' => '1',
        'timestamp' => '1437340713',
        'origname' => 'Joshua-Pestka-Natasha-Remarchuk13.jpg',
      ),
    ),
    'path' => 'stories/big-bang-0',
    'tags' => array(
      '1' => array(
        '689' => array(
          'tid' => '689',
          'vid' => '1',
          'name' => 'adidas',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '973' => array(
          'tid' => '973',
          'vid' => '1',
          'name' => 'Laquan Smith',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3215' => array(
          'tid' => '3215',
          'vid' => '1',
          'name' => 'Luma',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '3225' => array(
          'tid' => '3225',
          'vid' => '4',
          'name' => 'Joshua Pestka',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3226' => array(
          'tid' => '3226',
          'vid' => '4',
          'name' => 'Supreme',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2882' => array(
          'tid' => '2882',
          'vid' => '4',
          'name' => 'womenswear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'adidas, Laquan Smith, Luma',
        '4' => 'Joshua Pestka, Supreme, women, womenswear',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => 'accd4c50-5d68-11e5-9f74-8e17caaf1146',
    'is_new' => FALSE,
    'timestamp' => 1442513986,
    'xmlsitemap' => array(
      'id' => '5201',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5201',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1442513986',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5201',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
