array(
  array(
    'nid' => '5227',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1440671171',
    'changed' => 1442514016,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5227',
    'revision_uid' => '1',
    'title' => 'Unleashed',
    'body' => '<p>
	Let it out.<br />
	Exclusive photography by <a href="http://www.maxjamali.com/">Max Jamali</a>.<br />
	Model - Matthew Smith at <a href="http://www.angiesmodels.com/">AMTI</a>.</p>
',
    'teaser' => '<p>
	Let it out.<br />
	Exclusive photography by <a href="http://www.maxjamali.com/">Max Jamali</a>.<br />
	Model - Matthew Smith at <a href="http://www.angiesmodels.com/">AMTI</a>.</p>
',
    'revision_timestamp' => '1440692245',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.maxjamali.com/">Max Jamali</a> gets <a href="http://www.angiesmodels.com/">AMTI</a> model Matthew Smith to let it all out. Styling by Juan Solorzano and Jed Lueras.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	PHOTOGRAPHY<br />
	<a href="http://www.maxjamali.com/">Max Jamali</a><br />
	<br />
	<br />
	STYLING<br />
	Juan Solorzano<br />
	Jed Lueras.<br />
	<br />
	<br />
	HAIR<br />
	Palma N&#39;Sheluvzit<br />
	&nbsp;</p>
<p>
	MAKEUP<br />
	Sheena Thomson<br />
	&nbsp;</p>
<p>
	<span>MODEL<br />
	Matthew Smith</span><br />
	<span>at <a href="http://www.angiesmodels.com/">AMTI</a><br />
	<br />
	</span></p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '38588',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Unleashed-Matthew-Smith2.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Unleashed-Matthew-Smith2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '116688',
        'status' => '1',
        'timestamp' => '1437945880',
        'origname' => 'Unleashed-Matthew-Smith2.jpg',
      ),
      '1' => array(
        'fid' => '38590',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Unleashed-Matthew-Smith3.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Unleashed-Matthew-Smith3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '460720',
        'status' => '1',
        'timestamp' => '1437945889',
        'origname' => 'Unleashed-Matthew-Smith3.jpg',
      ),
      '2' => array(
        'fid' => '38592',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Unleashed-Matthew-Smith4.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Unleashed-Matthew-Smith4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '530683',
        'status' => '1',
        'timestamp' => '1437945899',
        'origname' => 'Unleashed-Matthew-Smith4.jpg',
      ),
      '3' => array(
        'fid' => '38594',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Unleashed-Matthew-Smith5.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Unleashed-Matthew-Smith5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68116',
        'status' => '1',
        'timestamp' => '1437945907',
        'origname' => 'Unleashed-Matthew-Smith5.jpg',
      ),
      '4' => array(
        'fid' => '38596',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Unleashed-Matthew-Smith6.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Unleashed-Matthew-Smith6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '66128',
        'status' => '1',
        'timestamp' => '1437945914',
        'origname' => 'Unleashed-Matthew-Smith6.jpg',
      ),
      '5' => array(
        'fid' => '38598',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Unleashed-Matthew-Smith7.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Unleashed-Matthew-Smith7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '472193',
        'status' => '1',
        'timestamp' => '1437945923',
        'origname' => 'Unleashed-Matthew-Smith7.jpg',
      ),
      '6' => array(
        'fid' => '38600',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Unleashed-Matthew-Smith8.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Unleashed-Matthew-Smith8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '594446',
        'status' => '1',
        'timestamp' => '1437945933',
        'origname' => 'Unleashed-Matthew-Smith8.jpg',
      ),
      '7' => array(
        'fid' => '38602',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Unleashed-Matthew-Smith9.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Unleashed-Matthew-Smith9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '61062',
        'status' => '1',
        'timestamp' => '1437945942',
        'origname' => 'Unleashed-Matthew-Smith9.jpg',
      ),
      '8' => array(
        'fid' => '38603',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Unleashed-Matthew-Smith10.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Unleashed-Matthew-Smith10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '68861',
        'status' => '1',
        'timestamp' => '1437945950',
        'origname' => 'Unleashed-Matthew-Smith10.jpg',
      ),
      '9' => array(
        'fid' => '38604',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Unleashed-Matthew-Smith11.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/Unleashed-Matthew-Smith11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '752261',
        'status' => '1',
        'timestamp' => '1437945965',
        'origname' => 'Unleashed-Matthew-Smith11.jpg',
      ),
    ),
    'path' => 'stories/unleashed',
    'tags' => array(
      '1' => array(
        '3238' => array(
          'tid' => '3238',
          'vid' => '1',
          'name' => 'Boris Bidjan Saberi',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3239' => array(
          'tid' => '3239',
          'vid' => '1',
          'name' => 'Carol Christian Poell',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3237' => array(
          'tid' => '3237',
          'vid' => '1',
          'name' => 'Julius_7',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '219' => array(
          'tid' => '219',
          'vid' => '1',
          'name' => 'JUMA',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '3236' => array(
          'tid' => '3236',
          'vid' => '1',
          'name' => 'Reinhard Plank',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '480' => array(
          'tid' => '480',
          'vid' => '1',
          'name' => 'RICK OWENS',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
      '4' => array(
        '3235' => array(
          'tid' => '3235',
          'vid' => '4',
          'name' => 'Max Jamali',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
        '2302' => array(
          'tid' => '2302',
          'vid' => '4',
          'name' => 'menswear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '1' => 'Boris Bidjan Saberi, Carol Christian Poell, Julius_7, JUMA, Reinhard Plank, RICK OWENS',
        '4' => 'Max Jamali, men, menswear',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'uuid' => 'bf2ba900-5d68-11e5-9f74-8e17caaf1146',
    'is_new' => FALSE,
    'timestamp' => 1442514016,
    'xmlsitemap' => array(
      'id' => '5227',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5227',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1442514016',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5227',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
