array(
  array(
    'nid' => '5235',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1439992800',
    'changed' => 1442514010,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5235',
    'revision_uid' => '0',
    'title' => 'Kyle King - Wear About',
    'body' => '<p>
	Fashion talk with designer <a href="http://www.kyleking.us/">Kyle King</a>.<br />
	Exclusive photography by <a href="http://www.jasonobrotka.com/">Jason Obrotka</a>.<br />
	Fashion photography by <a href="http://www.joshfilauri.com/">Josh Filauri.</a></p>
<p>
	&nbsp;</p>
',
    'teaser' => '<p>
	Fashion talk with designer <a href="http://www.kyleking.us/">Kyle King</a>.<br />
	Exclusive photography by <a href="http://www.jasonobrotka.com/">Jason Obrotka</a>.<br />
	Fashion photography by <a href="http://www.joshfilauri.com/">Josh Filauri.</a></p>
<p>
	&nbsp;</p>
',
    'revision_timestamp' => '1439992816',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Swimwear designer <a href="http://www.kyleking.us/">Kyle King</a>. Portraits by <a href="http://www.jasonobrotka.com/">Jason Obrotka</a>.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.kyleking.us/">Kyle King Swimwear</a></p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://www.jasonobrotka.com/">Jason Obrotka</a></p>
<p>
	&nbsp;</p>
<p>
	SWIMWEAR PHOTOS<br />
	<a href="http://www.joshfilauri.com/">Josh Filauri</a></p>
<p>
	MODEL<br />
	Ryan Marek</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '38738',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR-ABOUT-Kyle-King-swimwear2.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR-ABOUT-Kyle-King-swimwear2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '285573',
        'status' => '1',
        'timestamp' => '1438191552',
        'origname' => 'WEAR-ABOUT-Kyle-King-swimwear2.jpg',
      ),
      '1' => array(
        'fid' => '38739',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR-ABOUT-Kyle-King-swimwear3.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR-ABOUT-Kyle-King-swimwear3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '149321',
        'status' => '1',
        'timestamp' => '1438191590',
        'origname' => 'WEAR-ABOUT-Kyle-King-swimwear3.jpg',
      ),
      '2' => array(
        'fid' => '38741',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR-ABOUT-Kyle-King-swimwear4.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR-ABOUT-Kyle-King-swimwear4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '216685',
        'status' => '1',
        'timestamp' => '1438191603',
        'origname' => 'WEAR-ABOUT-Kyle-King-swimwear4.jpg',
      ),
      '3' => array(
        'fid' => '38743',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR-ABOUT-Kyle-King-swimwear5.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR-ABOUT-Kyle-King-swimwear5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '434925',
        'status' => '1',
        'timestamp' => '1438191613',
        'origname' => 'WEAR-ABOUT-Kyle-King-swimwear5.jpg',
      ),
      '4' => array(
        'fid' => '38745',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR-ABOUT-Kyle-King-swimwear6.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR-ABOUT-Kyle-King-swimwear6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '366081',
        'status' => '1',
        'timestamp' => '1438191623',
        'origname' => 'WEAR-ABOUT-Kyle-King-swimwear6.jpg',
      ),
      '5' => array(
        'fid' => '38753',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR-ABOUT-Kyle-King-swimwearEDIT7.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR-ABOUT-Kyle-King-swimwearEDIT7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '3958734',
        'status' => '1',
        'timestamp' => '1438194312',
        'origname' => 'WEAR-ABOUT-Kyle-King-swimwearEDIT7.jpg',
      ),
      '6' => array(
        'fid' => '38754',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR-ABOUT-Kyle-King-swimwearEDIT8.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR-ABOUT-Kyle-King-swimwearEDIT8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '4831791',
        'status' => '1',
        'timestamp' => '1438194331',
        'origname' => 'WEAR-ABOUT-Kyle-King-swimwearEDIT8.jpg',
      ),
      '7' => array(
        'fid' => '38750',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR-ABOUT-Kyle-King-swimwear9.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR-ABOUT-Kyle-King-swimwear9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '398657',
        'status' => '1',
        'timestamp' => '1438191735',
        'origname' => 'WEAR-ABOUT-Kyle-King-swimwear9.jpg',
      ),
    ),
    'path' => 'stories/kyle-king-wear-about',
    'tags' => NULL,
    'taxonomy' => array(),
    'files' => array(),
    'page_title' => '',
    'uuid' => 'bb113466-5d68-11e5-9f74-8e17caaf1146',
    'is_new' => FALSE,
    'timestamp' => 1442514010,
    'xmlsitemap' => array(
      'id' => '5235',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5235',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1442514010',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5235',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
