array(
  array(
    'nid' => '5237',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1439560800',
    'changed' => 1442514006,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5237',
    'revision_uid' => '1',
    'title' => 'Wear About - Prospective Flow',
    'body' => '<p>
	Fashion talk with designer Yusuke Muramatsu of <a href="http://www.prospectiveflow.com/">Prospective Flow</a>.<br />
	Exclusive photography by <a href="http://fidelgonzalezphotography.com/">Fidel Gonzalez</a>.</p>
',
    'teaser' => '<p>
	Fashion talk with designer Yusuke Muramatsu of <a href="http://www.prospectiveflow.com/">Prospective Flow</a>.<br />
	Exclusive photography by <a href="http://fidelgonzalezphotography.com/">Fidel Gonzalez</a>.</p>
',
    'revision_timestamp' => '1439576152',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Denim makers <a href="http://www.prospectiveflow.com/">Prospective Flow</a>. Photography by <a href="http://fidelgonzalezphotography.com/">Fidel Gonzalez</a>.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://www.prospectiveflow.com/">Prospective Flow</a></p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://fidelgonzalezphotography.com/">Fidel Gonzalez</a></p>
<p>
	FASHION EDITOR<br />
	Derric Lowe</p>
<p>
	GROOMING<br />
	Edwin Candalaria<br />
	&amp; Melissa Walsh<br />
	at <a href="http://cloutierremix.com/">Cloutier Remix</a><br />
	using Dermalogica</p>
<p>
	POST PRODUCTION<br />
	Kri3X</p>
<p>
	MODELS<br />
	Scott Gardner<br />
	at <a href="http://www.wilhelmina.com/">Wilhelmina</a><br />
	Kenny Sale<br />
	at <a href="http://www.ntatalent.com/">NTA</a></p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '38756',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow2.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '602909',
        'status' => '1',
        'timestamp' => '1438195048',
        'origname' => 'WEAR ABOUT -Perspective Flow2.jpg',
      ),
      '1' => array(
        'fid' => '38757',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow3.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '523827',
        'status' => '1',
        'timestamp' => '1438195074',
        'origname' => 'WEAR ABOUT -Perspective Flow3.jpg',
      ),
      '2' => array(
        'fid' => '38759',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow4.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '567351',
        'status' => '1',
        'timestamp' => '1438195088',
        'origname' => 'WEAR ABOUT -Perspective Flow4.jpg',
      ),
      '3' => array(
        'fid' => '38761',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow5.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '673829',
        'status' => '1',
        'timestamp' => '1438195098',
        'origname' => 'WEAR ABOUT -Perspective Flow5.jpg',
      ),
      '4' => array(
        'fid' => '38763',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow6.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '346556',
        'status' => '1',
        'timestamp' => '1438195107',
        'origname' => 'WEAR ABOUT -Perspective Flow6.jpg',
      ),
      '5' => array(
        'fid' => '38765',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow7.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '606410',
        'status' => '1',
        'timestamp' => '1438195116',
        'origname' => 'WEAR ABOUT -Perspective Flow7.jpg',
      ),
      '6' => array(
        'fid' => '38767',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow8.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '606852',
        'status' => '1',
        'timestamp' => '1438195124',
        'origname' => 'WEAR ABOUT -Perspective Flow8.jpg',
      ),
      '7' => array(
        'fid' => '38769',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow9.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '572644',
        'status' => '1',
        'timestamp' => '1438195132',
        'origname' => 'WEAR ABOUT -Perspective Flow9.jpg',
      ),
      '8' => array(
        'fid' => '38791',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow10.jpg',
        'filepath' => 'files/fmag_story/2015/Aug/WEAR ABOUT -Perspective Flow10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '103708',
        'status' => '1',
        'timestamp' => '1439576146',
        'origname' => 'WEAR ABOUT -Perspective Flow10.jpg',
      ),
      '9' => array(
        'fid' => '38773',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow11.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '576044',
        'status' => '1',
        'timestamp' => '1438195158',
        'origname' => 'WEAR ABOUT -Perspective Flow11.jpg',
      ),
      '10' => array(
        'fid' => '38775',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow12.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '530534',
        'status' => '1',
        'timestamp' => '1438195248',
        'origname' => 'WEAR ABOUT -Perspective Flow12.jpg',
      ),
      '11' => array(
        'fid' => '38777',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow13.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '611623',
        'status' => '1',
        'timestamp' => '1438195256',
        'origname' => 'WEAR ABOUT -Perspective Flow13.jpg',
      ),
      '12' => array(
        'fid' => '38779',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow14.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '637480',
        'status' => '1',
        'timestamp' => '1438195265',
        'origname' => 'WEAR ABOUT -Perspective Flow14.jpg',
      ),
      '13' => array(
        'fid' => '38781',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow15.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '767138',
        'status' => '1',
        'timestamp' => '1438195274',
        'origname' => 'WEAR ABOUT -Perspective Flow15.jpg',
      ),
      '14' => array(
        'fid' => '38783',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow16.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '621855',
        'status' => '1',
        'timestamp' => '1438195282',
        'origname' => 'WEAR ABOUT -Perspective Flow16.jpg',
      ),
      '15' => array(
        'fid' => '38785',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow17.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '679077',
        'status' => '1',
        'timestamp' => '1438195290',
        'origname' => 'WEAR ABOUT -Perspective Flow17.jpg',
      ),
      '16' => array(
        'fid' => '38787',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow18.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '668135',
        'status' => '1',
        'timestamp' => '1438195298',
        'origname' => 'WEAR ABOUT -Perspective Flow18.jpg',
      ),
      '17' => array(
        'fid' => '38788',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'WEAR ABOUT -Perspective Flow19.jpg',
        'filepath' => 'files/fmag_story/2015/Jul/WEAR ABOUT -Perspective Flow19.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '155588',
        'status' => '1',
        'timestamp' => '1438195305',
        'origname' => 'WEAR ABOUT -Perspective Flow19.jpg',
      ),
    ),
    'path' => 'stories/wear-about-prospective-flow',
    'tags' => NULL,
    'taxonomy' => array(),
    'files' => array(),
    'page_title' => '',
    'uuid' => 'b89e61fe-5d68-11e5-9f74-8e17caaf1146',
    'is_new' => FALSE,
    'timestamp' => 1442514006,
    'xmlsitemap' => array(
      'id' => '5237',
      'type' => 'node',
      'subtype' => 'fmag_story',
      'loc' => 'node/5237',
      'language' => '',
      'access' => TRUE,
      'status' => '1',
      'status_override' => '0',
      'lastmod' => '1442514006',
      'priority' => '0.5',
      'priority_override' => '0',
      'changefreq' => 0,
      'changecount' => 0,
      'status_default' => '1',
      'priority_default' => '0.5',
    ),
    'uri' => array(
      'path' => 'node/5237',
      'options' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
