array(
  array(
    'nid' => '5520',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1476723438',
    'changed' => '1478472316',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5520',
    'revision_uid' => '0',
    'title' => 'Wear About Paul Kaufman',
    'body' => '<p>
	Fashion talk with footwear designer <a href="http://www.pskaufman.com/">Paul Kaufman</a>.<br />
	Exclusive photography by <a href="http://fidelgonzalezphotography.com/">Fidel Gonzalez</a>.<br />
	Modles. Constance Nunes &amp; Tyler James at <a href="http://www.ntamodels.com/">NTA</a></p>
',
    'teaser' => '<p>
	Fashion talk with footwear designer <a href="http://www.pskaufman.com/">Paul Kaufman</a>.<br />
	Exclusive photography by <a href="http://fidelgonzalezphotography.com/">Fidel Gonzalez</a>.<br />
	Modles. Constance Nunes &amp; Tyler James at <a href="http://www.ntamodels.com/">NTA</a></p>
',
    'log' => '',
    'revision_timestamp' => '1478472316',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Footwear designer <a href="http://Designer Coco Johnsen. Photography by Fidel Gonzalez.">Paul Kaufman</a>. Photography by <a href="http://fidelgonzalezphotography.com/">Fidel Gonzalez</a>.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<p>
	<a href="http://Designer Coco Johnsen. Photography by Fidel Gonzalez.">PSKAUFMAN</a></p>
<p>
	&nbsp;</p>
<p>
	PHOTOGRAPHY<br />
	<a href="http://fidelgonzalezphotography.com/">Fidel Gonzalez</a></p>
<p>
	&nbsp;</p>
<p>
	<a href="http://fidelgonzalezphotography.com/">CREATIVE<br />
	Derric Lowe</a></p>
<p>
	&nbsp;</p>
<p>
	HAIR<br />
	Michael Harris</p>
<p>
	&nbsp;</p>
<p>
	MAKEUP<br />
	Ray Gonzalez</p>
<p>
	&nbsp;</p>
<p>
	MANICURIST<br />
	Shirlee Ann Kerr</p>
<p>
	&nbsp;</p>
<p>
	MODELS</p>
<p>
	Constance Nunes<br />
	Tyler James<br />
	at <a href="http://www.ntamodels.com/">NTA</a></p>
<p>
	<br />
	<br />
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '44142',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes2.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '571018',
        'status' => '1',
        'timestamp' => '1476723248',
        'origname' => 'Paul-S-Kaufman-shoes2.jpg',
      ),
      '1' => array(
        'fid' => '44143',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes3.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '683877',
        'status' => '1',
        'timestamp' => '1476723256',
        'origname' => 'Paul-S-Kaufman-shoes3.jpg',
      ),
      '2' => array(
        'fid' => '44144',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes4.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '740823',
        'status' => '1',
        'timestamp' => '1476723264',
        'origname' => 'Paul-S-Kaufman-shoes4.jpg',
      ),
      '3' => array(
        'fid' => '44145',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes5.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '139329',
        'status' => '1',
        'timestamp' => '1476723274',
        'origname' => 'Paul-S-Kaufman-shoes5.jpg',
      ),
      '4' => array(
        'fid' => '44146',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes6.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '222441',
        'status' => '1',
        'timestamp' => '1476723281',
        'origname' => 'Paul-S-Kaufman-shoes6.jpg',
      ),
      '5' => array(
        'fid' => '44147',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes7.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '677495',
        'status' => '1',
        'timestamp' => '1476723289',
        'origname' => 'Paul-S-Kaufman-shoes7.jpg',
      ),
      '6' => array(
        'fid' => '44148',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes8.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '849730',
        'status' => '1',
        'timestamp' => '1476723301',
        'origname' => 'Paul-S-Kaufman-shoes8.jpg',
      ),
      '7' => array(
        'fid' => '44149',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes9.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '257837',
        'status' => '1',
        'timestamp' => '1476723309',
        'origname' => 'Paul-S-Kaufman-shoes9.jpg',
      ),
      '8' => array(
        'fid' => '44150',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes10.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '495786',
        'status' => '1',
        'timestamp' => '1476723316',
        'origname' => 'Paul-S-Kaufman-shoes10.jpg',
      ),
      '9' => array(
        'fid' => '44151',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes11.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '608236',
        'status' => '1',
        'timestamp' => '1476723323',
        'origname' => 'Paul-S-Kaufman-shoes11.jpg',
      ),
      '10' => array(
        'fid' => '44165',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes12.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '558066',
        'status' => '1',
        'timestamp' => '1476723536',
        'origname' => 'Paul-S-Kaufman-shoes12.jpg',
      ),
      '11' => array(
        'fid' => '44152',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes13.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '487573',
        'status' => '1',
        'timestamp' => '1476723331',
        'origname' => 'Paul-S-Kaufman-shoes13.jpg',
      ),
      '12' => array(
        'fid' => '44153',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes14.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '701757',
        'status' => '1',
        'timestamp' => '1476723339',
        'origname' => 'Paul-S-Kaufman-shoes14.jpg',
      ),
      '13' => array(
        'fid' => '44154',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes15.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '759965',
        'status' => '1',
        'timestamp' => '1476723347',
        'origname' => 'Paul-S-Kaufman-shoes15.jpg',
      ),
      '14' => array(
        'fid' => '44155',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes16.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '232438',
        'status' => '1',
        'timestamp' => '1476723354',
        'origname' => 'Paul-S-Kaufman-shoes16.jpg',
      ),
      '15' => array(
        'fid' => '44156',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes17.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '605649',
        'status' => '1',
        'timestamp' => '1476723362',
        'origname' => 'Paul-S-Kaufman-shoes17.jpg',
      ),
      '16' => array(
        'fid' => '44157',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes18.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '672057',
        'status' => '1',
        'timestamp' => '1476723371',
        'origname' => 'Paul-S-Kaufman-shoes18.jpg',
      ),
      '17' => array(
        'fid' => '44158',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes19.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes19.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '700303',
        'status' => '1',
        'timestamp' => '1476723379',
        'origname' => 'Paul-S-Kaufman-shoes19.jpg',
      ),
      '18' => array(
        'fid' => '44159',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes20.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes20.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '540634',
        'status' => '1',
        'timestamp' => '1476723387',
        'origname' => 'Paul-S-Kaufman-shoes20.jpg',
      ),
      '19' => array(
        'fid' => '44160',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes21.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes21.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '572386',
        'status' => '1',
        'timestamp' => '1476723395',
        'origname' => 'Paul-S-Kaufman-shoes21.jpg',
      ),
      '20' => array(
        'fid' => '44161',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes22.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes22.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '479428',
        'status' => '1',
        'timestamp' => '1476723404',
        'origname' => 'Paul-S-Kaufman-shoes22.jpg',
      ),
      '21' => array(
        'fid' => '44162',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes23.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes23.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '452330',
        'status' => '1',
        'timestamp' => '1476723412',
        'origname' => 'Paul-S-Kaufman-shoes23.jpg',
      ),
      '22' => array(
        'fid' => '44163',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes24.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes24.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '253668',
        'status' => '1',
        'timestamp' => '1476723419',
        'origname' => 'Paul-S-Kaufman-shoes24.jpg',
      ),
      '23' => array(
        'fid' => '44164',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'Paul-S-Kaufman-shoes25.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/Paul-S-Kaufman-shoes25.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '688249',
        'status' => '1',
        'timestamp' => '1476723427',
        'origname' => 'Paul-S-Kaufman-shoes25.jpg',
      ),
    ),
    'path' => 'stories/wear-about-paul-kaufman',
    'tags' => array(
      '4' => array(
        '2181' => array(
          'tid' => '2181',
          'vid' => '4',
          'name' => 'fidel gonzalez',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2053' => array(
          'tid' => '2053',
          'vid' => '4',
          'name' => 'men',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2302' => array(
          'tid' => '2302',
          'vid' => '4',
          'name' => 'menswear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2056' => array(
          'tid' => '2056',
          'vid' => '4',
          'name' => 'women',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
        '2882' => array(
          'tid' => '2882',
          'vid' => '4',
          'name' => 'womenswear',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => NULL,
          '#_export_node_encode_object' => '1',
        ),
      ),
      '1' => array(
        '3549' => array(
          'tid' => '3549',
          'vid' => '1',
          'name' => 'PSkaufman',
          'description' => '',
          'weight' => '0',
          'v_weight_unused' => '0',
          'fields' => FALSE,
          '#_export_node_encode_object' => '1',
        ),
      ),
    ),
    'taxonomy' => array(
      'tags' => array(
        '4' => 'fidel gonzalez, men, menswear, women, womenswear',
        '1' => 'PSkaufman',
      ),
    ),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
