array(
  array(
    'nid' => '5529',
    'type' => 'fmag_story',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1477934083',
    'changed' => '1478472327',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '5529',
    'revision_uid' => '0',
    'title' => 'The Style Guys',
    'body' => '<p>
	We essay influencers of style extraordinaire.<br />
	Exclusive photography by <a href="http://www.allenzaki.com/">Allen Zaki</a>.<br />
	&nbsp;</p>
',
    'teaser' => '<p>
	We essay influencers of style extraordinaire.<br />
	Exclusive photography by <a href="http://www.allenzaki.com/">Allen Zaki</a>.<br />
	&nbsp;</p>
',
    'log' => '',
    'revision_timestamp' => '1478472327',
    'format' => '1',
    'name' => 'fantasticsmag',
    'picture' => 'files/userpics/picture-1.jpg',
    'data' => 'a:2:{s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
    'field_description' => array(
      '0' => array(
        'value' => '<p>
	Photographer <a href="http://www.allenzaki.com/">Allen Zaki</a> shoots guy-style influencers we love.</p>
',
        'format' => '1',
      ),
    ),
    'field_sidebar' => array(
      '0' => array(
        'value' => '<div style="font-size:0.9em;">
	<p>INFLUENCERS.</p>
	<p>
		PERKENS BIEN AIME<br />
		<a href="https://www.instagram.com/perkensbienaime/?hl=en">@perkensbienaime</a><br />
		<a href="http://www.garconalamode.com/">Garcon A La Mode</a></p>
	<p>
		DANIEL BETANCOURT<a href="http://www.instagram.com/danielbetan/"><br />
		@danielbetan</a><a href="http://www.betanstyle.com"><br />
		Betanstyle</a></p>
	<p>
		GEORGE D<br />
		<a href="https://www.instagram.com/atlasandmason/">@atlas&amp;mason</a><br />
		<a href="https://www.instagram.com/gentslounge/">@gentslounge</a><br />
		<a href="http://gentslounge.com/">Gents Lounge</a></p>
	<p>
		STEVE GALINDO<br />
		<a href="https://www.instagram.com/bloggerbeaux/">@bloggerbeaux</a><br />
		<a href="http://The Blogger Beaux">The Blogger Beaux</a></p>
	<p>
		TOMMY LEI<br />
		<a href="https://www.instagram.com/mybelonging/?hl=en">@mybelonging</a><br />
		<a href="http://www.mybelonging.com/">My Belonging</a></p>
	<p>
		STEPHEN OSCAR<br />
		<a href="https://www.instagram.com/thestephenoscar/?hl=en">@thestephenoscar</a><br />
		<a href="https://www.youtube.com/channel/UC-_9WVqOn5NNkm2uyt2mQ_Q">Stepehn Oscar at YouTube</a></p>
	<p>
		JET PRESLEY<br />
		<a href="https://www.instagram.com/imskinnyrich/">@imskinnyrich</a><br />
		<a href="https://www.youtube.com/channel/UCJAQCb9JaILTA1bn-AbnH-A">Jet Presley at YouTube</a></p>
	<p>
		PARKER YORK SMITH<br />
		<a href="https://www.instagram.com/parkeryorksmith/?hl=en">@parkeryorksmith</a><br />
		<a href="http://www.thelooksmith.com/">The Looksmith</a></p>
	<p>
		CHRISTOPHER YOUNGBLOOD<br />
		<a href="http://www.ceayoungblood.com/">CEA Youngblood</a></p>
	<p>
		&nbsp;</p>
	<p>
		PHOTOGRAPHY<br />
		<a href="http://www.allenzaki.com/">Allen Zaki</a>.<br />
</p>
	<p>
		PRODUCER<br />
		Steve Galindo<br />
		&nbsp;</p>
	<p>
		GROOMING<br />
		Leon Klima<br />
		Yolanda Price</p>
	<p>
		LOCATIONS<br />
		US Alteration<br />
		Media Playground PR<br /> 
at The Park Creative<br />
		&nbsp;</p>
</div>',
      ),
    ),
    'field_contributor' => array(
      '0' => array(
        'uid' => NULL,
      ),
    ),
    'field_page' => array(
      '0' => array(
        'fid' => '44240',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers2.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '474330',
        'status' => '1',
        'timestamp' => '1477933802',
        'origname' => 'zaki_influencers2.jpg',
      ),
      '1' => array(
        'fid' => '44241',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers3.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '131892',
        'status' => '1',
        'timestamp' => '1477933809',
        'origname' => 'zaki_influencers3.jpg',
      ),
      '2' => array(
        'fid' => '44280',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers4.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '197398',
        'status' => '1',
        'timestamp' => '1478272669',
        'origname' => 'zaki_influencers4.jpg',
      ),
      '3' => array(
        'fid' => '44243',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers5.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '419276',
        'status' => '1',
        'timestamp' => '1477933822',
        'origname' => 'zaki_influencers5.jpg',
      ),
      '4' => array(
        'fid' => '44244',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers6.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '315549',
        'status' => '1',
        'timestamp' => '1477933828',
        'origname' => 'zaki_influencers6.jpg',
      ),
      '5' => array(
        'fid' => '44245',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers7.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '127993',
        'status' => '1',
        'timestamp' => '1477933834',
        'origname' => 'zaki_influencers7.jpg',
      ),
      '6' => array(
        'fid' => '44246',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers8.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93813',
        'status' => '1',
        'timestamp' => '1477933840',
        'origname' => 'zaki_influencers8.jpg',
      ),
      '7' => array(
        'fid' => '44247',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers9.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers9.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '309749',
        'status' => '1',
        'timestamp' => '1477933846',
        'origname' => 'zaki_influencers9.jpg',
      ),
      '8' => array(
        'fid' => '44248',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers10.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers10.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '136741',
        'status' => '1',
        'timestamp' => '1477933852',
        'origname' => 'zaki_influencers10.jpg',
      ),
      '9' => array(
        'fid' => '44249',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers11.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers11.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '408310',
        'status' => '1',
        'timestamp' => '1477933858',
        'origname' => 'zaki_influencers11.jpg',
      ),
      '10' => array(
        'fid' => '44250',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers12.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers12.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '396408',
        'status' => '1',
        'timestamp' => '1477933865',
        'origname' => 'zaki_influencers12.jpg',
      ),
      '11' => array(
        'fid' => '44251',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers13.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers13.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '92244',
        'status' => '1',
        'timestamp' => '1477933871',
        'origname' => 'zaki_influencers13.jpg',
      ),
      '12' => array(
        'fid' => '44252',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers14.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers14.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '322513',
        'status' => '1',
        'timestamp' => '1477933877',
        'origname' => 'zaki_influencers14.jpg',
      ),
      '13' => array(
        'fid' => '44279',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers15.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers15.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '146672',
        'status' => '1',
        'timestamp' => '1477934566',
        'origname' => 'zaki_influencers15.jpg',
      ),
      '14' => array(
        'fid' => '44254',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers16.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers16.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '344093',
        'status' => '1',
        'timestamp' => '1477933893',
        'origname' => 'zaki_influencers16.jpg',
      ),
      '15' => array(
        'fid' => '44255',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers17.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers17.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '93676',
        'status' => '1',
        'timestamp' => '1477933899',
        'origname' => 'zaki_influencers17.jpg',
      ),
      '16' => array(
        'fid' => '44256',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers18.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers18.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '146390',
        'status' => '1',
        'timestamp' => '1477933906',
        'origname' => 'zaki_influencers18.jpg',
      ),
      '17' => array(
        'fid' => '44257',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers19.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers19.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '282367',
        'status' => '1',
        'timestamp' => '1477933914',
        'origname' => 'zaki_influencers19.jpg',
      ),
      '18' => array(
        'fid' => '44258',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers20.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers20.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '388532',
        'status' => '1',
        'timestamp' => '1477933921',
        'origname' => 'zaki_influencers20.jpg',
      ),
      '19' => array(
        'fid' => '44259',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers21.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers21.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '125359',
        'status' => '1',
        'timestamp' => '1477933928',
        'origname' => 'zaki_influencers21.jpg',
      ),
      '20' => array(
        'fid' => '44260',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers22.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers22.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '130000',
        'status' => '1',
        'timestamp' => '1477933934',
        'origname' => 'zaki_influencers22.jpg',
      ),
      '21' => array(
        'fid' => '44261',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers23.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers23.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '416158',
        'status' => '1',
        'timestamp' => '1477933941',
        'origname' => 'zaki_influencers23.jpg',
      ),
      '22' => array(
        'fid' => '44262',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers24.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers24.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '375443',
        'status' => '1',
        'timestamp' => '1477933949',
        'origname' => 'zaki_influencers24.jpg',
      ),
      '23' => array(
        'fid' => '44263',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers25.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers25.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '75795',
        'status' => '1',
        'timestamp' => '1477933956',
        'origname' => 'zaki_influencers25.jpg',
      ),
      '24' => array(
        'fid' => '44264',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers26.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers26.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '171009',
        'status' => '1',
        'timestamp' => '1477933963',
        'origname' => 'zaki_influencers26.jpg',
      ),
      '25' => array(
        'fid' => '44265',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers27.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers27.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '412548',
        'status' => '1',
        'timestamp' => '1477933969',
        'origname' => 'zaki_influencers27.jpg',
      ),
      '26' => array(
        'fid' => '44266',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers28.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers28.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '321165',
        'status' => '1',
        'timestamp' => '1477933979',
        'origname' => 'zaki_influencers28.jpg',
      ),
      '27' => array(
        'fid' => '44267',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers29.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers29.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '90746',
        'status' => '1',
        'timestamp' => '1477933986',
        'origname' => 'zaki_influencers29.jpg',
      ),
      '28' => array(
        'fid' => '44268',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers30.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers30.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '167132',
        'status' => '1',
        'timestamp' => '1477933993',
        'origname' => 'zaki_influencers30.jpg',
      ),
      '29' => array(
        'fid' => '44269',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers31.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers31.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '392683',
        'status' => '1',
        'timestamp' => '1477934000',
        'origname' => 'zaki_influencers31.jpg',
      ),
      '30' => array(
        'fid' => '44270',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers32.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers32.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '407731',
        'status' => '1',
        'timestamp' => '1477934007',
        'origname' => 'zaki_influencers32.jpg',
      ),
      '31' => array(
        'fid' => '44271',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers33.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers33.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '87314',
        'status' => '1',
        'timestamp' => '1477934016',
        'origname' => 'zaki_influencers33.jpg',
      ),
      '32' => array(
        'fid' => '44272',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers34.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers34.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '142087',
        'status' => '1',
        'timestamp' => '1477934024',
        'origname' => 'zaki_influencers34.jpg',
      ),
      '33' => array(
        'fid' => '44275',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers35.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers35.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '403239',
        'status' => '1',
        'timestamp' => '1477934068',
        'origname' => 'zaki_influencers35.jpg',
      ),
      '34' => array(
        'fid' => '44273',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers36.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers36.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '392762',
        'status' => '1',
        'timestamp' => '1477934032',
        'origname' => 'zaki_influencers36.jpg',
      ),
      '35' => array(
        'fid' => '44274',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
        'uid' => '1',
        'filename' => 'zaki_influencers37.jpg',
        'filepath' => 'files/fmag_story/2016/Oct/zaki_influencers37.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '102706',
        'status' => '1',
        'timestamp' => '1477934047',
        'origname' => 'zaki_influencers37.jpg',
      ),
    ),
    'path' => 'stories/style-guys',
    'tags' => NULL,
    'taxonomy' => array(),
    'files' => array(),
    'page_title' => '',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'navigation',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
